By
Charles Sale

Follow @@charliesale

Manchester City’s long-serving administrator Bernard Halford involved the FA council in their own sexist comment moment in the wake of the Richard Scudamore controversy.

City life president Halford, the club secretary for four decades, was speaking about the decline of schools football at the council summit this week in response to FA chairman Greg Dyke’s England Commission presentation.

Halford caused a stir in the room by effectively blaming the increase in women teachers for the chronic problems facing schools football.

Row: Man City administrator Bernard Halford, pictured with Pablo Zabaleta, involved the FA in their own sexist comment moment this week

Halford, 
who represents the Manchester county FA on the council, said words to 
the effect that women teachers had greatly improved the education in 
schools but not necessarily in terms of football.

His
 ill-timed remark - albeit supported by some dinosaur council members - 
comes in the week Helena Costa became the first female  professional 
football coach in a major league after taking charge of French 
second-tier side Clermont Foot.

The FA declined to comment.

.............................................................................

Premier
 League clubs unanimously backed chief executive Richard Scudamore in 
the sexism scandal. But there is a desire among them for their next 
chairman to be from outside football if Anthony Fry, making good 
progress following serious illness, is unable to return. 

A
 group of Premier League chairmen and chief executives informally 
discussing the big issues during a lunch at Scott’s in London’s Mayfair 
ahead of their summer meeting were joined by one former club owner - a 
certain Sir Elton John. Everton chairman and theatre tycoon Bill 
Kenwright bumped into the former Watford owner, who was on 
another table, and invited him over.

Support: Premier League clubs have backed chief executive Richard Scudamore in the sexism scandal

In attendance: Sir Elton John, former owner of Watford, joined Premier League chairmen at a lunch in Mayfair

There
 have been numerous glitches in the Lawn Tennis Association’s new 
computer system being rolled out after two years of trials to deal with 
Wimbledon ballot tickets at all LTA clubs, including losing personal 
information. An LTA spokeswoman said the initiative to give full 
transparency to the club ballot process had been well received and there
 were bound to be hiccups.

KP’s food for thought

Cricket
 fans willing to pay £2,000 for a table of 10 will be first to hear 
Kevin Pietersen’s version of his England divorce. MBN Promotions are 
staging the lunch - hosted by John Inverdale - at the Savoy for KP to 
tell all on October 16.

MBN say: ‘We hear from the man himself exactly what went wrong last winter and how relationships deteriorated so badly.’

Pietersen
 will have a column in a national newspaper from June 1, but his ECB 
confidentiality agreement will prevent him revealing too much. The 
agreement expires in September.

Two sides to every story: Cricket fans can pay to hear Kevin Pietersen's version of his England divorce

FIFA
 have defended president Sepp Blatter’s unilateral spending of an 
alleged £16m on the film United Passions, charting the history of world 
football’s ruling body.

Zurich say they have been considering such a 
proposal since 2004 and ‘agreed to contribute financially’ to the 
Leuviah Films production ‘as we considered this to be a unique 
opportunity to raise awareness. It was approved by relevant FIFA 
committees with the investment coming from the current budget.’

FIFA 
hope to recoup the money from revenue generated by the film - optimistic
 in the extreme.

Retired
 wine merchant Lionel Frumkin, who lives next to the proposed new 
entrance at Lord’s, was leading the complaints to Westminster Council 
about the MCC design.

However, Lord’s tour guide Frumkin withdrew his protest when MCC paid £8m - well above the market value - to buy his house.

An MCC spokesman said it was club policy to acquire properties adjacent to the ground.

Such
 is the hypocrisy around the Premier League that title sponsors 
Barclays, who were reported to be ‘deeply disappointed’ in Premier 
League chief executive Scudamore’s sexist emails, have had to set aside 
£678.43m since 2008 to cover fines for a variety of far more fraudulent 
and serious misdemeanours than Scudamore’s.

@highlight

Man City's life president Bernard Halford involved FA council in sexism row

@highlight

Halford effectively blamed increase in women teachers for problems facing schools football

@highlight

Premier League clubs unanimously back chief executive Richard Scudamore in sexism scandal

@highlight

Cricket fans can £2,000 for a table to hear Kevin Pietersen's version of his England divorce