By 
Matt Chorley, Mailonline Political Editor

PUBLISHED:

02:50 EST, 11 September 2013


| 

UPDATED:

06:43 EST, 11 September 2013

Swipe: Business Secretary Vince Cable is striking a more downbeat tone than the Chancellor

Vince Cable is to rebuke George Osborne for ‘complacency’ over Britain's economic recovery.

Amid renewed tensions between the two men, the Business Secretary warned the Chancellor that ministers ‘can't rest on our laurels’.

Mr Cable struck a distinctly gloomy tone in contrast to Mr Osborne’s assertion this week that the economy was finally ‘turning a corner’.

Lib Dem Mr Cable will use a speech tonight to say that ‘a few quarters of good economic data’ did not mean the country was out of the woods.

Instead he argues that while there are the ‘beginnings of a recovery story’, it would not become ‘meaningful’ until there was strong and sustained business investment, which remained well down on pre-crash levels.

There also appears to be a Cabinet split over efforts to revive the hosuing market.

Mr Osborne has also called for more 95 per cent loan-to-value mortgages which he insisted were not ‘weapons of financial mass destruction’

But Mr Cable warned of the risks of the housing market ‘getting out of control’. In his address to a joint Government/CBI industrial strategy conference at Warwick University, the Business Secretary will say that while there were ‘encouraging’ signs for the economy, there was still further to go.

‘We can't rest on our laurels. The kind of growth we want won't simply emerge of its own volition. In fact, I see a number of dangers. One is complacency, generated by a few quarters of good economic data,’ he will say.

‘It isn't difficult to see evidence of confidence returning, and there are positive trends in production. Taken together with success stories like the car industry and export growth in emerging markets, we have the beginnings of a recovery story.

‘But there are risks, not least the housing market getting out of control. Recovery will not be meaningful until we see strong and sustained business investment - and this is still 13% down on its 2008 peak and, as a share of GDP, is currently the lowest in the G7.’

Upbeat: George Osborne used a speech this week to declare that the British economy is 'turning a corner'

Mr Cable will stress that the 
improving economic news did not mean that the need for long-term 
re-structuring and re-balancing could be forgotten.

‘If we are to turn the British economy
around on a sustainable basis there will have to be relatively rapid 
growth of exports and import substitutes,’ he will say.

It is a markedly different tone to Mr
Osborne, who yesterday ridiculed Labour opponent Ed Balls for refusing 
to admit defeat on the big economic arguments.

Shadow chancellor Ed Balls has accused Mr Osborne of choking off the economic recovery

Mr Balls was likened to Monty Python’s Black Knight who brushes off losing both arms as ‘just a flesh wound’.

Mr Osborne said: ‘He is increasingly like Monty Python’s Black Knight defending that bridge.

‘When unemployment falls he says it’s 
but a scratch, when business confidence rises he says I’ve had worse, 
the recovery is just a flesh wound.

‘The limbs are falling off his 
economic argument and it would be a comedy if it were not for the fact 
Labour’s economic policies were a tragedy.’

The government has been bolstered by a
run of positive data which suggests the economy is on course for a 
sustained recovery in the run-up to the next election. The respected 
OECD think tank last week upgraded its growth forecast.

It now expects the UK economy to expand by 1.5 per cent in 2013, up from its prediction of 0.8 per cent issued in May.

But Labour’s shadow business secretary Chuka Umunna said Mr Cable had delivered an ‘embarrassing slap-down’ to Mr Osborne.

However, he insisted that the Lib Dems could not distance themselves from the Chancellor 's economic strategy.

‘It also reminds everyone that you 
can't trust a word the Lib Dems say. Vince Cable has supported the 
Chancellor's policies which choked off the recovery in 2010,’ he said.

‘Three wasted years of flatlining that
has left families worse off and done long term damage to our economy is
his record and he should take responsibility for it.’

@highlight

Downbeat Business Secretary warns against 'resting on our laurels'

@highlight

Upbeat Chancellor declared economy is 'turning a corner'

@highlight

Ridiculed opponents of his economic for refusing to admit defeat

@highlight

Osborne likened Ed Balls to Monty Python's Black Knight