By
John Hall

A property developer is offering buyers the chance to own a flat in London and a holiday home in Newquay for a total of just £325,000 in a special 'surf and turf' package.

Galliard Homes launched the scheme this morning to capitalise on the £120million-a-year UK surfing market, much of which centres on the Cornwall coast - particularly Fistral Beach in Newquay.

Now, for a total of £50,000 less than the price average London home, buyers who purchase a brand new one-bedroom apartment in Lewisham will get lodge overlooking Fistral Beach for free.

Surf: Dubbed Pebble Beach village, the Newquay site will have an large artificial surf wave machine and swimming pool and will be just a few yards from the famous Fistral Beach

Turf: The London apartments are in a brand new development in Lewisham, south east London. The area has seen major regeneration in recent years

Popular: Newquay is the centre Britain's surf industry - with Fistral Beach (pictured) considered one of the best places to ride the waves in northern Europe

The Lewisham apartments are in a brand new development, while Galliard Homes plans to build around 100 glass-fronted studios around a series of lakes and waterways on the Newquay seafront.

Dubbed Pebble Beach village, the site will have an large artificial surf wave machine and swimming pool and will be just a few yards from the famous Fistral Beach.

The 100-property development will also boast a spa, health club, gym, nine hole golf course, tennis courts and restaurant.

The flats, which measure up to 506 square foot, will also have a large timber floored reception room with wall mounted flat screen TV and floor to ceiling glazing opening onto an outside leisure deck.

Close to the city: The Lewisham apartments are in a brand new development (pictured) owned by property developer Galliard Homes

Great location: A surfer experiences the huge waves off the coast of Fistral beach in Cornwall

Large: The kitchen area of the so-called 'surfers suite' at the Pebble Beach development in Newquay, Cornwall

Fun: The huge artificial surf machine at Pebble Beach Village development

Much of Newquay's multi-million pound surfing industry centres on Fistral Beach. In summer the town's population can swell to 100,000

David Galman, sales director at Galliard Homes, said: 'Some of our metropolitan buyers love surfing, sailing, swimming, water sports and the outdoors, and it is something they miss living in London.'

'This is why we have launched our surf and turf offer, which for as little as £324,950 enables them to buy two homes in one deal and have a London home and a surfer’s suite at our Pebble Beach village.'

It is estimated that buyers purchasing the so-called 'surf suites' as a rental investment would recieve a return of up to six per cent for five years.

Fistral Beach is in Fistral Bay on the north coast of Cornwall - roughly half-a-mile west of Newquay.

Its sandy beach faces the Atlantic and is backed by steep sand dunes.

Lewisham
 is a major inner-city district in South East London that has seen a 
number of major regeneration projects in recent years.

Well-equipped: The 100-property development will also boast a spa, health club, gym (pictured), nine hole golf course, tennis courts and restaurant

Luxury: The flats, which measure up to 506 square foot, will have a large timber floored reception room

Profit: It is estimated that buyers purchasing the so-called 'surf suites' in Newquay with the intention of renting them out would recieve a return of up to six per cent for five years

Getting around: With a local population of about 284,000, the Lewisham development is in a bustling area popular with commuters. Lewisham is considered to be one of south London's major transport hubs

Each of the flats on the 100-property development in Newquay will come with a luxury bathroom suite showcasing extensive marble features

The properties on sale couldn't be in more different locations - Lewisham is an inner-city district of south east London, while Newquay is a small town and fishing port in Cornwall.

With its population of about 284,000, Lewisham is a bustling area popular with commuters and is considered to be one of south London's major transport hubs.

Newquay, on the other hand, has a permanent population of just 19,500, with much of its income generated by the multi-million pound surfing industry.

Despite their obvious differences, Newquay is hardly unfamiliar with the hustle and bustle that residents of Lewisham have grown so used to.

In summer months, the town's population can swell to around 100,000 people, as tourists, many of them teenagers, arrive on mass to populate the many holiday rental properties along Newquay's picturesque Atlantic coastline.

Newquay is, of course, the centre Britain's surf industry -  with a reputation as one of the best places to ride the waves in northern Europe.

Sprawling Lewisham has no comparable tourism industry, as it is situated six miles from the centre of London - too far for many international tourists to travel.

The London suburb has experienced major regeneration in recent years, however, with further plans to redevelop the run-down town centre.

@highlight

Developer offers combined sale of Lewisham flats and Cornwall lodges

@highlight

The double property deal totals £50,000 less than average London home

@highlight

Buyers will receive a one-bedroom apartment in south London and a multi-room lodge on the Newquay seafront for their money