By
Ellie Zolfagharifard

PUBLISHED:
  
  
      08:56 EST, 4 December 2013
    
  
 | 
  UPDATED:
  
  
      23:12 EST, 4 December 2013

Despite being 93 million miles from the sun, amateur astronomer Jose Manteca has captured these stunning shots from his back garden.

Mr Manteca, who works as a sales representative, installed a small observatory on the terrace of his house in 2011.

Ever since he has used a humble DSLR camera to capture breathtaking shots - including solar prominences, sunspots and even a plane crossing the face of the sun.

Despite being 93 million miles from the sun, amateur astronomer Jose Manteca has captured this stunning shot of a solar prominence from his back garden

Mr Manteca, 54, from Begues, near Barcelona, Spain, said: 'Capturing solar activity is a challenge. But I am happy because there's always some activity to photograph. It is a show every day and it looks so different each time.

'I learned a technique using my DSLR which helps me capture 15 images per second. It means I now capture 900 images over a few weeks and, later, pick the 100 best.

'Once I honed this technique, it was easy for me to click through my fixed telescope.'

Mr Manteca says he spends hours gazing 
into space, hoping to spot scintillating solar activity. The weather, 
however, is the biggest challenge he faces.

Mr Manteca, who works as a sales representative, installed a small observatory on the terrace of his house in 2011. Ever since he has used a humble DSLR camera to capture these breathtaking shots of solar eruptions

Mr Manteca, 54, from Begues, near Barcelona, Spain, said: 'Capturing solar activity is a challenge. But I am happy because there's always some activity to photograph. It is a show every day and it looks so different each time'. Pictured is a solar prominence

He added: 'The main difficulty is the turbulence. In order to get good solar images, everything has to be very stable. Clouds don't help either.'

Some of Mr Mantec's most amazing images are of solar prominences.

The red-glowing looped material shown in the pictures is plasma, a hot gas comprised of electrically charged hydrogen and helium.

The prominence plasma flows along a tangled and twisted structure of magnetic fields generated by the sun’s internal dynamo.

Hot sunspots dot the surface of the sun, as seen through the telescope captured by Jose Manteca in Begues, near Barcelona

With the sun in the backdrop, Mr Manteca captured a passenger jet forming a subtle silhouette

An erupting prominence occurs when such a structure becomes unstable and bursts outward, releasing the plasma.

Others pictures highlight giant sunspots. Sunspots form from shifting magnetic fields at the sun's surface, and are actually cooler than their surrounding solar material.

Mr Manteca says he now hopes to push his hobby even further - capturing more detailed shots of the sun's intense activity.

Jose Manteca's telescope fixed to a DSLR camera and rest of the equipment seen at his home in Begues, near Barcelona, Spain. Incredibly, the equipment used cost him no more than £2,900

Some of Mr Mantec's most amazing images are of solar prominences. 
The red-glowing material shown in the pictures is plasma, a hot gas comprised of electrically charged hydrogen and helium

'I like photographing solar flares and 
sunspots with maximum detail. Now, I want to see the interiors of the 
sunspots.,' he said.

Incredibly, the equipment used cost him no more than £2,900.

Mr Manteca added: 'I have an achromatic refractor (meade) and solar telescope (lunt). This equipment helped me do all these images.

'My solar equipment is very simple and basic. It costed me no more than 3,500 euros (£2,900). It has worked well for me so far.'

Mr Manteca says he now hopes to push his hobby even further - capturing more detailed shots of the sun's intense activity such as this pictured image of sunspots

Mr Manteca said: 'My solar equipment is very simple and basic. It costed me no more than 3,500 euros (£2,900). It has worked well for me so far'. Pictured is a solar prominence

@highlight

Jose Manteca from Begues, near Barcelona, took the photos from a small observatory on the terrace of his house

@highlight

The 54-year-old says he spends hours on the terrace gazing 
into space, hoping to spot scintillating solar activity

@highlight

He has developed a technique to take 15 images per second using a humble DSLR camera and a solar telescope

@highlight

Images include stunning close-ups of solar prominences, sunspots and even a plane crossing the face of the sun