By
Ian Drury

Lawyers, accountants and financial advisers who turn a blind eye to organised crime will face five years in jail under new laws to be unveiled in the Queen’s Speech.

Hundreds of white-collar professionals who help the most dangerous gangsters evade the law but are not directly involved in crimes will be targeted by police.

They help gangs set up their illegal businesses by writing contracts, arranging property purchases, offering advice or sending funds overseas.

Facing the threat of jail: Hundreds of white-collar professionals who help the most dangerous gangsters evade the law but are not directly involved in crimes will be targeted by police

The crackdown will also tackle ‘Mr Bigs’, such as the Adams family crime syndicate, who often plan and co-ordinate crimes but avoid prosecution because they do not ‘get their hands dirty’.

The wide-ranging overhaul of the law will be laid out in a Serious Crime Bill in the Queen’s Speech.

Similar to America’s anti-mafia laws, the legislation is part of a concerted drive by ministers to land a blow on Britain’s £24billion-a-year organised crime industry.

The Home Office is determined to focus on the corrupt professionals behind the underworld gangs who bring terror to the streets of Britain.

The so-called ‘crooks in suits’ help crime bosses set up their illegal businesses by writing contracts, arranging property purchases, offering advice or sending funds overseas.

But they avoid ending up behind bars by adopting a ‘no questions asked’ approach and then claiming in court they had no idea that they were involved in a crime networks.

Now a new offence of participation in an organised crime group – which includes everything from credit card fraud to cigarette smuggling – will allow police and prosecutors to take action against these individuals.

The authorities will only have to prove there were ‘reasonable grounds’ to suspect an individual knew they were helping carry out wrong-doing.

The measures will also target others who help gangs commit crimes by, for instance, renting warehouse space, hiring vehicles or delivering packages.

Those convicted under the new offence would face up to five years behind bars.

Ministers believe up to 200 people, including professionals such as lawyers and accountants, will go to prison under the laws each year.

'Nobody is above the law': Tory Home Office minister Karen Bradley said the new offence sends out a clear message to professionals helping criminals

The move follows rising concern about crime lords such as David Hunt, an East End businessman known as ‘Long Fella’ whose gang a judge said was involved in fraud, money-laundering and extreme violence, and the Adams family, whose members have been linked to at least 25 murders worldwide, as well as drug trafficking, extortion and hijacking.

Home Office minister Karen Bradley said: ‘Nobody is above the law. But for too long corrupt lawyers, accountants and other professionals have tried to evade justice by hiding behind a veneer of respectability.

‘This new offence sends out a clear message to those individuals - if you are helping to oil the wheels of organised crime, you will be prosecuted and face being jailed.’

Ministers will also beef up powers to prevent ‘Mr Bigs’ holding onto their multi-million pound gains because of flaws in the enforcement system.

The aim is to close loopholes which enable criminals to get round confiscation orders and tackle those who avoid paying.

The shake-up will bolster prosecutors’ ability to freeze assets and introduce prison sentences for offenders who hold onto their illegal profits.

The proposed legislation comes in the wake of a highly critical report by the National Audit Office which warned only 26p in every £100 generated by criminal activity was recovered by the authorities.

Under the changes, criminals who ignore court orders to repay over £10million of illicit gains will lose their right to early release from prison.

Organised crime bosses will be barred from using ‘designer divorces’ to conceal their illegal profits. Assets will be allowed to be frozen earlier in investigations and the maximum time to pay confiscation orders will be increased from six to 12 months.

Some £1.48billion is currently outstanding in unpaid confiscation orders.

One of the worst examples of criminal defiance is convicted fraudster Gerald Smith who still owes taxpayers £57.2million.

Smith, who was jailed in 2006 and is now free, made his illicit fortune from a dotcom swindle and used the money to buy a £3million house overlooking Wentworth golf course, another home in Jersey, a yacht and an art collection.

The oldest outstanding confiscation order is for £300,000 and dates back to 1988.

@highlight

Lawyers and accountants who help gangs will be targeted by new law

@highlight

Legislation to be unveiled in Queen's Speech is similar to anti-Mafia laws

@highlight

Professionals have so far evaded justice by adopting 'don't ask' approach