By
Lizzie Edmonds

PUBLISHED:
  
  
      04:22 EST, 3 November 2013
    
  

 | 
  UPDATED:
  
  
      05:08 EST, 3 November 2013

Appeal: Abdulla Ahmed Ali, mastermind of the 'liquid bomb plot', has appealed to the European Court of Human Rights for his life sentence to be overturned.

The mastermind behind the 'liquid bomb plot', one of the most deadly terrorist plans ever to be unearthed in Britain, is making a bid to have his conviction overturned on human rights grounds.

Abdulla Ahmed Ali developed a home-made hydrogen peroxide bomb that could be disguised as a soft drink and taken on board a plane.

He and a group of associates planned to take the bombs aboard seven flights.

The discovery of his suicide plan in 2006 led to urgent changes to international restrictions on carrying fluids on to planes.

However, the al-Qaeda terrorist now claims his human rights were infringed by publicity before he was convicted for life for conspiracy to murder - and has appealed to the European Court of Human Rights.

He argues that the jury would have been prejudiced by coverage of a previous trial.

Although the Strasbourg court does not hold the power to quash the conviction, it would be extremely problematic for the Government if they ruled in the terrorist's favour.

If Ali wins his case it would allow him and fellow plotters to begin an attempt in British to have their convictions quashed, using the European ruling to convince judges that their convictions were not fair.

Speaking to The Sunday Telegraph, Chris Grayling, the Justice Secretary, said the case highlighted why there was an urgent need for reform to human rights laws.

'Suicide video': Ali and his associates posted a video that boasted of his airline bomb plot, which would have seen the group attempt to smuggle the bombs on to seven flights

He also the case was evidence that the Strasbourg court was increasingly willing to interfere in Britain's justice system.

'This yet a further example of why things cannot go on as they are', he said.

'It is unacceptable to have a situation in which claims to the European Court of Human Rights are actually being used to undermine our justice system.

'Our justice system is one of the best in the world and the Strasbourg court has no business telling us how to run it.'

Although British judges at the Court of Appeal have ruled the case deserve a hearing, 
the European Court has examined Ali's application.

It has 
allowed it through the first stage of consideration for a full hearing, 
according to the Sunday Telegraph.

His case has been adjourned because more information was needed.

Supplies: A picture of several empty bottles found at the group's East London base, that was shown to a jury at Woolwich Crown Court

Appeal: Co-conspirator Tanvir Hussain

Four of Ali's co-conspirators have attempted to take cases to Strasbourg.

However, so far they have all been thrown out.

In three of the cases
 it was because their lawyers made a mistake and missed appeal deadlines.

The fourth case was submitted several months
 late.

The 
applications by Tanvir Hussain, jailed for at least 32 years; Umar 
Islam, jailed for a minimum of 22 years and Ibrahim Savant, jailed for 
at least 20 
years, were ruled inadmissible by the Strasbourg judges.

Representing the men, and responsible for the last appeal papers, were Tuckers 
Solicitors.

Duncan Lewis Solicitors, the lawyers 
for Waheed Zaman, serving a minimum of 20 years, also submitted the 
papers late.

Eight men were convicted for their involvement in the plot to blow up aircraft with liquid bombs after three trials.

The government has now been asked
 by judges in Europe to answer a series of questions about Ali's 
prosecution.

They said they wish to establish whether he had a 'fair trial by an impartial 
tribunal' as required under Article 6 of the European Convention on 
Human Rights.

Ali, now 33, was convicted of
 conspiracy to endanger the safety of an aircraft in his first trial in 
2008.

However, the jury was unable to reach a verdict on a charge of 
conspiracy to murder.

He was therefore re-trialled at Woolwich Crown Court, London, in 
September 2009.

There he was convicted of both charges and 
jailed for life -  with a minimum term of 40 years.

'Adverse publicity' generated by 
the media between his 2008 trial and his retrial a year later is the reason Ali claims his human rights were breached.

During the trials, it was revealed how Ali and a group of associates recorded 'suicide videos' at a flat in Walthamstow, east London.

The videos revealed his plot to bring down 
airliners with bombs smuggled in soft drink containers.

During the footage it was said the was intended to 'teach a lesson' that non-Muslims 'will never forget'.

Ali singled out seven flights to San Francisco, Toronto, Montreal, Washington, New York and Chicago that departed within two-and-a-half hours of each other and said his group would taken the explosives on board.

If successful, the explosions could have exceeded the carnage of the September 11 attacks.

When Ali was arrested he had a computer
 memory stick in his pocket that highlighted seven flights from London 
to North American cities that were each carrying hundreds of passengers 
and crew.

Security sources believed the group were also planning a further attack involving 18 suicide 
bombers which could have killed 5,000 people in the air and the same number on the ground.

At the time it was revealed that the men had gathered enough chemicals to make 20 liquid bombs.

Investigating and prosecuting the 
conspiracy has already cost the taxpayer more than Â£100million and Ali's
 legal challenge will push the bill higher.

 

@highlight

Abdulla Ahmed Ali developed a home-made hydrogen peroxide bomb that could be disguised as a soft drink and taken aboard a plane

@highlight

Mastermind of 'liquid bomb plot' - one of the most deadly plans ever to be discovered in Britain - sentenced to life for conspiracy to murder in 2009

@highlight

Claims publicity before his trial would have prejudiced a jury's decision and has appealed to European Court of Human Rights in Strasbourg

@highlight

Court does not hold power to quash conviction, but a ruling in his favour could lead to a fresh appeal in British courts

@highlight

Judges must establish whether he had a 'fair trial by an impartial 
tribunal' as required under Article 6 of the European Convention on 
Human Rights

@highlight

'Things cannot go on as they are,' says Justice Secretary Chris Grayling