By
Deni Kirkova

Sophisticated dolls' houses boasting groundbreaking design are to be auctioned at Bonhams, London on Monday.

The pint-sized masterpieces have been created by 20 of Britain's top architects - including Zaha Hadid - to raise money for UK children's charity KIDS.

Property developers from Cathedral Group who commissioned the project briefed designers with just one requirement: each house had to include at least one feature that makes life easier
 for a child with a disability.

Morag Myerscough and Luke Morgan designed this house 'on a coral in the deep blue sea' with artists Ishbel Myerscough, Chantal Joffe and poet Lemn Sissay

Paintings on easel and stretched canvases reside in the mini property, perhaps in the art studio room

MAKE ARCHITECTS' Jigsaw House is inspired by puzzles: a large house was created, made up of many small houses, the result is 26 fully designed houses with a further 20 empty houses to combine and complement the structure

Each partner in the practice was encouraged to invent their own house, 
filling each room with their own sensory expressions of play and colour

AMODELS' Elvis’s Tree House is based on a real playground in Southampton. The simple concept was to be as physically challenging as possible, because kids learn for themselves faster that way

The project is inspired by the dolls' 
house that British architect Edwin Lutyens designed for The British Empire Exhibition at 
Wembley in 1922 - using a very traditional children's toy to display the
 very best of modern architecture, craftsmanship, art and interior 
design.

Each architect was given a miniscule plot of land measuring 750mm square on 
which to build their property.

Laid out like architectural models, the mini marvels are as colourful and tempting as jars of sweets.

In the spirit of the Lutyens' house, the architects and designers collaborated with their own artists, designers and furniture-makers.

World-famous artists Grayson Perry, David Adjaye with Chris Ofili, Guy Hollaway with 
Hemingway Design and Studio Egret West with Andrew Logan all contributed to the project with stunning miniature artworks.

There are three days left to bid for the dolls' 
houses on adollshouse.co.uk until the auction on 
Monday evening at Bonhams. Zaha Hadid's dolls' house has
 currently attracted the highest bid so far of £10,500.

On Sunday 10th Nov 11am-3pm and then on Monday 11th from 9am-3pm, the complete collection will be exhibited for the first and only time and auctioned at Bonhams in London’s New Bond Street. All proceeds go to KIDS.

For more information, visit adollshouse.co.uk, spread the word #dollshouse

Hemingway Design and Guy Holloway's Jack in a Box starts off as a simple cardboard house (left), but when switched on, the inflatable structure inside begins to fill with air powered by an integrated fan. The dolls' house roof opens and the walls collapse to allow the organic structure (left) to grow out of the box

STUDIO EGRET WEST in collaboration with Andrew Logan made Puzzle House (left), when not in use it's a tidy colourful rectangular box, and when in play mode, the construction explodes into 7 separate pieces. HLM and JuJu Ross Design/A&J Hilliard Cabinet Makers: Sound [Play]ce (right) is an interactive tower - different sounds are generated by a marble running through the system 

House for a Deaf Child by DRMM in collaboration with Richard Woods Studio and Grymsdyke Farm has been designed with the needs of a deaf child in mind and aims to support sign language

The exterior has adjustable pieces to give colour expression on the outside, and control of light and views from the inside

Multi-story was designed by DUGGAN MORRIS ARCHITECTS in collaboration with Unit 22 Modelmakers and in consultation with Christina, mother of high functioning autistic Louis (5); the house has a set of rooms arranged in either a stack or plan form

DRDH ARCHITECTS in collaboration with Norwegian artist Anne Katrine Dolven: Play House is a toy theatre, based on those popular in the 18th century. Its inner world is full of high-contrast color visible to the partially sighted

Zaha Hadid's dolls' house 'This Must be the Plac'e has currently attracted the highest bid so far of £10,500

This Must be the Place by Zaha Hadid: Pieces can be assembled and dismantled in many combinations, to be re-assessed with each new composition ¿ voids are interpreted as new unique rooms or courtyards for dolls to inhabit.

@highlight

The Cathedral Group commissioned 20 of the world’s top architects and designers to build houses

@highlight

Each house had to include at least one feature that makes life easier for a child with a disability

@highlight

On Monday they will be exhibited and auctioned at Bonhams, London, with all proceeds going to KIDS charity