By 
Steve Doughty, Social Affairs Correspondent

PUBLISHED:

20:46 EST, 17 March 2013


| 

UPDATED:

03:24 EST, 18 March 2013

Family breakdown is costing taxpayers almost £50 billion a year and the bill is rising fast, a new analysis said yesterday.

The costs generated by family breakdown -  including subsidised housing, crime, health and social care and disrupted education - have gone up by nearly a quarter in just four years.

The estimates, produced by the Relationships Foundation think tank, include large rises in tax credits for single parents, in housing benefit, in NHS and social services spending, and in spending on policing.

Costly: Family breakdown is costing taxpayers almost £50 billion a year and the bill is rising fast, according to the Relationships Foundation think tank (file picture)

The report calls on David Cameron to find ways to support families and to put family policy at the forefront of the Government’s interests.

Foundation director Michael Trend said: ‘For too long Governments of all colours have ignored the vital output of families and the multi-billion pound cost of their failure.

‘This is unsustainable in any economic climate, let along the current one.’

The report put the share of tax credit 
spending attributable to family breakdown at £9.79 billion, up from 
£6.31 billion in 2009. Including other state handouts, the total benefit
spending on broken families was put at more than £18 billion.

It calculated that physical health 
problems accumulated as a result of family break-up cost nearly £6 
billion, mental health problems £1.8 billion, social services £5.5 
billion, and that almost £3 billion is spent looking after children 
taken into state care as a result of the collapse of their families.

Breakdown: Almost £3 billion is spent looking after children taken into state care as a result of the collapse of their families (file picture)

Police costs for dealing with crime generated by young people whose lives have been warped by family breakdown is said to be just over £5 billion, with a further £1 billion going on prison places for the more serious criminals among them.

The total of £46.07 billion compares with £37.03 billion in 2009, when the figures were first compiled, the report said.

It warned: ‘The breakdown of relationships, whether married, cohabiting or never stably formed, has far-reaching costs and consequences.

‘The emotional distress to those involved is considerable. The impact on children’s life chances is profound.

‘There are also costs to society as a whole. These include greater needs for financial support as well as increased demand on health, education and criminal justice.’

The report added: ‘The Government has recognised the case for investment in the most troubled families and that the failure to support these families effectively undermines the life chances of children.

‘The Government’s own figures calculate that the 120,000 most troubled families cost £9 billion a year.

‘Yet the same logic does not seem to have been applied to all families.’

It added that the estimates of costs do not include the impact of the latest benefit reforms or spending cuts.

The
£46 billion figure amounts to three per cent of the country’s gross 
domestic product - its annual earnings - the report said.

Just criminal: Police costs for dealing with crime generated by young people whose lives have been warped by family breakdown is said to be just over £5bn (file picture)

The findings come at a time when state figures suggest that a newborn baby has only a 50 per cent chance of living with both parents by the time he or she reaches the age of 16.

The Foundation report said that although the majority of married couples stick together, nearly four out of 10 marriages end in divorce, and cohabiting unions are much more likely to break up.

It said that relationships are under heavy pressure from high housing costs, debt, care costs and long working hours.

Mr Trend said: ‘Families in the UK are among the most pressured in Europe. We want to see the Government deliver on its state promise of applying a family test to all policy, an initiative that will need political will and courage but doesn’t need to add any cost to the country’s taxpayers.’

@highlight

Costs include housing, crime, health and disrupted education

@highlight

Estimates produced by Relationships Foundation think tank

@highlight

Report calls on David Cameron to find ways to support families