By 
David Mccormack

PUBLISHED:

00:48 EST, 18 July 2013


| 

UPDATED:

01:17 EST, 18 July 2013

A Texas man was shocked and surprised on Sunday when the fancy hotel he was staying at took him seriously over some bizarre suggestions he had requested on his online booking form.

Dustin Wray and girlfriend Lauren Taylor decided to spent the night at the Woodlands Resort in Houston after purchasing tickets to see their favorite singer John Mayer perform there.

When Dustin had completed the online booking for the hotel room a month earlier he couldn’t resist having some fun when it came to the ‘special requests’ section.

Dustin Wray and girlfriend Lauren Taylor decided to spent the night at the Woodlands Resort in Houston after purchasing tickets to see their favorite singer John Mayer perform there

Strange demands: Dustin Wray decided to set the staff at The Woodlands Resort an usual request

Dustin requested: ‘Three red M&Ms on the counter. Not packages, just three single M&Ms. One for me, one for my girlfriend, and one to split if we get hungry late at night. And a picture of bacon set on the bed. I love pictures of bacon.’

Not for a minute did he think the hotel would take his unusual requests seriously.

‘I wrote it so that if they saw it they would laugh because it was stupid, but also make it feasible if they actually wanted to fulfill it,’ he told ABCNews.com.

By the time the stay had come around, Dustin had almost forgotten about his demands.

Three single red M&Ms: Dustin's first special request which he quickly ate with girlfriend Lauren Taylor

Rather than chocolates on their pillow, the couple found a picture of bacon

Bacon fan Dustin Wray was especially impressed that the hotel was able to source this photo for his stay

'I saw the three red M&M's there and it honestly confused me,' he said.

'I was staring at them thinking this is weird. And then Lauren started laughing at the picture on the bed [of bacon] and I turned around and looked and that's when it all clicked.'

The couple celebrated by eating the M&Ms and enjoying the concert. Afterwards Dustin posted about his trip and the hotel's impressive customer behavior on Reddit.

Within hours his post had generated more than 80,000 views and led to coverage on local Houston radio shows and in local blogs and newspapers.

The hotel is so grateful for the publicity generated by the Dustin, that they've even offered him another stay at the resort for free.

Purpose of the trip: John Mayer performed at the hotel resort on Sunday night

The Woodlands Resort & Conference Center in Houston, Texas

@highlight

Dustin Wray and girlfriend Lauren Taylor stayed at the Woodlands Resort in Houston, Texas on Sunday night

@highlight

When booking their trip, Dustin had added a list of strange and unusual requests - which the hotel obliged with

@highlight

Dustin shared his experience on social media which generated a lot of positive publicity for the hotel chain - who've offered him a free stay