The Tower of London hosted a £240-a-head dinner for arms dealers while poppies were still being removed from the Blood Swept Lands and Seas of Red memorial.

Nearly 200 people from the UK arms industry sipped Champagne before dining on a swanky three-course dinner just yards from the memorial to the 888,246 British servicemen killed in the First World War.

The annual 'acclaimed and influential dinner' on Tuesday night was kept quiet by organisers London Chamber of Commerce and Industry (LCCI), which did not publicise where the event was taking place.

Protesters met arms dealers at the Tower of London as they arrived for a 'luxurious' three-course dinner just yards from the poppy memorial, which is still being removed 

Nearly 200 guests from arms trade met for the dinner at the Tower of London on Tuesday night

Guests, who included senior officials from the Ministry of Defence and foreign security companies, paid up to £3,000 for tables at the LCCI's Defence and Security Dinner but were told they would be advised on its location after registering.

The Tower of London was accused of 'crass insensitivity' for hosting the £240-a-head black tie dinner for weapons manufacturers at the Tower of London, where poppies from the Blood Swept Lands and Seas of Red memorial are still being removed.

Andrew Smith, of Campaign Against the Arms Trade, told the Independent: 'On Remembrance Day, the Tower of London was a focus for remembering the horrendous loss of life in the First World War. 

'It is disturbing that just weeks later it can play host to the very arms companies which profit from perpetuating war and conflict today. 

'It is crassly insensitive and in extremely bad taste that this historic monument would do this so soon after providing such a high-profile focal point for Remembrance Day.' 

The dinner was co-sponsored by the world's largest defence firm Lockheed Martin, with Chief of the Defence Staff General Sir Nicholas Houghton the guest of honour.

The Blood Swept Lands and Seas of Red memorial was made up of 888,246 poppies - one for each Commonwealth serviceman and woman killed in WWI

Thousands flocked to the poignant memorial to the fallen, including the Queen and the Duke of Edinburgh

Publicity for the event read: 'Raise your company profile, make new business connections and entertain clients at this acclaimed and influential annual dinner.

'Your ticket includes a Champagne drinks reception, luxurious three-course meal, half a bottle of wine and mineral water.'

Despite the efforts to keep the event quiet, arms manufacturers were met by protesters as they arrived for a pre-dinner drinks reception in the White Tower. 

Chief of the Defence Staff General Sir Nicholas Houghton was guest of honour at the dinner on Tuesday night

Demonstrators were waiting at the Tower with banners, with one reading: 'Send arms dealers to the Tower. Lives saved.'

The event was organised by the LCCI's defence and security committee group, made up of members of Britain's largest defence company BAE System, as well as Thales and Lockheed. 

The Tower of London hosted the event last year too, with guests asked to wear black tie to the New Armouries dinner.

A spokeswoman for Historical Royal Palaces, who run the Tower of London, said: 'As an independent charity receiving no Government or Crown funding, we rely on income generated by commercial activities to care for the palaces and keep them open for people to enjoy. 

'We are unable to confirm details of private events held at the palaces, however we always seek to ensure that such events are appropriate and compatible with our charitable status and would not wish to be associated with those who irresponsibly or illegally proliferate the arms trade.

'Our events policy states that we will work with clients who appropriately reflect the status and dignity of the palaces. In our judgement, the decision to host an event by the London Chamber of Commerce is consistent with this policy.'

An LCCI spokeswoman said: 'This event is attended by those who work or have an interest in the defence and security industry, including MoD and military personnel.

'Venues are chosen based on many considerations including cost, availability, their relevance to the sector and on feedback from our members.'   

@highlight

Nearly 200 arms manufacturers attend  three-course dinner at the Tower 

@highlight

Weapons dealers sipped on Champagne just yards from poppy memorial

@highlight

Defence officials paid up to £3,000 for a table at Tuesday's black tie event

@highlight

Thousands of poppies representing WWI soldiers are yet to be removed 

@highlight

Organisers accused of 'crass insensitivity' for holding event at the Tower 