The ostentatious hats, risqué dresses and outrageous behaviour on Ladies' Day has become as traditional at Aintree as its horse racing.

But bosses at the Grand National course have a plan to preserve their  visitors' dignity.

Photographers at the world's greatest steeplechase meeting will be banned from taking pictures of badly dressed women.

Scroll down for video 

Race-goers from Swansea in hats and heels at Ladies' Day at the Grand National race meeting in Aintree racecourse, Liverpool

Two ladies enjoy themselves, taking a swig from a bottle of bubbly at Aintree, Liverpool

John Baker, managing director of the racecourse,hoped the ban would put an end to what he claimed was unfair coverage of  customers getting drunk or flashing too much flesh at the event.

He said: 'We want to overwhelm the negativity, to push the positivity to the front.

'Our event is full of character, it's fun, and that's generated by the personality of the Liverpool people.'

Bosses have a plan to preserve their visitors' dignity and will ban any photographer taking unflattering photographs

Last year at Ladies' Day at Aintree racecourse, in Liverpool, where one racegoer takes a glug of pink champagne

He warned that any photographer taking unflattering pictures would lose their accreditation.  

'We have to absolutely protect that because it's at the core of what we are, and we have a responsibility to our customers to project the correct image,' he told the Liverpool Echo.

'We have talked about trying to monitor those photographers, so if we see any element clearly looking for a negative shot and we can identify that, we will take their accreditation off them and we'll kick them off the site.

'That's not easily manageable, but that's what we'll endeavour to do.'

A racegoer rests on her friend amongst the rubbish at Ladies' Day, Aintree

The managing director of the racecourse is hoping the ban will put an end to what he claims is unfair coverage

Two Ladies' Day visitors to the racecourse, both in big hats and heels, one wearing a bright red fur cape while another wears black

A racegoer in a bridal-style dress for Ladies' Day is helped up by her friend, in a very short pink dress, after she appeared to have fallen over

Ladies' Day, a firm fixture on the North West social calendar, frequented by celebrity WAGs such as Colleen Rooney and Alex Curran. 

Tens of thousands of racegoers attend each year and the Grand National is seen as the world's most famous horse race, generating TV viewing figures in the hundreds of millions from across the globe.

But recently, Ladies' Day has reportedly failed to sell out with suggestions regular race-goers have been put off by media coverage of some women taking advantage of the 'lax' dress code, banned at other racecourses.

Aintree, which runs a style contest for the best-dressed ladies on the day, will also now issue their own images on their website, Facebook and Twitter to counter other outlets who may want to put a 'negative slant' on the meeting.  

The ban aims to end the trend of endless pictures of customers getting drunk or flashing too much flesh at the event, like above

A racegoer writes his phone number on the thigh of a woman, left, and right, an elegantly dressed woman rides a mechanical horse

Photographers at Aintree racecourse will have their accreditation taken away if they take unflattering pictures at the event. Pictured: A racegoer plays to a televison camera

A racegoer is pictured open-mouthed as a friend feeds her a burger at Ladies' Day 

A woman laughs as she accidentally slips in her heels next to the bar at the Aintree Grand National meeting

Bosses at the Grand National course have a plan to preserve their visitors' dignity, by banning shots of women behaving badly

A woman holds a drink up at Ladies' Day at the Aintree Grand National meeting in April 2012

A woman shows off her winnings as racegoers enjoy the party atmosphere of Ladies' Day

Racegoers relax on the ground at Ladies' Day at the Aintree Grand National Festival meeting last year

Female racegoers make their way home through the rubbish at Ladies' Day

A woman dresses like a jockey at Ladies' Day at Aintree last year, complete with riding crop 

Some women take co-ordinating their outfits rather seriously. Pictured: a woman in a garish floral dress (left) and (right) a racegoer teams a garish fur-trimmed coat with an extremely short red dress

Young ladies wear very bold makeup and even bolder outfits at Ladies' Day at Aintree

Raucous women in short dresses pose for pictures at Ladies' Day at the Grand National meeting in Aintree

Racegoers swap their shoes for flip flops as they make their way home from  Ladies' Day

Women dress up for Ladies' Day at the Grand National Festival, Aintree racecourse in Liverpool

At the world famous Grand National Festival, fashion and dressing to impress is as important as the racing, but bosses have nor banned unflattering images like the one above

Rubbish litters the ground as racegoers make their way home at the end of Ladies Day at the Aintree Grand National Festival meeting last year

A man awkwardly gives a woman a piggyback ride as racegoers make their way home from  Ladies' Day

A couple kiss on the rubbish-littered ground at the Aintree Grand National Festival meeting last year

Racegoers dance and enjoy the party atmosphere of Ladies Day at the Grand National Festival meeting

John Baker, the racecourse's managing director, says the event is 'full of character'. Pictured: a woman enjoys a drink straight from the bottle

A female racegoer holds a plastic cup in her mouth at the Grand National Festival in Aintree

Women have been accused of taking advantage of the 'lax' dress code. Pictured: a racegoer wears an ill-fitting pink dress

A racegoer takes the extreme cleavage trend (left) to Ladies' Day at Aintree racecourse, while another wears a tight corset and shows off a large back tattoo (right)

'We have a responsibility to our customers to project the correct image,' said a spokesman for the event

Media coverage of some women taking advantage of the 'lax' dress code has reportedly put some off the Grand National meeting

Strange fashion choices at Ladie's Day include furry skirts and dresses which are short in the front and long in the back

Photographers at Aintree will have their accreditation taken off them if the photograph badly dressed women

One racegoer teams an jewellled headpiece with a complicated hairstyle and flowing dress (left) while another goes for a fur-trimmed pink number

A racegoer writes his phone number on the thigh of a woman, left, and right, an elegantly dressed woman rides a mechanical horse

The new rules aim to dispel the reputation of scantily-clad and badly dressed women the event has attracted

Abigail Johnson, Kerry Maher and Becca Davies at Ladies Day at the Grand National Festival, Aintree

A woman with an elaborate hairdo reveals ample cleavage in a tight red dress with a very high slit

Barefoot and carrying a bottle of water, this racegoer starts to make her way home after Ladies' Day

Racegoers leave the course in high spirits after Ladies' Day, Aintree Racecourse

Race fan Lilly Evans dresses up in her  finest during the second day of the Grand National meeting in 2007

Women wear ponchos and drink beer in the rain during Ladies' Day at Aintree in 2012

Alexis Althrope in an ornate butterfly hat at the Grand National race meeting at Aintree racecourse

A racegoer wears a bright multi-coloured hat with matching jacket at the Grand National race meeting at Aintree

A racegoer wears a short, cream-coloured dress with uncomfortably high wedged heels

These women appear to be more suitably dressed for a nightclub rather than Ladies' Day at Aintree

A woman in a bedazzled dress dances with her arms in the air at the Aintree Grand National meeting in 2012 

Racegoers brave the rain as they refuse to let it spoil the occasion at Ladies' Day in April 2013 

Racegoers cheer on their horses during The Tangle Teezer Top Novices' Hurdle Race on Ladies' Day in 2012

A female racegoers protect herself from the weather at Ladies' Day at Aintree Racecourse on April 13, 2012

A woman shows off the tattoo on her chest during Ladies' Day at the Aintree Grand National meeting in 2011

A woman wearing a couture hat eats a burger during Ladies' Day at Aintree Racecourse in 2010

A woman sticks her tongue out to the camera as she and a fellow racegoer enjoy a cigarette

Bride-to-be Gemma Blease enjoys a ride on a horse racing simulator as she and her hen party enjoy the atmosphere of Ladies Day at the Aintree Grand National Festival meeting in April last year

A female racegoers poses for a picture as she arrives for Ladies' Day at Aintree Racecourse last year

Women strikes a series of poses at Ladies' Day at Aintree racecourse last year

A woman in an ill-fitting pink dress makes her way to the bar at Aintree Grand National Festival meeting

Racegoers relax on the found as they enjoy the atmosphere of Ladies Day at the Grand National Festival

A barefoot racegoer smiles as she is seen leaving the course at the end of Ladies' Day last year 

A woman is helped to her feet after tripping as she and racegoers make their way home from  Ladies' Day

Garishly-dressed racegoers leave the course in flip-flops at the end of Ladies' Day last year

A woman in a tight dress reveals ample cleavage and plenty of thigh in a garish dress with matching bag

A woman applies bright lipstick, despite being in danger of a wardrobe malfunction 

Two men dressed as jockeys pose for a photo with three ladies on ladies day during day two of the John Smith's Grand National meeting at Aintree

A woman dons novelty glasses at Ladies' Day at the Aintree Grand National meeting 

A woman drinks straight from the bottle (left) and right, another racegoer makes a face at the camera 

Racegoers pose in novelty glasses at the Crabbie's Grand National Festival 2014

A female racegoer slumps over her friend on the ground surrounded by rubbish

A racegoer leaves the course at the end of Ladies' Day of the Grand National horse race meeting at Aintree

@highlight

Ladies' Day at Grand National is seen as the day for visitors to dress up

@highlight

Aintree event is often frequented by celebrity WAGs like Colleen Rooney

@highlight

But parade of risque dresses, fake tans and huge hats have led to ridicule

@highlight

Now bosses at the event are set to put a ban on unflattering photographs