Nasa is planning an audacious mission to catch an asteroid in a giant, draw-string bag and tow it to the Moon - close enough for human explorers to visit.

The U.S. space agency is set to ask Congress for $100million in its next budget request to start planning the project, which could be the next target for human spaceflight.

The mission, first suggested last year by space experts at the California Institute of Technology, would aim to pluck a 500-ton asteroid from its orbit using an unmanned spacecraft, then haul it into orbit near the Moon.

How to catch an asteroid: This graphic shows how
 the projected asteroid-catching spacecraft might look. The 18-ton probe
 would catch a 500-ton space rock in a giant, draw-string bag

Projected to cost $2.65billion in 
total and last ten years, the project is said to have found favour with 
President Obama's administration, which has already announced a goal of sending 
astronauts to a near-Earth asteroid by 2025.

Researchers from CalTech's Keck Institute for Space Studies (KISS) detailed the plan in a paper published last spring, but rumours of Nasa's decision to ask for funding for the project were reported by Aviation Week last week.

'The idea of exploiting the natural resources of asteroids dates back over a hundred years, but only now has the technology become available to make this idea a reality,' the report says.

The KISS feasibility study suggests that bringing a 500-ton asteroid closer to Earth would give astronaut crews a 'unique, meaningful and affordable' destination for the next decade.

It adds: 'Placing an NEA [Near Earth Asteroid] in lunar orbit would provide a new capability for human exploration not seen since Apollo. Such an achievement has the potential to inspire a nation.

'It would be mankind’s first attempt at modifying the heavens to enable the permanent settlement of humans in space.'

Schematic: Researchers from CalTech's Keck 
Institute for Space Studies (KISS) detailed the plan in a paper 
published last spring, but Nasa is now reportedly seeking funding to 
execute it

The report outlines an entirely robotic mission to locate and capture a Near Earth Asteroid (NEA), with a diameter of about seven metres and a mass of around 500,000kg.

It is hoped such a modestly sized space rock may contain up to 100 tons of water, 100 tons of carbon rich compounds, 90 tons of metals and 200 tons of silicates.

An 18-ton probe would be launched on an Atlas V rocket and use the Moon's gravity to slingshot itself towards its target in interplanetary space.

Once there, the spacecraft would deploy a massive inflatable bag to envelop the asteroid - manoeuvring to stabilise against any tumble or rotation - then 'multiple "draw strings" would cinch-close the opening of the bag and also cinch-tight against the bulk material,' the report says.

It adds: 'Due to the residual velocity between the asteroid and the spacecraft, there would be some “impact” as the asteroid is captured.

'Although, since the asteroid would be much more massive than the spacecraft, it is perhaps better to think of this as the asteroid capturing the spacecraft.

'Nevertheless, once the spacecraft and asteroid are tightly secured together, the spacecraft could then de-tumble the combination.'

The proposed timeline for capturing the 
asteroid: Projected to cost $2.65billion in total and last ten years, 
the project is said to have found favour with the Obama administration

An ion thruster is a form of electric propulsion used for spacecraft that creates thrust by accelerating ions.

Ion thrusters use beams of ions (electrically charged atoms or molecules) to create thrust in accordance with momentum conservation.

They create very small levels of thrust compared to conventional chemical rockets but achieve very high specific impulse, or propellant mass efficiencies, by accelerating their exhausts to very high speed.

However, ion thrusters carry a fundamental price: the power imparted to the exhaust increases with the square of its velocity while the thrust increases only linearly.

Normal chemical rockets, on the other hand, can provide very high thrust but are limited in total impulse by the small amount of energy that can be stored chemically in the propellants.

Due to their relatively high power needs and the requirement of an environment void of other ionized particles ion thrust propulsion is currently only practical in space.

Moving such a huge object using conventional rockets would need an enormous amount of fuel to be carried along with the probe.

So rather than using chemical rockets it would be equipped with a solar powered electric propulsion system.

Such 'ion thrusters', as they are known, work by using electricity generated by solar panels to accelerate charged particles away from the space craft, ars technica explains.

Using these, the spacecraft could begin its long track back to the Moon, estimated to take between two and six years.

The revelation that Nasa wants money to begin planning a mission to capture an asteroid from interplanetary space comes three months after Major-General James Bolden made a cryptic suggestion to a National Research Council committee on human space flight.

'When the President announced that an asteroid would be the next destination for Nasa's human spaceflight programme, he did not say Nasa had to fly all the way to an asteroid,' he said.

'What matters is the ability to put humans on an asteroid.'

@highlight

U.S. space agency reportedly set to ask for $100million to begin the project

@highlight

White House wants astronauts to carry out tests on asteroid by 2025