British commuters are subsidising foreign railways to the tune of tens of millions of pounds a year, campaigners claimed yesterday.

State-owned operators in Germany, France and the Netherlands are said to transfer home their profits from UK rail services, helped by taxpayer subsidies and higher fares than in their own countries.

Christian Wolmar, an industry expert, said successive UK governments had invited in ‘European wolves’ who were ‘chomping away at the carcass of our railway system’. 

State-owned operators in Germany, France and the Netherlands are said to transfer home their profits from UK rail services, helped by taxpayer subsidies and higher fares than in their own countries

He said Britain should instead copy the foreign firms by profiting from running trains on the Continent.

‘Why should these companies be making a profit out of our railways that is then exported to help their railways?’ he said. 

‘It is clear they operate in their own national interest, and that is to be expected. British Rail in its last years was pretty efficient and pretty well run, and had a very good generation of managers.

‘If we had kept it, we would be out there chomping up bits of French or Italian or German railways, rather than the other way around.’

Germany’s Deutsche Bahn made a pre-tax profit of £697 million in 2012-13, boosted by British arm Arriva

Mr Wolmar pointed out that British commuters generally paid higher fares than counterparts in Europe, with commuters here facing an inflation-busting rise of up to 2.5 per cent from tomorrow.

Some season tickets now cost more than £5,000. 

Some season tickets now cost more than £5,000

Manuel Cortes, leader of the TSSA rail union, said: ‘Hard-pressed British commuters are subsidising the rest of Europe which has wisely decided to keep publicly owned railways. 

'This is the economics of the madhouse.’ 

British taxpayers paid £2.5 billion in subsidies for trains operated in part or exclusively by subsidiaries of foreign state railways in 2012-13, official figures show.

Germany’s public-owned Deutsche Bahn made a pre-tax profit of £697 million in 2012-13 – a figure boosted by British arm Arriva.

Its franchises received £861 million in UK subsidies over the same period. Berlin’s transport ministry has stated: ‘We’re skimming profit from the entire Deutsche Bahn and ensuring that it is anchored in our budget. 

British commuters generally pay higher fares than in Europe, with commuters here facing an inflation-busting rise of up to 2.5 per cent from tomorrow

'That way we can make sure it is invested in the rail network here in Germany.’

But an Arriva spokesman said: ‘No dividend has been paid by Arriva to its parent company Deutsche Bahn. 

'Over that time, all profits generated by Arriva have been reinvested across the Arriva Group.’

Keolis – 70 per cent owned by French state rail firm SNCF – runs a series of franchises including London Midland, Thameslink and Great Northern. 

It paid £37.9 million in dividends to SNCF and its other shareholder, a Canadian pension fund, over the past two years from the profits of its UK operations.

Alistair Gordon of Keolis UK said: ‘Like any private sector business part of our earnings after taxation will be returned to shareholders and a portion will be reinvested into our business to fund improvements to our services.’

Dutch state-owned transport firm Abellio runs Abellio Greater Anglia and – with controversial British outsourcing giant Serco – Merseyrail and Northern Rail.

Northern Rail has been widely criticised by passengers for its unreliable service and crowded, uncomfortable and outdated trains, which Chancellor George Osborne pledged last month to replace.

This franchise alone received £713million in UK subsidies and paid out £36million in dividends in 2012-13. The firm did not respond to a request for comment.

A Department for Transport spokesman said: ‘Far from taking money out of the system, these companies are returning billions to the taxpayer and are investing in a host of improvements for passengers, including more seats.’

@highlight

British commuters subsidising foreign railways with millions a year

@highlight

Operators in Germany, France and the Netherlands allegedly transfer profits made in  UK through higher fares and taxpayer subsidies back home

@highlight

Expert said 'European wolves' are 'chomping at carcass' of our railways