By 
Daily Mail Reporter

PUBLISHED:

04:44 EST, 1 November 2012


| 

UPDATED:

04:45 EST, 1 November 2012

A power outage caused by Superstorm Sandy destroyed years of scientific research at a New York hospital, it emerged today.

The New York University Hospital saw its generator fail at about 8.30pm on Monday as ferocious winds ravaged the city.

At least 200 patients, including 20 babies in neonatal intensive care, were evacuated when it became clear that the hospital's emergency generator also failed to kick in.

Paramedics evacuate patients from New York University Hospital after a power outage during Superstorm Sandy on Monday evening. It has now emerged that years of scientific research at the hospital has been lost

But now scientists have discovered that years of research kept at the hospital's Smilow building on East 32nd St has been lost.

'This does not equate to a loss of life, but it is extremely disheartening to see years of research go down the drain,' a source told the New York Daily News.

Many valuable preagents, including special enzymes, antibodies and DNA strands, that were generated by scientists and stored at between -80C and -20C have been destroyed.

Thousands of genetically modified mice, used by scientists for research into cancer and other diseases, drowned when the flood waters struck.

It is understood that it took years to produce the mice.

During the height of Monday's storm, dozens of ambulances lined up around the block outside NYU Hospital, to transport its patients to other hospitals around the city.

Without power, there were no elevators, meaning patients had to be carefully carried down the stairs to safety.

In line: Ambulances waited around the block to evacuate patients from NYU Hospital after the power failure

Huge operation: Medical workers assist a patient into an ambulance during the evacuation

The power cuts came about soon after the massive storm made landfall in southern New Jersey.

Consolidated Edison cut power deliberately to about 6,500 customers in downtown Manhattan to avert further damage. Soon, huge swathes of the city went dark.

Among those evacuated from NYU Hospital was Julie Alemany, who went into labour at around 6pm on Monday, just as New Yorkers braced themselves for Sandy’s arrival onto land.

When the power went, the 34-year-old was told she would need to evacuate, despite the painful contractions that were ripping through her body.

‘I said “I can’t run!”’ she said, describing how she begged for pain relief until she was given a low-dose epidural by the light of a cell phone held by her husband.

She was placed on a sled and haphazardly carried down the eight flights of stairs from the hospital by headlamp-wearing security guards.

She eventually gave birth in Mount Sinai Hospital shortly after midnight on Tuesday morning.

@highlight

New York University Hospital's generator failed at 8.30pm on Monday

@highlight

At least 200 patients, including 20 babies in intensive care, were evacuated

@highlight

Scientists now discover that years of research kept at hospital's Smilow building on East 32nd St has been lost