Last updated at 1:41 PM on 2nd December 2011

YouTube has had its first major redesign since Google bought the site - and it's clearly aimed at making the video site more 'TV-like'.

It's now easier to find 'channels' from the front page, with a black navigation menu on the left hand side which allows users to organise channels, rather than simply search for video using Google search.

'More and more, behind every great video is a great Channel,' said YouTube via its official blog.

New look: The new look gathers 'Channels' in the black navigation bar on the right hand side of the 
page making it more like Google's homepage

Three billion videos are viewed on YouTube every day.

Google is attempting to 'shift' the way people use the site, with the increased focus on 'Channels' a clear attempt to mirror services offered by TV stations.

It also ensures that users are logged in via a Google account.

The new look for YouTube mirrors the redesign announced earlier this week of Google's home page.

Professional approach: Advertisers prefer not to be next to
user-generated content so earlier this year, YouTube announced a range of professionally produced channels from celebrities such as Madonna

'With our announcement last month that more Channels are coming to YouTube, we want to make it easier for you to find and keep tabs of what you want to watch,' said the company via an announcement on the official Google blog.

The final YouTube look comes after Google 
unveiled an experimental design in July called Cosmic Panda and used 
feedback from users to establish the finished appearance.

According to their official blog 
Google believe the new design provides a 'simpler YouTube, with a 
consistent grey background, bigger video thumbnails and a more 
streamlined watch page.'

Google also aims to offer more professional content on the site - and, as usual, everything will be free, supported by the internet giant's advertising system.

'DIY' channels allow users to earn a percentage by signing up for Google's 'Partner' programme, where they earn some of the advertising revenue generated by the site.

But YouTube will also offer professional content.

The changes follow a move earlier this year when the site launched 100 new 
professionally produced TV channels in partnership with stars such as singer 
Madonna and actor Ashton Kutcher.

The
move is designed to turn YouTube - already available via many internet 
TVs - into a rival to cable and satellite TV channels.

Owner Google says that the channels will be on-demand services, each offering 25 hours of programming a day.

The
arrangement should work in YouTube's favour when it comes to 
advertising.

Many big-ticket advertisers are relucant to be seen 
alongside 'user-generated' videos, and would be happier with 
professionally produced, star-studded content.

YouTube is said to be paying up to $100million to producers to take part, and up to $5million per channel.

The money is an advance on advertising 
money - Google will recoup its portion first
before splitting the proceeds.

Google also aims to make the site more 'social' - even allowing users to share via Facebook, rather than their own, less popular Plus Network.

'You can even link your YouTube account to Google+ and Facebook to see what your friends are sharing,' said YouTube.

@highlight

New design brings it in line with owner Google's look

@highlight

Users can now organise their favourite channels