Row after row, this astonishing array of solar panels has completely engulfed an enormous 30-acre field in the heart of the countryside.

As this aerial photograph reveals, acres of beautiful Hampshire countryside have been blighted as a result, by 18,000 solar panels.

The solar farm covers a staggering 30 acres of land creating a massive eyesore in the centre of an otherwise picturesque view.

The solar farm, Cadland Estate at Fawley in Hampshire, covers a staggering 30 acres of land creating a massive eyesore in the centre of an otherwise picturesque view

Photographer Tim Woodcock, 54, captured the image from a helicopter while flying more than 1,000ft above the solar array near Fawley.

The energy saving farm on the Cadland Estate uses photo-voltaic panels to produce five megawatts of power.

It creates enough natural energy to supply 1,000 homes each day.

Mr Woodcock boarded his friend’s Jetranger helicopter to capture the farm which was installed last June with his Nikon camera fitted with a 24-120 Nikon zoom lens.

Photographer Tim Woodcock captured these images from a helicopter, flying more than 1,000ft above the solar array

He said: ‘We were in the air for just over an hour and being at 1,000 feet is not really a problem.

‘By the time you have reached that altitude you have settled down.

‘The strangest sensation is just as you take off and you have an idea of how far off the ground you are.

‘I was able to open a window on the aircraft and take pictures through that.’ Mr Woodcock, a professional photographer from Fawley, feels that there is a lot of interest in alternative forms of energy.

Solar farms like this one have sprung up in recent years as farmers collect up to £50,000 a year in green subsidies - this site is made up of 18,000 solar PV panels, mounted on nine kilometres of frames using 5,000 ground screws

‘Many of these alternative energy sources are manufactured abroad, in China, for example.

‘It is very easy to say that a system is ‘green’ when all the energy and environmental damage and cost is made elsewhere.’

He added: ‘Obviously there is a lot of interest in alternative forms of energy. But the question remains how many of these will actually provide a real alternative to fossil fuels - so far, very few.

‘No one seems to have the courage to tell the truth about energy alternatives.’

The solar panel farm, which is the size of 18 football pitches, is one of the largest of its kind in Britain and took just four weeks to construct.

It is made of 18,000 solar PV panels, mounted on nine kilometres of frames using 5,000 ground screws.

Locals claim it is less of a blot on the landscape than wind farms, because the panels are completely surrounded by trees and greenery.

Energy efficiency solutions company Anesco designed and manages the farm on the land rented from the Cadland Estate.

The Estate is also used for farming wheat, maize and livestock. It is best known for supplying potato to leading food manufacturers such as Walkers crisps.

Some locals claim the solar panels are less of a blot on the landscape than wind farms, because the panels are completely surrounded by trees and greenery

Energy generated by the solar PV system is fed back into the national grid under the Government’s Feed in Tariff (FiT) scheme which makes payments for energy produced through renewable sources.

Dozens of large-scale solar farms like this have sprung up in recent years as farmers put up acres of them to rake in up to £50,000 a year in the green subsidies.

More than 100 new planning applications are currently in the system and work on a large-scale installation in Wiltshire began last month.

Another energy firm Kronos Solar has set out plans to build Britain’s largest solar farm, on agricultural land in Houghton, Hampshire.

Under the proposals, 225,456 panels would be laid out across an area the size of 100 football pitches. The scheme is intended to produce enough electricity for 31,500 people.

However, it will soon be far more difficult to set up a solar farm on greenfield land or areas of outstanding natural beauty it was revealed last month.

New planning guidance to be issued to local councils will state that ‘care should be taken to preserve heritage assets, including the impact of planning proposals on views important to their setting’.

More than 100 new planning applications are currently in the system and work on a large-scale installation in Wiltshire began last month

This will not affect small scale solar installations which families can install on their roofs or farmhouses, or can be put up on industrial land.

Energy minister Greg Barker has insisted that although solar has a bright future in the UK it should not be in any place or at any price.

He said last month: ‘I want UK solar targeted on industrial roofs, homes and on brownfield sites not on our beautiful countryside.’

Campaigners near solar farms in rural beauty spots say they have become a sea of silicon slabs, which are allowed by councils to meet their renewable energy targets.

People who set up their own solar panels benefit from the feed-in tariff.

This has been slashed by around two-thirds over the past year after the Government set the level far too high.

However people who signed up in the early days in 2010-11 have their fee fixed for 25 years and continue to benefit.

 

@highlight

The area in Hampshire would cover 18 football pitches and was set up in just four weeks

@highlight

Photographer captured 
the image from a helicopter more than 1,000ft above the 
solar array near Fawley

@highlight

It is made of 18,000 solar PV panels, mounted on nine kilometres of frames using 5,000 ground screws

@highlight

Locals claim it is less of a blot on the 
landscape than wind farms, because panels are surrounded 
by trees