By
Mark Prigg

PUBLISHED:
  
  
      19:01 EST, 27 February 2014
    
  

 | 
  UPDATED:
  
  
      19:53 EST, 27 February 2014

As Asia struggle with an ever increasing pollution problem, one firm believes a project that sounds like the plot of a sci-fi film could being relief.

Orproject, a London design agency, wants to build a park enclosed in a giant 'bubble' - and says school playgrounds could be enclosed in smaller versions of the clean air system.

The park would contain a large botanical garden, and be completely sealed from the outside world, with perfectly clean air being pumped into it.

As a response to the bad air quality which is affecting many cities in Asia, London firm Orproject wants to build an enclosed park within the city.

The park houses a botanical garden, the air inside the park is filtered, and temperature and humidity are controlled throughout the year.

'The park houses a botanical garden, the air inside the park is clean, and temperature and humidity are controlled throughout the year,' the firm says.

'The buildings surrounding the park, which are connected to the controlled air system, can house apartments, offices and retail, but may also offer sports or medical facilities which make specific use of the healthy air.'

To create the unusual structure, the firm wrote an algorithm which simulates the development of veins in leaves or butterfly wings.

Electricity for the project can be generated by solar cells integrated into the canopy surface, and the heating and cooling of the air is done through a ground source heat exchange system.

The buildings surrounding the park, which are connected to the controlled air system, can house apartments, offices and retail, but may also offer sports or medical facilities.

Park life: the protective bubble would completely seal the area off from the outside atmosphere, keeping pollutants at bay.

The firm says the key to the project is a botanical garden to give resident respite form the polluted air outside.

'Botanical Gardens have been built in many world cities.

'They are attractions for tourists and recreational facilities for the inhabitants of the city.

'Both children and adults can experience nature and learn about the plants of the park.

Parks would also be able to have seperate zones to recreate conditions anywhere in the world.

'Inside the green houses, the temperature and humidity are controlled throughout the year, which allows the growth of plants from any climate.

'The plants and landscapes from all over the world can be placed inside the Bubbles project.'

The large park would be enclosed on all sides to seal the bubble structure

Smaller designs can cover school playgrounds or apartment buildings

The proposed roof system can be used to enclose an urban botanical garden, but the system also lends itself for many other applications at various scales.

Orporoject says it can be used to economically enclose playgrounds or school yards, it can form the atrium of an office building or shopping mall, or it can be used to cover the gardens of an apartment complex.

@highlight

Bubbles created by a computer algorithm based on a butterfly wing

@highlight

Park could be sealed from the outside world

@highlight

Smaller versions could encase school playgrounds and apartment blocks