Brain-wave sensing machines have been used to ‘telepathically’ control everything from real-life helicopters to characters in a computer game.

Now the technology has gone a step further by allowing someone in India to send an email to his colleague in France using nothing but the power of his mind.

The researchers used electroencephalography (EEG) headsets to record electrical activity from neurons firing in the brain, and convert the words ‘hola’ and ‘ciao’ into binary.

The researchers used electroencephalography (EEG) headsets which recorded electrical activity from neurons firing in the brain to convert the words ‘hola’ and ‘ciao’ into binary. In EEG, electrical currents in the brain are linked with different thoughts that are then fed into a computer interface

In EEG, electrical currents in the brain are linked with different thoughts that are then fed into a computer interface. This computer analyses the signal and controls an action.

In the latest study, published in Plos One, researchers decided to replace the computer interface with another brain to receive the signals.

In the initial test, the greeting was sent from a volunteer in Thiruvananthapuram, India to Strasbourg, France.

There, a computer translated the message and then used electrical stimulation to implant it in the receiver’s mind. 

This message appeared as flashes of light in the corner of their vision.

In France, a computer translated the message and then used electrical stimulation to implant it in the receiver’s mind that appeared as flashes of light in the corner of their vision

The light appeared in sequences that allowed the receiver to decode the information in the message.

Researchers then conducted a similar experiment in which thoughts were successfully transmitted from two participants, one in Spain and one in France.

The human brain is made up of billions of active neurons that have around 105,600 miles (170,000 km) of combined length.

Every time you have a thought, your brain produces weak but distinct electrical signals corresponding to it.

The electrical impulse is generated by the chemical reaction between neurons, which can be measured.

Recording and deciphering those signals is called electroencephalography (EEG), and it has been medically possible since 1924.

The second experiment resulted in a total error rate of just 15 per cent, with a 5 per cent on the encoding side and roughly 11 per cent on the decoding.

The technology was developed as part of a collaboration between the University of Barcelona in Spain, Axilum Robotics in France,  Harvard Medical School and Starlab Barcelona in Spain. 

According to the researchers, this is the first time humans have sent a message ‘almost directly’ into each other’s brains.

‘We anticipate that computers in the not-so-distant future will interact directly with the human brain in a fluent manner, supporting both computer- and brain-to-brain communication routinely,’ they wrote.

Human-to-brain technology is also gaining traction. In May, German scientists showed how seven pilots used mind control to fly with ‘astonishing accuracy.’

In a simulation, several of the pilots managed the landing approach under poor visibility, while one was able to land a few metres from the runway’s central line.

Meanwhile, in June, University of Oregon researchers unveiled a device that claimed to be able to monitor memories in near real time to see what a person is thinking.

The receiver's brain (pictured) was stimulated (areas shown by dots) to see sequences of light that could be decoded into a message. Researchers then conducted a similar experiment in which thoughts were successfully transmitted from two participants, one in Spain and one in France

In the initial test, the greeting was sent from a volunteer in Thiruvananthapuram, India to Strasbourg, France

 

@highlight

Scientists used EEG headsets to record electrical activity in the brain

@highlight

Electrical activity from words ‘hola’ and ‘ciao’ were converted into binary

@highlight

The greeting was sent from Thiruvananthapuram, India to Strasbourg

@highlight

A computer translated the message and then used electrical stimulation to implant it in the receiver’s mind, appearing as specific flashes of light 

@highlight

According to the researchers, this is the first time humans have sent a message almost directly into each other’s brains 