By 
Rob Waugh

PUBLISHED:

08:07 EST, 7 June 2012


| 

UPDATED:

10:00 EST, 7 June 2012

Glitches: Airtime Co-founder Sean Parker has said that he is now 'bored' by Facebook. Parker was the first investor in the company

Sean Parker, Facebook's first investor, has said that he is now 'bored' by the company - despite having made a fortune from the company.

‘Facebook isn’t helping you make new connections, Facebook doesn’t develop new relationships, Facebook is just trying to be the most accurate model of your social graph,’ said Parker this week.

'There's a part of me that feels somewhat bored by all of this.'

But Parker said that a recent analyst report that Facebook would have gone the way of former internet titans such as Yahoo by 2020 was wide of the mark.

'Facebook is such a basic utility. It's something that is such a part of peoples' lives, I think it's hard to imagine it going away,' said the billionaire tech investor, one of the driving forces behind online music company Spotify.

Parker spoke out this week as he launched an app designed to use Facebook's store of knowledge about people to enable online video chat with people they might like - Airtime.

The app will operate within Facebook.

Parker no longer works for the company - and is said to have lost $820 million of his multi-billion fortune in share value in the wake of Facebook's recent wobbly IPO.

He has had several high-profile public spats with Mark Zuckerberg since leaving the company.

Mark 
Zuckerberg surprised users when he checked out the video chat service 
for himself this week.

Parker was played by Justin Timberlake in the film The Social Network

Created
by Napster founders Sean Parker and Shawn Fanning, Airtime is a 
one-on-one video chat service that allows users to share live video with
their Facebook friends, as well as strangers who have similar 
interests.

One New 
York blogger, Ronen V, tried out the new app today and was shocked when 
Zuckerberg was the first 'stranger' he chatted to.

Airtime app: Mark Zuckerberg was among the first users of new Facebook app, Airtime, today. New York blogger, Ronen V, left, only had time to thank Zuckerberg for creating Facebook before the billionaire moved on to talk to someone new on the video chat service

The app appears as a split screen with the user on the left side and the person they are chatting to on the right.

So Ronen V could see the billionaire Facebook founder when he popped up using the chat-a-stranger feature.

'I was still figuring it out, it was my first ‘random’ airtime chat,' Mr. V. told Betabeat.com. 'Once I realized who he was, I just thanked him for making Facebook. After like 30 seconds he NEXTed me.'

When users no longer want to talk to the person they are chatting with – they press the Next button to speak to someone new.

Conversely,
if you like the person you are chatting to you can reward them with 
stars, which will earn them badges and a higher credibility rating. 

Video chat: Created by Napster founders Sean Parker and Shawn Fanning, Airtime is a one-on-one video chat service that allows users to share live video with their Facebook friends, as well as strangers who have similar interests

The app lets people connect with random users based on locations, mutual Facebook friends and shared interests.

‘Create shared experiences with people you know, and people you want to know,’ is the app’s motto. 

Airtime users remain anonymous until they decide to reveal their names and other information.

As well as chatting, users can watch YouTube videos together. Sharing live music listening and photos may be added later.

'When
you jump on this product, you're immediately sharing, you're 
immediately having fun,' Parker said at today's launch in New York.

Glitches: Airtime Co-founder Sean Parker joked his way through the technical problems that arose at the app's launch in New York on Tuesday morning

Despite roping in major celebrities, 
including Hollywood actor Jim Carrey, rapper Snoop Dogg and singer 
Alicia Keys, the app's launch was not an unqualified success.

The demo for the new product failed one user-interaction test after another. 

'The
glitches from this morning's launch were generated by a custom built 
intranet for the event, not Airtime. We are happy to report the Airtime 
network is working and running smoothly,' a representative from Airtime 
told the Huffington Post.

Before the technical problems, Jimmy Fallon told the audience of journalists, techies and celebrities: 'You guys are going to flip out, this thing is super cool. It's going to blow your pants off.'

Watch video here

@highlight

First investor in social network says he is 'somwhat bored' by Facebook