France's under pressure power grid could struggle to cope if growing numbers of electric car owners all recharge their batteries when they sit down for dinner, the industry said today.

The warning comes after French car-maker Renault launched its long-awaited electric car Zoe this month at a price on a par with petrol models, making it the first electric vehicle with mass-market potential.

The government, meanwhile, has been encouraging the technology with generous subsidies.

But this comes in a country with a power 
grid that is already extremely sensitive to spikes in demand because of 
its high reliance on electric heating.

Power bosses have warned of the effect of an increasing number of people using electric cars after the Renault Zoe, the first with mass market potential, was launched

Though the prospect of a fleet of hundreds of thousands of electric cars remains some distance off, France needs to consider how it will cope when cold winter evenings prompt households to turn on the heaters, lights and electric gadgets at the same time.

Olivier Grabette, head of R&D at French power grid RTE, said: 'If it's badly managed, it could prompt power surges, which would cost a lot in peak production, CO2 emissions and would also necessitate the construction of relatively costly infrastructure.'

Grabette said that under the 'ambitious' scenario of a fleet of two million electric vehicles by 2020, total French annual electricity consumption would rise by 1 to 3 per cent.

'It's not huge in terms of energy,' Grabette said. 'But if all these vehicles charge at peak times, even with slow car chargers, it could add between 3 and 6 gigawatts (GW) of peak demand, which would be felt if it comes at the wrong moment.'

Data last year from U.S. eco-town Mueller, in Texas, showed that owners of electric cars typically plugged in their vehicles when home electricity use spiked, causing potential problems for the grid.

The heavy reliance on electrical 
heating in France was instigated by successive governments to absorb 
surplus nuclear power. Its 19 nuclear power plants make France Europe's 
biggest electricity exporter and ensure generally steady power supplies.

However,
 it lacks flexible capacity - usually generated by gas, coal or 
oil-fired plants - to meet peak evening demand during cold snaps.

Under pressure: Electric pylons which are part of the grid in Albertville, Savoie, France

Renault's decision not to provide chargers compatible with home sockets, thereby requiring Zoe owners to buy 'Wall-Box' chargers, could soften the impact.

Peak demand has hit record highs in each of the past 10 winters. In February last year demand at one point hit more than 102 GW and pushed the network to its limits, obliging France to import a record 9 GW.

RTE and other state agencies identified the problem in a 2011 report and recommended car chargers that take up to eight hours to recharge a vehicle. Though quick chargers do the job in about 30 minutes, these draw more energy than a dozen electric hot-water heaters.

There is also the problem of a geographical concentration of cars drawing power from quick chargers; at supermarkets, motorway service stations or business districts, for instance.

'The issue is not the total number of vehicles, it's how they will spread - and we think they will spread in clusters,' said Laurent Schmitt, Smart Grid vice-president at French engineering company Alstom.

'You can have only 1,000 cars, (but) if 500 of these are connected to the same building, you'll have a problem with this building and the neighbourhood around it,' he said.

'The issue is not the total number of vehicles, it's how they will spread - and we think they will spread in clusters.'

Alstom's vice-president

The key could be off-peak charging via 'smart grids' able to communicate with chargers that can then be operated remotely.

'There could be a problem, if we're not careful, in terms of peak capacity,' said Bruno Dobrowolski, in charge of the electric vehicle programme at ErDF, the electric distribution arm of state-owned utility EDF. 'That's why smart charging is necessary.'

French Industry Minister Arnaud Montebourg, the first Renault client to be handed the keys of a Zoe, has appointed a committee to advise on the expansion of the charger network.

Renault's decision not to provide chargers compatible with home sockets, thereby requiring Zoe owners to buy 'Wall-Box' chargers, could soften the impact. In Britain, Renault will subsidise the cost when the car is launched there in June.

The partly state-owned carmaker says owners could also use smartphone apps to set charging times depending on power prices.

'If it is developed well, in a coordinated way, it isn't a problem and could even help to rebalance a network, especially by integrating more renewable energy,' RTE's Grabette said.

Electric cars' batteries could smooth the variability of wind and solar energy by storing wind power produced at night and injecting it back to the grid when it needs help, he said. Such vehicle-to-grid systems are already being tested in the United States and Japan.

Alstom's Schmitt said France has domestic industrial players in each of the necessary fields of expertise, but the government needs a strong hand to ensure an integrated approach.

'You don't need to work with 10,000 players, but five or 10 who are leaders in their field. However, that raises the issue of the big players' egos,' Schmitt said.

 

@highlight

Warning comes after Renault launched electric car with mass potential

@highlight

Government has been encouraging technology with generous subsidies

@highlight

French grid already sensitive to demand spikes due to electric heating