Foreign television fans are enjoying BBC programmes for almost a third of the price charged to UK licence fee payers.

Millions of people across Europe, Australia and Canada are watching the best of the BBC for as little as £52 a year, or £4.33 a month.

An annual pass for thousands of hours of drama, comedy and documentaries is available for just £52, compared to the £145.50 licence fee paid by Britons at home.

For as little as £4 a month people overseas can access BBC iPlayer online while UK residents are forced to pay £145 for a licence fee whether they watch the channel or not

And overseas users get access to a vast vault of priceless BBC archive material unavailable to British viewers.

The disparity last night led to calls for the broadcaster to use the money to reduce the licence fee. 

Tory MP Conor Burns, a member of the Commons culture, media and sport select committee, said the profits should be used to save domestic viewers money. 

He added: ‘I am very much in favour of the BBC commercialising content and using the revenue to create more innovative, good quality British-made productions.

But it is an outrage that  they are selling content to  foreign nationals at a cheaper rate than to those in the UK who are obliged to pay the licence fee.

‘The licence fee is a poll tax. People in Britain, if they have a TV, have no choice, whether they watch the BBC or not.’

The BBC is quietly expanding the availability of the internet-based Global iPlayer – which is not available in the UK – after launching a ‘pilot’ more than two years ago.

It can be accessed across Western Europe, as well as in Australia and Canada.

European subscribers pay €7.99 a month (£6.70) or €74.99 euros a year (£63), which works out at £5.25 a month. In Australia the annual cost is even cheaper at 89.99 Australian dollars (£52.50) while in Canada access costs just 84.99 (£52) Canadian dollars – £4.33 a month.

The BBC is quietly expanding the availability of the internet-based Global iPlayer ¿ which is not available in the UK ¿ after launching a ¿pilot¿ more than two years ago.

For this, viewers can access 2,000 hours of shows on demand via their iPad or iPhone.

The Global iPlayer also offers the back catalogues of landmark comedies such as Blackadder and Fawlty Towers.

One Canadian viewer wrote: ‘At last decent programming! Canadian Dollars 85 for a year is NOTHING for what you get to see or listen to.’

Foreign viewers are not offered live streamed content, radio or an identical catch-up service to that which is available in Britain. 

But the vast majority of  BBC radio programmes can be accessed through the internet anywhere in the world. Last year, BBC Worldwide, which is behind the move, revealed the iPlayer has already been downloaded over a million times overseas.

The Global iPlayer is only available through the iTunes ‘app store’ which means, as with all other services, 30 per cent of all revenue is handed to US tech giant Apple.

Just last month the BBC revealed a record number of domestic households are watching programmes online, fuelling fears they are legally dodging the licence fee.

It is thought many viewers who use the iPlayer service do not own televisions, meaning they are not required to pay the licence fee. 

A TV licence is required for viewing programmes online only when broadcast in their scheduled slots or streamed live, as in the case of events such as Wimbledon.

A BBC spokesman said; ‘Unlike the UK BBC iPlayer, the Global iPlayer is not a seven-day catch-up service, and it does not offer the same breadth or amount of content available to the UK licence fee payer.

Profits generated by BBC Worldwide are returned to the BBC for the ultimate benefit of the licence fee payer.’

@highlight

Millions abroad have cheap access to shows which cost UK viewers £145.50

@highlight

The BBC is quietly expanding the availability of the internet-based Global iPlayer

@highlight

Spokesperson said profits are returned to BBC for 'ultimate benefit of licence fee payer'