The Royal Family might be more popular than ever before but the majority of Britons think funding for some parts of the institution should be cut.

Although taxpayers are happy to fund the Queen, the Duke of Edinburgh, Prince Charles, the Duchess of Cornwall, the Cambridges and Prince Harry, a new poll has revealed that most want the rest to take a pay cut.

That would mean Prince Andrew, the Princess Royal, the Wessexes and Princesses Beatrice and Eugenie, among others, losing any form of public subsidy.

Slimmed down: The majority of voters want a 'core' Royal Family comprised of the heir and his family

Currently, the Royal Family is funded by a combination of the Sovereign Grant, which replaced the annual Civil List payment and three other grants in 2011, and money from the Duchies of Lancaster and Cornwall.

The Sovereign Grant is taken from the revenues generated by the Crown Estate, a portfolio of properties and investments formerly owned by the monarch but now the Government, with the Royal Family being handed a total of £13.7m a year to cover the cost of official duties.

Although taxpayers do not directly fund any royal activity, they do bear the cost of providing police protection teams for royals and politicians, which funded via the Home Office.

The new poll, which was conducted by YouGov, asked voters which royals should be funded by the Sovereign Grant and the Royal Duchies.

69 per cent said the Queen and Prince Philip should continue to get funding, with 89 per cent of Conservative voters agreeing, compared to just 58 per cent of Labour voters.

Who should be paid? According to a new poll, only the Queen, Charles, the Cambridges and Prince Harry

New look: If the rules were implemented, Prince Andrew and his daughters would be among those to miss out

A similar number thought the same about Prince Charles and the Duchess of Cornwall, while another 59 per cent said the same of the Duke and Duchess of Cambridge and Prince George.

By contrast, just 28 per cent said Prince Andrew should receive a subsidy with a similar number saying the same about Prince Edward.

39 per cent said the Princess Royal should receive public money but just nine per cent said the same of Princesses Beatrice and Eugenie.

Although neither Zara Tindall or Peter Phillips are given any form of funding, 10 per cent of Britons said that they should be - more than the number happy to see payments to the Queen's cousins continue.

Royal cousins who perform official duties and are given a subsidy from the Sovereign Grant include the Duke and Duchess of Gloucester and Prince and Princess Michael of Kent.

Royal Duchies: The Queen and Prince Charles are the holders of Royal Duchies Lancaster and Cornwall

Funding: Harry, William, Kate and George are mostly funded by Prince Charles' Duchy of Cornwall

The concept of a slimmed down Royal Family, although popular, is not a new idea and features heavily in Prince Charles' plans for the future of the monarchy.

His idea, featuring a 'core' Royal Family comprised of himself, Camilla, Prince Harry and the Cambridges, has already been mooted and has met with some opposition.

Prince Andrew is believed to be particularly upset at 'being pushed to the margins' of royal life and was reportedly furious after his daughters were dissuaded from taking on royal duties.

Charles, who has been given an enhanced role since the Diamond Jubilee in 2012, was apparently also behind the slimmed down version of the Royal Family that appeared on the Buckingham Palace balcony during the Jubilee Flypast the same year.

Andrew, his daughters, and the Wessexes were also excluded from Prince George's Christening in October 2013, with the Cambridges apparently preferring a smaller ceremony with 'close' family and friends in attendance.

Since then, the two York princesses have become increasingly career-focused, with Beatrice taking on a role, now ended, at Sony, while Eugenie has moved to New York to work as an art dealer. 

Grant: Princess Anne and Prince Andrew are part-funded by the Sovereign Grant and Duchy of Lancaster

Cutting down: Just 28 per cent of those asked said the Wessexes should continue to be funded

No cash: Even less, just nine per cent, thought Beatrice and Eugenie should receive public money

Held by the monarch and his or her heir, the Duchies of Lancaster and Cornwall have been the main source of Royal funding for centuries.

Lancaster, the larger of the two, is owned by the Queen who also bears the subsidiary title of the Duchess of Lancaster.

Established in 1265, the Duchy was founded by Henry III when he made a gift of some land to his son Edmund.

A century later, Edmund's grandson Henry of Grosmont was given the title of Duke, making the Lancaster landholding into a Duchy.

The Dukedom also played a key role in the Wars of the Roses, with the Lancasters going on to triumph when Henry VII won the Battle of Bosworth Hill. 

Today, the 18,454ha estate includes a number of London properties, the majority of which are close to the Savoy in central London and were amassed by John of Gaunt - the royal scion who built the original Savoy Palace.

The younger of the two royal duchies, Cornwall was established in 1337 by Edward VIII to provide funding for his son, Edward, Prince of Wales or, as he is better known, the 'Black Prince'.

Comprised of a significant chunk of Cornwall, parts of Devon and Dorset, and the Isles of Scilly, it is automatically passed on to each successive Prince of Wales.

When  Charles becomes king, he will also take on the title Duke of Lancaster while Prince William takes Duke of Cornwall. 

In theory, Prince Harry should then become Duke of York, the title traditionally given to a monarch's second son, although whether or not that will happen is yet to be decided. 

 

@highlight

The majority want to stop funding 'minor royals' such as Prince Andrew

@highlight

Most royals are funded by Sovereign Grant and Duchy of Lancaster

@highlight

Charles, Camilla, Harry and Cambridges also funded by Duchy of Cornwall

@highlight

Taxpayers do not directly fund royals with money taken from Crown Estate

@highlight

Crown Estate is a Government-owned portfolio of land and other property 