Control over £6billion in health spending could be handed to  Manchester in a national first.

Chancellor George Osborne is expected to announce the radical plan, which will see all NHS funding devolved from Westminster to the region, later this week.

It is part of the creation of a powerful new body covering the whole of Greater Manchester, but critics warn that a time of intense pressure on NHS budgets it could be a 'poisoned chalice' for the region.'

Hospitals across Greater Manchester, including Stepping Hill hospital in Stockport, could be funded locally under radical plans to devolve health spending

Under the deal, full control health spending - worth £6billion-a-year - will be devolved to Greater Manchester.

A leaked draft memorandum of understanding includes the creation of a new board to distribute funding and take decisions in areas such as personnel, regulation, information-sharing and NHS buildings.

It would work closely with existing clinical commissioning groups (CCGs) of GPs.

In a surprise move the transfer of NHS funding to 10 local councils would happen very quickly, taking effect from April next year.

Chancellor George Osborne said today: 'We're discussing a plan for bringing together the NHS and social care in Manchester so we provide better care for patients.

'This is exactly what we want to see more of in our health care. It's also about giving Greater Manchester more control over things run in Greater Manchester - which is what our vision of a northern powerhouse is all about.

'It's early days, but I think it's a really exciting development. We'll be working hard now with Greater Manchester and NHS England on getting the details right so the arrangements work best for patients.'

The region has already accepted the creation of a powerful 'metro mayor' in return for taking over responsibility for transport, skills and housebuilding and the right to recoup some money generated by growth.

The Greater Manchester Combined Authority (GMCA) eventually hopes for full devolution of all £22billion of public spending in the city.

But any move to combine health budgets - currently held by NHS England - with councils' existing social care duties had been thought to be some way down the line.

However, devolving health spending to local areas could risk creating 'postcode lotteries' with differing levels of care and clinical priorities. 

NHS England's chief executive Simon Stevens said: 'NHS England is working on this ground-breaking offer to the local NHS in Greater Manchester, working in partnership with elected local authorities.

'The NHS five-year forward view says we want to back local leaders and communities who come together to improve health care of their residents and patients. While this new model won't necessarily be right for many other parts of England, for Greater Manchester the time is right and conditions are right for shared success.' 

In a speech in Manchester last month, George Osborne promised to hand control over spending and growth to the north west

Richard Humphries, assistant director of the King's Fund think tank, said that a full transfer of responsibility would be a reform 'on a breathtaking scale' but could pose serious risks.

He warned that taking money away from CCGs and NHS England to give it to councils was on 'the nuclear end of the spectrum and raises all sorts of questions and risks'.

He told BBC Radio 4's Today programme: 'Depending on the detail - and the detail is really crucial and we don't have that yet - you could either see this as a triumph for local democracy or creating real risks of yet another reorganisation of the NHS when it's barely recovered from the last one.'

With the NHS 'heading for the financial rocks', there were also concerns about accountability and financial risk with the NHS, he said.

'If the plan is to give the money to local government, the words 'chalice' and 'poisoned' perhaps spring to mind.'

The post of police and crime commissioner for Greater Manchester Police - established by the coalition Government - will also be scrapped in favour of the new mayor. 

Mr Osborne has hailed extended powers for cities as a key part of efforts to create a 'northern powerhouse' to rival London economically. 

@highlight

George Osborne expected to announce radical plan later this week

@highlight

New health board would make decisions on spending, staff and buildings 

@highlight

Major shift in control from Whitehall could happen from April next year

@highlight

Comes ahead of creation of a Boris-style mayor for Greater Manchester

@highlight

Intense pressure on NHS budgets mean difficult decisions need to be made