The hunt for alien life has been given a boost after scientists discovered a habitable planet almost the same size as Earth.

Astronomer Thomas Barclay from Nasa’s Ames Research Centre in California made the discovery using data collected by the Kepler space telescope.

The unnamed planet was found orbiting an unidentified star in its so-called Goldilocks zone - a region around the star that emits just enough energy, light and temperature for liquid surface water to appear.

Nasa's California Ames Research Centre used data taken from the Kepler space telescope to discover a total of five planets orbiting an unnamed M1 dwarf star, stock image pictured, with one said to be around 1.1 times the size of Earth. This planet sits on the outer edge of its star's habitable zone

M dwarfs are stars that are much smaller and dimmer than Earth’s sun, and aren’t bright enough to be seen with the naked eye.

Also known as red dwarfs, these stars make up around 70 per cent of all the stars in the galaxy.

Scientists originally discounted the theory that planets around M dwarfs could be habitable because the stars give out such little light and heat, compared to our sun.

However, in 2005, astronomers began searching for habitable planets around these dim stars.

The planet recently discovered by Nasa’s Ames Research Centre is what’s called a goldilocks planet, orbiting around an M1 dwarf. 

Goldilocks are planets that orbit inside a star’s habitable zone - a zone in which proximity to the host star is a certain distance that temperatures on the surface are suitable for water to appear.

Mr Barclay made the announcement during the Search for Life Beyond the Solar System conference in Arizona.

Using the Kepler images, Mr Barclay said he believes he has found a new star system consisting of five planets orbiting an M1 dwarf star.

M dwarfs are stars that are much smaller and dimmer than Earth’s sun, and aren’t bright enough to be seen with the naked eye.

Also known as red dwarfs, these stars make up around 70 per cent of all the stars in the galaxy and range in size.

By comparison, our sun is called a G dwarf, and these type of dwarfs account for only 5 per cent of stars in the universe.

The outermost planet in Barclay’s five-planet system is said to be 1.1 times the size of Earth and is called a goldilocks planet because it orbits within the M1 dwarf’s habitable zone.

Although other Earth-like planets have been discovered previously, Barclay’s unnamed goldilocks planet is believed to be the closest in size to our own.

Nasa's Kepler launched in 2009 with the purpose of hunting for Earth-like planets. It discovered a planetary system last April featuring Earth-size planets in a 'habitable zone.' Kepler-62f, pictured right on this illustration, is 1.4 times the size of Earth, while Kepler-62e, pictured bottom left, is estimated to be 1.6 times larger

Nasa’s Kepler mission launched in 2009 with the sole purpose of hunting for Earth-like planets.

It discovered a planetary system last April that featured Earth-size planets in an 'habitable zone.’

Dubbed Kepler-62 system, it has five planets in total called 62b, 62c, 62d, 62e and 62f.

Kepler-62f is about 1.4 times the size of Earth, while Kepler-62e is estimated to be 1.6 times larger.

Kepler-62 and the Solar System: The diagram compares the planets of the inner solar system to Kepler-62, a five-planet system about 1,200 light years from Earth in the constellation Lyra discovered last April. Until now, these were the closest planets to Earth, in terms of size

Both planets are thought to be rocky,
 or made mostly of ice, and until now were believed to be the most 
likely to be Earth 'doubles'.

No other details about Mr Barclay’s discovery have been announced and the official findings are due to be released later this year.

Nasa's
 Kepler
 space telescope has detected almost 3,000 candidate 
planets outside our solar system - a fifth of which are believed to be 
'super-Earths' between 1.25 and twice the size of the Earth.

The Kepler space observatory, named 
after the 17th century German astronomer Johannes Kepler, was launched 
on 7 March 2009 to scan a portion of the Milky Way for Earth-size 
planets that could harbour life.

The research team used data from 
Nasa's Kepler space telescope, which simultaneously and continuously 
measures the brightness of more than 150,000 stars every 30 minutes.

When
 a planet candidate transits, or passes, in front of the star from the 
spacecraft's vantage point, a percentage of light from the star is 
blocked. This causes a dip in the brightness of the starlight that reveals the transiting planet's size relative to its star.

The size of the star must be known in order to measure the planet's size accurately.

To
 learn more about the properties of the stars, scientists 
examined sound waves generated by the boiling motion beneath the surface
 of the star.

They 
probe the interior structure of stars just as geologists use
 seismic waves generated by earthquakes to probe the interior structure 
of Earth.

The science is called asteroseismology.

The sound waves travel into the star and bring information back up to the surface and these waves cause oscillations that Kepler observes as a rapid flickering of the star's brightness.

Small stars ring at high tones while larger stars boom in lower tones.

The barely discernible, high-frequency oscillations in the brightness of small stars are the most difficult to measure.

This is why most objects previously subjected to asteroseismic analysis are larger than the sun.

@highlight

The host star hasn’t been named but was identified as an M1 dwarf

@highlight

M dwarfs make up 70% of stars in the galaxy and are smaller than our sun

@highlight

Nasa astronomers found a total of five planets orbiting this unnamed host

@highlight

The outermost planet sits in the star’s habitable zone and may have liquid water on its surface

@highlight

This so-called goldilocks planet is believed to be 1.1 times the size of Earth

@highlight

Until now, the most Earth-like planet was Kepler-62f - 1.4 times the size

@highlight

Details of the new star system are due to be announced later this year