By 
Damien Gayle

PUBLISHED:

04:45 EST, 3 December 2012


| 

UPDATED:

09:16 EST, 3 December 2012

Volcanic eruptions could be the source of large changes in the sulphur dioxide levels in the atmosphere of Venus, say scientists studying data from a satellite orbiting the world.

Venus is covered in hundreds of volcanoes, but whether they remain active today is much debated, providing an important scientific goal for researchers studying the planet.

The planet's thick atmosphere contains over a million times more sulphur dioxide as Earth's. On our own planet almost all the pungent, toxic gas is generated by volcanic activity.

Scroll down for video

Heating up: An artist's impression of a volcano on Venus. New evidence from a satellite orbiting the planet suggests that its volcanoes may be active and could be the source of fluctuations in atmospheric sulphur dioxide

Most of the sulphur dioxide on Venus is hidden below the planet’s dense upper cloud deck, because the gas is readily destroyed by sunlight.

That means any sulphur dioxide detected in Venus’ upper atmosphere above the cloud deck must have been recently supplied from below.

The European Space Agency's Venus Express mission has already found clues pointing to volcanism on geologically recent timescales, within the last few hundreds of thousands to millions of years.

Venus Express is a satellite optimised for studying the atmosphere of Venus, from the surface right up to the ionosphere. It has been successfully operating in orbit around Venus since April 2006.

A previous analysis of infrared radiation from the surface pointed to lava flows atop a volcano with a composition distinct from those of their surroundings, suggesting that the volcano had erupted in the planet’s recent past.

Now, an analysis of sulphur dioxide concentration in the upper atmosphere over six years provides another clue. 

Fluctuations: The rise and fall of sulphur dioxide in the upper atmosphere of Venus over the last 40 years, expressed in units of parts per billion by volume (ppbv)

Immediately after arriving at Venus, the spacecraft recorded a significant increase in the average density of sulphur dioxide in the upper atmosphere, followed by a sharp decrease to values roughly ten times lower by today.

A similar fall was also seen during NASA’s Pioneer Venus mission, which orbited the planet from 1978 to 1992.

At that time, the preferred explanation was an earlier injection of sulphur dioxide from one or more volcanoes, with Pioneer Venus arriving in time for the decline.

Investigation: Venus Express is a satellite optimised for studying the atmosphere of Venus, from the surface right up to the ionosphere. It has been successfully operating in orbit around Venus since April 2006

Named for the Roman goddess of love and beauty, Venus is the second closest planet to the Sun and completes its orbit every 224.7 Earth days.

After the Moon, it is the brightest natural object in the night sky, bright enough even to cast shadows on Earth.

Venus reaches its maximum brightness shortly before sunrise or shortly after sunset, for which reason it has been referred to by ancient cultures as the Morning Star or Evening Star.

The Ancient Greeks believed Venus to be two separate bodies, calling the morning star Phosphoros, the 'Bringer of Light', or Eosphoros, the 'Bringer of Dawn'. The evening star they called Hesperos, the 'star of the evening'. By Hellenistic times, they realized the two were the same planet, which they named after their goddess of love, Aphrodite.

Hesperos would be translated into Latin as Vesper and Phosphoros as Lucifer ('Light Bearer'), a poetic term later used to refer to the fallen angel cast out of heaven.

Venus has an extremely dense atmosphere, which consists mainly of carbon dioxide and a small amount of nitrogen. Pressure at the planet's surface is about 92 times that at Earth's surface — a pressure equivalent to that at a depth of nearly 1km under the sea.

The CO2-rich atmosphere, along with thick clouds of sulfur dioxide, generates the strongest greenhouse effect in the Solar System, creating surface temperatures of at least 462 °C

Dr Emmanuel Marcq of Laboratoire 
Atmosphères, Milieux, Observations Spatiales, France, said: 'If you see a
sulphur dioxide increase in the upper atmosphere, you know that 
something has brought it up recently, because individual molecules are 
destroyed there by sunlight after just a couple of days.'

Dr
Jean-Loup Bertaux, principal investigator for the instrument that made 
the detections, added: 'A volcanic eruption could act like a piston to 
blast sulphur dioxide up to these levels, but peculiarities in the 
circulation of the planet that we don’t yet fully understand could also 
mix the gas to reproduce the same result.'

Venus has a ‘super-rotating’ atmosphere that whips around the planet in just four Earth-days, much faster than the 243 days the planet takes to complete one rotation about its axis.

Such rapid atmospheric circulation spreads the sulphur dioxide around, making it difficult to isolate any individual points of origin for the gas.

Dr Marcq’s team speculate that if volcanism was responsible for the initial increase, then it could come from a relatively gentle increased output of several active volcanoes rather than one dramatic eruption.

'Alternatively, and taking into account the similar trend observed by Pioneer Venus, it’s possible that we are seeing decadal-scale variability in the circulation of the atmosphere, which is turning out to be even more complex than we could ever have imagined,' he noted.

'By following clues left by trace gases in the atmosphere, we are uncovering the way Venus works, which could point us to the smoking gun of active volcanism,' added Håkan Svedhem, ESA’s Project Scientist for Venus Express.

VIDEO: NASA Scientist discusses agency's research into Venus Volcanoes:

@highlight

Scientists have not yet reached consensus on whether the planet's volcanoes remain active

@highlight

Fluctuations in levels of sulphur dioxide seem to suggest the atmosphere of Venus is being affected by volcanic activity