By 
Daily Mail Reporter

PUBLISHED:

08:20 EST, 21 September 2013


| 

UPDATED:

11:25 EST, 21 September 2013

The most powerful typhoon of the year was eyeing landfall on Hong Kong today as it swept past the Philippines and Taiwan, sparing those countries from the worst of its wrath.

Typhoon Usagi had gusts exceeding 163 mph this morning as it battered island communities in the Luzon Strait, according to the U.S. Navy's Joint Typhoon Warning Center.

China's National Meteorological Centre announced a red alert, its highest level, as the storm maintained its track toward Hong Kong and the manufacturing heartland of the Pearl River Delta.

Scroll down for video

Huge: Super Typhoon Usagi is seen heading west-northwest through the Luzon Strait in this shortwave infrared satellite image. The strongest storm in the Western Pacific this year was today headed for Hong Kong

The observatory warned that Usagi would also smash into coastal areas of Guangdong, Zhejiang and Fujian provinces.

The Hong Kong Observatory said today that Usagi was 406 miles east-southeast of the city.

It predicted that the storm's maximum sustained winds would weaken to 103mph by 2pm on Sunday as it approaches Hong Kong before making landfall overnight.

The observatory was maintaining a No. 1 Standby Signal and warned that the storm poses a 'severe threat' to the densely populated city, where windows were taped up in anticipation of the chaos. 

Blow me down: People in Taipei hold their umbrellas tight against powerful gusts of wind generated by Typhoon Usagi as the storm passed 342 miles south, sparing the country's coast from the worst of its wrath

Better off with a macintosh: People in Taipei struggle to keep dry in the heavy rain brought by the storm

A woman and her child hold their umbrellas tight against powerful gusts of wind: Gusts of nearly 150mph were recorded further south on the Taiwanese island of Lanyu in the Luzon Strait

Further south: A three-wheeled taxi lies on its side after being blown over by winds from Typhoon Usagi in the town of Hengtsun in south-east Pingtung county today as it swept past the southern parts of Taiwan

Waterfalls cascade on to a road close to Hengtsun: Nearly 2,500 people were evacuated from flood-prone areas and remote mountainous regions as Taiwanese soldiers were deployed into potential disaster zones.

As the storm passed 342 miles south of Taiwanese capital Taipei, the country's Central Weather Bureau said it was veering west, mostly likely sparing the country's south from the most destructive winds near its eye.

But gusts of nearly 150mph were recorded on the Taiwanese island of Lanyu, and the bureau warned that dangerous winds were buffeting the holiday resort of Kending on the Hengchun peninsula.

In the Philippines, the storm triggered landslides and power outages in parts of the north of the country, including the Batanes island group, where it made landfall early this morning.

No casualties have been reported.

The Filipino weather bureau warned that storm surges and heavy waves could cause damage in the Batanes and other islands in the Luzon Strait before Usagi blows past the country by tonight.

Is that really a good idea? A man and a boy sit inside a makeshift raft as they paddle through rough waves brought by Super Typhoon Usagi along the coast of Manila Bay in Navotas City, Philippines

A boy clings to a concrete bank as rough waves 
crash into Manila Bay: Usagi slammed into the Philippines' northern 
islands today, cutting communication and power lines, triggering 
landslides and swamping rice fields

Filipino children scamper across wrecked floating shanties at a
village in Paranaque city, south of Manila: The Filipino 
weather bureau warned that storm surges and heavy waves could cause 
more heavy damage tonight

A Filipino girl walks away from a shack: The 
Office of Civil Defense in Manila, the Filipino capital, said landslides
damaged houses and roads, and pockets of power outages were reported in
at least five northern provinces

A man walks past crashing waves at Manila's Baywalk area: The Philippines has avoided the brunt of the storm

In Taiwan, nearly 2,500 people were 
evacuated from flood-prone areas and remote mountainous regions as the 
government deployed military personnel into potential disaster zones.

The
storm system has dumped more than 8in of rain along the eastern and 
southern coasts in a 13-hour period, with officials warning that a total
rainfall of 39in could drop before the storm leaves tomorrow.

Local
officials closed mountain highways blocked by landslides and suspended 
train services connecting the east and west coasts as power outages 
affected thousands of homes.

Usagi
has a massive diameter of 680 miles, with its outer rain bands 
extending across Luzon and all of Taiwan across to the Chinese coast.

Frightening: An image taken from space by the Japanese Meteorological Agency's MTSAT-2 satellite yesterday

Getting ready: A man leaves a Hong Kong shopping mall where entrances are taped up in anticipation of the expected chaos that Usagi will bring when it makes landfall there on Sunday evening

Taiwan's Central Weather Bureau warned winds of 63mph could hit Taipei.

The Office of Civil Defense in Manila said landslides damaged houses and roads, and pockets of power outages were reported in at least five northern provinces, where several roads and bridges were impassable.

Cathay Pacific Airways and Dragonair said flights today were unaffected except for one canceled flight.

But both airlines warned of delays and cancelations at Hong Kong International Airport from tomorrow evening to Monday morning, and urged passengers to postpone non-essential travel on those two days.

@highlight

Gusts exceeded 163mph today as it swept through the Luzon Strait

@highlight

China announces red alert for Pearl River Delta manufacturing heartland

@highlight

Hong Kong Observatory warns of 'severe threat' to densely peopled city