By
Sarah Vine

Every time I see a picture of Helen Mirren, it gladdens my heart. There she is at a premiere, surrounded by women half her age and with twice as many stylists, and she looks better than the lot of them.

Better than Angelina (too thin), better than Gwynnie (too vanilla), better than Cara Delevingne or Kate Moss, women who make a living out of being beautiful.

What makes Helen so standout special is that she has an honest kind of beauty. She’s not trying too hard (Kim Kardashian), she’s sexy without being porny (Beyonce), she doesn’t have any weird affectations, such as Victoria Beckham’s pout or Anna Wintour’s fringe, and her smile always seems to reach her eyes.

Most notably, though, at 68 she is an example of how a mature woman can continue to turn heads long after her official sell-by date. If anything, she looks better now that she did in her theoretical prime.

Sarah Vine gives you her top tips on how to make your beauty regime turn you into Helen Mirren

And that’s because, contrary to what the magazines and ad agencies would have you believe, attractiveness has little to do with perfection.

All those hard-bodied, no-dairy, no-wheat, no meat, no-fun, fitness fascists aren’t beautiful, they’re just annoying — and extremely hungry.

Beauty is not about flawless skin or the perfect flat stomach. It’s holistic: a combination of style, confidence, personality, diet, decent genes, a good hairdresser and, of course, products.

Products are always a bit controversial for the older woman. Most women Mirren’s age, including my mother, think that my generation waste far too much money on lotions, potions and treatments.

It’s because they’re war babies; a pot of Pond’s is pushing the boat out for them. Even if my mother could have afforded Creme de La Mer, she wouldn’t have bought it on principle. She was the kind of person who melted down her old lipsticks.

So, with the ghost of all our mothers looking disapprovingly over their reading specs, I have chosen carefully when selecting my ultimate products for women over 50. Look no further ladies, this is all you need:

First is an all-time favourite of mine, Liz Earle’s Superskin Concentrate: (£40) 100 per cent natural, a blend of rosehip, argan, neroli and vitamin E.

It is nectar for older, dehydrated skins, and it smells like nectar, too. It’s best used at night, last thing before bed after a nice hot bath or shower. Warm a few drops between the palms of your hands, inhale the soothing scent and press it gently into your skin.

Co-enzyme Q10 (£12.92) is also one for mature ladies to watch out for. A powerful antioxidant that is naturally present in the body, it plays a key role in cell regeneration.

I have a theory about wrinkles: horizontal lines, good; vertical lines, bad. Horizontal lines come from laughing and squinting at the sun.

Vertical lines, the ones you get between your eyes and around the mouth, give you what’s known as ‘bitchy resting face’ (that’s a technical term). Not good.

What makes Helen Mirren so standout special is that she has an honest kind of beauty

And so onto my next product, Vichy’s Liftactiv Advanced Filler (£31, Boots). It contains the highest non-prescription levels of pure retinol, which is clinically proven to soften so-called ‘dynamic’ wrinkles (those generated by repeated muscle movement rather than ageing). Unlike most retinoids, this one is moisturising and suitable even for sensitive skins.

Every older woman should also pick up No 7’s Restore and Renew Day and Night Serum (£24.99), which is specifically designed for the over-60s. It aims to treat lines, lack of firmness, uneven pigmentation, fragility and dullness, and the ingredients are clinically proven.

And a cracking new all-rounder is Kiehl’s Super Multi Corrective Cream (£48). They’ve thrown the kitchen sink at this one, with ingredients such as hyaluronic acid and beech tree extract, and the result is a highly effective, comforting treatment that improves the feel and look of older skins. Aside from the face, the one area that you need to keep an eye on as the years roll by is the decolletage. Nothing is more annoying than a wrinkly cleavage.

UV rays are the real culprit, so Dr Ceuticals Neck and Chest Lift (£19.90, Boots) is ideal because it contains an SPF of 15 as well as tried and tested ingredients to improve skin elasticity and hydration.

Make-up wise, less is always more when you are over 50. You want light, translucent products that glide on and don’t get absorbed by thirsty skin. Armani’s Maestro Fusion Make-up (£39) combines effective coverage with a gossamer-like texture. You should also brighten and freshen up the eye area with a good illuminator: Guerlain’s Precious Light (£30.50) would be my choice. It’s a wonder product.

Guerlain would also be my suggestion for a bronzer — it’s one of the few cosmetics where you really do get what you pay for.

The Terracotta Four Seasons palette (£47) works all year round to add just a bit of pizzazz to dull skin.

Keep eyeshadow simple and clean: use soft golden pinks to flatter skin tone, and blend and blur as much as you can for a nice soft finish.

No7’s Shade and Define pencils (£8) are perfect, and they come in a good choice of neutral shades.

For lips, avoid highly pigmented lipsticks: they can look very harsh and unforgiving. Add a bit of Vaseline (£2.18) to your favourite lipstick for a fresher look and invest in Lipstick Queen’s colourless lip liner (£18), which will stop colour bleeding.

Lastly, if you dye your grey hair, get down to Marks & Spencer for colourist-to-the-stars Josh Wood’s innovative Blending Wand (£12.50). It’s indispensable between visits to the hairdresser. It’s foundation for hair: you paint on the colour and those pesky roots vanish in a flash.

Sisley's Eau de Soir

Sisley’s Eau de Soir (£78.50, John Lewis). My favourite. It’s gorgeous, warm and  glamorous without being overpowering.

Caron’s
 French Cancan. A soft, seductive woody floral, first formulated in 
1936. Order a sample for £3.50 from lessenteurs.co.uk (020 7730 2322).

Chanel
 Cuire de Russie (from £110). Created in 1927 by Coco following an 
encounter with a dashing Russian. Dark, daring and dangerous.

Creed Fleurs de Gardenia (from £95, Les Senteurs, as above). Like falling head first into a spring bouquet.

Annick Goutal Eau D’Hadrien (from £60, House of Fraser). Fizzy, fresh citrus with a cypress base. A lovely,  go-anywhere scent.

Actresses Jane Seymour, 63, and Jacqueline Bisset, 69, have voiced their disapproval of Botox, saying they would never consider it as a way of staving off old age.

‘As an actress, this is my canvas,’ says Seymour. ‘I stay away from Botox and all these things because I need my wrinkles.’

Hmm. Anyway, a few years ago I would have been in complete agreement with them. Until very recently, pretty much anyone who had Botox just ended up really weird and shiny.

Parts of Liverpool, London and LA were starting to look like that episode of Doctor Who when the mannequins come to life and try to take over the world.

Then came the killer blow: Jordan had it live on telly. A backlash was inevitable. Thing is, Botox — used correctly and judiciously — is actually rather brilliant. The effects can be subtle, but extremely effective.

Nicole Kidman used to have botox treatments in the past

The real issue is that though Botox is a prescription drug, anyone can administer it.

There are people offering Botox who have no more knowledge or understanding of the way the facial muscles work and interact with each other than the postman.

This is something that irks not just Botox’s critics, but also those responsible practitioners who know what they’re doing. The British Association of Aesthetic Plastic Surgeons has been banging the legislation drum for years, pleading for the Government to make it impossible for anyone except a qualified medical professional to administer the substance.

And still they resist. This month’s report on proposals to regulate the cosmetic surgery industry (following the PIP implant scandal) was about as much use as a chocolate teapot. 

I am lucky: my job gives me access to the best in the business — the likes of Dr Vicky Dondos, Dr Terry Loong and Dr Frances Prenna Jones.

I have Botox to try to reduce the size of my jaw muscles which, after years of tooth-grinding, are so over-developed they’re starting to alter the shape of my face. It’s subtle, and it works. And it’s not the root of all evil.

SHEALd Recovery Balm (£43, victoria health.com)This all-purpose balm is a godsend for older, compromised skins that are especially prone to scarring and splitting. Medicine cabinet or bedside table? Up to you.

Al PacinoI yield to no one in my admiration for Al Pacino. But look: he’s orange! Perhaps he’s been taking style tips from Simon Cowell. Next thing you know, he’ll be wearing his trousers around his armpits.

@highlight

At 68, Helen Mirren shoes how a mature woman can still turn heads

@highlight

Beauty is combo of style, confidence, diet and, of course, products

@highlight

Sarah has selected her ultimate products for women over 50