The fastest car ever built in Britain is being sold for £400,000 more than when it was new. 

The McLaren P1 - which can rocket from zero to 60mph in under three seconds - is available to purchase for £1.25million at a Hertfordshire showroom. 

There were only 375 of the supercar ever made and they were all snapped up despite the eye-watering £866,000 price tag.

But now a second-hand model is being sold at DK Engineering in Hertfordshire for almost £400,000 more - enough to buy 38 new Ford Fiestas. 

A black and white McLaren P1 (pictured) is being sold at a Hertfordshire showroom for £400,000 more than when it was new

The McLaren P1 - described by Autoweek as 'possibly the most exciting road car ever built' - is one of only 375 ever made

The supercar is powered by a 3.8litre twin-turbo V8 engine and can hit 124mph in under seven seconds and 190 in under 17

The McLaren P1 - described by Autoweek as 'possibly the most exciting road car ever built' - can hit 124mph in under seven seconds and 190mph in under 17.  

It is powered by a 3.8litre twin-turbo V8 engine and linked to a dual clutch seven-speed F1 style racing gearbox, which is equivalent to nine Ford Fiestas. 

The engine set-up promises 'instantaneous throttle response', according to McLaren. 

Car-mad comedy actor Rowan Atkinson was reported to be after one of the cars when it was released having secured a £910,000 insurance pay-out to restore his McLaren F1 after he crashed it.

The McLaren P1 on sale is a white and black model with only 21 miles on the clock. 

James Cottingham, from DK Engineering, said: 'When you have a limited supply and a really good car, you will often see a premium.

'We have seen it with the Ferrari Enzo, the Pagani Zonda and now we are seeing it with the McLaren P1.

'Just like with the Enzo and Zondas, the P1 is a truly rare car with less than 400 being built.

'It is a stunning piece of kit and very much a real supercar. I believe this is the first P1 to be sold in the UK and it only has delivery miles.

'We have had a lot of interest in it and we expect a buyer soon.'

The P1 was officially launched in Geneva in 2013 and is regarded as one of the great British cars - a second-hand model is available to buy

The car - which was sold new for £866,000 - is being sold at DK Engineering in Hertfordshire for £1.25million 

The car was launched officially at the Geneva Motor Show on March 5 2013, with the first deliveries in September to coincide with McLaren's 50th anniversary.

The P1 features Formula 1-derived race technology which the company says increases speed and acceleration.

It has an 'instant power assist system' that propels the car, rocket-like, from rest to 190mph in under 17 seconds – more than 35 per cent faster than even the F1. 

It also has lightweight batteries behind the driver store charge generated by the petrol engine but a plug-in charger can also be used to boost energy levels from empty to full in two hours.

As a result the car produces zero emissions when running on electric power only and has a range of 12.5miles at an average city speed of 30mph.  

The supercar has a top speed of 217mph, with McLaren claiming it can lap the notorious Nurburgring race track in less than seven minutes

It has alcantara seats, dash, door inserts, steering wheel and sun visors while a number of exterior parts have a carbon fibre finish

The McLaren P1 also has parking sensors, a meridian sound system, an ashtray and a fire extinguisher

 

 

@highlight

The McLaren P1 - which can rocket from zero to 60mph in under three seconds - available to buy for £1.25m

@highlight

There were only 375 of the supercar ever made and they were all snapped up despite the £866,000 price tag

@highlight

Second hand model, believed to be fastest ever built in Britain, is being sold at DK Engineering in Hertfordshire 