By
Chris Foy

Follow @@FoyChris

The last time England were in the ‘City of Sails’, they had become figures of fun and were mercilessly mocked as they made a shambolic exit from the World Cup.

That was three years and a veritable lifetime ago. The locals aren’t laughing at Stuart Lancaster’s national team now. The joke has long since worn off. Instead, Kiwis are coming to terms – somewhat grudgingly – with the fact that England are emerging as very serious challengers to their beloved All Blacks’ global pre-eminence.

Saturday’s tense first Test at Eden Park may just go down as the watershed occasion when the national team proved they really are capable of wresting the World Cup from New Zealand next year. Amid the devastation of losing a game they could have won, England will seize on some highly encouraging signs about their collective development.

VIDEO Scroll down to see Lewis Moody correctly predict an England first game loss

Knock-out blow: All Blacks centre Conrad Smith scored the decisive try with two minutes left to play

Time to shine: If England play their cards right, they can join a small group to have won in England

Heartbreak: England must bounce back from their loss and keep the series alive with victory in Dunedin

What a savagely-weakened line-up 
showed in this series opener was that they are amassing the depth of 
talent to be prime contenders at their home tournament next year. They 
exposed the fact that the All Blacks are afflicted by mortality — in 
defiance of popular myth — and also obliterated the notion that weary 
European teams must head south in June and meekly accept their medicine.

It
 is now evident that England are not battling demons on this side of the
 Equator. These tourists will not accept the age-old perception that in 
these parts, they are inherently inferior. English spirit no longer 
withers in the Antipodes, thanks to the conviction generated by 
heartening past results and the coaches’ ability to instil soaring 
confidence in their players, even those who have been out of form or 
lacking match-fitness.

Manu Tuilagi is a case in point. The last time he was here he was lampooned after jumping off a ferry for a dip in the harbour.

War dance: The All Blacks perform the haka ahead of kick off at Eden Park

On target: Freddie Burns kicks a penalty during England's first Test against New Zealand

Tuilagi
 hadn’t played for his country all season due to injury but he stormed 
back to prominence on Saturday. New Zealand had suffered from the 
Leicester centre’s marauding midfield presence during their record 
defeat at Twickenham 18 months ago and how they suffered again this 
time. The 23-year-old pounded the home defence and the Kiwis were simply
 unable to contain him.

After
 Conrad Smith’s late try had condemned Lancaster’s heroic side to a 
heart-breaking fate, Tuilagi cut a disconsolate figure. In days gone by,
 this result would have generated English satisfaction but not this 
time. The Tiger’s trademark grin was largely eclipsed by a stern 
demeanour as he made it abundantly clear that glorious failure would not
 suffice.

‘No-one is happy 
that we have lost today,’ he said. ‘A loss is a loss. It doesn’t matter 
if you lose by one point or 40 so the boys in the changing-room are 
gutted. I think we should have won. We had a few opportunities but we 
didn’t finish them. In games like this you are only going to get one or 
two chances and you have to take them.’

Bombing forward: Englandís Chris Robshaw makes a break against New Zealand at Eden Park in Auckland

Back with a bang: James Haskell is tackled Dane Coles on his England comeback

Clockwork: England's Geoff Parling rises highest to claim the ball from a line-out

On the charge: Israel Dagg makes a break from full back in the first Test

Asked
 if England’s progress was such that they now regard themselves as the 
All Blacks’ equals, Tuilagi added: ‘Absolutely. We showed that today. We
 played well, we held on to the ball well, we defended well. But it is 
all about those little margins. The good thing is we’ve got two matches 
left and we still have the opportunity to go for the series.’

To
 a man, England’s players and coaches lamented their cruel demise at 
Eden Park and expressed the view that they can fight back in this 
three-Test series by beating New Zealand in Dunedin this Saturday. Ben 
Morgan, who was outstanding at No 8, insisted that this result wasn’t a 
catalyst for belief among the tourists because they already possessed it
 in abundance.

‘We didn’t 
have any fear,’ said the Gloucester forward. ‘The confidence in our 
squad has been building over the last couple of years and we just feel 
stronger and stronger. We will go away from this game, rectify things 
and continue to improve. We believe in our squad and how we play. If you
 go into a Test match with elements of doubt you have lost before you 
begin.’

Flying winger: England's Jonny May attempts to beat the tackle of Liam Messam (left) and Ben Smith

Comeback: Aaron Cruden scored two penalties to put New Zealand back into the lead with ten minutes to go

Dangerous break: Kyle Eastmond charges at the New Zealand defence as England clear their lines

Quick ball: All Blacks scrum half Aaron Smith keeps the New Zealand attack ticking

There was no doubt 
or fear, which is an endorsement of the work done by England’s coaches. 
It was an occasion which provided further evidence that Lancaster and 
his assistants have the technical, tactical and motivational qualities 
to turn their team into a major global force.

Frankly,
 given the uniquely trying circumstances, the visitors were not expected
 to make a game of it. Forced to operate without around a dozen of their
 leading players the Red Rose management worked wonders to bring the 
best out of the men left standing.

Certain
 members of the starting XV had gone into this daunting fixture against a
 backdrop of poor or disrupted seasons but almost to a man they 
delivered, notably Freddie Burns and Kyle Eastmond as a raw 10-12 
combination. The fundamental point is that the England set-up now serves
 as a centre of excellence, enhancing those involved, and that has not 
always been the case. Players appear to grow in stature within the 
national ranks.

Heavy hitter: England No 8 Ben Morgan carries the ball upfield

Making yards: New Zealand's Brodie Retallick leaves England's Freddie Burns lying on the ground

Late blow: Marland Yarde is shown a yellow card by referee Nigel Owens after illegal play at the breakdown

Late charge: Danny Cipriani made an immediate impact after coming off the bench in the second half

Yet, for all
 the encouragement, a famous victory proved beyond captain Chris Robshaw
 and Co. They were not behind on the scoreboard until 10 minutes from 
time and when New Zealand snatched their late try, England were down to 
14 men as Marland Yarde was in the sin-bin.

Inexplicably,
 Ma’a Nonu and Malakai Fekitoa escaped yellow-card punishment for 
cynical acts of foul play and those were not the only dubious decisions 
made by referee Nigel Owens which hurt England. But they kept any sense 
of injustice under wraps — pointing instead to costly handling errors 
and a lack of clinical precision when chances were created.

The
 All Blacks were forced into a torrent of mistakes but when it mattered 
they found a way to win a Test they could have lost, which has become a 
hallmark under Steve Hansen. Yet, their profound relief will have been 
tempered by the knowledge that England are coming for them, with 
increasing purpose. In this series and in next year’s World Cup, the Red
 Rose is destined to become a symbol of danger, challenging Kiwi 
supremacy.

Powerful: Malakai Fekitoa of the All Blacks is hauled down by Ben Morgan and Geoff Parling

Deadly touch: Veteran centre Conrad Smith dives over in the corner at Eden Park

Jubilation: Conrad Smith is congratulated by team-mate Ben Smith after scoring the only try of the match

Valiant effort: Ben Morgan and Kyle Eastmond of England walk through the tunnel after the final Test

@highlight

England narrowly lost 20-15 to New Zealand at Eden Park

@highlight

All Blacks have not been beaten at their rugby citadel for 20 years

@highlight

A late try from Conrad Smith sealed dramatic victory for the Kiwis

@highlight

England were in front for most of the game thanks to penalties from Freddie Burns

@highlight

Danny Cipriani kicked a late penalty on his return to England action