Where there is muck there really is brass with scientists claiming that millions can be made by extracting gold from human waste.

In fact as well as gold, faeces contains platinum, silver and other metals along with rare elements such as palladium and vanadium.

Researchers now hope to 'mine' sewage reducing the need to mine raw metals from the ground, while reducing pollution by recycling human waste.

Scientists have discovered a literal goldmine of precious metals in human poo.The US researchers are investigating ways of flushing out the valuable minerals, including gold, silver and rare elements such as palladium and vanadium. Pictured are microscopic gold-rich and lead-rich particles in human waste

Taking a lesson from industrial mining, the scientists are experimenting with chemicals called leachates that are used to pull metals out of rock.

Some of these chemicals have a bad reputation for damaging ecosystems when they leak or spill into the environment. 

But in controlled conditions, they could safely be used to recover metals from treated solid waste, Dr Smith claims.

In the treated waste researchers already started to discover metals like platinum, silver and gold observing microscopic-sized metal particles in biosolids.

Previous research estimated the waste from one million Americans could contain as much as $12 million (£8.7 million) worth of metals.

In 1999 the UK produced over 1,130,000 tonnes of sludge dry solids, which averages to about 20kg generated by each person.

If Britain's waste was mined it could be worth $762 million (£510 million) a year.

Dr Kathleen Smith of the US Geological Survey said: 'If you can get rid of some of the nuisance metals that currently limit how much of these biosolids we can use on fields and forests, and at the same time recover valuable metals and other elements, that's a win-win.

'There are metals everywhere. They are in your hair care products, detergents, even nanoparticles that are put in socks to prevent bad odours.'

Yet all end up at the sewage works and many metals end up in the leftover solid waste.

At treatment plants, wastewater goes through a series of physical, biological and chemical processes and the end products are treated water and biosolids.

In the US alone seven million tons are leftover each year with half used as fertiliser on fields and in forests and the other half incinerated or sent to landfills.

Dr Smith added: 'We have a two-pronged approach.

'In one part of the study, we are looking at removing some regulated metals from the biosolids that limit their use for land application.

If Britain's waste was mined it could be worth $762 million (£510 million) a year. Previous research estimated the waste from one million Americans could contain as much as $12 million (£8.7 million) worth of metals.

'In the other part of the project, we're interested in collecting valuable metals that could be sold, including some of the more technologically important metals, such as vanadium and copper that are in cell phones, computers and alloys.'

The study aims to use the same chemicals, called leachates, which the mining industry uses to pull metals out of rock.

While some of these leachates have a bad reputation for damaging ecosystems when they leak or spill into the environment, in a controlled setting, they could safely be used to recover metals in treated solid waste.

In the treated waste researchers already started to discover metals like platinum, silver and gold observing microscopic-sized metal particles in biosolids using a scanning electron microscope.

'The gold we found was at the level of a minimal mineral deposit' meaning if that amount were in rock, it might be commercially viable to mine it.

Dr Smith added that 'the economic and technical feasibility of metal recovery from biosolids needs to be evaluated on a case-by-case basis.'

The study presented at the 249th National Meeting & Exposition of the American Chemical Society (ACS) involved collecting samples from small towns in the Rocky Mountains, rural communities and big cities.

For a more comprehensive picture, they plan to combine their information with many years' worth of existing data collected by the Environmental Protection Agency and other groups at the Geological Survey.

@highlight

Scientists looking for ways to flush out the valuable minerals from waste

@highlight

These include gold, silver and elements such as palladium and vanadium

@highlight

Waste from a million Americans could contain $12 million (£8.7 million)

@highlight

Britain's waste is worth an estimated $762 million (£510 million) a year