The Ebola virus is continuing its rampage throughout West Africa with the number of people infected doubling every three to four weeks.

So far, more than 8,000 people are thought to have contracted the disease, and almost half of those have died, according to the World Health Organisation.

In the battle to stem the virus, health organisations are turning towards data generated by social media and mobile technology - with some hoping it may even help find a cure.

Scroll down for video and interactive map 

Text messages are helping in the fight against Ebola in Sierra Leon with people receiving public health text alerts and sending messages about food security to aid agencies

For instance, text messages are helping in the fight against Ebola in Sierra Leone, with people receiving public health text alerts and sending messages about food security to aid agencies.

The initiative was started by the Word Food Programme (WFP) in an effort to source information about household food security for those at risk. 

So far, more than 850 people have responded to a survey which was sent to mobile phone subscribers randomly by location, and involved answering ten text messages.

'[An] advantage of mobile data collection is that is it quicker than sending around teams to do face to face surveys around the country,' said Jean-Martin Bauer, a WFP food security analyst.

Researchers are collecting mobile phone mast activity data from operators and mapping where calls to helplines are located. Pictured is an example of mobile phone data collected from Côte d'Ivoire to monitor Ebola by Flowminder.org

The Ebola virus is continuing its rampage throughout West Africa with the number of people infected doubling every three to four weeks. So far, more than 8,000 people are thought to have contracted the disease, and almost half of those have died, according to the World Health Organisation. Pictured on the left is a health worker, and on the left a demonstration hoping to stem the spread of Ebola

Big data is the term used to describe extremely large data sets that can be analysed to reveal widespread patterns, trends, and associations.

The amount of data is usually so large that it requires a computer to process the information, rather than just a person or group of people.

Big data is usually used to better understand human behaviour and trends within society - both on the small scale and globally.

'In a public health emergency, where the situation of communities is changing by the week, this helps WFP have more timely information to shape our response.'

The Red Cross and Red Crescent also hope to extend a text message-based system used to advise people about Ebola in to seven West African nations.

The facility will allow the charities to send SMS messages to every switched-on handset in an area by drawing its shape on a computer-generated map.

Meanwhile, the BBC has started sending Whatsapp alerts that include short audio clips and low-resolution photos to people threatened by Ebola.

Within just four hours of launching the service, more than 1,000 people signed up for its Ebola alerts, which are sent in both English and French.

As well as sending alerts, technology is helping health agencies monitor trends in outbreaks by their speed, number and location.

Zoom in on the interactive map to see areas affected by the Ebola outbreak. Move the markers on the bottom bar to change the date 

This year has seen the worst outbreak in history of the Ebola Virus Disease (EVD). The outbreak has a mortality rate of around 50 per cent. This scene shows bodies being taken away in Sierra Leone

One example is Harvard University's HealthMap which flagged up a 'mystery haemorrhagic fever' nine days before the World Health Organisation announced the Ebola epidemic.

The fever was seen developing in the forested areas of southeastern Guinea by a free online tool known as HealthMap on March 19.

Ebola emerged in 1976 in two simultaneous outbreaks in Sudan and near the Ebola River in the Democratic Republic of Congo.

There are several strains which vary in how dangerous they are to humans, but death rates have reached as high as 90 per cent.

In the current outbreak that is just over 50 per cent. It is introduced into humans through direct contact with the blood, organs or other bodily fluids of infected animals including fruit bats, which are eaten as a delicacy.

The virus then spreads between humans through direct contact with blood, organs or other bodily fluids of infected people.

Symptoms include fever, intense weakness, muscle pain, headache and sore throat followed by vomiting, diarrhoea, rash, impaired kidney and liver function, and in some cases, both internal and external bleeding.

People are infectious as long as their blood and bodily fluids contain the virus and the incubation period can range between two and 21 days.

Although the disease has no cure, modern medical treatment and quick isolation help hugely to bring the death toll down.

The US group behind the software started putting out alerts and providing information to the World Health Organisation, which reported its first confirmed case of Ebola on March 23.

Since then, the HealthMap team has created an interactive Ebola map, free to use by anyone who wants to see where the disease is spreading.

The map, run by scientists in Boston, uses algorithms to scour tens of thousands of social media sites, local news and government websites to detect and track disease outbreaks.

It then filters out irrelevant data to identify dangerous diseases and map their locations with the help of health experts.

'It shows some of these informal sources are helping paint a picture of what's happening that's useful to these public health agencies,' said HealthMap co-founder John Brownstein.

Ebola is transmitted by human contact, which means knowing where people are moving can provide valuable insight to researchers trying to contain the outbreak.

'Big data has really changed epidemiology,' Madhav Marathe, director of Virginia Bioinformatics Institute's Network Dynamics and Simulation Science Laboratory told International Business Times.

Mr Marathe has been working with the U.S. Department of Defense for almost a decade to help track diseases like and predict how they might spread.

In addition to using information send via text message, the team have turned to updates on social networks such as Facebook and Twitter.

A project by the group, dubbed '#HackEbola', gathers the data put out by local ministries of health and publishes the results online.

Meanwhile, the US Centers for Disease Control and Prevention (CDC) is collecting mobile phone mast activity data from operators and mapping where calls to helplines are located.

While this data has proved valuable, experts claim that more resources are needed to analyse the data faster.

If they manage this, scientists believe big data analytics could help provide an off-the-shelf Ebola vaccine.

But that may still be some way off. 'We're learning all this from scratch - we've never had this level of data before,' Qlik's David Bolton told the BBC.

'So it's probably too early to say whether big data analytics is having a meaningful impact on the rate and spread of the disease, but at least it is helping us decide where to allocate our resources.'

Ebola is transmitted by human contact, which means knowing where people are moving can provide valuable insight to researchers trying to contain the outbreak. Liberia and Guinea are thought to be the worst affected areas

 

@highlight

So far, more than 8,000 people are thought to have contracted the disease, and almost half of those have died

@highlight

Text messages are helping in the fight against Ebola in Sierra Leonne with people receiving health text alerts

@highlight

BBC has started sending Whatsapp alerts that include short audio clips and photos to people at risk from Ebola

@highlight

As well as sending alerts, social media is helping health agencies monitor trends in outbreaks by their location

@highlight

Harvard University's HealthMap flagged a 'haemorrhagic fever' nine days before Ebola was formally announced