Miguel Cotto’s sensational stoppage of all-time middleweight great Sergio Martinez forces another revision of this column’s world pound-for-pound ratings.

Now the first in the heroic history of Puerto Rican fighting men to win world titles in four different weight divisions, Cotto climbs back into boxing’s elite.

When they fought in New York two weekends ago Martinez was clearly past his prime, his phenomenal athleticism limited by the succession of injuries which had kept him out of the ring for almost a year.

Sensational: Miguel Cotto surprisingly stopped Sergio Martinez and climbed back into boxing's elite

Champion: Cotto would be too mobile for Floyd Mayweather and would beat the Money Man, says Freddie Roach

Nevertheless the Argentine remains a master of his craft and forcing his corner to pull him out in the tenth represents a considerable triumph.

Cotto looked to be on the wane himself after he was taken apart by Manny Pacquiao a couple of years ago but such is the fraternity of the hardest game that he has the PacMan to thank for his renaissance.

The pair have sparred frequently since Cotto was taken on by Pacquiao’s master trainer Freddie Roach.

Their sessions at Roach’s Wild Card gym in Los Angeles gave Cotton the best of both worlds – the best possible coaching put into practice courtesy of one of the two greatest boxers of our time.

Roach says: ‘I was confident Miguel was going to beat Martinez and of course it pleases me that he’s made me look good while doing it. The way Manny does.’

Helping hand: Manny Pacquiao has let Cotto train in his Wild Card gym, with successful results

Strong words: Freddie Roach reckons the new, improved Cotto would knock out Floyd Mayweather

1)    Floyd Mayweather (unchanged)              

2)    Manny Pacquiao (unchanged)

3)    Wladimir Klitschko (unchanged)

4)    Guillermo Rigondeaux (unchanged)

5)    Andre Ward (unchanged)

6)    Juan Manuel Marquez (up 1)

7)    Carl Froch (up 1)

8)    Miguel Cotto (new)

9)    Tim Bradley (unchanged)

10)   Adonis Stevenson (unchanged)

With Pacquiao now back in the big-time following his brilliant reversal of that scandalous decision given against him and favour of Tim Bradley, Roach’s stock is now sky-high again.

He gives much of the credit for his remarkable defiance of Parkinson’s disease to the adrenalin generated by the rigours of the sport and Cotto is supplying an additional surge.

He has also given his career and earning potential a significant boost. Although the closeness of their professional relationship makes a return match with Pacquiao unlikely, Cotto could be back in the mix for a chance to avenge his 2012 defeat by Floyd Mayweather.

Roach says: ‘The new Cotto, with his improved movement, would be too mobile for Floyd now and I believe he would knock him out.’

All powerful reasons for welcoming him to the top 10.

I bring him in at eighth, which with Martinez dropping out serves to lift Carl Froch another place higher to seventh in this list (above right).

Brian Rose goes by the ring moniker The Lion and it always looked as if he would be walking into the den of his feline namesakes in New York on Saturday night.

And so it was that although the brave boy from Blackpool had only been off his feet once before, in his only previous defeat, he was on the wrong end of a mauling by Rhode Island’s Demetrius Andrade.

A bridge too far: Brian Rose was well beaten in New York by Demetrius Andrade

Since he had been decked in the first and the third rounds and was taking a beating, it might have been a kindness had his corner pulled Rose out at the end of the sixth. But the inevitable stoppage was delayed only for another minute and 19 seconds.

Rose had said himself that he considered Andrade to be the weakest of the 154lb belt holders. So the sad conclusion has to be that although he is fine competitor at domestic and European level, he may be just short of world class.

 

@highlight

Martinez past his prime but Cotto's victory was still huge

@highlight

Cotto looked to be on the wane after losing to Manny Pacquiao

@highlight

But Puerto Rican got back on track by using PacMan's gym

@highlight

Freddie Roach reckons Cotto could knock out Mayweather

@highlight

Brian Rose fell short in beating by Demetrius Andrade