After weeks of slow, stop-and-go movement towards a village on Hawaii's Big Island, a menacing river of molten lava was calmed by an overnight downpour on Saturday night.

The rain has reduced the smoke that's coming from the lava flow - which remains stalled 480 feet from the main road in and out of Pahoa, a town of about 1,000 people.

Hawaii County Civil Defense director Darryl Oliveira claims the the moisture helped pack down some of the smoke that's been generated by small fires from the lava.

Glimmer of hope: An official claims an overnight downpour on Saturday has reduced the smoke that's rising from the lava flow

He said: 'It was pretty light this morning when we were out there. There's still supply or material coming down the mountain from the source.

The lava is burning through vegetation on an agricultural property containing trees and grass, but Mr Oliveira says there are no brush fires and the flow is no longer advancing towards the road.

He added: 'At this point, that supply that's reaching the front of the very leading edge is being shared throughout the system and the volume has decreased. It's not allowing it to push forward.'

Lava has been spilling down the flank of Kilauea volcano toward the northeast since June and recently crossed a country road, then smothered part of a cemetery. It also has toppled trees and burned a shed, tires and grass.

Moistened: Hawaii County Civil Defense director Darryl Oliveira claims the the moisture helped tamped down some of the rising smoke

Last week, 83 National Guardsman were dispatched to the area to aide in the evacuation of homes threatened by the hot molten rock.  

The lava flow from the Kilauea volcano had been advancing at less than five miles-an-hour before it stalled, said Mr Oliveira.  

While it threatens to destroy homes and cut off a road and a highway through Pahoa, officials have not offered any predictions on when exactly it could bisect the town at the site of an old sugar plantation.

Stalled: The river of molten rock remains 480 feet from the main road in and out of Pahoa, a town of about 1,000 people.

Defiant: A chiropractor's office vows to stay open for business in Pahoa as lava threatens to bisect the town's main road

The lava flow stems from a June eruption of the Kilauea active volcano. The lava surfaced from a vent on the volcano and may reach all the way to the sea 

Destructive power: The lava is hot enough to incinerate any homes, roads and businesses that fall in its path (photo taken October 31)

No homes have been destroyed so far, and a finger of lava that threatens one house on the edge of town has not advanced closer to the evacuated structure since Wednesday night - remaining around 100 feet away.

Meanwhile, the glowing leading edge of the lava flow is now about 160 yards from Pahoa Village Road, the main street through the town.

Residents of about 50 dwellings in what civil defense officials called a 'corridor of risk' have been asked to be ready to leave, and many have been slowly emptying their homes of furniture and treasured possessions.

Menacing: Lava from a vent at Kilauea volcano, one of the earth's most active, has been sliding northeast toward the ocean since an eruption on June 27

Lava from a vent at Kilauea volcano, one of the earth's most active, has been sliding northeast toward the ocean since an eruption on June 27.

Locals say the molten rock is being spread by Pele, the Hawaiian volcano goddess.

'She is so gentle, but so unrelenting. She is just slow and steady,' said Jamila Dandini, a retiree who stopped at a coffee shop down the road from where scientists have forecast the lava will likely cross. 

Superstition: Locals say the molten rock is being spread by Pele, the Hawaiian volcano goddess

Erbin Gamurot, 48, a handyman, said Pele just wants to visit her sister, Namakaokahai, the sea goddess.

'She's doing what she gotta do. That's her way, that's her nature. Who can stop her?' he asked. 

Last month, scientists said it was two weeks away from hitting the main road in Pahoa. The lava slowed but has largely remained on course.

The slow pace has given residents time to pack their valuables and get out of the way. 

Paul Utes, who owns the Black Rock Cafe, said: 'It's like slow torture. It speeds up, it slows down. It speeds up, it slows down.

After weeks of slow, stop-and-go movement towards a village on Hawaii's Big Island, a menacing river of molten lava bubbled over a road and overran a cemetery and crossed onto a residential property on Tuesday

'It's not like any other event where it comes and goes and it gets over with and you can move on.'

Mr Utes' restaurant is not in the predicted path even though it's just a few hundred yards south from where the lava will likely cross the main road.

But he worries this could change. Even if the cafe is spared, he doesn't know how traffic will be diverted once lava crosses the road, how his vendors will supply his restaurant and what the public - his customers - will do.

For the time being, business is up because more people from around the island and tourists from outside Hawaii have been streaming into town hoping to get a glimpse of the molten rock.

Construction crews prepare Pahoa Village Road as lava flow from Mt Kilauea approaches the village of Pahoa, Hawaii, on Tuesday

'The anxiety building up is kind of hard to deal with,' he said.

Some changes brought by lava are already starting to have an effect.

The county bus no longer passes through the main street lined with wood buildings dating to the town's heyday as a lumber and sugar-plantation town.

Locals have been discussing pooling their resources for supply runs to Hilo, the nearest city, because it could take hours to get there on alternate routes once Pahoa's main roads are cut off. 

An Hawaiin Volcano Observatory geologist walks across the surface of the lava flow last week

@highlight

Lava from erupting Kilauea volcano has been advancing on town of Pahoa on Hawaii's Big Island for weeks

@highlight

But the flowing molten rock has now stalled 500 feet from town's main road after bubbling into a cemetery last week

@highlight

As many flee their homes - an Hawaiian official says Saturday's overnight rain has cooled the lava and put out fires