By
Emma Thomas

PUBLISHED:
  
  
      19:36 EST, 21 October 2013
    
  
 | 
  UPDATED:
  
  
      02:35 EST, 22 October 2013

Heart-throbs One Direction have topped another chart - toppling Daniel Radcliffe from the number one spot in a rich list of young stars.

The singers have shot to the summit of Heat magazine’s Rich List for under-30s with combined earnings estimated at £59.33 million.

Harry Potter star Radcliffe has topped the list since it was established in 2010, but is this year in second place with £56.19 million.

Niall Horan, Louis Tomlinson, Zayn Malik, Liam Payne and Harry Styles of One Direction top the young rich list. Their combined earnings are estimated at £59.33 million

One Direction - soon to release their third album Midnight Memories - were included as a single entry for their total earnings, rather than individually, because the money has been generated by the group rather than for any solo work.

The highest new entry is DJ and music producer Calvin Harris who was number 8 in the list with £22.2 million.

Lucie Cave, editor-in-chief of Heat, said: “One Direction are young, talented, staggeringly good looking and adored by millions. To that we can now add ‘rolling in cash’. No one said life was fair.”

The stars’ financial dealings, including TV shows, movies, record sales and product endorsements, were examined by a panel of industry experts.

Names falling out of the top 30 this year included Paolo Nutini, Jamie Bell, Natasha Bedingfield and Sienna Miller.

The full list is published in Heat tomorrow.

Knocked off the top spot: Daniel Radcliffe

1 (5) One Direction, £59.33 million

2 (1) Daniel Radcliffe, £56.19 million

3 (2) Robert Pattinson, £44.16 million

4 (3) Keira Knightley, £37.28 million

5 (4) Emma Watson, £27.93 million

6 (6) Adele, £27.54 million

7 (7) Rupert Grint, £24.09 million

8 (-) Calvin Harris, £22.21 million

9 (9) Cheryl Cole, £15.50 million

10 (8) Leona Lewis, £14.45 million

New entry: DJ Calvin Harris was number eight in the list with £22.2 million

@highlight

Singers replace Daniel Radcliffe at top of list

@highlight

Highest new entry is DJ Calvin Harris with £22.2 million

@highlight

Harry Potter star Radcliffe had topped the list since 2010