By
Jill Reilly

PUBLISHED:
  
  
      04:05 EST, 11 November 2013
    
  

 | 
  UPDATED:
  
  
      14:52 EST, 11 November 2013

In the midst of all the chaos and devastation in the Philippines a baby girl was safely born in the rubble of a typhoon-devastated airport.

Emily Ortega, 21, gave birth in a destroyed airport compound that was turned into a makeshift medical centre, with her bed a piece of dirty plywood resting amid dirt, broken glass, twisted metal, nails and other debris.

'She is so beautiful. I will name her Bea Joy in honour of my mother, Beatriz,' Ortega whispered shortly after giving birth.

Scroll down for video

Safe delivery: Cheers broke out this morning when 21-year old Emily Ortega gave birth to a baby girl in the city of Tacloban.  Bea Joy is carried by her aunt

Ortega said her mother was swept away
 when giant waves generated by Super Typhoon Haiyan surged into their 
home near Tacloban city, the capital of Leyte province which was one of 
the worst-hit areas, and she has not been seen since.

More than 10,000 people are believed 
to have died in Leyte, and many hundreds on other islands across the 
central Philippines, which would make Haiyan the country's worst 
recorded natural disaster.

But, in the most tragic of circumstances, Bea Joy restarted the cycle of life.

'She is my miracle. I had thought I 
would die with her still inside me when high waves came and took us all 
away,' she said, as her teary-eyed husband, Jobert, clasped the baby and
 a volunteer held an IV drip above them.

Miracle birth: New-born baby Bea Joy is held as mother Emily Ortega, 21, rests after giving birth at an improvised clinic at Tacloban airport

Named: Bea Joy was named after her grandmother Beatrice, who was missing following the onslaught of typhoon Haiyan

The husband said the first wave that 
came carried their wooden home in the coastal town of San Jose many 
metres inland, washing all of the family outside.

He said the entire community had been
 washed away, with the once picturesque area replaced by rubble and the 
bloated remains of people and animals.

'We are supposed to be celebrating today, but we are also mourning our dead,' Jobert said.

He said it was God's will that he found his wife floating amongst the debris.

New addition: New-born baby Bea Joy is held by her aunt Michelle Satur

Flooded: The new mother was in an evacuation centre when the storm surge hit and flooded the city

Makeshift clinic: A woman comforts a pregnant relative having labour pains

Temporary: The control tower was turned into a temporary clinic for the expectant mothers

They were carried away for what felt 
like hours until the water subsided, and they found themselves 
sheltering in a school building where other mud-soaked and injured 
survivors had huddled.

The couple and their surviving 
neighbours subsisted there until Monday morning only on bottles of water
 they found among the debris. Jobert said he knew that his wife was 
about to give birth any day, but no help or aid had come.

'She began labour at 5:00 am (Monday) so we had to walk several kilometres before a truck driver hitched us a ride,' he said.

The young military doctor who 
attended to her, Captain Victoriano Sambale, said the new mother had 
already broken her waters by the time the couple stepped inside the 
building, and then developed bleeding during the delivery.

'This is the first time we have 
delivered a baby here. The baby is fine and we have managed to stop the 
bleeding of the mother,' he said.

However, he cautioned doctors were 
extremely concerned about potential infections that could easily be 
caught amid the unsterile conditions, with the medical team almost 
powerless now to help her.

'Definitely the mother is still in 
danger from infection and sepsis (septicemia). So we need to give her 
intravenous antibiotics. Unfortunately we ran out of even the oral 
antibiotics yesterday,' Sambale said.

@highlight

Emily Ortega, 21, gave birth to a baby girl in the typhoon-devastated airport

@highlight

Bea Joy Sagales appeared in good health after her unusual birth

@highlight

The mother had to swim and cling to a post to survive

@highlight

She was then taken to the airport and gave birth to healthy baby girl