By 
Reuters/ap

PUBLISHED:

01:02 EST, 5 October 2013


| 

UPDATED:

09:02 EST, 5 October 2013

Tropical Storm Karen was losing strength late Friday as it headed toward the central Gulf Coast, but forecasters are still expecting it to bring significant rain and potential flooding to low-lying areas.

Authorities issued mandatory evacuation orders for low-lying areas south of New Orleans on Friday as the weakened Tropical Storm Karen closed in on the Louisiana coast after disrupting U.S. energy output in the Gulf of Mexico.

Karen's top winds dropped to 45 mph, down from 65 mph a day earlier, although National Hurricane Center forecasters in Miami said the storm was expected to strengthen slightly on Saturday but remain a tropical storm.

Surf's up: People watch surfers ride waves generated by Tropical Storm Karen atop the Pensacola Beach Pier at Pensacola Beach, Florida

Preparation: C.J. Johnson pulls a shrimp boat out of the water in preparation for the arrival of Tropical Storm Karen, at Myrtle Grove Marina in Plaquemines Parish, Louisiana

Karen began losing its punch after a busy day of preparations along the Gulf Coast for the storm, a late-arriving worry in what had been a slow hurricane season in the U.S. Karen would be the second named storm to make landfall in the U.S. - the first since Tropical Storm Andrea hit Florida in June.

Oil output in the U.S. Gulf of Mexico had been cut in half as oil and gas firms shut platforms and evacuated some workers in preparation for the storm.

The Gulf accounts for about 19 per cent of U.S. oil production and six per cent of natural gas output.

The mayor of Grand Isle, Louisiana, clamped a mandatory evacuation on the popular vacation and fishing destination on a barrier island south of New Orleans.

Evacuations were also ordered in Lafourche Parish in the south, and residents in much of Plaquemines Parish, southeast of New Orleans, were told to be out of their homes before nightfall.

Karen's projected path shifted slightly westward and it was expected to move ashore over Louisiana on Saturday night and into Mississippi and then Alabama on Sunday.

Alabama joined Louisiana, Mississippi and Florida in declaring a state of emergency. The Federal Emergency Management Agency and Interior Department recalled workers, furloughed because of the government shutdown, to deal with the storm and help state and local agencies.

Evacuated: Jonie Harvey carries items as she loads the family cars as her family prepares to leave, due to a mandatory evacuation in advance of Tropical Storm Karen, in Belair, part of Plaquemines Parish, Louisiana on Friday

By late Friday afternoon, the storm was centered about 235 miles south-southwest of the mouth of the Mississippi River. It was moving north-northwest but was forecast to turn to the northeast as it crossed the coast.At the Port of New Orleans, cargo operations continued normally, but the harbor pilots who guide ships through the mouth of the Mississippi had ceased operations.

'No ships are coming in or out the mouth of the river,' said port spokesman Matt Gresham.

Forecasters said late Friday that Karen was expected to dump one to three inches of rain on the central Gulf Coast and southeastern United States by Monday night, less than originally predicted, with up to six inches in isolated parts.

The storm was expected to dump up to six inches of rain in its path and to push a surge of seawater over the shoreline, the hurricane center said.

Batten down: Al Baumer of Madisonville, Louisiana unties his boat to take it out of the water before Tropical Storm Karen arrives at Point Cadet Marina in Biloxi, Mississippi

Ralph Atkins, owner of Southern Fish & Oyster Co on a downtown dock in Mobile, Alabama, said he expected to see a 'good squall' from Karen but nothing he couldn't deal with.

'Our big trouble is water. Water can build up and make it bad,' Atkins said. 'It's just another day in the fish business. Nature just needs to take a bath every now and then,' he added.

At Alabama's Grand Mariner Marina on Dog River and Mobile Bay, boaters were tying down the larger vessels with double ropes and putting the smaller ones on trailers to haul them up the river to sheltered coves.

'It's like New York City at lunch time here. We are really busy,' said marina manager Steve Penny. 'We are doing everything we can to make room for four to six feet of water. Anything we can move, we get out.'

Calm before the storm: Maintenance crews with Plaquemines Parish lift a heavy gate across an opening where train tracks are located in anticipation of Tropical Storm Karen

Valuables: Tamisha Isidore, 16, carries her shoes to the family car as they prepare to leave, due to a mandatory evacuation in advance of Tropical Storm Karen, in Pointe a la Hache in Plaquemines Parish, Louisiana yesterday

Weakening: Tropical Storm Karen is seen in a National Oceanic and Atmospheric Administration (NOAA) Geostationary Operational Environmental Satellite (GOES) East infrared enhanced satellite image taken at 21:45 EST October 4

Marina workers were adding fuel to their 8,000-gallon (30,280-liter) tanks to weigh them down and keep them from floating away.

A hurricane watch for the coast from Grand Isle, Louisiana, to Destin, Florida was dropped. Tropical storm watches and warnings were still in effect in other areas including metropolitan New Orleans and Lake Pontchartrain. Tropical storms carry winds of 39 mph to 73 mph.

In Washington, White House spokesman Jay Carney said President Barack Obama was being updated about the storm, which put an undisclosed number of FEMA workers back to work.

Interior's Bureau of Safety and Environmental Enforcement, which oversees offshore drilling, is providing updates on oil and gas drilling in the Gulf that has been shut-in as a result of the storm. The National Park Service and Fish and Wildlife Service were securing parks and refuges in the storm's path, officials said.

The Bureau of Indian Affairs contacted the three federally recognized tribes in the storm's path to coordinate responses and assess needs, and the U.S. Geological Survey is monitoring for flood levels.

@highlight

Authorities issued evacuation orders for low-lying areas of Louisiana Friday

@highlight

Tropical Storm Karen is losing strength but is expected to strengthen slightly on Saturday

@highlight

Karen is expected to remain a tropical storm and not escalate to a hurricane

@highlight

Oil output in the Gulf of Mexico has been cut in half as Louisiana prepares for the storm

@highlight

Alabama, Louisiana, Mississippi and Florida all declared a state of emergency