By
Associated Press

Cristobal strengthened into a hurricane in the Atlantic as it moved away from the Bahamas on Monday, leaving behind flooded communities across a swath of soaked Caribbean islands and at least three fatalities.

The National Hurricane Center in Miami said that by Monday evening the hurricane was centered about 660 miles (1,065 kilometers) southwest of Bermuda. It had maximum sustained winds of 75 mph (120 kph) and was tracking east at 2 mph (4 kph).

The storm was projected to later move on a slow north-northeastward track, with a gradual increase in forward speed. It was expected to pass to the west and north of Bermuda on Wednesday.

Hurricane Cristobal: By Monday evening the hurricane was centered about 660 miles (1,065 kilometers) southwest of Bermuda

Moving fast: By Momday evening Hurricane Cristobal had maximum sustained winds of 75 mph (120 kph) and was tracking east at 2 mph (4 kp)

Before strengthening into a hurricane, the storm flooded several communities across the Caribbean and halted flights in the drenched Turks & Caicos Islands.

Government offices and banks were shuttered Monday on the low-lying islands that are highly vulnerable to flooding from heavy rains and storm surge, and authorities said many homes were flooded, especially on North and Middle Caicos islands.

Officials in Turks & Caicos said some 12 inches (30 centimeters) of rain had been dumped since Friday.

In the Bahamas, government meteorologists warned that severe thunderstorms from the storm's outer bands posed threats Monday to Mayaguana, Acklins and a few other islands and they called for boaters to return to port and residents to stay indoors.

On the Caribbean island of Hispaniola, two Dominican men drowned and two Haitians went missing when they were caught up in waterways swollen by Cristobal's driving rains.

Authorities said they were still searching for the two Haitians missing since late Saturday in Saint Marc, a port town on the country's west coast.

On Monday, the Turks & Caicos governor's office reported one storm fatality in the tiny archipelago, saying a body was recovered from floodwaters on the main island of Providenciales.

Florida weather: Winds from the Northeast and rough surf hit the beaches on Monday morning

High winds: Twenty five mph winds from the Northeast and rough surf hit the Jacksonville Beach in Florida

About 3,600 people were evacuated from communities in the Dominican Republic, according to Jose Manuel Mendez, director of the country's emergency operations center. More than half returned to their homes by Monday.

Roughly 640 Haitian families were left temporarily homeless during the passage of the storm, said Luckecy Mathieu, a civil protection coordinator. At least 28 homes were badly damaged and four others were destroyed, he said.

Many beaches along the U.S. east coast - from Florida to Washington - are expected to feel Cristobal's effects as it tracks north through the Atlantic this week.

The National Weather Service warned of strong rip currents, as strong winds from the northeast are pushing large waves toward the shore.

Beach goers should also be prepared for waves ranging from three to five feet, according to The Washington Post.

Meanwhile in the Pacific, Hurricane Marie was moving northwest as a major Category 4 storm, bringing high waves but no threat of a direct hit to Mexico's Pacific coast.

The weakening hurricane's sustained winds were near 135 mph (214 kph) with more weakening expected over the next two days. It was centered about 490 miles (790 kilometers) southwest of the southern tip of Mexico's Baja California Peninsula.

Swells generated by Marie were affecting the southwestern coast of Mexico and the southern gulf of California. National Hurricane Center forecasters said the swells were expected to reach southern California by Tuesday and were likely to cause 'life-threatening surf and rip current conditions.'

Tropical storm:  A tropical depression formed over the Turks and Caicos Islands on Saturday as it headed toward the Bahamas and dumped heavy rains on parts of Puerto Rico and the Dominican Republic

Gaining power: Tropical storm Cristobal was headed away from the Bahamas Monday as the strengthening system pounded the Turks and Caicos Islands with heavy rainfall

@highlight

By Monday evening the hurricane was centered about 660 miles (1,065 kilometers) southwest of Bermuda

@highlight

Before strengthening into a hurricane, 
the storm flooded several communities across the Caribbean

@highlight

On the Caribbean island of Hispaniola, 
two Dominican men drowned and two Haitians went missing when they were 
caught up in waterways

@highlight

At least 28 homes were badly damaged and four others were destroyed

@highlight

The National Weather Service warned of rip currents and waves of up to five feet from Florida to Washington as the storm moves north this week