 

By
Beci Wood

Ryan Giggs proved class is permanent with a delicious chip in a charity match.

The Manchester United legend called time on his 23-year playing career in May but showed he's not lost any of his skill with a sublimely cheeky effort.

The former Class of 92 were joined by celebrity friends for a fund-raising match against the Salford City team that Giggs now co-owns with Paul Scholes, Nicky Butt and Gary and Phil Neville. 

He's still got it: Ryan Giggs proves he's still a force to be reckoned with in charity match

Elegant: Paul Scholes showed composure in midfield but couldn't stop the Class of '92 going down 5-1 

And when trailing 2-0 to the Evo-Stick League Division One North side it was Giggs who stepped up and took responsibility when his side were awarded a penalty.

The superb 'Paneka' effort was similar to the one Andrea Pirlo scored against England in Euro 2012.

All the money generated by the match goes directly to Salford City, and Giggs was delighted to get back in action to help raise funds. 

Classy chip: Salford City goalkeeper is grounded as Giggs' effort floats over him

'I couldn't turn down the opportunity of putting the boots on with the lads again,' Giggs said.

'It's for a good cause, it's a great way of raising the profile and for keeping fit as well.

'I grew up in Salford and a lot of the lads plied their trade there when they were young, so we've all got affiliations.

'It's a great way of hopefully putting something back.

Class of '92 and Friends' team photo: (L-R back row) coach Eric Harrison, Gary Neville, Robbie Savage, Dutch former goalkeeper Raimond Van Der Gouw, John O'Kane, Polish goalkeeper Tomasz Kuszczak, Mikael Silvestre, Quinton Fortune, David May, former cricketer Steve Harmison, Phil Neville and former cricketer Michael Vaughan, (L-R front row), Nicky Butt, Raphael Burke, Ryan Giggs, Paul Scholes, comedian Jack Whitehall and Ben Thornley

'If we wanted glamour we wouldn't be doing this but we're getting a lot of benefits and a lot of happiness from what we're doing at the moment.'

The new owners have ambitions of getting Salford into the Football League, and Butt - who, unlike Phil Neville, is retaining a place on the United coaching staff along with Giggs - said: 'We all have dreams. We all think we can go as high as we can.

'We think it is a city that deserves a Football League club. If we can get there, who knows how high we can take it?

'Firstly, we need to get into the Football League as soon as possible. How long that will take I don't know. But once we are there we can reach for the stars.' 

CLICK HERE to start picking your Fantasy Football team NOW! There’s £60,000 in prizes including £1,000 up for grabs EVERY WEEK… 

@highlight

Manchester United legend proves he's still got the skills with cute chip

@highlight

Welsh legend retired from professional football in May

@highlight

He is now Louis van Gaal's assistant at Manchester United