A coral reef in Northern Australia severely damaged by warming seas has managed to completely heal itself in just 12 years, stunned researchers have found.

The team found that being left alone to breed on its own was key.

The discovery raises hope that other damaged reefs could 'regenerate'.

Scott Reef in Northern Australia, where researchers found coral has 'regenerated' itself after almost 12 years following a warming incident

The new research shows that an isolated reef off the northwest coast of Australia that was severely damaged by a period of warming in 1998.

It was hit by coral bleaching, caused by higher water temperatures that break down the 
coral's symbiotic relationship with algae that provide food for coral 
growth.

However, the team found Scott reef has regenerated in a very short time to become nearly as healthy as it was before.

What surprises scientists, though, is that the reef regenerated by itself, found a study published Thursday in the journal Science.

James Gilmour and colleagues studied the Scott system of reefs on the edge of Western Australia’s continental shelf, which lost 70 to 90 percent of its corals to a climate-induced bleaching event back in 1998.

Scott Reef is an isolated group of three reefs near the edge of northwestern Australia's continental slope

The researchers found that, although the corals’ reproductive abilities were by the bleaching, coral cover still increased from 9 percent to 44 percent across the entire system in just 12 years.

The team say the finding is surprising because researchers have assumed that recovery from such bleaching events depends upon the delivery of larvae from other, nearby reef systems.

But, the Scott system of reefs is located 155 miles (250 kilometers) from the mainland or any other reefs.

So, Gilmour and his team suggest that herbivorous fish, which remained abundant in the undisturbed Scott system, even after the bleaching, kept microalgae in check and allowed coralline algae to thrive.

This set of conditions in turn provided a suitable substratum upon which young corals could establish and grow., they claim.

The study suggests that reef systems can recover using local sources of larvae, especially when fish are plentiful and human activities, which have been shown to slow coral recovery in the past, are limited.

At first, the reef grew slowly, mostly through the enlargement of existing coral colonies. But to really recover, the coral needs to sexually reproduce, creating sperm and egg that form embryos that then land on the ocean floor and grow into adult corals, if all goes well.

These larvae can survive for hundreds of miles, swept along by ocean currents, and colonize new areas under the right circumstances.

Larvae floating in from other reefs could have helped the reef, had it not been so isolated.

But amazingly, after about six years, the surviving corals matured and began to reproduce, creating even more new colonies than before the bleaching. 'They recovered, and the larvae they produced settled and survived, at much higher rates than is often reported,' Gilmour said.

The rate of recovery was attributed to the lack of many local human pressures affecting reefs around 
the world, such as degraded water quality and overfishing of herbivores

By 2012, the reef was basically back to its old self.

The study suggests that, when it comes to reefs, being isolated from human activity may trump being connected to other reefs.

Overfishing, for example, removes fish that keep algae from choking out and outcompeting corals, and sediment and pathogens in runoff water can lead to coral diseases and death.

But the results also mean that local decisions about fishing and other issues can help preserve reefs, which are threatened by global warming. 'Managing local conditions is a tangible way to maximize the resilience of coral reefs while the more difficult problem of addressing the causes of climate change are resolved,' Gilmour said.

@highlight

Scott reef on the northwest coast of Australia was severely damaged by a period of warming in 1998

@highlight

Researchers found after six years mature corals began breeding again