Manchester United have warned Premier League rivals that their £150million summer spending spree is only the beginning of an ongoing bid to snap up the world’s top talent.

The Old Trafford outfit lavished an astonishing £150m over the summer on new six recruits, including a British transfer record £60m deal to land Argentina wing wizard Angel di Maria from Real Madrid and a further £31.5m to prise Luke Shaw away from Southampton. 

Colombian striker Radamel Falcao also joined from Monaco in a mega-loan deal worth £20m.

VIDEO Scroll down for Neil Ashton: Radamel Falcao is obsessed with scoring goals 

In the red: But Manchester United can easily afford to pay Radamel Falcao his high wage demands

Spanking new home: Falcao poses outside United's sponsored training ground

Seven heaven: Angel di Maria poses with Louis van Gaal after signing for United in a record £60m deal

The spending spree follows the £65m that former manager David Moyes spent on Juan Mata and Maroune Fellaini during his ill-fated season at the club - and he inherited £15m Wilfried Zaha, making a total transfer spend at Old Trafford of £230m since last summer.

But far from putting away the cheque book, sources close to the club say the hunt for further Galacticos will continue, paid for by the expanding commercial revenues generated by the club, described as more than sufficient to fund the current and additional player costs.

In the latest full-year accounts released for the club, covering the 2012-13 season, United’s commercial operation pulled in £152.5m. However that figure has grown dramatically, with estimates suggesting that figure will be closer to £190m when the next full-year results - which cover 2013-14 - are released later this month.

Accounts covering the current season are expected to show commercial income closer to £240m when they are released next year.

As a result, the Old Trafford commercial operation will also allow the club to continue to pay massive wages, comparable with captain Wayne Rooney who earns £300,000 a week. 

Fueled for success: United's players pose as their official diesel engine partner is revealed

On the board (from left): Jesse Lingaard, Michael Carrick and Rio Ferdinand (now at QPR) in Sydney last year

Party time: But (from left) Javier Hernandez, Ferdinand and Ryan Giggs do not currently play for the club

Cashing in their chips: Mister Potato is United's 'official savoury snack partner'

Follow Alex @alexmiller73

The feeling within the club is that there is still comfortable headroom to comply with the rules of both UEFA’s Financial Fair Play and the Premier League’s Spending Constraints rules.

The club’s unprecedented spending spree is being paid for by a number of major deals. According to the club’s official website, the club currently has 29 sponsors and commercial partners.

These include the £47m-a-year shirt sponsorship deal with Chevrolet. United’s world-record deal was agreed and signed in 2012 on terms of $559m over seven years, starting this season. Chevrolet has replaced United’s previous deal with Aon, which was worth £20m a year. 

However, Old Trafford officials negotiated an ongoing £17m-a-year sponsorship deal with Aon that includes their training kit and sponsorship of the Carrington training ground.

Local hero: Shinji Kagawa was a popular figure with fans in Japan and was part of a tomato juice campaign

Can-do attitude: Robin van Persie was also used to promote the tomato juice in Asia

Driving force: Sir Alex Ferguson attends a Chevrolet soiree in Shanghai in the summer of 2012

Delivering even more money: DHL pay United £10m a year to be the club's official logistics partner

Next season will see the start of another record-breaking deal when adidas take over from Nike as the club’s kit provider in an agreement worth a staggering £750m over 10 years, that's £75m a year. The current deal with Nike is worth in the region of £30m a year.

The deal with the German’s sportswear giant is understood to contain a clause to cut United’s earnings if they fail to qualify for the Champions League for two consecutive seasons starting in 2015-16. Even if that were to happen United would still bank £55m a year.

DHL pays £10m a year for the right to be the club’s official logistics partner. Bwin signed a £2.4m deal with the club in 2012 to become the official Man Utd gaming partner, while Singa pays approximately £2m a year to be the club’s official beer supplier.

Meanwhile, despite the promise of further Galactico signings and the surprising decision to sell Danny Welbeck to Arsenal for £16m, the club will continue to invest in local and young talent.

Moving on: Danny Welbeck was sold to Arsenal on transfer deadline line for £16m

Promotion: Tyler Blackett (right) has featured for United in their opening Premier League games

Sources close to the club maintain that developing young players is still very much at the core of what the club and manager Louis van Gaal will continue to do.

The club point to the fact that four players (James Wilson, Tyler Blackett, Jesse Lingard and Reece James) have been promoted from the youth team into the first team this season, while they have loaned another starlet, Michael Keane, to Burnley until January to gain first-team experience. 

Chevrolet: Principal sponsor - £47million a year

Nike: Principal sponsor - £25.4m a year

Aon: Principal sponsor - £17m a year

DHL: Logistics partner - £10m a year

bwin: Online Betting and Gaming partner - £2.4m a year

Casillero del Diablo: Official wine of Man Utd - £2m a year

Singha Beer: Official beer of Man Utd - £2m a year

DEALS WORTH £1m-2m a year 

Aeroflot: Official airline

Bulova: Official timekeeping partner

Epson: Office equipment partner

Toshiba Medical Systems: Medical systems partner

Aperol Spritz: Global spirits partner

Nissin Foods Group: Global noodle partner

STC: Telecommunications partner of Man Utd for Saudi Arabia

Yanmar: Official global partner

Kansai Paint: Official paint partner

The Hong Kong Jockey Club: Official partner

TM: Telecommunications partner in Malaysia

Apollo Tyres: Tyre partner in UK and India

Globacom: Telecommunication services partner in Nigeria, Ghana, Republic of Benin

VIVA: Telecommunication services partner in Bahrain

VIVA Kuwait: Telecommunication services partner in Kuwait

Honda: Motorcycle partner in Thailand

Bakcell: Telecommunications partner for Azerbaijan

Gloops: Gaming partner in Japan

Kagome: Official partner for Japan

Truemove H: Mobile partner for Thailand

Truevisions: MUTV broadcaster for Thailand

PCCW: Telecommunications partner and broadcast partner for Hong Kong

@highlight

United broke the British transfer record to sign Angel Di Maria for £60m

@highlight

On deadline day they signed Radamel Falcao on loan in a deal worth £20m

@highlight

Since last summer they have spent £230m on new players

@highlight

Louis van Gaal is expected to make more signings in next transfer window 

@highlight

United's staggering spending spree is funded by huge commercial revenue

@highlight

United made £152m in 2012-13 and expect an increase to £240m this season

@highlight

Club's record kit deal with adidas is worth £750m over 10 years from 2015

@highlight

In total United have 29 sponsors and commercial partners 