By 
Ray Massey

PUBLISHED:

04:13 EST, 26 February 2013


| 

UPDATED:

11:39 EST, 27 February 2013

The fastest car ever built in Britain with a top speed of 217mph is officially unveiled today.

The McLaren P1 can rocket from zero to 62mph in under three seconds, hit 124mph in under seven seconds and 190mph in under 17.

Believe it or not, it also promises to be as environmentally clean as a family saloon thanks to its ‘green’ petrol-electric plug-in hybrid technology.

Stunning: The McLaren P1, the fastest car ever built in Britain, has been unveiled today

Fast: The car has a top speed of 217mph and can go from 0 to 62mph in under three seconds

Rapid: The new McLaren can hit 124mph in under seven seconds

The red-hot two-seater, designed for use both on the road and race-track, will cost £866,000.

And that’s without a carpet, which will be an optional extra on this purist sports car built at the firm’s state-of-the-art factory in Woking, Surrey.

McLaren has already increased its workforce by 100, to 1,000, to build the car.

A spokesman for the company said: ‘It is the most technologically advanced and fastest series production car ever to come from the UK.’

Modern: The McLaren P1 is said to be the 'spiritual successor' to the three-seater McLaren F1

Environmentally-friendly: The car's 'green' petrol-electric plug-in hybrid technology also promises to make it as environmentally clean as a family saloon

Interior: The car will set you back £866,000, with carpets as an optional extra

To maintain exclusivity, only 375 will be built. Half of those have been sold already, with some customers buying two.

It
is the ‘spiritual successor’ to the three-seater McLaren F1, launched 
in 1993 with a price tag of £600,000 but which now fetches up to 
£4million at auction.

Exclusive: Only 375 of the cars are to be built and half of those have been sold already

Car-mad
comedy actor Rowan Atkinson is expected to be at the head of the queue 
for the machine, having recently secured a £910,000 insurance pay-out to
restore his McLaren F1 after he crashed it.

The
P1 is powered by a mid-mounted 3.8litre twin-turbo V8 petrol engine 
developing 727 brake horse-power, which sits behind  the driver and 
passenger. It is connected to a lightweight 176bhp electric motor, and 
the company claims that the two work ‘seamlessly’ to keep down 
emissions.

The total 
combined power of 903 brake horse-power – linked to a dual clutch 
seven-speed F1-style racing gearbox – is equivalent to nine Ford 
Fiestas. The engine set-up promises ‘instantaneous throttle response’, 
says McLaren.

Lightweight batteries behind the 
driver store charge generated by the petrol engine but a plug-in charger
can also be used to boost energy levels from empty to full in two 
hours.

As a result the 
car produces zero emissions when running on electric power only and has a
range of 12.5miles at an average city speed of 30mph.

‘That’s
more than enough for an owner to enter, for example, a city-centre zero
emissions zone, have dinner and return home,’ says McLaren.

Overall,
the McLaren P1 emits an average of 200g/km of CO2 – about the same as a
Honda Accord 2.4litre family saloon. The rival Bugatti Veyron emits 
559g/km of carbon dioxide while the Ferrari 458 averages 307g/km.

Car-mad: Comedy actor Rowan Atkinson is expected to be at the head of the queue for the machine

Dashboard: The car is to be launched officially at the Geneva Motor Show on March 5

Technology: McLaren says the P1 features Formula 1-derived race technology which increases speed and acceleration

Power: The car's 'instant power assist system' propels the car from rest to 190mph in under 17 seconds

Special date: The first deliveries of the car are planned for September 2 to coincide with McLaren's 50th anniversary

The P1 features Formula 1-derived race technology which the company says increases speed and acceleration.

It
has an ‘instant power assist system’ that propels the car, rocket-like,
from rest to 190mph in under 17 seconds – more than 35 per cent faster 
than even the F1.

The 
car will be launched officially at the Geneva Motor Show on March 5, 
with the first deliveries planned for September 2 to coincide with 
McLaren’s 50th anniversary.

A
company spokesman said: ‘Our goal is to create the best driver’s car in
the world on both road and track. A maximum speed which is 
electronically limited to 217mph should be sufficient for most.’

McLaren's stunning new supercar, the P1 will have a staggering 903bhp

The P1 has a 3.8-litre twin-turbocharged engine which develops 727bhp. But it also benefits from an electric motor which adds a further 176bhp to the car's total output

A spokesman for McLaren has called the P1 the 'most technologically advanced production car ever to come from the UK'

@highlight

The new McLaren P1 is to be fastest car ever built in Britain

@highlight

The car can hit 124mph in under seven seconds

@highlight

Also promises to be as environmentally-clean as family saloon