Voyager 1 has crossed a new frontier, becoming the first spacecraft ever to leave the solar system.

Thirty-six years after it was 
launched from Earth on a tour of the outer planets, the 
plutonium-powered probe is more than 11 1/2 billion miles from the sun, 
cruising through what scientists call interstellar space — the vast, 
cold emptiness between the stars, the space agency said.

Voyager 1 actually made its exit more
 than a year ago, according to NASA. But it's not as if there's a dotted
 boundary line out there or a signpost, and it was not until recently 
that the space agency had the evidence to convince it of what an outside
 research team had claimed last month: that the spacecraft had finally 
plowed through the hot plasma bubble surrounding the planets and escaped
 the sun's influence.

Scroll down for video

A massive 36 years of scientific data generated by Nasa's Voyager spacecraft has been transformed into a powerful piece of orchestral music. Voyager 1's current mission (illustrated) along with Voyager 2, is to explore the outermost edge of the Sun's domain and beyond

A massive 36 years of scientific data generated by Nasa's Voyager spacecraft has been transformed into a powerful piece of orchestral music. Voyager 1's current mission (illustrated) along with Voyager 2, is to explore the outermost edge of the Sun's domain and beyond

While some scientists said they remain unconvinced, NASA celebrated.

'It's a milestone and the beginning 
of a new journey,' said mission chief scientist Ed Stone at NASA's Jet 
Propulsion Laboratory in Pasadena.

Voyager 1 will now study exotic 
particles and other phenomena in a never-before-explored part of the 
universe and radio the data back to Earth, where the Voyager team awaits
 the starship's discoveries.

The interstellar ambassador also 
carries a gold-plated disc containing multicultural greetings, songs and
 photos, just in case it bumps into an intelligent species.

This artist's concept shows NASA's two Voyager spacecraft exploring a turbulent region of space known as the heliosheath, the outer shell of the bubble of charged particles around our sun

It is 36 years since the twin Voyager 1 and 2 spacecraft were launched and the pair continue to explore where 
nothing from Earth has flown before.

Their primary mission was the exploration of Jupiter and Saturn.

After
 making a string of discoveries there -- such as active volcanoes on 
Jupiter's moon Io and intricacies of Saturn's rings -- the mission was 
extended.

Voyager 2 went on to explore Uranus and Neptune, and is still the only spacecraft to have visited those outer planets.

The
 current mission for both spacecraft, the Voyager Interstellar Mission, 
is to explore the outermost edge of the Sun's domain and beyond.

Voyager 1's odyssey began in 1977 
when the spacecraft and its twin, Voyager 2, were launched on a tour of 
the gas giant planets of the solar system. After beaming back dazzling 
postcard views of Jupiter's giant red spot and Saturn's shimmering 
rings, Voyager 2 hopscotched to Uranus and Neptune. Meanwhile, Voyager 1
 used Saturn as a gravitational slingshot to power itself past Pluto.

Voyager 1, which is about the size of
 a subcompact car, carries instruments that study magnetic fields, 
cosmic rays and solar wind.

Last year, scientists monitoring 
Voyager 1 noticed strange happenings that suggested the spacecraft had 
broken through: Charged particles streaming from the sun suddenly 
vanished. At the same time, there was a spike in galactic cosmic rays 
bursting in from the outside.

Since there was no detectable change 
in the direction of the magnetic field lines, the team assumed the 
far-flung craft was still in the heliosphere, or the vast bubble of 
charged particles around the sun

Voyager is bathed in solar wind from the southern hemisphere flowing northward

The Voyager team patiently waited for
 a change in magnetic field direction — thought to be the telltale sign 
of a cosmic border crossing. But in the meantime, a chance solar 
eruption caused the space around Voyager 1 to echo like a bell last 
spring and provided the scientists with the data they needed, convincing
 them the boundary had been crossed in August of last year.

'It took us 10 seconds to realize we 
were in interstellar space,' said Don Gurnett, a Voyager scientist at 
the University of Iowa who led the new research, published online in the
 journal Science.

The new observations are fascinating,
 but 'it's premature to judge,' said Lennard Fisk, a space science 
professor at the University of Michigan and former NASA associate 
administrator who was not part of the team. 'Can we wait a little while 
longer? Maybe this picture will clear up the farther we go.'

Voyager 1 is capable of returning scientific data from a full range of instruments, with adequate electrical power and attitude control propellant to keep operating until 2020.

What bothers Fisk is the absence of a change in magnetic field direction.

Harvard astrophysicist Jonathan 
McDowell was more blunt: 'I'm actually not going to believe it for 
another year or two until it's been solidly outside for a while.'

While Voyager 1 may have left the 
solar system as most people understand it, it still has thousands of 
years to go before bidding adieu to the last icy bodies that make up our
 neighborhood.

Voyager 2 trails behind at 9 1/2 
billion miles from the sun. It may take another three years before 
Voyager 2 joins its twin on the other side. Eventually, the Voyagers 
will run out of nuclear fuel and will have to power down their 
instruments, perhaps by 2025.

This artist's impression shows how plasma flows around NASA's Voyager 1 spacecraft as it gets close to entering interstellar space

@highlight

New data suggest the venerable spacecraft has entered interstellar space

@highlight

Voyager 1 and 2 were launched in 1977, 16 days apart

@highlight

'We are in a new region of space,' NASA project scientist says

@highlight

Scientists claim Voyager 1 entered interstellar space more than a year ago

@highlight

Study claims Voyager 1 left heliosphere around August 25, 2012

@highlight

Voyager 1 is now the first mission to explore interstellar space