By 
Associated Press Reporter

PUBLISHED:

04:02 EST, 7 October 2013


| 

UPDATED:

09:17 EST, 7 October 2013

A typhoon slammed into southeastern China today with powerful winds and heavy rains that killed three people, cut power, canceled flights and forced more than half a milion people from their homes.

Typhoon Fitow struck Fuding city in Fujian province with winds of up to 125 miles an hour in the early morning hours, then slowed before weakening to a tropical storm, the National Meteorological Center said.

More than 500,000 people had been evacuated and fishing boats were called back to shore while authorities issued a red alert - the highest warning - on Sunday as the typhoon approached.

At least three people have been killed by the typhoon, including one who was on his way to rescue a fisherman when he was blown off a hill by strong winds late on Sunday.

Scroll down for video.

Making waves: Typhoon Fitow struck Fuding city of Fujian province with winds of up to 120 miles an hour causeing huge and powerful waves to pummel the coastline

Fearsome: The typhoon began dumping heavy and torrential rain across the southeastern seaboard, with rainfall of up to eight inches in some parts as well as gusty winds

Floods: Businesses were brought to a near standstill in the Sansha Township of Xiapu County where water flooded the streets

The provincial flood relief agency in Zhejiang, which neighbors Fujian, said 574,000 people had been evacuated by Sunday evening and 35,800 vessels returned to shore.

Fujian's government said 177,000 people had been moved to safety and nearly 30,000 fishing boats called back.

The typhoon cut power in towns and counties in Zhejiang province while high-speed rail services in the region were suspended.

At least 27 flights out of Wenzhou airport in Zhejiang were canceled on Sunday, according to the official Xinhua News Agency.

Pylons down: A villager rides past electricity pylons brought down by the typhoon in Xiaoyue Village in Fuding City

Japan: Waves generated by Typhoon Danas hit the coast in Yonabaru city, Okinawa, southern Japan

Damage: Citizens ride on a road after Typhoon Fitow hit Sansha Township of Xiapu County

Danger: More than half a million people had been evacuated and fishing boats were called back to shore while authorities issued a red alert - the highest warning - on Sunday as the typhoon approached

Dramatic: People view roaring waves at the north seashore in Keelung, China. The typhoon cut power in towns and counties in Zhejiang province while high-speed rail services in the region were suspended

Chaos: The typhoon caused rain to fall almost horizontally in parts of the region while flights were cancelled leaving hundreds of passengers stranded at the Taipei Songshan Airport in Taipei

Safety fears: The provincial flood relief agency in Zhejiang, which neighbors Fujian, said 574,000 people had been evacuated by Sunday evening and 35,800 vessels returned to shore

Xinhua said two people were killed in Wenzhou, including a 55-year-old man who was blown off a hill while heading out to help rescue a stranded fisherman.

Calls to the city's flood relief agency and other government and Communist Party offices rang unanswered Monday.

The typhoon began dumping heavy and torrential rain across the southeastern seaboard, with rainfall of up to 29 centimeters (8 inches) in some parts as well as gusty winds.

Battered coast: Before striking China, Fitow skirted the northern coast of Taiwan, causing many flight disruptions and dumping large quantities of rain on the island, but resulting in only minimal damage and no casualties

Rescue: Fujian's government said 177,000 people had been moved to safety and nearly 30,000 fishing boats called back

Before striking China, Fitow skirted 
the northern coast of Taiwan, causing many flight disruptions and 
dumping large quantities of rain on the island, but resulting in only 
minimal damage and no casualties.

Officials said it delayed or canceled more than 200 domestic and international flights, and brought about the evacuation of several hundred people from northern Taiwanese communities considered vulnerable to rain-induced mudslides.

Elsewhere in Asia, a typhoon east of the northern Philippines blew away with no impact on the country.

@highlight

Typhoon Fitow hit Fuding city in Fujian province with winds of up to 125mph

@highlight

One man was killed after he was blown off hill while trying to help fisherman

@highlight

More than half a million people had been evacuated and all boats called in

@highlight

It cut power in towns and counties in Zhejiang province, trains all suspended

@highlight

Officials said it delayed or canceled more than 200 flights to and from Taiwan