By 
Emily Allen

PUBLISHED:

11:01 EST, 17 April 2012


| 

UPDATED:

11:35 EST, 17 April 2012

Researchers found a big increase in anger and fear head of last summer's riots

British scientists are using Twitter to gauge the nation’s mood, it has been revealed.

Researchers at Bristol University studied nearly 500 million tweets by ten million users of the social network between the summer of 2009 and early 2012, a period marked by economic downturn and social tension.

They found a big increase in negative mood, anger and fear, coinciding with the announcement of spending cuts and last summer’s riots together with a calming effect of Prince William’s wedding to Kate Middleton.

In the study the researchers focused 
on measuring the mood, and changes, using standard tools for mood 
detection, of a large sample of the UK population.

A
collection of 484 million tweets generated by more than 9.8 million 
users from the UK were analysed between July 2009 and January 2012.

The findings reveal intriguing patterns that can be explained when events and social changes are taken into account.

The researchers found that a significant increase in negative mood indicators coincided with the announcement of the cuts to public spending by the government, and that this effect is still lasting.

They also detected events such as the riots of summer 2011, as well as a possible calming effect in the run up to the Royal Wedding.

A rise in public anger seems to have already been under way in the days before the riots.

Researchers at Bristol University found Prince William's wedding to Kate Middleton had a calming effect according to tweets

Study co-author Nello Cristianini, professor of artificial intelligence at Bristol University, said: 'Social media allows for the easy gathering of large amounts of data generated by the public while communicating with each other.

'While we leave the interpretation of our findings to social and political scientists, we observed how the period preceding the royal wedding seems to be marked by a lowered incidence of anger and fear, which starts rising soon after that. Of course, other events also happened in early May 2011, so they may also be responsible for that increase.'

The aim of the study was to see if the effects of social events could be seen in the contents of Twitter.

A collection of 484 million tweets generated by more than 9.8 million users from the UK were analysed between July 2009 and January 2012

The first part of the analysis backs up the researchers’ theory that word-counting methods can provide a reasonable approach to sentiment or mood analysis.

By making use of lists of words that are correlated with the sentiments of joy, fear, anger and sadness, they observed that periodic events such as Christmas, Valentine’s Day and Halloween evoke the same response in the population, year after year.

The main part of the analysis focused on a visible change-point occurring in October 2010, when the government announced cuts to public spending.

The study showed that public mood has still not recovered from that announcement.

The same testing technique shows another important period, that of summer 2011, when riots broke out in various UK cities, leading to looting and even loss of life.

The researchers method seems to suggest that some increase in public anger preceded, and not followed, these events, although the significance of this finding is a matter for social scientists to discuss.

Future work will include the comparison with social media content with traditional media content, as well as the comparison of both with traditional opinion polls methods.

The study was presented to an international workshop on social media applications in news and entertainment in Lyon, France.

@highlight

Researchers found increase in anger and fear in the day before the riots

@highlight

They found the Royal Wedding had a calming effect on the nation