A stunning display of the Northern Lights has been seen in Northumberland with the dancing colours visible to the naked eye.

The beautiful spectacle was seen in the early hours of Christmas Eve, as colours of green and pink appeared in the sky.

Known as the Aurora Borealis, the natural wonder is caused by charged particles colliding in the Earth’s atmosphere. 

Scroll down for video 

Beautiful: A stunning display of the Northern Lights has been seen across parts of the UK with the dancing colours visible to the naked eye. In this image, an Aurora is seen on the horizon behind Bamburgh Lighthouse in Northumberland

Press Association photographers Owen Humphreys and Tom White braved the cold to capture the display, that could be seen near Bamburgh lighthouse, in Northumberland.

It is believed the light show, which was also captured across Northumberland National Park, was caused by a strong solar storm which began on December 20th.  

Aurora are one effect of energetic particles which can speed out from the sun both in a steady stream called the solar wind and due to giant eruptions known as coronal mass ejections, or CMEs.

After a trip toward Earth that can last two to three days, the solar particles and magnetic fields cause the release of particles already trapped near Earth. 

Breathtaking: At five minutes past midnight on Christmas Eve the lights of the Aurora Borealis created a beautiful display of colours in the night sky above Northumberland National Park

Festive glow: An Aurora is seen on the horizon in Northumberland. It is believed a solar storm on December 20th caused the light show

Clear skies: Aurora are one effect of energetic particles, which can speed out from the sun both in a steady stream called the solar wind and due to giant eruptions known as coronal mass ejections, or CMEs

It is believed the Christmas Eve light show was caused by a strong solar storm which began on December 20th.

The solar flare registered as an X1.8-class event - one of the most powerful types of flares possible.

The solar flare also caused a radio blackout for parts of Earth over the weekend, according to an alert from the U.S. Space Weather Prediction Center.

Aurora are created when energetic particles from a solar flare trigger reactions in the upper atmosphere of Earth.

This in turn trigger reactions in the upper atmosphere in which oxygen and nitrogen molecules are released a particles of light.

The strong solar flare which created this aurora triggered a radio blackout for parts of Earth over the weekend, according to an alert from the U.S. Space Weather Prediction Center.

Usually the best spots to see the lights are those places close to the North Pole, such as Iceland and Norway.

In the southern hemisphere, they are known as the Aurora Australis and can often be mirror-like images that occur at the same time as in the north.

Clear winter nights tend to be better for observing the sky due to less haze and water vapour in the air.

The colour of the aurora depends on which gas - oxygen or nitrogen - is being generated by the electrons. It also depends on how fast the electrons are moving.

As well as Earth, any planet with a magnetic eld and an atmosphere should have auroras, including Jupiter, Saturn, and Uranus.

Lucky shot: Clear winter nights tend to be better for observing the sky due to less haze and water vapour in the air. Usually the best spots to see the lights are those places close to the North Pole, such as Iceland and Norway

Braving the cold: Press Association photographers Owen Humphreys and Tom White captured the display in the early hours of this morning

 

@highlight

Photographers Owen Humphreys and Tom White braved the cold to capture the display near Bamburgh lighthouse

@highlight

Natural wonder is believed to have been caused by a huge solar storm that erupted on the sun on December 20

@highlight

Solar flare caused charged particles to collide with Earth's atmosphere, which in turn created stunning colours