England recovered from a poor start at Twickenham and the early loss of full-back Mike Brown to maintain their RBS Six Nations title title with an emphatic 47-17 victory against England. 

Sergio Parisse shocked the home side when he powered over in the fourth minute but England replied with tries from Billy Vunipola and Jonathan Joseph to lead 15-5 at half-time. 

Stuart Lancaster's men added further tries from Ben Youngs, Joseph, Danny Cipriani and Nick Easter in the second half as the Azzurri challenge faded.  

Host commentator

They made hard work of it at times but England remain unbeaten in this year's Six Nations. 

Stuart Lancaster's side recovered from a poor start after Sergio Parisse's early try to lead in the second half thanks to tries from Billy Vunipola and Jonathan Joseph. 

England pulled clear in the second period as Joseph, May and Cor ran riot. Next up for England is a trip to Dublin in two weeks time. A huge encounter awaits at the Aviva Stadium. 

That man Morisi has had quite the second half. The powerful Italian centre did brilliantly to muscle over in the right corner following a superb break from replacement Giulio Bisegni. 

Italy keep possession for a sustained period in the England 22 and McLean pokes through a deft grubber but substitute Tomasso Allen can not gather the rebound to touch down. 

Another recalled England exile crosses the line. Nick Easter has just joined the action but the veteran Harlequins No 8 emerges from a powerful England maul to touch down. Cipriani hooks his conversion effort. England have 10 minutes to rack up some more tries and they look to bump up their points difference on the table...

The floodgates have opened. Danny Cipriani has barely been on the field for two minutes and the Sale Sharks fly half has crossed the whitewash. Cipriani ran a great support line to latch onto Jonny May's offload as England cruise out a huge lead 

England are cruising now. A rock solid scrum on half allows Youngs to feed Twelvetrees at first receiver before the Gloucester man sends a screen pass to George Ford who puts his Bath team-mate Joseph through a yawning gap in midfield for his second try of the afternoon. 

Some of England's attacking play has left much to be desired today but George Ford's place kicking has been immaculate. The Bath No 10 knocks over another three-pointer as England begin to pull away. 

That's poor from Italy. Referee John Lacey awards England a penalty from a collapsed scrum and Ben Youngs shows quick wits to take a quick tap and crash over from close range. Ford fires over the conversion as England establish a 15-point lead. 

That's the first sign of fatigue from the Azzurri. England will look to put this game to bed and rack up a score in the final quarter surely. 

That's as good a try as you will see anywhere this season. Italy winger Leonardo Sarto chips the England defence and gathers to set up a great attacking platform. 

Quick hands from McLean and Haimona release Luca Moris who shows Attwood and Haskell a clean pair of heels to scorch over from 30 metres. Haimona misses the conversion but Italy are right back in this contest again. 

Silly play from Italy flanker Francesco Minto hands Ford the chance to further increase England's lead early in the second half following a bullocking run by lock Dave Attwood in the build-up. 

Luke McLean kicks the ball dead as both sides head for the sheds. 

A thrilling opening half here in Twickenham. Parisse's opening try shocked England into life before Mike Brown's unfortunate injury. Tries from Vunipola and Joseph have steadied the ship for Stuart Lancaster's side but the second half promises to be a fascinating contest. 

England go to their lineout maul close to the Italian line but Robshaw and Haskell are driven back by the Azzurri pack and are awarded the put-in to the resultant scrum. 

Amid all the excitement generated by Jonathan Joseph's electric, long-range try, England's coaches will be especially satisfied by Chris Robshaw's breakdown work. Not so long ago, the management were casting doubt on their captain's credentials at the ruck, but he earned the turn-over which paved the way for Joseph's scorching run and finish. Moments later, James Haskell also weighed in with a breakdown 'steal'. An area of previous English weakness is becoming a strength on this evidence.

James Haskell is penalised at the breakdown but Haimona fails to punish England as his long-range penalty effort drags to the right and wide. 

That was a marginal decision by the TMO. Replays seemed to suggest that after Billy Vunipola had crashed over the line and landed on top of Edoardo Gori, the ball had ended up touching the ground, but it wasn't clear if the England No 8 was in control of it at the time. Nonetheless, the try was awarded. Italy will feel aggrieved, but the home side are increasingly asserting themselves after a slow start.

What a try from Jonathan Joseph! Chris Robshaw steals the ball on the deck and when the ball is spun out to the Bath centre, he doesn't need a second invitation to stretch his legs. 

Joseph shows his stunning footwork to step Haimona before setting off on a 40 metre dash to the try line. Awesome from the Bath man. After a stuttering start, England have cruised into a 10-point lead. 

Great power from Billy Vunipola to power over in the left corner. Vunipola managed to squeeze over following a superb lineout move involving disguised passes from Chris Robshaw and Dave Attwood. 

George Ford pulls the touchline conversion wide, but England finally have the lead in this game. 

England have their first points on the board after 18 minutes of play. 

Haimona has made a great start to the game but he'll be disappointed with his indiscipline at the ruck which allows George Ford to bisect the posts to get his side back in the game. 

Kelly Haimona has made a sensational start to this game. Italy's Kiwi No 10 is 17st but he has deft skills on the ball, as he has already demonstrated. The dummy and break from his own 22 showed a daring instinct, his distribution in the lead-up to Sergio Parisse's try was shrewd and his well-weighted kick into England's 22 so nearly sent Andrea Masi away for a second Italian try.

Mike Brown has left the field on a stretcher following his collision with Masi. Billy Twelvetrees is on for the Quins man. Jonathan Joseph moves to the wing with Anthony Watson going to full back

Mike Brown did brilliantly to bring down Andrea Masi after the Wasps centre gathered Haimona's brilliant chip, but the Harlequins full back is getting treatment on the ground after an apparent head knock. 

It's all one-way traffic so far at Twickenham. 

Italy had a great attacking platform on the England 22 allowing Haimona to release Andrea Masi in midfield.  Giovambattista Venditti, George Biagi and Francesco Minto all carried in the attack before Haimona threaded through a lovely weighted kick which Masi regathered. 

The Wasps player was brought to ground by Mike Brown but the onrushing Martin Castrogiovanni spilled his offload with the try line begging...

Italy are full value for their early lead here. The Azzurri came firing out of the blocks early on with centre Luca Morisi looking dangerous with ball in hand. 

Kelly Haimona made a lovely half break with a dummy inside his 22 in just one of several Italian phases of possession.

Interesting start to this game. 

Who saw that coming! Great build-up from Italy on the short side and Sergio Parisse throws an audacious dummy and barrels over close to the line. Great start for the visitors. 

Mike Brown takes the kick-off and takes the tackle. Ben Youngs gets a poor pass away to George Ford who does well to clear his lines. 

Time for the anthems and then we'll be underway...

Ten minutes to kick-off here at Twickenham and it's fair to say that there's a distinct lack of noisy tension around the place. Understandable expectation of a resounding home win, but England will need the home support early on as they attempt to soften up Italy's formidable pack.

Rain in the air 15 minutes before kick off at Twickenham. England head in to changing rooms after Italy. Twickenham's otherwise excellent surface will be a little slippery early on. 

Both sides are out warming up on the Twickenham turf. The sizable figure of Kelly Haimona will be central to Italy's fortunes this afternoon. 

The Azzurri have struggled to fill the No 10 jersey since Diego Dominguez retired in the early noughties. Jacques Brunel has turned to Kiwi-born powerhouse Haimona for this year's championship. 

The last time Italy came to Twickenham, England got into a right tussle. Six Toby Flood penalties secured an 18-11 victory against the Azzurri two years ago as Lancaster's side survived an almighty scare. 

England backs coach Andy Farrell is hoping his side can keep the good times rolling against the Azzurri following their triumph in Cardiff. 

Farrell said: 'It is important to win your home games — with what we have got coming up this year. All week there has been a feelgood factor within the rugby nation. We want to put on a performance to make sure people come to the ground, enjoy themselves and have the feelgood factor next week. That only comes from a good performance.'

McLean; Sarto, Morisi, Masi, Venditti; Haimona, Gori; De Marchi, Ghiraldini, Castrogiovanni, Fabio, Bortolami, Bergamasco, Minto, Parisse

Brown; Watson, Joseph, Burrell, May; Ford, B Youngs; Marler, Hartley, Cole; Attwood, Kruis; Haskell, Robshaw (capt), B Vunipola

Well, England certainly blew the tournament wide open with that stunning display 21-16 victory at the Millennium Stadium on the opening night of the Championship. 

Stuart Lancaster's side welcome the perennial whipping boys of the Six Nations to Twickenham this afternoon. The Azzurri haven't got the best record against England to put it lightly. These two sides first met in a Test match in 1991. The record reads: England played 20, Won 20. The odds are certainly stacked against Jacques Brunel's side...

Lancaster's men go into this contest as overwhelming favourites. Can Italy throw a spanner in the works this afternoon? Stay tuned. 

@highlight

Stuart Lancaster's side secure a 47-17 victory at Twickenham  

@highlight

England lead Italy 15-5 at half-time 

@highlight

Sergio Parisse crossed for Italy early on 

@highlight

But England replied through tries from No 8 Billy Vunipola and outside centre Jonathan Joseph   

@highlight

Lancaster's men added furthur tries from Ben Youngs, Joseph, Danny Cipriani and Nick Easter in the second half  

@highlight

ENGLAND XV: Brown; Watson, Joseph, Burrell, May; Ford, B Youngs; Marler, Hartley, Cole; Attwood, Kruis; Haskell, Robshaw (capt), B Vunipola

@highlight

Replacements: T Youngs, M Vunipola, Brookes, Easter, Croft, Wigglesworth, Cipriani, Twelvetrees

@highlight

ITALY XV: McLean; Sarto, Morisi, Masi, Venditti; Haimona, Gori; De Marchi, Ghiraldini, Castrogiovanni, Fabio, Bortolami, Bergamasco, Minto, Parisse

@highlight

Replacements: Manici, Aguero, Chistolini, Furno, Vunisa, Palazzani, Allan, Bisegni