By
Jonathan O'Callaghan

In September 2013 Nasa announced they were pretty sure that Voyager 1, the most distant man-made spacecraft from Earth, had passed into interstellar space.

And now that finding has been confirmed, thanks to a ‘tsunami wave’ of radiation from the sun.

The wave vibrated particles in the spacecraft’s vicinity and allowed scientists to calculate that the probe was in a different region of the universe to our own solar system.

Nasa has confirmed that Voyager 1, illustrated here, has successfully entered interstellar space. Data from the spacecraft in September 2013 suggested that it had done so almost a year earlier in August 2012 but the finding has only just been confirmed thanks to an ejection from the sun

Voyager 1 launched in 1977 and has been making its way out of the solar system ever since.

Along the way it made numerous discoveries and observations at various locations including Jupiter and Saturn.

It is 37 years since the twin Voyager 1 and 2 spacecraft were launched and the pair continue to explore where nothing from Earth has flown before.

Their primary mission was the exploration of Jupiter and Saturn.

After making a string of discoveries there -- such as active volcanoes on Jupiter's moon Io and intricacies of Saturn's rings -- the mission was extended.

Voyager 2 went on to explore Uranus and Neptune, and is still the only spacecraft to have visited those outer planets.

The current mission for both spacecraft, the Voyager Interstellar Mission, is to explore the outermost edge of the Sun's domain and beyond.

Having passed the outermost planets it is now the furthest man-made object from Earth and continues to send back data as it becomes the first spacecraft ever to enter interstellar space.

The recent confirmation that it was in interstellar space was made by observing the effects ‘bubbles’ from the sun had on Voyager 1’s surroundings.

The bubbles originate as waves known as coronal mass ejections from the sun, huge outpourings of energy that often accompany a solar flare.

These waves are what led scientists to the conclusion, in the fall of 2013, that Voyager 1 had indeed left our sun's bubble, entering a new frontier.

As they move out from the sun they create the bubbles of radiation and since 2012 three of these bubbles had been observed, but this latest one confirms the earlier findings.

‘Normally, interstellar space is like a quiet lake,’ said Ed Stone of the California Institute of Technology in Pasadena, California, the mission's project scientist since 1972.

‘But when our sun has a burst, it sends a shock wave outward that reaches Voyager about a year later.

‘The wave causes the plasma surrounding the spacecraft to sing.’

One cause of contention from Voyager 1 is that there have been repeated announcements that it has 'entered interstellar space', with several false alarms, which has become somewhat of a running joke among astronomers.

However, Professor Martin Barstow, President of the Royal Astronomical Society and Professor of Astrophysics and Space Science at the University of Leicester, explains to MailOnline why this is so.

'I worked on Voyager 1's cruise science in the 1980s and 90s and I think it is a remarkable mission, still going almost 40 years after its launch in 1977,' he says.

'It is interesting that Nasa keeps renouncing [it has entered interstellar space], but that is because it’s really hard to be sure.

'The boundary between the solar system and interstellar space is not very sharp, or obvious, but is complicated. It also moves as solar activity varies.

'It’s quite likely that the boundary has moved backwards and forwards past the spacecraft over the last few years as we have gone from solar minimum to solar maximum, where we are now.'

Voyager 1 became the furthest man-made object from Earth in the 1990s when it overtook the slower deep-space probes Pioneer 10 and 11 that had been launched previously. It will remain operational until about 2025, at which point it will be adrift in space. It will take 17,500 years for Voyager 1 to travel one light year

Data from this newest tsunami wave generated by the sun confirms that Voyager is in a region between the stars filled with a thin soup of charged particles, also known as plasma.

The mission has not left the solar system, though, as it has yet to reach a final halo of comets surrounding our sun known as the Oort Cloud.

Announcements of Voyager 1 entering interstellar space are a running joke for astronomers (shown), as there have been many 'false alarms' before - but this seems to be the real deal

But it has broken through a wind-blown magnetic bubble, or heliosphere, that encases the solar system.

'All is not quiet around Voyager,' said Don Gurnett of the University of Iowa, Iowa City, the principal investigator of the plasma wave instrument on Voyager, which collected the definitive evidence that Voyager 1 had left the sun's heliosphere.

'We're excited to analyze these new data. So far, we can say that it confirms we are in interstellar space.'

So, how do scientists know that Voyager 1 is now in interstellar space?

It's due to our sun going through periods of increased activity, where it explosively ejects material from its surface, flinging it outward.

These events, called coronal mass ejections, generate shock, or pressure, waves.

Three such waves have reached Voyager 1 since it entered interstellar space in August 2012.

The first was too small to be noticed when it occurred and was only discovered later, but the second was clearly registered by the spacecraft's cosmic ray instrument in March of 2013.

Cosmic rays are energetic charged particles that come from nearby stars in the Milky Way galaxy.

The sun's shock waves push these particles around like buoys in a tsunami. Data from the cosmic ray instrument tell researchers that a shock wave from the sun has hit.

Voyager 1 and its twin, Voyager 2, were launched 16 days apart in 1977. Both spacecraft flew by Jupiter and Saturn (illustrated here). Voyager 2 also flew by Uranus and Neptune. Voyager 2, launched before Voyager 1 but on a slower trajectory, will also enter interstellar space in a few years

Meanwhile, another instrument on Voyager registers the shock waves, too. The plasma wave instrument can detect oscillations of the plasma electrons.

'We live in a dynamic solar system, with the atmosphere of our Sun interacting with the planets and galactic cosmic winds,' Kelvin Long, Executive Director of the Initiative for Interstellar Studies, tells MailOnline. 

'The definition of the solar system boundary is not yet well characterised, and this is mainly due to the very low level of space probe reconnaissance we have done of the outer solar system; namely the Voyagers and Pioneers.

'To better characterise the extent of our solar system it is clear therefore that we need more reconnaissance and exploration and also to obtain better measurements of the interstellar medium.

'These are clear science goals for future missions.'

'The tsunami wave rings the plasma like a bell,' said Stone.

'While the plasma wave instrument lets us measure the frequency of this ringing, the cosmic ray instrument reveals what struck the bell - the shock wave from the sun.'

This ringing of the plasma bell is what led to the key evidence showing Voyager had entered interstellar space.

Because denser plasma oscillates faster, the team was able to figure out the density of the plasma.

In 2013, thanks to the second tsunami wave, the team acquired evidence that Voyager had been flying for more than a year through plasma that was 40 times denser than measured before - a telltale indicator of interstellar space.

Why is it denser out there? The sun's winds blow a bubble around it, pushing out against denser matter from other stars.

Now, the team has new readings from a third wave from the sun, first registered in March of this year.

These data show that the density of the plasma is similar to what was measured previously, confirming the spacecraft is in interstellar space.

And thanks to the sun's rumblings, Voyager has the opportunity to listen to the singing of interstellar space - an otherwise silent place.

@highlight

Nasa researchers in California say Voyager 1 is in interstellar space

@highlight

They confirmed the finding from last year using a wave of solar radiation

@highlight

The spacecraft is currently over 19 billion kilometres from Earth

@highlight

In September 2013 it was announced it had probably made it into interstellar space, but Nasa couldn't be 100 per cent sure

@highlight

Now they are thanks to observing the vibration of particles in its vicinity when a 'solar tsunami' passed through

@highlight

'We can say that it confirms we are in interstellar space,' said the team