Jenson Button, newly wearing a wedding ring, can afford to smile even if some of the rituals of his long career in Formula One will not be repeated at Sunday’s Australian Grand Prix.

Three times he has won around Albert Park. There is little chance of that tally being added to in his temperamental McLaren-Honda.

There is absolutely no chance of a pre-race coffee and post-race celebratory fish and chips at the Stokehouse on St Kilda beach. It has burned down.

McLaren's Jenson Button is gearing up for his 16th season in Formula One

Button has recorded three victories in Melbourne during his career

But, aged 35, just being here is the great boon. A 16th season beckons after he feared being dropped last year to make way for Fernando Alonso, the incoming double world champion from Ferrari.

But he was kept on — the result of a boardroom fight between McLaren chairman Ron Dennis, who favoured Kevin Magnussen partnering Alonso, and fellow shareholder Mansour Ojjeh, who supported whichever driver Dennis did not want. Ojjeh won.

‘This is where I should be,’ said Button in the paddock on Thursday. ‘It doesn’t feel like a bonus, it feels normal, — and exciting because it is such an exciting new package of engine and car.’

But as cruel irony would have it, Alonso will miss this race after he banged his head in testing and Magnussen has been called up to replace him in tandem with Button. 

Button poses with the NSX concept vehicle at a Honda F1 Grand Prix press conference

Alonso’s accident in Barcelona last month prompted a host of theories: among them that he had a fit before losing control or suffered an electric shock. The second theory is totally denied by the team. Button, however, was concerned enough to examine the data of Alonso’s car to satisfy himself there was nothing for him to fear. 

‘I will not get into a car unless I am 100 per cent sure that it is safe,’ he said. ‘I spent hours going through the data with the engineers and talking to them about the incident.

‘There was nothing wrong with the car whatsoever. I needed to know that before getting into the car at the next test, so I made certain of it.

‘When you are driving at the limit, you need to be sure. I trust these guys and that is why I have the confidence to drive it this weekend.’

Yes, but not as fast as McLaren would like. They are nowhere near the top teams — in expected order: Mercedes, by miles, Williams, Red Bull and Ferrari.

Button, a glass-half-full sort of man, was realistic in his assessment of his team’s prospects. 

Button married his fiancee Jessica Michibata in a secret ceremony in Hawaii in January

‘We definitely won’t be fighting for a win here,’ he said. ‘The important thing for us is to see improvements every race and progress.

‘The power unit package is so tight and so advanced that you do have issues and we have had more issues than we would have liked.

‘Whether we score points here or not is irrelevant; it is all about improvements race to race.

‘I would rather not score points here and then win a race later in the year.’

This prognosis is a bit dispiriting given the expectations generated by McLaren’s new partnership with Honda. Should the team’s fortunes not turn around, questions will be asked about the success of the restructuring carried out a year ago.

Martin Whitmarsh, who it was yesterday announced will take over as chief executive of Sir Ben Ainslie’s America’s Cup challenge, was sacked as team principal. Eric Boullier was brought in to replace him and Dennis took on a more involved role as chief executive.

‘We are a year behind the other manufacturers and the design is more aggressive to be a challenge to Mercedes in the future,’ added Button.

‘Honda are the manufacturer who will take it to Mercedes. There are going to be teething problems, but it is about answering those issues right now.’

While Button brings his experience to bear, another British driver, Will Stevens, is just starting out.

The 23-year-old Essex-born racer made his debut in Abu Dhabi for Caterham last November and the Australian Grand Prix should be his first race for Manor, if they qualify by the 107 per cent rule — within seven per cent of the pole-sitting car’s time. He drove well on his debut and was assured in his press briefing yesterday.

Stevens, whose father is a successful financial figure, comes with an estimated £5million of personal sponsorship to fund his ride. He has signed a one-year contract.

‘Two months ago you couldn’t say I would definitely be here,’ he said of the last-minute deal that saved Manor. ‘There were other options, but we held out for this.’

He has even less chance of scoring points than Button. ‘We need to try to be here at the end of the race to pick up the pieces,’ he said.

 

@highlight

Jenson Button has recorded three victories in Melbourne during his career

@highlight

The McLaren driver was kept on for 16th season due to a boardroom fight

@highlight

He married his fiancee Jessica Michibata in a secret ceremony in January