These fascinating pictures show how engineers in 1960s California secretly developed the SR-71 Blackbird for the US Air Force – a plane which still holds the record for being the fastest ever aircraft.

The Lockheed SR-71 Blackbird is a long-range, strategic reconnaissance aircraft and these once classified photos reveal how Lockheed built three types of Blackbird - A, B and C in top secret conditions in Burbank, California.

The aircraft were built by American aerospace company Lockheed under a 'black project' - a highly classified military defence project unacknowledged by the government until its declassification.

Since July 28 1976 the SR-71 Blackbird has held the world record for the fastest air-breathing manned aircraft with a record speed of 2,193.2mph.

Scroll down for video 

Scientists at Lockheed's Skunk Works in Burbank developed the plane -this picture shows their assembly line

Lockheed engineers working on the Blackbird - the dark colour acts as a camouflage 

To withstand high temperatures during sustained Mach 3 flight, the Blackbird required an array of specially developed materials including high temperature fuel, sealants, lubricants, wiring and other components

Renowned American aerospace engineer Clarence 'Kelly' Johnson was responsible for many of the design's innovative concepts.

During reconnaissance missions, the SR-71 operated at high speeds and altitudes to allow it to outrace threats - if a surface-to-air missile launch was detected, the standard evasive action was simply to accelerate and out fly the missile.

The SR-71 was designed to have basic stealthy characteristics and served as a precursor to modern stealth aircraft.

The Blackbird served with the U.S. Air Force from 1964 to 1998 and a total of 32 aircraft were built; 12 were lost in accidents, but none were ever lost to enemy action. 

Around 93% of the plane's frame was made of titanium alloy which allowed the aircraft to fly fast and high

An SR-71B trainer over the Sierra Nevada Mountains in 1994 - the raised second cockpit is for the instructor

Since 1976 the Blackbird has held the world record for the fastest air-breathing manned aircraft

Flying at 80,000 ft meant that crews could not use standard masks, which would not provide enough oxygen above 43,000 ft, so specialist protective pressurised suits were made. 

The plane's titanium skin was capable of surviving temperatures up to 482C.

The SR-71 was the world's fastest and highest-flying operational manned aircraft throughout its career and is believed to be the most advanced airplane ever built in relation to the technology available at the time.

These once classified pictures reveal how Lockheed built A, B and C versions of plane - this version is based on the Blackbird's precursor, the A-12 Oxcart

SR-71 was designed to have basic stealth characteristics and served as a precursor to modern stealth aircraft

Almost every aspect of its design required new approaches or breakthroughs in technology. 

To withstand high temperatures generated by friction in the upper atmosphere during sustained Mach 3 flight, the Blackbird required an array of specially developed materials including high temperature fuel, sealants, lubricants, wiring and other components. 

Around 93% of the Blackbird's airframe consisted of titanium alloy that allowed the aircraft to operate in a regime where temperatures range from 450 degrees  to 950 degrees. 

On July 24 1964, US President Lyndon B. Johnson publicly announced the existence of the classified Lockheed SR-71 program. 

The first flight was held on December 22 and operational aircraft deliveries began in 1966.

An SR-71 refueling from a KC-135Q Stratotanker during a flight in 1983. Because they were powered by a uniquely formulated jet fuel, SR-71 Blackbirds were refueled exclusively by KC-135Q tankers

1. Los Angeles, CA, to Washington, D.C., distance 2,299.7 miles, average speed 2,144.8 miles per hour (3,451.7 km/h), and an elapsed time of 64 minutes 20 seconds.

2. West Coast to East Coast, distance 2,404 miles, average speed 2,124.5 miles per hour, and an elapsed time of 67 minutes 54 seconds.

3. Kansas City, Missouri, to Washington, D.C., distance 942 miles, average speed 2,176 miles per hour, and an elapsed time of 25 minutes 59 seconds.

4. St. Louis, Missouri, to Cincinnati, Ohio, distance 311.4 miles, average speed 2,189.9 miles per hour  and an elapsed time of 8 minutes 32 seconds.

These four speed records were accepted by the National Aeronautic Association (NAA), the recognized body for aviation records in the United States. 

The Blackbird's first flight was held on December 22 and operational aircraft deliveries began in 1966

The Blackbirds kept flying after their retirement from the USAF - one of them even stayed at NASA. This photo shows an SR-71 at the Armstrong Flight Research Center  being retrofitted for a test

@highlight

Lockheed SR-71 Blackbird was built in the 1960s by engineers in California

@highlight

Long-range strategic reconnaissance aircraft was made for US Air Force

@highlight

Classified pictures reveal how Lockheed built A, B and C versions of plane

@highlight

Held world record for the fastest air-breathing manned aircraft since 1976