Stare up at the moon and you might be forgiven for thinking that it’s a barren, desolate world that does little more than orbit Earth.

But research suggests that our planet’s natural satellite is not a lifeless hunk of rock - it’s actually got a hot liquid layer around its core that is still churning today.

If true, the study would suggest the moon is more active than once thought, and it would also have important implications for the history of Earth.

Researchers in Beijing have presented evidence that part of the moon is still liquid. They say Earth's gravity is keeping a molten layer around the moon's core (illustration shown). The conclusion is based on seismic experiments from the Apollo mission and also information from Japan's Selene lunar orbiter

It has proven for the first time that the deepest part of the lunar mantle is soft, based upon the agreement between observation results and the theoretical calculations.

The research team also clarified that heat is efficiently generated by the tides in the soft part, deepest in the mantle. 

In general, a part of the energy stored inside a celestial body by tidal forces (caused by being pushed and pulled by its partner, in this case Earth, as it orbits) is changed to heat.

The heat generation depends on the softness of the interior. 

Whereas previous research also suggests that some part of the energy inside the moon due to the tidal forces is changed to heat, the present research indicates that this type of energy conversion does not uniformly occur in the entire moon, but only intensively in a soft layer.

The research team believes that the soft layer is now warming the core of the moon as the core seems to be wrapped by the layer, which is located in the deepest part of the mantle, and which efficiently generates heat. 

They also expect that a soft layer like this may efficiently have warmed the core in the past as well.

Any two bodies in orbit in space have a gravitational effect on one another, but as no orbit is perfectly circular, the force of gravity varies as they move closer and further from one another.

The effect is very noticeable on moons such as Jupiter’s Io, where volcanoes rage on its surface as it swings round its parent planet in an elliptical orbit and is pushed and pulled by the planet’s gravity.

And the effects are apparent here, too, on Earth, where the seas and oceans undergo daily tides due to the gravity of the moon.

Of course, given that our planet is 81 times larger than the moon, it’s obvious that in turn the moon would experience similar forces as it orbits.

It had previously been considered that this might cause part of the moon’s core to be liquid, just as how Earth’s core is liquid, but until now no one had shown this could be true.

Now an international research team, led by Dr Yuji Harada from Planetary Science Institute, China University of Geosciences, has found that there is an extremely soft layer deep inside the moon and that heat is effectively generated in the layer by the gravity of Earth.

The discovery was made by comparing the deformation of the moon as precisely measured by Jaxa's Selene (Selenological and Engineering Explorer) spacecraft and other probes with theoretical calculations.

The findings suggest that the interior of the moon has not yet cooled and hardened, and also that it is still being warmed by the effect that Earth has on the moon.

Researchers say the findings provide a chance to reconsider how both Earth and the moon evolved - and continues to evolve - since their births through mutual influence.

Any two bodies in orbit have a gravitational effect on each other, but as no orbit is perfectly circular the force of gravity varies as they move closer and further. This effect causes a  pushing and pulling effect, noticeable by Earth's tides. An exaggerated diagram of this effect on the moon is shown

This is an estimate value of the Moon’s interior viscosity structure replicated with the observational results in this research. The viscosity is one indicator of how tender or hard the moon's interior is. For reference, the density structure and seismic velocity based on previous studies are added

‘I believe that our research results have brought about new questions,’ said Dr Harada. ‘For example, how can the bottom of the lunar mantle maintain its softer state for a long time?

‘To answer this question, we would like to further investigate the internal structure and heat-generating mechanism inside the moon in detail.

‘In addition, another question has come up: How has the conversion from the tidal energy to the heat energy in the soft layer affected the motion of the moon relative to Earth, and also the cooling of the moon?

‘We would like to resolve those problems as well so that we can thoroughly understand how the moon was born and has evolved.’

The research team focused on the structure deep inside the moon. During the Apollo programme, seismic observations were carried out on the moon.

Analysis of data concerning the internal structure of the moon indicates that the satellite is considered to consist mainly of two parts: the ‘core’ - the inner portion made up of metal - and the ‘mantle’, the outer portion made up of rock.

Researchers found that the observed tidal deformation of the moon can be explained if  there was an extremely soft layer in the deepest part of the lunar mantle.

Previous studies have indicated that  a part of the rock at the deepest part inside the lunar mantle may be molten.

These results support the above possibility since partially molten rock is soft.

Here Buzz Aldrin is shown with a seismic experiment during the Apollo 11 mission in July 1969. Experiments such as these provided the researchers with information they could use to prove that part of the moon's core is still hot and molten

Another investigator, Professor Junichi Haruyama of the Institute of Space and Aeronautical Science at Jaxa, mentioned the significance of this research.

'A smaller celestial body like the moon cools faster than a larger one like the Earth does,' he said. 

'In fact, we had thought that volcanic activities on the moon had already come to a halt. Therefore, the Moon had been believed to be cool and hard, even in its deeper parts. 

'However, this research tells us that the Moon has not yet cooled and hardened, but is still warm. 

'It even implies that we have to reconsider the question as follows: How have Earth and the moon influenced each other since their births? 

'That means this research not only shows us the actual state of the deep interior of the moon, but also gives us a clue for learning about the history of the system including both Earth and the moon.'

@highlight

Researchers in Beijing present evidence that part of the moon is liquid

@highlight

They say Earth's gravity is keeping a molten layer around the moon's core

@highlight

The conclusion is based on seismic experiments from the Apollo missions and also information from Japan's Selene lunar orbiter

@highlight

Suggests the moon's core has not cooled and is still churning

@highlight

It could provide information on the history of the Earth-moon system