Green subsidies added to families’ energy bills are to rise nearly four-fold by 2030, according to a report published today.

State funding for wind and solar power and a carbon tax on coal and gas will together add £175 to the average household bill by 2030, according to the Government’s climate advisors.

That is nearly four times the £45 added to bills last year, the Committee on Climate Change said.

The cost of energy to business and industry is set to double in the same period, with the price of goods and services bound to increase as a result.

The report is published as politicians from 196 countries meet in Peru to try to agree a treaty to curb climate change.

State funding for wind and solar power and a carbon tax on coal and gas will together add £175 to the average household bill by 2030, according to the Government’s climate advisors. File picture

Energy Secretary Ed Davey, who arrived at the UN summit in Lima yesterday, is among those trying to push for every nation to adopt strict targets on carbon emissions to restrict global warming to 2C.

Britain has already adopted the most stringent climate law in the world – a legal obligation to reduce greenhouse gases by 80 per cent by 2050.

But Mr Davey wants other nations to follow suit, to adopt rules that will force them to reduce emissions.

The impact of such policies is laid bare in the Committee on Climate Change report today.

In order to reduce emissions of carbon dioxide in line with its strict targets, the British government has agreed to plough money into solar farms, wind turbines and nuclear power – with the cost added to consumer bills.

The Government also has several measures in place designed to deter companies from emitting greenhouse gases, which in turn create a ‘carbon price’ that is added to the cost of power generated by gas, coal and oil.

In order to reduce emissions of carbon dioxide, the British government has agreed to plough money into solar farms, wind turbines and nuclear power – with the cost added to consumer bills

The committee estimates that these measures together made up £45 of the average £1,140 dual gas and electricity bill in 2013.

The green components will more than double to £100 by 2020, and soar to £175 by 2030, by which time the total average bill will be £1,305.

The committee also identified £70 added to bills to support energy efficiency measures such as new boilers in low income homes and for wall and loft insulation. This element will of bills will decrease to £60 in 2020 and £40 in 2030.

The committee said that funding for green power helped cut as much emissions as taking 10 million cars off the road.

Most of the rises in household bills, which have increased almost £500 on average since 2004, are due to rising wholesale gas prices and investment in electricity and gas networks, it said.

The cost to business will also rise, with the green element of energy bills set to double to 31 per cent for the commercial sector and 26 per cent for the industrial sector.

Consumers will undoubtedly be effected by this, with the cost due to drive up the price of food, clothes and services.

Most of the rises in household bills, which have increased almost £500 on average since 2004, are due to rising wholesale gas prices and investment in electricity and gas network. File picture

The report said: ‘Meeting the UK’s statutory carbon targets will add to energy bills in the future, though with potential to offset much of this through energy efficiency.

‘Electricity generation will need to shift from fossil fuels to low-carbon alternatives such as renewables and nuclear, which are currently more expensive.’

Committee chairman Lord Deben added: ‘Last year, as energy consumers we all helped hundreds of thousands of poorer people to have warmer homes and contributed to real reductions in our emissions in the fight against climate change.

‘Many people saved more than that by taking simple energy saving measures that didn't interfere with their life-style.’

Dr John Constable, director of Renewable Energy Foundation, a UK charity critical of the costs of policies to consumers said: ‘Consumers should be aware that low carbon policies do not just affect their energy bills, but also increase the cost of living as industrial and commercial consumers pass on their costs in the price of goods and services.

‘The CCC’s study shows, in the fine print, that this effect will range from £210 to £360 a year 2020, depending on the cost of fossil fuels, and between £345 and £705 a year in 2030. This is very expensive.’

The Government has repeatedly insisted that imposing green levies and taxes will save consumers money in the long-run, because energy efficiency measures will mean that total bills are cheaper than they otherwise would have been.

However, ministers were forced to drastically downgrade their estimates of the potential saving last month. Previously they had estimated that the average bill would be £166 cheaper in 2020 than if no green policies had been adopted – but as the Daily Mail revealed in November, the Government’s own calculations have reduced that potential saving by 45 per cent to £92.

A spokesman for the Department of Energy and Climate Change said: ‘Thanks to Government policies, bills are an estimated £90 lower this year and will be even lower by 2020.

‘Our policies are designed to keep the lights on, reduce polluting emissions, cut energy use at the lowest possible cost to gas and electricity customers.’

 

@highlight

The cost of energy to business and industry is set to double in the same period, causing a knock-on effect to other goods and services

@highlight

Britain has already adopted the most stringent climate law in the world