Supermassive black holes at the centre of large galaxies could be powering blasts from deep inside the galaxy's core, astronomers have claimed. 

The huge outpourings of material are responsible for ejecting enough dust and gas to build more than a thousand stars the size of our sun every year. 

And these outflows could also remove huge quantities of star-making gas, dictating the size, shape and overall fate of galaxies.

Scroll down for video 

Astronomers studying the supermassive black hole at the centre of the galaxy IRAS F11119+3257 have found proof that the winds blown by the black hole are sweeping away the host galaxy's reservoir of raw material to form stars. This artist's impression depicts how a black hole accretes the surrounding matter through a disc

The image looks uncannily like an eye in the sky - such as the Eye of Sauron from Lord of the Rings

Astronomers have sought the driving force behind these massive molecular outflows for years, and now a team of University of Maryland scientists has found an answer. 

The galaxy in the study, known as IRAS F11119+3257, has an actively growing supermassive black hole at its centre. 

This means that, unlike the large black hole at the centre of our own Milky Way galaxy, this black hole is actively consuming large amounts of gas. 

As material enters the black hole, it creates friction, which in turn gives off electromagnetic radiation - including X-rays and visible light.

Black holes that fit this description are called active galactic nuclei (AGN), and their intense radiation output also generates powerful winds that force material away from the centre of a galaxy.

In February it was revealed that a supermassive black hole 12 million times larger than the sun and powering ‘the brightest lighthouse in the distant universe’ has been discovered.

The extraordinary object is at the centre of a quasar - an intensely powerful galactic radiation source - with a million billion times the sun’s energy output.

The nature of quasars has remained a mystery since they were discovered in 1963.

But scientists theorise that they are generated by matter heating up as it is dragged into supermassive black holes at the centre of distant galaxies.

The new object, named SDSS J0100+2802, is 12.8 billion light years from Earth and was formed 900 million years after the Big Bang, which gave birth to the universe.

Astronomers cannot explain how such an enormous black hole could have formed so soon after the first stars and galaxies emerged. 

The study found that these AGN winds are powerful enough to drive the large molecular outflows that reach to the edges of the galaxy's borders.

Although theorists have suspected a connection between AGN winds and molecular outflows before, the current study is the first to confirm this link.

'This is the first galaxy in which we can see both the wind from the active galactic nucleus and the large-scale outflow of molecular gas at the same time,' said lead author Dr Francesco Tombesi, an assistant research scientist in the University of Maryland's astronomy department. 

He also worked at Nasa's Goddard Space Flight Centre. 

The team analysed data collected in 2013 by Suzaku, an X-ray satellite operated by the Japan Aerospace Exploration Agency (Jaxa) and Nasa, as well as data from Esa's Herschel Space Observatory.

An alternate theory says that active star formation near the galactic centre could drive these outflows.

But the brightness of IRAS F11119+3257's active nucleus - which is responsible for about 80 per cent of the galaxy's overall radiation - suggested otherwise. 

Star formation alone can't explain this intense concentration of energy, leading the researchers to conclude that the AGN winds must be the primary driver.

The outflows could also remove huge quantities of star-making gas, dictating the size and shape of galaxies. This artist's impression shows the outflow of molecular gas (red) in a galaxy hosting a supermassive black hole at its core. The study is based on data from the Herschel and Suzaku space observatories

This is a red-filter image of IRAS F11119+3257 (inset) from a telescope at the University of Hawaii's, showing faint features that may be tidal debris, a sign of a galaxy merger. The background is a wider view of the region from the Sloan Digital Sky Survey

'The temptation is to ignore the supermassive black hole when studying galactic dynamics and evolution, but our study shows that you can't because it influences galaxies on the larger scale,' added co-author Dr Marcio Meléndez. 

Limited satellite time means that, at least for now, the team has only this one galaxy as a baseline for study.

But now that they have a better idea what they are looking for, they will be able to find more candidate galaxies in the future. 

Within the next year, Jaxa and Nasa will launch Astro-H, a successor satellite to Suzaku.

The instruments aboard Astro-H will make it possible to study more galaxies like IRAS F11119+3257 in greater detail.

'These are not like normal spiral or elliptical galaxies. They're like train wrecks,' said co-author Dr Sylvain Veilleux. 

'Two galaxies collided with each other, and it's now a single object. This train wreck provided all the material to feed the supermassive black hole that is now driving the huge galactic-scale outflow.' 

The findings were published in the journal Nature.

@highlight

University of Maryland scientists present theory for galaxy cores

@highlight

They say supermassive black holes are causing blasts of material

@highlight

This leads to the formation of thousands of stars ever year

@highlight

And the huge outflows could also dictate the size and shape of galaxies 