Many people need a gentle nudge to exercise, and what better motivation than saving money on your electricity bills.

That's the concept behind the Wheel washing machine and treadmill, created by South Korean designer Si Hyeong Ryu.

He envisages a large hamster-style wheel fitted with rubber that captures kinetic energy as a person runs on it, and uses this to power other home appliances.

The Wheel (pictured) was created by South Korean designer Si Hyeong Ryu for the 2014 Electrolux Design Lab competition. His concept collects kinetic energy generated by the treadmill, which is built into a large hamster-style wheel

It uses this energy to power washers built into the wheel, to churn water and wash clothes as well as light up a display.

Realising at the last minute your favourite dress is dirty, or you don’t have a clean shirt for an important meeting could soon be a thing of the past. 

The Swash is a washing machine and iron in one that refreshes clothes, removes odours and flattens out wrinkles at the press of a button.

Pods of liquid are sprayed directly onto the clothes, before a drier circulates air through the device, and a dirty item is ready to wear in just 10 minutes.  

Ryu created the concept for the 2014 Electrolux Design Lab competition.

‘Wheel is a crossover between gym bike and washing machine by using human kinetic power to save electricity and our nature,' said Ryu.

‘The power generated from the spinning can be used to wash clothes and the unused power can be savedas electricity in the future.’

The concept also features washing balls inside the canisters, designed to shorten the washing time and save water in the process. 

The power generated can be used to wash clothes and the unused power can be saved to a battery. The concept also features washing balls inside the canisters, designed to shorten the washing time and save water, solar panels to generate extra energy, and a flexible display (pictured)

The concept design has been likened to a hamster on a wheel (stock image pictured)

'The treadmill mechanism helps the user for better work out experience and healthier life,’ continued Ryu.

Elsewhere, the Wheel has a flexible display, which provides ‘a visual experience’ for the user - such as films or music videos. 

Solar panels also help absorb ‘solar energy from daylight’, and these panels can be a substitute energy source when the treadmill isn’t being used.

Ryu is a product design graduate from Samsung Art and Design School and is now a freelance designer. 

The theme for this year's Electrolux competition was The Home of Tomorrow.

 

@highlight

The Wheel was created by South Korean designer Si Hyeong Ryu

@highlight

His concept collects kinetic energy generated by the treadmill

@highlight

The treadmill is built into a large hamster-style wheel 

@highlight

It then uses this energy to power a washing machine built into wheel

@highlight

Ryu created the concept for the 2014 Electrolux Design Lab competition