A supermassive black hole 12 million times larger than the sun and powering ‘the brightest lighthouse in the distant universe’ has been discovered.

The extraordinary object is at the centre of a quasar - an intensely powerful galactic radiation source - with a million billion times the sun’s energy output.

The nature of quasars has remained a mystery since they were discovered in 1963. 

An international team of scientists has discovered a supermassive black hole (shown in the artist's impression above) at the centre of a distant quasar - an intensely powerful galactic radiation source

But scientists theorise that they are generated by matter heating up as it is dragged into supermassive black holes at the centre of distant galaxies.

The new object, named SDSS J0100+2802, is 12.8 billion light years from Earth and was formed 900 million years after the Big Bang, which gave birth to the universe.

Astronomers cannot explain how such an enormous black hole could have formed so soon after the first stars and galaxies emerged.

Dr Fuyan Bian, from the Australian National University, who was involved in the discovery, explained: ‘Forming such a large black hole so quickly is hard to interpret with current theories…

‘This black hole at the centre of the quasar gained enormous mass in a short period of time.’

The quasar, which is the brightest ever detected in the early universe, was found after astronomers conducted a survey of distant luminous objects using data from several large telescopes around the world. 

The new object, named SDSS J0100+2802, is 12.8 billion light years from Earth and was formed 900 million years after the Big Bang, which gave birth to the universe. An artist's interpretation of the Big Bang is shown

Nasa's Nuclear Spectroscopic Telescope Array (NuSTAR) and ESA's (European Space Agency) XMM-Newton telescope have spotted fierce winds blowing outwards in all directions from a supermassive black hole.

The phenomenon had been suspected, but now researchers have proved the winds are powerful enough to inhibit the host galaxy's ability to make new stars.

In the new study, astronomers determined PDS 456 - an extremely bright black hole known as a quasar more than 2 billion light-years away - sustains winds that carry more energy every second than is emitted by more than a trillion suns.

'Now we know quasar winds significantly contribute to mass loss in a galaxy, driving out its supply of gas, which is fuel for star formation,' said the study's lead author Emanuele Nardini of Keele University in England.

NuSTAR and XMM-Newton simultaneously observed PDS 456 on five separate occasions in 2013 and 2014.

It is stands out as a very distant and old object because it had a ‘redshift,’ which is a measurement of the stretching of light to the red end of the spectrum by the expansion of the universe, of 6.30.

Only 40 known quasars have a redshift higher than six, which is the yardstick used to define the early universe boundary.

SDSS J0100+2802 was formed soon after the end of the ‘epoch of reionisation,’ which created the star-filled universe we know today.

It was a transformative era that ended the ‘cosmic dark age’ following the Big Bang.

Astronomers have uncovered more than 200,000 quasars dating as far back as 700 million years after the Big Bang.

Despite their high luminosity they are extremely faint because of their great distance and difficult to find.

Professor Xue-Bing Wu, from Peking University in China, who led the study reported in the journal Nature, said: ‘This quasar is very unique.

‘We are so excited, when we found that there is such a luminous and massive quasar only 0.9 billion years after the Big Bang.

‘Just like the brightest lighthouse in the distant universe, its glowing light will help us to probe more about the early universe.’

US co-author Dr Yuri Beletsky, from the Carnegie Institution in Washington DC, said the quasar will act like a laboratory for scientists to study the way that a quasar’s black hole and host galaxy co-evolve.

‘Our findings indicate that in the early universe, quasar black holes probably grew faster than their host galaxies, although more research is needed to confirm this idea,’ he said. 

@highlight

Supermassive black hole is at the centre of a quasar - a powerful galactic radiation source - with a million billion times the sun’s energy output

@highlight

The object, named SDSS J0100+2802, is 12.8 billion light years from Earth

@highlight

It formed 900 million years after the Big Bang, when the universe began

@highlight

Astronomers cannot explain how the black hole could have formed so early