Television presenter Lorraine Kelly has called the police over diet pill adverts which use her before and after weight-loss images without her permission to promote the product.

The Scottish star, 55, has alerted police to the advertisements for raspberry ketone pills and tea, which feature photographs of her and fraudulently claim she used the products to lose weight.

It is claimed raspberry ketone capsules and herbal tea are used to quicken the metabolism, which results in weight loss.

Scottish television presenter Lorraine Kelly, 55, revealed she has called the police over diet pill adverts which are using her before and after weight-loss images (above) without her permission to promote the product

 The 55-year-old took to her Twitter page today to confirm she had informed the police of the advertisements

The mother of one took to her Twitter page today to warn fans that she did not give her permission for the weight-loss photographs to be used, nor did she endorse the products.

The morning television presenter told her 504,000 followers: 'I'm extremely angry that a bogus company is using my image to promote their weight loss "ketone" tea. It's being going on for months.

'I've informed the police. PLEASE do not fall for this! I lost weight by eating sensibly and doing 2 classes a week with @MaxZumbaQueen.'

Her spokesman added: ‘Lorraine is extremely angry that her name and image are being used in this way and that women are being duped into spending their money.

'She believes the only way to lose weight and keep it off is through exercise and eating healthily.’ 

It is believed the adverts have been generated by a bogus company to dupe people into parting with their credit card details. It is believed that the customers do not receive the pills once they have paid the money for the bogus product. 

They first appeared in June last year and Lorraine threatened to take legal action in January when they continued to appear online.

It was unclear tonight which police force in the country the television presenter reported the issue to. It is also unclear which company is behind the adverts. 

However, Gerard Cukier, a partner specialising in media law at Kingsley Napley, said he could understand why the television presenter had gone to police, if the advertisements were being produced by a bogus company.

Mr Cukier said: ‘If it is the case that it is a bogus company that is responsible for these advertisements, and some form of fraud has been committed, then one can understand why Miss Kelly has gone to the criminal authorities to seek to put a stop to these harmful activities.’  

He said that if the company was a legitimate trading firm then it could still face civil and criminal proceedings under English law.

He said: ‘On a civil side, the fact they have used her name to suggest she has endorsed their product - her name, image and reputation - that constitutes false endorsement and passing off which would entitle her to bring proceedings, to stop them using her name and image in this way, and for damages.

‘If Lorraine Kelly has a registered trademark in her name, then it is possible that a criminal offence may have been committed under the Trade Marks Act 1994, and if that is the case there are criminal penalties for unauthorised use of trademark under the act.' 

The television star said she was 'extremely angry' about the adverts and said she lost weight by eating well

Television presenter Fern Britton has previously been forced to deny using diet pills after being linked to a scam advertising campaign for a weight-loss supplement. She lost weight through gastric band surgery

The Advertising Standards Authority (ASA), which is responsible for making sure UK adverts are responsible and not misleading, said using a person's image in an advert without their permission was 'likely to be a problem under the advertising code'.

Regulations imposed by the ASA warn that companies using endorsements in advertising must 'hold documentary evidence that a testimonial or endorsement used in a marketing communication is genuine’.

With Kelly denying any involvement with ketone products, it appears the advertisements using her photographs have breached the code.

However, an ASA spokesman said that the issue 'appears to go beyond our role and remit.'

The spokesman said: 'We’re aware of several bogus operators, often based abroad and outside our jurisdiction, who peddle Ketone products.

'We regulate the advertising of legitimate UK companies, we’re not a statutory or law enforcement body.

'In this instance, it looks like a legal issue surrounding image rights/copyright and a problem best tackled through appropriate legal channels.'

The TV personality was also caught up in a similar situation last year when several companies selling raspberry ketone tablets stated that she, along with the Duchess of Cambridge, Victoria Beckham and Adele, had used their product to lose weight.

The companies all issued their adverts through Facebook.

Images of the Duchess of Cambridge, Kate Middleton, have been used by  the so-called Raspberry Ketone diet

Popstar Adele (left) and Victoria Beckham (right) have both previously had images used in scam advert

At the time, the Advertising Standards Authority (ASA) said that the adverts were misleading and upheld complaints which had been made.

The adverts were subsequently banned from appearing on the internet.

Television presenter Fern Britton was also forced to deny using diet pills after being linked to a scam advertising campaign for a weight-loss supplement.

The 56-year-old rubbished the claims via Twitter saying she had never used raspberry ketone capsules, and warned: It's a scam! Not me!'

The adverts featuring the TV star included the words: 'Fern proves critics wrong. Drops 22st without cheating – no weird exercise or ugly diets!'

It also featured a photograph of her face, despite the former This Morning presenter having not given her consent to be linked with the product.

People who attempted to purchase the pills became locked into costly monthly contracts that they struggled to get out of after handing over their bank details or end up paying for goods that do not arrive.

@highlight

TV star has called police over adverts using her images without permission

@highlight

Advert for Raspberry Ketone pills features her before and after weight-loss

@highlight

They claim she took the product to help her lose weight - but she denies it

@highlight

Presenter said she was 'extremely angry' and lost weight by healthy eating