Microsoft pays no tax on £1.7billion of online sales in the UK thanks to a legal loophole, it has been reported.

The technology monolith is funnelling cash generated by online sales of Windows 8 software to Luxembourg to sidestep tax obligations, according to The Sunday Times.

If the allegations are true the company will join a growing number of foreign companies coming under scrutiny for avoiding UK tax, such as Amazon, Apple and Google. Earlier this week coffee chain Starbucks caved to public fury and announced it would pay Her Majesty’s Revenue and Customs to pay £20million over the next two years.

Microsoft founder and chairman Bill Gates at the company's annual meeting of shareholders last month. The company allegedly uses a base in Luxembourg to avoid paying tax on its UK sales

Money trail: How Microsoft channels its money to avoid paying corporation tax in the UK

The Sunday newspaper's investigation led it to an office in Luxembourg where a small number of staff handle sales from throughout Europe and transfer the money to the company's European HQ in Ireland, where it is then routed to Bermuda.

The legal process allows Microsoft to bypass UK corporation tax on sales of £1.7billion.

Luxembourg's favourable tax laws have enticed a number of companies to set up headquarters there, including Amazon, Skype, Facebook, eBay, AOL and Apple.

In 2011 Microsoft's UK operation paid £19million in corporation tax, 2.8 per cent of revenue totalling £663 million. UK corporation tax currently stands at 24 per cent.

Microsoft is avoiding tax on UK sales of its Windows 8 operating software, according to reports

Microsoft has its main European headquarters in Ireland, where the corporation tax rate is roughly half of that.

Richard Murphy, of the Tax Justice Network, a global tax watchdog and thinktank, said: 'Like many other companies, Microsoft is trying to avoid tax.

'It has tried hard to represent itself as doing the best thing for the world, but if you really want to solve the world's problems, pay taxes.

'£159million would more than pay for a hospital, or provide IT training for young people so they can work in that industry.

'They are withholding money from the people who need it.'

A spokesman from Microsoft said: 'Microsoft pays all due taxes, as required by law, worldwide. Microsoft subsidiaries are fully subject to tax in the jurisdictions in which we operate.

'We are regularly audited by major tax jurisdictions, which ensure the company is complying with all rules and regulations.'

Tax haven: A number of major international companies have set up in Luxembourg because of favourable tax laws

The Sunday Times also reported that the Luxembourg office of international law firm Dechert, where Nick Clegg's wofe Miriam Gonzalez is a partner, lent £17m to the London office.

The loan interest paid allowed the partners to claim tax relief back. The company said the money was for a refurbishment, not tax avoidance.

A BT subsidiary based in Luxembourg which made a profit of £136m paid less than 0.5 per cent tax, according to the paper. BT responded that it derives no tax benefit from the arrangement.

Rage: There is growing public anger over foreign companies using tax law to avoid UK corporation tax. Yesterday saw protests at Starbucks in Liverpool

Protestor holding sign outside Starbucks. A number of organisations targeted branches of Starbucks in Liverpool

A masked protestor with sign saying 'Starbucks Pay Your Tax'. Demonstrators went to two branches of the coffee shop, occupying one and closing another

@highlight

Microsoft avoids UK corporation tax on £1.7billion a year in UK revenue

@highlight

Along with other major companies, uses Luxembourg office to legally dodge tax

@highlight

Tech giant claims it 'fulfills all tax obligations'

@highlight

Tax activist blast the company as 'withholding money from the people who need it'