An immediate rise in holiday bookings to Scotland has been recorded following the country's vote to remain part of the United Kingdom.

Travel comparison and booking site GoEuro has revealed 4 per cent increase on Friday in bookings from England to Scotland following the 55 per cent to 45 per cent referendum vote against independence. 

With tourists from England shunning Scotland in the lead-up to the vote - Trivago.co.uk recorded a 29 per cent year-on-year drop in interest from the rest of the UK - it appears Scotland's Great British brothers and sisters are quick to forgive and forget.

Scroll down for video 

Back in demand: Scotland's most popular paid entry tourist attraction, Edinburgh Castle

Votes are in: After the 55 per cent to 45 per cent referendum vote in favour of pro-union campaigners (pictured), bookings to Scotland have risen immediately

The English were not alone in their keenness to reaffirm  ties with the Scots, with a 2.5 per cent increase in bookings via GoEuro overnight from Ireland. 

Nations with strong independence movements of their own, France and Spain, had revealed in a survey leading up to the vote that a yes decision would make Scotland a more attractive destination to them. 

However after the no vote the immediate response from the countries has been positive with bookings from Spain rising by 2 per cent and a 3.3 per cent boost from France.

Germany, Netherlands and Belgium's interest in the country has remained stable. 

Boost: An immediate rise in bookings to Scotland has come with news of a no vote for independence

The most remarkable rise in interest has come from the United States, with their jump of 4.8 per cent for bookings to Scotland indicating many were awaiting the result of the referendum before booking their next break abroad. 

On Thursday, as Scotland went to the polls, some tourism operators said the uncertainty surrounding Scotland's future was unsettling English tourists who were cancelling holidays across the border in their droves.

But since the polls of Scotland's 32 council areas recorded a result of 2,001,926 no votes to  1,617,989 yes votes, the country could be set for a tourism boom.  

Split: Industry experts expressed concern over the affect of independence would have on Scottish travel

'Earlier this week, we polled thousands of GoEuro users across Europe, and the majority responded saying that an independent Scotland would be a less appealing holiday destination,' said GoEuro's Country Manager Pablo Martinez. 

'The referendum result seems to confirm that a united Scotland could well be looking forward to more tourists than ever before. 

'This morning's bookings through GoEuro suggest that a "no" vote, coupled with the exposure Scotland has had in the media over recent weeks, has increased number of bookings overnight, especially those from England, France and the US.' 

Scotland will be in the headlines again for less political reasons next week with the The Ryder Cup golf tournament taking place at Gleneagles in Perthshire between Europe and the United States, another possible catalyst for the surge in American bookings.  

Back in the spotlight: Gleneagles resort in Perthshire will host the Ryder Cup golf tournament next week

A statement from UK travel association ABTA after the vote was finalised soon after 6am on Friday welcomed the stability that came with the no vote but said there were still issues to be ironed out between the industry and the British government.

'Today's No vote brings to a close a protracted period of uncertainty, and means that travel companies and their customers can continue with the current regulatory and business systems,' ABTA said in a statement.  

'Some of the travel issues raised during the independence debate, such as Air Passenger Duty and consumer protection, remain live issues, and ABTA will continue to engage with these on behalf of its Members in Scotland and the rest of the United Kingdom.' 

 

 

 

 

@highlight

Bookings from England to Scotland have risen after the independence vote

@highlight

GoEuro reported an immediate boost to bookings  post-referendum 

@highlight

Surveys said English tourists had lost interest in Scotland over the vote

@highlight

GoEuro says Scotland could benefit publicity generated by the referendum

@highlight

Perthshire's Gleneagles hosts the 2014 Ryder Cup from next week