By 
Sam Shead

PUBLISHED:

05:18 EST, 14 August 2012


| 

UPDATED:

06:05 EST, 14 August 2012

Stanford University scientists have developed a self-driving robotic race car that can hit 120mph on the test track.

The white Audi TTS was put through its paces on the Thunderhill Raceway, north of Sacramento, California.

The autonomous car raced round the three mile course in two and a half minutes, a time that rivals those posted by professional drivers.

The affectionately named Shelley is the 
result of a collaboration between Stanford's Dynamic Design Lab, led by 
mechanical engineering design graduate Chris Gerdes, and the Volkswagen 
Electronics Research Lab.

Scroll down for video

Shelley was named after Michele Mouton, the first woman to win the race up Pikes Peak in the Rocky Mountains

The team hopes to use the same technology that helps Shelley navigate around corners to develop collision avoidance systems for normal cars

Shelley navigates the course with the help of an assortment of algorithms.

The
software that tells Shelley when to brake, how tight to turn, and when 
to push the pedal to the metal, was tested by Gerdes at Thunderhill. 

The researchers claim the route Shelley takes is nearly the same as the one a professional racing driver would take.

The Audi TTS is kitted out with antennas and sensors to help it navigate around the track

However, despite the autonomous car's sophisticated technology, it still can't quite compete with human-driven equivalents.

'Human drivers are very, very smooth,' said Gerdes.

Shelley computes the fastest line around a course and executes the exact corrections required to stick to it.

A
person relies more on feel and intuition, and thus may, for example, 
allow the car to swing too wide in one turn if he knows it sets him up 
better for the next.

'Human drivers are ok with the car operating in a comfortable range of states,' said Gerdes. 'We're trying to capture some of that spirit.'

Gerdes
and his students will have the opportunity to do just that this weekend
at the Rolex Monterey Motorsports Reunion races at the Laguna Seca 
Raceway.

The group has enlisted two professional drivers to wear a suite of biological sensors as they race around the track.

Graduate research team leader Chris Gerdes shows off the systems carried onboard the autonomous car, a modified Audi TTS

The sensors will record variables such as the driver's body temperature and heart rate.

Scalp
electrodes will be used to register the driver's brain activity as they
race against other humans to determine which driving maneuvers require 
the most concentration and brainpower.

The
biological data will be paired with mechanical performance data from 
the car – a 1966 Ford GT40, the only American-built automobile to finish
first overall at the 24 Hours of Le Mans race – which Stanford has 
kitted out with feedback sensors similar to those on Shelley.

'We need to know what the best drivers do that makes them so successful,' said Gerdes. 'If we can pair that with the vehicle dynamics data, we can better use the car's capabilities.'

The team believes that the experience and the data they have gained can be used to develop autonomous vehicles for use on public roads.

In the nearer term, the technology could be used as an onboard co-pilot that helps the driver steer out of a dangerous situation.

The reality of racing a car round a track and pushing that vehicle to its absolute limit means that it will be subjected to exceptionally high levels of stress.

The recent tests left poor Shelley without any brake pads due to the intense heat generated by friction between the tyres and the pads themselves.

Pushing a car to the limit on the racetrack is one of the best ways to find out what type of stress that car is under in a crisis.

'If we can figure out how to get Shelley out of trouble on a race track, we can get out of trouble on ice,' said Gerdes.

@highlight

Driverless Audi TTS hit speeds of 120mph, rivalling professional drivers

@highlight

Relies on a series of algorithms to brake, corner and accelerate

@highlight

Technology could be used to help drivers avoid car crashes