By 
Victoria Bischoff

PUBLISHED:

20:36 EST, 25 December 2012


| 

UPDATED:

06:00 EST, 26 December 2012

You never think it could happen to you — but fraudsters scam trusting investors out of more than £1.2billion every year.

From cold-calling chancers flogging non-existent shares to smooth-talking salesmen convincing you to plough thousands of pounds into dodgy property schemes, criminals never miss an opportunity to tap into an age-old instinct — the desire to get rich quickly.

The financial losses to individuals can be huge — anywhere between £10,000 to as much as £1 million, according to Action Fraud, the national fraud and internet crime centre.

Fraudsters scam trusting investors out of more than £1.2 billion every year. One of the tricks involves cold-calling chancers flogging non-existent shares (file photo)

Often the scams start small, asking for as little as £500 of your cash just to ‘see how it goes’.

Then, after fictitious updates suggesting explosive profits and huge gains, duped investors hand over even greater sums.

Only when promised returns fail to materialise does the penny drop.

The personal impact of fraud can hit victims even harder than the financial blow. Many are too embarrassed to tell anyone, and suffer stress from worrying about the fallout.

It’s estimated that nine in ten cases go unreported, according to the City regulator, the Financial Services Authority (FSA).

But the heartbreak and financial headaches can be avoided.

Never give out any personal information — especially not your bank details — to any individual or company over the phone before you’ve checked their credentials.

After fictitious updates suggesting explosive profits and huge gains, duped investors hand over greater sums. Only when promised returns fail to materialise does the penny drop (file photo)

Be especially wary of post, phone calls or emails offering you business deals out of the blue.

If an offer seems too good to be true, it probably is. Always question it.

You can report a scam and get advice about protecting yourself by calling Action Fraud, the national crime centre backed by the Government on 0300 123 2040.

To help alert you, here are three of the biggest investment frauds:

PLOTS OF LAND YOU CAN NEVER SELL ON

An increasingly common scam is run by conmen who buy a huge plot of land and slice it up into smaller plots, which they sell on to individual investors.

The idea is that investors are snapping up wonderful real estate that will increase in value and be sold at a substantial profit.

Investors are convinced to buy without even seeing the plot or conducting a survey.

But in reality the plots generally can’t be built on — instead, they might be sites of historic or natural interest or, in one example, include a 45-degree slope with no access.

In some cases, the land does not even exist.

The FSA estimates investors have lost £200 million to these so-called ‘land-banking’ scams.

Angela Crossley, head of investigations at the Insolvency Service, says: ‘Companies deliberately mislead the public and ruin the lives of honest people.

‘Our investigators are tracking down these con artists and stopping them from trading, but new firms pop up immediately offering the same false investment opportunities.’

CARBON CREDITS THAT ARE JUST THIN AIR

One of the latest cons is run by dodgy salesmen who promise huge returns from investing in green schemes, known as carbon credits.

The idea is that ordinary investors will be able to profit from companies that have to be more environmentally friendly to keep down pollution.

These types of firms need to buy carbon credits — essentially certificates giving them permission to pump one ton of carbon dioxide into the atmosphere.

Because all companies have targets for the amount of carbon dioxide they are allowed to emit, the big polluters need to buy carbon credits to offset the extra they create.

The carbon credit certificates are generated by companies that use less than their allowance  or are particularly environmentally friendly.

Potential investors are lured by reports that trading carbon credits may become increasingly profitable in future years.

As more companies will need to offset the pollution they cause,  so the value of the carbon credits will go up.

But carbon credit schemes are essentially buying nothing but thin air — there is nothing tangible to invest in.

Though there are plenty of legitimate companies offering access to such schemes, many others are fraudulent and trying their luck with cold calls — and promises of windfalls.

The FSA is worried about the promise of returns and is sceptical that anyone has ever made money.

Jonathan Phelan, head of unauthorised business at the FSA, says: ‘We have yet to see any convincing evidence to indicate that investors can make money from investing in carbon credits.’  

So far, the regulator has launched 77 inquiries into carbon credit firms and recently added a further 13 to its warning list.

BOILER ROOMS THAT SELL FAKE SHARES

Despite continued crackdowns, huge numbers of investors still lose money to so-called boiler room scams.

With these, a person is called at home by a salesman and persuaded to buy shares in a company.

They are told that the firm, which is often based overseas and has a professional-sounding name, is about to make huge profits.

This could be because they are about to list on a stock exchange, be bought out by a bigger company or, in the case of engineering firms, have just discovered oil or another mineral deposit somewhere around the globe.

The fake stockbroker — who is usually calling from another country — then pressures you into making a quick decision to avoid missing out on the deal.

But, in reality, what you are  buying are shares in small firms which are difficult to sell or sometimes don’t even exist.

The returns never appear and once you start to ask questions, the brokers will suddenly stop returning your calls.

Mike and Susan Denny, pictured, were nearly duped by a pushy cold-caller representing a carbon credit firm

Retiree Mike Denny had a narrow 
escape when he nearly handed over £2,500 of his hard-earned cash to a 
pushy cold-caller representing a carbon credit firm.

Mr Denny (pictured with his wife Susan) was shocked at how much the salesman, called Oliver, seemed to know about him.

‘I have no idea how he got hold of my 
number and details. He knew I had enough money to invest and that I had 
solar panels on my roof so was obviously interested in green issues.’

‘Oliver’ told Mr Denny that if he sent
a cheque for £2,500 he could ‘get in on the ground floor of an exciting
investment’ and earn back eight times that in just two years.

Oliver said the money would buy him 
carbon credits that other companies would need in the future to offset 
their carbon footprint. There would even be an opportunity to invest 
more down the line.

Mr Denny, who lives in Manchester, said the exaggerated return was a red flag for him.

But after he said he wasn’t interested, Oliver still called back and even tried to go through Mrs Denny, a retired NHS worker.

@highlight

Fraudsters scam trusting investors out of more than £1.2billion every year

@highlight

Personal impact of fraud can hit victims harder than the financial blow

@highlight

Estimated nine in ten cases go unreported according to City regulator