Wind farms will never be able to ensure the nation’s lights stay on because they are ‘expensive and deeply inefficient’, it is claimed today.

Confirming the long-held fears of many critics, a new study published by the right-leaning Adam Smith Institute and the Scientific Alliance argues the green energy revolution has been an expensive folly.

Researchers found that, on average, wind farms produce 80 per cent of their potential power output for less than one week annually – and they manage 90 per cent output for only 17 hours a year.

Ineffective: Thousands of turbines are useless in low winds and they are turned off to prevent damage if the speeds are too high. Above, file image of Carno wind farm, Wales

Thousands of turbines are useless in low winds and they are turned off to prevent damage if the speeds are too high.

Families and businesses have paid billions of pounds to subsidise the building of wind farms, both on-shore and off-shore, through their energy bills, sending tariffs soaring.

The schemes are key to the Government’s promise to switch to green energy, reducing the nation’s carbon emissions in line with British and EU targets to tackle man-made global warming. 

The study, entitled Wind Power Reassessed: A review of the UK wind resource for electricity generation, recommends pushing ahead with nuclear power and gas-fired power stations. 

Ben Southwood, Head of Policy at the Adam Smith Institute, said: ‘Wind farms are a bad way of reducing emissions and a bad way of producing power.

‘They are expensive and deeply inefficient and it seems like they reduce the value of housing enormously in nearby areas.

Promise: The Conservatives have already pledged to end subsidies for new wind farms as Britain is set to meet EU targets, which decree that 15 per cent of energy is generated by renewable sources by 2020. (File image)

Defending turbines, trade body RenewableUK claimed: ‘Wind power has been quietly powering millions of homes and providing a robust response to detractors.’

The Conservative party has already pledged to end subsidies for new wind farms as Britain is set to meet EU targets.

The EU Renewable Energy Target decrees that 15 per cent of all energy in the UK - or 30 to 35 per cent of electricity - is generated by renewable sources by 2020.     

The Department for Energy and Climate Change said the country needs a wide mix of energy sources. It said: ‘We're preventing a predicted energy crunch by turning round a legacy of underinvestment and neglect.

‘To deliver this, we need a diverse energy mix that includes renewable sources like wind and solar alongside nuclear and technologies like carbon capture and storage so we can continue to use fossil fuels in a cleaner way.’ 

 

@highlight

Wind farms produce 90% of potential power output for only 17 hours a year 

@highlight

Families and businesses have paid billions  to subsidise building of turbines

@highlight

Tories have pledged to end subsidies as Britain is set to meet EU targets 