By 
Margot Peppers

PUBLISHED:

15:54 EST, 19 September 2013


| 

UPDATED:

12:54 EST, 20 September 2013

Playboy's annual party college list was spoofed by a group of activists on Tuesday, who created a fake website highlighting the importance of practicing consensual sex.

PartyWithPlayboy.com featured a list of the 'Top Ten Party Commandments' on how to have a 'consensual good time', parodying the magazine's annual list of the Top Ten Party Colleges.

While many believed the magazine run by Hugh Hefner was responsible for the site, it was actually a hoax launched by anti-rape group FORCE, with the aim of opening up a dialogue about the prevalence of sexual assault on college campuses.

Copycat: Playboy's annual party college list was spoofed by a group of activists on Tuesday, who created a hoax website highlighting the importance of practicing consensual sex

Updated list: The hoax site featured a list of the 'Top Ten Party Commandments' on how to have a 'consensual good time', parodying the magazine's annual list of the Top Ten Party Colleges

Playboy's annual party school list examines the colleges with reputations for partying cultures and the most drug and alcohol use.

In reaction against partying culture which leads to sexual assault, FORCE - along with students from 25 colleges across the country - created a parody website that looked exactly like the Playboy one, with a focus on the issue of rape culture.

'Over the years, it has been brought to our attention that some of our long-standing party picks have a not-so-toast-worthy, rape-ridden side to their campus life,' read the fake website.

'Rape is kryptonite to sexual 
pleasure. The two cannot co-exist. For our revised party guide to live 
up to our founder’s vision, we had to put a new criterion on top. 
Namely, consent.'

'Our culture needs influential leaders like Playboy  to step up and change the conversation'

Responses to the 'updated' list were 
overwhelmingly positive, with the website going viral within hours and 
news sites praising Playboy for their 'progressive' new stance.

One of the 'commandments' listed on the fake website read: 'Ask first. . . consent is not just sexy.
It's necessary.'

Another said: '[Don't] take advantage of sloshed persons. . . 
because drunk does not equal consent.'

Party rules to live by: One of the 'commandments for a consensual good time' listed on the fake website reads: 'Ask first. . . consent is not just sexy. It's necessary'

Sparking a conversation: According to a release from FORCE - the activist group behind the hoax - the fake websites received over 3,000 hits an hour on Tuesday

Serious problem: 'With one in four female undergrads being assaulted while they are in school, obtaining a bachelor's degree in this country comes with an untenable high level of violence,' says the e-mail release

Along with the fake Playboy website, the activists also posted fake news
stories about it on Huffington Post and BroBible.com, with students who
were involved linking to it via Twitter and Facebook.

And they evidently achieved their goal of sparking up an important conversation about consent.

According to a release from FORCE, each
of the hoax websites received over 3,000 hits an hour on Tuesday, and the fake Huffington 
Post site garnered more than 5,000 Facebook likes.

'With one in four female undergrads being assaulted while they are in 
school, obtaining a bachelor's degree in this country comes with an 
untenable high level of violence,' says the e-mail release.

Spreading the word: 'One reason we used Playboy is that it's important for these messages to come from men and not just women,' said FORCE co-founder Rebecca Nagle (pictured: Playboy owner Hugh Hefner)

'All college students, male, female and gender queer, deserve better.'

While
writers at BroBible wrote that they 'agree with the overall messaging' 
that the hoax promoted, Playboy has asked that the website be taken 
down.

'The politics of Playboy and women’s bodies is really complicated and something that we thought about a lot,' FORCE co-founder Rebecca Nagle told MailOnline.

'One reason we used Playboy as a platform is that I think it's important for these messages to come from men and not just women.'

Responsibility: Katya Palsi, a student who helped with the hoax, said in a release: 'Our culture needs influential leaders, like Playboy and other enterprises, to step up and change the conversation'

Rebecca also explained that the fact so many readers believed the Playboy website was real means that the company has the capability - and the responsibility - to promote such a message.

Indeed, Katya
Palsi, a student at Rowan University who helped with the hoax, said in a release: 'Our culture needs influential leaders, like Playboy 
and other enterprises, to step up and change the conversation.

'The excitement generated by this just shows how ready we are as a society for a cultural shift.'

@highlight

Playboy magazine publishes an annual list of the best 'party colleges'

@highlight

On Tuesday, anti-rape activist group FORCE created a parody website that turned the yearly ranking into a platform for promoting the importance of sexual consent