By 
Helen Pow

PUBLISHED:

17:56 EST, 17 October 2013


| 

UPDATED:

18:40 EST, 17 October 2013

Lawsuit: Minneapolis priest Michael Keating, pictured, is being sued for allegedly sexually abusing a girl for three years a decade and a half ago

A Minneapolis priest sent at least 19 'seductive' emails confessing his love to a teenage girl who he was allegedly sexually abusing for a period of three years a decade-and-a-half ago.

The victim, who was 13 when the alleged abuse started and is in her late 20s now, filed a lawsuit against Reverend Michael Jerome Keating Monday claiming 'dealing with what he did to me is an hourly battle.'

She alleges he fondled her breasts, made her lie on top of him while he was aroused, woke her in the middle of the night to ask for a back rub and french kissed her.

In the deeply personal emails, made 
public today by the girl's lawyer, Keating expressed love and affection for 
the girl, regularly signing off 'love you lots and lots' and warning her
that she will be popular with the boys because she was 'pretty and 
charming.'

Keating, then-44 and 30 years the girl's senior, was attending St Paul Seminary at the time, studying to be a priest. He is now an associate professor in Catholic studies at the University of St. Thomas.

According to her suit, Keating 'engaged in multiple instances of unpermitted, harmful and offensive sexual contact with the girl from 1997 to 2000.

She said Keating repeatedly told her he loved her and she believed she loved him.

In 2004 she said confronted him about the alleged abuse.

'He twisted things so much that by the end, I was apologizing to him,' she told the TwinCities.com.

'(He said) "you're just an angry girl, and everything I've ever done has been out of love,"' she said.

She said the abuse drove her to attempt suicide twice.

'The pain of the abuse didn't stop,' she said. 'What he did to me was so internally damaging that I forgot who I was.'

Keating was ordained in 2002 and served as a priest at St. John the Baptist church in New Brighton from 2003 to 2005, the lawsuit states.

In 2006, the woman, then 21, detailed the alleged abuse, and showed the personal emails, to archdiocese officials but the church found there was insufficient evidence to support a finding of sexual abuse of a minor.

The board 'does not believe that the priest's faculties should be suspended, given his effectiveness in many areas of his work,' a summary provided to the family in 2007 stated. A concurrent police investigation was also abandoned.

She described the decision as devastating.

Thrown out: In 2006, the woman, then 21, detailed the alleged abuse, and showed the personal emails, to archdiocese officials but the church found there was insufficient evidence to support a finding of sexual abuse of a minor

The woman said she decided to file her suit against Keating this week after allegations involving another priest at the Twin Cities archdiocese and claims that the church had failed to report sexual misconduct.

She said she felt a tremendous relief since opening up about the abuse.

She said: 'I feel free. I'm not scared. I feel proud of myself. I feel excited for what it means not just for me but for other kids.'

On the weekend, Keating announced that he was taking a leave from the archdiocese. He is however, still scheduled for classes at St Thomas, according tot he University's website.

Neither commented on the case to TwinCities.com and Keating did not return a call made to his home on Monday.

In a statement to the Star Tribune, Keating's attorney Fred Bruno on Thursday said the woman's claims 'were thoroughly discredited over six years ago.'

He said at the time Father Keating passed a polygraph administered by Minnesota's 'most experienced and highly regarded law enforcement polygrapher.'

'The unfortunate grandstanding and publicity generated by the recent announcement of this lawsuit add nothing to the credibility of the claims,' he said. 'Such self-serving tactics do not promote genuine justice, and are needlessly hurtful to an esteemed member of the Catholic community and to the Church as a whole.'

In a statement from the girl on Thursday, she said she had given her attorney Jeff Anderson permission to release a video testimony recorded when she came forward about the abuse in 2006.

She said in the statement: 'I want the truth to be known. I want it to be understood that when the abuse started I was barely 13. I want people to know that I came to the Archdiocese with everything I had, with my whole and honest story and I feel like I begged them to hear me. The abuse itself and the way this has all been handled makes me so sad. It breaks my heart.'

@highlight

The victim, who was 13 when the alleged abuse started and is in her late 20s now, filed a lawsuit against Twin Cities, Minnesota Reverend Michael Jerome Keating Monday

@highlight

She claims 'dealing with what he did to (her was) an hourly battle'

@highlight

Keating, then-44, was attending St Paul Seminary at the time, studying to be a priest

@highlight

He is now an associate professor in Catholic studies at the University of St. Thomas

@highlight

The woman reported the abuse to the archdiocese in 2006 but they claimed the allegations were unfounded

@highlight

He sent scores of deeply personal emails to the young girl