The heirs of late 
author J.R.R. Tolkien are suing the producers of 'The Lord of the Rings'
 and 'The Hobbit' movie trilogies over alleged exploitative 
merchandizing.

The lawsuit, filed Monday in 
U.S. District Court in Los Angeles, comes a week before the premiere of 
the 'The Hobbit: An Unexpected Journey' in Wellington, New Zealand.

The first film in
 the trilogy hits theaters worldwide next month.

Sued: The heirs of late author J.R.R. Tolkien are suing the producers of 'The Lord of the Rings' and 'The Hobbit' movie trilogies over alleged exploitative merchandizing

The
 estate of Tolkien is upset at what it calls 'morally questionable' 
digital marketing including an online slot machine, according to a copy 
of the lawsuit obtained by The Hollywood Reporter.

The Tolkien estate is
 seeking $80million from Warner Bros., its New Line subsidiary and 
rights holder Saul Zaentz Co.

Warner Bros. declined to comment on the claims.

Money: The Tolkien estate is seeking $80 million from Warner Bros., its New Line subsidiary and producer Saul Zaentz (pictured)

Tolkien's
 family contends a merchandizing agreement extends only to tangible 
products such as figurines and clothing and not to electronic rights.

'Not
 only does the production of gambling games patently exceed the scope of
 defendants' rights, but this infringing conduct has outraged Tolkien's 
devoted fan base, causing irreparable harm to Tolkien's legacy and 
reputation and the valuable goodwill generated by his works,' the family
 claims in the lawsuit.

The family says 
lengthy discussions with the producers over the disagreement proved 
fruitless and that it fears the scope of online merchandizing will only 
increase with the release of the `Hobbit' movies.

Tolkien's
 heirs settled a lawsuit over the 'Lord of the Rings' movies for an 
undisclosed amount in 2009, allowing production to proceed on 'The 
Hobbit.'

That lawsuit against New Line Cinema 
claimed Tolkien's trust received only an upfront payment of $62,500 for 
the three movies before production began but was due 7.5 per cent of the 
gross receipts.

The 'Rings' films earned an estimated $6 billion from 
movie tickets, DVDs and merchandise.

Rough Week: The producers of 'The Hobbit' have came under fire Monday from wranglers after 27 animals used on set during the filming of the trilogy have died

It's been a rough week for Warner Brothers and the 'Lord of the Rings' franchise.

The producers of 'The Hobbit' have came under fire Monday from wranglers after 27 animals used on set during the filming of the trilogy have died.

While no animals were harmed during the actual filming, wranglers claim the production company is still responsible for the deaths because the animals were kept at a nearby farm filled with bluffs, sinkholes and other 'death traps.'

Four wranglers working with the animals claim they repeatedly raised concerns about the farm peppered with bluffs, sinkholes and broken-down fencing with their superiors and the production company, owned by Warner Bros., but it continued to be used.

Tolkien: The lawsuit against New Line Cinema claimed Tolkien's trust received only an upfront payment of $62,500 for the three movies. The "Rings" films, based on the works of  J.R.R. Tolkien, pictured,  earned an estimated $6 billion

The
 producers of The Hobbit have come under fire from wranglers after 27 
animals used on set during the filming of the trilogy have died.

While
 no animals were harmed during the actual filming, wranglers claim the 
production company is still responsible for the deaths because the 
animals were kept at a nearby farm filled with bluffs, sinkholes and 
other 'death traps'.

Four
 wranglers working with the animals claim they repeatedly raised 
concerns about the farm peppered with bluffs, sinkholes and broken-down 
fencing with their superiors and the production company, owned by Warner
 Bros., but it continued to be used.

The
 producers of The Hobbit have come under fire from wranglers after 27 
animals used on set during the filming of the trilogy have died.

While
 no animals were harmed during the actual filming, wranglers claim the 
production company is still responsible for the deaths because the 
animals were kept at a nearby farm filled with bluffs, sinkholes and 
other 'death traps'.

Four
 wranglers working with the animals claim they repeatedly raised 
concerns about the farm peppered with bluffs, sinkholes and broken-down 
fencing with their superiors and the production company, owned by Warner
 Bros., but it continued to be used.

The
 producers of The Hobbit have come under fire from wranglers after 27 
animals used on set during the filming of the trilogy have died.

While
 no animals were harmed during the actual filming, wranglers claim the 
production company is still responsible for the deaths because the 
animals were kept at a nearby farm filled with bluffs, sinkholes and 
other 'death traps'.

Four
 wranglers working with the animals claim they repeatedly raised 
concerns about the farm peppered with bluffs, sinkholes and broken-down 
fencing with their superiors and the production company, owned by Warner
 Bros., but it continued to be used.

The
 producers of The Hobbit have come under fire from wranglers after 27 
animals used on set during the filming of the trilogy have died.

While
 no animals were harmed during the actual filming, wranglers claim the 
production company is still responsible for the deaths because the 
animals were kept at a nearby farm filled with bluffs, sinkholes and 
other 'death traps'.

Four
 wranglers working with the animals claim they repeatedly raised 
concerns about the farm peppered with bluffs, sinkholes and broken-down 
fencing with their superiors and the production company, owned by Warner
 Bros., but it continued to be used.

@highlight

Heirs of Lord of the Rings creator suing over exploitative merchandizing

@highlight

Lawsuit comes one month before The Hobbit: An Unexpected Journey premieres