By
Victoria Woollaston

A new computer program is scanning satellite images from Google Earth looking for faces hidden in the world's landscape.

Google Faces has been developed by German design studio Onformative and uses an algorithm that can highlight land masses and terrains with face-like features.

The system scans the world, switches to the next zoom level, and starts the scan again taking snapshots and coordinates of the faces it finds.

Scroll down to video

This face was found in the Magadan Oblast region of Russia, in the Far Eastern Federal District of the country. This part of the world is mainly made up of mountainous desert, tundra, and forests

This image is one of the faces found in the UK. It was taken next to Priory Road in Ashford in Kent and could be either a human face in profile, or the face of an animal. Trees appear to form the face's mouth and nostrils

In 1976 Nasa sent two spacecraft called Viking 1 and Viking 2 to the Cydonia region of Mars.

Both spacecraft took images of the planet's surface and beamed them back to Nasa scientists on Earth.

One image, taken on 25 July 1976 by Viking 1, showed what appeared to be a face in the rocks.

This 'Face on Mars' image was taken about half-way between the Arandas Crater and Bamberg Crater in Cydonia.

When the image was seen by Viking chief scientist Gerry 
Soffen, he dismissed it as a 'trick of 
light and shadow'.

But another image taken at a different angle also appeared to show a face in the planet's surface, and was found by Vincent DiPietro and 
Gregory Molenaar, two computer engineers at NASA's Goddard Space Flight 
Center.

A total of 18 images of the Cydonia region were taken by the Viking orbiters.

The entire scan is expected to take several months because each time the scanner zooms in, the amount of time it takes to scan the images and travel the globe increases.

Onformative founders Julia Laub and Cedric Kiefer from Berlin used openFrameworks - an open-source creative coding program - to develop the algorithm. 

In a blog about the project, the founders explained that they developed the idea for the Facetracker because they wanted to explore 'how the psychological phenomenon of Pareidolia could be generated by a machine.'

Pareidolia is the tendency to see faces in clouds or inanimate objects, or hear hidden messages when songs are played backwards, for example.

Human eyes can spot faces within their environment and it helps them recognise friends in a crowd, work out how fast a car is travelling, and see patterns.

Onformative claims that we also tend to use this ability to 'enrich our imagination' and 'recognise meaningful shapes in clouds or detect a great bear upon astrological observations.'

Another image captured by the Google Faces project in Russia. This grumpy-looking face was found in the Jewish Autonomous Oblast, in the Russian Far East - an area also known as Yevrey. Soviet leaders created the autonomous oblast in 1934 as a result of Joseph Stalin's nationality policy to give the Jewish population an area in which to practice Yiddish culture

This frowning face with large teeth was found in the Sakha, or Yakutia Republic, of Russia. Sakha makes up half of the Far Eastern Federal District of the country and is the largest subnational governing body by area in the world

To see if a machine could detect this 
phenomenon, Laub and Kiefer wrote a computer algorithm that mimics the 
way human eyes work and our tendency to distinguish faces.

They were inspired by the Face on 
Mars image taken by the Viking 1 Orbiter - one of two spacecraft 
sent to Mars by Nasa in July 1976. 

Laub
 and Kiefer said: 'Our Facetracker already circumnavigated the world a 
couple of times and astonished us with quite versatile results.

'As it continues to travel the world within the upcoming months, it continuously zooms into the Earth.

'Some
 of the detected images aren’t usable at all, as we are not able to 
recognize any face-like patterns within the detected images.

The Onformative Facetracker also discovered this image in the Magadan Oblast region of Russia. The face detector uses a computer algorithm that attempts to mimic how human eyes work, in particular their ability to see faces in clouds and inanimate objects. This psychological phenomenon is called Pareidolia

Onformative's Google Facetracker mainly found images in natural landscapes; fields, mountains and rocky terrains. However, some faces were also detected in industrial and urban regions. The face in this image is seen in the centre of the screen. A green hairdo is shown above two 'eyes' that have trees for eyebrows. It then has a wide open mouth below

'Other satellite images, on the other hand, inspired our imagination in a tremendous, yet funny way.

'However the search goes on, as our diligent robot continuous investigation.'

The team use the face detection algorithm on top of different satellite images and stores the geographical coordinates.

They
 then use software to send these coordinates from the Facetracker to a virtual browser scanning Google Earth images in Google Maps.

This face isn't as instantly recognisable as some of the other images captured by the Google Faces project, yet you can see its eyes, nose and what appears to be a quiff-style haircut. This image was taken on the side of one of the mountains at the Denali National Park and Reserve in Alaska. The park is home to Mount McKinley - the tallest peak in North America

The Google Faces tracker scans the satellite images from Google Earth using a computer algorithm. When it detects an area of land that appears to look like a face, the features are highlighted and the coordinates are sent to the design team in Germany to record its location and take a screenshot of the hidden face

@highlight

Google Faces project is scanning the world one zoom level at a time, recording the coordinates of each hidden face

@highlight

Facetracker uses an algorithm developed by German company Onformative that mimics how humans have a tendency to see faces in everything