By
James Chapman

'The European Union has blood on its hands': Farage on TV with Clegg. His comments have led to accusations that he is siding with Vladimir Putin

Nigel Farage refused to back down yesterday after he was accused of siding with Vladimir Putin in claiming the EU has blood on its hands over the crisis in Ukraine.

The Ukip leader provoked controversy by using a TV debate with Nick Clegg to insist that both Britain and Brussels are to blame for Russia seizing Crimea.

Critics from all three main parties accused him of allowing his hatred of the EU to lead him into mirroring the arguments of Putin, which have prompted worldwide condemnation.

But Mr Farage insisted the West had given false hope to people in Ukraine of closer ties with Europe in the full knowledge that it would antagonise Putin and prompt a military response.

‘I’m not sure how this is controversial: there is a clear pattern of behaviour on how Russia reacts to eastward EU expansion and it’s not with invitations for a tea party and a polite chat,’ he said.

The Ukip leader said the Government had ‘geed up the EU’ to pursue an ‘imperialist, expansionist’ policy which had meant leading people in the Ukraine to believe that their future could lie with Europe.

‘They actually toppled their own elected leader,' he said. ‘That provoked Mr Putin, and I think the European Union frankly does have blood on its hands in the Ukraine.’

Mr Farage said later that he did not support the Russian invasion of Crimea, but insisted: ‘If you poke the Russian bear with a stick he will respond.’

Former Ukip leader Lord Pearson backed Mr Farage, saying: ‘Russia has been making it known for years that it couldn’t, can’t and won’t tolerate the Crimea coming under the sphere of influence of the corrupt octopus in Brussels.’

Mr Clegg, who clashed with Mr Farage on jobs and immigration in the first of two TV debates on the EU, said Ukip’s claims were shocking and an insult to democracy campaigners in Kiev who rose up after President Viktor Yanukovych rejected an association deal with the EU, preferring closer ties with Russia. Dozens were killed in the violence.

‘It shows quite how extreme people can be, like Nigel Farage, when their loathing of the European Union becomes so all-consuming that they even end up siding with Vladimir Putin in order to make their point,’ Mr Clegg told LBC radio.

Russian soldiers and their dog in Crimea: Mr Farage said later that he did not support the Russian invasion of the Black Sea peninsula, but insisted: 'If you poke the Russian bear with a stick he will respond'

International Development Minister Lynne Featherstone said of Mr Farage: ‘I expected him to be populist, to twist the facts and to blow his dog whistle on immigration.

‘What I didn’t expect was to hear him taking his talking points straight from the Kremlin. When the subject of Ukraine came up, Nigel Farage’s answer was “I agree with Vlad”.’

Mr Clegg faced his own difficulties after claiming in the debate that only 7 per cent of UK law originates in Brussels.

It emerged that the Deputy Prime Minister’s figure relates only to primary legislation and the true figure is estimated at between 15 per cent and 50 per cent.

ANALYSIS By DANIEL HANNAN, Conservative MEP

FARAGE CLAIMED: Seventy-five per cent of our laws come from the EU.

CLEGG CLAIMED: It’s only 7 per cent.

Seat of power? As much as half of Britain's laws are rooted in edicts handed down by the European Union, according to to a Commons Library briefing note

THE FACTS: Farage’s figure is an estimate based on two others – a survey by Germany’s Federal Justice Ministry which looked at every law passed in Germany and found 84 per cent emanated from Brussels, and the opinion of Luxembourg’s European Commissioner Viviane Reding who said the figure was 70 per cent. Farage, in effect, split the difference.

Clegg said his 7 per cent figure was in a House of Commons Library briefing note. In fact, it mentioned the figure of 6.8 per cent only as a proportion of the UK’s primary legislation directly made by the EU. It added that several other laws were generated by EU rules, concluding: ‘All measurements have their problems and it is possible to justify any measure between 15 per cent and 50 per cent or thereabouts.’

VERDICT? Farage’s figure was sloppy, but Clegg’s was downright dishonest.

CLEGG: Three million jobs are linked to our trade with the EU. If we were outside, those jobs would be at risk.

FARAGE: We buy much more from the EU than we sell – £150billion a year compared to £100billion – and it’s inconceivable that the other EU states would jeopardise their exports to us simply because we withdrew from their political arrangements.

THE FACTS: Clegg’s three million figure is a decade old and, in any case, the pro-European who came up with it has since disowned it. No one seriously claims that if Britain withdrew from the EU we would be excluded from the common market. Almost every other non-EU country – from Iceland and the Faroe Islands to Macedonia and Turkey – trades freely with the EU.

Farage was right to point to the balance of our trade with the EU, which has been negative in 39 of the 40 years of our membership (while we have run a cumulative surplus with the rest of the world).

VERDICT? Clear win for Farage.

Clegg's claim that a withdrawal from the EU could send millions marching to the Jobcentre doesn't stand up

CLEGG: A Ukip leaflet had suggested that 29million Romanian and Bulgarian immigrants might settle in Britain whereas, in fact, the two countries’ joint populations are not even 29million.

FARAGE: The figure had changed because a couple of million had already emigrated to other EU states. In any case, every one of the EU’s nearly 500million people has the right to settle in the UK.

THE FACTS: The combined population of Romania and Bulgaria is 27.5million. Provisionally, the Office for National Statistics puts the total number from the two countries living in the UK (including those who had arrived before restrictions were lifted in January), below 200,000.

Farage is right that the free movement of people is an inescapable requirement of EU membership – though this does not qualify them to free benefits. Ukip damaged its case by its hysterical predictions at the end of last year, and Clegg is right to point out that EU migrants to Britain have, so far, generated more in tax than they have claimed in welfare.

VERDICT? Win on points for Clegg.

@highlight

Ukip leader refuses to back down after criticism from three major parties

@highlight

He had accused EU of 'imperialist, expansionist' policy over Ukraine

@highlight

'If you poke the Russian bear with a stick he will respond,' Farage said

@highlight

Clegg calls his remarks an insult to pro-democracy campaigners in Kiev

@highlight

But Deputy PM faces criticism over sloppy use of statistics in debate