By
Tom McTague, Deputy Political Editor for MailOnline

Fed-up Scottish voters have flocked to a new art exhibition lampooning the warring independence camps, with just two weeks to go before the historic September 18 poll.

Glasgow's Veneer Gallery has been taken aback by the public interest in a new show featuring tongue-in-cheek images mocking the Yes and No teams. It comes as Alex Salmond and Alistair Darling ramp up their campaigns to win over the remaining undecided voters.

The paintings, by Scottish artist Dominic Currie, 56, are inspired by cult pop artist Roy Liechtenstein and American comic books. They include a unique take on Liechtenstein's Drowning Girl, with the speech bubble altered to say: ‘Ah dinnae care. I'd rether sink than vote yes!’

Referendum-inspired Scottish Pop Art by Fife artist Dominic Currie is being displayed at the Veneer Gallery, Glasgow

Another features Margaret Thatcher's face with the slogan 'Better To Get Her'. Another depicts a group of young boys urinating on a wall beneath a window from which Alistair Darling is watching.

Mr Currie said he decided to create his artwork because he was ‘absolutely fed up of the Punch and Judy show’ involving Alistair Darling and Alex Salmond.

He said: ‘I would say for the average punter in the street it's been a total turn-off. It's not been any advert for empowering people.

‘The whole campaign has been absolutely negative and throwing insults. Nobody knows what's going to happen.

‘I thought to myself what you need is a bit of tongue-in-cheek satire and maybe even give people a bit of something to think about.’

The Methil artist said the Margaret Thatcher image came to him as he felt no matter who Scotland voted for in past elections, they always got ‘Margaret Thatcher politics’.

And according to Mr Currie, the urinating boys picture is ‘Better Together in action’.

He said: ‘It's just taken off. I never thought I would do this in any serious way.’

Mr Currie’s referendum series is currently on display in Glasgow's Veneer Gallery and he has already sold a huge number of prints. His original Drowning Girl painting was snapped up on the launch night.

One of the images depicts a group of young boys urinating on a wall below a window where Alistair Darling is standing

Currie used the Pop Art images to poke fun at both sides in the referendum debate

The images are inspired by American-pop artist Roy Lichtenstein and characters from comic books

It comes as Scotland’s First Minister Alex Salmond goes head to head with the No campaign over threats to the economy.

Mr Salmond will set out his vision of the gains of independence for the food and drink industry on a visit to Eden Mill distillery and brewery in Guardbridge, Fife.

Meanwhile, shadow Scottish secretary Margaret Curran and Labour MSP Iain Gray will be at Glasgow's Tennent Caledonian Breweries to highlight jobs and opportunities they say will be available as part of the UK.

Today is the deadline for Scots to register to vote in the referendum on September 18.

The latest YouGov poll shows support for independence has risen eight points in a month, with the No camp now six points ahead of the Yes campaign.

Excluding undecided voters, 53 per cent plan to vote No, while 47 per cent would back Yes.

Speaking ahead of his visit, Mr Salmond said: ‘Scotland is one of the wealthiest countries in the world, and our booming food and drink industry is just one of our remarkable success stories in recent years.

‘More and more people are waking up to the fact that Scotland has a strong and diverse economy on which we can build a more prosperous future with control of key economic levers.

‘Scotland is currently in the international spotlight like never before, but the huge publicity generated by a Yes vote - and the transition to independence - will be the opportunity of a lifetime for our food and drink sector to extend its global reach even further.’

Mr Salmond said the Scottish Government had been working with the industry on a £4.5 million food and drink export plan.

He added: ‘Following a Yes vote, we will sit down with industry and Food and Drink Scotland to discuss how we can supplement that plan to take full advantage of the unprecedented global publicity, creating thousands of jobs in Scotland and boosting our exports.’

Fife-based painter Dominic Currie has put together 11 individual pieces - including a take on Liechtenstein's Drowning Girl, with the speech bubble altered to say: 'Ah dinnae care. I'd rether sink than vote yes!'

Ms Curran argued that young people in Scotland would benefit from more job opportunities within the UK.

She said: ‘Around one million jobs in Scotland rely on companies based elsewhere in the UK and many more are with companies that rely on trade with England, Wales and Northern Ireland.

‘Young people across Scotland can't afford to have opportunities cut off.

‘'We want a strong Scotland backed up by a strong United Kingdom. Being part of the UK means that we can share our resources across the country.

'Scots are squeezed between two governments with the wrong priorities.

Neither the Tories nor the SNP are giving our young people the chances they need to succeed.’

Elsewhere on the campaign trail, Labour MP Jim Murphy is due to resume his 100 streets in 100 days tour in Edinburgh's Princes Street. 

 

@highlight

Glasgow's Veneer Gallery taken aback by public interest in a new show

@highlight

Paintings inspired by public anger over 'Punch and Judy' referendum debate

@highlight

Pop art images feature boys urinating against a wall below Alistair Darling

@highlight

Artist Dominic Currie behind the show says exhibition has 'just taken off'

@highlight

It comes just two weeks before the historic September 18 referendum

@highlight

Today is the deadline for Scots to register to vote in the referendum