A British gym has become the first in the world to harness the energy of its users to generate its own electricity.

Bikes, cross trainers and 'vario' machines at Cadbury House in Congresbury, near Bristol will each feed around 100w per hour back into the building's power supply.

The new treadmills will also use 30 per cent less electricity and generate enough energy to power their own information screens.

A first: The Cadbury House gym in Congresbury, Somerset is the first in the world to harness the energy of its users to generate electricity

Power: The machines, which use 30 per cent less electricity than usual machines, store energy produced by users in a dynamo

The 42 pieces of equipment, called ARTIS and supplied by Technogym, cost £600,000 and are considered the most energy efficient in the world.

Jason Eaton, general manager of the 
club said: 'This is the very latest in health club technology in terms 
of design, sustainability, connectivity and biomechanical excellence.

'On top of that we're reducing the level of energy needed to power the club which is great for the environment.'

The technology works by using a dynamo or holding cell.

Once the user has begun to exercise, the equipment will power up - generating electricity from the energy they are producing.

Work out: The energy generated by users helps power the machine's screens, pictured

View: The machine's screen shows how much energy is being produced by the exerciser

As soon as the machines have generated enough power to operate, any surplus energy will be stored inside a holding cell, or dynamo, which is then fed back into the building's electricity supply.

The treadmills use innovative brushless motor technology, combined with low friction materials, to reduce their energy consumption by 30 per cent.

The state-of the-art equipment also allows users to connect to the machines using their smart phones.

Users can log on via Quick Response (QR) codes of Near Field Communication (NFC) technology and track their own training programme and records.

Web bookmarks, apps and social networks are accessible from the machines and gym-goers can even use programmes such as Facebook or even Skype while exercising.

Range: There are 42 pieces of ARTIS equipment in the gym, which cost £600,000 to install

Each cycling and running machines have a screen on the front, which can access the internet and various TV services, as well as provide access to training information and professionals.

Users can also virtually compete against anyone else around on the Unity system.

Outside workouts can also be linked to 'Unity' so users can keep track of bike rides, runs, hill walks or team sports allowing a complete overview of their physical activity.

Mr Eaton added: 'The prevalence of smart phones has opened up the way people live their lives and by allowing them to manage their work out and training programme via this sort of technology is a great step forward.'

 

@highlight

ARTIS machines at Cadbury House in Congresbury, near Bristol will each feed around 100w per hour back into the building's power supply

@highlight

Also use 30 per cent less electricity than regular machines

@highlight

Energy generated by the eco machines - which can be controlled by a smartphone - also powers up the screen displays