Foreign billionaires, multinational businesses and UK-based banks will be hit with swingeing tax hikes, George Osborne said today.

Wealthy ‘non doms’, who have based themselves in Britain for years without paying tax, will  see the annual charge for staying in the country double. 'Non-domiciled residents' live in UK but are registered as foreign nationals to save tax on income made abroad.

But from next year  non-doms who have lived in the UK for 12 of the last 14 years will have to pay £60,000 a year to qualify for the status – rising to £90,000 if they have been in Britain for 17 of the past 20 years. The current rate is £30,000.

Scroll down for video 

George Osborne said some banks won’t pay tax for 15 to 20 years. He said this was 'totally unacceptable'

Mr Osborne said the tax changes meant the richest 20 per cent in Britain were contributing more than the remaining 80 per cent put together. He said this proved ‘we are all in this together’.

A new levy on multinational businesses - dubbed a ‘Google tax’ - will also be introduced to stop giant technology firms avoiding tax. 

The Chancellor claimed that some of the largest companies in the world ‘including those in the tech sector’ use complex tax arrangements to ‘avoid paying taxes’.

He announced there would be a new 25 per cent tax on profits generated by multinationals  in the UK.

At the moment many firms ‘artificially shift’ profits out of the country to cut their tax bill, he said.

Mr Osborne told MPs: ‘That’s not fair to other British firms. It’s not fair to the British people either. Today we’re putting a stop to it. My message is consistent and clear. Low taxes; but taxes that will be paid.’

Google was last year accused by MPs of 'calculated and unethical' tax affairs after its HMRC bill came to light.

The company generated £11.5billion in revenue from the UK between 2006 and 2011 and paid just £10million in corporatation taxes in the same period. 

The multinationals targeted include Silicon Valley technology companies such as Google, Amazon and Apple, and also Starbucks.

The tax - officially referred to as the 'diverted profits tax' is intended to raise an extra £1billion over the next five years.

Mr Osborne said the tax changes meant the richest 20 per cent in Britain were contributing more than the remaining 80 per cent put together. He said this proved ‘we are all in this together’.

UK-based banks will also be stopped from using losses from overseas to cut their tax bill in Britain.

The Chancellor also laid out plans to ‘make sure our banks pay their fair share too’.

Mr Osborne told MPs: ‘Under the rules we inherited banks can offset all their losses from the financial crisis against tax on profits for years to come.

‘Some banks wouldn’t be paying tax for 15 to 20 years. That’s totally unacceptable. The banks got public support in the crisis and they should now support the public in the recovery.

‘I am today limiting the amount of profit in established banks that can be offset by losses carried forward to 50 per cent and delaying relief on bad debts.

‘Together that means banks will contribute almost £4billion more in tax over the next five years.’

 

@highlight

Wealthy 'non doms' in UK for years to be charged up to £90,000 a year

@highlight

New levy dubbed 'Google tax' introduced to raise more from multinationals

@highlight

Comes after MPs said tech firm accused of paying 'unethical' amount of tax

@highlight

Banks also stopped from using foreign losses to reduce taxes in UK 