Claims: Lutfur Rahman, 48, is accused of using illegal tactics to win a mayoral election

Britain’s first elected Muslim mayor is to face trial over claims he committed widespread voting fraud.

Lutfur Rahman, 48, is accused of using illegal tactics to win the mayoral election in Tower Hamlets, East London, in May.

People were allegedly promised council houses if they backed him and Islamic voters were told they should be ‘good Muslims’ and support him.

His supporters are accused of doctoring ballot papers, manipulating postal voting and sabotaging the chances of his main rival, Labour candidate John Briggs, by branding him racist and anti-Islamic.

Four voters have submitted a damaging dossier of evidence to the High Court in an attempt to overturn Mr Rahman’s election victory.

Yesterday Mr Justice Supperstone and Mr Justice Spence granted them the right to have their allegations heard at a full trial, which is expected to be heard in Tower Hamlets later this year.

Mr Rahman was a member of the Tower Hamlets Labour Party and was its candidate to be the first directly elected mayor of the borough in 2010.

But he was expelled from the Labour party after allegations surfaced about his close links with an Islamic extremist group called the Islamic Forum of Europe.

Mr Rahman then won the 2010 mayoral contest as an independent candidate.

The mayor, who earns around £65,000 a year, was re-elected in May, even though his council was under two separate investigations at the time – one by the Government for alleged misuse of funds and one by the police for fraud.

The petition against Mr Rahman was submitted by residents Andrew Erlam, Debbie Simone, Azmal Hussain and Angela Moffat.

Allegations: Four voters have submitted a damaging dossier of evidence to the High Court (pictured) in an attempt to overturn Mr Rahman's election victory

They claim that supporters of the mayor descended on 41 polling stations at night, ‘making it difficult or impossible for voters to get into the stations’.

Bengali voters, especially women, were intercepted by Mr Rahman’s supporters outside polling stations and ‘directed how to vote’, the dossier claims.

Labour votes were allegedly ‘crossed out’ on ballot papers and replaced with votes for Mr Rahman’s party, using a different coloured pen.

The dossier also alleges that council officers were bullied into ‘securing a certain number of votes’ and were threatened with the sack if they refused.

Votes were cast in the names of people who were not ‘entitled to be on the electoral register’ and numerous postal ballots were filled in by the same person, the High Court heard.

Signatures on some postal ballots did not match the signatures on application forms previously submitted and a voluntary organisation was given grants in exchange for votes, it was said.

Rivals: Supporters of Mr Rahman (right) are accused of doctoring ballot papers, manipulating postal voting and sabotaging the chances of Labour candidate John Briggs (left), by branding him racist and anti-Islamic

Ahmed Hussain, a losing Conservative Party candidate, told the Mail: ‘Mr Rahman and his supporters carried out fraud on a massive scale.

‘Voters turned up at the polling station 
to be told they had already sent in a postal vote and therefore could 
not vote again. But they hadn’t – Rahman supporters had stolen their 
votes and now it was too late.

‘His men would target the vulnerable - the elderly, women and single parents - and offer to “help” them with their vote. This would mean filling out a postal vote in front of the party voters who would then check they had voted for Rahman.

‘They would offer to post votes, but check them first. If they had not voted for Rahman then they would simply scrub it out and tick the Rahman party box.

‘They offered to pay for the votes of relatives who were out of the country - £10 or £15 each. And they made people add members of their household so they too could vote.’

The 46-year-old, who works for the NHS, said Mr Rahman also used more subtle ways to intimidate voters into supporting him.

Mr Hussain, who is originally from Bangladesh, says the alleged fraud has nothing to do with ‘cultural traditions or practices’ of the many Asian voters in Tower Hamlets.

He added: ‘It’s nothing religious. It’s nothing cultural. This is illegal full stop. This would be illegal in Bangladesh as it is in the UK.’

Last night Mr Rahman strenuously 
denied allegations of electoral fraud. He said: ‘There is simply no 
evidence to substantiate that the recent elections results were due to 
fraud and intimidation.

‘It 
is clear that these complaints are being generated by disgruntled 
candidates who lost. I am completely confident that at the end of this 
process such claims will be exposed for the smears that they are.’

Rahman and supporters of his Tower Hamlets First (THF) party were also accused of bribing voters.

In an application to the High Court petitioner Andrew Erlam said: ‘A THF council candidate telling [told] voters that if they vote for THF they will all get [local authority] houses.

‘A THF candidate handing [handed] out lollipops to children whose parents came to vote.’

'His men would target the vulnerable - the elderly, women and single parents - and offer to "help" them with their vote'

Ahmed Hussain, losing Conservative Party candidate

Mr Erlam, a Labour Party supporter, added that Rahman supporters intercepted Bengali voters, especially women, outside polling stations, ‘accompanied’ them to polling booths and ‘directed them how to vote’.

He claimed in one ward votes for Labour were ‘crossed out’ and ‘Tower Hamlets First votes entered with a different colour pen’.

He added in another ward Labour votes ‘appeared to have been erases’ on a ‘substantial number’ of postal ballot papers. And that counting agents ‘reported that many postal ballots to have been completed in the same hand writing’.

Sorry we are not currently accepting comments on this article.

@highlight

Lutfur Rahman allegedly used illegal tactics to win May mayoral election

@highlight

Islamic voters were 'told they should be good Muslims and support him'

@highlight

Supporters accused of branding his main rival racist and anti-Islamic

@highlight

Four voters have submitted damaging dossier of evidence to High Court