As the anticipation builds for the release of Fifty Shades Of Grey, it seems there is one person who simply can't hide his excitement.

Today Show host Matt Lauer  was seen revealing his kinky side when he donned a leather harness - and not much else - while  interviewing the movie's costars.

However, it turned out to be some clever digital trickery from prankster Ellen DeGeneres and her team, who showed the spoof clip during Wednesday's episode of her chat show.

Scroll down for video 

Who knew he was such a fan?: Today Show host Matt Lauer is seen taking his love of Fifty Shades Of Grey a little too far in a spoof clip Ellen DeGeneres put together on Wednesday

Kinky: The host is seen giving a sneaky crack of his whip during the sit-down chat

Ellen introduced the video saying: 'The Today Show has been showing exclusive clips of the movie for the past two weeks and they've been interviewing the stars.

'And boy, they're getting into it. I was watching this morning and Matt Lauer... eh.. just take a look.'

In the short clip Fifty Shades star Jamie Dornan is seen answering a question posed to him by the NBC hosts when the camera pans back to his interviewers to show Matt casually adjusting his bondage straps. 

'Boy they're getting into it': The comedian joked with her audience that she noticed something interesting in the Today Show interview before showing the clip

Just a regular interview: Matt is seen wearing a leather harness as he sits across from Fifty Shades costars Jamie Dornan and Dakota Johnson 

Fellow Today cohost Savannah Guthrie keeps smiling at the actors as she sits beside her colleague who is seen in black hotpants, PVC lace-up boots and wrist cuffs.

Dornan and Dakota Johnson remain composed - even as Matt takes out a whip and cracks it in their direction.

Taking it one step further, the journalist then looks intently at the costars while he dangles a pair of sinister-looking handcuffs in front of them. 

On Thursday morning's Today show Matt took the prank in good humour telling viewers 'That cracked me up - I laughed out loud'.

Nothing to see here: The journalist - sat next to cohost Savannah Guthrie - casually adjusts a strap as Jamie chats away

Professional: The actors looked calm and serious as they discussed the upcoming flick with the near naked newsreader

BALENCIAGA leather skirt

Not available online but check the current collection at Barney's

Visit site

The movie adaptation of 50 Shades Of Grey might have divided critics, but Fashion Finder thinks we can all agree that Dakota Johnson's style during the promotional tour has been faultless.

Here the brunette beauty stunned in a quirky yet sophisticated outfit of a mohair white and black buttoned cardigan tucked into a leather skirt, both items by esteemed French fashion house, Balenciaga.

And there were no shades of grey in this monochrome outfit as Dakota sleekly finished the look off with a pair of ankle strap stiletto heels and her hair styled in a messy side plait, keeping accessories stripped back. Gorgeous!

Leather has been the ultimate texture this autumn/winter and has been adored by A-list fashionistas, with Kim K loving her leather blazers, trousers and skirts amongst other things, as well as Beyonce following suit with her love of leather look trousers from Zara. They’re all into it!

And although you can't buy Dakota's exact skirt online, you can emulate her look (for a lot less) with the alternatives in the style edit below which includes our top picks from River Island and Forever 21.

Forever 21 leather look pencil skirt

Visit site

River Island black leather look pencil skirt

Visit site

ASOS pencil skirt

Visit site

Bailey 44 high waist skirt at Neiman Marcus

Visit site

But Ellen better watch out as the NBC newsreader warned: 'Revenge is a dish best served cold!'

Meanwhile, Fifty Shades Of Grey - based on the erotic novel of the same name by E.L James is released on Friday.

Critics have been quick to point out the movie's flaws - mainly the lack of chemistry between the two leads who play lovers Christian Grey and Anastasia Steele. 

One reviewer pointed out that sex only makes up 15 minutes of the two-hour runtime. Another pointed out that there are no visible genitals, no orgasms - and not that much nudity. 

Laughs: Ellen looked very pleased with herself after presenting the prank on Wednesday's show 

His response: Matt took it in good humour but warned 'revenge is a dish best served cold'

@highlight

NBC host seen in leather harness and chains as he interviews actors

@highlight

But clip was computer generated by Ellen DeGeneres and her team

@highlight

Lauer says he will get revenge on comedienne for her prank