Fat? Who? Me? Oh, get away with you. Yes, it’s strange, but true: two years ago, I was so far into self-deception that not only did I not mind being fat, I honestly didn’t even realise that I was.

Where others might have been buffeted by shame, I had hurtled north of 60 in merrier mood, counting the blessings, but never the pounds.

The hair was, and is, unblemished by grey. Adapting the mantra that ‘when I am old I shall wear purple’, my wardrobe eschewed chic black in favour of riotous colour.

Carol says: 'You are fat because you gave your stomach too much and now you're giving it too little. Of course it's going to growl.'

As for my fading eyesight, I turned it into a plus with a costly passion for outrageous glasses.

But the body? Ah, the body.

I think the mindset changes when you reach the age when your body is never again likely to be seen by anyone who has not already seen it.

It’s not an overnight thing, but you start to cross lines — not least the line between dressing the body and draping it. I ate like a pig, the scales gathered dust and dresses grew wider.

I no longer struggled upstairs on a bus, my ankles swelled in heat and I bought a bath with handles.

Still, I thought, that’s just age. Isn’t it?

And so to the awakening. A routine medical began with being weighed. ‘Two hundred pounds,’ the (skinny) nurse intoned. Or, if you prefer, 14 stone 4lb. On a 5ft 6in frame.

Worse were blood sugar levels teetering towards diabetes.

I didn’t need the doctor to mention the elephant in the room — and rarely has the phrase been so aptly used. On the BMI (body mass index) scale  I had waddled into ‘obese’ (over 30). Something had to be done.

But what? Please, please let it not be a diet.

Heaven knows, I am no stranger to diets. In younger days — propelled by vanity, not health, I would happily diet to 9st while smoking 40 a day — I tried the lot.

90 per cent of British women have been on some form of diet in their lifetime -  on average spending a staggering 17 years of their life dieting

From cabbage soup to grapefruit to high-protein to low-fat, from counting calories to counting carbs to injectable stimulants. And while I would — temporarily — lose weight, what I gained was an abiding loathing of the diet industry.

The bare facts disgrace us: 29 million people in Britain tried to diet last year, with 39 per cent buying into the trendy 5:2, which is propelling its creator, Michael Mosley, towards the Rich Lists already climbed by his diet guru predecessors.

Dr Robert Atkins (ten million books sold) died a millionaire — albeit a fat one; Pierre Dukan (seven million sold) is similarly wealthy.

Yet all this money, together with billions generated by diet clubs, recipe books, supplements and ready meals, is made out of selling the lie that they will work when in the long run they do not.

What is worse, the only way this industry can keep the lie alive is to turn clever women into stupid women.

Answer this: which makes you fatter: a large sweet potato, roasted in oil then piled with cinnamon sugar and melting butter, or two sticks of celery? See?

The fact is, any adult with an IQ above room temperature knows what makes them fat.

And so back to my dilemma: dangerously porky, determined not to be, but damned if I would go on a diet.

So, I resolved to lose weight my way. The BMI index hinted three stone should be enough; that’s 42 pounds. I decided to lose one pound a week, every week, for 42 weeks. And it worked. What annoys my  friends is that I can’t tell anyone else how to do it — if I could, I might sell a million books, too. All I can say is that I neither counted nor weighed anything. I relied instead on ‘more’, ‘less’ and ‘none’.

The first two were trial and error: if the pound failed to budge one week, I’d revise the ‘more’ to ‘less’.

‘None’ was easy: some pleasures stayed sacrosanct (butter, Yorkshire pudding, red wine), others I banished (beer, cheese, sugar).

Unlike diets, when all you think about is what you are next ‘allowed’ to eat, I put food on the back burner. Unlike diets, I told myself no lies. The first great lie that diets tell is that their food is delicious when it is not — egg-white omelettes enlivened by cottage cheese? Why pretend?

Instead, I expected my food to be fuel, not fun. Breakfast — yoghurt, seeds, nuts and berries — and lunch — a small sandwich — passed without note. Dinner was steak or chicken with veg  (hence the butter and red wine).

The second great diet lie is that you won’t be hungry; there is that terrific snack for elevenses and another at teatime …

'All I can say is that I neither counted nor weighed anything. I relied instead on 'more', 'less' and 'none'.' says Carol, who lost 42 pounds in 42 weeks

This is nonsense. You are fat because you gave your stomach too much and now you’re giving it too little. Of course it’s going to growl.

Fact: if you do not feel hungry on occasion, then you are not losing weight.

Maybe this is why so many diets fail. The discomfort feels like a betrayal, you don’t believe in the diet any more, so where’s the biscuit tin?

However, I could only let myself down. Or not.

One trick was to drink a pint of fizzy water and go early to bed feeling full. Another was to drink the water AND red wine … then go early to bed with a smile.

The point about losing weight my way is that everyone would choose different non-negotiables, different banishments and different tricks.

The loss is in any case slow, so for ages it is unnoticeable. I did keep track, but because I was doing it for health I used a BMI chart: down it crept, from the ‘obese’ 33 to — hallelujah! — merely ‘overweight’ at 29 (180lb). In time, bonuses cheer you along, like the first time I hopped upstairs on a bus without thinking about it.

Clothes fitted better, then not at all: just too big, at 20 or 18. Their replacements were less draped and more tailored.

I could clamber more easily from the bath — of course I could; have you tried lifting a suitcase weighing 42 lb? My shoe size dropped, my ankles shrank, my puff calmed.

‘Overweight’ eventually fell into a ‘normal’ BMI of 25 as, after 40 weeks, I reached a loss of exactly 42 lb, to weigh 11 st 4lb. Better yet: my blood sugars also read ‘normal’.

Admittedly, I am no string bean; I am a size 14 and need shapewear. Nevertheless, I understand my body better than ever and feel absurdly proud that I took control of it myself, rather than relinquishing it to someone else’s rules.

So, again at my own behest, I chose to stop losing weight.

And here’s the best bit of all. It is a year since I stopped. A year during which, if I gained a pound, I immediately took it off again just by following the same principle of self-control.

This means that today, as I write, I still weigh the same  11 st 4lb. Smug? Oh, you bet. Unbearably.

@highlight

Hater of diets, when Carol realised she was fat she wasn't sure what to do

@highlight

She needed to lose 42 pounds

@highlight

Decided to lose a pound a week for 42 weeks

@highlight

Relied upon 'more', 'less' and 'none', rather than calorie counting