By 
Helen Collis

PUBLISHED:

04:58 EST, 27 September 2013


| 

UPDATED:

08:18 EST, 27 September 2013

A British schoolboy has been arrested over his alleged involvement in the 'world's biggest cyber attack' generated by a suspected global crime gang.

The 16-year-old was taken into custody when police swooped on his south-west London home after investigations identified 'significant sums of money' were 'flowing through his bank account'.

Detectives found he was allegedly logged onto several 'virtual systems and forums' when they swooped on the property and worked through the night to collect as much evidence as possible.

The teenager was arrested in April when detectives swooped on his south west London home. They allegedly found him' logged onto various virtual systems and forums'

The teenager is accused of being involved in one of the world's largest and most destructive cyber attacks, which allowed spam messages for fake drugs and other illegal products to reach people's inboxes.

The global crime gang believed to be responsible is accused of unleashing a 'distribution denial of service' (DDoS) attack against the anti-spam group Spamhaus so big that it slowed the internet.

The schoolboy was arrested in April and was released on bail, but his alleged link to the crime gang has been kept under wraps until now.

His arrest was revealed during a ministerial visit by James Brokenshire MP to the UK government's growing cyber unit last week.

A briefing document for the visit, seen by the Evening Standard, under the umbrella of Operation Rashlike, described the cyber attack as the 'largest DDoS attack ever seen' which had a 'worldwide impact' on internet exchanges.

In details of the boy's alleged involvement, it states: 'The suspect was found with his computer systems open and logged on to various virtual systems and forums.

'The subject has a significant amount of money flowing through his bank account. Financial investigators are in the process of restraining monies.'

Attack: The cyber attack targeted the Dutch anti-spam group Spamhaus, which was listed as being based at Communications House, in London pictured

Officers from the National Cyber Crime Unit, recently formed by the merger of the Police Central e-Crime Unit and the Serious Organised Crime Agency (SOCA), have been working with detectives worldwide to trace the suspects of the attack.

Others have also been identified and their properties raided as part of the operation, according to the Independent, and at least one other arrest has been made - a 35-year-old Dutchman living in Spain.

The National Cyber Unit will soon fall under the control of the newly-formed National Crime Agency, employing 4,000 staff tasked with solving and combatting the country's most serious crimes.

More than half of the workforce will be trained in fighting cyber crime, a fast-growing potential threat to the UK security.

Recently, two cyber attacks on banks were unleashed in Europe.

Four men have appeared in court accused of plotting to allegedly take of Santander computers by fitting a device during maintenance work.

And in connection with the second attack, eight were arrested over a £1.3million theft by a gang who took control of a Barklays computer, according to the Independent.

Sorry we are unable to accept comments for legal reasons.

@highlight

Detectives 'found boy logged onto various virtual systems' when they raided

@highlight

Cyber attack 'was so big it slowed the internet with spam messages'

@highlight

It was believed to be generated by an international organised crime gang

@highlight

At least one other arrest has been made in Spain in global cyber operation