They have been touted by some as the cheap and eco-friendly future of energy. 

But many of Britain’s solar panels are not actually generating as much power as they could – because they are facing the wrong way, an expert has warned.

Angling solar panels in an alternating east and west-facing formation, rather than in rows facing directly towards the south, would actually increase the amount of electricity generated overall.

This house, built in the thirties, has a solar panel heating system across the roof (File photo)

Such a formation means they do not 
need to be spaced out, as there would be a reduction in shadow. This 
allows them to be active for a longer period each day.

It
 would also cut the risk of disruption to the National Grid, says Ralph 
Gottschalg, of Loughborough University, who is working on a UK-wide 
project aiming to answer a number of questions relating to the 
production of energy through solar panels.

In
 solar farms or industrial premises with swathes of solar panels, they 
are broadly positioned to face south following the logic that they will 
pick up the most sunlight.

However, the shadows they cast means the panel behind can’t be too close together.

Video courtesy of Eco Experts

A single east-west panel produces slightly less electricity than single south-facing one, twice as many panels can be packed in the same space

As
 Britain’s use of solar power increases, this could lead to disruption 
to the grid. Plus, excess energy that cannot be stored will be wasted

Professor
 Gottschalg, an expert in solar technology, said that laying them 
flatter and angling them so that they face east and west alternately 
would cut the amount of shading and so allow them to be put more closely
 together.

And while it is 
true a single east or west-facing panel produces slightly less 
electricity than a single south-facing one, around twice as many panels 
can be packed in the same space. Even when the cost of installing the 
extra panels is taken into account, savings will be made in the long 
run.

Professor Gottschalg 
admits that his theory is not easily adopted by householders who install
 solar panels as they  cannot change the shape of their roof. Nearly 
half a million British homes have solar panels and the typical family 
saves an estimated £800 a year due to cheaper energy bills and green 
subsidies.

But Professor Gottschalg does suggest that, where possible, homeowners should take advantage of panels that face east and west.

Speaking
 on Radio Four, he said that south-facing panels generate the most 
electricity in the afternoon when the sun is at its highest – but this 
is when householders are out at work and cannot use all the power 
generated.

While some can be stored in batteries, much of the excess electricity is fed back into the national grid.

And as Britain’s use of solar power increases, this could even lead to disruption to the grid.

However,
 he would like to see a ‘smart subsidy’ introduced that would 
incentivise owners of large-scale solar farms to angle their panels 
differently.

Leonie Greene,
 of the Solar Trade Association, said householders should not worry as 
the difference in electricity generated by south, east and west-facing 
panels is small.

However, large-scale installations could benefit from installing a combination of panels.

@highlight

Prof Ralph Gottschalg, of Loughborough University, said that angling solar panels east and west would increase the amount of electricity generated

@highlight

Nearly half a million British homes have solar panels

@highlight

Typical family saves an estimated £800 a year due to cheaper energy bills and green subsidies 