By
Eddie Wrenn

A space professor from Oxfordshire is battling 'to save Earth' from a solar storm that experts fear will wreak worldwide chaos next year.

Professor Mike Hapgood, who chairs the Space Environment Impacts Experts Group (SEIEG) and advises the Government on space weather, says solar storms, generated by an outburst from the sun, are set to knock out national power grids and Global Positioning Systems.

He believes magnetic rays from the storm will result in widespread blackouts which will plunge homes and businesses into darkness.

Scroll down for video

Eye of the storm: A solar eruption, with a temperature of approximately 50,000C, could take out the National Grid, along with many electrical systems across the world

It could also lead to potentially deadly knock-on effects, for instance 
if hydro-electric dams holding back millions of gallons of water are 
knocked offline.

Early next year, the sun will reach the peak of its 11-year activity cycle, which puts the planet at greater risk of such storms.

And experts say with the planet now relying on the Internet and hi-tech gadgetry, the chaos caused by the 2013 solar storm will have a far greater impact than any in the past.

Prof Hapgood, who studied at Oxford, warned: 'A big magnetic storm can permeate the Earth's crust, which can drive electric currents through aluminium or copper wires in the National grid, which could cause a national blackout.

'Interactions with Earth's atmosphere can also affect any radio signals. If you had a big storm, GPS might be unavailable for a couple of days.

'On July 21 this year there was a very large event on the far side of the sun, if it had intercepted Earth we would have had a very large magnetic storm.'

All manner of transport relies on GPS including aircraft and if the systems suddenly collapse, there could be lethal consequences.

He said 'My main interest is to study the likely extremes in these scenarios. These are enormous events that could have a very significant effect on GDP.

'The National Grid now relies on warnings from space craft carrying equipment built at Rutherford and they are developing plans on how to evolve.'

Detecting: ACE - the Advanced Composition Explorer - observes particles of solar, interplanetary, interstellar, and galactic origins

Magnetic storms on Earth are caused by Coronal Mass Ejections (CMEs) on the sun, where large clouds of gas held in place by the sun's magnetic field are suddenly released.

When magnetic storms permeate the Earth's crust, the direct current can meet with the alternating current in the National grid and over power transformers, causing them to malfunction.

Prof Hapgood explained there is currently one possible defence.

'It sounds counter-intuitive, but actually the National Grid could switch on the whole grid, to block the effect of extra currents.

Unlike many recent natural disasters, a huge solar flare would cause the greatest suffering in developed countries.

Plasma
 balls blasting out from the surface of the sun could wipe out our 
modern electricity grids, which would draw the energy to them like 
antennas and quickly overload.

This
 would have a knock on effect on many of the systems that support our 
lives, including water and sewage treatment, medicine cooling, 
supermarket delivery, power station controls and financial markets.

To rebuild the grid, the melted transformer hubs would need to be replaced but new ones take up to a year to make to order.

At
 present NASA's Advanced Composition Explorer (ACE) is the most 
important indicator of incoming space weather. It can give 15 to 45 
minutes warning of geomagnetic storms and power companies need 15 
minutes to prepare systems for a critical event.

However, ACE is 14 years old and already operating beyond its planned lifespan with no planned replacement.

Prof Hapgood said 'We will largely lose the early warning capability.'

'At the moment we rely on one American aircraft called ACE which measures the speed of solar flares, plasma coming towards Earth, and its speed and density, but even that can only give a 20 minute warning.'

Prof Hapgood warned that even though next year would bring a peak of solar activity, the Earth is always under threat.

'Next year is a peak in activity. However, we can't find a link between these peaks and the major events like CMEs. You shouldn't breath a sigh of relief and think you are safe, this is a constant risk.'

Experts are warning that the Government must make contingency plans for the solar storm which could create severe water and food shortages.

In 1859 the so-called 'Carrington event' was a magnetic storm that struck Earth - long before the Internet and GPS - and caused the failure of telegraph systems all over Europe and North America. The Northern Lights were reportedly seen as far south as Florida.

In 2009 a report funded by NASA claimed similar storms today would lead to 'planetary disaster.'

The study outlined the devastating impact it would have. For instance it could leave half of the US without power within 90 seconds, without coal after 30 days and would take the country a decade to recover.

Such a scenario would also cost an estimated £1.5trillion - and that would just be in the first year.

Prof Hapgood told the New Scientist magazine in 2009 that 'I don't think the report is scaremongering. This is a fair and balanced report.'

The flare emitted during the Carrington event in 1859 travelled so fast it took less than 15 minutes to reach Earth anyway.

The report's chief author Daniel Baker from the University of Colorado said he hoped it would push decision-makers into action.

'It takes a lot of effort to educate policy-makers, and that is especially true with these low-frequency events. But we are moving closer and closer to the edge of a possible disaster', he said.

VIDEO: Example of a massive solar flare flying off the sun in July 2012... 

@highlight

National Grid and GPS expected to go down if burst from sun hits our planet

@highlight

Sun will reach peak of 11-year solar storm cycle next year, and magnetic storms could knock out most of Earth's electrical items

@highlight

A big storm in 1859 knocked out early telegraph systems - but world is much more dependent on electricity now