By 
Claire Bates

UPDATED:

03:10 EST, 17 January 2012

Boosting vitamin D intake could help prevent deteriorating eyesight and 
blindness in older people, it is claimed.

Scientists said tests revealed taking vitamin D for six weeks could improve vision among middle-aged subjects.

Levels of amyloid beta, a toxic protein linked to Alzheimer's disease and known to be a hallmark of ageing, were also reduced in the study.

Eye test: By the time a person is 70, the effects of normal ageing can lead to a 30 per cent reduction in the number of light receptive cells in the retina

Although the research was on middle-aged mice, scientists believe it could have important implications for human health.

Lead scientist Professor Glen Jeffery, from the University College London: 'Researchers need to run full clinical 
trials in humans before we can say confidently that older people should 
start taking vitamin D supplements, but there is growing evidence that 
many of us in the Western world are deficient in vitamin D and this 
could be having significant health implications.'

Age-related inflammation and damage to the eye's retina can lead to macular degeneration, the biggest cause of blindness in people over the age of 50 in the developed world.

By the time a person is 70, the effects of normal ageing can lead to a 30 per cent reduction in the number of light receptive cells in the retina.

The UCL team injected one-year-old female mice with safflower oil containing vitamin D every three days. A mouse year is roughly equivalent to 50 human years. Another group received injections of vitamin-free safflower oil.

After six weeks, tests which measured the electrical responses of retinal cells showed significant improvement in the vision of the treated mice.

The better performance of their eyes was associated with key biological and molecular changes.

Vitamin D treatment reduced numbers of cells called macrophages that play a vital role in the immune system but can also trigger inflammation. The remaining macrophages seemed to work in a more beneficial way.

Deposits of amyloid beta in the eye were also lowered. Accumulations of the toxic protein are believed to contribute both to age-related macular degeneration (AMD) and Alzheimer's. Amyloid deposits can also play a role in heart disease.

Tests also showed that the vitamin D-treated mice had significantly less amyloid beta build-up in their blood vessels. This included the aorta, the major artery that carries blood away from the heart.

Taking vitamin D supplements in the early stages of AMD 'may prove a very simple and effective route to limit disease progression', the researchers wrote, in the journal Neurobiology of Aging.

They added that the vitamin 'may have a wider role to play in health and problems associated with ageing than in AMD alone'.

Evolutionary history may explain the link between vitamin D deficiency and age-related diseases, said Prof Jeffery.

Most human evolution took place in Africa where the ancestors of modern humans were exposed to strong sunlight. They would not have been short of vitamin D, which is generated by the action of the sun's ultraviolet rays on the skin.

Humans only started living in colder climates and covering their bodies relatively recently in their history.

As a result, people today are generally less exposed to vitamin D than their early ancestors. At the same time life expectancy has increased greatly, bringing a greater disease burden.

Professor Douglas Kell, chief executive of the Biotechnology and Biological Sciences Research Council which funded the study, said: 'Many people are living to an unprecedented old age in the developed world. All too often though, a long life does not mean a healthy one and the lives of many older people are blighted by ill health as parts of their bodies start to malfunction.

'If we are to have any hope of ensuring that more people can enjoy a healthy, productive retirement then we must learn more about the changes that take place as animals age.

'This research shows how close study of one part of the body can lead scientists to discover new knowledge that is more widely applicable. By studying the fundamental biology of one organ scientists can begin to draw links between a number of diseases in the hope of developing preventive strategies.'

@highlight

Deposits of toxic protein linked to age-related macular degeneration and Alzheimer's also lowered in test subjects

@highlight

Scientists believe study could have important implications for human health, especially among elderly