By
Wills Robinson

In 1943, British troops commandeered the hamlet of Imber on Salisbury Plain to prepare for the D-Day landings. 

Seventy years on, a new group of residents have taken it over - a colony of 8 million bees.

Commanded by retired Army major Chris Wilkes, 61, the insects are given the opportunity to thrive in one of the last wilderness area in the UK.

With permission from the Ministry of Defence, he watches over 150 hives dotted across the Site of Special Scientific Interest (SSSI) that has never been treated with modern pesticides.

It is the perfect spot for the beekeeper, who wants to reintroduce Britain's population of indigenous bees, as it is five miles from the nearest colony of foreign insects. 

'The area is very rich in wild flowers,' he said. 'Eighteen of the 22 top nectar producing plants in the UK are right here, including clover, sainfoin, viper’s bugloss, knapweed and melilot. There is also no interference from the public.' 

About 95 per cent of bees in the UK are non-native and were introduced here in the 1920s after a disease virtually wiped out the population. 

Having  are thriving. The hot summer, following on from the wet winter and dry spring, have created a cornucopia of the top nectar flowers in the UK, producing a honey with the distinctive flavour of one of Britain's last wilderness areas. 

Colony: Major Chris Wilkes, 61, commands an astonishing 8 million bees in a 150 different hives near the abandoned village of Imber on Wiltshire's Salisbury Plain

Thriving: The isolated plain is covered with a range of wild flowers across the Site of Special Interest (SSSI), creating a perfect habitat for the bees

Growth: The retired Army major is hoping to reintroduce Britain's native black bee. Most of the indigenous species was wiped out by disease in the 1920s 

Rich: The wet winter and dry spring have produced perfect conditions for the diverse flora of the grasslands which, in turn, have created a cornucopia of nectar 

Unique: The weather will result in a distinctive flavour of honey (right) being produced in one of Britain's last wilderness areas 

New career: The retired Army major from Salisbury, has been given special permission by the Minisrty of Defence to set up 14 colonies of black bees

Isolated: Major Wilkes chose the area in Wiltshire because the colony will not be affected by foreign flying insects 

Closed off: Imber, near Warminster in Wiltshire, was one of several villages in Britain to be taken over by the army in the Second World War so troops could practise for D-Day. It is still surrounded by signs warning the public against venturing onto the land, which is still used for training exercises by the Army

Blossom: In the warm weather, colourful wildflowers have thrived allowing a small number of insects, including a Cinnabar moth, to make the most of the nourishment

 

Array of colours: Two bees sit on the bud of a flower (left). A Wild Orchid is one of the many species of flower that are dotted over the area of Salisbury Plain 

 

@highlight

Imber, a hamlet on Salisbury Plain in Wiltshire, was abandoned in 1943 and acquired by the Ministry of Defence 

@highlight

Retired Army major Chris Wilkes, 61, now commands 8 million native bees in a bid to grow the indigenous population

@highlight

The insects produce a distinctive flavour of honey from the nectar generated by the wildflower in the wilderness area

@highlight

About 95 per cent of bees in the UK are non-native because the indigenous population was wiped out in the 1920s