By
Hugo Gye

PUBLISHED:
  
  
      12:13 EST, 2 January 2014
    
  
 | 
  UPDATED:
  
  
      12:29 EST, 2 January 2014

A museum is appealing for experts to help them decipher mysterious codes written on the side of a World War Two kamikaze plane.

The Japanese 'Ohka 2' aircraft, captured in the Pacific 70 years ago, has been hanging in the rafters of an air museum for more than three decades.

But when it was taken down and inspected more closely, curators found two sets of symbols etched on to the side of the plane, which was intended to be used by a suicide pilot as a flying bomb.

Antique: This Ohka 2 kamikaze plane from World War Two is being restored at the Fleet Air Arm Museum

Mystery: Curators are appealing for experts to decipher these faded symbols on the aircraft hatch

One of the messages is found on the hatch cover, which would have held more than a ton of explosive material, while the other is on the left side of the plane.

Both appear to combine Japanese symbols with other markings whose significance is unknown.

Staff at the Fleet Air Arm Museum in Yeovil, Somerset are now hoping that an expert will come forward who can explain the meaning of the writing.

Ohka 2 aircraft, which were used by the Japanese military towards the end of the war, were deployed on kamikaze missions which killed thousands of Allied sailors.

Display: The plane has been hanging from the rafters of the museum in Yeovil, Somerset for three decades

Bizarre: The drawings are a combination of Japanese characters and mysterious marks

Insignia: The plane is also emblazoned with a cherry blossom, which gives the aircraft its name

They were fixed to the underside of bomber planes, before being flown up to a height of 12,000ft and released.

The vessels would be piloted by suicide pilots, who aimed for Allied ships and would inevitably die on impact.

They could travel unaided for 21 miles, reaching a maximum speed of 475mph.

Only 800 of the aircraft were ever made.

The name of the plane means 'cherry blossom' in Japanese, and a picture of the flower is painted on its side along with the mysterious symbols.

In action: A photograph of the Ohka flying bomb when it was in use during World War Two

Crashed: An Ohka plane captured in Okinawa after failing to hit its Allied military target

The model held by the Fleet Air Arm Museum is believed to have been captured by Allied troops in the Pacific.

It is owned by the Science Museum in London, which lent it to the Fleet Air Arm Museum in 1982.

'It is chilling to look through the cockpit window of this piloted rocket and through the ringed sight,' said Jon Jefferies of the the Fleet Air Arm Museum.

'There's a grab handle fixed to the inner wall of the cockpit as acceleration generated by the three solid fuel rockets would have been incredible.'

The aircraft is set to undergo a forensic restoration, with layers of paint being stripped off to reveal its original colour and markings.

Fearsome: A group of suicide pilots waiting to be dispatched on their deadly final missions

Kamikaze missions are notorious due 
to the fanatical devotion shown by Japanese suicide pilots over the last
 few months of World War Two.

The
 pilots would fly in planes packed full of explosives and direct them 
into Allied ships in a bid to cripple the war effort in the Pacific 
theatre.

Thousands of Allied sailors were killed 
in the attacks, which continued until the end of the war in September 
1945, according to experts.

The advantage 
of kamikaze attacks was that planes being piloted right up to the moment
 of impact were able to hit their targets more accurately than bombs 
dropped from a height.

To
 begin with, the air force simply used conventional planes fitted with 
explosives, but they soon developed purpose-built aircraft such as the 
Ohka 2.

Nearly 4,000 
Japanese pilots lost their lives in the missions, but the death toll was
 considered acceptable because of the huge damage they could do by 
taking out large ships.

However,
 fewer than 15 per cent of kamikaze attacks are thought to have been 
successful, with the vast majority missing their targets.

Attack: A kamikaze mission on the USS Enterprise carried out in May 1945

@highlight

Ohka 2 plane was captured in the Pacific and ended up on display at the Fleet Air Arm Museum in Yeovil

@highlight

When it was being restored experts found undecipherable Japanese codes

@highlight

Curators want experts to help them work out what the symbols mean