A mysterious 'beam' of static electricity has been caught on camera making a passer-by's hair stand on end. 

In the clip, filmed outside Google's headquarters in London, Simon Legrand is shown entering the field of electricity before his hair rises - silhouetted by a nearby street lamp. 

As the camera then pans towards the building, a large crack of static electricity is heard before the video cuts out. 

Scroll down for video 

In the clip, filmed outside Google's headquarters in St Giles High Steet London, Simon Legrand is shown entering the field of electricity (pictured left) before his hair begins to stand on end (pictured right) - silhouetted by a nearby street lamp

The footage was filmed on Friday night. 

Mr Legrand and his friend, known only as Nick, were walking past the tech giant’s office in St Giles High Street, when they said they felt a ‘strong electric field’ and decided to film the experience. 

In the clip, Mr Legrand passes his phone to Nick before saying: ‘Alright, so there’s this static electricity beam, right next to the Google building in London.

‘I’m going to go inside the beam, and my hair is going to go up.’

At which point he explains that he can feel the electricity on his forehead, and describes it as ‘super strong, like a beam of static electricity.’

Although the shot is dark, Mr Legrand’s hair can be seen rising in front of a nearby street light.

The strange field was first discovered by a Reddit user earlier this year. This led to theories that there was a problem with wiring beneath the building (pictured), or that electricity was being generated by the building's metal poles rubbing together. MailOnline has contacted Google for a comment

Static electricity occurs when there is an imbalance between the positive and negative charges in an object.

These charges can build up on the surface of an object, until they find a way to be released or discharged.

When certain materials rub against each other, it can transfer electrons and create this charge - although it is not known what caused the electrical build-up to occur around the Google building.

MailOnline has contacted Google for a comment. 

As the camera pans towards the building, a crackle of static electricity is heard and Nick shouts: ‘Oh my god, can you hear that?’, before the video cuts out.

‘Initially it didn't hurts us, just surprised us,’ Mr Legrand wrote online.

‘Then it seemed to intensify and my phone started crackling and the video cut.

'My friend got a strong electric shock from holding my phone up high.’

Static electricity occurs when there is an imbalance between the positive and negative charges in an object.

These charges can build up on the surface of an object, until they find a way to be released or discharged.

When certain materials rub against each other, it can transfer electrons and create this charge - although it is not known what caused the electrical build-up to occur around the Google building.

Google declined to comment.

The strange field was first discovered by Reddit user master_poop earlier this year. 

He wrote that that since experiencing the phenomenon, he had suffered from toothache and nosebleeds.

This led to theories that there was a problem with wiring buried beneath the spot at which the field had been felt, but UK Power Networks investigated the issue and announced the area was safe. 

It is also thought that the design of the building, and its network of metal poles that rub together, could be generating the static field. 

 

 

 

@highlight

Video was filmed outside Google’s London offices in St Giles High Street

@highlight

In the clip, Simon Legrand is shown standing in front of the building

@highlight

As he enters the 'beam', hair is shown rising, silhouetted by a street lamp

@highlight

As the camera pans towards the building, a crackle of static is heard

@highlight

It is not known what caused the electrical build-up to occur

@highlight

Theories include a problem with wiring beneath the building, and electricity being generated as the building's metal poles rub together

@highlight

Google declined to comment