By
James Gordon

Google may tout itself as being a publicly responsible, green fingered, all-things-good company that touts green technology, but the companies chief executives are not setting a good example from on high.In fact, it would appear they're flying high whilst American taxpayers foot the bill.

Despite lobbying the federal government on environmental policy, Sergey Brin, Larry Page, and Eric Schmidt have put 3.4 million miles on their private jets in recent years, polluting the atmosphere with 100 million pounds of carbon dioxide according to The Blaze.

Forget using Google Hangouts to conduct business, the execs prefer the old-fashioned method of face-to-face communication. Often, they'll take a trip on one of the enormous corporate fuel-guzzling 757 or 767 aircraft or the more exclusive Gulfstream V at a moments notice – and sometimes to the most exotic of vacation destinations.

Hypocritical: The company extol the virtues of greener living but it also appears that Google are happy to travel at the expense of taxpayers in gas-guzzling jets

Racking up the airlmiles: Googl;e owns several aircraft including this Gulfstream V private jet

We only pay this much: Executive Chairman of Google Eric Schmidt is one of the lucky Google employees who has a fleet of aircraft at his disposal. Better yet, the fuel is also far cheaper than anyone else pays thanks to taxpayers

Their trips have been analyzed and logged and show that despite trying to convince federal lawmakers to introduce stringent and restrictive environmental regulations, they happily jet off using gallons of polluting aviation fuel.

It might not be such a big deal if Google would practice what it preaches. The search engine powerhouse has been a leading proponent of encouraging the federal government to, as the company says, ‘put a price on carbon through cap-and-trade or a carbon tax.’

Through has introduced its own Google Green Initiative as well as a Clean Energy 2030 proposal to wean the U.S. off its reliance on fossil fuels.

Google wishes to transform the economy from one running on fossil fuels to one largely based on clean energy.

They’re happy to talk about building whole new industries and creating millions of new jobs along with cutting energy costs both at the gas pump and at home. Could it be that this is nothing more than hot-air in an effort to maintain its hip image?

Gas-guzzler: Google even owns 767 and 757 jets such as this one. Their trips, according to flight log data analyzed, included single-day jaunts and brief corporate meetings, but also what appear to be hundreds of exotic vacation destinations

The Blaze claim that when a company attempts to manipulate the government into using environmental policies to determine what types of cars Americans can drive, what kinds of jobs Americans can have and how taxpayers’ hard-earned dollars are spent, it should at least be unerring in its commitment to the environment.

Drew Johnson, a fellow at the Center for Individual Freedom has been looking through the hours and hours of flying time generated by Google’s Sergey Brin, Larry Page, and Eric Schmidt.

Google maintains a hangar of jets ready to take to the air at a moments’ notice.

In total, according to flight data that was analyzed, Google executives have flown more than 3.4 million miles, burning an average of 100,000 gallons of fuel every month in recent years.

Google’s planes burned through nearly 59 million barrels of crude since 2007, much of it on non-essential trips to adult playgrounds Nantucket, Aspen, Costa Rica, St. Maarten, Hawaii, Bermuda and Tahiti.

The supposedly environmentally conscious company’s jets have emitted more than 100 million pounds of carbon dioxide over the last four years alone.

Google co-founder Sergey Brin: Brin, Larry Page, and Eric Schmidt have put 3.4 million miles on their private jets in recent years, polluting the atmosphere with 100 million pounds of carbon dioxide

No wonder he's smiling: Larry Page, Google co-founder and CEO  uses campaign contributions to strong-arm federal lawmakers into hamstringing everyone else with restrictive environmental regulations

It even appears that Google is hand-in-glove with the government.

Google has snagged a few favors along the way and has been getting preferential rent when it comes to housing their collection of gigantic jets.

Since 2007, the private airplane fleet owned by Google execs has been housed in a hangar at NASA’s Ames Research Center just outside Google’s Mountain View, California HQ.

The hangars are funded by the taxpayer and are supposed to be for aircraft conducting scientific research for NASA.

The government is even allowing Google to fill itself up with jet fuel at a cut price deal – again, thanks to U.S. taxpayers.

The fuel was of course meant for NASA and Department of Defense aircraft, but why fly somewhere else to fill up when you have it on tap?

Mr Johnson estimates that Google 
officials spent $29 million on jet fuel – a saving of around $10 
million. But what is $10 million to a company that has generated $60 
billion in revenue over the past few years?

It should come as no surprise that as a result of Google’s involvement with the government and securing their cheap and exclusive parking space and fuel s for the company’s jets, Google also happens to be among the largest contributors to political campaigns in the United States.

Almost a million dollars was given to President Obama’s campaign in 2008 with a similar amount in 2012.

Not practicing what they preach: While Google encourages government to limit carbon emissions for the rest of the American economy, company VIPs are zooming through the skies, polluting their way to the exotic playgrounds of the rich and famous

Mr Johnson claims that ‘by pushing strict ‘climate change’ policy on everyone else, while polluting up a storm themselves. ‘ Google reaches levels of hypocrisy not seen since I uncovered the inconvenient truth about frenzied environmentalist Al Gore, who devours about 20 times more electricity in his mansion than the average American family uses in their home over the course of a year.’ Incidentally, Mr Gore has been an company has had plenty of time to learn directly from the discredited environmental prophet, whom they have paid handsomely to serve as a ‘senior adviser‘ since 2001.’

As Google continues to extol the virtues of environmental purity and encourage the government to limit carbon emissions for the rest of the American economy, its own company VIPs are busy zooming around, polluting the skies as they go on travel subsidized by American taxpayers.

Perhaps Google should begin by Googlingthe word ‘Hypocrites’?

@highlight

Google execs have traveled millions of miles to playgrounds of the rich and famous

@highlight

Several trips on company jets were to Washington D.C.

@highlight

Planes are filled up with government-subsidized fuel and even get to park cheaply

@highlight

Company maintains a green image yet does not practice what it preaches