By
Sarah Griffiths

Sat-navs are not much use if you want to take a scenic walk around an unfamiliar city at the weekend.

While they may be good for getting from A to B in a hurry, the technology is unhelpful at selecting the prettiest routes, which may be of interest if you are not in so much of a rush.

But Yahoo is working on an aesthetically-focused solution and is creating an algorithm that can pick out the most beautiful and pleasurable routes, initially based upon the views of locals.

Yahoo is creating an algorithm that can pick out the most beautiful and happy of routes, based upon the views of locals. The map on the left shows the most direct route from Euston Square to the Tate Modern, wheres the one on the right, generated by the new algorithm is longer, but more aesthetically pleasing

According to the crowd-sourced exercise, Londoners consider these eight places the most beautiful in the capital.

Daniele Quercia, of Yahoo Labs, Barcelona, wrote in a paper: ‘The goal of this work is to automatically suggest routes that are not only short but also emotionally pleasant.’

In order to create the scenic route algorithm, the computer scientists collected images from Google Street View and Geograph to create a database for central London, Gizmodo reported.

They then asked 3,300 Londoners how pleasant the places and neighbourhoods were relative to each other. Users saw two places side by side and chose which one was more attractive.

‘We arranged those locations into a graph upon which we learned pleasant routes,’ Ms Quercia wrote.

The team used the results to make heat maps of beautiful parts of London and generated an algorithm to plot the most attractive routes for people to walk along.

The algorithm does this by searching through suggested routes from one location to another, manipulating the path to choose the most attractive roads.

The computer scientists used crow sourced results to make heat maps of beautiful parts of London - including Millennium Bridge (pictured left) and Covent Garden (right) from which they generated an algorithm to plot the most attractive routes for people to walk along

The researchers said that routes tend to be 12 per cent longer than the shortest paths.

When 30 volunteers tested their ‘attractive’ routes, they confirmed that they were indeed more aesthetically pleasing.

‘Based on a quantitative validation, we find that, compared to the shortest routes, the recommended ones add just a few extra walking minutes and are indeed perceived to be more beautiful, quiet and happy,’ they wrote.

To test and build on the idea, the computer scientists then examined almost four million images on Flickr taken in specific London locations that they had already mapped, to understand what is considered beautiful.

Knocking out the crowd-sourcing element of the process, the repeated the Flickr process to made a new map of central Boston, pinpointing beauty hotspots and routes.

Volunteers who tried them out confirmed that they were more scenic than the most direct routes offered by other software, such as on sat-navs.

While one person’s idea of beauty may differ from another, the computer scientists hope to develop an app exploiting their algorithm soon.

@highlight

Computer scientists in Barcelona aimed to create an algorithm suggesting routes in London that are 'not only short but also emotionally pleasant'

@highlight

They asked over 3,000 people to choose the prettiest places in London from a collection of shots from Google Street View

@highlight

From this they created a database and graphs to make the algorithm capable of selecting the most scenic routes

@highlight

The researchers said routes tend to be 12% longer than the shortest paths