By
Eddie Wrenn

A 100 kilometre-wide crater has been found in Greenland, the
result of a massive asteroid impact a billion years before any other
known collision on Earth.

The previously oldest known crater on Earth formed two billion years ago
and the chances of finding an even older impact were thought to be
astronomically low.

Now, a team of scientists from the Geological Survey of
Denmark and Greenland (GEUS) in Copenhagen, Cardiff University in Wales, Lund
University in Sweden and the Institute of Planetary Science in Moscow has upset
these odds.

Explosive: This simulated image shows how the impact would have looked - it would have wiped out all forms of higher life if it happened later in Earth's history

Hidden in the runes: Evidence came in the form of broken-up, contorted, melted and hydrothermally altered rocks affected by the impact and influx of sea-water during the impact

The spectacular craters on the Moon formed from impacts with
asteroids and comets betweenthree3 and four billion years ago.

The early Earth, with
its far greater gravitational mass, must have experienced even more collisions
at this time - but the evidence has been eroded away or covered by younger
rocks.

Following a detailed programme of fieldwork, funded by GEUS and the
Danish ‘Carlsbergfondet’ (Carlsberg Foundation), the team have discovered the
remains of a giant three billion-year-old impact near the Maniitsoq region of West
Greenland.

'This single discovery means that we can study the
effects of cratering on the Earth nearly a billion years further back in time
than was possible before,” according to Dr Iain McDonald of Cardiff
University’s School of Earth and Ocean Sciences, who was part of the team.

It is possible or even likely that the meteorite hit the sea, for the
 preserved rocks have been intensely altered by circulating hot aqueus 
fluids. These fluids were likely derived from sea water that would have 
been able to penetrate deep into the Earth's crust through the numerous 
fissures and crush zones generated by the impact.

Boris A. Ivanov at the Institute of Planetary Science, Russian Academy of Science, Moscow, has carried out a series of provisional model calculations, which suggest that the impacting meteorite at Maniitsoq may have had a diameter of more than 30 km, i.e., about twice the size of the Vredefort meteorite and with a mass about ten times larger.

If this meteorite had hit the Moon, the final crater structure would have had a diameter well above 1000km and easily visible from Earth. However, due to the much stronger gravity of our planet, the Maniitsoq structure may have had a diameter of 'only' some 500-600km

Clues: Finnefjeld mountain, which is around 1050m high, is believed to be the crushed core of the structure

The dull grey rocks were crushed to fine powder by the impact, and then cut by white melt sheets

Making an impact: The asteroid is believed to have hit close to where the town of Maniitsoq in Greenland

If an impact of this size hit the Earth today, it would not only be 
able to pulverise a medium-sized national state but its global effects 
would also kill all higher life.

Then, three billion years ago, there was not
 much life to extinguish, but as yet no depositional rocks of matching 
age have yet been identified that could enlighten the effects of the 
Maniitsoq impact such as extreme tsunamis, deposition of re-condensated 
atmospheric glass particles from the evaporated meteorite or other signs
 of global atmospheric and marine effects.

Finding the evidence was made all the harder because there
is no obvious bowl-shaped crater left to find. Over the three billion years since
the impact, the land has been eroded down to expose deeper crust 25km below
the original surface.

All external parts of the impact structure have been
removed, but the effects of the intense impact shock wave penetrated deep into
the crust - far deeper than at any other known crater - and these remain
visible.

However, because the effects of impact at these depths have
never been observed before it has taken nearly three years of painstaking work
to assemble all the key evidence.

If you look at the Moon on a clear night through a pair of ordinary, 
hand-held binoculars, you'll see a multitude of meteorite craters.

Some are larger than 1000 km in diameter and readily visible with the naked eye.

Through the first 500 million years of Solar System history, both the
 Moon and the Earth were constantly bombarded with a multitude of small 
and large meteorites and comets.

Some scientists even think that life was brought to the Earth by comets.

The Moon has preserved the remains of thousands of impacts, but on 
Earth only about 180 such impact structures are known, and most of them 
are very small, young and repidly decaying.

Contrary to the Moon, the Earth is a dynamic planet with plate 
tectonics, mountain belts and erosion, which means that most impact 
structures are eroded away, destroyed by mountain building processes or 
buried by younger deposits over geological time.

Until recently, the 2.02 billion years old and 300 km wide Vredefort 
crater in South Africa was considered to be both the oldest and largest 
impact structure on Earth.

It is estimated that the impacting meteorite had a diameter of about 
15 km. During the development of the final crater structure, a 
kilometre-thick layer of sedimentary rocks containing the World's 
largest gold deposits collapsed into the cavity excavated by the 
meteorite and in this way became protected from erosion and preserved 
until today.

Also the second largest impact structure on Earth, the 1.85 billion 
years old Sudbury crater in Canada, hosts world-class mineral deposits -
 in this case nickel-rich minerals that were melted and concentrated by 
the extreme heating caused by the impact.

'The process was rather like a Sherlock
Holmes story,' said Dr McDonald. 'We eliminated the impossible in
terms of any conventional terrestrial processes, and were left with a giant
impact as the only explanation for all of the facts.'

Only around 180 impact craters have ever been discovered on
Earth and around 30 per cent of them contain important natural resources of minerals or
oil and gas. The largest and oldest known crater prior to this study, the 300
kilometre wide Vredefort crater in South Africa, is 2 billion years in age and
heavily eroded.

Dr McDonald added that 'It has taken us nearly three
years to convince our peers in the scientific community of this but the mining
industry was far more receptive. A Canadian exploration company has been using
the impact model to explore for deposits of nickel and platinum metals at
Maniitsoq since the autumn of 2011.'

The international team was led by Adam A. Garde, senior
research scientist at GEUS. The first scientific paper documenting the
discovery has just been published in the journal ‘Earth and Planetary Science
Letters’.

@highlight

100km (62mile) wide crater discovered in Greenland - and it is possible crater is more than 500km in size

@highlight

The research was supported by the Carlsberg Foundation.