By 
Ray Massey

PUBLISHED:

18:01 EST, 24 June 2013


| 

UPDATED:

18:06 EST, 24 June 2013

British holidaymakers have made the country the cruise capital of Europe, a report reveals today.

Some 1.7million UK passengers took to the waves last year and spent nearly £2.5billion, a report reveals today.

The growing passenger numbers mean Britain is Europe’s biggest cruise market with a 27.7 per cent share, compared to 22.5 per cent in Germany and 14.9 per cent  in Italy.

Popular trip: Brits cruise more than any nation in Europe and make up more than a quarter of the market on the continent (file photo)

The report released by the Cruise Lines International Association (CLIA) says: ‘The British cruise industry continued to grow strongly in 2012 creating more employment opportunities and increasing its economic contribution to the UK.’

The cruise industry’s direct expenditure in the UK last year was £2.49 billion - an increase of 3.7 per cent on 2011.

Cruising was given a boost earlier this month when the Duchess of Cambridge launched the Royal Princess cruise liner in Southampton on her last solo public appearance before the birth of her first child next month.

The fair wind comes despite the bad publicity generated by the partial sinking of the Costa Concordia in 2012 and several outbreaks of norovirus.

Boost for business: Catherine, Duchess of Cambridge smiles after naming a Princess Cruises ship 'Royal Princess' earlier this month

Royal approval: The Duchess of Cambridge's 'seal of approval' has seen an increase in cruise sales

European passenger numbers totalled 6.1 million and the global figure was 20.9 million passengers.

Southampton’s importance to the European cruise market also increased with more than 1.5 million passengers passing through, making it Europe’s largest embarkation and disembarkation port.

More than 11,000 jobs across the South-East of England are supported by the port and each cruise ship turnaround is estimated to contribute around £2.5 million to the local economy.

Southampton is one of 19 ports in the UK and Ireland that now offer cruise ship departures.

High numbers: About 1.7million Britons went on a cruise last year, spending nearly £2.5billion

The number of British jobs supported by the cruise industry continued to grow too with 66,059 people employed – an increase of 2,000 jobs or 3.5 per cent, and now representing 20 per cent of the total number of jobs the industry provides Europe-wide.

The industry’s contribution to the economies of Europe was also up - 3.4 per cent to £13.15 billion - with the UK economy one of the top three recipients, after Italy and Germany.

The overall contribution of the cruise industry, including indirect expenditure, to the European economy grew 2.9 per cent to £32.19 billion.

Andy Harmer, director of CLIA UK & Ireland, said: ‘These figures demonstrate the continued and growing strength of the British cruise market.

‘The cruise industry is a significant growth vehicle for the UK economy.’

@highlight

Britons cruise more than any other European country spending £2.25bn

@highlight

UK travellers make up more than a quarter of the cruise market