An unmanned Atlas
rocket blasted off from Florida on Thursday with a quartet of
NASA science satellites designed to map explosions triggered by
criss-crossing magnetic fields around the Earth.

The 20-story-tall rocket, built and launched by United
Launch Alliance, a partnership of Lockheed Martin and
Boeing, lifted off from Cape Canaveral Air Force Station
at 10:44 p.m. EDT (0244 GMT on Friday).

Perched atop the rocket were four identical satellites
designed to fly in a pyramid formation high around Earth.

Scroll down for video... 

3-2-1! NASA has launched four identical spacecraft on a billion-dollar mission to study the explosive give-and-take of the Earth and sun's magnetic fields

We have liftoff! An unmanned Atlas rocket blasted off Thursday night from Cape Canaveral, Florida, carrying NASA's Magnetospheric Multiscale spacecraft

Up, up and away! The observatories will be placed into an oblong orbit stretching tens of thousands of miles into the magnetosphere

Each satellite is equipped with 25 sensors to record in
split-second detail what happens when the planet's magnetic
field lines break apart and reconnect. Data from the four probes
will be combined to produce three-dimensional maps of the
process.

Magnetic reconnection, as the phenomenon is known, is
commonplace throughout the universe, but poorly understood.

Magnetic fields are generated by planets, stars, galaxies,
black holes and other celestial objects. When field lines snap
apart and reconnect, charged particles are sent soaring into
space at nearly the speed of light, roughly 186,000 miles per
second.

On the sun, magnetic reconnection unleashes solar flares,
each as powerful as 1 million atomic bombs. Such solar activity
can trigger magnetic storms and aurora displays on Earth.

Mission space: They will fly in pyramid formation to provide 3-D views of magnetic reconnection on the smallest of scales

New frontiers: Magnetic reconnection is what happens when magnetic fields come together, break apart, then come together again, releasing vast energy

NASA is spending about $1.1 billion on the project, known as
Magnetospheric Multiscale, or MMS, in an effort to understand
how the energy is generated and released. 

The satellites will
fly directly into reconnection zones 44,000 to 95,000 miles above Earth and map what happens when
magnetic field lines realign.

"The MMS mission will conduct a definitive experiment in
space that will finally allow us to understand how magnetic
reconnection works," lead researcher Jim Burch, from the
Southwest Research Institute in San Antonio, Texas, told
reporters at a pre-launch press conference.

The research may have some practical spinoffs as well.
Efforts to harness nuclear fusion in laboratories have been
stymied by magnetic reconnection, which causes temperatures to
drop in the fusion chambers.

It also may help forecasters predict dangerous solar storms,
which can knock out power grids on Earth and disrupt radio, GPS
and satellite signals.

The mission is designed to last two years.

Science: The process of magnetic reconnection drives the aurora, as well as potentially disruptive solar storms

@highlight

NASA has launched four satellites in a $1.1 billion mission to study the high-speed interactions between Earth's magnetic field and the sun

@highlight

Magnetic discharges drive auroras and play havoc with satellite navigation, communications and power grids

@highlight

The hard-to-study mechanism underlying space weather is known as magnetic reconnection

@highlight

Atlas 5 rocket was carrying four satellites

@highlight

When in space, all four will be arranged in a pyramid formation, flying within about 6 miles of one anoter