Whether it's a UNESCO Heritage site or a small market town in the Cotswolds, all it takes is several minutes of screen time for a location to rise to prominence - and, subsequently, experience a significant boost from TV-watching tourists.

In fact, recent research shows just how powerful the silver screen effect really is, estimating that international tourism brought in between £100 and £140 million for the English economy with tourist treks to recognisable countryside locations around Britain accounting for the bulk of the revenue.

In honour of the newly-coined 'set-jetting' phenomenon, MailOnline Travel is counting down its top ten as-seen-on-screen locations for film-loving tourists to explore...

Scroll down for video 

ITV's drama, Broadchurch, is set on the Jurassic Coast in Dorset, an area which has seen increased tourist interest in recent years

Searches for West Bay in Bridport were up 161 per cent in 2015 following the series' January 5 premiere, according to Hotels.com

West Bay, Bridport, Dorset

ITV's hit drama, Broadchurch, has contributed to a great deal of interest in the west country, in particular the area of West Bay.

In fact, just days following the series' January 5 premiere, Hotels.com saw a spike in searches for the area with Bridport up by 161 per cent compared to the same period the year before.

The harbour and the town are also used as filming locations, but its the Jurassic coast, a World Heritage site, that has most benefitted from this 'set-jetting' phenomenon.

Matthew Goode, who played Charles Ryder in the remake of Brideshead Revisited, is seen here outside Castle Howard in North Yorkshire

The iconic home has served as the backdrop for a wide range of productions, but is perhaps best known for its appearance in the 2008 film

Castle Howard, North Yorkshire

The stately home has served as the backdrop for a wide range of film and television productions, but is perhaps best known for its starring role in Brideshead Revisited.

Following the success of the 80s television programme of the same name, Hollywood returned to Castle Howard to film the 2008 feature film remake, starring Ben Whishaw, Matthew Goode and Emma Thompson.

Inside, The Long Gallery, The Great Hall, and Grand Staircase all featured prominently and visitors to the house can still peruse the Brideshead Exhibition on display to see exactly how the transformations took place.

Students and fans flock to Oxford's Christ Church College and Bodleian Library to see where several pivotal Harry Potter moments were filmed

Christ Church's Great Hall dining room, which sees a huge amount of yearly visitors, was replicated in the film studios to create Hogwarts Hall

Oxford University, Oxfordshire

Students and Harry Potter fans alike flock to Oxford University's Christ Church College and the school's Bodleian Library where pivotal scenes from the franchise were filmed.

Perhaps most noteworthy in the College's Great Hall dining room, which was replicated in the film studios to create Hogwarts Hall, and the Grand Staircase, was used as the arrival scene for new Hogwarts students in the first two films.

And life imitated art once more in 2011 when then-university student Emma Watson, who played Hermione in the films, completed a study abroad year at the prestigious university.

According to the BBC, thanks in large part to the Harry Potter films, Oxford University has seen tourist numbers rising steadily, particularly in 2012, when numbers were up by 50,000 guests from three years prior. 

Allen Leech, pictured here, is often spotted filming scenes in Bampton, Oxfordshire, as part of his hit period drama, Downton Abbey

St. Mary's Church and the old market village's library are most often seen in the series, acting as the entrance to the cottage hospital

Bampton, Oxfordshire 

The market town of Bampton, located in south of the Cotswolds, has most recently served as a filming location for the widely popular television programme Downton Abbey, selected due to its many 17th and 18th century houses and inns.

One of the oldest towns in England, it makes perfect sense that the period drama would select such a location to add authenticity to the production.

According to a survey compiled by Creative England, which measured the impact of tourism revenue generated by famous locations, Bampton was one of the best performing, with fan-led day visit spends topping £2.7 million in 2014.

While Highclere Castle in Hampshire was used for exterior shots of the home, many of the outdoor scenes are filmed in Bampton, most notably at the village's St. Mary's Church and the library, which was used as the entrance to the cottage hospital.

Doctor Who stars Peter Capaldi and Jenna Coleman made an appearance at Cardiff Castle in Wales as part of the series' World Tour

The castle has featured prominently in the science fiction TV show since 2005 and several tours are available to tourists in the area

Cardiff Castle, Wales

The stunning castle has featured prominently in Doctor Who since 2005 and, as such, played host to a photo call for the television programme in 2014.

In fact, for the eighth series premiere, the Tardis itself even made an appearance at the top of Cardiff Castle ahead of the science fiction screening that evening.

And VisitWales has taken advantage of the visitor interest in the area following the recent success of the revived series, launching a four-hour Doctor Who Tour that takes in over 20 locations in and around Cardiff.

The setting of Disney's hit animated film, Brave, was inspired by Dunnottar Castle, located in Aberdeenshire, Scotland

The ruins of the medieval castle are located on a remote cliff and are believed to have generated £120 million in tourism revenue since 2012

Dunnottar Castle, Stonehaven, Scotland

This real-life relic was the inspiration behind the location of Disney's animated epic, Brave, which told the story of courageous Merida, a Scottish princess struggling to find her own path in life.

The ruins of the medieval castle are located on a remote cliff, accessible only by several winding staircases and bridges, in Aberdeenshire, Scotland, near the town of Stonehaven.

According to VisitScotland, thanks in large part to a joint marketing campaign with Disney, the castle has generated £120 million for the Scottish economy, experiencing a 16 per cent increase in visitor numbers following the film's 2012 release.

Actor Alfie Allan, who played Theon Greyjoy on Game of Thrones, filmed near the Giant's Causeway in Northern Ireland during season two

The unique rock formation, located in Antrim County, has been attracting visitors for years, but has experienced a recent surge thanks to HBO

The Giant's Causeway, Antrim, Northern Ireland

The gorgeous Causeway Coast of Northern Ireland is home to several key Game of Thrones filming locations. 

A unique rock formation, the Causeway has been attracting visitors to the Antrim Coastline for centuries, and now, with the popularity of the HBO TV series, the location has experienced even more of a tourist boom. 

Ballinroy,  which is located about 15 minutes from the Causeway stands in for the town of Pyke in the series, is clearly visible in the second season scenes during which Theon decides to leave his coastal hometown.

From Belfast, fans can choose from a variety of Game of Thrones-themed tours to explore the many castles and beaches in the region. 

Anna Kendrick (pictured) stars at Cinderella in this year's movie musical, Into the Woods, also featuring Meryl Streep and Chris Pine

Dover Castle in Kent, including its magnificent Great Tower, provided the setting for any scenes of the King's Palace in Into the Woods

Dover Castle, Kent

As a filming location for blockbusters such as Into the Woods, Wolf Hall, and Hollow Crown, Dover Castle in Kent has similarly experienced the benefits of a tourism boom.

Starring Meryl Streep, Anna Kendrick and Chris Pine, Into the Woods utilised the magnificent Great Tower and Inner Bailey walls for scenes that were set at 'the King's Palace.' 

Taking advantage of interest in the region, this year, English Heritage began offering special themed guided tours of the real-life fairy tale castle.

Tom Hanks starred in the 2006's film, The Da Vinci Code, which was based on the best-selling novel of the same name

The 900-year-old Lincoln Cathedral in Lincolnshire stood in for London's Westminster Abbey, in particular its cloisters and chapter house

Lincoln Cathedral, Lincolnshire

The 900-year-old church is Lincolnshire's largest building and served as a pivotal filming location for the 2006 film, The Da Vinci Code, which was based on the novel of the same name.

And according to the BBC at the time, it was believed that the Lincoln Cathedral had generated a substantial amount of extra revenue thanks to the visitors attracted by the Tom Hanks hit. 

The cloisters, as well as the cathedral's chapter house, stood in for London's Westminster Abbey and it is estimated that the church, which costs £3 million per year to run, received £250,000 in return for filming.

Miss Potter, the semi-biographical film about children's writer, Beatrix Potter, stars Renee Zellweger and Ewan McGregor

Since Potter lived in the Lake District in North West England, the crew filmed extensively in the region with the help of the National Trust

The Lake District, North West England

Miss Potter, the semi-biographical film about beloved children's writer, Beatrix Potter, and which stars Renee Zellweger and Ewan McGregor, was filmed on location in Potter's old stomping grounds: The Lake District in North England.

The National Trust was actively involved in location scouting, as Potter's 17th century farmhouse, Hill Top, was simply to fragile to use. 

As such, filming, which took place in 2006, focused in on other sites such as Yew Tree Farm, Loughrigg Terrace and Tarn, and Loweswater.

Today, GoLakes.co.uk offers a handy location map to help visitors make the most of their self-led tours. 

 

@highlight

Thanks to ITV's hit drama Broadchurch, Bridport in Dorset has experienced a surge in tourist interest in the area

@highlight

Bampton, Oxfordshire, which features prominently in Downton Abbey, brought in an estimated £2.7 million in 2014

@highlight

This year, Dover Castle in Kent, began offering themed tours, after being used in the hit film, Into the Woods 