By
Sarah Griffiths for MailOnline

Whale song, wolf howls, frog croaks and bird chirps are complex forms of communication - just like human speech, according to new research.

These creatures may not be able to master advanced language techniques, but their unique calls are much more than just random noises, a study shows.

The 'speech' of seven different species of birds and mammals found they appear to be generated by processes similar to how we speak.

Monkey business: Oranguatans may not be able to master advanced language techniques, but their unique calls are much more than just random noises, a study shows

The mockingbird, for example, can mimic more than 100 distinct song types of different species, and the long string of wails and snorts of the from a rock hyrax - a type of badger - signify male territory.

The study 
suggests there may be a ‘missing link’ on the path from animal 
communication to human language that has not yet been found.

‘Multiple
 studies are finding more and more stepping stones that seem to bridge 
this gap,’ said Dr Arik Kershenbaum, from the National Institute for 
Mathematical and Biological Synthesis in Knoxville, Tennessee.

Dr Kershenbaum said uncovering the process could help scientists understand the origin of human language.

Love birds: Scientists conducting the study looked for evidence of Markovian noises in the noises made by seven creatures - chickadees, finches (pictured), bats, orangutans, killer whales, pilot whales, and hyraxes

But while the vocalisations suggest language-like characteristics, scientists have found it difficult to figure out the complexity.

Typically, they have assumed the sequence of animal calls is generated by a simple event called a ‘Markov process’, named after a Russian mathematician eighty years ago, which is dependent on what happened last.

Earlier
 this year a BBC documentary called ‘Talk To The Animals’ investigated 
how creatures, ranging from fireflies to hippos, talk to one another.

Presenter
 Lucy Cooke, an Oxford zoologist, said: ‘Ever since I was a kid I have 
longed to be a real life Dr Doolittle and talk to animals. I think it is
 something we would all love to be able to do.’

She
 believes that communication is key to understanding the secret lives of
 animals and said that huge scientific advances have been made in 
cracking this animal code in recent years.

‘I
 roared, croaked, squeaked and bellowed my way across three continents 
to talk with creatures great and small; from flirting with fireflies to 
saying hello in hippo,’ she said.

‘I
 was blown away by how sophisticated animal speak is. I discovered that 
dolphins have names, horses know who their friends are and I even met a 
bird that speaks meerkat.

‘And then there were the chimpanzees with a language so similar to ours it gave me goose bumps to watch.’

Animal calls are said to be restricted by rigid Markovian rules of ‘regular’ grammar that have a set sequence.

Human language, in contrast, uses what are called ‘context-free grammars’ that apply the same set of rules in different ways, making it much less predictable.

Scientists conducting the study looked for evidence of Markovian noises in the noises made by seven creatures - chickadees, finches, bats, orangutans, killer whales, pilot whales, and hyraxes.

They found little evidence of Markovian processes in animal calls. Instead, the sounds made by animals were more like human language.

The findings suggests there may be an intermediate step on the evolutionary path between the regular grammar of animal communication and the context-free grammar of the human form that has not yet been identified and explored. Pictured are a family of hyraxes, a species included in the study

 

@highlight

Bird song and bat calls are complex forms of communication, study claims

@highlight

Scientists from in Knoxville, Tennessee, say the noises are not random

@highlight

They say there may be a ‘missing link’ on the evolutionary path from animal communication to human language that has not yet been identified

@highlight

Experts previously assumed that animal sounds involved a simple structural system known as the 'Markov' process