Ronny Deila’s knowledge of Glasgow’s most emotive derby has been gleaned by proxy. From the tales, glories and disappointments of the men by his side. From snatched clips on YouTube.

The first manager of Celtic ever to have gone seven months in the job without playing Rangers, his inexperience has so far been tolerated. Indulged even. That won’t last if he notches up another landmark by becoming the first Parkhead manager ever to lose to a lower-league Ibrox outfit.

A League Cup semi-final at Hampden offers no margin for error. By his own admission, Deila has been forced to bone up on the meaty side of his Glasgow induction through the anecdotes of his backroom lieutenants.

Ronny Deila (left) poses with the Scottish League Cup alongside Rangers manager Kenny McDowall (right)

Deila wants the Old Firm derby to pass without trouble between Celtic and Rangers supporters

‘I have John Collins and John Kennedy around me who have played in these games before,’ said the former Stromsgodset coach.

‘I have heard about Collins’ free-kick (when Celtic won 2-0 at Ibrox in 1994) and everything. The whole club is thinking and talking about it, so I have some idea what it is.

‘I have also watched a couple of games from before to get a little bit of feeling about the atmosphere. It is going to be a big day.’

It’s hardly unheard of for an Old Firm managerial debutant to have no previous experience of the fixture on his CV.

Neither Martin O’Neill or Dick Advocaat had played for either Celtic or Rangers. Both won a domestic treble in their first seasons in charge.

Gordon Strachan had witnessed many Glasgow derbies, but found his inexperience of playing one no barrier to winning trophies.

Experience of playing in the fixture, then, is not essential. Neither can anyone say for certain that it even matters. 

Deila (left) and McDowall (second left) pose with Derek McInnes (second right) and Jackie McNamara (right)

‘It’s very hard to say,’ shrugged Deila. ‘But I have experienced big matches before. I have fought for trophies before and it’s the same problems you encounter going into them all.

‘I know how to cope with the pressure and that’s the most important thing.’

Predicting how a manager or player will fare in his first Old Firm game is largely pointless. O’Neill won his first derby 6-2. England icon Paul Gascoigne turned in a virtuoso display in a 2-1 Rangers win at Parkhead, while Lubo Moravcik’s debut in a 5-1 win is still regaled by Celtic fans.

None of that exalted trio had ever sampled the white-hot heat generated by the game before, but found their ignorance a form of bliss.

Deila, nevertheless, will leave nothing to chance. The key to winning his first Old Firm game, he believes, could lie in his right-hand men Collins and Kennedy.

‘That’s vital,’ conceded the Celtic boss. ‘I am so happy to have staff who know Scottish football.

‘That not only helps me in this situation, but through the whole season.

‘I didn’t know much about the other teams, the players and culture.

‘It’s much easier to get it when you have other people next to you.’

John Barnes had Kenny Dalglish, of course. Jozef Venglos had Eric Black. It did neither man much good in the end.

Deila celebrates in front of Celtic fans after victory over Ross County last weekend in the Scottish league

The Norwegian was compared unflatteringly - unfairly - to Barnes in his early months. They are more forgiving now, but no one is comparing to him to an O’Neill or Strachan just yet and it may be some time before they do. Sunday and his first Rangers win would be a decent foundation.

Collins and Kennedy are not his only points of reference. Scott Brown, Mikael Lustig, Kris Commons, Adam Matthews, Emilio Izaguirre, Anthony Stokes and the injured Charlie Mulgrew have all sampled the fixture. Deila will make a point of speaking to them all.

‘We are a team, the staff and me and the players,’ he continued. ‘I have spoken to them a lot, not only this week but all the time. Good communication is important.

‘I think this game is going to be much louder than I am used to but that is why I am managing. You train out in the cold 50 per cent of the time because you are looking forward to these days.

‘I don’t think it is going to be too emotional before the game, because you so concentrated on what you are going to do.

‘But hopefully if we have a good result it is easier to enjoy the feelings and the emotions.

‘Football is not always fun when you play, but it is fun afterwards. Everything you have seen and experienced you can then take it in and I think it will be a great experience.’

It’s only fun after a victory, of course. Even then, the prevailing, dominant emotion is relief. The fear of defeat has always trumped the joy of victory when Celtic and Rangers meet. 

Deila wants his team to consider the FA Cup shocks in England to make sure they avoid complacency

For the Scottish champions, there is an additional pressure borne of their tag as overwhelming favourites. They are expected to not only win but to win well.

‘It is something extra because it is a derby and you want to win the city,’ Deila added. ‘It is a bigger match than a normal semi-final.

‘I understand the expectations and you all understand my expectations, as well.

‘But this is not the first time in my life there is an expectation to win. It is how you handle that which is the most important thing.’

Discipline - on the field as much as off - will be key. In any given press conference, Deila will use the word ‘energy’ three or four times, sometimes more.

His key message to his players is to ignore the negative, sometimes ugly and abrasive energy from the stands and the hype generated by the game and keep it for where it matters. On a football pitch.

In the coming days, Celtic players will be urged to don blinkers and shut out the nonsense around them.

Leading by example, Deila said: ‘I haven’t met anyone. I have been in Lennoxtown the whole week. But I know where I can go and where I should go.

‘I know the expectations and want to save my energy for Sunday. You have to choose yourself where you go and what you do.

‘That’s what I said to them the first day I met them. We talk about it all the time.

‘Use your energy for something you can actually do something about.’

 

@highlight

Sunday's Celtic and Rangers Old Firm tie is the first in nearly three years

@highlight

They meet in the semi-final of the Scottish League Cup at Hampden Park

@highlight

Celtic manager Ronny Deila calls for calm between both sets of fans 