In the squalid Jacksonville dogfighting kennel, a champion named Bulletproof Sam sat in a makeshift wooden cage, his teeth exposed from a missing snout.

Nearby, an undercover agent with the sheriff's office met with Sam's breeder, a big-timer in the underground world of dogfighting named Willie Coleman, and made a deal that was caught on a hidden video camera.

Coleman - whose puppies other breeders nationwide sought for their prized bloodlines - was charged with 17 felony counts associated with dogfighting after that 2012 sting, and faced possible prison time.

A dog seized during the second-largest dog fighting bust in U.S. history sits in a pen at a kennel in Jacksonville, Fla.

It seemed like a sure win for investigators, who have gone after dogfighting with greater interest ever since NFL star Michael Vick pleaded guilty in 2007 to bankrolling a dogfighting ring and other charges, eventually serving 18 months in prison.

The three largest dogfighting busts in U.S. history have occurred since 2009.

But despite being banned in all 50 states and the momentum generated by the Vick case, the ancient blood sport is thriving in the underground, with hundreds of thousands of dollars at stake on big matches, police detectives and prosecutors said.

State laws still require no minimum mandatory jail time, so while arrests and convictions can be disruptive to dogfighting rings for a short while, the practice continues to flourish.

"Unfortunately, in our courts today, animal welfare is not given the attention and seriousness that it deserves," said Cyrus Zomorodian, the Jacksonville-based animal cruelty prosecutor who tried Coleman's case. "We constantly fight for more court time, resources and attention."

In 2013, after a three-year investigation that included local police and the FBI, more than 15 people were arrested, 367 dogs seized, $500,000 in cash, firearms and drugs were seized in Alabama, Georgia, Mississippi and Texas.

It was the second-largest dogfighting bust U.S. history, known as the '367 case.'

A few big federal busts like the 367 case that have occurred since Vick are rooting out some large fighting groups, the more investigators look for organized, professional level dogfighting, the more they're finding.

NFL star Michael Vick pleaded guilty in 2007 to bankrolling a dogfighting ring and other charges, eventually serving 18 months in prison

'This is a much bigger problem than people realize. Law enforcement is learning that there's an absurd amount of money involved,' said Officer Ivan Wick, a dogfighting investigator with the Milwaukee Police Department.

Wick, who worked with the FBI in April on a dogfighting bust that netted 12 suspects in Milwaukee, said investigations focused on a criminal group's dogfighting business can be more useful to detectives than following drug money.

'The criminal organization (in Milwaukee) was making more money from the dogfighting part of gang activities than from the drug trafficking part,' Wick said.

Authorities say dogfighting isn't a regional phenomenon: arrest data collected by The Humane Society of the U.S. since 2011 show hundreds of busts ranging from San Francisco to New York City, and in nearly every state.

"People believe it's happening in someone else's community," said Tim Rickey, of the ASPCA, who worked with law enforcement on the 367 bust. "There's not one kind of neighborhood or type of individual ... we've seen judges, a doctor, lawyers, nurses and firefighters all being involved in this."

Still, when there are arrests, prosecutors are often hamstrung by outdated laws once a case gets to the courts.

In Florida, where dogfighting arrests are routine, there is no minimum mandatory sentence for conviction.

The state's animal welfare law was written to protect livestock, so prison time is mandatory for the felony abuse of a horse or a cow, but not a dog.

Animal cruelty legal experts say the same is true in states throughout the nation, but note that there is progress in toughening laws.

In Florida, where dogfighting arrests are routine, there is no minimum mandatory sentence for conviction

For example, New York's animal protection laws are more than a century old, and also focus on the treatment of livestock, said Nassau County District Attorney Kathleen Rice.

Rice, who heads the state's district attorneys association, is advocating for a new law in Albany that would bring cruelty laws up to date and strengthen penalties.

'Prosecutors and the courts are hamstrung by laws that aren't just out of date but that don't treat crimes against animals like the serious crimes that they are. Not only does animal crime law in New York have little to no sentencing requirements, but it doesn't even allow the courts to count prior convictions in sentencing, essentially giving a free pass to repeat offenders,' Rice said.

Laws are slowly changing in other states to make prosecuting these cases easier, said Lora Dunn, a staff attorney at the Animal Legal Defense Fund in Portland, Oregon.

Seven states have added dogfighting to racketeering laws since Michael Vick's case in 2007, and in 2013 the federal government added a law to the Farm Bill that made attending a dogfight illegal.

Florida prosecutor Zomorodian wants increased penalties for animal fighting to help bring more successful cases, but says either way, the cases will always be difficult.

Even though Coleman, the dog breeder who faced 17 counts, and was well-known by advocates and dogfighters alike, he received no time behind bars.

His case was delayed for two years until August, when a judge taking into account Coleman's advanced age - he's now in his 70s - and lack of a significant prior record sentenced him to probation and set him free.

'Our victims don't have a voice and cannot testify as to what happened,' Zomorodian said.

 

@highlight

NFL star  Vick pleaded guilty in 2007 to bankrolling a dogfighting ring and other charges, eventually serving 18 months in prison

@highlight

The three largest dogfighting busts in U.S. history have occurred since 2009

@highlight

Though banned in every state, laws still require no minimum mandatory jail time