By 
Steve Robson

PUBLISHED:

04:41 EST, 20 March 2013


| 

UPDATED:

07:52 EST, 20 March 2013

Fans of veteran heavy metal band Napalm Death are used to seeing their idols bring the house down.

But it was their reputation for ear-shattering sets which led to a gig being cancelled this week.

The band were due to take part in a special one-off performance alongside ceramic artist Keith Harrison at London's Victoria & Albert museum in Kensington.

SCROLL DOWN FOR VIDEO

Eardrum assault: Heavy metal band Napalm Death have been entertaining 'grindcore' fans since 1981

Disappointed: Napalm Death singer Mark Greenway, left, and guitarist Shane Embury, in full flow

Mr Harrison, who shares the band's roots in Birmingham, had built a sculptural sound system clad with ceramic tiles which would in theory disintegrate as the band thrashed out their songs to illustrate a theme of 'sound as a weapon'.

A limited number of fans had been given free tickets for the show in Room 7 of the European Galleries on Friday.

But earlier this week, museum bosses were forced to pull the plug on the event amid fears that not only would the ceramic tiles explode, the building could come down with it.

A statement on the V&A's website 
reads: 'It is with regret that we have taken the decision to cancel the 
one-off Napalm Death performance in collaboration with our ceramic 
artist in residence Keith Harrison.

'This
was due to take place in the Europe Galleries which are currently being
refurbished and a further safety inspection has revealed concerns that 
the high level of decibels generated by the concert would damage the 
historic fabric of the building.

'The
V&A is committed to an exciting programme of exhibitions and events
but the safety of our visitors and building remains our priority at all
times.'

Historic: Ceramic specialist Keith Harrison has been an artist in resident at the Victoria & Albert museum since last October

Worried: Museum bosses had concerns that the loud decibels could damage some of the ancient artifacts (pictured is the Medieval and Renaissance Gallery)

Mark 'Barney' Greenway, the lead singer of Napalm Death, told The Times he was disappointed but not entirely surprised.

'They had been making noises. They started asking the sound guy fairly nervously: "What will the volume be like?" He was like, "What can I tell you? They make a lot of noise",' he said.

He added there were specific concerns about a hanging sculpture near to the stage.

The museum's worries were unlikely to have been alleviated by Mr Greenway's influences.

'Some of my favourite bands go out to make enough noise to make people physically sick. They use sound as a weapon,' he told The Times.

'We were ready for things to go awry,' he added. 'Apparently there was some suspended china thing around the stage. Obviously if we cranked [the music] out and it detached from the ceiling, that would be embarrassing.'

The band, who released debut album 'Scum' in 1987, are regarded as pioneers of the 'grindcore' scene and one of the loudest performers in the music industry.

@highlight

Special performance with ceramic artist Keith Harrison had been lined up

@highlight

Built tiles around sound system which would 'explode' as they played

@highlight

Museum bosses pull the plug amid fears noise could bring down building too

@highlight

Lead singer Mark 'Barney' Greenway not surprised by cancellation

@highlight

'They had been making noise. We were ready for things to go awry,' he said