An effective moratorium on new onshore wind farms will be in place within six months of a Tory election victory next year, the party will pledge today.

Energy Minister Michael Fallon will say that there is ‘no requirement  for any more’ of the turbines  erected across the country with  little or no regard for the views of local communities.

The Conservative manifesto will also pledge to scrap the subsidies paid by bill-payers for onshore wind power and change the planning system to allow local councils to block any which do not already have planning consent.

Blight: Turbines in Anglesey, North Wales. The Conservatives will pledge today that an effective moratorium on new onshore wind farms will be in place within six months of a Tory election victory next year

Pledge: Energy Minister Michael Fallon will say that there is 'no requirement for any more' of the turbines  erected across the country with  little or no regard for the views of local communities

The key reforms would be implemented six months after a majority Conservative government is elected, Mr Fallon is expected to say.

The move represents a major concession by
 David Cameron – who once urged voters to ‘vote blue, go green’ and 
erected a turbine on the roof of his house – to sceptical Tory MPs.

The Tories have gradually lost their enthusiasm for green policies since 2006.

‘Vote blue, go green. We have to think global, act local’

Conservative Party  manifesto, April 2006

‘We are not going to drop the environmental agenda. We will take forward our green agenda in a way that strengthens the economy – not “green” or “growth”, but both’

David Cameron, June 2008 

‘I want us to be the greenest government ever – a very simple ambition and one that I’m absolutely committed to achieving’ 

Mr Cameron, May 2010

‘Onshore wind plays a role in a balanced UK electricity mix, alongside gas, nuclear, cleaner coal and other forms of renewable energy. I am also determined that we seize the economic  opportunities in renewable energy supply chains’

Mr Cameron, Feb 2012

‘We can no longer have wind turbines imposed on communities. I can’t single-handedly build a new Jerusalem but I can protect our green and  pleasant land’

Former Tory energy minister John Hayes, Oct 2012

‘There’s a limited potential for onshore wind. Frankly, we’ve got some in the UK – I don’t think we’re going to have a huge amount more’

Mr Cameron, Aug 2013

‘Get rid of all the green c**p’

Mr Cameron, reportedly, to aides, Nov 2013

‘Unthinking climate change worship has damaged British industry and put up bills’

Tory energy minister Michael Fallon, Feb 2014

‘Wind farms have a place – and it is offshore by and large. They work better in the sea because it’s windier, so they don’t have to blight the landscape’

Tory party chairman Grant Shapps, April 2014

The Prime Minister has been persuaded that Britain can meet targets for increasing the amount of power generated by onshore wind farms through those that have already been built and those with planning consent.

The 4,000 existing onshore wind turbines, which have enjoyed generous subsidies for 20 years, deliver power to four million homes.

A further 3,000, for which planning permission has been given, will deliver power to three  million more by 2020.

Mr Fallon said: ‘Making sure we have a good mixture of reliable energy is an important part of our long-term economic plan.

‘We remain committed to cutting our carbon emissions – and renewable energy, including onshore wind, has a key role in our future energy supply.

'But we now have enough billpayer-funded onshore wind in the pipeline to meet our renewable energy commitments.

‘That’s why the next Conservative government will end any additional billpayer subsidy for onshore wind, and give local councils the decisive say on any new wind farms.’

A government source said that a majority Tory government would ‘effectively curtail further large-scale onshore wind developments’, adding: ‘If elected, we would make these changes within the first six months.’

As well as ending subsidies, which mean wind farm owners are paid nearly double the going rate for every unit of energy they generate for the National Grid, legislation would be introduced to reform applications for new developments.

Applications for new wind farms have to be made to local authorities, and around a half are refused.

But under the existing system, energy firms often win on appeal to the Government’s planning inspectorate.

The Tories say the entire process would be handled by councils through a locally-led planning system, not a national regime which prioritises ‘significant infrastructure’ projects as at present.

The party will also pledge to ensure that concerns about the impact of projects on landscapes and heritage sites cannot be overturned except in exceptional circumstances.

The party’s shift in policy appears timed with next month’s local elections in mind, given the controversy generated by wind turbines in many areas.

It opens up a significant dividing line for the Conservatives with Labour and the Liberal Democrats, who enthusiastically support more wind power.

Ed Miliband told the Mail that Britain would have to ‘embrace’ onshore wind if Labour wins next year.

Prime Minister: The move represents a major concession by David Cameron - who once urged voters to 'vote blue, go green' and erected a turbine on the roof of his house - to sceptical Tory MPs

Last night Ed Davey, the Liberal Democrat Energy Secretary, said: ‘I know what our Coalition Government policy is: It is to invest in renewables, to invest in low carbon, and onshore wind is a major part of that investment.

‘Onshore wind is the cheapest form of renewable electricity, and if you were to not go ahead with that investment you would see people’s bills go up.’

Britain must invest £33billion in infrastructure if the country is to make the most of its shale gas reserves, says a study today.

Commissioned by the UK Onshore Operators Group which represents fracking firms, it estimates that 4,000 wells will be drilled over 18 years.

Greenpeace claimed the report was ‘rose-tinted industry  guess-timates’ and ‘a veiled plea  for government and taxpayer support’.

@highlight

Reforms to come in six months after majority Tory government elected

@highlight

Move represents a major concession by Prime Minister David Cameron

@highlight

Told voters to 'vote blue, go green' and erected a turbine on home's roof