Scientists have created an entire simulation of the universe in order to understand the formation of galaxies, stars and more.

The man-made cosmos is a computer simulation in which galaxies similar to those observed by astronomers grow and evolve.

Two of the world's most powerful supercomputers - the 'Cosmology Machine' at the University of Durham and 'Curie' in Paris - were used to conduct the simulations, which took several months in total to run.

Scroll down for videos 

The new simulation could reveal how galaxies and dark matter formed in the early universe. Here, gas in the Eagle Simulation shows hot bubbles (red colours) surrounding large galaxies, connected by colder filaments (blue and green colours). The insets show the distribution of gas, stars and dark matter

Previous attempts to model the formation of galaxies have met with little success, producing collections of stars that were often too massive, small, old or spherical.

Those produced in the Eagle (Evolution and Assembly of GaLaxies and their Environments) simulation are much more realistic.

One key to its success is the recreation of galactic winds - cosmic gas gales driven by stars, supernova explosions and supermassive black holes - which are stronger than those in earlier simulations, say the scientists.

Galactic winds affect the development of galaxies by blowing away the gas from which stars form.

The sizes and shapes of the thousands of galaxies produced in the Eagle simulation closely match their 'real' counterparts, and can be used to study the history of the universe almost as far back as the Big Bang 13.8 billion years ago.

Professor Richard Bower, from the University of Durham, said: 'The universe generated by the computer is just like the real thing. There are galaxies everywhere, with all the shapes, sizes and colours I've seen with the world's largest telescopes.

'It is incredible. In the Eagle universe I can even press a button to make time run backwards.'

Results from the research will appear in the journal Monthly Notices of the Royal Astronomical Society tomorrow.

Co-author Dr Rob Crain, from Liverpool John Moores University, said: 'This is the start of a new era for us. We can now manipulate the conditions of the universe and study the evolution of galaxies throughout the past 14 billion years.'

 

Dark matter accounts for around 85 per cent of the universe.

It surrounds galaxies across the universe, and is invisible because it does not reflect light.

It cannot be seen directly with telescopes, but astronomers know it to be out there because of the gravitational effects it has on the matter we can see.

A dark matter halo is the hypothetical region that surrounds a galaxy.

It is thought to extend well beyond the visible edge of the galaxy and dominates the total mass of the galaxy.

However, since they cannot be observed directly their existence is only a theory.

Nonetheless its believed that many galaxies were born in such halos - but why there are only a few in our vicinity is a mystery.

According to Durham University's simulation the explanation could be that only those halos that grew fast enough after the Big Bang were able to eventually form galaxies.

The Eagle simulation may also help in the hunt for one of the universe's most elusive phenomena - dark matter. 

Physicists say the simulations show that 'halos' of matter that formed as the universe developed could be evidence of the elusive substance.

Scientists believe that these clumps of dark matter, or halos, that emerged from the early universe trapped intergalactic gas and became the birthplaces of galaxies.

Cosmological theory predicts that our own cosmic neighbourhood should be teeming with millions of small halos containing galaxies, but only a few dozen such small galaxies have been observed around the Milky Way.

'I've 
been losing sleep over this for the last 30 years,' said Professor Carlos Frenk, Director of Durham University's Institute for Computational Cosmology.

'Dark
 matter is the key to everything we know about galaxies, but we still 
don't know its exact nature.

'Understanding how galaxies formed holds the
 key to the dark matter mystery.'

One of the biggest mysteries is why there isn't a galaxy in every halo.

The researchers believe their simulations answer this question, showing explicitly how and why millions of halos around our galaxy and neighbouring Andromeda failed to produce galaxies and became barren.

They say the gas that would have made the galaxy was sterilised by the heat from the first stars that formed in the universe, and was prevented from cooling and turning into stars.

However, a few halos managed to bypass this cosmic furnace by growing early and fast enough to hold on to their gas and eventually form galaxies.

In this animation, a flight through 13 billion years of cosmic history takes us to 'our' Local Group in the Eagle simulation. The change in colours indicates how stars heat up the intergalactic gas to high temperatures (credit: Richard Bower, Durham University)

The simulation is hoped to solve the mystery as to why there isn't a galaxy in every dark matter halo. Here the visible galaxies in the Local Group simulation, shown in the lower right, only trace a tiny fraction of the vast number of dark matter halos, revealed in the upper left

The findings, first presented at the Royal Astronomical Society's National Astronomy Meeting in Portsmouth earlier this year, were funded by the UK's Science and Technology Facilities Council (STFC) and the European Research Council.

A recent Massachusetts-led researchers said they may have found the first hints of dark matter particles.

Using two observatories they found an unidentified spike of X-ray intensity in a galaxy cluster 240 million light-years away.

The signal could be the sign of the decay of 'sterile neutrinos', one of the proposed particles that dark matter is made of.

However, the researchers claim the dark matter explanation is a 'long shot'.

'We have learned that most dark matter halos are quite different from the 'chosen few' that are lit up by starlight,' Professor Frenk continued, referring to some that contain stars and some that do not.

'Thanks to our simulations we know that if our theories of dark matter are correct then the universe around us should be full of halos that failed to make a galaxy.

'Perhaps astronomers will one day figure out a way to find them.'

Lead researcher Dr Till Sawala, in the Institute for Computational Cosmology, at Durham University, said the research was the first to simulate the evolution of our 'Local Group' of galaxies.

This is a group of more than 54 galaxies that includes Andromeda and the Milky Way.

'What we've seen in our simulations is a cosmic own goal,' said Dr Sawala.

'We already knew that the first generation of stars emitted intense radiation, heating intergalactic gas to temperatures hotter than the surface of the sun.

'After that, the gas is so hot that further star formation gets a lot more difficult, leaving halos with little chance to form galaxies.

'We were able to show that the cosmic heating was not simply a lottery with a few lucky winners.

'Instead, it was a rigorous selection process and only halos that grew fast enough were fit for galaxy formation.'

The findings by the researchers were funded by the UK's Science and Technology Facilities Council (STFC) and the European Research Council. The team used the DiRAC Cosmology Machine, pictured, to create the simulation. It has 6720 Intel Xeon Cores and 53,760 gigabytes of ram

The close-up look at the Local Group is part of the larger Eagle project currently undertaken by cosmologists at Durham University and the University of Leiden in the Netherlands.

Eagle is one of the first attempts to simulate what happened from the Big Bang to the present day in the formation of galaxies in the universe.

By peering into the virtual universe, the researchers find galaxies that look remarkably like our own, surrounded by countless dark matter halos, only a small fraction of which contain galaxies.

The Durham-led simulation was carried out on the 'Cosmology Machine', which is the part of the DiRAC national supercomputing facility for research in astrophysics and particle physics funded by the Department for Business, Innovation and Skills through the STFC.

The Cosmology Machine - based at Durham University - has more than 5,000 times the computing power of typical PCs, and over 10,000 times the amount of memory.

@highlight

Researchers at Durham University in the UK and Leiden University in the Netherlands have made an entire simulation of the universe

@highlight

They used two of the world's most powerful supercomputers to make it

@highlight

Called the Eagle simulation it charts the formation of stars and galaxies

@highlight

It allows researchers to go forwards and backwards in time and space

@highlight

And it could even be used to solve mysteries such as dark matter