A doctor who snored terribly for years says he has cured the problem by performing surgery on his own tongue.

Dr Zhang Xiangmin undertook the remarkable operation to help his long-suffering wife sleep.

He believes his snoring was caused by obstructive sleep apnoea, where the throat closes repeatedly during the night.

Dr Zhang Xiangmin performed surgery on his own tongue to try and stop his snoring problem

He said the experimental op was prompted by his desire for his long-suffering wife to get a good night's sleep

During the procedure, Dr Xiangmin inserted two thin pipes through tunnels he made on the back of his tongue. At night, the loops these pipes onto his teeth to stop his tongue from collapsing and causing him to snore

Snoring occurs when the airway is partially obstructed - the sound is generated by air rushing past the soft tissues in the throat.

In severe cases, the airway can become completely blocked, stopping breathing for up to ten seconds, before the brain jolts the body awake, causing the airway to reopen. 

During his experimental procedure, Dr Xiangmin inserted two thin pipes through tunnels he made on the back of his tongue.

At night, he loops these pipes onto his teeth to stop his tongue from collapsing and causing him to snore. 

Three months on, he has now declared the procedure a success.

Speaking at a press conference in Changsha, the capital of China's Hunan Province, he said: 

'The surgery won't affect normal speaking and eating functions at all, and is very safe.' 

Obstructive sleep apnoea is a risk factor for a number of conditions, including heart attack, stroke, high blood pressure, daytime fatigue and weight gain.

One of the most successful treatments for the condition is a continuous positive airway pressure mask or CPAP, where mildly increased air pressure keeps the airways open during sleep.

However, many people dislike wearing the mask, with some estimates suggesting that only half of sufferers with a CPAP device regularly use it. 

Dr Xiangmin believes his snoring was caused by obstructive sleep apnoea, where the throat closes repeatedly during the night. Snoring occurs when the airway is partially obstructed

Three months on, he has now declared the procedure a success. 'The surgery won't affect normal speaking and eating functions at all, and is very safe,' said Dr Xiangmin, speaking at a press conference 

 

@highlight

Dr Zhang Xiangmin says he wanted to stop snoring so his wife could sleep

@highlight

Believes his years of snoring were caused by obstructive sleep apnoea

@highlight

This is where the throat closes repeatedly during the night

@highlight

During op he inserted two pipes through tunnels he made on back of tongue

@highlight

At night, the loops these pipes onto his teeth to stop his tongue from collapsing, and causing him to snore

@highlight

Three months after op, Dr Xiangmin, from China, has deemed it a success