By 
Daily Mail

PUBLISHED:

17:08 EST, 9 May 2013


| 

UPDATED:

17:28 EST, 9 May 2013

Youtube joined the paid-content streaming video fray today as it officially outlined its selection of premium channels, many with a decidedly nostalgic bent, starting at $0.99 per month.

Roger Corman's campy B movies, children's shows like ‘Sesame Street’ and ‘Inspector Gadget,’ and inspirational monologues by celebrities - these are among the offerings on 30 channels that will soon require a paid monthly subscription on YouTube.

Although the world's largest video site has rented and sold movies and TV shows from major studios since late 2008, most people watch videos on YouTube for free.

Classics: A screenshot shows The Henson Company's premium Youtube channel, one of 30 initially offered as the video giant enters the paid content market

It's the first time YouTube is introducing all-you-can-watch channels that require a monthly fee. The least expensive of the channels at will cost 99 cents a month but the average price is around $2.99.

In the field of paid video content online, YouTube is playing catch up to services like Netflix, Hulu and Amazon, all of which have millions of paying customers.

Netflix shares soared in April after the runaway success of its original series House of Cards and expects similar returns from their release of new episodes of Arrested Development, a comedy that once aired on Fox.

But with a billion monthly visitors from around the globe, the Google-owned video service hopes to quickly add subscribers and add to the money it already makes from online advertising.

‘This is just the beginning,’ said 
Malik Ducard, YouTube's director of content partnerships. The site plans
to roll out a way for a broad number of partners to also launch pay 
channels on their own soon.

Campy: Roger Corman, whose credits included the cult camp classics Piranha and Little Shop of Horrors, will also have his own paid channel

And kids: Alongside Corman's classics will be channels offering old kids favorites like Inspector Gadget. Teh channels start off at 99 cents per month, but each is priced differently

Corman,
a producer and director whose influential cult classics like ‘Deathrace
2000’ and ‘Piranha’ earned him an honorary Oscar in 2009, said he's 
kept his 400-film library off of video streaming sites until now.

In
an interview with The Associated Press, he said he turned down an offer
from Hulu for about $5,000 to $6,000 per film several years ago, but 
sees promise in the YouTube offering. His channel, ‘Corman's Drive-in,’ 
will cost subscribers $3.99 per month for a rotating selection of 30 
movies, refreshed with new interviews and clips from films that are in 
production. It is set to launch in June.

‘I
believed for many years that the future of motion picture distribution,
particularly for the independents, is on the Internet,’ said the 
87-year-old director. ‘I think the time is now.’

YouTube will keep slightly less than half of the revenue generated by the subscriptions.

Corman's
wife and producing partner Julie Corman said they were taken aback at 
YouTube's potential after a clip of their 2010 movie ‘Sharktopus’ went 
viral with 11 million views.

If even 1 percent of those viewers signed up for a subscription, it would amount to a healthy revenue stream, she said.

‘The numbers are astonishing. We're waiting for the fireworks display,’ she said.

Different: Until now, the Google-owned company has largely been known for ad-driven content that is free to users. It now joins paid providers Hulu, Netflix, and Amazon

@highlight

Legendary 'Piranha' creator Roger Corman to have his own channel alongside the Jim Henson Company, Ultimate Fighting Championship, and around 30 others