It's been a harrowing time for residents in the Adelaide Hills over the past few weeks, but one sporting event is trying to show that the area is literally on the on road to recovery.

As the peloton of the Tour Down Under sped through burnt bushland on stage one in the Adelaide Hills it was as if new life and colour had been breathed back into the region.  

The scorched earth and trees were a severe backdrop as some of the world's best cyclists whizzed by, but it also stood for a rebirth of sorts as people continued to get their lives back on track.

Scroll down for video 

Competitors ride through burnt bushland destroyed in a recent bushfire at Checker Hill in the Adelaide Hills during stage one of the 2015 Tour Down Under

Burnt trees line either side of the road as cyclists in the Tour Down Under spill through Checker Hill

Jack Bobridge of Australia races up Checkers Hill as scorched trees stand in the background

The peloton breezes through another section of the Adelaide Hills that was badly hit by bushfire

It may look picturesque but the reality was anything but pretty after fires raged through the Adelaide Hills earlier this month  

A stranded koala bear can only cling on for dear life amidst the burnt trees and scorched earth of the Adelaide Hills 

But certain precautions had to be made behind the scenes before the competition got the green light.

ABC News reported that Tourism Minister Leon Bignell said safety audits had been carried out in the Adelaide Hills along roads in Kersbrook, Gumeracha and Cudlee Creek following last week's bushfires.

The safety of the teams and spectators had been the South Australian Government's top priority.

‘We've had the teams out there from the Department of Transport to make sure that trees that were a threat to riders and to spectators have been removed and the path is clear for stages one and three to go ahead in the fire-affected areas,’ he said. 

It's hoped that the Tour Down Under will raise people's spirits in the Adelaide Hills area after the bushfires

Australia's Richie Porter (right) flies past an area of scorched earth as he leads a breakaway from the peloton 

Having the race travel through the Adelaide Hills is a much-needed boost for the fire-affected communities, which face a long recovery period ahead. The publicity given to the area has already resulted in a surge of donations to the Country Fire Service. 

‘We see this as a huge boost to the people who have suffered so much angst and worry over the past few days with the bushfire,’ Mr Bignell said.

‘There's still a lot of hard things to be done in the next few weeks and months, perhaps years, for the people in the area, but we wanted to make sure that if there was any possibility at all we would make sure that the race went ahead as scheduled.’ 

Earlier this month the sight of burning houses could be seen throughout the Adelaide Hills because of bushfires 

Guardian angel: A CFS fire-fighter looks to the heavens in thanks as it begins to rain during the Adelaide fires

The peloton bunches up as it passes through the Adelaide Hills during stage one of the Tour Down Under on Tuesday

The reality of Australia's hot summers and the devastation it can cause would be clear for all to see for those watching the broadcast of the race. 

'It will be great for the world to tune in and see that the area is returning to normal,' Mr Bignell said.

‘To see the blackened Australian landscape is something that unfortunately Australians are used to - it happens from time-to-time during our harsh summers - but for people from overseas to see what's happened, it will be a stark contrast to the vineyards and the beautiful coastal views that they normally have of the Tour Down Under.’

Publicity has already resulted in a surge of donations to the Country Fire Service who fought day and night to keep the fires at bay

Australia's Jack Bobridge won the opening 132.6km stage of the race, as the cyclists lapped the Barossa wine region twice before heading into the fire-ravaged hills. Wednesday's stage two will be from Unley to Stirling over 150.5km.

 

@highlight

The world's best cyclists weaved their way through the bushfire-ravaged Adelaide Hills in the Tour Down Under

@highlight

Cyclists sped past kilometres of burnt trees and scorched during stage one of the race    

@highlight

The peloton lapped the Barossa wine region twice before heading into the hills that had been devastated by fire

@highlight

Publicity generated by the event has already resulted in a surge of donations to the Country Fire Service  