By
Toni Jones
and Catherine Eade

Travel addicts always want to be ahead of the curve when it comes to the hottest new holiday destinations.

But who decides which places will be the 'next big thing' and how can we find out about them?

TravelSupermarket.com has tracked online searches and Twitter mentions to create a list of the up-and-coming holiday destinations that are already on the hit list of travel 'tastemakers'.

Scroll down for video

Trending in travel: Twitter images of Croatian town Rovinj which has been tipped as the hottest new holiday destination by TravelSupermarket.com

Sunset: Romantic Rovinj is situated on
the Adriatic coast

1  
Rovinj (Croatia)2   Warsaw (Poland)
3   St Petersburg (Russia)
4   Reykjavik (Iceland)
5   Copenhagen(Denmark) 
6   Tel Aviv (Israel)
7   Biarritz (France)
8   Bergen (Norway)
9   Valletta (Malta)
10 Gothenburg (Sweden)

And where they go the rest of us are soon to follow.

The pretty, little-known coastal town of Rovinj in Croatia is garnering the most attention online.

Poland's capital Warsaw is in second place, with St Petersburg third.

And Europe seems to be the travel hotspot for 2014 as Iceland, Denmark, Israel, France, Norway, Malta and Sweden all feature too.

Croatia is already popular as a destination for British travellers but the coastal town of Rovinj is still relatively undiscovered and therefore a cheaper place to visit, say TravelSupermarket.com.

Next month the town hosts the Red Bull Air Race and a forthcoming music festival in September could also be the reason for a higher number of searches.

A recent increase in the number of low
 cost flights to Poland's capital Warsaw could be the main reason for 
its current popularity as it works out as a cheap location to visit.

Russia
 has been receiving more interest generally as a result of the Winter 
Olympics, and its current newsworthy status will also have sparked 
interest in the country.

Dramatic: Visitors to Saint Petersburg in Russia will need to wrap up

Reykjavík: Not only one of the cleanest, greenest, and safest cities in the world, Iceland's capital - the most northern capital in the world - is famous for its wild weekend nightlife, colourful buildings and quirky people

Scandi cool; Lit buildings reflected in an urban canal in Copenhagen

A tale of two cities: Different types of architeture on show in Copenhagen

Tel Aviv: Whether it's to watch Justin Timberlake perform in May, take part in the Gay PRide Parade in June, visitors will be flocking to the 'white city' if online forums are anything to go by

Lots of media interest in the Northern Lights has been generated by sightings in the UK recently, and Reykjavik is still considered one of the places to go to see the spectacle, while the announcement of new low cost services from easyJet will also boost tourism numbers this year.

Norway's Bergen has a blossoming art and music 
scene, and a Viking festival in June half way between
 Bergen and Stavanger in Carmoy may attract increased visitors to the 
area over the summer.

Scandinavia is still uber-cool at the moment, and for those who've been to Stockholm already, Gothenburg is a great alternative.

Bob
 Atkinson, travel expert at TravelSupermarket, said: 'We've been keeping
 an eye on which destinations have been searched for over the last year 
to uncover the top holiday hot-spots that have seen an unusual increase 
in interest.

Biarritz: For a long time the playground of the rich, this French coastal town is renowned for the beauty of its coastline, its curved inlets punctuated by rocky outcrops, and many cultural and musical events

Quaint: Narrow streets are full of character in Valletta in Malta

Last but not least: The opera house at the yacht harbour of Gothenburg, Sweden

'It's often the case that new destinations start to come into our psyche as a result of a music or sports events, or even film and TV programmes from dramas to documentaries and we find our attention suddenly drawn towards a new place we might never have considered before.

'The good news is, low-cost air travel has given us the confidence and the opportunity to try out these up-and-coming locations. It means we can now get away for short breaks easily and affordably and be much more experimental with our choice of destination , having fun discovering new places in the process.'

Which holiday hotspot will you be heading to this year? Post your comments below

On the magnificent coast of Istria (Croatia), right below the Lim Fjord, is the most romantic place in the Mediterranean!

The town of Rovinj is the right destination for those seeking a sentimental feel of times that have forever gone by.

This town began its romantic life on an island, its restricted area resulting in crowded houses, narrow streets and small squares, still untouched by modern urbanism.

Rovinj is billed as one of the most romantic towns in the Mediterranean

On the seaside, the town is protected by a high rocky shore and house walls built on cliffs, while the mainland side is protected by solid walls.

The town is dominated by the baroque St. Euphemia’s Church, its 60-meter tower providing a view of grey and red rooftops and chimneys, streets and squares, the port and pier with ships and boats, and the marina harboring yachts.

This unique old town core, the 67-kilometer shoreline, 2,289 acres of protected green surfaces and improved park forests, 16 islands, islets and reefs, make this town unique.

Built upon a rich fishermen’s tradition, it has become distinctive for its unique boat called batana and its songs bitinada.

Its beauty was particularly appreciated by artists who have painted the most beautiful motifs here and exhibited them on Grisia, the street of artists.

Romantic and mysterious, yet full of options for an unforgettable time.

- Rovinj Tourist Board

@highlight

List of hip destinations created using online searches and Twitter statistics

@highlight

'Enchanting and historic' Rovinj in Croatia is garnering the most interest

@highlight

Warsaw in Poland and Russia's Saint Petersburg take 2nd and 3rd place 