Underwater military sonar could be killing blue whales, according to scientists.

American researchers have found that baleen whale species, which include the world’s largest animal, the blue whale, react to the mid frequency noises by changing behaviour.

This includes altering foraging so they 
miss out on high-quality prey, which could make them weak and decimate 
numbers through starvation.

The study, from the Cascadia Research Collective based in Washington, adds weight to environmentalists' claims that the use of sonar disrupts marine animals' feeding habits and can lead to them getting lost.

American researchers have found that baleen whale species, which include the blue whale (pictured), react to sonar by changing behaviour. This includes altering foraging so they miss out on high-quality prey, which could make them weak and decimate numbers through starvation

The soundwaves, developed by the military to track enemies beneath the waves, are between 1 and 10 kHz, which is within the human hearing band.

They have been blamed for lethal mass stranding of deep diving toothed whales.

Sonar is thought to disrupt the animals’ diving behaviour so much  that they suffer a condition rather like ‘the bends’ which human divers can contract if they surface too quickly.

The effects on endangered blue whales were virtually unknown.

This research claims that sonar can significantly disrupt their foraging and dramatically decrease feeding efficiency.

The Navy claims that military sonar is needed to defeat recent technological advances such as quiet propellers being added to modern submarines that make sound detection more difficult.

However, it has proven to be one of the most troubling acoustical assaults on marine life, particularly associated with catastrophic strandings of marine mammals.

The most common victims have been toothed whales and dolphins, but minke whales have also washed up on the shore after the use of these sonars.

Undersea noise blocks animals’ communication. Baleen whales produce low frequency calls that can travel thousands of kilometres through water.

Dolphins and toothed whales generate higher frequency clicks used to locate prey.

Noise generated by ships’ engines and propellers and by seismic airguns used in oil and gas exploration, produce a range of frequencies that can interfere with both these groups of species.

A sonar device on board a ship. The Navy says that the low frequency system will enable its warships to detect modern submarines, which are quieter and smaller than their predecessors. 
However, it has proven to be one of the most troubling acoustical assaults on marine life, particularly associated with catastrophic strandings of marine mammals

Dr Jeremy Goldbogen used suction caps to electronically tag 17 blue whales off the coast of Southern California and monitor their response to simulated sonar sound waves from a nearby research vessel.

He said: 'Despite using source levels orders of magnitude below some operational military systems, our results demonstrate that mid-frequency sound can significantly affect blue whale behaviour, especially during deep feeding modes.

'When a response occurred, behavioural changes varied widely from cessation of deep feeding to increased swimming speed and directed travel away from the sound source.'

Blue whales dive continuously throughout the day to feed on large numbers of dense krill that sustain their huge bodies size.

Dr Goldbogen said: “This type of behavioural response that involves cessation of feeding clearly results in reduced foraging efficiency.'

Could images like this become a thing of the past? Undersea noise emitted by sonar systems blocks animals' communication, according to scientists. Baleen whales, which include the Humpback (pictured) produce low frequency calls that can travel thousands of kilometres through water

His team of researchers calculated 
that a blue whale has a feeding rate of 19 kg of krill a minute before 
exposure to sonar sound.

When the whale heard the simulated sonar, it stopped foraging for 62 minutes, resulting in a loss of more than a ton of krill.

His findings are published in Proceedings of the Royal Society B.

Dr Goldbogen warned the results suggest sonar sound may pose significant risks to the endangered blue whale which, unlike other baleens including the humpback, grey and fin, have not shown signs of recovery off the west coast of North America in the last twenty years.

He said: 'Our results provide the first experimental demonstration that individual baleen whales, specifically blue whales, respond to simulated mid frequency sonar.

Dr Goldbogen warned his research suggests sonar sound may pose significant risks to the endangered blue whale (pictured) which, unlike other baleens have not shown signs of recovery off the west coast of North America in the last twenty years. He said: 'Our results provide the first experimental demonstration that individual baleen whales, specifically blue whales, respond to simulated mid frequency sonar.'

'Management decisions regarding baleen whales and military sonar should consider the likely contexts of exposure and the foraging ecology of animals in predicting responses and planning operations in order to minimise adverse effects.'

Nature magazine recently reported that prompt political action may have resulted in a remarkable conservation success for whales and dolphins.

The Canary Islands, which used to be a hotspot for mass standings of beaked whales, has had no beachings since the Spanish government imposed a moratorium on naval exercises using sonar in 2004.

In 2002, a group of 14 beaked whales fell foul of mid-frequency Navy sonar activity and were beached.

@highlight

American researchers found that sonar can significantly disrupt blue whales' foraging and dramatically decrease feeding efficiency

@highlight

The study is the first experimental demonstration into how blue whales respond to simulated
 mid frequency sonar

@highlight

The Navy claims sonar is needed to monitor modern submarines with quiet propellers that are difficult to detect

@highlight

Environmentalists believe that sonar blocks baleen whales' communication and can lead to stranding