By 
James Chapman

PUBLISHED:

19:01 EST, 5 November 2012


| 

UPDATED:

03:31 EST, 6 November 2012

Child benefit could only be paid for the first two children under radical reforms being considered at the Treasury.

Senior sources confirmed that as the Coalition looks to trim more from Britain’s bloated welfare bill, one option is to limit future payments of the handout by family size.

The proposal goes further than Work and Pensions Secretary Iain Duncan Smith’s suggestion that workless families could have child benefit and child tax credits limited if they insist on having more than two children.

Hint at reform: Financial Secretary to the Treasury David Gauke (left) said the government was looking at restrictions to child benefit which could go further than those mooted by Work and Pensions Secretary Iain Duncan Smith (right) for families who have more than two children

Instead, child benefit could be paid to all families, whether in work or not, for the first two offspring but not for subsequent children.

Ministers say benefit would not be removed from existing families, so could only apply in the future.

The reform would be far simpler to administrate than a complicated means-tested removal of benefit from lower income households.

The Treasury has already had to introduce a complex system of means testing at the other end of the income scale, as child benefit is reduced for families where one earner is on more than £50,000 and removed altogether from those earning £60,000 or more.

But it would prove hugely controversial among Conservative backbenchers, who are already concerned about the backlash generated by Chancellor George Osborne’s existing changes.

These come into force in January, but at present all parents with young children are given the benefit worth £20.30 a week for the first child and £13.40 for each subsequent child.

Exploring all options: Under the reforms being considered by the Treasury, families would get child benefit for the first two offspring only (file picture)

For a couple with two children, it is worth £1,752 a year, while for a couple with three children it is worth £2,448 a year. A senior Treasury source told the Daily Mail: ‘All options are being looked at in this area.

‘It’s not something we can do retrospectively. The main focus is on the incentives that apply to workless households as opposed to working households. You could just do that with child tax credits. But we are looking in detail at child benefit as well. We are looking at various options.’

Another Treasury source said: ‘No details, including whether it would apply to people in work, are settled, and it would only apply to new children.’

Financial Secretary to the Treasury David Gauke hinted at broader reform in an interview with BBC Radio 4’s Moneybox programme.

Controversial: Conservative backbenchers are already concerned about the backlash generated by Chancellor George Osborne's existing changes to child benefit

Asked if he supported Mr Duncan Smith’s ‘two child policy’, Mr Gauke said: ‘Iain Duncan Smith has set out a proposal in that area. That’s something that collectively across government we are looking at, including for child benefit.

‘Clearly that’s something we would need to look at in some detail but there is a point about the fact that those people who are in work have to make decisions when they have additional children as to whether they can afford to do that or not...

‘It’s important that the welfare system works in such a way that everybody is faced with a degree of responsibility as to the children they have and whether they are able to afford that.’

Asked whether child benefit might be limited to the first two children, he added: ‘We are looking at it in terms of the welfare bill across the board as to how that might work.’

A Treasury spokesman said: ‘The Government is exploring further options for making the welfare system fairer and more affordable, and details will be announced in due course.’

Senior Conservatives insist that removing or cutting child benefit from the top 15 per cent of earners remains one of the Government’s ‘most popular policies’, with a poll showing that even a majority of those affected back the idea.

Despite warnings of a potential bureaucratic nightmare, and crippling marginal tax rates for higher-earning couples with big families, ministers are pressing ahead with plans to restrict the benefit paid to 1.2million households.

Affected families have started to receive letters from HM Revenue & Customs giving them the choice of stopping receiving benefit or having cash clawed back at the end of the year through the tax system.

A Populus poll commissioned by the Conservative Party found that 82 per cent of people support the policy, including 78 per cent of people with children under the age of 18.

It was backed by 80 per cent of households with income between £41,000 and £55,000.

@highlight

Restrictions would apply to all families whether they are in work or not

@highlight

Goes further than IDS's plan to merely reduce payouts beyond two children

@highlight

Reform would be far simpler than complicated means-tested system