The NSA is now building a facility that will make it more than seven times the size of the Pentagon, making the secretive compounds the biggest in the country.

In addition to building a $1.9billion data center in Utah, crews also started construction on a computing center that is expected to cost $792million near Baltimore.

Together, the two facilities total 228 acres, much of which is dedicated to the collection of emails and phone calls that it was recently revealed the NSA stores without an individual knowledge.

Information overload: A report in July showed the NSA is doing a lot more than spying on Americans with terrorist connections, perhaps with the help of its $1.7 billion Utah Data Center

More convenient: As opposed to the remote Salt Lake facility, there is also a 28-acre facility owned by the NSA that in outside of Baltimore, Maryland

Outnumbered: The two NSA sites are now more than seven times the size of the Pentagon

Much attention has been paid to the secretive practices of the NSA since consultant Edward Snowden leaked classified documents proving that the intelligence agency had free reign to the electronic footprint of people, both in and out of the country, who used certain phone carriers.

NSA official Harvey Davis told Defense One that the Utah facility is 'only brick and mortar' but they need the space because 'it's required to be big' as a result of their growing surveillance.

'I think we're crossing into content,' he told the site.

Mike Baker, a former cover field operations officer for the CIA, told Fox News that the paranoia surrounding the billion dollar project was understandable yet exaggerated, adding that the main problem was the size of the data collection warehouse.

More:The Utah Data Center, near Bluffdale, was rumored to be one of the sites where personal data extracted by the NSA was stored

Storage: An aerial photograph shows the center

'The fact that they’re building a new data center isn’t news,' Baker told Fox News. 'They’ve got several other [similar] facilities. The size of this is what is creating the stir.'

Once built, the million square foot centre will be more than five times the size of the US Capitol, and will use an estimated $40m of electricity every year, according to one estimate.

NSA public information officer Vanee' Vines added: 'Many allegations have been made about the planned activities of the Utah Data Center

'What it will be is a state-of-the-art facility designed to support the Intelligence Community’s efforts to further strengthen and protect the nation. NSA is the executive agent for the Office of the Director of National Intelligence, and will be the lead agency at the center.'

Mystery: A close-up section of NSA's Utah Data Center is shown in Bluffdale in July

Powerhouse: These images were released last year as it emerged the government is secretly collecting the telephone records of millions of Verizon customers, as well as data from companies including Facebook and Google

The Utah Data Center which is being constructed on Camp Williams on the Salt Lake-Utah County line will be completed in October - but officials have been tight-lipped about what will be stored there.

The spy center is being built at an estimated cost of $1.9billion, and is expected to employ 100 to 200 permanent employees after its completion. The plans note they must all be U.S. citizens.

In light of the nature of the site they are building, many will have to have a higher degree of security clearance than an average construction worker.

Despite the boom for the local economy, the American Civil Liberties Union of Utah has expressed their fears over what will be stored at the center.

Stash: The government has been tight-lipped about what will be stored in the center's four 'data halls'

Plans: Sketches released by Army engineers show the massive center, which is believed to cost $1.7 billion

'We're mining data, we're gathering data and it's all done secretly,' ACLU of Utah director Karen McCreary told Fox13. 'We don't even know what's going on.'

'When the NSA facility in Utah was announced, local officials praised it for the jobs it would bring,' Libertas director Connor Boyack added.

'As Americans are now learning, those jobs entail harvesting the data generated by innocent Americans not suspected of any crime, in contradiction to the Fourth Amendment.'

@highlight

Government will complete its data storing facility in Utah this October

@highlight

Concerns about what personal information will be stored there as it emerged the government has been extracting data from big companies