They have plagued feet for centuries, but only now have physicists revealed what causes ingrown nails.

Experts have  come up with the first mathematical formulae that describe how human nails grow.

They have discovered that ingrown toenails are caused when the forces holding nails in place, and their rate of growth, become unbalanced.

Experts have come up with mathematical formulae that describe how nails grow. These graphs show how the tilt of the nail changes when the adhesive molecules are not working efficiently (C), the probability that a bond is not keeping up with nail growth (D) and a representation of the force generated by a nail (E)

Other factors, such as the thickness of the nail, biomechanical stress and the way people trim their nails, influences their chances of getting ingrown nails.

The University of Nottingham study solves a long-running mystery about why ingrown nails occur.

Nails are made of dead skin cells, which are hardened by a protein called keratin.

They grow outwards from the half-moon shaped ‘lunala’ at the base of the nail, but their progress of 0.1 to 0.2mm a day is kept in check by adhesive molecules that ‘stick’ the nail to the finger, Popsci reported. 

They have discovered that ingrown toenails are caused when the forces holding nails in place, and their rate of growth, become unbalanced. When this happens, a nail becomes wider at the top and curls round into the sensitive flesh to either side of the nail. Big toenails are prone to becoming ingrown because of their shape

Scientists looked at the mechanical stresses and energies associated with the nail, to come up with equations to explain nail growth.

They show that when the balance between the nail’s growth stress and adhesive stress is broken – if a nail grows too quickly or slowly, or the number of adhesive structures changes – a residual stress across the entire nail can occur, causing it to change shape over time.

The equations demonstrate that residual stress can occur in any fingernail or toenail; however, the stress is greater for nails that are larger in size and have a flatter edge, which explains why ingrown toe nails predominantly occur in the big toe.

Experts say that the tiny, microscopic structures, which allow the nail to slide forwards, grow in a ‘ratchet-like’ fashion by continuously binding and unbinding to a nail.

If the balance between adhesion and growth becomes unbalanced, the nail changes shape, and can become ingrown or spoon-shaped, according to research published in the journal, Physical Biology.

Ingrown nails often occur in children, teenagers and pregnant women, when hormones cause a growth spurt of the nails, which extend into the sensitive flesh alongside them.

Cyril Rauch, lead author of the study at the University of Nottingham, said that big toenails are particularly prone to becoming ingrown because of their shape.

Scientists say that people should trim their nails in a ‘parabola shape’ to minimise their chance of getting ingrown nails. They warned that poor trimming can tip the fine balance of nails, causing residual stress to occur across the entire nail, making problems like ingrown nails more likely

Their squareness means stress caused by walking is diverted to the tip of the nail, which gets wider to spread the load.

The scientist says that people should trim their nails in a ‘parabola shape’ to minimise their chance of getting ingrown nails.

Dr Rauch warns that regular poor trimming can tip the fine balance of nails, causing residual stress to occur across the entire nail.

‘We suggest that nail beauty fanatics who trim their nails on a daily basis opt for straight or parabolic edges, as otherwise they may amplify the imbalance of stresses which could lead to a number of serious conditions,’ he says.

@highlight

Scientists at the University of Nottingham have come up with the first mathematical formulae that describe how human nails grow

@highlight

They say ingrown toenails are caused when the forces holding nails in place, and their rate of growth, become unbalanced

@highlight

Other factors, such as the thickness of the nail, biomechanical stress and the way people trim their nails, changes the odds of getting ingrown nails

@highlight

Experts advise people to trim their nails in a 'parabola shape'