It could be the answer to the growing problem of phone addiction - or simply a spoof to show just how much we are obsessed by our cellphones.

A new website claims to offer the equivalent of a security blanket for phone addicts - a plastic 'brick' exactly the same size and weight as an iPhone.

It boasts the noPhone has 'no camera, no bluetooth and it can't make calls.'

Scroll down for video 

'The noPhone simulates the exact weight and dimensions of your most beloved gadget in order to alleviate any feelings of inadequacy generated by the absence of a real smartphone,' the firm behind it says. 

Recent research has found that more than half of gadget owners (53 per cent) worldwide admit to suffering anxiety when they can’t use their phones.

It found having a tech detox was ‘as stressful as a trip to the dentist or even their own wedding day.’

The number of people being treated for this addiction has risen over the past year and around 1 in 8 people in the UK now exhibit signs of being hooked on their gadgets.

According to the gadget's website, 'The noPhone simulates the exact weight and dimensions of your most beloved gadget in order to alleviate any feelings of inadequacy generated by the absence of a real smartphone.' 

As the site explains, the noPhone has superior features to a normal smartphone, because it's totally wireless, battery-free, doesn't require software updates, and is shatterproof and waterproof. 

'With a thin, light and completely wireless design,the noPhone acts as a surrogate to any smart mobile device, enabling you to always have a rectangle of smooth, cold plastic to clutch without forgoing any potential engagement with your direct environment. 

'Never again experience the unsettling feeling of flesh on flesh when closing your hand.

'The noPhone simulates the exact weight and dimensions of your most beloved gadget in order to alleviate any feelings of inadequacy generated by the absence of a real smartphone.'  

The noPhone simulates the exact weight and dimensions of an iPhone

In a testimonial section, Whitney R. notes, 'With the noPhone, my eye contact skills have improved 73%.'

Recent research has found that more than half of gadget owners (53 per cent) worldwide admit to suffering anxiety when they can’t use their phones.

It found having a tech detox was ‘as stressful as a trip to the dentist or even their own wedding day.’ 

However, it is not known if the handset will ever be sold. 

Ingmar Larsen, one of the designers of the project, told ABC News: 'What inspired us is the fact that a lot of people around us nowadays are focused on their mobile devices and not on the social environment anymore. 

'We wanted to make people aware of their addiction by creating a product that can be used for their addiction. It works as a placebo.'

Larsen said the group is still figuring out 'the possibilities' for manufacturing and selling the noPhone and said it's something they hope to do in the future.

NoPhone Demo from No Phone on Vimeo.

@highlight

Fake handset designed for addicts set to go on sale 

@highlight

Same size and weight as an iPhone 

@highlight

Designers began site as a spoof - but now plan to manufacture the noPhone 