All Americans would be better off if the top rate of income tax was returned to Eisenhower-era levels of about 90 per cent, economists have claimed.

The recommendation would more than double the current top U.S. rate of income tax - 39.6 per cent - and runs counter to more than two decades of economic orthodoxy.

At the moment fewer than one per cent of Americans reach the top income tax bracket of $406,750 for individuals and $457,600 for couples, yet the topic is one of the most emotive in U.S. politics. 

Post-war consensus: President Dwight D Eisenhower presided over a successful U.S. economy in which high taxation was seen as normal practise for those earning incomes far above the national average 

Low rates: This graph shows how the U.S. income tax rate has fluctuated in the past century

Fabian Kindermann from the University of Bonn and Dirk Krueger from the University of Pennsylvania make the case for radically higher rates of taxation in a new paper published by the National Bureau of Economic Research.

Their conclusions come nearly 25 years after the idea that the wealthy should be allowed to keep as much of their money as possible became the accepted political norm.

Beginning with the presidency of Ronald Reagan, spurred by the new ideology of neoliberalism, the U.S. saw radical cuts to the top rate of income tax until it fell to less than 30 per cent.

The architects of these policies were spurred by ideologues like the radical capitalist Ayn Rand, an originator of the 'wealth creator' myth, who believed rational self-interest would create the most-perfect economic conditions.

Taking money out of the hands of the rich was not only unjust, she and her acolytes believed, but also economically illiterate, since those who were best at making money would know the best way to spend it.

But as Dr Kindermann and Dr Krueger point out, these tax cuts coincided with a spike in inequality, with the total share of U.S. household income accruing to the top 1 per cent doubling between the early 1970s and 2007.

Since the 2008 financial crisis and banking bail-out, inequality has soared more than ever, leading to calls from from academic economists and street-level protesters alike for something to be done to reverse it. 

Radical right: Ayn Rand, an originator of the 'wealth creator' myth, who believed rational self-interest would create the most-perfect economic conditions

Of course, no-one wants to hand 90 per cent of their income over to the federal government. But much of this fear stems from a misunderstanding of how marginal tax rates work.

If you make $500,000 and are subject to a 90 per cent marginal tax rate, that doesn't mean you are going to pay $450,000 in tax. What it means is you pay 90 per cent tax on every dollar you earn over the threshold of $406,750.

If you make $500,000 that means you pay the top rate on your final $93,250 of income.

The researchers come to their conclusions after some 30 pages of complex economic calculations which they say models 'a quantitative overlapping generations economy'.

They claim that 'in the model the top 1 per cent [of earners] look exactly as in the data, at least with respect to their key economic characteristics.'

Running their model, Dr Kindermann and Dr Krueger conclude a tax rate of 90 per cent or higher on the top band of earners would not only decrease inequalities in both income and wealth, but also increase everyone's well-being - even those paying the new tax.

In essence, Dr Krueger told The Huffington Post, such a high tax would 'provide social insurance against not making it into the 1 per cent.'

In the paper he and Dr Kindermann write that 'such high marginal tax rates provide optimal social insurance in a world where very high labour incomes are generated by rare (but somewhat persistent) earnings opportunity.'

There is a caveat. It is argued that higher marginal tax rates would not discourage the enterprising and entrepreneurial from wanting to work as hard at making money.

This is precisely the contention of Ayn Rand and her acolytes. In her bestselling novel, Atlas Shrugged, Rand imagines a dystopia where successful industrialists abandon their fortunes in response to aggressive regulations.

The result of this capital strike is that most vital industries collapse, leaving the nation in ruins, until the wealthy ride to the rescue and reorganise society along the lines of Rand's 'rational selfishness'.

But Dr Kindermann and Dr Krueger counter that such an eventually is unlikely, because even those among us who are unusually talented have only a limited window of opportunity to exploit their abilities.

They have only a few years to use their skills to make all the money they can. As Dr Krueger told the Huffington Post: 'How much less hard would LeBron James play basketball if he were taxed at a much higher rate?'

The answer, the economist says, is not much. With only five or so years of peak earning potential the basketballer will work to earn as much as he possibly can in that time.

The question, of course, is: would Jamie Dimon or Lloyd Blankfein behave the same way? And would it matter if they didn't?

 

@highlight

Economists' paper calls for return to Eisenhower-era rates of income tax

@highlight

Higher rates would benefit all Americans, even the rich, it is claimed

@highlight

Recommendation runs counter to two decades of economic orthodoxy 