By
Daily Mail Reporter

The storm set to hit Hawaii overnight has been downgraded from hurricane to tropical storm as it approaches the island group.

Iselle has been downgraded to a tropical storm about 50 miles from where it is expected to make landfall in the southern part of Hawaii's Big Island today.

More good news followed as Hurricane Julio, which approaches the area behind tropical storm Iselle, is now largely expected to pass north of the island.

Scroll down for video

Downgraded: A red flag flies over at Polo Beach, Wailea, Maui, as Hawaii prepared for the arrival of Iselle which was downgraded from hurricane to a tropical storm

Despite its downgrading, Iselle is the first hurricane or tropical storm to hit the island chain in 22 years.

Wind and rain from the system still had enough force to knock down trees, cause power outages and block roads on the Big Island, however. No deaths or major injuries have been reported.

Iselle was classified as a tropical storm 11pm Thursday Hawaii Standard Time when its winds slowed to 70mph, putting it below the minimum of 74mph for a hurricane.

The storm was weakening because of several factors, including wind shear chopping at the system and the Big Island's terrain above the water, said Chris Brenchley, meteorologist with the National Weather Service in Honolulu.

‘As wind blows into the terrain, the terrain kind of redirects the wind,’ he said. 

Spectators line the coast to watch large swells generated by the approaching Hurricane Iselle in Pohoiki, on the Big Island of Hawaii

Staff members of the Royal Kona Resort in Kailua, Hawaii take down umbrellas as the resort prepares for Hurricane Iselle on Thursday

In this composite image provided by NASA, Hurricane Iselle (L) is followed by Hurricane Julio as they approach Hawaii from the east

Hundreds
 of people flowed into emergency shelters set up at high schools on the 
Big Island on Thursday, one of which lost power.

Crews worked to restore electricity
 to the shelter in Pahoa with at least 140 people.

Power also was lost Thursday 
evening in two communities on the Big Island: Waimea, a town of about 
9,200 people near the island's north shore, and Puna, a district 
scattered with residents south of Hilo, Hawaii County Civil Defense 
officials said.

Mayor Billy
 Kenoi told KHON-TV that no major injuries or damage from the first bits
 of wind and rain have been reported. But heavy rains led authorities on
 the Big Island to issue a flood advisory.

People got ready for the storm by making last-minute trips to the store and boarding up windows at their homes.

'It's getting more windy, and it's raining pretty good,' said Denise Laitinen on the Big Island.

'But
 I'm ready for it. Everything outside is secured, and I've boarded up 
the picture windows. I feel good about being prepared for anything these
 storms bring us.'

Meanwhile,
 Hurricane Julio, strengthened into a Category 3 storm and followed 
Iselle's path with sustained maximum winds of 115 mph. It was about 
1,000 miles behind Iselle and projected to head just north of the 
islands sometime early Sunday morning.

Hawaii
 has been directly hit by hurricanes only three times since 1950. The 
last time Hawaii was hit with a hurricane or tropical storm was in 1992,
 when Hurricane Iniki killed six people and destroyed more than 1,400 
homes in Kauai, Lau said.

Crowds line up inside the departures terminal at the Honolulu International Airport in Honolulu on Thursday

With Iselle, Hawaii is expected to take its first direct hurricane hit in 22 years. Tracking close behind it is Hurricane Julio. Hawaiian Airlines announced Thursday they are waiving change fees for passengers trying to leave before the hurricanes hit the islands

Hawaii Governor Neil Abercrombie said
 the state is prepared for the back-to-back storms, noting the National 
Guard is at the ready and state and local governments were closing 
offices, schools and transit services across Hawaii.

'What
 we're asking the people to do now is pay attention, stay focused and 
listen to the directions,' he said. 'Hunker down with your family and 
friends and ride out the storm.'

State
 Attorney General David Louie promised that Saturday's primary 
elections, including congressional and gubernatorial races, will go 
forward as planned.

Travelers
 faced disrupted plans when at least 30 flights were canceled Thursday 
from several airlines, including Delta, United, Air China and WestJet, 
the Hawaii Tourism Authority said.

American Airlines and US Airways 
canceled flights in and out of the Big Island and Maui after 6 p.m. 
Thursday through noon Friday. Commuter airline Island Air canceled some 
afternoon flights and shut down all operations Friday.

Hawaiian
 Airlines canceled some interisland flights for Thursday evening and 
moved its Maui-Los Angeles flight up by nearly five hours.

The
 airline waived reservation change fees and fare differences for 
passengers who needed to alter their plans Thursday and Friday.

After
 high winds hit Maui, California couple Rudy Cruz and Ashley Dochnahl 
left the island earlier than planned, getting to Oahu but failing to 
secure a flight back home.

'We were trying to beat it, but we now will have to ride it out,' Cruz said.

Passengers
 at the Honolulu International Airport spilled out to the curb Thursday,
 and lines wrapped around the TSA screening area. But some travelers 
remained optimistic.

A sign inside the Walmart McDonalds restaurant alerts customers that it sent its employees home early in Kailua-Kona, Hawaii

Workers at the Menehune Water Company load five gallon bottles of water into a customer's truck, Thursday

Bottles of water are quickly disappearing off shelves in Hawaii causing many people to line up for several hours to purchase water directly from the company

Clouds hang over Honolulu, seen from the top of Tanalus Drive on Thursday

Airports remained open Thursday, but 
the Department of Transportation encouraged travelers to check with 
airlines. Nearly 30 flights from several airlines, including Delta, 
United, Air China and WestJet, were canceled Thursday, the Hawaii 
Tourism Authority said.

American
 Airlines and US Airways announced they canceled flights in and out of 
the Big Island and Maui Thursday evening through noon Friday. Hawaiian 
Airlines canceled some interisland flights for Thursday evening and 
moved its Maui-Los Angeles flight up by nearly five hours.

Travelers were urged to stay in hotels instead of heading to the airport, unless their flight was imminent.

'It's
 very, very important that people understand that our airport is not set
 up to handle large crowds,' Ford Fuchigami, interim director of the 
Hawaii's Department of Transportation, said in a news conference.

Most
 public bus services on Oahu and Maui would be shut down Friday, but 
some express buses would run in the morning, officials said. On Oahu, 
evacuation buses would start running late Thursday.

The
 U.S. Coast Guard shut down ports on the Big Island, Maui and Oahu, 
arranging for barges and ships to leave the ports and seek sheltered 
waters.

'I am committed to reopening each port as soon as it is safe to do so,' Capt. Shannon Gilreath said in a statement.

Tourist Denise Newland of New Zealand reads a hurricane update in the lobby of a hotel in Waikiki in Honolulu

A traffic jam forms in front of the Menehune Water Company as customers wait to purchase water from the company, Thursday

Beach goers are seen on Waikiki Beach, Thursday, Aug. 7, 2014, in Honolulu

An estimated 204,000 visitors are scattered across the Hawaiian islands on any given day, and hotel and tourism officials are delivering emergency information in multiple languages, said Mike McCartney, president and CEO of the tourism authority.

Tourists in popular Waikiki Beach on Oahu lounged on beach chairs Thursday morning and surfed on the azure waves while the tropical sun shone.

'We did decide to come out here and make the most of it before we had to be back inside because of the storm,' said Helen Povazan, retired IT manager visiting from Melbourne, Australia.

On Hawaii's Big Island, residents in the quaint town of Pahoa were glad they stocked up on bottled water earlier in the week because most stores had run out.

'Lucky thing I bought four cases Monday,' said Tarty Taurus at the Kaleo's Bar and Grill, as restaurant staff served customers and tied down everything they could.

Residents of rural Hana on Maui are hoping Hana Highway isn't washed out and have been buying up plywood, said Wiloris Perry-Estocado of Hasagawa General Store.

'There's a lot of old homes in Hana - we're all as prepared as can be,' Perry-Estocado said. 'If the wind comes, a lot of our roofs are going to go.'

@highlight

Iselle has been downgraded to a tropical storm, 50 miles from Hawaii

@highlight

Set to become the first tropical storm to hit island group in 22 years

@highlight

Hundreds of people have flowed into emergency shelters on the Big Island

@highlight

Power also was lost Thursday evening in two communities on the Big Island