As five years as Prime Minister David Cameron should have a decent stock of anecdotes to keep a room of voters entertained.

But in an advert break for last night's TV election contest the Tory leader took the chance to perform his own party trick.

In front of more than 100 voters and studio crew, he recited a verse from his favourite childhood song: Ernie (The Fastest Milkman in the West). 

Scroll down for video 

David Cameron revealed the only song he knows the words to is Ernie (The Fastest Milkman in the West), before reciting the first verse

Initial reports that the Prime Minister had burst into song were disappointingly wide of the mark.

During a break he told Sky News presenter Kay Burley how the chart-topping song by Benny Hill was the only one he could sing in full.

She tweeted: 'Just heard from PM that he can sing Ernie and nothing else...' 

The Premier could not be persuaded to showcase this talent, but did prove his love of the song by reciting the first verse. 

Burley added: 'He didn't sing but he did recite 'you could hear the hoof beats pound as they raced across the ground...' 

Mr Cameron's love of the song first emerged in 2006 when he appeared on Desert Island Discs and revealed it would be one of the songs he would take to the fictional island.

'This really just reminds me of my childhood,' he said at the time. 'When you are asked to sing a song, this is, I'm afraid, the only song whose words I can remember.'

The private rendition for the audience in last night's TV studio might explain why he got a relatively easy time from them when the cameras went live.

While Mr Cameron was asked about treating the elderly with dignity and the depth of spending cuts, Mr Miliband faced a series of aggressive questions.

Mr Cameron waves to the audience after taking questions in the first TV contest of the general election campaign 

The Tory leader's first question from the audience was: 'What do you think are Ed Miliband's best qualities?'

One of the few off-the-cuff questions from Burley to the PM was: 'Have you ever had three shredded wheat?'

When Mr Miliband face the audience, he was first asked: 'You sound gloomy most of the time, are things really so bad?'

Another asked: 'Do you not think that your brother would have done a better job? He was better qualified and better positioned.'

Mr Cameron and Mr Miliband faced the wrath of voters - and Jeremy Paxman - last night as they were forced to defend their broken promises, judgement and ability to lead the country in the first prime-time TV contest of the general election.

They were interviewed by Paxman for 18 minutes each, and also took questions from a studio audience with Ms Burley acting as moderator on the show broadcast on Sky News and Channel 4.

This afternoon Ofcom had received 254 complaints  - all of which were about perceived bias against the Labour leader.

It is thought they have been generated by a social media campaign sharing a link to the watchdog's website and urging people to complain. 

Jeremy Paxman appears to scratch his head mid-way through interviewing Prime Minister David Cameron 

An Ofcom spokesman said: 'We are assessing the complaints before deciding whether or not to investigate.'

A Channel 4 spokeswoman said it had received around 300 complaints, but was unable to say specifically what they were about.

'Both politicians, one of whom is likely to be the next Prime Minister, agreed to the format and were prepared for and actively participated in robust questioning about their policies and abilities. Neither party has expressed any dissatisfaction to Channel 4,' she added. 

Labour insiders privately noted that they thought Burley 'intervened and followed up aggressively a number of times'.

At one point Burley told Mr Miliband: 'That's a politicians answer there isn't it?' She also pressed him on the impact of his leadership victory over his brother David.

When the Labour leader said family relations had been strained, Burley responded: 'Your poor mum.' In a series of posts on Twitter, Burley took on her critics. 

Hundreds of people have lodged complaints with TV watchdogs that Kay Burley and Jeremy Paxman were biased against Ed Miliband

You could hear the hoof beats pound as they raced across the ground, and the clatter of the wheels as they spun 'round and 'round.

And he galloped into market street, his badge upon his chest, his name was Ernie, and he drove the fastest milk cart in the west.

Now Ernie loved a widow, a lady known as Sue, she lived all alone in Liddley Lane at number 22.

They said she was too good for him, she was haughty, proud and chic, but Ernie got his cocoa there three times every week.

They called him Ernie, (Ernieeeeeeeeeee) and he drove the fastest milk cart in the west.

She said she'd like to bathe in milk, he said, 'all right, sweetheart,' and when he'd finished work one night he loaded up the cart.

He said, 'd'you want it pasturize? 'cause pasturize is best,' she says, 'Ernie, I'll be happy if it comes up to my chest.'

That tickled old Ernie, (Ernieeeeeeeeeee) and he drove the fastest milk cart in the west.

Now Ernie had a rival, an evil-looking man, called Two-Ton Ted from Teddington and he drove the baker's van.

Comedian Benny Hill pictured as Ernie receiving a ticket from a policeman

He tempted her with his treacle tarts and his tasty wholemeal bread, and when she seen the size of his hot meat pies it very near turned her head.

She nearly swooned at his macaroon and he said, 'If you treat me right, you'll have hot rolls every morning and crumpets every night.'

He knew once she sampled his layer cake he'd have his wicked way, and all Ernie had to offer was a pint of milk a day.

Poor Ernie, (Ernieeeeeeeeeee) and he drove the fastest milk cart in the west.

One lunch time Ted saw Ernie's horse and cart outside her door, it drove him mad to find it was still there at half past four.

And as he lept down from his van hot blood through his veins did course, and he went across to Ernie's cart and didn't half kick his 'orse.

Whose name was Trigger, (Triggerrrrrrrr) and he pulled the fastest milk cart in the west.

Now Ernie rushed out into the street, his gold top in his hand, he said, 'If you wanna marry Susie you'll fight for her like a man.'

'Oh why don't we play cards for her?' he sneeringly replied, 'and just to make it interesting we'll have a shilling on the side.'

Now Ernie dragged him from his van and beneath the blazing sun, they stood there face to face, and Ted went for his bun.

But Ernie was too quick, things didn't go the way Ted planned, and a strawberry-flavoured yogurt sent it spinning from his hand.

Now Susie ran between them and tried to keep them apart, and Ernie, he pushed her aside and a rock cake caught him underneath his heart.

And he looked up in pained surprise and the concrete hardened crust, of a stale pork pie caught him in the eye and Ernie bit the dust.

Poor Ernie, (Ernieeeeeeeeeee) and he drove the fastest milk cart in the west.

Ernie was only 52, he didn't wanna die, and now he's gone to make deliveries in that milk round in the sky.

Where the customers are angels and ferocious dogs are banned, and the milkman's life is full of fun in that fairy, dairy land.

But a woman's needs are many fold and soon she married Ted, but strange things happened on their wedding night as they lay in their bed.

Was that the trees a-rustling? Or the hinges of the gate? Or Ernie's ghostly gold tops a-rattling in their crate?

They won't forget Ernie, (Ernieeeeeeeeee) and he drove the fastest milk cart in the west.

 

@highlight

Prime Minister reveals Benny Hill hit is the only song he can sing in full

@highlight

Stopped short of bursting into song but recited first verse to prove it

@highlight

Bizarre moment came while cameras were off during TV election contest

@highlight

Watchdogs have received hundreds of complaints of bias against Miliband 