By 
Matt Blake

PUBLISHED:

06:11 EST, 11 July 2012


| 

UPDATED:

02:06 EST, 12 July 2012

This is the terrifying moment a drunken reveller threatened staff and customers at a bar with a sawn-off shotgun... when they wouldn't serve him a drink.

Darren McDermott used the weapon to smash a pane of glass at One Lounge Bar in Didsbury after he had been refused drink and thrown out of a nearby bar.

McDermott, 31, went back to One Lounge Bar armed with a sawn-off shotgun, apparently seeking revenge.

Scroll down for video.

Overreaction: Darren McDermott used the weapon to smash a pane of glass at One Lounge Bar in Didsbury after he had been refused drink and thrown out of a nearby bar

Customers dived for cover when he shouted: 'I’m gonna put a hole in somebody.'

Footage taken from a passer-by on a mobile phone shows him pointing the gun at the unseen door staff inside the front door.

Guilty: McDermott was jailed for two years and eight months

Manchester Crown Court heard that when police later arrested McDermott, they found he had a bag of cocaine.

McDermott, of Mauldeth Road West, 
Fallowfield, pleaded guilty to possession of a firearm with intent to 
cause fear of violence, possession of class A drugs and criminal damage.

He was jailed for two years and eight months.

After
the hearing, Detective Constable Dominic Heslop said: 'McDermott was 
drunk and abusive initially towards door staff at M20 because they would
not let him in. We believe he targeted the One Lounge Bar after a staff
member there helped out at the incident.

'Members of the public were so 
frightened by the sight of the barrels pointing through the window and 
the noise generated by the smashing of glass they rang 999, fearing that
shots had been fired into the bar.

'They had no way of knowing that the barrels were incapable of firing a shot.

'The CCTV footage clearly shows the panic he caused that night and I am glad to say he has now been brought to justice.'

Bleary eyed vendetta: McDermott, 31, went back to One Lounge Bar armed with a sawn-off shotgun, apparently seeking revenge

Scary: Customers dived for cover when he shouted, 'I'm gonna put a hole in somebody'

Packing more than just heat: Manchester Crown Court heard that when police later arrested McDermott, they found he had a bag of cocaine

@highlight

Darren McDermott used the weapon to smash a pane of glass at One Lounge Bar in Didsbury after he had been refused drink

@highlight

He went back to One Lounge Bar apparently seeking revenge

@highlight

Drinkers dived for cover when he yelled: 'I'm gonna put a hole in somebody'

@highlight

McDermott pleaded guilty to possession of a firearm with intent to cause fear of violence, possession of class A drugs and criminal damage

@highlight

He was jailed for two years and eight months