The day before George Osborne delivers his budget to the nation the Lawn Tennis Association came up with its rough equivalent – the latest long term plan to revive the state of the game in Great Britain.

Chief Executive Michael Downey finally unveiled his vision for the governing body, and in budgetary terms the big winner will be those people involved in marketing the sport and trying to get more people playing it.

Over the next four years there will be a 50 per cent uplift in money spent on marketing, so that by 2018 around £26 million will be spent on promoting the sport of tennis in the United Kingdom.

While Andy Murrayis established as one of the world's best players, problems still exist at grass roots level

Other countries will look on enviously at such a huge sum although, given the current rankings of most GB juniors, many may well comfort themselves that their stocks of elite players will be superior for years to come.

Downey reaffirmed the LTA's laudable, broad policy of building the game from the bottom up by concentrating on participation and talked through a range of worthy and sensible measures to help achieve this.

However, there was nothing especially original to stir the imagination or make an impact with the wider public, no 'Parks tennis revolution' or some such thing. Anyone wanting to see something more radical to improve the British game would be left disappointed.

Not that Downey, the former head of Tennis Canada who was appointed 18months ago, pulled all of his punches in presenting the latest of what have hitherto been doomed long-term plans for the British game.

LTA Chief Executive Michael Downey has unveiled his long term strategy to rejuvenate the game

'Our sport is declining and some people have a problem hearing that,' he said at the start.

What he was specifically referring to was the problems tennis, like most other ball sports, has with declining participation numbers. They all face a challenge from what he termed 'doorstep' sports, highly convenient and less technically demanding activities such as running, cycling, swimming and going to the gym, which can be done solo and whenever time permits.

Despite the hundreds of millions gleaned from Wimbledon profits and that event's ever growing popularity, there has been an average drop of 5 per cent in adult participation over each of the past five years.

The particular problem is among the 16-44 age group with numbers steady above that. Curiously he omitted to mention, until asked, that tennis is now played to a greater or lesser extent in 20,000 schools among 2.6 million children, an impressive figure that would be envied by most other sports.

Among the smorgasbord of measures to improve things, there will be a drive to increase participation in parks tennis. 'I think the old LTA would have driven by the parks and straight into the clubs and schools,' he said.

The LTA receives millions annually from funds generated by the Wimbledon Championships

There were other sensible ideas. With tennis participation peaking in July, there will be a concerted effort to get people to start playing earlier in the year. Clubs, volunteers and coaches will get more support (attempts at this are nothing new).

In junior tennis there will, wisely, be more emphasis on team events and there will be a much-needed concentration on creating a less pressured environment at junior tournaments. The emphasis will be on creating inclusive fun and recreational competitions across the board.

Downey asserted that he was looking at the 'meat and potatoes' issues, rather than eyecatching initiatives. He also pledged that the LTA would spend money 'like it's your own' (no reference here to his own £434,000 pay package).

It is, clearly, expecting too much for any results to be instant, as with the efforts to improve the elite end of tennis. He was unrepentant about cuts to the performance side of the game and funding for lower ranked players, pointing out that the average entry age into the world's top 100 is 21 for men and 20 for women.

Murray's victory at SW19 in 2013 spiked interest but there has been a five per cent fall in adult participation

'If you are 27 years old and still playing Futures I don't think you are going to be a top 50 player. It's a ruthless business,' he said, reiterating the 'no compromise' message he wants to run through the elite end of the sport.

While there has to be a degree of patience with his plans, they also illustrated the glacial pace of how things tend to be done at the governing body compared to what would happen in the more dynamic private sector.

There are many things that have not even been considered or barely thought about. Andy Murray, for instance, is nearly 28 and there is still no clue as to how to use his profile to spread the game. (Downey presented his ideas to him in Glasgow two weeks ago and was impressed by his interest.).

Downey has spoken to Murray after Britain's 3-2 Davis Cup win over USA in Glasgow

TV advertising during the summer is not on the agenda. If there is an embracing of the excellent Tennis For Free charity and its proven methods then it seems limited. The whole key issue of playing surfaces did not raise a flicker, nor did the idea of adopting foreign training base with clay courts and a better climate. No participation targets have been set.

The simple idea of trying to rebrand the organisation from its anachronistic 'Lawn Tennis Association' title to something more modern is apparently a non-starter for some reason.

What was presented, though, was steady and sensible enough, while not especially imaginative nor wide in scope. Like most budget speeches, the effects of its contents will not be immediately obvious.

 

@highlight

LTA have unveiled their long term plan to get more people playing tennis

@highlight

There will be 50 per cent increase in marketing budget over next four years

@highlight

There has been five per cent drop in adult participation over last five years

@highlight

Chief Michael Downey has spoken to Andy Murray on spreading the game 