The 96th USPGA Championship will either conclude on Sunday with Rory McIlroy leaving his latest mark on the road to greatness or a shootout for the ages.

Either way cancel any plans to go out, because this is going to be a fitting conclusion to a classy season in the four majors.

Has there been a more exciting day in the game this year than Saturday’s third round? Played at a Ryder Cup venue, it generated Ryder Cup levels of hysteria as fearless wannabes, evergreen veterans and unsung Europeans took turns alongside the man of the moment to produce shots of stunning quality. For the final two hours of play the noise was unbelievable as roars echoed all over the property.

Fist-pump: A strong back-nine allowed McIlroy to stay in control heading into the final round at Valhalla

Up-and-down display: McIlroy rolls his eyes as he leaves his tee shot on the eighth hole just short of the green

In trouble: The 25-year-old looks into the creek for his tee shot on the second hold during his third round

Patient: McIlroy waits for his caddie as he gets ready to his his ball after losing his drive off the fourth tee

Scrambling: The Northern Irishman comes out of the crowd after hitting up to the fourth green

Upping his game: McIlroy picked up shots on the back nine with birdies at the 10th, 15th and 16th holes

Perhaps inevitably, given how the last month has gone, it was Open Champion McIlroy who had the final word to seize a narrow advantage.

At one point there were an incredible ten players either tied or within one shot of the lead. Then McIlroy rolled in a 20 footer to birdie the 15th.

At the near 500 yard par four 16th he pummelled a drive 340 yards and his nine iron finished 18 inches from the flag. He birdied the 18th from the sand as well for his third gain in four holes to regain top spot. It was truly mesmerising to watch.

Just as compelling was the pairing of Phil Mickelson and Bernd Wiesberger. Mickelson birdied four of his last five holes to give himself a shot at his sixth major on Sunday but he was still outscored by two shots by the 28 year old Austrian, who shot 65 to the 67 from the player he grew up idolising. ‘It was just a dream come true today,’ said Wiesberger.

So McIlroy will go into the final round with a one shot lead over Wiesberger on 13 under after a 67. He will not only be trying to win back-to-back majors but complete his third win in a row, after a stupendous run of play that has seen him complete his last 11 rounds in an aggregate of 45 under par, with just one round in the seventies. 

Distraught: McIlroy reacts to a missed putt for birdie at the picturesque 13th hole

Picture perfect: McIlroy hits an impressive shot on the sixth hole at Valhalla

Rickie Fowler, the man who chased him so hard at The Open at Hoylake last month, is just two back. Then comes the popular Mickelson and Jason Day, with quite a cast on nine under including two Scandinavians in Henrik Stenson from Sweden and Mikko Ilonen from Finland.

Given Valhalla’s place in Norse mythology, they’d be appropriate champions, wouldn’t they?

On seven under par, six shots back are two former world number ones in Adam Scott and Lee Westwood, and they will probably need to break the major championship scoring record of 63 to win. After yesterday’s play, you wouldn’t rule out someone shooting such a score.

McIlroy said he knew hearing all the roars that he needed to do something down the stretch. ‘There was a lot of noise out there and it wasn’t being generated by me, so the birdies at the 15th and the 16th were huge,’ he said.

‘It means I am still in control of the golf tournament but clearly I am going to have to play really well and shoot a low number in the final round. But I’m loving it. This is why we play the game and practice all these hours on the range.

'It has its stresses but I wouldn’t want to be anywhere else. You’ve got to enjoy being in the lead because that’s what it is all about.’

Swing low: He drives his tee shot down the fairway on the 10th hole during his third round

Going for a walk: McIlroy makes his way to the ninth tee with his caddie J.P. Fitzgerald

McIlroy and Jason Day certainly had their fair share of adventures in the final group. The 25 year old Northern Irishman and the 26 year old Australian are known for their penchant for spectacular rounds laced with birdies and eagles. But it was a par that each of them made in turn early on that fairly took the breath away.

First up was Day, whose jumpiness over the opening holes was personified with a horrendous hook off the second tee. It led to him taking off his socks and shoes, rolling up his trousers, wading through a creek and back – but still walking off the green with a par.

Not to be outdone, McIlroy came up with one of his own at the par four 4th. The tee had been moved up on this hole to make it driveable, and Rory duly took dead aim. He was soon dropping his club in disgust, however, as the ball sailed miles left and dropped into a creek.

After taking a penalty drop, it left him with a difficult pitch back, which he played well to 12ft. Now he was looking at a par putt that, had he missed, would have meant he was giving up at least two shots to the field and three shots to some.

But his solid putting, a feature of his brilliant run of form this summer, came to prominence once more, and he was pumping his fist as the ball disappeared. As both players had proved, sometimes pars are every bit as pivotal as birdies.

McIlroy notched his first birdie of the day at the next, and was a ball-width from making it two in a row at the difficult 6th, as his try from 25ft stopped on the edge. No matter. He duly made one on the next hole to establish a two shot lead. The tone for the afternoon was set.

Chatting: Jason Day of Australia and McIlroy chat as they walk to the seventh green in Kentucky

Nice approach: McIlroy chips on to the green at the eighth hole of the US PGA Championship

Almost inevitably a good bit of the excitement was being generated by the irrepressible Fowler, the bright spark in this dark season for American golf.

Tied fifth at the Masters, tied runner-up at the US Open and Open, he has given himself another realistic shot at winning his first major with a fine round of 67.

Then there was Welshman Jamie Donaldson, whose 66 was one of the most admirable rounds of all. After looking a certainty all year to make his Ryder Cup debut at Gleneagles next month, the 38 year old Welshman arrived here having dropping into the 9th and precarious last spot in the automatic standings. With the likes of Ian Poulter, Luke Donald and Lee Westwood all looking for one of the three wild cards at present, the pressure was clearly on.

How well Donaldson has responded and how much he deserves to make it. Donaldson told Sportsmail last week: ’No matter how much you try to forget about it, the Ryder Cup is always at the back of your mind tormenting you.’

Now lieing in the top ten in this big-money event on eight under, he can remove all the torment with a good final round today. ‘All I could do this week was go out and take control of my own destiny, and I certainly built towards that with this round,’ he said. ‘This was about perfect.’

With overnight rain and no wind rendering the course defenceless, there was a chance for the early starters to post a low score and make a statement. Emerging Englishman Danny Willett and Scot Marc Warren both shot 66 and Justin Rose a 67, and all of them will have the chance to post a top ten on Sunday. 

Relief: The 25-year-old reacts after saving par on the tricky 11th hole at Valhall Golf Club

@highlight

Northern Irishman finished third round at 13-under par for the tournament 

@highlight

McIlroy fired a round of 67 at Valhalla on Day 3 of US PGA Championship

@highlight

He keeps his one-shot lead at the top despite an up-and-down display  

@highlight

Bernd Wiesberger is just one behind after finishing with three birdies