By 
Chris Greenwood

Last updated at 10:38 PM on 14th October 2011

Hundreds of police sergeants are having to waste time correcting the poor English of frontline colleagues.

The officers work behind the scenes checking files for basic spelling and grammatical errors, as well as ensuring sums add up.

As many as 500 ‘evidential review officers’ – mostly sergeants on up to £43,000 a year – are employed by the Metropolitan Police alone.

Hundreds of police sergeants are having to waste time correcting the poor English of frontline colleagues

The news will enrage ministers desperate for police chiefs to cut bureaucracy and ensure officers spend their time catching criminals.

It comes after independent police pay and conditions reviewer Tom Winsor sparked controversy when he revealed he had been told the work of some officers was ‘barely literate’.

The former rail regulator endured a torrent of abuse after claiming reading, writing and mathematical skills in the service had fallen ‘significantly’ since the 1930s.

He was accused of ‘contempt’ for rank-and-file officers, who said higher educational standards were not necessary for much of their work.

Evidential review officers examine the huge volume of paperwork generated by investigating officers, including witness statements, interviews and other documentation.

They ensure all the necessary items are correct before offering advice and deciding how an inquiry should progress, if at all.

But many chief constables around the country have scrapped the posts  to focus on the front line.

In London, there are 199 evidential review officers in 32 boroughs, and up to 300 in specialist departments.

A straw poll of other forces revealed West Yorkshire Police employs 11, while Thames Valley Police has 24 ‘case director sergeants’.

Greater Manchester Police said it employed none and senior officers in the West Midlands said the role was made redundant two years ago.

A Metropolitan Police spokesman defended literacy levels in the force, saying officers had to reach a minimum standard set by the Home Office.

He added the main role of evidential review officers was to ‘facilitate the criminal justice process’ by checking files from an ‘independent viewpoint’ and ensuring the correct procedures had been followed.

@highlight

Up to 500 'evidential review officers' are employed by the Met alone