Liverpool stars past and present gathered on Thursday to honour the club's Anfield expansion announcement.

The Merseyside club revealed that construction on the club's Main Stand will begin early next year ready for completion during the 2016-17 season.

Club legends such as Phil Thompson, Alan Hansen, Kenny Dalglish and Ian Rush have posed in front of Liverpool shirts with each one commemorating the number of appearances each player has made for the club.

Liverpool players past and present (from left to right) Ron Yeats, Rodger Hunt, Ian Callaghan, Phil Thompson, Phil Neal, Alan Kennedy, Alan Hansen, Kenny Dalglish, Ian Rush, Robbie Fowler, Jamie Carragher, Steven Gerrard, Raheem Sterling and Jordan Rossiter of Liverpool pose for a photograph with managing director Ian Ayre and first team manager Brendan Rodgers

Ron Yeats: 454 appearances

Rodger Hunt: 492

Ian Callaghan: 857

Phil Thompson: 477

Phil Neal: 650

Alan Kennedy: 359

Alan Hansen: 620

Kenny Dalglish: 515

Ian Rush: 660

Robbie Fowler: 369

Jamie Carragher: 737

Steven Gerrard: 688

Raheem Sterling: 97

Jordan Rossiter: 1

The picture, which also includes manager Brendan Rodgers and chief executive Ian Ayre, shows the huge number of appearances past players made during the club's glory years and ranges from the 857 showings of Ian Callaghan between 1960 and 1978 to Reds youngster Jordan Rossiter, who has made just one appearance during his fledgling Liverpool career.

Red captain Steven Gerrard also features, sitting proudly in front of his '688' appearance shirt between Sportsmail columnist Jamie Carragher and English winger Raheem Sterling.

Gerrard, who will be out of contract in the summer, has been linked with a move away from Anfield after a slow start to the 2014-15 Premier League season, but Ayre insists the club want Gerrard to stay.

'We have a fantastic dialogue with Steven and his representatives,' said the Reds managing director, speaking at an event to announce the £100million redevelopment of Anfield's Main Stand will begin on Monday.

'We have made an offer to Steven and we have to be respectful to him and where he is in his career. There is no pressure from our side.

'The one thing I can say is he will always be a part of this football club whatever his decision.

'He is an iconic part of this football club and we want to see him here for many years - and that is not just about his playing career.

'He has been a fantastic servant to this football club and we don't expect that to change.

'If you ask Steven Gerrard he will say he wants to be here as long as he can.'

Liverpool Football Club is soon to add more seats to its famous and iconic home Anfield - to look like this

Anfield could look like this should its potential 13,000 seats be added to bring its capacity to about 58,800

The cost of the redevelopment has been funded internally by owners Fenway Sports Group in the form of a loan which will be paid back over five years.

Ayre also expects new sponsorship opportunities to be generated by the stand with the possibility of naming rights for all or parts of the stand likely.

And while crippling debt under the previous regime of Tom Hicks and George Gillett took the club to the brink of administration, there will be no impact on squad strengthening.

'The funding has been put in place by the owners, we haven't gone outside, and it will come in as a loan and that is great news because it minimises the cost and allows us to move very quickly,' he added.

'It is an effective way rather than going to a bank and paying escalating interest prices.

'It shouldn't affect squad development as we built this economic model on the basis it was important to find a solution where we could maintain our level of investment throughout the build.

Anfield is soon to be altered after Liverpool won permission from the city council in September

Rodgers looks on as Mamadou Sakho passes the ball during a Liverpool training session on Thursday

45,522 - Anfield's current capacity

58,800 - Anfield's potential new capacity

8,500 - Phase one to extend the Main Stand

4,500 - Phase two to extend Anfield Road end 

£75m - cost of extension by 2016/17 season 

£260m - cost of overall regeneration in Anfield

'It can only improve once the construction is finished and the money is paid (off) then it is additional revenue so it is additional revenues to invest in the team.

'It shouldn't have any negative effect on investment in the football team.

'That is why we do this. We obviously want more of our fans to come through the door each week but we want to compete at the highest level with our biggest competitors.

'They have a bigger capacity and therefore bigger revenue so can invest bigger amounts so this is one of the final pieces in the jigsaw for us.'

There have been protests at Anfield over ticket prices in recent weeks but Ayre insisted the new development would allow for a greater spread of prices.

'We have said all along we recognise there needs to be some affordable pricing and tickets in the stadium - that is the case today and maybe there can be more of that,' he added.

'It is about finding the right balance as transfer fees and wages are going up.'

Ayre also confirmed the Hillsborough Memorial would be placed into storage and a temporary feature installed at the stadium until construction is completed.

Rickie Lambert (right), Martin Skrtel (centre) and Raheem Sterling go through their warm-up during the session

@highlight

Liverpool have confirmed expansion of Anfield's Main Stand

@highlight

Liverpool legends gather for dressing room picture which commemorates appearances made by Ian Rush and Co

@highlight

Appearances ranges from Ian Callaghan's 857 to Reds youngster Jordan Rossiter's solo showing  