A new type of solar cloud has been discovered emanating from the sun.

The magnetic cloud is a smaller version of larger clouds of particles known as solar flares and coronal mass ejections, which can produce auroras on Earth.

And the finding could apparently help us understand how such space weather affects our planet.

Dr Janvier from the University of Dundee has discovered a new solar cloud. Solar clouds are groups of particles emitted by the sun into space, often as coronal mass ejections (CMEs), shown. This latest finding is smaller than comparable CMEs. But she says it could help us understand how space weather affects Earth

The discovery was made by Dr Miho Janvier from the University of Dundee together with Pascal Démoulin of the LESIA Observatoire de Paris in France, and Sergio Dasso at the University of Buenos Aires.

She made the discovery while looking at matter expelled from the sun and thrown out into space.

'Our work has been studying how solar flares are generated and the effects they cause,' explained Dr Janvier, reports the BBC.

'We already knew there were these large magnetic clouds generated by solar flares.

'We also knew that smaller magnetised structures existed, but what we have found is that they have a completely different origin.

The earth's magnetic field could flip in just 100 years, researchers have found.

The move, which would mean all compasses pointed south instead of north, was thought to take thousands of years.

However, a new study found it can happen far faster.

The new study by a team of scientists from Italy, France, Columbia University and the University of California, Berkeley, demonstrates that the last magnetic reversal 786,000 years ago actually happened very quickly, in less than 100 years - roughly a human lifetime.

The discovery comes as new evidence indicates that the intensity of Earth's magnetic field is decreasing 10 times faster than normal, leading some geophysicists to predict a reversal within a few thousand years. 

'These smaller clouds have different characteristics which mean they must be generated in a different place and/or in a different way.

'They must be coming from the sun but we are not sure yet where in the sun's atmosphere they are being born.'

She explained to MailOnline the finding is comparable to hurricanes and regular storms on Earth.

In this instance coronal mass ejections are much larger clouds of particles, whereas these new 'flux ropes' are much smaller.

Their size can be one tenth the Earth-sun distance, but they are thought to be much more numerous on the sun than larger coronal mass ejections.

But she adds: 'We didn't just see one cloud, it was a population of smaller clouds.' 

Solar clouds are storms of energised particles sent across the solar system at speeds of up to 370 miles (600 kilometres) per second.

When they arrive at Earth they can cause geomagnetic storms and pose a potential danger to satellites and even astronauts on the ISS.

Solar clouds are storms of energised particles sent across the solar system at speeds approaching that of light. When they arrive at Earth they can cause geomagnetic storms and auroras (shown), and pose a potential danger to satellites and even astronauts on the ISS.

Numerous spacecraft are in orbit around the sun to observe these events, including Nasa's twin Stereo spacecraft.

The two probes observe the sun simultaneously to produce stereoscopic images and observe solar phenomena including coronal mass ejections - commonly associated with solar storms.

However, the agency announced the other day that they had lost contact with Stereo B ('Behind'), putting the mission in jeopardy.

'Communications with the Stereo Behind spacecraft were interrupted on 1 October, immediately after a planned reset of the spacecraft performed as part of a test of solar conjunction operations,' Nasa said. 

'The cause of the anomaly is not yet known, though a sensor anomaly in the guidance and control system is suspected. Attempts to recover the spacecraft are continuing.'

The latest findings, though, will be useful for other spacecraft including the sun, such as a planned probe by Esa in 2017.

The discovery comes as one of Nasa's twin sun-observing Stereo spacecraft failed (illustration shown). The two probes observe the sun simultaneously to produce stereoscopic images and observe solar phenomena including coronal mass ejections - commonly associated with solar storms

@highlight

University of Dundee's Dr Janvier discovered a new type of solar cloud

@highlight

Solar clouds are groups of particles emitted by the sun into space

@highlight

This latest finding is smaller than comparable coronal mass ejections

@highlight

She tells MailOnline they are known as 'flux ropes' owing to their shape  

@highlight

But they were found to be much more numerous than bigger solar eruptions

@highlight

She says it could help us understand how space weather affects Earth

@highlight

Discovery comes as one of Nasa's sun-observing Stereo spacecraft failed