From stunning gemstones to glittering snowflakes, the mesmerising patterns of crystals can be found everywhere in nature.

Their beautiful structure has provided scientists with an understanding of matter itself, giving them incredible insights into the intricate patterns of everyday objects.

Now London-based photographer Max Alexander had shed light on some of these shapes, highlighting the importance of a technique known as X-ray crystallography.

Photographer Max Alexander had shed light on some of the shapes of substances created by a technique known as x-ray crystallography. Pictured here is the rapid crystallisation of a cancer drug

The method describes a process that allows scientists to find the shape of molecules and then learn more about their atomic arrangement. 

It was pioneered in the early 20th century when scientists discovered that X-rays could be used to 'see' the structure of matter in a non-intrusive way.

When X-rays hit a protein crystal they are scattered by individual atoms, and the way they are diffracted depends on the how the atoms in the molecule are arranged.

Using sophisticated mathematical techniques, an X-ray diffraction pattern can be used to work out the relative positions of different atoms in a molecule.

Crystallographers now use their knowledge of the structure of objects to change it and improve both its properties and behaviour.

In this image, a tiny crystal squeezed between diamonds - the hardest structures on Earth - subjects it to extreme pressures and making the crystal structure change

The eye of crystallographer Margarete Neu reflected from her computer screen. The scientist creates crystals to understand how they interact with new medicines

Crystallographer David Keen (pictured) studies crystal structures that behave in strange ways. In this image, he has created holes in Porthcawl beach in South Wales to portray the neutron diffraction pattern from a quartz crystal

Crystallography is the study of atomic and molecular structure. 

The method describes a process that allows scientists to find the shape of molecules and then deduce their atomic arrangement.

It was pioneered in the early 20th century when it was discovered that X-rays could be used to 'see'  structure of matter in a non-intrusive way.

When -rays hit a protein crystal they are scattered by individual atoms, and the way they are diffracted depends on the how the atoms in the molecule are arranged.

Using sophisticated mathematical techniques, an x-ray diffraction pattern can be used to work out the relative positions of different atoms in a molecule. 

For instance, the double-helical structure of DNA was found from an X-ray diffraction pattern that had been generated by a fibrous sample.

Mr Alexander told MailOnline that this is perhaps the biggest breakthrough achieved by the technique.

'Crystallography is a process in which art and science overlap,' he said. 

'But while it has achieved a great deal in science, it is very much an unsung story.'

The 53-year-old, originally from New Zealand, is hoping his photographs of the science and the people who made it happen, could raise the profile of crystallography. 

Mr Alexander said aspects of science can be very difficult to understand, but he hopes his images will simplify ideas to get those concepts across.

'It opens up a new set of people that might be engaged with crystallography and the science, just as we're engaging with the arts,' he told the BBC.

In one image, technicians are shown forming a fan blade for a jet engine from titanium alloys, by injecting high-pressure argon gas at around 1,000 degrees celcius. 

Crystallography experiments carried out on these blades helps to understand how their performance is affected by the materials used in the manufacturing process.

In another image, crystallographer David Keen was captured by Mr Alexander creating holes in Porthcawl beach in South Wales to portray the neutron diffraction pattern from a quartz crystal.

In addition to looking pretty, the crystal shapes can also serve an important purpose. For example, needle-shaped crystals in drugs can be hard to analyse but finding the right crystal is the first step in the development of treatments for diseases such as malaria.  

(pictured) can be hard to analyse but finding the right crystal is the first step in the development of treatments for diseases such as malaria

Technicians here are forming a fan blade for a jet engine from titanium alloys, by injecting high-pressure argon gas at around 1,000 degrees celcius. Crystallography experiments carried out on these blades helps to understand how their performance is affected by the materials used in the manufacturing process. This is one of Max Alexander's favourite images of the series

Meanwhile, centrosomes are molecular machines that organise the process of cell division in the body. 

To understand this process better, scientists try to grow crystals and solve the structures of the proteins from which they are built. 

These crystals are of a protein that co-ordinates the assembly of this important machine. 

Mr Alexander took the images as part of the International Year of Crystallography, designed to celebrate the technique.

Mr Alexander's photos are currently being shown at the Illuminating Atoms exhibition in London's Royal Albert Hall. 

The exhibition will be open until the 7 December 2014.

Centrosomes are molecular machines that organise the process of cell division in the body. To understand this process better, scientists try to grow crystals and solve the structures of the proteins from which they are built. These crystals are of a protein that co-ordinates the assembly of this important machine

A crystal is placed on the end of the pin with a stream of cool air coming in from the right. The X-ray beam arrives from the silver pipe and the camera images the crystal

@highlight

London-based photographer Max Alexander has shed light on a technique known as X-ray crystallography

@highlight

Process allows scientists to find the shape of molecules and then learn more about their atomic arrangement

@highlight

The technique has been vital to science, helping to uncover, for instance, the double-helical structure of DNA 

@highlight

The new exhibition aims to highlight the structures, people and processes involved in X-ray crystallography