By 
Ted Thornhill

PUBLISHED:

07:11 EST, 25 April 2012

 | 

UPDATED:

07:45 EST, 25 April 2012

Older people are a benefit, rather than a burden, to the economy and society according to a new report.

Researchers from the University College London School of Pharmacy refute the view that older people are a major source of economic problems such as reduced international competitiveness.

Their study provides evidence that the benefits of living longer will outweigh the additional health and social care costs of population ageing.

Positive effect: The elderly contribute billions to the economy, according to a UCL study

‘All too often old age is seen as a time of increasing dependency, vulnerability and frailty. But older people already contribute significantly to their families’ and wider communities’ wellbeing,’ said Dr Jennifer Gill, co-author of the report.

Life expectancy at 65 has increased by six years since the 1950s. As people live longer they stay healthier, at any given age. Such advances have partly been generated by the pharmaceutical revolution of 1950‐2000.

Medicines for conditions such as heart attacks, strokes and diabetes, are now well understood and have already contributed significantly to falling death and disability rates, despite problems such as obesity.

‘In future decades, greater participation by people in their 60s and 70s in formal and informal work, alongside additional decreases in the number of life years spent with major disabilities, could increase national productivity by up to 10 per cent of GDP,’ said Dr Gill.

One example of how those of more advancing years contribute to the economy is London-based handyman service Silver Saints, which operates a policy of employing men of more advancing years, with one aged 62 and until recently another aged 68.

Operations Manager Jordan 
Taylor told MailOnline: 'We find that because of their experience and 
exposure to life they have a calmer approach to the job - they're more 
confident and female customers are certainly more at ease with the 
elderly guys.'

In the 1980s and 1990s estimates indicate that just 0.2 per cent of the annual increase in NHS spending was caused by population ageing.

Benefit: Hospital costs for the elderly are outweighed by their positive contribution to the economy

Even though the current figure is in the order of one per cent per annum such cost increases have been outweighed by the positive contribution of £40 billion that adults aged 65 and over made to the British economy in 2010. It is estimated that by 2030 retired ‘baby boomers’ will contribute £80 billion to the economy.

The team points out that even if older people do need long term supportive care, they won’t be a burden on the economy.

Co-author Professor David Taylor said: ‘For instance, the extra  public cost of the recent Dilnot proposals for making residential and community care more fairly available in England would, if implemented, probably be under 0.2 per cent of current UK Gross National Product.’

@highlight

Over-65s added £40bn to the British economy in 2010

@highlight

Retired 'baby boomers' will have fed £80bn into the economy by 2030, according to a study