Scientists are constantly on the lookout for links between data to try and prove certain theories - but just because two sets of statistics match up, it doesn't necessarily mean they're are closely tied.

To prove a direct correlation does not always mean causation, a Harvard student has plotted various spurious links between randomly selected statistics.

These include a correlation between sour 
cream and motorbike accidents, Nicolas Cage films and swimming pool deaths, and divorce rates and margarine.

To prove that correlation does not always mean causation, a Harvard student has plotted various spurious links between randomly selected sets of data from the U.S Census. These include a correlation between sour cream and motorbike accidents, pictured

According to the data plotted from the U.S Census, Tyler Vigen's Spurious Correlations site found a link between:

The consumption of sour cream, and the number of motorcycle riders killed in accidents.

The number of people who tripped over their own two feet and died, with civil engineering doctorates awarded in the U.S.

How much beef is bought in the U.S, compared to the number of deaths caused by lightning.

The number of films Nicolas Cage has starred in, versus the number of people who died falling into a swimming pool.

The amount of cheese purchased, and the revenue generated by golf courses.

Tyler Vigen is studying for a juris doctorate at Harvard School of Law.

Using data from the U.S Census and Centres for Disease Control and Prevention research, Vigen was able to plot correlations between different subjects.

Each Spurious Correlation consists of a graph that plots the development of both chosen statistics.

Depending on the data, the date range can run from 1999 up to 2012.

Below each graph is a chart that shows the numerical statistics, as well as their source, plus the correlation.

The closer a correlation is to the number one, the more closely linked the two sets of data are.

‘Anyone can plainly tell that there’s not a connection between margarine and marriage,’ explained Vigen.

This graph plots the correlation between people who died by falling out of wheelchairs between 1999 and 2005, and the rising costs of a 16oz bag of potato chips in the U.S during the same period. The data was taken from the U.S Census and Centres for Disease Control and Prevention research

‘We saw data, we formed a hypothesis and then we rejected that hypothesis, based on our personal experience with the world.

The graphs claim there to be a correlation between the films Nicolas Cage, pictured, has been in and deaths, driving accidents and divorce rates

That’s a big deal - and it’s a part that computers can’t do. Research is about discovery, but only humans can actually make discoveries.’

The purpose of the Spurious Correlations site, according to Vigen, is not to say data is ambiguous and can be interpreted however people want, 'instead it reveals it’s up to us as rational thinkers to work out if there’s actually a connection between the variables - or if it’s a coincidence.'

‘Finding causal mechanisms is the key goal in a lot of scientific research because when we find causal mechanisms, we learn that much more about the world around us.

‘Sometimes, we see connections that we can’t explain and it inspires us to search for a potential cause.’

A good example of correlations leading to conclusions is the connection between smoking and lung cancer.

In the early 1900s, incidents of lung cancer were on the rise but no-one really knew why.

In 1929, German physician Fritz Lickint published a paper in which he showed that lung cancer patients were particularly likely to have been smokers.

That paper led to a body of research in which scientists learnt about the dangers of smoking - but it may never have happened if someone hadn’t spotted the links.

'Correlations between two variables could be merely coincidence, or they could be the result of an underlying causal link – and every time we see a correlation, we have the marvellous opportunity to try and figure out which one it is,' concluded Vigen. 

The purpose of the site, according to Vigen, is not to say data is ambiguous, 'instead it reveals it's up to us as rational thinkers to work out if there's actually a connection between the variables - or if it's a coincidence.' This graph shows a link between Nicolas Cage films and people who died falling into a swimming pool

Between 2000 and 2009, there was a link between how many people ate eggs in the U.S and the number of drivers killed in non-collision transport accidents. The closer a correlation is to the number one, the more closely linked the two sets of data are. This correlation is 0.88

 

@highlight

The Spurious Correlations site was created by Harvard student Tyler Vigen

@highlight

It plots data from the U.S census and Centres for Disease Control and Prevention research

@highlight

Vigen is also in the process of adding international statistics to the site

@highlight

He created it to prove that correlation does not always mean causation

@highlight

Other correlations include the number of Nicolas Cage films and people who died in swimming pools, and egg consumption with driving accidents