The moon once had a magnetic core which helped it generate a magnetic field stronger than Earth's is now, researchers say.

They believe a lunar dynamo, a molten, churning core at the centre of the moon, may have powered an intense magnetic field for at least 1 billion years.

However, researchers are still baffled by how it was powered, and when it ended.

A lunar dynamo, a molten, churning core at the centre of the moon, may have powered an intense magnetic field for at least 1 billion years.

Planetary dynamos are generated by the process of induction, in which the energy of turbulent, conducting fluids is transformed into a magnetic field. 

The motion of Earth’s liquid core is powered by the cooling of the planet, which stirs up buoyant fluid from the surrounding liquid — similar to what happens in a lava lamp.

'We think planets generate magnetic fields by moving electrically conducting fluids inside them,' said study co-author Benjamin Weiss, a planetary scientist at MIT. 

Flowing metal in Earth's core makes the heart of the planet a dynamo - a generator of electrical current - which in turn generates Earth's magnetic field.

Planetary dynamos are generated by the process of induction, in which the energy of turbulent, conducting fluids is transformed into a magnetic field. 

The motion of Earth’s liquid core, for instance, is powered by the cooling of the planet, which stirs up buoyant fluid from the surrounding liquid.

'similar to what happens in a lava lamp,' said Wiess.

'We have recently argued from magnetic studies of Apollo samples that the moon also generated a dynamo in its molten metal core.

'Our data suggest that, despite the moon’s tiny size — only 1 percent of the Earth’s mass — its dynamo was surprisingly intense (stronger than Earth’s field today) and long-lived, persisting from at least 4.2 billion years ago until at least 3.56 billion years ago. 

'This period, which overlaps the early epoch of intense solar system-wide meteoroid bombardment and coincides with the oldest known records of life on Earth, comes just before our earliest evidence of the Earth’s dynamo.' 

The moon today does not have a global magnetic field. 

However, moon rocks that astronauts collected during the Apollo missions suggested the moon once had a magnetic field billions of years ago.

But scientists were uncertain whether the moon generated a magnetic field the same way Earth does, or if the magnetic fields seen on the moon were instead produced by outside forces. 

 The moon today does not have a global magnetic field. However, moon rocks that astronauts collected during the Apollo missions suggested the moon once had a magnetic field billions of years ago.

For instance, cosmic impacts on the moon could have sparked super-heated plasma that generated strong, brief magnetic fields, explaining the magnetized rocks the astronauts discovered. 

Weiss and former MIT student Sonia Tikoo's review, published in Science, believe the corew ould have been 'a convective dynamo powered by crystallization of an inner core could potentially sustain a lunar magnetic field for billions of years,' he told MIT News.

'An exotic dynamo mechanism that could explain the moon’s strong field intensity is that the core was stirred by motion of the solid overlying mantle, analogous to a blender. 

'The moon’s mantle was moving because its spin axis is precessing, or wobbling, and such motion was more vigorous billions of years ago, when the moon was closer to the Earth. '

 

@highlight

Lunar dynamo was  a molten, churning core at the centre of the moon

@highlight

Powered an intense magnetic field for at least 1 billion years that was far stronger than Earth's is today

@highlight

Researchers are still baffled by how it was powered, and when it ended