By
Sarah Griffiths

You may have created a battery using a potato or a lemon in a physics class at school.

But one artist has taken the humble experiment a step further by using an array of fruit from limes to apples in order to make self-powered lights that light up his photographs.

Caleb Charland uses nails hidden inside the fruit which are connected with copper to make batteries, inspired by the classic potato classroom experiment.

Scroll down for video

A bright idea: An artist has taken the humble potato battery experiment a step further by using a vast array of fruit from limes to oranges (pictured) in order to make self-powered lights

The popular school experiment involves inserting two electrodes made of different metals into a potato or lemon to generate a small amount of electricity.

Almost any liquid or moist object that has enough ions to be electrically conductive can serve as the electrolyte for a cell.

The fruit/vegetable battery is a simple type of electrical battery that illustrates their main components.

They are used in schools to illustrate the type of chemical reaction - oxidation-reduction - that occurs in batteries.

A piece of zinc (such as a galvanised nail) and a piece of copper (wire or a penny) are used as electrodes, while the juice inside is the electrolyte.

Several lemons or potatoes can be wired together to form a more powerful battery that will power a light, buzzer or digital clock.

Fruit batteries are similar to the first electrical battery invented in 1800 by Alessandro Volta, who used brine (salt water) instead of lemon juice.

The artist, from Bangor, Maine, transforms the fruit into electrochemical cells, which he arranges artistically before taking long-exposure photographs of his work in a bid to highlight the potential of sustainable energy.

The fruit itself provides enough light to illuminate the photographs, which are all taken in the dark.

He writes on his website: ‘To understand the world and to profit from it one must interact with it, one must experiment.

‘My practice as an artist combines a scientific curiosity with a constructive approach to making pictures.

‘I utilise everyday objects and fundamental forces to illustrate experiences of wonder.

Mr Charland explained that his Back to Light project ‘expands upon a classic grade school science project, the potato battery.

Juice to make juice: Caleb Charland uses nails hidden inside the fruit, such as limes (pictured) which are connected with copper to make batteries, inspired by the potato classroom experiment

Beacon of hope: The artist
transforms the fruit into electrochemical cells, which he arranges 
artistically before taking long-exposure photographs of his work in a 
bid to highlight the potential of sustainable energy. A quirky apple lampshade is pictured left and a citrus light, right

Illuminating: The fruit itself provides enough light to illuminate the photographs, which are all taken in the dark. At first glance, this arrangement looks a little like the solar system

‘By 
inserting a galvanised nail into one side of a potato and a copper wire 
in the other side a small electrical current is generated. The utter 
simplicity of this electrical phenomenon is endlessly fascinating for 
me.’

He
 believes that the fact that so many people have conducted the 
experiment when they were young speaks to a common curiosity that humans
 have in understanding how the world works ‘as well as a global concern
 for the future of Earth’s energy sources.

Mr Charland said: 'My practice as an artist combines a scientific curiosity with a constructive approach to making pictures.' Here, jars and bottles of liquid are used as batteries to produce light

Shining example: A  small electrical current is generated by inserting a galvanized nail into one side of the fruit and a copper wire in the other side. These apples have been connected to make a circuit capable of powering a small light (pictured)

‘My hope is that these photographs function as micro utopias by suggesting and illustrating the endless possibilities of alternative and sustainable energy production,’ he said.

‘The cycle that begins with the light of our closest star implanting organic materials with nutrients and energy, is re-routed in these images, Back to Light, illuminating Earth once again.’

Tree of knowledge: Mr Charland explained that his Back to Light project 'expands upon a classic grade school science project, the potato battery'. Here, the principles of the experiment - and plenty of apples -are used to illuminate the tree with a make-shift chandelier

'My hope is that these photographs function as micro utopias by suggesting and illustrating the endless possibilities of alternative and sustainable energy production,' he said

@highlight

An artist in Bangor, Maine was inspired to create the fruit-powered lights by the popular potato battery classroom experiment

@highlight

Caleb Charland uses nails hidden inside the fruit which are connected with copper as well as a light bulb to make batteries and the fruit glow

@highlight

He arranges the electrochemical cells before photographing them

@highlight

His art aims to show people the potential of simple sustainable energy