A concept for the ‘Concorde of the tunnelling world’ has been revealed.

And if it ever becomes a reality, it could make high speed train travel from the UK to the US a reality.

The idea for the transport system of the future, was proposed in a competition run by think tank in a bid to boost business between Manchester and New York.

The future? A concept for a transatlantic train in a vacuum tunnel (illustrated) dubbed the ‘Concorde of the tunnelling world,’ has been proposed in a competition

The proposal, which was seen by IPPR North, claims that technological advantages could make the dream of a transatlantic train journey a reality and transform the economy in the north of England.

The train would be contained within a tube underneath the Atlantic Ocean, with a service running in a perfect vacuum.

‘The train is levitated in mid-air using electric magnets,’ said Simon Horton, a young professional who submitted the idea with several colleagues.

The proposal  claims that  a transatlantic train journey would transform the economy in the north of England, together with the region's own 'Hyperloop' (pictured) which would connect city airports

‘This reduces nearly all causes of friction and drag, enabling both huge speeds and a completely smooth (and silent) journey.’

Based on calculations by entrepreneur Elon Musk, who came up with the idea of a train that travels inside a vacuum tube, a journey between Manchester and New York City could take just four hours, if a maximum speed of 800mph (1,287kph) was achievable.

Paul Batty, another competition entrant under the age of 25, proposed a 'northern hyperloop,' which has much in common with Elon Musk’s designs for a Hyperloop vacuum train, only instead of connecting Los Angeles and San Francisco, the northern English version would link airports to a ‘superhub’.

Inside the tubes of Elon Musk's design, Hyperloop, pods are mounted on thin skis made out of inconel,an alloy already used by his SpaceX firm that can withstand high pressure and heat.

Air is pumped into the skis via small holes to make an air cushion, and each pod has air inlets at the front.

An electric turbo compressor compresses air from the nose and routes it to the skis and to the cabin.

Magnets on the skis, plus an electromagnetic pulse give the pod its initial thrust; reboosting motors along the route would keep the pod moving at just below the speed of sound so the system does not produce sonic booms.

Under the plans, individual airports would act as terminals within a single rapidly connected local, national and international rail and air network.

The English design also builds on Mr Musk’s vacuum tunnel concept by adding a propeller to the front of the train to force any remaining air resistance back.

Cities such as Manchester could also see other futuristic changes to their transport systems.

Sections of the road could be replaced by solar panels to generate power for the national grid, according to a group of students, or electricity could be generated by energy-capturing technology to convert noise energy to electricity intended to power electric cars, for example.

In another futuristic vision, the region’s roads would be equipped with wind-capturing technology, which would convert wind energy to electricity, made available to electric car drivers via vehicles charging points.

The transport system would reap benefits including a reduced reliance on fossil fuels and greater availability of renewable energy, the think tank said.

Under the plans, individual airports would act as terminals within a single rapidly connected local, national and international rail and air network. A train could run from Manchester (pictured left) to New York (right)

The design has much in common with Elon Musk’s plans for a vacuum train called the Hyperloop (illustrated), only instead of connecting Los Angeles and San Francisco, the Northern English version would link airports to a ‘superhub’

A 15-year plan called One North, submitted on behalf of the cities of Liverpool, Manchester, Leeds, Newcastle and Sheffield already features an interconnected transport system across air, roads, ports and rail, including the high-speed east–west rail route dubbed HS3.

It also includes a potential new tunnel through the Pennines to increase rail capacity.

Environmentally-friendly developments feature heavily in future plans with ideas for ‘green cities’, a carbon free north and even the creation of a Pennines National Park.

The park would span the Lake District and Yorkshire Dales National Parks to include the Pennines range, attracting tourism and jobs by playing on the heightened ‘status’.

It is the brainchild of Professor Ian Wray, who believes parts of the moors should be considered potential World Heritage Sites arguing they are ‘particularly rich in industrial archaeology’.

‘Some of these moors were the birthplace of a system of “proto-industrialism” which lit the fuse for the industrial revolution in Manchester and Yorkshire,’ he said.

The proposal, which was seen by IPPR North, claims that technological advantages could make the dream of a transatlantic train journey a reality, between Manchester and New York (both marked on the map)

One day, sections of road could be replaced by solar panels (illustrated with a concept image) to generate power for the national grid, or electricity could be generated by energy-capturing technology to convert noise energy to electricity intended to power electric cars, for example

Billionaire inventor Elon Musk has revealed he plans to build a test track for Hyperloop - a futuristic type of transport that would shoot capsules of passengers along a tube at around the speed of sound.

Mr Musk claims his solar-powered 'Hyperloop' could herald a revolution in travel - and is building the test facility to prove it.

He believes it would take just 30 minutes to travel the 381 miles (613km) from Los Angeles to San Francisco – half the time it takes in a plane – and likened the passenger experience to Disneyland's rocket ride Space Mountain.

Elon Musk's Hyperloop (an conceptual image is shown) could take just 30 minutes to travel the 381 miles (613 km) from Los Angeles to San Francisco – half the time it takes in a plane. He has likened the passenger experience to Disneyland's rocket ride Space Mountain

Now, the plans are beginning to take shape. Mr Musk tweeted: 'Will be building a Hyperloop test track for companies and student teams to test out their pods. Most likely in Texas.'

A new firm, Hyperloop Transportation Technologies, is developing plans to makes the tubes a reality - and it has recruited experts from around the world.

The crowdsourced firm has around 100 engineers on the projects, and nearly all of them have day jobs at companies like Boeing, Nasa, Yahoo!, Airbus, SpaceX, and Salesforce.

Mr Musk's idea is based on the pneumatic tubes that fire capsules of paperwork between floors in offices. In this case, the capsules would carry people – even cars – in low-pressure tubes to minimise turbulence and maximise speed.

On top of pylons is a hovering capsule inside a low-pressurized tube, which can reach speeds of up to 760 mph.

'The only resistance would be the air in front of the capsule, which we moved to the back by using a compressor,' Hyperloop CEO Dirk Ahlborn said.

At its launch, Musk described the Hyperloop design as looking like a shotgun, with the tubes running side-by-side for most of the journey, then closing at either end to form a loop.

Trains of capsules would shoot through the almost air-free tube at up to 760mph (1,223kph), accelerated by magnets which would also keep each pod on a steady course.

Each capsule would float on a cushion of air it creates as it speeds along – similar to an air hockey table.

While trains travelling through vacuum tubes could one day connect major US cities (illustrated), for now, a test track will be uilt to test the idea - most likely in Texas, according to a tweet

Capsules carrying six to eight people would depart every 30 seconds, with tickets costing around £13 ($20) each way.

In his proposal released online, Musk wrote: 'Short of figuring out real teleportation, which would of course be awesome (someone please do this), the only option for super-fast travel is to build a tube over or under the ground that contains a special environment.'

The proposed route of the first Hyperloop follows Interstate 5, which runs through the agriculture-rich Central Valley in California. It would take seven to ten years to build. Musk put the price tag at around £4billion ($2.6billion).

 

@highlight

The transatlantic train idea was one of the ideas were proposed in a competition run by Manchester-based think tank, IPPR North

@highlight

 The train would run between the northern English city and New York City 

@highlight

The train would be contained within a tube underneath the Atlantic Ocean, with a service running in a perfect vacuum, like Elon Musk's idea 

@highlight

A northern English version of his 'Hyperloop' has been proposed to connect airports and cities in the north of the country

@highlight

Roads made from solar panels are among other technologies suggested 