By 
Kathryn Blundell

PUBLISHED:

16:40 EST, 28 August 2013


| 

UPDATED:

02:12 EST, 29 August 2013

When the Cambridges proudly released their first family photos - with the snugly wrapped Prince George cradled in his mother's arms - the nation breathed a collective 'awww'. Swaddled in a simple shawl, the youngest member of the Royal Family was, we all agreed, what a newborn baby should look like.

After all, the image of the Virgin Mary and swaddled baby Jesus is one we've grown up to recognise as the embodiment of motherhood.

Well, not any more. Last week, grandmother Valerie Butcher inadvertently dragged the new prince and his devoted mother into a debate on the wrongs and rights of swaddling by writing an angry letter to a newspaper about an incident involving her four-week-old grandson, also called George.

Good enough for royalty: Prince George of Cambridge was seen wrapped in a swaddling shawl in his first official pictures

Valerie wrote that her daughter had taken George to her local clinic where she was 'sternly told off' for swaddling her child. What's more, she now has a note on her file saying that by swaddling, she 'is willing to put her baby's life at risk'. In short, she has been marked down as a bad parent.

Swaddling involves wrapping a newborn in a thin cotton sheet or blanket, so its arms are pinned against its body by the fabric, which is then secured under the child's body.

Many mums hail it as an easy way to settle very young babies as it makes them feel warm and safe.

As a bonus, by restricting the movement of the arms, swaddling suppresses the 'startle reflex', where babies suddenly - and often - throw out their arms in their sleep, waking themselves in the process.

Encouraging the trend: Baby Cambridge was also seen in the swaddling blanket when he left hospital with his parents and other new mothers and fathers have been following suit

Not too tight: Prince George had the blanket loosely wrapped around him on his first day out

Swaddling isn't advised for babies once they're capable of rolling over, as the cloth can end up over their  face, increasing the risk of suffocation and cot death - but many mothers still swear by it up to the age of around four months.

Does any of this sound like poor parenting? It certainly doesn't to me. I swaddled my children - both my daughter, who is now 17 years old, and my son, who is six - and I swear I got more sleep as a result.

However, there's an increasing body of opinion calling for an end to it, pointing to the danger of the baby overheating, and suggesting the practice could even damage their joints.

A 2009 study carried out by the universities of Bristol and Warwick indicated an increased risk of cot death in babies who were swaddled.

'If your baby doesn't like it, then don't force it. Swaddling has to be baby-led'

Of the group of infants in the study who succumbed to cot death between 2003 and 2006, 24 per cent were swaddled, compared with 6 per cent in a control group of healthy babies.

However, other factors, such as sleeping in the parents' bed or on a sofa, or being in poor health, may also explain the results.

The fear is that swaddling can send a baby's temperature spiralling out of control.

Janet Fyle, of the Royal College Of Midwives, says: 'A newborn is unable to regulate its own body temperature in the way an adult can. That's why the current advice for mothers is not to wrap their babies tightly or in heavy blankets, especially in warm weather. And a blanket should never be added to a swaddled baby.'

Professor Nicholas Clarke, a consultant orthopaedic surgeon at Southampton General Hospital, is firmly in the anti-swaddle camp. He says: 'We saw a huge resurgence in swaddling in 2011, generated by the suggestion it could ease colic (a condition where very young babies cry uncontrollably for no apparent reason), though I’ve seen no evidence to support this.

'That spike in popularity linked directly to an increase in the number of babies I saw with hip dysplasia - where the bones of the hip joint are not aligned correctly.

Parenting debate: Swaddled newborns tend to sleep better but some believe it isn't worth the risk

'Infants are born with very flexible joints, which are also under the effects of relaxin - a hormone women produce when they’re pregnant to loosen joints and make birth easier.

'So a newborn's joints are more prone to issues at this age than any other. They need to be able to bend their legs up and out at the hips.'

His concerns are clear: swaddling infants so their hips and knees are kept straight or together may increase the risk of hip dysplasia and dislocation. Yet many see Professor Clarke’s stance as an  over-reaction.

Midwife Janet Fyle says: 'I'm not sure it's such a big issue - why would anyone wrap their baby up to the extent that it's causing developmental problems? This only happens if you're rough with your baby, so it’s unlikely in my view.'

Childcare consultant and author Rachel Waddilove, who has worked as a maternity nurse for celebrities including Gwyneth Paltrow, is passionate about the benefits of swaddling.

'It's a wonderful way of ensuring babies feel safe and secure when put into their cots,' she says. 'I will often go to a home where every time the baby tries to drop off to sleep, his little arms go and he wakes himself up. I swaddle him, tuck him in tight and he will normally drop off happily and quickly.'

She rejects the suggestion that swaddling hurts babies. 'The fuss that is being made about it being bad for babies' hips is, I believe, unsubstantiated. If we were binding babies then that would be a different matter, but that's not the same as swaddling, where babies' legs aren’t restricted.'

She points out that the precautions she takes when swaddling are the ones any sensible mother would take.

'Obviously, you need to keep an eye on your baby’s temperature, by feeling at the base of his neck, to avoid the risk of overheating. But it’s a wonderful tool to help your baby settle and sleep well.'

And sleep, as any parent will tell you, is a big issue. In the early days, many parents feel lucky if they get four hours in a row, and I spent the first few weeks with each of my children wondering if I'd ever know what it felt like to be rested and focused again.

Under wraps

In Tudor times, swaddling involved wrapping the baby in linen bands from head to foot until nine months old

I was so demented with tiredness I often found myself in the middle of a task, like making up a bottle, and forgetting where I was and having to start all over again. Who wouldn't try every sleep trick in the book?

Yet teaching parents about swaddling has been gradually dropped from many antenatal courses.

Teresa Walsh, a midwife childbirth educator at London’s Portland Hospital, says: 'Although I don't mention swaddling as part of my baby-care classes because it's not a core skill, parents always bring it up - it's very fashionable at the moment.

'I swaddled my babies but I'm not sure I would now because the research on its main benefit - more sleep - isn't good enough to say it makes any difference. Studies show that at best a child might sleep for an extra half-hour.

'And I actually think allowing babies to wake slightly makes them learn to settle themselves back to sleep - a key skill if a baby's ever going to go through the night.'

Teresa encourages parents to try swaddling if they like - but to be mindful of their babies' reactions.

'If the baby settles and doesn't fight it, then I say go with it. But if your baby doesn't like it, then don’t force it. Swaddling has to be baby-led.'

Janet Fyle agrees. 'Midwives don't live with mothers or know their babies better than a parent does - we can only tailor advice in context with each family’s routine and preferences.'

Indeed, if swaddling is good enough for a future King, then surely it’s good enough for the rest of us?

@highlight

Prince Cambridge has been pictured in a swaddling shawl

@highlight

Many mothers hail swaddling as easy way to settle newborns

@highlight

But increasing body of opinion 
calling for an end to it

@highlight

They cite risk of baby 
overheating and damage their hip joints