By 
Ellie Zolfagharifard

PUBLISHED:

06:27 EST, 23 October 2013


| 

UPDATED:

06:29 EST, 23 October 2013

The sun may be 93 million miles away from Earth, but that hasn't stopped amateur astronomer Ralph Smith capturing these stunning close-ups from his garden.

Mr Smith, from Deeral in Queensland, Australia, used off the shelf equipment to capture the detailed snaps.

The stunning results show huge bursts of flames - known as prominences - leaping from the sun's surface.

The sun may be 93 million miles away from Earth, but that hasn't stopped amateur astronomer Ralph Smith capturing these stunning close-ups from his garden. Shown here is a close up of the sun showing a solar prominence on its surface

A prominence forms over timescales of about a day, and stable prominences may persist in the corona for several months, looping hundreds of thousands of miles into space.

The red-glowing looped material is plasma, a hot gas comprised of electrically charged hydrogen and helium.

The prominence plasma flows along a tangled and twisted structure of magnetic fields generated by the sun’s internal dynamo.

Mr Smith from Australia used off the shelf equipment to capture the detailed snaps. The stunning results show huge bursts of flames leaping from the sun's surface

Others highlight giant sunspots (in the centre of this image) which are often larger in size than Earth itself. Sunspots form from shifting magnetic fields at the sun's surface, and are actually cooler than their surrounding solar material

The red-glowing looped material is plasma, a hot gas comprised of electrically charged hydrogen and helium

An erupting prominence occurs when such a structure becomes unstable and bursts outward, releasing the plasma.

Others highlight giant sunspots which are often larger in size than Earth itself.

Sunspots form from shifting magnetic fields at the sun's surface, and are actually cooler than their surrounding solar material.

According to Nasa, the sun is currently in the midst of an active phase of its 11-year solar weather cycle and is expected to reach peak activity sometime this year.

Mr Smith said: ‘The sun is of course a star and it is forever changing. It does so by the minute, which makes it a fascinating subject to photograph.

‘It is a great hobby and one I love to share with anyone who is interested.'

Mr Smith said: 'The sun is of course a star and it is forever changing. It does so by the minute, which makes it a fascinating subject to photograph'

This image is a close up of the sun showing sunspots on its surface captured from a garden in Queensland, Australia using amateur equipment

The prominence plasma (pictured) flows along a tangled and twisted structure of magnetic fields generated by the sun's internal dynamo

Mr Smith captures the images using a small USB monochrome camera attached to a telescope, with H-Alpha filters.

He then shoots small video clips before stacking and processing the split-second frames in photoshop to build a single clear image.

Mr Smith, who has only been photographing the sun for around 14-months, added: ‘There are no text books on this subject and I have developed my own methods over time to get a good result.

‘All of my equipment is off the shelf amateur astronomy gear. It is all within reach of a normal working person.’

But despite having all the equipment, there are some things no one can prepare for - the weather.

Mr Smith added: ‘It is not always easy to capture these images as you have to contend with bad sight lines in the daytime due to clouds, wind and rain.’

The sun is pictured using a Calcium K-Line Filter. Mr Smith captures the images using a small USB monochrome camera attached to a telescope, with H-Alpha filters

According to Nasa, the sun is currently in the midst of an active phase of its 11-year solar weather cycle and is expected to reach peak activity sometime this year. Pictured here is a sunspot

Mr Smith, who has only been photographing the sun, and features such as these solar prominences, for around 14-months, said: 'There are no text books on this subject and I have developed my own methods over time to get a good result'

Ralph Smith seen with his telescope who captured the close ups of the sun in Queensland, Australia. 'All of my equipment is off the shelf amateur astronomy gear. It is all within reach of a normal working person,' he said.

@highlight

Ralph Smith from Deeral in Queensland, Australia has been photographing the sun for around 14 months

@highlight

The stunning results show huge bursts of flames - known as prominences - leaping from the Sun's surface

@highlight

Others highlight giant sunspots which are cooler areas of the sun and often larger in size than Earth itself

@highlight

'My equipment is off the shelf amateur astronomy gear. It is all within reach of a normal working person,' said Mr Smith