Life beyond the Earth seems 'inevitable' given the immensity of the universe, according to planetary scientist Dr Sara Seager (pictured)

Astronomers are standing on a 'great threshold' of space exploration that could see evidence of extra-terrestrial life being discovered in the next 20 years, an expert has claimed.

Life beyond the Earth seems 'inevitable' given the immensity of the universe, according to planetary scientist Dr Sara Seager.

In the coming decades, chemical fingerprints of life written in the atmospheres of planets orbiting nearby stars could be found by the next generation of space telescopes.

Writing in the journal Proceedings of the National Academy of Sciences, Dr Seager, from the Massachusetts Institute of Technology (MIT), said: 'We can say with certainty that, for the first time in human history, we are finally on the verge of being able to search for signs of life beyond our solar system around the nearest hundreds of stars.'

Astronomers now know that statistically, every star in our galaxy, the Milky Way, should have at least one planet, and small rocky worlds like the Earth are common.

'Our own galaxy has 100 billion stars and our universe has upwards of 100 billion galaxies - making the chance for life elsewhere seem inevitable based on sheer probability,' said Dr Seager.

In the next decade or two, a handful of 'potentially habitable' exoplanets will have been found with atmospheres that can be studied in detail by sophisticated space telescopes.

The first of these next generation telescopes will be Nasa's James Webb Space Telescope (JWST) due to be launched in 2018.

It will analyse the atmospheres of dozens of 'super-Earths' - rocky planets somewhat larger than our own planet - including several that could harbour life.

Studying a planet's atmosphere for signs of life involves capturing starlight filtering through its gases. 

In the next decade or two, a handful of 'potentially habitable' exoplanets will have been found with atmospheres that can be studied in detail by sophisticated space telescopes. The first of these next generation telescopes will be Nasa's James Webb Space Telescope (pictured) due to be launched in 2018

Different elements absorb different wavelengths of light, providing information about the atmosphere's make-up.

Living things, from bacteria to large animals, are expected to produce 'biosignature' gases that could be detected in a planet's atmosphere. They include oxygen, ozone, nitrous oxide, and methane.

The problem faced by scientists is that some of these, such as methane, can be generated by geological processes as well as life.

The likelihood of false positives could be reduced by searching for rarer biosignature gases more closely tied to living systems, such as dimethyl sulphide (DMS), and methanethiol, said Dr Seager.

But she pointed out that observations using telescopes such as the JWST, which will focus on backlit transiting planets that happen to passing in front of their parent stars, will be limited.

A 'starshade' is an umbrella-like screen tens of metres in diameter placed tens of thousands of kilometres in front of a space telescope lens. The starshade is designed to cast a shadow blocking out light from a star while leaving a planet's reflected light unaffected

Aliens are real - not little green men visiting Earth as depicted in movies, but rather microbial life in our own solar system and intelligent life beyond.

That’s according to two leading Search for Extraterrestrial Intelligence (Seti) researchers, who yesterday took part in a hearing at the House Committee on Science, Space, and Technology in Washington DC.

During the talk dubbed ‘Astrobiology and the Search for Life in the Universe’ in May, the scientists laid out the evidence and reasoning for believing we are not alone.

The speech was made by Dr Seth Shostak, Senior Astronomer at the Seti Institute in California, and Dr Dan Wethimer, Director of Seti Research.

And, they added, with adequate support it is likely we will find alien life in some form or another within 20 years.

Dr Wethimer said: ‘It would be bizarre if we are alone,’ he told the committee. ‘It would be a cramped mind that didn’t wonder what other life is out there.’

Maximising the chances of finding evidence of extraterrestrial life will require a technological leap to methods of directly imaging large numbers of exoplanets.

Such an undertaking is daunting, given that directly imaging an Earth-like exoplanet is equivalent to picking out a firefly in the glare of a searchlight from a distance of 2,500 miles.

Yet two techniques now under development could make direct imaging of Earth twins possible.

One involves specialised optics to block out interfering starlight and reveal the presence of orbiting exoplanets.

The other is the 'starshade' - an umbrella-like screen tens of metres in diameter placed tens of thousands of kilometres in front of a space telescope lens.

The starshade is designed to cast a shadow blocking out light from a star while leaving a planet's reflected light unaffected.

'To be confident of finding a large enough pool of exoplanets to search for biosignature gases, we require the ability to directly image exoplanets orbiting 1,000 or more of the nearest sun-like stars,' said Dr Seager.

She added: 'We stand on a great threshold in the human history of space exploration...If life is prevalent in our neighbourhood of the galaxy, it is within our reach to be the first generation in human history to finally cross this threshold and learn if there is life of any kind beyond Earth.'

'Our own galaxy has 100 billion stars and our universe has upwards of 100 billion galaxies - making the chance for life elsewhere seem inevitable based on sheer probability,' said Dr Seager. An artist's impression of an alien planet is pictured

@highlight

Life beyond Earth seems 'inevitable' given the immensity of the universe

@highlight

The comments come from MIT-based planetary scientist Dr Sara Seager

@highlight

Improving chances of finding alien life will require a technological leap

@highlight

Two techniques under development could help the search significantly

@highlight

One involves using specialised optics to block out interfering starlight

@highlight

The other is the 'starshade' - an umbrella-like screen tens of metres in diameter placed tens of thousands of kilometres in front of a telescope