The young men in tangerine shirts trooped off Bloomfield Road to a standing ovation as another bewildering week in the life of Blackpool FC reached its bizarre conclusion.

Days of anger and recrimination had ended in mystery and farce. For the most part, that pitifully small but enthusiastic crowd was applauding perfect strangers. Even the most ardent home fan could not have named more than a handful of Blackpool’s unlikely heroes.

A summer of bitterness and confusion had left Blackpool with a grievously depleted first-team squad. At one stage last week, the club employed just eight fully fledged professional footballers. A tour of Spain had been cancelled, just a single pre-season friendly had been played and there was real doubt they would be able to field a side for Saturday’s match with Burnley.

Discontent: Blackpool fans vent their anger at chairman Karl Oyston before the game with Burnley

Oyston out: Blackpool fans want Karl Oyston out of the club after a disastrous few years for the club

The club’s owner, Karl Oyston, had attracted even more than his usual ration of anger and contempt in these parts. Rumours and accusations were running wild and the entire dark pantomime was expressed in the pre-match message on the public address. ‘The Seasiders team will be — No1: Triallist... No3: Triallist...’ And so on. A few old favourites had survived the summer but several of the new men had arrived under conditions of anonymity.

This phenomenon was seen at its most vivid in the second half, when the substitutes started to arrive. Again, the announcer could not enlighten the small assembly. The outcome was that 2,389 patrons now believe their new players are, respectively: No15, No14, No13 and 16 and last, but by no means least, No17, who came on with eight minutes left.

Many a club would infuriate their fans with such cavalier treatment but at Blackpool they just chuckled. ‘Where are they finding them?’, asked one lady in the Matthews Stand. ‘Do you think we’re actually paying all these people?’ Her husband snorted cynically: ‘Not if Oyston has got anything to do with it.’

In truth, the most savage reaction against Oyston and his father, the former chairman Owen, had been vented outside the ground before the match.

A crowd of about 120 gathered with banners and flags chanting: ‘Get out of our club, get out of our club, two greedy b******s, get out of our club!’

The Oystons have heard far worse over the years and the fans’ advice is unlikely to be obeyed. And not all the supporters are as antagonistic. But the abject failure of Blackpool’s owners to build upon their single, immensely lucrative season in the Premier League is the chief cause of the bitterness. The season of 2010-11 was their year in the sun. Indeed, for one, bright, shining moment, they sat at the summit of the English game after beating Wigan 4-0 in the opening match. But despite occasionally delighting with their attacking football, they survived for only that season.

Their financial reward amounted to some £40million plus substantial ‘parachute payments’, the last of which is almost due. They have a fine, modern ground and, it is said, many millions in the bank. But investment in the team has been negligible. The bookmakers have made Blackpool favourites for relegation at 8-13 on.

Hard work ahead: Jose Riga has a huge task ahead of him at Blackpool this season

Who are you: Darren Ambrose was one of the trialists who come on for Blackpool against Burnley

And yet Saturday, against a side who are preparing for their own shot at the top division, Blackpool played with spirit, a surprising degree of organisation and the vaguely desperate air generated by pros in search of a contract. By contrast, Burnley were rather less than ordinary. Although their own pre-season preparations have been infinitely more serene than Blackpool’s, they swiftly ran short of ideas and enterprise.

They will improve, of course, but after taking 68 minutes to score the only goal of the game against the team with no names — Marvin Sordell striking a volley with casual authority — a hefty degree of improvement will be essential.

Glenn Bowley, chairman of the Blackpool Supporters’ Association, takes the view that the Oystons are going nowhere and so the fans will have to work with them. Blackpool Supporters’ Club take a quite different view. 

‘Oyston is clearly to blame for the chaos at the moment,’ said Bowley. ‘With so few players signed and ready, he has to be. He’s the most hated man in Blackpool and possibly with good reason. But he has things in his favour. He refuses to deal with agents, which takes some principles, even if it sometimes seems a bit naive. And he has put money into the ground, to set alongside the money the family has supposed to have taken out. So there’s a balance to be struck.’

According to Bowley, the club made £40m from that Premier League season, plus the parachute payments. ‘We don’t have high expectations,’ he said. ‘There are more important things than football in Blackpool. There are areas of real deprivation round here. But still we take the club seriously.

‘Look, the training ground is not fit for purpose. We’ve battled relegation for two seasons running. And all this is the result of bad management by Karl Oyston, basically.’

And this from a man regarded as a moderate by the Blackpool followers.

Rise high: Nathan Delfouneso has penned a permanent deal at Blackpool after two previous loan spells

New beginnings: Jacob Mellis will be looking to get his career back on track at Blackpool

Naturally, it would have been helpful to hear from Oyston himself but he was not only unavailable for comment, he also banned the Mail newspapers from the Press box. And Oyston was not alone in his pique. His new manager Jose Riga refused to comment after the game. He is said to be on unfriendly terms with his employer. He had no notes in the programme and the dwindling band of fans have no notion of what he is thinking. Such is the way of things at Bloomfield Road.

Yet some things never change in this rackety old town. When the storm was done, Blackpool landmarks emerged from the driving rain in all their gaudy glory; Tower and Pier and Nellie Dean’s Karaoke Bar.

I remembered the old chap shuffling away from the Matthews Stand when the storm was brewing. He zipped his wet-top to his neck. ‘They reckon it’s in for four days, is this,’ he remarked. ‘Still, it’s good for the garden, eh?’

That’s the thing about Blackpool fans, they like to see the bright side in the darkest situations. It is a gift which will be sorely needed for the new season.

@highlight

Blackpool fans were protesting against owner Karl Oyston on Saturday

@highlight

There are only 13 players contracted to the club currently

@highlight

Just four years ago the Tangerines were preparing for the Premier League 