The parents of 43 students who went missing in Mexico after being attacked by police 'need protection' from enraged campaigners trying to demonise their children, the UN has said.

The group of trainee teachers vanished ten weeks ago in Iguala after being detained by local police and, critics say, thrust into the hands of a criminal gang.

Since their disappearance hundreds have marched across the south American country calling for authorities to bring them back alive and establish how they came to be abducted. 

Scroll down for videos 

Parents of missing students 'need protection' from online campaigners 'trying to vilify' their sons, the UN said

In recent weeks however a campaign has been launched to suggest that the students, all enrolled at a rural teacher's college in the southern state of Guerrero, had a hand in sinister criminal activity.

Yesterday the UN Human Rights High Commission said the youngsters' parents were in danger in light of critics' demonstrations. 

'Some are starting to vilify and insult the disappeared students and demonise their parents and their demands,' Javier Hernandez, the Commision's representative in Mexico told the Guardian.  

'The vast wave of protest generated by the case of the 43 students needs to be protected.'

Protests have been widespread across the country since the students' disappearance more than two months ago. 

No traces of the men's bodies have been found after investigators ruled out a mass grave in the state where they were last seen as a possible burial site. 

Victims: The above poster shows the 43 missing students and offers a reward for their recovery more than ten weeks after the trainee teachers vanished after being taken into police custody

Demonstrators take part in a protest in Guadalajara city demanding justice in the case of the 43 students that went missing in Iguala, Guerrero state, last September 26

A drug gang has confessed to killing the group, claiming the students were handed over to them by local policemen in Iguala following clashes on September 26. 

Prosecutors have not confirmed this as true, with the victims' families awaiting DNA results from charred corpses which have been sent to an Austrian university. 

The case has put a spotlight on Mexico's struggle to end corruption and impunity amid a drug war that has left 100,000 people dead or missing since 2006.

 

 

 

 

@highlight

Parents of missing men are 'at risk',said UN Human Rights Commission

@highlight

Campaign to try to 'vilify' the missing trainee teachers spread online

@highlight

Men vanished ten weeks ago from Iguala in southern state of Guerrero 

@highlight

They had been taken into local police custody before disappearing 

@highlight

Widespread fears the men were thrust into hands of violent drug gang 