From national security data to secret company information, some of the most sensitive documents are stored on computers that are never connected to the internet.

This precaution of keeping such information on an ‘air-gap’ network is popularly considered the safest way to prevent hackers from accessing it.

But computer scientists from Ben-Gurion University in Israel have found a way to attack these machines and ‘steal’ the confidential data.

Scroll down for video 

Hackers from Ben-Gurion University in Israel have found a way to attack computers that are not connected to the internet - as used by many companies to store sensitive data - and steal data. The finding means that some high profile machines may not be as safe from hackers (illustrated) as previously thought

'Air gaps' currently used to protect important computers could be rendered useless.

An air-gap or air wall is a network security measure. 

It was designed to make sure secure computer networks are physically isolated from unsecured networks, such as the internet or a local area network.

The researchers from Israel designed computer software that logs keystrokes.

This software transmits these strokes via FM radio signals generated by the computer's graphics card. 

The data is picked up by a nearby mobile, equipped to pick up radio signals.

In the example case, the researchers used a Samsung Galaxy S4 and had to plug in the headphones to get the radio receiver to work.

This can be done without being detected by the user, but does rely on the software being installed on the computer in the first place.

Since FM radio signals can travel over long distances, the receiver could be placed in another building. 

A new method of protecting these machines will now have to be found, claimed the researchers. 

In an experiment designed to highlight the danger facing machines in an air-gap, the researchers assumed that the attacker has already broken into a protected system to sneak out new data.

An air-gap or air wall is a network security measure. 

It was designed to make sure secure computer networks are physically isolated from unsecured networks, such as the internet or a local area network.

The researchers from Israel designed computer software that logs keystrokes,  Ars Technica reported.

This software transmits these strokes via FM radio signals generated by the computer's graphics card. 

The signals are picked up by a nearby mobile, equipped to pick up radio signals.  

In the example case, they used a Samsung Galaxy S4 and had to plug in the headphones to get the radio receiver to work.

This can be done without being detected by the user, but does rely on the software being installed on the computer in the first place. 

And since FM radio signals can travel over long distances, the receiver could be placed in another building. 

A new method of protecting these machines will now have to be found, claimed the researchers.  

They demonstrated that a hacker could use it to collect data from devices protected by an air-gap in a paper, which they presented at the IEEE 9th International Conference on Malicious and Unwanted Software (Malcon).  

'The scenario is that you go to a secure facility and leave your cell phone at the entrance,’ said Dudu Mimran, chief technology officer for the cyber security labs at the university. 

‘The virus will send the data to your phone.’

‘Such a technique can be used potentially by people and organisations with malicious intentions and we want to start a discussion on how to mitigate this newly presented risk.’

Commentators said the AirHopper technique is a refinement of methods used by intelligence agencies since the mid 1980s to bypass machines protected with passwords (stock image) and other measures

Last year, German computer scientists proved that malware can travel between machines using sound waves that are inaudible to unsuspecting humans.

Using built-in microphones and speakers in laptops, the researchers managed to transmit passwords and small amounts of data between machines 65ft (19 metres) away from each other.

They came up with a hack using sound to steal data from protected machines and suggested that noise could be used to pass data between target computers and the ‘hacker’ machine.

The researchers chose to use sounds that are too high pitched for humans to hear and harnessed the microphone and speakers in a Lenovo T400 computer to transmit keystrokes from one computer to another.

Commentators say the AirHopper technique is a refinement of methods used by intelligence agencies since the mid 1980s.

It was known that electromagnetic signals could be intercepted from computer monitors to reconstitute the information being displayed.

Hackers have turned monitors into radio-frequency transmitters and it is thought that the US National Security Agency has used radio-frequency devices implanted in various computer-system components to transmit information and exfiltrate data.

AirHopper has the edge, however, because it uses off-the-shelf components such as a smartphone as a receiver.

But the method is still slow, transferring less than 60 bytes a second and only at a distance of between 3ft (one metre) and 22ft (seven metres).

This allows someone with a smartphone to steal data from nearby systems and send it to another hacker.

'This is the first time that a mobile phone is considered in an attack model as the intended receiver of maliciously crafted radio signals emitted from the screen of the isolated computer,’ the researchers said in a statement.

The university's findings have reignited a discussion about whether air gap networks are still effective and the experts are now working on a way of protecting machines from such a breach.

The only measure they know of so far is to lock computers in metal enclosures and within walls that are thick enough to disrupt radio frequencies, stopping the transmission of sensitive data.

@highlight

Sensitive machines are often protected on an offline 'air-gap' network

@highlight

This is considered to be the most effective way to keep data safe

@highlight

But computer scientists from Ben-Gurion University, Israel, have found a way to attack machines and 'steal' data, called the AirHopper method

@highlight

They used a smartphone capable of receiving FM signals

@highlight

Experiment means new protective measures will have to be found 