Majid Haq, Scotland’s leading wicket-taker and most capped player, has been forced to fly home from the World Cup after a controversial tweet

One of Scotland’s most successful cricketers has been sent home from the World Cup in disgrace after suggesting his axing from a match was racially motivated.

Majid Haq, the country’s leading wicket-taker and most capped player, was ordered to fly back early from Australia for breaching the team’s code of conduct.

Haq was not selected for the team that lost to Sri Lanka in Hobart yesterday and later tweeted: ‘Always tougher when your in the minority! #colour #race’, before later deleting the post.

After the match, Cricket Scotland broke the news in a brief statement that 32-year-old Haq was coming home early, adding: ‘No further statement will be issued until internal processes have been completed.’

The Paisley-born cricketer now faces a disciplinary hearing which could decide whether his distinguished ten-year career continues or is brought to an ignominious end.

The spin bowler, who made his first-class debut with the national team in 2004, suffered mixed fortunes in the World Cup in which Scotland has lost all five pool matches so far. 

It has a last game on Saturday in which to register a win, but that’s a tall order against four-time champions and co-hosts Australia.

Haq took three wickets in Scotland’s first four matches, and was dropped after bowling figures of 0-49 and scoring only one run in the defeat to Bangladesh at Nelson in New Zealand on March 5.

In the match against England on February 22, offspinner Haq dismissed opener Moeen Ali to claim a record 257th wicket for Scotland. 

Former England all-rounder Ian Botham and ex-coach David Lloyd ruffled feathers when they branded the Clydesdale Cricket Club bowler a ‘lobber’ in their TV commentary.

At the time, Scotland’s director of cricket Andy Tennant, a specialist spin coach, came to his player’s defence, insisting he was ‘world class’. 

Tennant said: ‘The commentators kept going on about how slowly Maj was bowling but his flight and dip in the air is what makes him a special bowler.

Haq was dropped from Scotland's squad for their defeat to Sri Lanka yesterday after bowling figures of 0-49 and scoring just one run in the previous game, but suggested the move was racially motivated

‘What they portrayed as a weakness is actually a strength. I think the remarks came across as ill-informed. Majid should be rightly proud of what he has achieved for Scotland and I’m sure he’ll go on to take many more wickets for his country.’

Haq holds the Scottish record for most international cricket caps – 209 – and was presented with a trophy for becoming lead wicket-taker following the England match.

Coach Grant Bradburn said in a statement: ‘It is a huge honour and fantastic achievement for Majid, who now becomes Scotland’s leading wicket-taker of all time. 

'As such a loyal servant to Scotland Cricket, it is especially appropriate for Majid to achieve this milestone during our World Cup campaign.’

Coach Grant Bradburn had previously praised Haq when he collected a record 209th cap for Scotland, but his tweet has since dampened the mood

However, the buoyant mood in the Scotland camp generated by Haq’s achievements has been dampened by his tweet. 

A Cricket Scotland statement yesterday said: ‘Following a breach of Cricket Scotland’s internal code of conduct, international team member, Majid Haq, is travelling home from the ICC World Cup.

‘No further statement will be issued until internal processes have been completed in due course.’

Haq, whose family is of Pakistani heritage and ran a curry restaurant in Glasgow, was brought up in Paisley, Renfrewshire, attending Castlehead High School and Reid Kerr College.

He later graduated in accountancy at the former University of Paisley.

He worked part-time as an accountant before switching to cricket full-time six years ago.

In an interview last month, Haq revealed that the last World Cup held in Australia and New Zealand, in 1992, helped him fall in love with the game, with Pakistan’s victory in the final against England a seminal moment.

BBC radio commentator and former England off-spinner Vic Marks said yesterday he was ‘shocked’ that Haq’s tour should end in such fashion.

He said: ‘I understand why any player would be really disappointed about being dropped – it’s a horrible feeling, especially if you are a senior player. 

'I can also understand from the Scottish selectors’ point of view that it was an opportunity to blood a talented young offspinner and that might be why they took the step to drop Haq.

‘I guess the authorities were left with no real option once he’d delivered his tweet. They had to take pretty severe action.’

 

@highlight

Majid Haq was dropped from Sr Lanka match after indifferent form

@highlight

He tweeted: 'Always difficult when your [sic] in the minority #colour'

@highlight

Cricket Scotland said the leading wicket taker has been sent home

@highlight

Say they will be investigating and cannot comment any further 