By 
Rob Waugh

PUBLISHED:

09:33 EST, 19 March 2012

 | 

UPDATED:

07:18 EST, 20 March 2012

YouTube is successfully transforming into a full-blown web TV service - site users are staying 60 per cent longer than they did a year ago.

The average time spent watching video on Google video sites is now 418.2 minutes per user, per month, according to Comscore data.

The shift is credited to YouTube's recent relaunch, which added a focus on TV-like 'Channels' and longer, professionally made shows.

Google staff said that subscriptions to the site's 'Channels' have gone up 50 per cent since the 'new look' launched in December.

New look: The new look gathers 'Channels' in the black navigation bar on the right hand side of the 
page making it more like Google's homepage

'The data is a sign that YouTube’s sizeable audience base is beginning to tune in for longer periods of time, rather than simply snacking and leaving,' said PaidContent.

'That result is at least in part a function of YouTube’s decision to offer more compelling, longer-form content.'

Three billion videos are viewed on YouTube every day.

Google
is attempting to 'shift' the way people use the site, with the 
increased focus on 'Channels' a clear attempt to mirror services offered
by TV stations.

The new look has made it easier to find 'channels' from the front page, with a black 
navigation menu on the left hand side which allows users to organise 
channels, rather than simply search for video using Google search.

'More and more, behind every great video is a great Channel,' said YouTube via its official blog.

Professional
approach: Advertisers prefer not to be next to
user-generated content so earlier this year, YouTube announced a range 
of professionally produced channels from celebrities such as Madonna

'DIY' channels allow users to earn a 
percentage by signing up for Google's 'Partner' programme, where they 
earn some of the advertising revenue generated by the site.

But YouTube will also offer professional content.

The site launched 100 new 
professionally produced channels in partnership with stars such as singer 
Madonna and actor Ashton Kutcher.

Owner Google says that the channels will be on-demand services, each offering 25 hours of programming a day.

Many big-ticket advertisers are relucant to be seen 
alongside 'user-generated' videos, and would be happier with 
professionally produced, star-studded content.

The money is an advance on advertising 
money - Google is expected to recoup its outlay.

@highlight

Site users now stay for 418 minutes per month

@highlight

Increase of 60% on last year, say Comscore figures

@highlight

Comes in wake of relaunch to become more TV-like

@highlight

Subscriptions to Channels have risen 50%