Twitter users are inadvertently revealing their location in updates on the social media channel, an expert claims.

A study that sampled more than 15 million tweets, found that one in five updates give away a user's whereabouts, which could present unwelcome opportunities for criminals.

The research provides important factual data for a growing conversation about online privacy and third-party commercial or
 government use of geo-tagged information.

This heat map shows the density of all tweets during the study collection period where the location was identifiable through ambient information or direct sharing

The University of Southern California (USC) study, which was published in the International Journal of Geoinformatics used a custom-built app to examine how many people willingly and accidentally publicise their presence on Twitter.

Lead author Chris Weidemann, a graduate 
student in the Geographic Information Science and Technology (GIST) 
online master's program at USC, said: 'I'm a pretty private person, and I wish others would be more cautious with the types of information they share.'

'There are all sorts of information that can be gleaned from things outside of the tweet itself.'

Twitter has approximately 500 million active users, who are expected to tweet 72 billion times in 2013.

Reports have shown that about 6 per cent of users opt-in to allow the platform to broadcast their location with every tweet.

But that's only part of the footprint Twitter users leave, and even users who do not willingly 'tag' their location, they may be inadvertently revealing where they are, the study shows.

Twitter has approximately 500 million active users, who are expected to tweet 72 billion times in 2013. Reports have shown that about 6 per cent of users opt-in to allow the platform to broadcast their location with every tweet

To get a fuller sense of what publicly accessible data might reveal about Twitter users, Mr Weidemann developed an app called Twitter2GIS, to analyse the metadata collected by Twitter, including details about the user's hometown, time zone and language.

The data, generated by Twitter users and publicly available through Twitter's application programming interface (API) and Google's Geocoding API, was then processed by a software program, which mapped and analysed the data, searching for trends.

During the one-week sampling period of the study, roughly 20 per cent of the tweets collected showed the user's location to an accuracy of street level or better.

Many Twitter users divulged their physical location directly through active location monitoring or GPS coordinates.

But another two per cent of all tweets – equating to about 4.4 million tweets a day – provided so-called 'ambient' location data, where the user might not be aware that they are divulging their location.

Mr Weidemann said: 'The downside is that mining this kind of information can also provide opportunities for criminal misuse of data.

'My intent is to educate social media users and inform the public about their privacy.'

An increasing number of social media platforms (pictured) allow users to share their location. During the one-week sampling period of the study, roughly 20 per cent of the tweets collected showed the user's location to an accuracy of street level or better

In addition to being a graduate student at USC, Weidemann works for a company that builds geographic information systems for the federal government.

He initially developed Twitter2GIS as part of a project for a course taught by Jennifer Swift, associate professor of spatial sciences, who said the app 'will help create an awareness among the general population about the information they divulge.'

Weidemann is a self-described 'conservative' Twitter user, using the social media channel infrequently and has the privacy set to not share any location information about his tweets.

Still, in the course of doing this study, he turned Twitter2GIS on his own account and was surprised at the specificity the application was able to find about his location, based on a hashtag he used about an academic conference.

'This research has been fun and a little scary,' he said.

@highlight

A U.S. scientist found 20% of the tweets collected showed the user's location to an accuracy of street level or better

@highlight

Research provides data for a growing conversation about online privacy and third-party commercial or
 government use of geo-tagged information

@highlight

The USC study warned the information can provide opportunities for criminal misuse of data