Twitter on Thursday reported its revenue nearly doubled in the final three months of last year, but user growth fell short of analyst expectations.

'We closed out the year with our business advancing at a great pace,' said Twitter chief executive Dick Costolo.

Revenue hit $479 million in the fourth quarter, up 97 percent from $242.6 million in the same period a year ago.

Twitter on Thursday reported its revenue nearly doubled to $479 million in the final three months of last year, as its quarterly loss shrank to $125 million ©Leon Neal (AFP/File)

The number of active monthly users of the San Francisco-based one-to-many messaging service monthly grew to 288 million -- just four million more than in the previous quarter.

That figure fell short of expectations -- analysts had predicted the figure would climb to 292 million.

About 80 percent of the people using Twitter monthly connected with the service using mobile devices.

Its quarterly loss shrank to $125 million, as compared with a $511 million loss a year ago.

The number of active monthly users of the San Francisco-based one-to-many messaging service monthly grew to 288 million -- just four million more than in the previous quarter.

That figure fell short of expectations -- analysts had predicted the figure would climb to 292 million.

About 80 percent of the people using Twitter monthly connected with the service using mobile devices.

Twitter has also struck a deal with Google to make its 140-character updates more searchable online.

In the first half of this year, tweets will start to be visible in Google’s search results as soon as they are posted, thanks to a deal giving the Web company access to Twitter’s 'firehose', the stream of data generated by the microblogging service’s 284 million users. 

Twitter shares spiked nearly 10 percent aftermarket, as the messaging service shrank losses and nearly doubled quarterly revenue by drawing more users and expanding its advertising offerings.

Shares jumped over 9 percent in aftermarket trading.

Twitter's user growth continued to lag other popular social networks. 

The company had 288 million monthly users at the end of the quarter, up 20 percent from a year earlier. 

But the pace of growth slowed in the fourth quarter, something Twitter attributed to changes in the way third-party apps integrate Twitter. 

CEO Dick Costolo said Twitter expects to add a similar number of net users in the first quarter as it did in the first three quarters of 2014.

Earlier today Twitter’s chief executive took personal responsibility for the social media website’s problems in dealing with abuse reported by users.

Dick Costolo admitted that Twitter ‘sucks at dealing with abuse and trolls’ in an internal memo seen by The Verge.

In it, he said that he is embarrassed by the way the company handles abuse and that it must take stronger action in the future. 

The company had 288 million monthly users at the end of the quarter, up 20 percent from a year earlier.

By comparison, LinkedIn Corp. on Thursday reported 347 million users through the end of December. The Facebook-owned photo sharing app Instagram, meanwhile, recently surpassed 300 million users. None come close to Facebook, however, with its 1.39 billion members.

The San Francisco-based company was still privately held for part of the year-ago quarter - it went public in November 2013. 

For the final three months of 2014 it had losses of $125.4 million, or 20 cents per share, down sharply from a loss of $511.5 million, or $1.41 per share, a year earlier. 

Excluding one-time items, Twitter earned $79.3 million, or 12 cents per share - double the 6 cents expected by analysts, according to FactSet. 

 

@highlight

Just four million users have joined in last quarter, results reveal 

@highlight

Firm also revealed deal with Google to put tweets into search results

@highlight

Twitter’s chief executive took responsibility for  problems dealing with trolls