By
Ryan Gorman

PUBLISHED:
  
  
      18:54 EST, 6 January 2014
    
  
 | 
  UPDATED:
  
  
      18:54 EST, 6 January 2014

The next big thing is already here – touchless touchscreens.

Touching a phone's screen will soon be a thing of the past – so soon
the technology is only a software update away for some of the most popular
smartphones already on the market.

Touchscreen maker Synaptics unveiled technology Monday that
makes it possible to detect fingers from a quarter of an inch away. It’s called
‘Air Touch.’

No need to touch: Smartphones like the Samsung Galaxy S4 are able to be used without touching the screen, all they need is a firmware update

The technology has the ability to wake up a smartphone,
bring a keyboard onscreen or any number of tasks, according to NBC News.

Synaptics demonstrated the new functionality on a Samsung
Galaxy S4, but told NBC it could work on a number of recently released devices.

Touchscreens currently work by detecting electrical currents
that pass through a fingertip or stylus, and translate that to select links,
start apps and scroll.

Devices can also sense the electrical charge generated by
static electricity that results in shocking others, as NBC noted, but no
devices could take advantage of that until now.

A Synaptics ‘Air Touch’ demonstration viewed by NBC showed
to be ‘sensitive,
accurate… and very useful,’ but it is for now limited to only one application.

Just an update away: Many popular smartphones already on the market are able to use the technology

A
calendar app easily showed details for appointments and scrolled with ease –
without touching the screen. The
only thing holding the technology back is developer implementation, Synaptics
told NBC.

Fragmentation
among operating systems, multiple phone manufacturers and carrier restrictions
could make the road to touchless a long one, but at least it’s viable.

Synaptics is not putting all its eggs in one basket, it already produces touchscreens for several electronics companies.

Phone
makers have not yet commented on whether it will make it onto devices released
later this year.

@highlight

Touchscreen manufacturer Synaptics developed the technology

@highlight

Smartphones already released, including the Samsung Galaxy S4 could already take advantage

@highlight

It detects human fingers from up to a quarter of an inch away