By 
Sara Malm

PUBLISHED:

23:34 EST, 19 December 2012


| 

UPDATED:

05:08 EST, 20 December 2012

It is a monument to Wales' proud coal-mining history, celebrating one of the world's oldest energy sources.

But now the Welsh National Coal Museum is acknowledging power sources of the future - and installing solar panels.

The Big Pit museum has turned to renewable energy to power its buildings in Blaenafon, south Wales.

More than six per cent of Big Pit’s energy will be generated by 200 solar panels installed on the museum’s roof in a bid to reduce bills and carbon footprints, museum representatives said.

Green energy: The main building of the Big Pit National Coal Museum in Wales set to be fitted with solar panels

Despite complaints from some of the ex-miners who work as guides at the museum the most common reaction to the new energy source has been positive, the Guardian reported

'Coal is such an important part of Wales’ heritage and yet green energy will play a major part in its future,' Peter Walker, museum manager at Big Pit said. 'A solar powered coal mining museum is a fantastic way to celebrate this national journey.'

Mr Walker added that the panels will also bring economic benefits to the museum in reducing energy bills.

The panels are an initiative of community interest company Warm Wales, Cymru Gynnes, who said any surplus energy from the solar panels will be fed back into the national grid.

‘In
bringing together a major contributor to our Welsh heritage with new 
technology we’re demonstrating to all that even the 
most traditional of industries can gain substantial benefits through 
integrating the old and the new,’ Warm Wales' project director Craig 
Anderson said.

Hot spot: The Big Pit, staffed by former miners, was converted into a museum to honour Wales' proud coal mining history and is one of the country's most visited tourist destinations

Iron-y: Visitors are taken on underground tours of the working mine by which is set to have more than six per cent of its energy provided by solar panels

Big Pit is part of National Museum Wales, Amgueddfa Cymru, who highlighted the importance of bringing old and new energy sources together in planning for the future.

Mark Richards, Director of Operations and Deputy Director General for Amgueddfa Cymru, said he was ‘delighted’ to be moving towards green energy at the coal mining museum.

’As a working coal mine we are here to celebrate one of the world’s oldest energy sources and an enormously important aspect of Welsh heritage. But it is important to look to, and plan for, the future.’

The Big Pit won the Gulbenkian Prize 
for Museum of the Year in 2005 for 'keeping the story of British coal 
alive,' and is one of Wales most popuar tourist attractions.

The museum is visited by thousands of 
children every year who will now be able to learn about the industrial 
heritage of coal mining whilst kept warm by renewable energy.

@highlight

Big Pit museum to be partly powered by 200 solar panels

@highlight

Wales National Coal Museum gives guided tours of a working coal mine