Wayne Rooney told Harry Kane to go out and get a goal for himself when the Tottenham striker replaced him as a late substitute against Lithuania on Friday night – but admits that he was stunned when Kane did so within 79 seconds.

And Rooney, who says the excitement generated by Kane in the 4-0 win over Lithuania reminds him of his early games for England at the age of 17, insists that the 21-year-old will be better prepared to handle the adulation coming his way.

Rooney said: 'When I came off, I said to him, 'Go and get yourself a goal'. But I didn't think he would score so quick! It's fantastic.

Wayne Rooney (right) praised Harry Kane's immediate impact for England against Lithuania 

Kane (left) headed in England's fourth against Lithuania shortly after replacing England captain Rooney

Tottenham striker Kane celebrates scoring his first goal for England on his debut  

‘It's incredible really. You can feel the excitement around the country. You could tell when he came on everyone wanted him to come on and even he himself didn't think he'd score so quick, but we are all delighted for him. He's an exciting player. When you speak to him you can see he is a level headed guy and I am sure he has good people around him so will be able to cope with it.’

Rooney was a teenage sensation for England twelve years ago and caused even more of a stir when he starred in England’s 2-0 win over Turkey in 2003 as a 17-year old. 

And the England captain says there were elements of Kane’s substitute performance which reminded him of that game at the Stadium of Light in Sunderland.

‘There was one stage in the game, after his goal, where he ran down the left and took a few players on which reminded me of that,’ said Rooney. ‘But he will tell you himself he still has a lot to learn but at the minute he is scoring goals left right and centre and it is great for us as a nation to have that excitement around us. 

Rooney starred on his England debut against Turkey in 2003, at the age of 17

Rooney (centre) said Kane's debut reminded him of his first game for his country, 12 years ago

Rooney believes that Kane will go on and become an accomplished international player for England

‘There are things I could say to advise him but I think there are things you have to learn on your own, which I am sure he will do in the next year or two. 

'He is obviously a little bit older than I was and a bit wiser as I was 16 or 17 when I came in. But he is level headed and can cope.

‘I think people try to help you but it is best to learn on your own. When you are a young lad you do make mistakes and you have to learn from them because it will make you a better player.’ 

 

@highlight

Harry Kane scored 79 second into his England debut on Friday

@highlight

Kane netted a header against Lithuania as England won 4-0

@highlight

England captain Wayne Rooney admitted he was surprised by Kane 