By 
Emily Allen

PUBLISHED:

03:41 EST, 16 July 2012


| 

UPDATED:

05:06 EST, 16 July 2012

Harassed: Michael Austin was branded a 'crafty butcher' - slang for homosexual - by his workmates

A sales rep who was repeatedly accused by colleagues of being gay just because he was not a football fan has been awarded almost £44,000 for the harassment he suffered.

Michael Austin, 48, was also branded a 'crafty butcher' - slang for homosexual - by his workmates, who were avid Newcastle United supporters.

Newcastle employment tribunal heard that it was 'quite normal' in the North East for anyone who does not like football to be considered gay.

Mr Austin’s interest in the arts and viewing of a documentary about surrealist painter Dali were taken as 'further evidence of his homosexuality'.

Mr Austin, who is a married father-of-one, was also upset when he went to make a cup of tea - and then found porn had been put on his computer.

When he was seriously ill with swine flu, his boss Ian Laidlaw texted him saying: ‘Oink oink, lol’.

On his return to work at packaging firm Samuel Grant, his colleagues greeted him wearing surgical masks. In his very first week, one office worker pretended to suffer from Tourettes syndrome and swore at him endlessly.

Mr Laidlaw and a quarter of the firm’s staff at its Jarrow offices were Jehovah’s Witnesses and tried to ram their religion down Mr Austin’s throat, the tribunal heard.

He was encouraged to attend faith meetings and regularly lectured about religion.

When Mr Austin made a formal complaint about bullying and inappropriate homophobic and religious remarks, he was summarily sacked from his £25,000-a-year post.

The tribunal found that Mr Austin, of Durham, suffered 'atrocious' bullying by managing director Mr Laidlaw and fellow sales executive Tony Kozlowski.

It found Leeds-based Samuel Grant guilty of harassment on the grounds of sexual orientation and religion and victimisation.

The panel awarded Mr Austin £43,755 for loss of earnings and injury to feelings.

Bully: The tribunal found that Mr Austin suffered 'atrocious' bullying by managing director Ian Laidlaw (pictured) and fellow sales executive Tony Kozlowski

In its judgment, it ruled: 'It was a series of treatment by two people over a period of several months during which Mr Austin was treated atrociously, by being referred constantly to being gay, homosexual and a crafty butcher.

'It was extreme, frequent and very unpleasant. All he wanted to do was get out and get on with his job.

'He was subjected to unwanted religious discussions, then when he made a complaint was dismissed.

'It has obviously had a deep-seated emotional effect on Mr Austin.'

The tribunal also ordered that the company’s directors and managers must receive diversity training within six months.

Speaking after the recent judgment, Mr Austin said: 'The level of compensation was a pleasant surprise but this was never about the money. It was about me getting justice for what happened to me at Samuel Grant.

'I have always worked as a sales rep for blue chip companies. I thought it would make a nice change to work for a small, family-run business and make a big impact there.

'I was really looking forward to it but it was an absolutely unbearable, dreadful nightmare from day one. The only thing I can compare it to was the tough comprehensive school I attended in the 1970s.

'There was an atmosphere of fear generated by Mr Laidlaw and Mr Kozlowski and everyone was watching their backs. It got to the point where I could not stand it any more. I thought I had nothing to lose by making a formal complaint.

'But they had a meeting in Leeds and decided to get rid of me. If they’d apologised, handed me a month’s pay and wished me all the best for the future, I would have walked away.

'Instead, they were arrogant and lied every step of the way. They got staff who had worked with me to lie at the tribunal.

'The tribunal was the most stressful time of my life but it was really embarrassing for them because everything came out.'

Mr Austin joined the firm as a sales executive in September 2010. On his first day Mr Laidlaw told Mr Austin that Mr Kozlowski suffered from Tourette’s and to 'just ignore him'.

Mr Kozlowski admitted to the tribunal that his constant swearing had been 'crass and out of order'.

Warm welcome: Newcastle fans taunt their former hero Andy Carroll on his return to the North East

Mr Austin was asked whether he liked football. When he said he was not interested in it he was told 'you’re gay then'. Mr Laidlaw and Mr Kozlowski also told him he was 'not a real man'.

The tribunal panel noted: 'Both Mr Laidlaw and Mr Kozlowski, in their evidence, say that such an expression is quite normal in north east England football circles, in that anybody who does not like football must accordingly be homosexual.'

Mr Kozlowski equated Mr Austin’s willingness to do household chores with him being gay.

Mr Laidlaw also sent 'overtly sexist and racist' emails to staff, the tribunal found.

He and Mr Kozlowski would quote tracts from the Bible and brand anyone with an alternative religious view 'a Pagan'.

In March last year Mr Austin formally complained of bullying by Mr Laidlaw and Mr Kozlowski.

Just over two weeks later Mr Austin was marched out of the building and summarily dismissed.

Neither of the culprits were suspended with their behaviour later dismissed as 'banter'.

The firm claimed that Mr Austin was sacked for poor performance but the tribunal found the real reason was Mr Austin’s complaint.

One
of the offices of packaging firm Samuel Grant. A tribunal has found 
that the Leeds-based firm is guilty of harassment and must pay Mr Austin
£44,000

It ruled that Mr Laidlaw and Mr Kozlowski 'colluded' with other employees and that their evidence was 'unconvincing and contrived'.

It found that Mr Laidlaw was responsible for an office culture of sexism, racism and religious discussion.

It said: 'This conduct is led by the managing director who sets the tone of the culture within the office by his own behaviour and by accepting the behaviour of others.'

Mr Austin was fired because 'Mr Laidlaw knew serious complaints had been made and, with proper investigation, could be proved.'

The tribunal heard that Mr Austin declined his GP’s offer of medication for work-related stress.

But he broke down while on a walk with his daughter and wept several times while giving his evidence to the tribunal.

The tribunal heard that Mr Austin has been unable to find another job. He has now set up his own business.

 

@highlight

Michael Austin was branded a 'crafty butcher' by his workmates

@highlight

Tribunal heard it was 'normal' for those who don't like football to be considered gay

@highlight

Mr Austin was sacked when he complained but was found to be a victim of 'atrocious' bullying