PUBLISHED:

15:35 EST, 3 February 2013


| 

UPDATED:

03:05 EST, 4 February 2013

An online video showing a blind student skateboarding near his Chicago home has made him a star and inspired thousands across the globe.

The film uploaded onto video sharing website, Vimeo, three weeks ago, has been viewed almost half a million times and passed by users across the globe.

It shows the remarkable ability of Tommy Carroll who was born with bi-lateral retinoblastoma or cancer of the retinas and left blind at the age of two.

Inspirational: Blind skateboarder Tommy Carroll has become an internet sensation after a video about his life was uploaded to sharing site Vimeo last month

Passion: Carroll now a student at Northwestern University refused to allow his disability to keep him away from the skate park

The Northwestern University student has been skateboarding since he was 10 and uses his sense of sound to assess the movements of his board on the half pipe. 

'All I do in skateboarding is based on sound. I'm constantly using the sound of my wheels to check if there's anything in my way and get my sense of direction, all that kind of stuff,' he said in the Vimeo footage of him skating near his home of Glenview.

'I think everybody should know that everything happens for a reason and there's always a way to overcome an obstacle if you really want it enough.'   

Carroll says he loves to go to the park early when it's quiet so he can 'use every inch' of it.

He, like all other skateboarders, has been known to fall, although the dangers are obviously much greater if you can't see where you're falling. 

'Falling is a skill you get good at just the same as getting good at the sport itself,' he says in the film.

In an interview with McSweeney's, he says he once broke a tooth but it was because he was tired. 

Tough falls: Tommy Carroll, like most skateboarders, tends to fall when he's trying new tricks. In his worst fall he broke a tooth

Determination: Carroll says he just ignored those who told him a blind teenager couldn't skateboard. His ability has won him global acclaim

'I hadn’t slept much the night before; I had gone on a trip. And my friend called me and said, “Hey, you want to go skate?” And my parents said, “No, you’re too tired, you shouldn’t go.” I was like no, I want to go. First thing I do, I drop in and I hit the side of the ramp. I just slipped and chipped my teeth.'

His mother was particularly concerned about her son taking on the sport as a teenager but relented to let him explore his passion.

'My dad was pretty cool. My mom was more worried. But if I wanted to do it, she supported it,' he told the website. 'Luckily there’s been some positive media attention and scientific studies showing the adrenaline and stuff generated by [skateboarding]. It’s a good alternative to drugs and stuff like that. I feel like there’s been some positive light shed on it.'

Two years ago his amazing skills on the skate park reached skateboarding legend Tony Hawk who flew to Glenview to skate with him for the day.

Hero: Tommy Carroll met his hero Tony Hawk who learned of his extraordinary ability two years ago and flew to Glenview to skateboard alongside him

Inspiration: Carroll says his story shows everyone can overcome an obstacle if they really want to

The sophomore student majoring in journalism and international studies is now setting up a college skateboarding club and uses his experience to promote the use of protective gear - without which he says he would never have found the hobby.

'I think what's really fun about skateboarding is when you get something new and kind of scary - when you finally land that scary thing and you feel that tension release, that's one of the better feelings and one of the biggest adrenaline rushes you'll ever experience,' he says in the video.

'For me protective gear is the difference between being absolutely terrified while skateboarding and being completely confident. I feel that I can push myself to the next level when I am protected. I can try big tricks and not worry about getting hurt. You can be really brave when you are safe.'

He says he faced doubt from some when he told them of his skateboarding ambitions but also his disability is what pushed him to master the sport.

'There were people who discouraged me. They were like, 'There’s no way. You’re going to kill yourself. Blind people can’t skateboard.' So I just ignored them',' he says on McSweeney's.

'I wanted to impress people. Definitely. I wanted to show that I could go big. I definitely always felt that pressure. Unless I was the best at a park, it was like, 'Well, you’re pretty good… for a blind kid.' I always felt pressure to try to be the very best at any given skate park because if I was only 'good' people would judge me as just being great for a blind skater. I wanted to be a great skater, period.'

BRAVE from EyEFORcE on Vimeo.

@highlight

Tommy Carroll, a student at Northwestern University, has been skateboarding since he was 10 despite being blind from the age of two

@highlight

A teenager growing up in Glenview, Illinois, he mastered the sport on a local half pipe despite his disability

@highlight

His experiences have led him to meet skateboarding greats like Tony Hawk and the video of his story has now been viewed almost half a million times