Two paintings worth millions of euros by the French artists Paul Gauguin and Pierre Bonnard which were stolen in London in 1970 then abandoned on a train have been recovered in Italy.

Gauguin's 'Fruit on a table or small dog' and Bonnard's 'Woman with two chairs' which were taken from a family house in the British capital, were recovered from an Italian factory worker who had hung them in his kitchen for almost 40 years.

The Gauguin painting is worth between 10 and 30 million euros (£8million and £24million) while the Bonnard is valued at some 600,000 euros (£500,000), Italy's heritage police said at a press conference on Wednesday.

Found... 40 years on: Italian military police stand next to the two paintings by French artists Paul Gauguin and Pierre Bonnard which were stolen in London in 1970 and recovered from a factory worker's kitchen last month

Job well done: Italian minister of culture Dario Franceschini (left) and General of Carabinieri Mariano Mossa shake hands in front of the painting which are worth up to £30million

The paintings turned up in a lost property department at a train station and were sold at auction in 1975 to a worker at a Fiat factory, who bought them for 45,000 Italian lire or 23 euros (£20, equivalent to about £300 today). He hung them on the wall of his kitchen.

'It's an incredible story, an amazing recovery. A symbol of all the work which Italian art police have put in over the years behind the scenes,' Italy's Culture Minister Dario Franceschini told journalists.

The paintings were found last month after a lengthy investigation, which began when police received a tip off that they may have been stolen.

Investigators trawled through back catalogues of exhibitions from the time of the theft, from which the 1889 Gauguin mysteriously disappeared after it was stolen, reportedly from the widower of a daughter of one of the Marks & Spencer co-founders in Regent's Park, north-west London, according to The Guardian.

They then used newspaper reports about the 1970s theft in The New York Times and a Singaporean paper to trace the paintings back to the London-based family.

Prized possession: Gauguin's 'Fruit on a table or small dog' is valued between £8million and £24million

Retrieved: Bonnard's 'Woman with two chairs' is valued at some 600,000 euros (£500,000)

'The two paintings were presumably left on a train from Paris to Turin,' said Mariano Mossa, who heads up the heritage police.

'They were bought by an art-loving worker, who hung them for 40 years in his kitchen, first in Turin then in Sicily, after he retired,' he said.

According to press reports at the time, the two paintings were stolen by thieves on 6 June 1970 from Kennedy's home in Regent's Park, north-west London.

The Observer newspaper reported: 'Three men, posing as a police officer accompanying two burglar alarm engineers last night stole two paintings together worth £155,000 from a house in Chester Terrace, NW London.'

The thieves asked for a cup of tea and when the housekeeper returned they had fled with the paintings.

The Fiat worker's son, an architecture student in Sicily, discovered the paintings' true value after noticing a Guagin featured in a book he was reading was very similar to those owned by his father.

The future of the paintings is unclear. A source told The Guardian that Italian police were liaising with the Metropolitan Police's art and antiques unit.

Italy opened a special department to investigate art thefts in 1969, the first in the world, which is situated in a Baroque palace in the centre of Rome's bustling tourist centre.

The heritage police manages the largest data bank on stolen art in the world, with details on some 5.7 million objects.

Last year, they found a painting by Russian-born Jewish artist Marc Chagall, 'Le Nu au Bouquet,' in a private collector's home in Bologna that had been stolen from a US tycoon's yacht in Italy in 2002.

They also investigated the theft of possibly thousands of rare books from the Girolamini Library in Naples, which were allegedly smuggled out and sold internationally by its former director.

Mossa said in January that 'the turnover generated by the illegal sale of works of art comes fourth on a world level behind the sale of weapons, drugs and financial products.'

@highlight

Paintings are by French artists Paul Gauguin and Pierre Bonnard

@highlight

Found in lost property at a train station and sold at auction in 1975

@highlight

Fiat factory worker bought them for £20 and hung them on kitchen wall

@highlight

Found 40 years on after a lengthy police investigation following tip-off

@highlight

Used newspaper reports in New York and Singapore to trace UK owners

@highlight

Italian culture minister: 'It's an incredible story, an amazing recovery'