BBC Children in Need has kept £87.7million stashed away in its investment portfolio instead of giving it directly to charity, its latest accounts reveal.

The charity, which has raised more than £600million for youngsters in the UK since 1980, is preparing to launch a fresh appeal to viewers next month.

But some donors may be surprised to discover it does not give the money directly to good causes.

Scroll down for video 

Charity accounts reveal £87.7million invested in portfolios which the BBC will be handed out once they assess the impacts of other projects (pictured, charity mascot Pudsey and show host Terry Wogan)

Children in Need has £87,705,000 invested in a range of portfolios, up from £81.2million last year. Another £2.2million is sitting in its bank accounts, up from £864,000 last year.

The accounts reveal it paid £9,000 in fees to fund managers and made £893,000 in investment income.

Its latest charity drive will include a series of celebrity-endorsed fundraising campaigns, and with the profits of a recently released BBC recording of the Beach Boys track God Only Knows, is expected to raise more than £20million.

The money is used to help charities that support disadvantaged and disabled children around the country. Yesterday, the BBC insisted all of the money it raises is given to charity, but said it does not release all of it at once so it is able to measure the impact of its donations and ensure funds are being put to good use.

A spokesman said: ‘This money is not simply cash. It has been allocated to projects working with disadvantaged children and young people throughout the UK.

‘In line with standard grant-making practice we do not typically release the full grant upon successful application from projects but rather over a three-year period on a quarterly basis so we can monitor projects to ensure that they continue to comply to the terms and conditions of the grant.’

In 2008 the BBC faced the prospect of an investigation by the Serious Fraud Office after keeping more than £100,000 which should have been given to charity.

The BBC is about to launch a fundraising drive, with sales of Beach Boys track God Only Knows set to raise £20million (pictured, One Direction, Pharrell, Kylie Minogue and Chris Martin who feature on new single)

The broadcaster admitted staff knowingly withheld money meant for causes including Children in Need and Comic Relief. The scandal emerged after auditors carried out an investigation into the BBC’s phone-voting systems.

The cash was generated by callers voting after phone lines had closed on about 20 shows, believed to include Eurovision and Fame Academy, between October 2005 and September 2007.

They were still charged for their calls, typically around 25p a time, but the cash went into the bank account of BBC Worldwide, the corporation’s commercial arm, rather than the charities.

An internal audit showed that a number of workers in Audiocall, part of BBC Worldwide, repeatedly kept money back. It has now been passed on, with interest. The BBC has said the ‘small number’ of staff involved face disciplinary action.

In 2006 TV viewers were warned against giving money to the BBC’s Children in Need appeal.

An independent watchdog said donating to the charity is ‘a bad idea’ because of its huge administration costs – £2.4million out of a total of £33million raised at the time.

Intelligent Giving said money is swallowed up by the need for two sets of bureaucrats: those who run the charity and those in charge of the organisations to which it gives money.

 

@highlight

Charity also has £2.2million in its accounts up from £900,000 last year

@highlight

Spokesman said money being temporarily held and would be given away

@highlight

In 2008 BBC faced investigation after keeping £100,000 of charity money 