Jockey Tom O’Brien will replace a suspended Richard Johnson on the key Christmas-period rides of Menorah in King George VI Chase and Garde La Victoire in the Ladbroke Hurdle.

Grahame Whateley, who owns both Philip Hobbs-trained geldings with wife Diana, confirmed he would be using Hobbs’ No 2 rider and not searching for a big-name replacement after emotionally welcoming his resurgent Peterborough Chase winner Wishfull Thinking at Huntingdon.

Menorah is 10-1 for the King George with sponsors William Hill after winning the Charlie Hall Chase at Wetherby and finishing second to Silviniaco Conti in the Betfair Chase at Haydock while Garde La Victoire is 8-1 second favourite to follow up last month’s Greatwood Hurdle win at Cheltenham at Ascot on December 20.

Tom O’Brien will replace suspended jockey Richard Johnson in two of the key Christmas-period rides

Johnson is ruled out because of the 12-day suspension he picked up at Exeter on Friday for taking the wrong course.

Whateley, who won the 2012 Peterbough Chase with Menorah when it was switched to Kempton, said: ‘I am very sorry for Richard. He made a mistake but we are all human. We have a good jockey in Tom O’Brien – he is a cracking rider. We will just have to hope the ground both suits Garde le Victoire and Menorah.’

Whateley punched the air as if he had won the Gold Cup as he led Wishfull Thinking to the Huntingdon winner’s enclosure.

Like Menorah, 11-year-old Wishfull Thinking, who had produced a career best steeplechasing performance when landing the Old Roan Chase at Aintree on his penultimate run, is riding on the crest of the wave being generated by the in-form Hobbs.

Whateley, who saw his winner’s brother Wishfull Dreaming finish second on his Exeter Bumper debut on Friday, added: ‘If we had only been able to solve Wishfull Thinking’s breathing problem, which we have never done, he would have been exceptional.’

Wishfull Thinking made virtually all under Johnson, jumping with real spring in his hooves, but he was arguably lucky. Nicky Richards-trained Eduard had hit the front when losing all momentum under Brian Harding at the last fence.

Johnson was given a 12-day suspension at Exeter on Friday for taking the wrong course

Some bookmakers quote Wishfull Thinking for the King George but he is likely to have a ‘long rest’ and be brought back for a spring campaign.

Similarly, Gold Cup quotes about Don Cossack, winner of the John Durkan Memorial Chase at Punchestown for trainer Gordon Elliott and jockey Brian O’ Connell, seem equally redundant.

Elliott said his preference would be to go direct to the Cheltenham Festival in March to run in the shorter Ryanair Chase.

Returning Gold Cup winner Lord Windermere did as well as could be expected with his third place behind Don Cossack, finishing strongly over the inadequate two and a half mile distance.

Meanwhile, C4 presenter Clare Balding will not be the only absentee from Aintree on Grand National day next year after preferring to cover the first televised Woman’s Boat race instead in her much scaled-down role.

Robert Waley-Cohen doubts he will let Saturday’s Becher Chase winner Oscar Time take his chance at the age of 14.

His dual King George winner Long Run, however, has Aintree on his agenda and is about ‘six to eight weeks’ off returning to trainer Nicky Henderson as he recuperates from injury.

 

@highlight

Richard Johnson is suspended for two of the key Christmas-period rides 

@highlight

Tom O'Brien will replace him in two races

@highlight

O'Brien will ride Menorah in the King George VI Chase

@highlight

He will also ride Garde La Victoire in the Ladbroke Hurdle