By 
Chris Greenwood, Stephen Wright and Arthur Martin

UPDATED:

06:10 EST, 17 September 2011

A smiling Kweku Adoboli, 31, leaves City of London magistrates court yesterday

The father of the suspected rogue trader Kweku Adoboli said he believed his son 'made a mistake or wrongful judgement.'

Speaking from his home in Tema, Ghana, retired United Nations employee John Adoboli said the family 'were heartbroken' at the news of his son's arrest.

He said: 'We are all here reading all the materials and all the things being said about him.

'The family is heartbroken because this is not our way of life.

'I brought them up to be God-fearing and to appreciate decency.'

Mr Adoboli, who was arrested at his desk on Thursday September 15, is alleged to have lost £1. 3 billion through his rogue trades.

The scandal wiped £4 billion off the value of shares in UBS, affecting thousands of pensioners whose funds had invested in the company.

The loss uncovered by UBS is almost exactly the same amount the bank was trying to save by cutting 3,500 jobs from its worldwide empire.

Before he was arrested, he had changed his status on his Facebook page to 'I need a miracle'.

Mr Adoboli, who until recently lived in a £1,000-a-week loft apartment in the City, is described by friends as 'a really relaxed, happy guy'.Yesterday Mr Adoboli wept as he was accused of gambling away a record £1.3billion.

He wiped tears from his eyes as his alleged crimes at Swiss banking giant UBS were outlined in court.

The former public schoolboy, who later smiled broadly outside court, has been charged with fraud and false accounting.

Speaking from the family home in Tema, Ghana, Kweku Adoboli's father said his son is 'decent and hardworking'

Adoboli appeared in court hours after it was reported he had alerted his employers to unauthorised deals.

UBS’s internal controls had not picked up the huge losses allegedly generated by Adoboli, according to the BBC.

The bank then examined his trading positions and called in the Financial Services Authority and the police. The case has intensified calls for greater regulation of banks, in particular for those engaged in high-risk trading.

Initially Adoboli  worked in a back-office role but quickly rose through the ranks to become a trader.

He
was an employee who ‘did his own thing’ and ‘started to go awry’ in 
2008, hiding his losses in a series of false trades, magistrates were 
told.

By Thursday he had lost $1.5billion and had sold positions that would cost a further $500million.

Dressalikes: Rogue trader Nick Leeson arrives at Heathrow Airport yesterday

David
Levy, prosecuting, said Adoboli involved himself in trades that were 
highly dangerous for the bank and used various means to cover up his 
improper conduct.

‘He may 
well have made some profits, on one occasion up to $20million, but 
losses followed,’ he added. ‘It carried on for three years. He continued
to take risks, gambling the money of UBS bank.

UBS equities trader Kweku Adoboli leaves City of London Magistrates Court in central London after his appearance about a fraud charge

Kweku Adoboli, who had wept during his appearance, smiled outside the court

Adoboli,
whose computer has been seized for analysis, was represented by 
Kingsley Napley, the firm which worked for rogue trader Nick Leeson 
after he broke Barings in 1995.

Leeson arrived at Heathrow yesterday afternoon for media interviews about the UBS case.

The 44-year-old, who lives in Kuala Lumpur, spent three years in a Singapore jail for his crimes.

Adoboli
was remanded in custody until September 22. Days before his arrest, he 
posted a message on Facebook, saying: ‘Need a miracle’.

The
Financial Services Authority and the Swiss Financial Market Supervisory
Authority said they  had ordered a  comprehensive investigation.

Speaking from Wroclaw, Poland, Chancellor George Osborne said the case highlighted why the Independent Commission on Banking's plans for reforming the banking sector were right for Britain.

Heart of probe: Adoboli worked at Swiss bank giant UBS, pictured

The ICB proposals, which were 
announced on Monday, included ring-fencing banks' high street divisions 
to protect them from riskier investment arms.

'Shocking case': George Osborne, the Chancellor, said the case proved the need for reform of the banks

Mr Osborne told Sky News: 'It is a 
shocking case. Obviously we will wait for the full details of it to 
emerge, but it is pretty clear that totally unacceptable things were 
going on in UBS and our regulator is looking into it at the moment and 
indeed the police are looking into it.

'I draw two lessons. One is we need a
better system of regulation, and that is why the British Government is 
proposing to give to the Bank of England much greater powers of 
supervision, so it can look across the piece at issues of stability and 
proper conduct in our banking system, and indeed we will have a 
financial conduct authority specifically looking at market abuse.

'But also I take the lesson that John
Vickers drew to our attention a few days ago which was: how do you 
protect retail banking from those kinds of activities in investment 
banking that we saw at UBS this week?

'If you ever wanted a better example 
of why the kinds of ideas that John Vickers was putting forward were 
right for Britain, look at what happened at UBS just a few days later.'

Sorry we are unable to accept comments for legal reasons.

@highlight

Case proves the Vickers proposals are 'right for Britain', says Chancellor George Osborne