By
Snejana Farberov for Mail online

A surfer who succumbed to his injuries after being pulled from the ocean in Malibu, California, Tuesday, has been identified as a 54-year-old man.

Silverio Rafanan Laconsay, from Los Angeles, was found unconscious in the water off Surfrider Beach at around 11.20am as Hurricane Marie raged on the West Coast.

Officials with the coroner's office told NBC Southern California an autopsy will be performed to determine Mr Laconsay's exact cause of death.

Scroll down for video 

Deadly waves: Silverio Rafanan Laconsay, 54 (not pictured), from Los Angeles, was found unconscious off Surfrider Beach Tuesday as Hurricane Marie raged on the West Coast

An unidentified surfer gets assistance from a Los Angeles County lifeguard on a watercraft, as heavy waves crash against the pier in Malibu, Calif., Wednesday

Mr Laconsay was killed as Hurricane Marie kicked up 20-foot swells along beaches in Southern California.

Dozens of surfers and swimmers had to be rescued Tuesday and Wednesday as the storm walloped the shore.

Thundering surf caused minor flooding in a low-lying beach town while drawing daredevil surfers and body-boarders into churning monster waves as crowds of spectators lined the shore.

Despite the danger, surfers, body-boarders and body-surfers flocked to the notorious Wedge at Newport Beach, where the interaction of swells and a jetty produced colossal waves.

Waves up to about 20 feet high crashed along the Southern California coast on Wednesday, as heavy and potentially dangerous surf from a Pacific cyclone drew crowds of surfers and spectators

Dozens of surfers and swimmers had to be rescued in the area on Tuesday and Wednesday 

Lifeguards up and down the coast sought to keep anyone out of the water who did not have strong experience and were kept busy making rescues all day. There were 60 rescues Wednesday in the area.

Residents of about four blocks of homes along Seal Beach, south of Los Angeles, swept seawater from ground-floor rooms after flooding overnight, and bulldozers reinforced a 6-foot-tall sand berm hastily built to protect shoreline structures.

The towering waves and rip currents were being produced by swells generated by Hurricane Marie in the Pacific Ocean about 800 miles west of the southern tip of Mexico's Baja California peninsula.

Marie has since weakened to tropical storm levels, but life-threatening water conditions were expected to continue into Friday.

 

@highlight

Silverio Rafanan Laconsay, 54, from Los Angeles, perished while surfing off Malibu during Hurricane Marie Tuesday 

@highlight

Dozens of swimmers and surfers had to be rescued during the storm  