By 
Daily Mail Reporter

PUBLISHED:

03:50 EST, 24 September 2013


| 

UPDATED:

06:18 EST, 24 September 2013

The daughter of cosmetics tycoon Ron 
Perelman has accused her uncle of stealing millions in inheritance from 
her late grandfather, the newsstand millionaire Robert Cohen.

Lawyers
for Samantha Perelman told a New Jersey probate court that James Cohen,
her late mother's brother, had tricked his father into cutting her out of his will.

In
opening statements Paul Rowe, for Miss Perelman, claimed that there was
'overwhelming' evidence that Mr Cohen took advantage of his ailing 
father to seize control of the $800million Hudson News Company.

Daddy's girl: Samantha Perelman, seen here at this year's Costume 
Institute Gala with her billionaire father Ron Perelman, is suing her uncle James Cohen over a $600 million legacy left by her grandfather

Mr
Cohen denies the claims. His lawyer contended yesterday that Miss 
Cohen, who at 23 is already a multimillionairess in her own right, was 
scheming to deny Robert Cohen's only living child out of his 
inheritance.

The elder 
Cohen, who died last year aged 86 after a 13-year battle with 
Parkinson's built Hudson News into a retail empire starting with a 
Newark, New Jersey news stand.

After his death last year he left the company to his son James, who then sold it and collected $600million from the deal.

Miss
Perelman is the daughter of former New York Daily News gossip columnist
Claudia Cohen, James Cohen's sister, who died in 2007 leaving her child
a $60million fortune.

Meanwhile,
her father, Ron Perelman, is worth an estimated $12billion, made 
through leveraged buyouts of companies and his stake in Revlon 
cosmetics.

Heiresses: Miss Perelman with her late mother, gossip columnist Claudia Cohen, in 2005. She claims that her mother's brother schemed to exclude her from her grandfather's will as he suffered from Parkinson's

Benjamin Clarke,
for James Cohen, told the court that his client's media mogul father 
was 'not the kind of person you told what to do,' the New York Daily News reported.

'Robert
Cohen was the kind of person who told you what to do,' the lawyer said,
adding that the only possible exception to that was his 'little 
cupcake' granddaughter, Miss Perelman.

He
portrayed the plaintiff as greedy and selfish, claiming that she did 
not even bother to see her grandfather in the final years of his life.

'She
wants to believe that she, the daughter of one of the wealthiest people
in the world, should [inherit] hundreds of millions of dollars 
generated by the sale of a company that James Cohen, not Robert Cohen, 
owned,' Mr Clarke told the court.

Miss
Perelman's lawyer argued that it was Mr Cohen who was the greedy one, 
alleging that he had taken advantage of his father's deteriorating 
mental state to exclude his niece from her rightful inheritance.

Robert
Cohen's decline began in 1999, said Mr Rowe, when the tycoon was 
diagnosed with Parkinson's. In 2004 he was battling liver cancer and 
that year also lost control of his limbs and bodily functions.

By
2009, the year he wrote his last will naming his son James as sole 
beneficiary, the businessman was so incapacitated that he was unable 
even to blink.

A spokesman 
for Miss Perelman has claimed that she was prevented from seeing her 
ailing grandfather in the final years of his life.

Family drama: James Cohen, seen here with his 
wife, is battling niece Miss Perelman over millions she claims he 
cheated her out of by coercing his late father to change his will. Mr Cohen denies the claim

Mr
Rowe has asked the court to throw out that will and reinstate one 
written in 2004, which had left Claudia Perelman, Miss Perelman's late 
mother, valuables including a 30-carat diamond ring worth $10million and
his private jet, as well as $25million in cash.

Since Miss Perelman was the main beneficiary of her mother's estate she stands to inherit most of that fortune.

Mr
Clarke countered that Robert Cohen had transferred Hudson News to his 
son in a bit of nifty estate planning that helped avoid a big tax bill.

He
also contended that the elder Cohen had been upset with his 
granddaughter for challenging his mental competency in a previous case.

Furthermore, he added, even under the 2009 will, Miss Perelman still stands to inherit the £10million ring.

The case continues.

@highlight

Samantha Perelman claims uncle coerced his father into changing his will to leave him the entire $800million Hudson News Company

@highlight

But James Cohen, brother of Miss Perelman's late mother, contends that his father Robert new exactly what he was doing prior to his death last year

@highlight

Miss Perelman, 23, is already a multimillionairess in her own right and is the daughter of Ron Perelman, who is worth an estimated $12billion