A playground has been closed after a single complaint from a resident about the noise of children playing.

The Bakewell Recreation Ground in Derbyshire attracts 
parents and children from as far as 20 miles away from Sheffield, South Yorkshire.

But families have been stunned to discover that the popular outdoor area has been closed for three days a week after the local council received just one complaint about noise.

The splash play area at Bakewell Park, Derbyshire, which has been partially closed after a single complaint from a resident about the noise of children playing

Kate Hunt, of Sheffield, often visited the park with mother Jayne, and her son George and niece Molly, both aged four, said: 'I can’t believe one person can ruin so many children’s fun.

'We’ve been visiting the park for years so were shocked to find the wet area closed - it was particularly upsetting for George and Molly.

'Upon investigating we were told the opening hours had been reduced due to one nearby resident complaining about the noise of children playing.

'It’s beyond belief someone would complain about children having fun - I’m sure the traffic noise from the main road is far more disruptive.

'The council were apologetic and 
explained the area would still be open at certain times, but these 
aren’t convenient for everyone.'

The
 wet play area was open seven days a week up before council bosses 
slashed its opening times to just four afternoons a week following the 
complaint.

Kate Hunt, of Sheffield, often visited the park with her son George (pictured) and niece Molly, both aged four. She said: 'I can't believe one person can ruin so many children's fun'

The area, which features splash pads, is now open from noon to 5pm on Fridays, Saturdays, Sundays and Mondays.

It will also be open every afternoon but only during the school summer holidays.

Ms said: 'Weekday mornings during term-time were an ideal time for parents to visit with pre-school children because bigger children are at school, so it’s less busy and there’s less chance of them getting hurt or knocked over.

'Visiting in the afternoon would mean less play time, as we would have to leave quite early to pick up my other children from school.

- Mother Kate Hunt

'Also you can’t control when the sun is going to come out, so there could be hot days where it’s going to waste.

'I just can’t believe one person’s view outweighs everyone else and they can ruin so many children’s fun.'

Another mother added: 'Obviously, children aren’t supposed to have fun in this supposedly fun area. It beggars belief.'

Grandma Anne Barrett, 76, regularly visits Bakewell Recreation Ground with grandson Isaac.Anne,
 who lives in the nearby village of Eyam with partner Stewart Delk, 66, 
said: 'I think it's ridiculous that the council has cut the opening 
hours because of one noise complaint.

'The council should reconsider their decision.

'People aren't always free to come to the park at weekends and it's nice to come here when it's not so busy.

'I can't see how the restricted hours will make any difference to the resident that has complained either - it just means there will be lots of disappointed children this summer, which is sad.'

Residents on the road where the complainant arose said they expected noise from the park but said they can understand why their neighbour complained.

Marian Lomas, 75, who lives in a house which backs onto the park, said: 'The noise from the play area does get very loud sometimes but I would never complain about it as you would come to expect some noise where we are situated.

'The main noise is from the children playing. They scream and laugh together.

'But it doesn't bother either of us too much, and luckily we are both mobile and can get out of the house.'

She added: 'I can understand why the couple that complained did.

'But I think it's a real shame that the council have restricted the opening hours.

'I used to bring my own daughters here when they were children, they're both in their fifties now - that's how long ago it was - and it's always been open in the summer months.

'The noise was worse when it was a paddling pool there - not the padded play area.'

A spokesman for Derbyshire Dales District Council said: 'The council freely acknowledges it is in a no-win situation here.

'Some
 time ago, a local resident complained to us about what he claimed was 
an increase in noise from the play area since the replacement of an old 
paddling pool in 2010 by new splash pads.

'Our
 officers carried out tests which showed the noise generated from the 
play area has the potential to represent a statutory nuisance. It’s not 
only the noise generated by screaming children, but also the pump that 
works the splash pads.

'The complainant’s view is the play equipment should be re-sited or closed.

'However,
 as the cost of such a move would be significant and its closure 
unacceptable, we’re trialling a restricted hours operation.

'We
 are attempting to strike a balance between two sets of views. All 
feedback will be reported to councillors for further consideration at a 
meeting early in July.'

 

@highlight

Bakewell Recreation Ground, Derbyshire, closed for three days a week

@highlight

It comes after the local council received just one complaint about noise

@highlight

Parents have reacted furiously to the news, saying: 'It beggars belief'

@highlight

Council said the noise of children and the splash pad pump is a 'nuisance'