Shoppers made their feelings clear about an EU ban on models of more than 1,600 watts by visiting stores or online sellers in their droves

The stampede to buy powerful vacuum cleaners intensified yesterday as retailers reported a fourfold surge in sales.

Shoppers made their feelings clear about an EU ban on models of more than 1,600 watts by visiting stores or online sellers in their droves.

Many have been stockpiling two or more high-power models to beat regulations that came into effect yesterday.

The new EU directive is intended to reduce energy use, but it has infuriated the public, who say they’ll have to spend longer using the appliances.

Online electrical retailer ao.com said weekly sales had soared 380 per cent compared with the first week of August.

The most popular model was the 2,400-watt Bosch Pro Energy BSGL3126GB cylinder vacuum cleaner costing £99, which sold out yesterday.

It currently has two models left in stock that are over 1,600 watts, but expects to have more this week.

There was clear evidence of customers stockpiling vacuums, it added, particularly in the 2,000+ watt ranges, where 3 per cent of sales were generated by shoppers buying two or more.

‘We saw a huge surge in sales of corded vacuums over 1,600 watts over the weekend, with sales quadrupling,’ said head of small domestic appliances Leanne Beswick.

‘Having reviewed our stocking levels it looks like we still have a limited number of high wattage vacuum cleaners in our warehouse and we are expecting another two models to come back into stock this week.’

Sales at the Cooperative Electrical Shop over the past two weeks leapt by 129 per cent compared with the same period last year.

Currys said sales were up 94 per cent compared with the same weekend 12 months ago.

A spokesman added: ‘They have been flying off the shelves and that has been across the board – from uprights to cylinders.’

Scroll down for video 

Under threat: Food blenders may also be targeted 

Some 30 devices – mostly domestic electrical items – are facing overhauls to meet the EU guidelines, including:

Air conditioning in cars – blamed for increasing fuel consumption although critics point out the drag created by opening a window uses more energy. Window heaters and seat heating will also be looked at.

Fitness equipment – many modern exercise bikes and rowing machines use electricity to generate resistance.

Hairdryers – power savings of 30 per cent may be required, although salons argue they will spend longer drying hair.

Blenders – smoothies and soups may take longer to prepare if new rules are introduced.

Fax machines – under scrutiny despite all but dying out in homes as people switch to email. Photocopiers, printers and scanners are on the list too.

Power tools – they could face changes despite the Commission’s report stating the potential improvements are ‘small’.

Lawnmowers – all types, including electrical and petrol, could be affected.

Patio heaters – a key target due to the amount of energy lost.

Kettles – may have to be redesigned to switch off sooner or slash surface heat loss.

Toasters – they waste power if one or more slots is empty.

Tesco has previously reported sales rocketing by 44 per cent over the past fortnight with models selling out including the 2,300-watt Hoover Breeze BR2306.

Argos said it had seen an increase in sales despite 97 per cent of its stock being compliant with the new legislation since July. Retailers can continue selling existing stock until it runs out but they cannot import more and manufacturers are no longer allowed to produce them.

Vacuums will also have to carry ratings from A to G similar to those on fridges and washing machines, explaining energy use, cleaning performance on carpets and hard floors, and dust emissions.

The crackdown affects five of the seven vacuums given ‘Best Buy’ status by Which?, and the consumer watchdog last week advised people to ‘act quickly’ before stocks of powerful models run out. A 2012 report by retail analyst Mintel found 76 per cent of consumers rated suction power the most important feature when buying a vacuum.

Senior household care analyst Richard Caines said: ‘I’m not 100 per cent convinced it will save a lot of energy as if a vacuum is not providing as much suction it will have to be used for longer.’

The power of cleaners will be reduced further from 2017, when the maximum will be 900 watts.

 

@highlight

Shoppers made feelings clear about ban on models of more than 1,600 watts

@highlight

Many have been stockpiling two or more models to beat the regulation

@highlight

New EU directive is intended to reduce energy use, but has infuriated public

@highlight

Online electrical retailer ao.com said sales had soared by 380 per cent  