Enough is enough: Energy Minister John Hayes has called for an end to onshore wind farms

A furious coalition row erupted today after a junior Tory minister declared that the relentless march of onshore wind farms is at an end.

Insisting ‘enough is enough’, energy minister John Hayes said turbines had been ‘peppered around the country’ with little or no regard for local opinion.

He said existing sites and those in the pipeline would be enough to meet green commitments with no need for more.

‘Even if a minority of what’s in the system is built we are going to reach our 2020 target,’ he said. ‘I’m saying enough is enough.’

But at an early-morning showdown with his boss - Lib Dem Energy Secretary Ed Davey - Mr Hayes was told he does not decide government policy.

Mr Hayes told the Mail he had commissioned research on the impact of wind turbines on the landscape and whether they drive down house prices.

He has also asked scientists to examine noise complaints and more sinister suggestions that the turbines endanger military aircraft by blocking radar signals.

The intervention by Mr Hayes, who became energy minister in last month’s reshuffle, will delight 100-plus fellow Tory MPs who have urged David Cameron to take a more sceptical approach to onshore wind power.

It does however risk a clash with the Liberal Democrats, who are enthusiastic advocates of renewable energy.

A source close to Mr Davey said today: 'John does not decide government policy. There will be no change. We are in a coalition government, not a single party government and definitely not a single minister government.

'We are determined to make sure the coalition lives up to the Prime Minister’s pledge to make it the greenest government ever.'

At a meeting of ministers at the Energy department this morning, Mr Davey made clear his anger at Mr Hayes.

'Ed is of the opinion that he ultimately signs off renewables policy. He is the Secretary of State. John is not in the Cabinet and he is not Secretary of State,' the source added.

In a statement later Mr Davey said: 'There has been no change to Government policy on renewable energy, as collectively agreed by the Coalition Cabinet.

Energy Secretary Ed Davey today slapped down Mr Hayes, insisting onshore wind has 'an important role to play' in Britain

'Onshore wind is one of the cheapest 
renewables, which is why we’ve been able to cut the subsidy.  It has an 
important role to play in our energy future.'

However Mr Hayes suggested the 
controversy over turbines was giving other sources of renewable power – 
such as offshore wind, solar and tidal power – a bad name.

‘The onshore wind debate is skewing 
the whole debate, which is not good for the Government, not good for 
people and not good for the renewables lobby,’ he told the Mail.

‘We can no longer have wind turbines imposed on communities. I can’t single-handedly build a new Jerusalem but I can protect our green and pleasant land.

‘Firstly, I have asked the planning minister to look again at the relationship between these turbines and the landscape.

‘It seems extraordinary to have allowed them to be peppered around the country without due regard for the interests of the local community or their wishes.

‘We have issued a call for evidence on wind. That is about cost but also about community buy-in. We need to understand communities’ genuine desires.’

Mr Hayes said policy should not be based on some ‘bourgeois left article of faith’.

‘These things are about the people and I am the people’s minister,’ he added.

Controversial: The Energy Minister said onshore wind farms are turning people against other sources of renewable energy such as offshore alternatives and solar power

‘I want to look at a broader analysis of the effects – I mean house price values, and other quality of life issues. I want to look particularly at noise, so I have asked the Institute of Acoustics to look at the noise issue from a completely independent perspective.

‘There is a case where people had to move from their family farm because of noise. It is very often the case that local authorities don’t have the wherewithal to address these planning issues.’

Mr Hayes said defence ministers had agreed to investigate claims of radar interference from the spinning blades.

The Government has set a target of increasing the amount of power generated by onshore wind farms to 13 gigawatts by 2020.

But in an indication of a shift in Government policy, ministers announced this summer that the subsidy for onshore wind power generation would be cut by 10 per cent this year.

Approvals for onshore wind farms – 
around 3,800 turbines are in operation – have however reached record 
levels, according to figures published yesterday.

RenewableUK,
 the wind industry trade body, said in a statement: ‘For the first time 
in five years, the UK is seeing a rise in the amount of UK capacity 
approved at a local level.’

There
 was a 15 per cent increase in approval rates for smaller onshore 
projects with capacity of less than 50 megawatts last year compared with
 the previous year, it said.

Applications for new wind farms have to be made to councils, and around a half are refused. But under the existing system, energy companies often win on appeal to the planning inspectorate.

Campaigners took heart from a court ruling in May, in which villagers in Hemsby, on the edge of the Norfolk Broads, succeeded in blocking four 350ft turbines after a judge agreed their right to preserve their landscape was more important than renewable energy targets.

Tory MP Chris Heaton Harris, who has led calls for a rethink on wind power, said of Mr Hayes’s remarks: ‘This is a huge step forward. These awful turbines do nothing for the environment – they barely reduce CO2 – they force up energy bills and put more people into fuel poverty.

‘It’s about time the Government listened in this way. Communities will be delighted that they may now be spared the torment they have seen others go through when turbines go up.’

Former Conservative Chancellor Lord Lawson, an arch-sceptic on climate change, said: ‘I would welcome the minister’s statements. I would hope they would translate into a moratorium. An additional problem is that wind power is one of the most expensive forms of generating electricity there is.

‘At a time when there is so much concern both from households and industry about the cost of energy, that too should be a decisive argument against going this way.’

But Labour seized on the coalition row about the future of wind farms.

Shadow energy secretary Caroline Flint said: 'Britain needs a clean, diverse and secure energy supply – but this Government appears clueless when it comes to delivering clean energy and fair bills.

'With energy bills skyrocketing, what hard pressed people urgently want is action but instead we have a shambles of a Tory-led Government which can't even agree with itself.'

Greenpeace Energy Campaigner Leila Deen said: 'John Hayes’ petulant outburst adds to the Coalition’s growing energy shambles and to a deepening divide within Government between those who care about green growth and the economy and those who just want more oil and gas.

'Here is a new minister veering off brief and publicly contradicting his bosses. His comments threaten jobs and his approach will drive up energy bills.'

@highlight

Onshore wind farms give other renewable energy sources a bad name,  Energy Minister John Hayes tells the Daily Mail

@highlight

Existing and planned sites are enough to meet environmental goals

@highlight

Research into effects on house prices, noise levels and military radars has been commissioned, said Mr Hayes

@highlight

Comments spark a furious coalition row, with Lib Dem Energy Secretary Ed Davey insisting 'I'm in charge'