Two young men who built a mysterious tunnel in Toronto had no criminal intent - they just wanted a man cave, police said Monday.

Const. Victor Kwong said tips from the public helped them identify the two men in their 20s responsible for building the underground chamber near a Pan Am Games venue.

News of the tunnel's discovery set off a social media frenzy, with theories of its purpose ranging from zombie hideouts to affordable housing.

Kwong said the two men just wanted to have fun and there was never any danger to public safety.

Scroll down for video 

Mystery: Authorities said this image reveals the tunnel's entrance, as well as a sump pump water hose and an electric extension cord 

Good times: Toronto police said the tunnel, seen following an excavation, was built for fun 

Puzzle: News of the tunnel's discovery set off a social media frenzy, with theories of its purpose ranging from zombie hideouts to affordable housing

Const. Victor Kwong said the two men just wanted to have fun and there was never any danger to public safety

'It was a place for them to hang out. They started out as goal to make a cool place and that's what they did,' Kwong said.

He said investigators checked out their explanation and the case is now closed. He said the men will not be charged, though they could face a fine.

The bunker, discovered in January by a conservation officer in a densely wooded area, is located 25 meters (27 yards) from the fence of the Rexall Centre, which is to host tennis events for the Pan Am Games.

Inside, police said they found beverage containers, plywood wall supports, a generator and a sump pump. The chamber was almost 2 meters (2 yards) high, 86 centimeters (34 inches) wide and 10 meters (33 feet) long.

Kwong said police are not releasing the men's names, or any further details since the case is not a criminal investigation.

Kwong said the men are not believed to be survivalists, adding they just 'wanted to dig a tunnel.' He said they were not ex-miners or engineers.

Investigation: Kwong said police are not releasing the names of the men who built the tunnel, or any further details since the case is not a criminal investigation

Discreet: Toronto police say this is what was used to cover the tunnel 

Prepping: A compressor (left) and a generator pit (right) were also at the tunnel site in Toronto 

'The minute they were found they were apologetic,' Kwong said.

He said there is no connection to this summer's Pan Am Games, or to York University, which is also near the site where the tunnel was found.

'With the enormous interest generated by the media, police received information on Friday, February 27, 2015, which enabled investigators to identify two men,' Toronto police said in a Tuesday news release.

It continued 'The two men told investigators they built the tunnel for personal reasons. Investigators have verified their account and are satisfied there was neither criminal intent nor any threat to the people or city of Toronto. The investigation is concluded.'

Speaking to CBC News, Kwong said 'So, when we say "personal reasons," what we basically mean is that it was not for any type of nefarious, nothing in terms of, you know, ritual or anything like that.

'It is simply two guys who just wanted to dig a cave. And that really is the - I mean, it sounds too simplified, but that really is what our investigation has led to.'

He also told the news outlet 'Although we're not getting into details about them, what we can say is that they were not related to Rexall. Not related to Pan Am. Nor were they related to York University.

'These are just two men who decided that they wanted to embark upon this adventure.'

Toronto police announced the discovery of the tunnel on Feb. 24 after weeks of surveillance didn't turn up anything.

Safety: Kwong said the tunnel has no connection to this summer's Pan Am Games, or to York University, which is also near the site where the tunnel was found

Identities: Kwong said the men are not believed to be survivalists, adding they just 'wanted to dig a tunnel.' Toronto police say this image reveals what was used to keep the generator pit hidden from view 

Curious: Investigators also recovered this rosary necklace and poppy flower 

 

@highlight

The bunker was discovered in January by a conservation officer in a densely wooded area

@highlight

It is located 25 meters (27 yards) from the fence of the Rexall Centre, which is to host tennis events for the Pan Am Games

@highlight

Const. Victor Kwong said the two men who built the tunnel just wanted to have fun and there was never any danger to public safety

@highlight

He said the men will not be charged, though they could face a fine 