It’s been 26 years since we saw them magically tightening Marty McFly’s Nike boots in Back to The Future.

Now, self-tying shoelaces could actually become a reality this year, proving right one of the film’s fantastical predictions for what 2015 would be like.

Engineers have designed a shoe that can automatically lace up, adjusting itself to the shape of your foot. 

Scroll down for video  

The German scientists attached an energy harvester attached to the shoe during trial runs to see how recharging will work with different body types

The University of Freiburg self-tying shoe prototype recalls the famous Nike High Tops in Back to the Future. The shoe company is releasing a version of the trainers (pictured in 2015

Simply slip the trainer on and pressure sensors will tell the ‘smart shoe’ when your foot is in position, triggering a tiny motor in the heel that pulls the laces tight.

When you want to take off the shoes, you click your heels together twice and the motor will release a spring in the shoe’s tongue, which loosens the laces enough for you to slip them off. 

And the ingenious invention doesn’t even need to be plugged in to charge or have its battery replaced because it runs on power generated by the swing of your foot as you walk.

Engineer Klevis Ylli, of the Institute for Micromachining and Information Technology in southern Germany, said the shoes could help a variety of different people.

‘One focus is that it could be used in shoes for elderly people who have mobility problems,’ he said. ‘But it could also work for children, or as a lifestyle product.’

The design, which is still in a prototype phase, cleverly captures the energy of the foot’s swing when opposing magnets in each shoe move past each other.

It then uses that power to charge a battery. An hour of walking is enough to tighten the laces once, and it requires no energy to undo the shoes because that relies on the spring alone.

The shoes’ power can also be topped up by placing them on a wireless charging mat.

Mr Ylli and a team from the University of Freiburg, who detail their design in the journal Smart Materials And Structures today, are also developing a gadget that could be put in shoes to make them act as a navigation system.

The device would use a compass, a speed calculator and a gyroscope – a device which determines orientation – to track the wearer’s movements. 

The designers hope it could be used to help emergency services navigate around unfamiliar buildings.

In 1989’s Back To The Future II, Marty McFly wears automatically-lacing Nike High Tops and flies on a hoverboard when he travels forward to 2015.

A graphic in the scientists' paper shows how a person walking can generate energy to be used in the shoes

 

@highlight

University of Freiburg team develops 'smart shoe' with sensors and motor

@highlight

Laces tighten to different-sized feet and users click heels  to take them off

@highlight

An hour of walking is enough to tighten the laces once

@highlight

Shoes capture the energy of foot movement with magnets 

@highlight

Germans also developing footwear with compass and gyroscope