Wind farms could cause people living nearby to go deaf, a new study claims.

The barely audible low frequency hum emitted by turbines harms ‘the exquisite mechanics of our inner ears’, scientists say.

A study of 21 healthy young men and women who were exposed to such sound, revealed that most experienced changes in cells in the cochlear - a spiral shaped cavity essential for hearing and balance.

Scroll down for video 

Wind farms (pictured) could cause people living nearby to go deaf, a new study claims. Scientists from the University of Munich said that the barely audible low frequency hum emitted by turbines harms ‘the exquisite mechanics of our inner ears’

Researchers measured the changes by analysing Spontaneous Otoacoustic Emissions (SOAEs), which are the faint sounds produced in the ear that can detect changes to its physiology.

Dr Marcus Drexel, of the University of Munich, said man-made sources of low frequency noise have spread dramatically in recent years and are also generated by thermal power stations, ventilation and air conditioning systems.

‘The dogma of “what you can’t hear, won’t hurt you” is deeply rooted in society and governs the current health and safety regulations,’ he said.

‘However, while even loud low frequency sounds are not perceived as obtrusive, our findings show such sounds affect the exquisite mechanics of our inner ears in a significant manner.

‘Our study identifies a mechanism in our hearing system, which can contribute to explain conditions associated with low-frequency sound emissions.’

A study of 21 healthy young men and women who were exposed to 'the hum' - a noise mimicking that made by wind turbines - revealed that most experienced changes in cells in the cochlear (pictured) which is a spiral shaped cavity essential for hearing and balance

The hum is a persistent and invasive low-frequency humming or droning noise, which is only audible to some people.

It is thought that around two per cent of people can hear it - but there has long been scepticism about whether it actually exists.

The hum is made by thermal power stations, ventilation and air conditioning systems as well as some factory machinery, household appliances and even the sea.

This new report suggests that not only do wind farms produce 'the hum' but that it also damages hearing

Scientists found that most of the healthy adults who they exposed to the sound - a low frequency wavelength of 30Hz - experienced changes in cells in the cochlear.

In the study, the participants were exposed to a low frequency wavelength of 30Hz for 90 seconds, to mimic the noise generated a wind turbine. 

The noise was well below health and safety regulations, according to the paper, which was published in the journal Royal Society Open Science.

Humans can have a hearing range of between 20 and 20,000Hz. 

Dr Drexel said: ‘Most interestingly, 17 of the 21 subjects revealed an overall of 56 new SOAEs, which had not been measurable before low frequency stimulation.’

For decades, experts thought that sound lower than 250Hz largely bypassed the inner ear even at intense levels, because thresholds are relatively high. But this could be incorrect.

Dr Drexel said: ‘The current data show in humans, active cochlear mechanics, as assessed by SOAE measurements, are significantly affected by low frequency stimulation.

‘To the best of our knowledge, this is the first comprehensive study focusing on the effect of low frequency sound on level and frequency of human SOAEs.’

Wind farms have also been linked with a greater risk of heart disease, panic attacks and migraines.

The farms are said to cause ‘wind turbine syndrome’, the symptoms of which include tinnitus, vertigo and sleep deprivation.

It is estimated that up to 30 per cent of the population suffer from some sort of noise sensitivity and at least 10,000 people now hear 'the hum' (illustrated with a stock image)

It is thought that thousands of people are super sensitive to low frequency sounds which are produced by factory machinery and transport as well as household items such as fridges and boilers.

In extreme cases, ‘the hum’ can result in headaches, depression and even, in one instance, suicide.

It is estimated that up to 30 per cent of the population suffer from some sort of noise sensitivity and at least 10,000 people now hear ‘the hum’.

The wind industry has been accused of ignoring the damaging impact of the intermittent noise from turbines for 25 years.

A 1987 research paper for the US Department of Energy showed the ‘annoyance’ caused by them to nearby residents was ‘real not imaginary’.

@highlight

Study of 21 healthy adults exposed to 'the hum' revealed that most experienced cell changes in the cochlear - part of the inner ear

@highlight

The hum emitted by a wind turbine is a low frequency wavelength of 30Hz

@highlight

Researchers from the University of Munich measured the cellular changes by examining the faint sounds produced in the ear

@highlight

Wind farms have already been linked to a greater risk of heart disease, panic attacks and migraines, with people living nearby most at risk

@highlight

It is estimated that up to 30 per cent of the population suffer from some sort of noise sensitivity and at least 10,000 people now hear ‘the hum’ 