A prototype toilet that generates 'everlasting' electricity from urine has been launched near a university bar.

The scientists behind the 'pee-power' toilet hope it can be used by aid agencies in disaster zones to supply much-needed electricity to refugee camps.

The technology uses microbial fuel stacks in the toilets, which feed on urine, creating biochemical energy  that can be turned into electricity.

Scroll down for video 

A prototype toilet that generates 'everlasting' electricity from urine has been launched near at a university bar (stock image used). The scientists behind the 'pee-power' toilet hope it can be used by aid agencies in disaster zones to supply much-needed electricity to refugee camps 

The urinal is the result of a partnership between researchers at the University of the West of England in Bristol and Oxfam. 

The units contain bacteria that breaks down the chemicals in urine, in the process releasing energy in the form of electricity which is stored on a capacitor within a fuel cell.

'The microbial fuel cells (MFC) work by employing live microbes which feed on urine for their own growth and maintenance,' explained Professor Ioannis  Ieropoulos.

'The MFC is, in effect, a system which taps a portion of that biochemical energy.

'This technology is about as green as it gets, as we do not need to utilise fossil fuels and we are effectively using a waste product that will be in plentiful supply.' 

It is located near the students' union at the university's Frenchay campus and researchers will be hoping for brisk business at closing time.

Students and staff are being asked to use the urinal to donate pee to fuel the microbial fuel cell stacks that generate electricity to power indoor lighting.

The research team is led by Professor Ioannis Ieropoulos, of the Bristol Robotics Laboratory at UWE Bristol, who is an expert at harnessing power from unusual sources using microbial fuel cells.

'We have already proved that this way of generating electricity works,' the professor said.

'Work by the Bristol BioEnergy Centre hit the headlines in 2013 when the team demonstrated that electricity generated by microbial fuel cell stacks could power a mobile phone.

'This exciting project with Oxfam could have a huge impact in refugee camps.

'The microbial fuel cells work by employing live microbes which feed on urine for their own growth and maintenance.

'The microbial fuel cell is in effect a system which taps a portion of that biochemical energy used for microbial growth, and converts that directly into electricity - what we are calling urine-tricity or pee power.

'This technology is about as green as it gets, as we do not need to utilise fossil fuels and we are effectively using a waste product that will be in plentiful supply.'

The urinal on the university campus resembles toilets used in refugee camps by Oxfam to make the trial as realistic as possible.

The technology that converts the urine in to power sits underneath the urinal and can be viewed through a clear screen.

The toilet is located near the students' union at Bristol university's Frenchay campus and researchers will be hoping for brisk business at closing time.Students and staff are being asked to use the urinal to donate pee to fuel the microbial fuel cell stacks that generate electricity to power indoor lighting

Andy Bastable, head of water and sanitation at Oxfam, said: 'Oxfam is an expert at providing sanitation in disaster zones, and it is always a challenge to light inaccessible areas far from a power supply.

'This technology is a huge step forward. Living in a refugee camp is hard enough without the added threat of being assaulted in dark places at night. The potential of this invention is huge.'

They hope the abundant, free supply of urine will make the device practical for aid agencies to use in the field.

Prof Ieropoulos added: 'One microbial fuel cell costs about £1 ($1.5) to make, and we think that a small unit like the demo we have mocked up for this experiment could cost as little as £600 ($900) to set up, which is a significant bonus as this technology is in theory everlasting.'

@highlight

Scientists say toilet can be used to supply electricity in disaster zones

@highlight

Bristol system uses microbial fuel stacks in toilets which feed on urine

@highlight

This then creates biochemical energy that can be turned into electricity

@highlight

Its inventors say the system could cost as little as £600 ($900) to set up