By 
Daily Mail Reporter

PUBLISHED:

23:21 EST, 28 August 2013


| 

UPDATED:

05:26 EST, 29 August 2013

Google’s much-admired policy of allowing staff one day a week to work on side projects is a thing of the past, former employees have claimed.

The '20 per cent time' policy has reportedly been effectively abolished, because workers are simply too busy trying to complete their punishing day jobs, the website Quartz reports.

The perk was introduced by Google founders Larry Page and Sergey Brin who have said it is responsible for the company's 'most significant advances'.

120% time: Google's policy of allowing staff one day a week to pursue side projects has all been abolished, former employees have claimed

Gmail, Google Transit, Google Talk, and Google News, are among the successful projects said to have been generated by Google engineers using their 20 per cent time allowance.

One former employee claims that engineers must now get approval from management to take their 20 per cent time, where in the past it had been seen as a right for every employee.

The firm has reportedly created an internal analytics team that constantly measures all employees’ productivity levels with managers now being being judged on the productivity of their teams.

Senior managers now reportedly discourage lower-level managers from approving any 20 per cent projects at all. Workers are instead expected to concentrate on their primary responsibilities 100 per cent of the time.   

Google CEO Larry Page said the company would be adopting a 'more wood behind fewer arrows' strategy when he took over in 2011

Google staff are now reportedly referring to 20 per cent time as '120 per cent time'.

It follows the closure of Google Labs in 2011 when Larry Page took over as CEO, which had showcased many of the projects created in the employees’ 20 per cent time.

At the time Mr Page said Google would be adopting a 'more wood behind fewer arrows' strategy, meaning more employees would be working on a smaller number of projects.

A Google spokesperson disputed teh claim saying 20 per cent time was 'alive and well'.

@highlight

Policy is said to be behind some of the company biggest advances

@highlight

Engineers 'having to get permission from management to take time off'

@highlight

Google deny the rumours saying the policy is 'alive and well'