By 
Victoria Woollaston

PUBLISHED:

10:49 EST, 3 September 2013


| 

UPDATED:

10:52 EST, 3 September 2013

A Canadian firm wants to replace all our computer passwords, screen locks on phones and tablets, car and house keys and even wallets with a single authentication band worn on the wrist.

The Nymi bracelet reads and monitors the wearer's cardiac rhythm, which is as unique as a person's fingerprint, to authenticate who they are.

A built-in proximity sensor can then detect where they are, and when the wearer is close to a paired computer, device or car, will automatically confirm their identity and unlock the required hardware or software. 

Scroll down for video

Canadian firm Bionym has created the Nymi bracelet, pictured, that identifies the wearer by tracking their unique heart rate, or cardiac rhythm. The bracelet can then be used to unlock paired computers and mobile devices and cars, for example

When the wearer clasps the Nymi around their wrist, the bracelet powers on. By placing a finger on the topside sensor while the wrist is in contact with the bottom sensor, it completes an electrical circuit. Nymi will then vibrate and built-in LEDs light up to tell the wearer the device has successfully authenticated them

When the wearer clasps the Nymi around their wrist, the bracelet powers on.

By placing a finger on the topside sensor while the wrist is in contact with the bottom sensor, it completes an electrical circuit.

Nymi will then vibrate and built-in LEDs light up to tell the wearer the device has successfully authenticated them. 

Users will stay authenticated until they remove their Nymi and the electrical circuit is broke.

The Nymi functions on a 3-factor security system - the bracelent, a unique heartbeat and an Authorized Authentication Device (AAD), which is a smartphone or device registered with the app. 

Although other companies are also working on password replacements that use a person's biometric data such as an iris, face, or fingerprint, for example, Bionym founder, Dr. Karl Martin, claims Nymi is even more secure.

He told The Verge: 'Your face, your iris — they're all physical features that can be stolen, that you leave everywhere.'

The bracelet contains a HeartID that measures the amount of electrical power generated by a human heart, called a cardiac rhythm tracked on an electrocardiogram, or ECG.

This ECG differs from person to person and depends on the location and size of the their heart.

Nymi only works with a registered person's cardiac rhythm, meaning if the bracelet is stolen it can't be hacked.

And unlike photos of people's faces and iris, or fingerprints left on surfaces, a heart can't be copied or stolen.

Along with the HeartID and proximity sensors, the Nymi bracelet also has a motion sensor and connects to devices using Bluetooth.

The motion sensor can be used to open car boots or doors wirelessly by moving the wrist in a certain direction, for example.

Applications on smart TVs can also be controlled using flicks and spins of the wrist.

Plus, Nymi can be used to pay for shopping wirelessly and securely.

Although
the first Nymi release is a bracelet, Martin claims that the technology
could also be embedded into other accessories, such as a ring or belt - all the device needs is a connection that can be undone.

Along with the HeartID and proximity sensor, the Nymi bracelet also has a motion sensor and connects to devices using Bluetooth. The motion sensor can be used to open car boots or doors as well as used to control certain applications on smart TVs, pictured

The bracelet only works with paired devices and once it has been joined to a smartphone, for example, it can vibrate and respond to notifications on the device such as a new email or text message. 

The product's site said: 'Nymi offers security without compromising convenience, putting you and only you in control of your identity.

'As you head out the door, you’ll be able to interact with the world around you through the power of simple gestures.

'With accurate and convenient authentication technology there is no end to the possibilities. The Nymi can replace everything from the PIN on your credit card to the account information on your gaming console without sacrificing security, privacy or convenience.

'No more prompts, only awesome experiences.'

The Nymi bracelet can be pre-ordered for $79 (£50) for the first 250,000 orders, or $99 (£63) after.

Devices will be shipped 'early 2014.'

The Nymi bracelet can also be used to pay for shopping wirelessly and securely and could replace cards or wallets

@highlight

The Nymi bracelet reads and monitors a wearer's cardiac rhythm

@highlight

When the wearer goes near a paired device, Nymi authenticates them and unlocks the phone or computer using a proximity sensor

@highlight

Nymi can also unlock cars and pay for shopping wirelessly

@highlight

A built-in motion sensor makes it possible to control smart TVs too