By
Mark Prigg

PUBLISHED:
  
  
      09:18 EST, 7 September 2012
    
  

 | 
  UPDATED:
  
  
      09:19 EST, 7 September 2012

Nasa today released a stunning video showing a 500,000 mile long 'solar whip' on the surface of the sun - and the beautiful aurora it created on earth.

Captured by from NASA’s Solar Dynamics Observatory (SDO), the video shows in unprecedented detail a 
very long, whip-like solar filament extending over half a million miles 
in a long arc above the sun’s surface.

Click for video

The coronal mass ejection, or CME, traveled at over 900 miles per second.

The CME did not travel directly toward Earth, but did connect with Earth's magnetic environment, or magnetosphere, with a glancing blow, causing aurora to appear on monday evening.

A
 'solar whip' or filament is caused when a red glowing loop of plasma 
erupts, releasing the plasma out in huge loops hundreds of thousands of 
miles into space.

The 
filaments are anchored to the Sun's surface in the photosphere, and 
extend outwards into the Sun's hot outer atmosphere, called the corona.

The 'whip' was a filament, cooler clouds of solar material that are tethered above the sun’s surface by unstable magnetic forces.

The
 images and video (below), which covers August 6 to 8, 2012 show the 
filament as a darker strand that has been in view for several days.

It the snaps, sending radiation hurtling towards earth.

At the time, Nasa revealed a video of the activity.

'Towards
 the end of the video part of the filament seems to break away, but its 
basic length and shape seem to have remained mostly intact,' says Nasa.

The video, which condenses three hours of activity, also reveals the action in dramatic detail in extreme ultraviolet
 light.

The 
NOAA spaceweather prediction center warned that a cloud of radiation 
from the eruption would reach Earth today.

The radiation 
cloud will create a minor to moderate geomagnetic storm, bringing the northern lights to parts of North America, it said.

To prove the point, Nasa today revealed the image below, showing the aurora in breathtaking beauty.

Swirls of green and red appear in an aurora over Whitehorse, Yukon on the night of September 3, 2012 following a massive eruption on the solar surface

Nasa says the image is a classic example of a solar prominence (also known as a filament when viewed against the 
solar disk).

This is a large, bright feature extending outward from the Sun's 
surface.

Prominences are anchored to the Sun's surface in the photosphere, and
 extend outwards into the Sun's hot outer atmosphere, called the corona.

A prominence forms over timescales of about a day, and stable 
prominences may persist in the corona for several months, looping 
hundreds of thousands of miles into space.

However, scientists are still researching how and why prominences are formed.

The red-glowing looped material is plasma, a hot gas comprised of 
electrically charged hydrogen and helium.

The prominence plasma flows 
along a tangled and twisted structure of magnetic fields generated by 
the sun’s internal dynamo.

An erupting prominence occurs when such a 
structure becomes unstable and bursts outward, releasing the plasma.

The huge coronal mass ejection erupting on the Sun (This picture: an overlay blended version of the 304 and 171 angstrom wavelengths)

On August 31, 2012 a long filament of solar material that had been hovering in the sun's atmosphere, the corona, erupted out into space at 4:36 p.m. EDT. The coronal mass ejection, or CME, traveled at over 900 miles per second.

An image created by blending two different wavelengths of the magnificent coronal mass ejection on the Sun on 31 Aug 2012

This incredible image from NASA's Solar Dynamics Observatory (SDO) shows a very long, whip-like solar filament in the centre of the image, extending over half a million miles in a long arc above the sun's surface

The video also reveals what the filament looks like closer to the surface of the sun

This image of a previous solar filament of the sun's surface shows the scale of eruptions.

@highlight

Astonishing footage shows a 500,000 mile long 'filament' sending radiation powering towards earth

@highlight

Video captured from Nasa's Solar Dynamics Observatory