They may have intelligent sales techniques and an ability to make viewers splash the cash on items they do not necessarily need - but astronomy  is clearly not these QVC presenters' strong point.

This hilarious video shows the moment two presenters on the shopping channel go from selling a cardigan to discussing whether the Moon is a star or a planet.

As on of the presenters, Jane Treacy, displays the garish outfit, she says it looks like Earth as viewed from beyond 'planet Moon'.

Facepalm: A model (right) on the QVC cringes as the two hosts discuss whether the moon is a planet or a star

In the clip from QVC earlier this week, Ms Treacy says the cardigan 'kind of looks like what the Earth looks like when you're a bazillion miles away from the planet Moon'.

Co-host designer Isaac Mizrahi replies: 'The planet Moon...'

After hearing it out loud for herself, Ms Treacy appears to realise she has made a mistake in turning the conversation from fashion to science. 

She backtracks with: 'Isn't the Moon a star?' 

'The Moon is a planet, darling,' Mr Mizrahi incorrectly tells her. 

The show descends into a bizarre argument as the hosts try to work out what the Moon - Earth's only natural satellite - and the Sun are. 

Forgetting they are meant to be selling the cardigans, the presenters continue their argument, asking viewers to Google what the Moon is

Ms Treacy says: 'Is the Moon really a planet? Don’t look at me like that. The Sun is a star ... Is the Sun not a star?'

Mr Mizrahi replies: 'I don’t know what the Sun is.'

Viewers are then asked to Google the answer to help the confused co-hosts, who seem to have lost all interest in selling clothes.

'So what else is it?' Mr Mizrahi asks. 

Ms Treacy replies: 'I believe it's a star ... or something.' 

She adds: 'I feel like sometimes, though I am educated, I expose in this show that this blonde could be real.'

Viewers of the video on YouTube were amazed at the 'shameful display of scientific illiteracy'.

One user, called Troy, wrote: 'This should serve as inspiration. The man who believes the Moon is a planet "that things live on" is a millionaire who was a household name in the 90s for his eponymous fashion line. If he can do it, we all can. ' 

User paddles409 added: 'The moon is a hollow, artificial satellite inhabited by giant, superior, hyperintelligent, ants. Hail Ants!' 

The Moon is neither a star or a planet, it is Earth's only natural satellite.

Thought to have formed 4.5 billion years ago, scientists believe it is made from debris left from an impact between Earth and a large planet.

It orbits our planet around once every four weeks, with one side of the Moon always facing Earth.

Despite being more than 238,000 miles away, Earth's tides are mostly generated by the Moon's gravitational pull.

The first human to walk on the moon was Neil Armstrong in 1969, with a total of 12 astronauts setting foot on the satellite. No one has visited the Moon since 1972. 

Other planets in the solar system have moons, but Earth is the only one with a singular satellite.

@highlight

Video shows QVC presenters arguing over composition of the Moon

@highlight

Host gets sidetracked speculating whether the Moon is a planet or a star

@highlight

Puzzled co-hosts asked viewers for the answer as they didn't know

@highlight

The Moon is the Earth's only natural satellite - not a star or planet 