Sunderland have sacked manager Gus Poyet in the wake of Saturday’s humiliating 4-0 defeat at home to Aston Villa.

The result leaves the Black Cats one point and one place above the drop zone and owner Ellis Short believes a change of manager is needed to avoid relegation.

Poyet – who leaves after 17 months in charge – was informed of the club’s decision having taken training at the Academy of Light on Monday morning. 

Gus Poyet has been sacked by Sunderland with the club just one point above the relegation zone

Sunderland fans turned on manager Poyet during the defeat by Aston Villa on Saturday 

Sportsmail reported earlier in the day that influential sporting director Lee Congerton had advised Short to sack Poyet.

A statement on the club's website confirmed the news on Monday afternoon, in which Short said: 'I would like to thank Gus for his endeavours during his time at the club, in particular last season’s "great escape" and cup final appearance, which will live long in the memory of every Sunderland fan. 

Goalkeeper Costel Pantilimon looks dejected as Sunderland were thrashed at home by Villa

Gabriel Agbonlahor scored two of Aston Villa's goals in the 4-0 win on Saturday

525 - Poyet's number of days in charge since his arrival on October 8, 2013.

75 - The Uruguayan's number of games in charge, winning 23, losing 22 and drawing 30.

3 - The number of games against bitter rivals Newcastle. He won them all with an aggregate of 6-1.

35 - Poyet was the 35th man to manage Sunderland either permanently or as a caretaker.

22 - The number of years between Sunderland's appearances in a major final. Poyet took them to the 2014 Capital One Cup final, 22 years on from their defeat to Liverpool in the FA Cup showpiece. They lost to Manchester City.

14 - Sunderland's final position in Poyet's first season.

4 - The amount of games won in the Premier League by Sunderland this season. The joint-worst with bottom side Leicester.

'Sadly, we have not made the progress that any of us had hoped for this season and we find ourselves battling, once again, at the wrong end of the table. We have therefore made the difficult decision that a change is needed.'

Poyet’s position had become untenable after a breakdown in relationship with Congerton and the club’s fans, thousands of whom streamed for the exits with the team trailing by four at half-time against Villa.

A handful of supporters even tried to storm the dugout while some targeted the directors’ box – including chief executive Margaret Byrne - leaving the club hierarchy in no doubt that a change was necessary.

Holland boss Dick Advocaat has already spoken to the club about a short-term deal until the end of the season and he could be installed before Saturday’s trip to West Ham.

Congerton is close to Frank Arnesen – they worked together at Chelsea and Hamburg – and he is thought to have recommended Advocaat for the role.

The new man will inherit a team which has won just once in 12 matches and is without a home goal in more than five hours. 

Poyet leaves Sunderland after just over a year in charge 

Poyet was appointed by Sunderland in October 2013 following the sacking of Paolo Di Canio

They were dumped out of the FA Cup by League One Bradford City last month and away fans fought among themselves at Valley Parade.

Bizarrely, Poyet blamed the Press for Sunderland’s woes after that game but his excuses did not wash with supporters.

Former Rangers and Holland manager Dick Advocaat is one name in the frame to take over

The goodwill generated by last season’s League Cup final appearance and their escape from relegation in the final weeks of the campaign had long since evaporated and few fans will be mourning his departure.

Poyet’s backroom team of Mauricio Taricco and Charlie Oatway are also expected to leave the club.

The next home match sees North-East rivals Newcastle visit the Stadium of Light on Easter Sunday.

 

HULL

Chelsea (Home) - March 22

Swansea (Away) - April 4

Southampton (Away) - April 11

Liverpool (Home) - April 18

Crystal Palace (Away) - April 25

Arsenal (Home) - May 2

Burnley (Home) - May 9

Tottenham (Away) - May 16

Man United (Home) - May 24

ASTON VILLA

Swansea (Home) - March 21

Man United (Away) - April 4

Tottenham (Away) - April 11

Man City (Away) - April 25

Everton (Home) - May 2

West Ham (Home) - May 9

Southampton (Away) - May 16

Burnley (Home) - May 24

*QPR (Home) - Date to be arranged

 

SUNDERLAND

West Ham (Away) - March 21

Newcastle (Home) - April 5

Crystal Palace (Home) - April 11

Stoke (Away) - April 25

Southampton (Home) - May 2

Everton (Away) - May 9

Leicester (Home) - May 16

Chelsea (Away) - May 24

* Arsenal (Away) - Date to be arranged

BURNLEY

Southampton (Away) - March 21

Tottenham (Home) - April 5

Arsenal (Home) - April 11

Everton (Away) - April 18

Leicester (Home) - April 25

West Ham (Away) - May 2

Hull (Away) - May 9

Stoke (Home) - May 16

Aston Villa (Away) - May 24

 

QPR

Everton (Home) - March 22

West Brom (Away) - April 4

Chelsea (Home) - April 12

West Ham (Home) - April 25

Liverpool (Away) - May 2

Man City (Away) - May 9

Newcastle (Home) - May 16

Leicester (Away) - May 24

*Aston Villa (Away) - Date to be arranged

LEICESTER

Tottenham (Away) - March 21

West Ham (Home) - April 4

West Brom (Away) - April 11

Swansea (Home) - April 18

Burnley (Away) - April 25

Chelsea (Home) - April 29

Newcastle (Home) - May 2

Southampton (Home) - May 9

Sunderland (Away) - May 16

QPR (Home) - May 24

Note: Fixtures in May subject to change for television schedule. 

@highlight

Sunderland are just one place and one point above the relegation zone

@highlight

Gus Poyet was appointed as manager in October 2013

@highlight

Dick Advocaat has been linked with taking over until the summer

@highlight

Paolo Di Canio: Don't blame Gus Poyet, Ellis Short is the problem 

@highlight

CLICK HERE for all the latest Sunderland news as Poyet is OUT 