By 
James Chapman

PUBLISHED:

17:10 EST, 10 May 2013


| 

UPDATED:

17:10 EST, 10 May 2013

Homeowners who live within a mile of proposed wind turbines could be offered a 20 per cent discount on their electricity bills in an attempt to reduce opposition to the green technology.

Residents could also get university fee bursaries, village halls and even free home improvements as part of attempts to allow communities to ‘see the windfarms and the windfall’.

They are part of a package of measures planned by Energy Secretary Ed Davey after he was impressed by a ‘local tariff’ scheme pioneered in Cornwall.

Green energy bribe: Homeowners could be offered cut bills and university fee bursaries in return for having wind turbines nearby

Those living within 1.2 miles of the Delabole wind farm now qualify for a fifth off bills – saving the average customer about £100 a year.

The Government hopes asking firms to provide community benefits will stifle planning objections for new developments, despite critics calling them ‘bribes for blight’.

‘Onshore wind has an important role to play in a diverse energy mix that is secure, low carbon and affordable,’ said Mr Davey. ‘We know that two-thirds of people support the growth of onshore wind.

‘But far too often, host communities have
seen the wind farms but not the windfall. We are sensitive to the 
controversy around onshore wind and we want to ensure that people 
benefit from having wind farms sited near to them. In the next few weeks
we will be publishing the results of our call for evidence, which has 
looked at ways to reward host communities and ensure that wider 
investment, employment and social benefits are felt locally.’

Scheme: Homeowners could also be bribed with smaller bills if they agree to have a new generation of nuclear power station in their area. Picture shows Sizewell B

Millions of households could miss out on energy savings of more than £100 after ministers delayed the roll-out of so-called smart meters by more than a year.

The £11.7billion scheme to install the devices in 30million homes from next summer has been hit by technical issues.

Families are paying higher power bills in order to finance the project, but now many  will have to wait longer to reap the benefits.

The technology ends estimated bills by supplying precise gas and electricity readings over the mobile phone network. Families could also be helped to cut spending on power as they see meter readings in pounds and pence.

Some estimates put average savings at £65 per year based on a 5 per cent reduction in energy usage, while others have calculated savings as high as £130 on a 10 per cent cut in domestic usage.

Tom Lyon, of uSwitch.com, called it a ‘blow’ to consumers, but Energy and Climate Change Minister Baroness Verma said the industry had to ‘get it right’ before introducing the meters.

Ministers also plan to adopt a similar approach to the development of new nuclear power stations and ‘fracking’ rigs that extract underground reserves of shale gas.Mr Davey is understood to be particularly attracted to the idea of discounted electricity bills as a way of neutralising the political backlash against developments after the expansion of onshore wind power has become a major source of tension in the coalition.

The Government has set a target of increasing the amount of power generated by onshore wind farms to 13 gigawatts by 2020, with about 3,800 turbines currently constructed. But although approvals for onshore windfarms have reached record levels and the 2020 target is on course, ministers have announced a 10 per cent cut to subsidies following a shift in policy.

Meanwhile, wind farm developers are being urged by ministers to increase the amount of community benefits to win over locals because there have been so many complaints about the impact on the landscape. Along with lower energy bills, each household close to the Delabole wind farm also gets a ‘windfall’ credit of up to £50 every year that the turbines exceed their expected performance.

Power company Good Energy now runs what was Britain’s first commercial wind farm when it opened in 1991.

Company boss Juliet Davenport said: ‘Wind power has a huge role to play in meeting the UK’s future energy needs, and we think that it’s only right that our local communities should be recognised for their contribution to tackling climate change and reducing the UK’s reliance on expensive imported fossil fuels.’

At the recently-opened Kelburn wind farm, near Largs, Scotland, the community is paid £1,600 per installed megawatt – or £44,000 a year.

Caroline Flint, shadow secretary for energy and climate change, said the community benefits scheme was a form of ‘bribery’ that would reinforce the dominance of big energy companies.

Labour favours a German model that allows local communities to own renewable energy developments and keep all the benefits.

@highlight

Free home improvements could be offered in return for wind farms

@highlight

Those living within 1.2miles of Delabole wind farm get a fifth off energy bills

@highlight

Ministers could adopt same approach to new nuclear power plants