Lanes of impatient drivers and pot-hole ridden pavements can make cycling in the city seem like a battle for survival.

But now, an innovative helmet that reads a rider's brain waves is hoping to change that by mapping cyclists' stress levels.

Dubbed MindRider, the helmet uses the data it collects to create real-time maps of the best routes for stress-free city cycling.

Zoom in on the interactive map below to find out the most relaxing cycle routes in New York

The helmet is being developed by Brooklyn-based start-up DuKorp, who have been testing it on the streets of New York.

During September and October, eight riders wore the helmets while travelling Manhattan using the north-south thoroughfares.

As the wearer rode down city streets, the mind reading helmet tracked their brainwaves to measure their stress levels before plotting them on a map.

A riders' level of attention – which indicated stress - was ranked from 0 to 100, then linked onto a colour scale, from green to yellow to red. 

The 'Mindrider' helmet has a forehead-based sensor that uses EEG to measure the cyclist's brain waves. This data is then placed on to a real-time map, revealing the biker's stress levels on different city streets. Pictured are maps of Manhattan created using the system

During September and October, eight riders wore the helmets (right) while travelling Manhattan (left) using the north-south thoroughfares. The ride is shown on the map using a colour scale, with green suggesting a relaxing ride and red revealing stress

The helmet has a soft forehead-based sensor that uses EEG – or electroencephalography – to measure the rider's brain waves.It also has an ear-based sensor that's used to remove noise from the EEG signal. The current design is also Bluetooth compatible allowing the data from the EEG sensor to be fed to an app on the user's smartphone which uses the phone's GPS

After a few rides, the cyclists could analyse the data they had generated to plan the best route.

A separate crowd sourced map was also created, which gathered data to help other cyclists or city planner plan the best bike routes in their area.

Its creators hope, eventually, anyone with the helmet can share their data anonymously, and this information will be included in a real-time map online.

Developed by a designer during a visit to MIT Media Lab, the helmet looks slightly different to an ordinary bike helmet.

'The bumps are inspired by the branching neurons and shape of the brain itself,' Arlene Ducao, who created the helmet told FastCoExist.com.

'They are stylistic, but as we move toward a final design, we may use them to help secure the circuit in place.'

The new version of the helmet has a light that tells the cyclist if their anxious by glowing in area visible from the corner of their eye. Pictured is a map generated by the system which shows the 'hotspots' and 'sweet spots' in New York

A riders' level of attention – which indicated stress - was ranked from 0 to 100, then linked onto a colour scale, from green to yellow to red

The helmet has a soft forehead-based sensor that uses EEG – or electroencephalography – to measure the rider's brain waves.

It also has an ear-based sensor that's used to remove noise from the EEG signal.

An early prototype included red and green lights to warn drivers if a cyclist was particularly stressed.

That design has now been scrapped and the new version has a light that tells the cyclist if their anxious by glowing in area visible from the corner of their eye.

This can help the cyclists know when to be more cautious, and lower their stress levels by moving away from a particularly busy street.

The current design is also Bluetooth compatible allowing the data from the EEG sensor to be fed to an app on the user's smartphone which uses the phone's GPS.

The team is currently mapping local neighbourhoods in Brooklyn, New York, block-by-block.

'We think the map could still be useful to compare against traffic and accident data, and will be a cool visual proof-of-concept,' said Ms Ducao.

The Visijax Commuter Jacket contains flashing LEDs on the sleeves which are activated when a cyclist raises their arm

From smart helmets to traffic detection systems, inventors are working to make cycling safer.

Now there's a light-up jacket with built in indicators to make a biker's intentions clearer to motorists.

The Visijax Commuter Jacket contains flashing LEDs on the sleeves which are activated when a cyclist raises their arm - so that other road users can clearly see when they're making a turn.

The smart jacket also contains a built-in light on the back to help boost riders' visibility.

It runs off a handy USB-charged battery pack and comes in two colours – black and neon yellow.

The jacket will go on sale later this month at Halfords, for £99 ($150). 

'Our customers told us that better safety products would encourage them to cycle more, and the illuminating Visijax Commuter Jacket will make it easier for commuters to be seen on the roads,' said Halfords product manager Ross Hubbard said.

'We know visibility can be a major barrier to cycling at this time of year - we want to help commuters to overcome these barriers and to encourage as many people as possible to cycle.'

@highlight

The 'Mindrider' helmet has a forehead-based sensor that uses EEG to measure the cyclist's brain waves

@highlight

This data is then placed on to a real-time map, revealing the biker's stress levels on different city streets

@highlight

Ride is shown on map using a colour scale, with green suggesting a relaxing ride and red revealing stress

@highlight

Helmet is Bluetooth compatible allowing the data from the sensor to be fed to an app on user's smartphone