By 
Tara Brady

PUBLISHED:

07:07 EST, 21 April 2012


| 

UPDATED:

09:35 EST, 21 April 2012

Twin brothers are facing charges in the United States for allegedly tricking investors out of more than £700,000 with a fake stock-picking robot called Marl. 

Alexander and Thomas Hunter from Whitley Bay, North Tyneside, were just 16-years-old when they devised the 'elaborate' online scam from their bedroom in their parents' home which fooled around 75,000 people, U.S. officials have claimed. 

The brothers allegedly invented a fictitious 'stock picking robot' in 2007 and claimed on a series of websites that the highly sophisticated computer programme could identify stocks that were about the rocket in price.

Court action: Alexander (left) and Thomas Hunter (right) are accused of setting up the company from their bedroom in their parents' home in Whitley Bay

They then targeted thousands of unsuspecting investors selling them 'home versions' of the bogus software - named Marl - and annual subscription to a newsletter that listed the programme's stock recommendations, it is claimed. 

However, according to the United States Securities and Exchange Commission (SEC), which has brought the civil action, the stocks were not generated by any technical analysis and were in fact companies paying the brothers for promotion.

Legal papers filed in the U.S. District Court for the Southern District of New York yesterday claimed investors paid $47 for newsletters listing Marl's stock picks and $97 for the home software.

The twins allegedly promoted the scam on website doublingstocks.com, which claimed the robot's stock analysis earned returns of 34 per cent per week, it is said.

According to the Financial Times, investors were also told the stock picking robot had been invented by Michael Cohen, who developed the system for Goldman Sachs.

But there was no record of an employee or contractor at Goldman Sachs called Michael Cohen, the SEC said.

Meanwhile, the Hunters, now 20, received at least an additional $1.86m, about £1.5m, in fees from stock promoters for their services, which was advertised on website equitypromoter.com, it is said.

The US District Court for the Southern District of New York where the papers were filed against the twins

The site boasted of the brothers' ability to 'rocket' the price and volume of thinly traded penny stock issuers.

On the about me section, it is claimed that Thomas Hunter described himself as a 23-year-old stock trader.

'I have been trading for seven years and operate multiple penny stock websites,' he is alleged to have wrote.

When a stock promoter was signed up, the twins would then send an email to the thousands of investors subscribed to their newsletter, recommending they buy the share.

Claims: The twins allegedly created the programme from their bedroom in their parents' home in Whitley Bay, North Tyneside

Once investors followed the advice, the shares' value and volume would instantly increase.

US officials claim the brothers breached both the Securities Act and Securities Exchange Act.

The SEC is seeking permanent injunctions against the pair to prevent them from continuing to engage in securities fraud and an order requiring them to hand over any money they made, which is allegedly in UK and offshore bank accounts.

In November, Newcastle Crown Court ordered Alexander Hunter to pay back nearly $1m after he admitted providing unregulated financial advice, according to the BBC.

He was given a suspended 12-month prison sentence and ordered to carry out 200 hours of community service.

@highlight

US officials claim the brothers breached both the Securities Act and Securities Exchange Act

@highlight

But twins cannot be extradited because case is civil and not criminal 