Radiation from an earthquake may be responsible for the mysterious Turin Shroud image many believe to be a depiction of Jesus Christ, scientists claim.

An Italian team at the Politecnico di Torino, a well respected Italian University, claims the powerful magnitude 8.2 earthquake, which occurred in Old Jerusalem in the year 33 AD, would have been strong enough to release neutron particles from crushed rock.

The flood of neutrons may have imprinted an X-ray-like image onto the linen burial cloth by reacting with nitrogen nuclei, say the researchers.

According to scientists from Politecnico di Torino, radiation emissions caused by an earthquake may have confused carbon dating tests conducted in 1988 which suggested the cloth was only 728 years old, and therefore likely to be a forgery.

The first, hotly debated, documented reference to the Shroud of Turin dates back to the 14th century when a French knight was said to have had possession of the cloth in the city of Lirey.

Records suggest the Shroud changed hands many times until 1578, when it ended up in its current home, the Cathedral of Saint John the Baptist in Turin, Italy.

The 14-foot long herringbone woven cloth appears to show the faint imprint of a man bearing wounds consistent with crucifixion.

In 1898, a lawyer named Secondo Pia took the first known photograph of the cloth.

His negative revealed new details, including striking facial features that were hidden to the naked eye.

In addition, the radiation emissions would have increased the level of carbon-14 isotopes - atomic strains of carbon - in the Shroud.

According to the scientists, this may well have confused carbon dating tests conducted in 1988 which suggested the cloth was only 728 years old, and therefore likely to be a forgery.

'We believe it is possible that neutron emissions by earthquakes could have induced the image formation on the Shroud's linen fibres, through thermal neutron capture on nitrogen nuclei, and could also have caused a wrong radiocarbon dating,' said Professor Alberto Carpinteri, from the Politecnico di Torino.

The new theory is published in the journal Meccanica.

Other scientists have previously suggested that neutron radiation may have been responsible for the ghostly image of a crucified man with his arms crossed.

However, no plausible explanation has been offered for the source of the radiation.

Some have proposed that it came from the body itself, or was generated by an event inside the tomb, pointing to a divine origin linked to the resurrection.

Neutron radiation is usually generated by nuclear fusion or fission, and may be produced by nuclear reactors or particle accelerators.

Prof Carpinteri's team believes earthquake-induced high pressure waves in the Earth's crust may be an overlooked natural source.

The face of Jesus? Other scientists have previously suggested that neutron radiation may have been responsible for the ghostly image of a crucified man with his arms crossed. However, no plausible explanation has been offered for the source of the radiation until now.

The scientists base the idea on research into piezonuclear fission reactions which occur when brittle rock is crushed under enormous pressure.

During the process, neutron particles are released from atoms.

A powerful earthquake could achieve the same effect, generating neutron radiation from stresses in the Earth, it is claimed.

Mark Antonacci, a leading expert on the Shroud and president of the Resurrection of the Shroud Foundation, is currently petitioning Pope Francis to allow molecular analysis of the cloth using the latest technology.

It is hoped that such an investigation will be able to confirm or rule out the radiation theory.

The first, hotly debated, documented reference to the Shroud of Turin dates back to the 14th century when a French knight was said to have had possession of the cloth in the city of Lirey.

Records suggest the Shroud changed hands many times until 1578, when it ended up in its current home, the Cathedral of Saint John the Baptist in Turin, Italy.

The 14-foot long herringbone woven cloth appears to show the faint imprint of a man bearing wounds consistent with crucifixion.

In 1898, a lawyer named Secondo Pia took the first known photograph of the cloth.

His negative revealed new details, including striking facial features that were hidden to the naked eye.

@highlight

Magnitude 8.2 earthquake occurred in Old Jerusalem in 33 AD

@highlight

Flood of neutrons could have confused carbon dating which recently found shroud is just 728 years old

@highlight

May have been responsible for imprinting 'x-ray' image onto the cloth