Mars is most definitely an alien landscape, with its barren craters and huge mountains.

However, researchers have now got a new insight into possibly its most bizarre region.

Known as 'chaos terrain', the areas have dozens or even hundreds of isolated mountains up to 2000 metres high  scattered through them.

Scroll down for video 

Hydraotes Chaos, a large basin, approximately the size of the German state of Baden-Württemberg, lies in the Martian highlands, near the equator.

The area has  isolated mountains up to 2000 metres high scattered through it. Seen from orbit, they form a bizarre, chaotic pattern.

Scientists believe that water in the form of ice was stored in cavities beneath the surface of the highlands early in the history of Mars; this was then heated and thawed out. 

It was then placed under so much pressure that it escaped to the surface with great force through fissures and fault zones. 

As it flowed out, the water eroded the terrain and gradually left behind the striking landscape visible today. 

Among the most interesting landforms on Mars are features referred to as 'chaotic terrain', the DLR, Germany's national aeronautics and space research centre, which created the video, said.

Dozens or even hundreds of isolated mountains up to 2000 metres high are scattered in these extensive regions. 

Seen from orbit, they form a bizarre, chaotic pattern. 

Such terrains are found over a large area to both the west and east of Valles Marineris, the largest canyon in the Solar System. 

Hydraotes Chaos is a typical example of this type of landscape. 

This large basin, approximately the size of the German state of Baden-Württemberg, lies in the Martian highlands, near the equator.

Headwaters of large rivers that flowed from the highlands

'No comparable landforms are found on Earth,' said DLR.

'Scientists believe that water in the form of ice was stored in cavities beneath the surface of the highlands early in the history of Mars; this was then heated and thawed out. 

'It was then placed under so much pressure that it escaped to the surface with great force through fissures and fault zones. 

The data used to generate these images and the simulated overflight were acquired by ESA's Mars Express spacecraft.

The High Resolution Stereo Camera (HRSC), operated by the German Aerospace Center (Deutsches Zentrum für Luft- und Raumfahrt; DLR) on board

Once again, image strips from orbit 18 – symbolically significant for the HRSC scientists – were edited and used for the animations and images shown here. 

Over 10 years ago, in January 2004, Mars Express flew over Hydraotes Chaos during orbit 18. 

This was the third time that the HRSC camera had been switched on, and the images in the image strips, which were over 1000 kilometres long, were so spectacular that they were drawn on for publication of the first images from the successful ESA mission. 

To be able to show the western half of the Hydraotes Chaos basin in a larger regional context, additional HRSC images from subsequent orbits were used for the large image mosaic. 

The region shown is around 400 by 200 kilometres.

'As it flowed out, the water eroded the terrain and gradually left behind the striking landscape visible today.' 

Another factor supporting this theory is that many of the chaotic terrains on Mars are located at the head of large outflow channels, through which enormous quantities of water flowed out of the highlands towards the northern lowlands.

The quantities of water that were first stored in Hydraotes Chaos and then flowed northward through Simud Valles must have been enormous. 

Such terrains are found over a large area to both the west and east of Valles Marineris, the largest canyon in the Solar System. Hydraotes Chaos is a typical example of this type of landscape (inset)

They flowed away from a drainage area about 1500 kilometres in diameter, an area approximately the size of central Europe. The Hydraotes basin is 420 kilometres in diameter. 

It is thought to have formed a very long time ago – over three and a half billion years – during the Noachian Period on Mars.

Generation of the images and animations

The images and animations were generated by the Planetary Sciences and Remote Sensing Group at Freie Universität Berlin, which was headed by Gerhard Neukum (1944 – 2014) from the beginning of the Mars Express mission.

 

@highlight

Known as 'chaos terrain', the areas have dozens or even hundreds of isolated mountains

@highlight

Mountains up to 2000 metres high are scattered through them

@highlight

Large basin is approximately the size of the German state of Baden-Württemberg

@highlight

Lies in the Martian highlands near the equator 