Mind control has reached new heights after a group of pilots were successfully able to fly a plane using nothing but their thoughts.

German scientists showed how seven pilots – some with no previous experience of flying – used mind control to fly with ‘astonishing accuracy.’

In a simulation, several of the pilots managed the landing approach under poor visibility, while one was able to land a few metres from the runway’s central line.

Scroll down for video

Mind control has reached new heights after a group of pilots were able to successfully fly a plane using nothing but their thoughts. German scientists showed how seven pilots – some with no previous experience of flying – used mind control to fly with ‘astonishing accuracy'

Under the EU-funded project ‘Brainflight’ project, scientists hooked participants up to a cap containing dozens of electroencephalography (EEG) electrodes.

Researchers at the Technical University of Munich and the Technical University of Berlin then sat them down in a flight simulator and told them to steer the plane using just their thoughts .

The cap was able to read the electrical signals from their brains and a specially-formulated algorithm then converted those signals into computer commands.

In a simulation, several of the pilots managed the landing approach under poor visibility, while one was able to land a few metres from the runway’s central line. However, one problem with the system is lack of feedback

Seven people underwent the experiment and all were able to use mind control to control the plane well enough to meet some of the criteria for getting a pilot's license.

The human brain is made up of billions of active neurons that have around 105,600 miles (170,000 km) of combined length.

Every time you have a thought, your brain produces weak but distinct electrical signals corresponding to it.

The electrical impulse is generated by the chemical reaction between neurons, which can be measured.

Recording and deciphering those signals is called electroencephalography (EEG), and it has been medically possible since 1924.  

‘A long-term vision of the project is to make flying accessible to more people,’ said aerospace engineer Tim Fricke, who heads the project at the Technical University of Munich.

‘With brain control, flying, in itself, could become easier. This would reduce the work load of pilots and thereby increase safety.

‘In addition, pilots would have more freedom of movement to manage other manual tasks in the cockpit.’

Our brain is made up of billions of active neurons, around 105,600 miles (170,000 km) of combined axon length.

When these neurons interact, the chemical reaction emits an electrical impulse, which can be measured using EEG.

One of the problems with the system is lack of feedback. Normally, pilots feel resistance in steering and have to exert significant force when the loads on the aircraft become too large.

Under the EU-funded project ‘Brainflight’ project, scientists hooked participants up to a cap containing dozens of electroencephalography  electrodes (left). The right image shows the computer display used in the simulation to help the pilots guide the plane to safety

This feedback is missing when using brain control. The researchers are now hoping to find alternative methods to simulate the process.

But this isn’t the first time mind control has been used to fly an object. Last year a remote controlled helicopter was flown through a series of hoops using the power of the human mind.

The feat was achieved by U.S. researchers who are hoping to develop future robots that can help restore the independence of paralysed victims and those suffering from neurodegenerative disorders.

According to Professor Bin He, from the University of Minnesota, the achievement in 2013 was the first time that humans have been able to control the flight of flying robots using just their thoughts.

‘A long-term vision of the project is to make flying accessible to more people,’ said aerospace engineer Tim Fricke, who heads the project at the Technical University of Munich.‘With brain control, flying, in itself, could become easier. This would reduce the work load of pilots and thereby increase safety'

 

@highlight

Seven pilots were able to control a flight simulator using just their thought

@highlight

They each wore a cap that could read the electrical signals from their brain

@highlight

Algorithm was then able to convert those signals into computer commands

@highlight

‘A long-term vision of the project is to make flying accessible to more people,’ said Technical University of Munich's Tim Fricke