Up to half the food we buy from supermarkets goes in the bin despite much of it being perfectly edible, a report reveals today.

Experts say a throwaway consumer culture that undervalues food is behind the colossal waste.

They blame confusion over sell-by dates and retailers’ ‘buy one, get one free’ offers that tempt shoppers into buying more than they need.

Waste: Seven million tons of food, worth more than £10billion, is wasted in the UK every year, according to a report by the Institution of Mechanical Engineers

Across the country seven million tons of food, worth more than £10billion, is thrown away annually – costing the average household £480 each year.

Of the food binned by families, from fresh fruit and veg to tinned and packet produce, £1billion worth is still within its sell-by date and good to eat.

The report, by the Institution of Mechanical Engineers, says that up to three quarters of vegetables grown in Britain ends up never being eaten, with large amounts being left in the field or rejected by supermarkets for being too ugly.

Confusion: The report's author places some of the blame for food wastage on special offers in supermarkets that result in consumers 'buying more produce than they need'

Author Dr Tim Fox, head of energy and environment at the IME, said that over a lifetime an average household will throw away up to £24,000 worth of food.

He said: ‘Between 30 and 50 per cent of food bought from supermarkets is thrown away. It gets home from the shops, placed in the cupboard or fridge, and then up to half of that food goes in the bin.

‘One of the problems is the way supermarkets retail. Consumers end up buying more produce than they need because of special offers. Many of these items have a limited shelf life, so they end up being thrown away.

‘And with much of our fresh fruit being imported from around the globe, it does not have the lifespan of locally produced food because it has already spent days travelling.

‘There is also confusion over labelling and sell-by dates, with many people opting to throw away perfectly good food.’

The average British family spends only 11 per cent of its budget on food, which explains why it is not valued more highly, the report found.

Dr Fox said: ‘With the shift away from small shops on the High Street to large-scale supermarkets, we have lost the sense of value of food.’

Almost a third of vegetables are never harvested and are ploughed back into the field because of overproduction and for aesthetic reasons, according to the report, Global Food: Waste Not, Want Not.

‘Many farmers produce more than is necessary as back-up to meet the strict criteria in the supply agreements set by supermarkets,’ said Dr Fox.

Warning: Author of the report Dr Tim Fox said between 30 and 50 per cent of food bought in supermarkets is thrown away and warned that people had 'lost the sense of value of food'

With a further 30 per cent never 
making it to the supermarket shelf because they are considered too ugly 
to be sold, only half a farmer’s crop is likely to be sold.

The
 misshapen produce is either left to rot in the field, sold off to be 
added to manufactured products such as soup, used as animal feed, or put
 in composting.

But, once consumer waste is factored in, up to three-quarter of vegetables never make it on to a family’s plate.

Dr Fox said: ‘It is remarkable that you get any food to the table at all. Up to 75 per cent of the veg grown in the UK doesn’t end up being eaten. That’s the bottom line.

‘With a lot of vegetables, it is simply the fact that it just doesn’t look right. The crop is not harvested simply because it will not sell, but apart from appearance they are perfectly edible.

‘Although schemes are in place to sell some of this veg in different outlets, not enough is being done to tackle this waste.’

The picture remains the same across the globe, with around half of all food produced – two billion tons worth – lost to waste. But in developing countries the issue is one of storage rather than profligacy.

Others have queried the report’s figures, with the food waste campaigners WRAP saying only one fifth of all the food and drink we buy as consumers ends up unused in the bin.

Unused: Food waste expert Emma Marsh said that preparing too much food was one reason for waste, while misunderstanding over labels was another factor

Food waste expert Emma Marsh said: ‘Our research has shown that 7.2million tons of food and drink waste is generated by households in the UK each year. Of this, 4.4million tons is avoidable food waste. This avoidable food waste has a value of £12billion per year.’

She said that preparing too much food was one reason for waste, while misunderstanding over labels was another factor.

Andrew Opie, director of food and sustainability at the British Retail Consortium, which represents retailers, said: ‘Using more of the crop to cut food waste and increase sustainable production is an objective for all retailers. This is how we are exceeding Government targets for food waste.

‘It was supermarkets that lobbied Europe to relax strict marketing rules on fruit and veg to allow us to sell more misshapen produce. This has led to an enormous increase in the sale of “wonky” veg.

‘We’ll continue to work with growers to use more British produce, cut food waste and give customers great value. It’s a win, win, win.’

@highlight

Seven million tons of food worth £10billion is thrown away every year

@highlight

Of the wasted food £1billion is still within sell-by date and good to eat

@highlight

Three quarters of vegetables grown in Britain never get eaten

@highlight

Report by Institution of Mechanical Engineers blames supermarkets

@highlight

Says average household wastes £24,000 worth of food in lifetime