Fans of Fifty Shades Of Grey, you've been warned: leave those whips and riding crops at home on your way to the movies next week.

AMC, Regal Entertainment and Cinemark have banned movie goers from bringing naughty props to the cinema in anticipation of the hotly awaited world premiere of Fifty Shades Of Grey.

The film adaptation of EL James' steamy best-selling erotic romance starring Jamie Dornan as Christian Grey and Dakota Johnson as Anastasia Steele hits the big screen on Valentine’s Day, February 14.

Scroll down for videos 

Cracking the whip: Fans of Fifty Shades Of Grey have been warned by theaters against bringing whips, handcuffs and other BDSM props to the movies

Steamy: The screen adaptation of EL James' best-selling erotic romance  hits the big screen on Valentine’s Day

Keeping it PG: AMC is one of three movie theater chains that has issued a ban on sex toys ahead of the Fifty Shades premiere

The ticket-buying site Fandango said pre-sales have propelled Fifty Shades into the 15-year-old company's all-time Top 5 for R-rated selections. Several hundred screenings have already sold out.

With excitement generated by the R-rated film reaching a fever pitch, the three American cinema chains have put out statements asking customers to leave all their bondage accessories at home, including whips, paddles, handcuffs and ropes.

‘While we welcome those guests who want to show their excitement for a film by dressing up in costume, we do not permit weapons (real or fake), or props/costumes that would make guests uncomfortable, or detract from the moviegoing experience,’ AMC Theaters spokesman Ryan Noonan tells Consumerist.com. 

Author: E.L. James attends the Fifty Shades Of Grey' New York Fan First screening at Ziegfeld Theatre on February 6, 2015

On-screen lovers: Actors Jamie Dornan (L) and Dakota Johnson attend the Fifty Shades Of Grey New York Fan First screening at Ziegfeld Theatre Friday

In the past, superfans of popular franchises like the Harry Potter series, Star Wars and Sex and the City, were welcome to show up at the theater dressed as their favorite character, or carrying a wand or a light saber.

But it appears that cinemas are drawing a line when it comes to bondage paraphernalia.

The three books written by EL James have reportedly sold over 100 million copies worldwide and been translated into more than 50 languages. 

@highlight

AMC, Regal Entertainment and Cinemark have banned customers from bringing naughty props to the movies 

@highlight

Adaptation of EL James' best-selling erotic romance starring Jamie Dornan and Dakota Johnson  hits the big screen on Valentine’s Day