It is regarded as one of the world's safest and most popular jets, which comes complete with a range of technologies designed to keep it in touch with air traffic controllers on the ground.

Fitted with an ASD-B flight transponder which, unlike the GPS in a car, broadcasts its location by sending information back to air traffic controllers every second, the Boeing 777 would appear to have the necessary technology to prevent it disappearing completely without a trace.

Yet early Saturday morning, this is precisely what happened to Malaysia Airlines flight MH370, as it made its way, 35,000 ft in the air, from Kuala Lumpur to Beijing.

The service is being offered to 11,000 planes already equipped with an Inmarsat satellite connection, stock image of a Boeing 777 cockpit is pictured. The firm claims the service will cover 'virtually 100 per cent of the world's long haul commercial fleet'

The plane would also have been fitted with an indestructible black box recorder and a beacon to continue transmitting its location should it land in water

The Malaysia Airlines Boeing 777-200ER that disappeared from air traffic control screens Saturday (2011 file picture)

The transponder on the plane, which is also fitted with an indestructible black box recorder and a beacon to continue transmitting its location should the aircraft land in water, should provide air traffic controllers on the ground with the aircraft's speed, altitude and direction, according to Tom Clarke, of Channel 4 News.

But the signal from the transponder appears to have been lost at about 1.20am, without a change in altitude or course, which has suggested to some a sudden event caused the plane to crash.

Crews however are also able to speak to their airline through 'discrete radio channels', according to aviation expert John Goglia, writing on the Forbes website.

Again, he argues the sudden end to all communication, without a distress signal, suggests a 'catastrophic failure of the aircraft'.

He says:  'A complete electrical failure is extremely unlikely because of redundancies in the system, especially the ram air turbine which uses the power of the wind generated by the aircraft’s motion in flight to generate electricity which would power critical navigation and communication systems, as well as flight controls.  

'But even if the aircraft had a complete electrical failure, the aircraft could have continued to fly.'

Malaysia's Department Civil Aviation Director General, Azharuddin Abdul Rahman, pictured left, with Malaysian Airlines CEO Group Ahmad Jauhari Yahya, pictured right, during a press conference on the new search area

A cabin crew of Division 918 of the Vietnam Air Force is onboard a flying Soviet-made AN-26 during the search operations

He goes on to argue the plane could have eventually flown to an area where it would have been picked up again by radar, concluding it was 'too early to speculate' on what has caused the disappearance.

The long-range jumbo jet has helped connect cities at the far ends of the globe, with flights as long as 16 hours.

But more impressive is its safety record: The first fatal crash in its 19-year history only came last July when an Asiana Airlines jet landed short of the runway in San Francisco. Three of the 307 people aboard died.

Airlines like the plane because it is capable of flying extremely long distances thanks to two giant engines.

Each engine is so massive that a row of at least five coach seats could fit inside it. By having just two engines, the plane burns through less fuel than four-engine jets, like the Boeing 747, which it has essentially replaced.

'It has provided a new standard in both efficiency and safety,' said Richard Aboulafia, an aviation consultant with the Teal Group.

An iPad is used to support orientation by a military official inside a Vietnamese Air Force plane during search and rescue operations for the missing Malaysian Airlines flight

Vietnamese military personnel prepare a helicopter for a search and rescue mission for the missing Malaysia Airlines flight

'The 777 has enjoyed one of the safest records of any jetliner built.'

Besides last year's Asiana crash, the only other serious incident with the 777 came in January 2008 when a British Airways jet landed about 1,000 feet short of the runway at London's Heathrow Airport.

Malaysia Airlines did have an incident in August 2005 with a 777 flying from Perth, Australia, to Kuala Lumpur, Malaysia's largest city.

While flying 38,000 feet above the Indian Ocean, the plane's software incorrectly measured speed and acceleration, causing the plane to suddenly shoot up 3,000 feet.

The pilot disengaged the autopilot and descended and landed safely back in Perth. A software update was quickly made on planes around the world.

Malaysia Airlines has 15 Boeing 777-200ER jets in its fleet of about 100 planes. The first was delivered on April 23, 1997, and the most recent on December 13, 2004, according to Boeing. The 200ER is one of four versions of the 777.

 

@highlight

Plane's transponder should provide information to air traffic controllers

@highlight

But at around 1.20am on Saturday, transponder on flight MH370 appears to have stopped working

@highlight

Experts say loss of communication suggests 'catastrophic failure'

@highlight

But it is 'too early to speculate' on what caused the disappearance