'Not acceptable': Theresa May fears relaxing visa rules for Chinese tourists could open the door to an influx of organised crime gangs

Theresa May has blocked plans to make it easier for Chinese tourists to get visas because she fears it would lead to a rise in organised crime, it has been revealed.

The Home Secretary has warned that national security would be threatened and criminals would be brought in if checks on Chinese visitors were relaxed.

A leaked letter from Mrs May's private secretary to the Prime Minister’s private secretary reveals her staunch opposition to the plans by Cabinet colleagues.

According to the Daily Telegraph, the letter said: 'The proposal... is not acceptable to the Home Secretary for national security reasons. At Cabinet, the issue of asylum claims was discussed.

'We also face significant challenges with Foreign National Offenders and organised crime including drugs, money laundering, fraud, criminal finances, intellectual property, immigration and cyber crime.'

Culture Secretary Jeremy Hunt has raised concerns that potential tourists are being put off visiting the UK because of the expensive and difficult visa system.

He is understood to be supported by the Chancellor, George Osborne, and Business Secretary, Vince Cable.

But Mrs May has rejected the proposals to let Chinese tourists apply for European and British visas at the same time as she believes their checks ‘do not match the UK decision quality’.

Economic boost: Official figures show that Chinese visitors typically spend an average of £1,700 per trip to the UK

She has also pointed to figures that show 400 Chinese criminals are awaiting deportation and there were 1,000 applications for asylum from Chinese citizens last year.

Official figures show that Britain is losing out on the potential income generated by Chinese visitors, who typically spend £1,700 each per trip.

Around 147,000 came to the UK last year compared to 1.2million who went to France.

The Home Office said last night that improvements had been made to the Chinese service, including bringing in more visa officers and introducing an online application process, but declined to comment on the letter.

@highlight

Leaked letter reveals Home Secretary's opposition to Cabinet proposals