Overcome: Zane, seven, died in his sleep during last winter's floods as waters rose around Surrey home

Parents who suspect their seven-year-old son was killed by cyanide gas during last winter’s floods say authorities knew there was a risk of deadly ‘ground gas’ at their home but did not warn them.

Zane Gbangbola was overcome by fumes while he slept as floodwaters rose in the basement of the house during storms in February .

His parents were taken to hospital suffering from the effects of hydrogen cyanide poisoning and his father Kye has been left a paraplegic due to exposure to the gas.

Now it has emerged that the Environment Agency and the local council were aware of potential risks of ground gas from an old landfill site next to the Gbangbolas’ riverside home.

The Environment Agency – which is responsible for regulating waste sites and dealing with floods – even installed a gas-proof membrane at a cabin it built four years ago next door to their house, but did not warn residents about the risk.

Council documents also show that as far back as 2007 planning officials knew that the ground could contain ‘harmful substances’ – but residents were only told if they applied for permission to alter their homes.

The revelations are the latest twist in an eight-month battle by Kye and Nicole Gbangbola to find the truth about their son’s death.

After receiving a letter of condolence from David Cameron, they met Ministers last week and will meet Liz Truss, the Environment Secretary, later this month.

They have accused the police and authorities of a cover up, after Zane’s death was attributed to carbon monoxide poisoning, supposedly caused by a faulty petrol-driven pump.

A pathologists’ report initially said that said the cause of death was ‘inconclusive’, but after further tests, it was changed to ‘carbon monoxide poisoning’.

But the couple say that is impossible as they never used the hired pump in their house.

Zane’s parents believe he must have been overcome by hydrogen cyanide released by the floods from contaminated land in an old landfill 20 yards from their home.

Scientists have told The Mail on Sunday that the deadly gas – used in the Nazi death camps – could have come from the former landfill site behind the family’s home, generated by water rising through the landfill soil.

Zane’s family say he would still be alive if they had been told of the danger lurking just beyond their property, a riverside home in Chertsey, Surrey.

His death sparked panic in the early hours of February 8 as 17 residents were sent to a decontamination ward and warned that hydrogen cyanide had been detected at the home by firefighters.

Flooded: The houses in Chertsey surrounded by flood waters close to the old landfill site (bottom left field)

Tragedy: The home of Kye and Nicole Gbangbola during the floods in February where their son, seven, died

Some neighbours were told they may have only 15 minutes to live.

Last night Mr Gbangbola said: ‘If we had been told the land was contaminated we would have been able to protect ourselves.’

The company director added: ‘To put down a gas membrane in their own property suggests the Environment Agency had real concerns about ground gases such as hydrogen cyanide. So why didn’t they tell anyone else?’

Inundated: The well-defended Environment Agency-owned hut next to the family's home

Last night the family’s MP, Kwasi Kwarteng, accused the EA of ‘dragging its feet’. He said: ‘If the Environment Agency had some intelligence there were gases there and used a gas membrane when they built their property, that is significant and we need to find out more information about it.

‘It is an appalling tragedy and we need some action.’

After Zane’s death, police investigations focused on a petrol-driven pump the family hired to remove floodwater from the basement.

The couple insist the pump was never switched on during the flood. They say the pathologist was not told to test Zane’s blood for the presence of hydrogen cyanide – which disappears from the body within 48 hours.

Pollution expert Dr Mark McKinney said: ‘There is no reason to put down a gas membrane unless there is evidence and concern about ground gases.’

Asked about the membrane at the hut, an EA spokesman said: ‘The local authority was satisfied our desktop study identified basic ground protection as entirely appropriate as a purely precautionary approach.’ 

In a new statement last night the Environment Agency said: 'In 2010 we built the property with standard damp-proofing protection as it's a timber structure on low-lying land.

'Our sincere sympathies continue to be with the Gbangbola family and we are cooperating with the investigation fully.'  

Spelthorne Council said: 'A desk-top study prepared by the Environment Agency's consultant was submitted to the Council. It recommended basic ground gas protection as an alternative to undertaking monitoring and assessment. This is common practice.' 

Surrey Police said: ‘We are conducting further enquiries to establish whether there is any liability or criminal offences in respect of the hire company who provided [the pump] and we have submitted a file to the Crown Prosecution Service.’

More than 15,000 people have signed a petition demanding the ‘Truth About Zane’ and the family has the support of celebrities including Vivienne Westwood, Emma Thompson and Peter Gabriel.

Zane would have been eight on Tuesday, and his parents and their supporters are set to mark the day with a march on Spelthorne Borough Council’s offices in Staines at 1pm.

Celebrity support: Designer Vivienne Westwood (left), musician Peter Gabriel (centre) and actor Emma Thompson (right) have signed a petition demanding the 'Truth About Zane'

Warning: A 2007 planning condition for a nearby extension within '250m of a current or historical landfill site'

 

@highlight

Seven-year-old Zane Gbangbola was overcome by fumes as he slept

@highlight

Floodwaters filled basement of home in Chertsey, Surrey in February

@highlight

It's emerged authorities were aware of potential risks from ground gas

@highlight

Council papers from 2007 say ground could contain 'harmful substances'

@highlight

Revelations are latest twist in eight-month battle by Zane's parents