His assignment had been to encourage youngsters to take up skiing.

But while Prince Daniel’s his prowess on the slopes would have impressed his young audience, the view might not have proved quite so inspirational.

The prince, whose title is the Duke of Västergötland, is the husband of Crown Princess Victoria of Sweden.

Sweden's Prince Daniel visited the Hammarbybacken ski resort in Stockholm for the annual All on the Snow day which aims to inspire children to take up the sport

He has been invited to take part in the annual ‘Alla på Snö’ day or ‘All on the Snow’ day together with a group of children aged between nine and ten at Hammarbybacken, a ski resort in Stockholm.

However, the resort is a man-made hill constructed on the site of a former rubbish dump.

Rather than offering visitors picturesque views of towering mountain ranges, guests are given sweeping views of high-rise apartment buildings and a sprawling car park.

Built in 1983, the resort opened in 1990. In the past it has encountered problems with stopping the snow from melting because of the heat generated by the large highway running along the base of the slopes.

However, the resort is a man-made hill constructed on the site of a former rubbish dump

Rather than offering visitors picturesque views of towering mountain ranges, guests are given sweeping views of high-rise apartment buildings and a sprawling car park

The resort was renovated in 2006 and snowmaking machines installed to make sure the visitors are able to ski.

Reviews of the resort have been mixed, with one describing it ‘as basic as can be’.

However, it is popular with local swedes who don’t have the time to travel further away to the ski in the country’s mountain ranges.

The ‘All on the Snow event attended by Prince Daniel is arranged by the Swedish Ski Council, and allows children a chance to ski on the slopes for free.

Prince Daniel is normally seen in more formal attire as here with Crown Princess Victoria at the Royal Palace

They are offered the chance to go sledging and cross-country skiing, all for free with the point of the day being to promote ski sport.

Prince Daniel appeared quite at home on the piste as he glided expertly down the hill wearing a crash helmet and goggles.

Prior to his marriage to the heir to the Swedish throne, Daniel was a personal trainer and gym owner.

@highlight

Prince Daniel was visiting the Hammarbybacken ski resort in Stockholm

@highlight

The prince was taking part in the annual 'All on the Snow' day

@highlight

The event is aimed at encouraging children to take up skiing

@highlight

The resort was built in the 1980s and constrcuted on site of rubbish dump 

@highlight

Resort popular with locals who don’t want to travel to the country’s mountain ranges