By 
Ray Massey, Transport Editor

PUBLISHED:

17:26 EST, 12 June 2013


| 

UPDATED:

09:23 EST, 13 June 2013

Trials of 80mph motorway speed limits could start next year, the road safety minister said yesterday.

Stephen Hammond said raising the limit to 80mph is still firmly on the Government’s agenda.

There will be three trials of the higher speeds in different areas, and if successful they will be introduced across the country.

The higher 80mph speed limit could be trialled at three sites across the country as early as next year

Speaking in a magazine interview Mr Hammond said: ‘It is not dead. We are thinking about it. We are thinking about how we could trial it rather than go to a consultation.

‘It would be important to have a good evidence-based trial.’

He said there will be an announcement in the autumn on the prospect of an increase and that trials could take place during 2014.

He told Auto Express magazine: ‘You probably will not see it happen before the summer of next year. It might need a whole year to put the whole regulatory format in place.

‘My message, though, is that it [80mph] has not been lost. Our philosophy is that we should have the right speed on the right road.’

He added: ‘Drivers will have noticed that we have made some significant changes to guidelines to local authorities about lower speeds in rural areas.

‘We have also made it easier to introduce 20mph limits and zones.’

Supporters of the idea argue that motorways are the safest of all roads and that cars become safer at speed.

Road safety minister Stephen Hammond (left) said 80mph speed limits are still on the Government's agenda but Transport Secretary Patrick McLoughlin (right) is said to be 'cooler' on the issue

The move towards an 80mph limit has 
fallen down the Department for Transport’s list of priorities under 
Transport Secretary Patrick McLoughlin, who is said to be ‘cooler’ on 
the issue.

By contrast, former transport secretary Philip Hammond was a major supporter, arguing that raising the limit could ‘provide hundreds of millions of pounds for the economy’, generated by lowering journey times.

Road safety charity Brake opposes the plans, arguing an 80mph limit is likely to ‘lead to more deaths, crashes and serious injuries’.

But AA president Edmund King said: ‘Our view is that 80mph in a modern car, in good weather, driven at a safe distance from the car in front is a safe speed.

‘Whereas 50mph in bad weather, tailgating the car in front is a very dangerous speed.’

Auto Express editor in chief Steve Fowler said: ‘My personal view is we don’t need an increase to 80mph. ‘Everyone knows people drive faster than 70mph on motorways.

'If the limit were to increase to 80mph, people would drive at 90mph.’

Mr Hammond said the Government has made it easier to introduce 20mph limits and zones

Supporters of raising the speed limit point out that when the current 70mph limit was introduced in 1964, it was set at the flat-out speed of most cars which were pretty basic compared with today’s.

Last February Labour announced that, subject to safeguards, it was dropping its opposition to raising the limit and supported a switch to ‘variable’ limits of up to 80mph as a ‘safer alternative’ to blanket rises.

A recent Road Safety Foundation report found motorways do not currently provide enough protection to drivers and car occupants to justify raising the speed limit. It notes England’s motorways account for 6 per cent of road deaths.

Professor Stephen Glaister, director of the RAC Foundation, said: ‘If the limit is raised then there is likely to be an increase in carbon emissions and deaths.

‘The big question is at what speed the police will enforce a new limit. Will 80mph actually mean 90mph?

'The irony is that free flow speeds on motorways have actually fallen in recent years, so you have to question the public appetite for a change.’

@highlight

Stephen Hammond said an announcement will be made in the autumn

@highlight

Trials could go ahead as early as summer 2014