By
Daily Mail Reporter

Social media really is the end of privacy, if a new algorithm developed by IBM is anything to go by.

The tech giant announced on Friday that they have come up with a formula that can track the home city of any Twitter user based on the metadata contained in their last 200 tweets.

According to The Daily Caller, the formula has an almost 70 percent rate of accuracy.

It's the latest research finding to highlight the possible danger to privacy and security presented by metadata collection and analysis.

Be careful what you Tweet: IBM researchers have developed an algorithm that predicts your home location using your last 200 tweets

Researchers say that advertisers looking for specific areas to market and journalists covering major news events have the most to gain from the algorithm.

Research head Jalal Mahmud said IBM began the process by seeing whether they could predict the location of a Twitter account by analyzing tweets and matching the content against their geotagged metadata.

One of twitter's options features allows for location tagging.

The team started by tracking geotagged tweets from the 100 largest cities in America between July and August 2011, and isolated 100 users out of each location.

Researchers then examined the last 200 tweets from each user, discounting private tweets from the mix, and were left with 1.5 million geotagged tweets from almost 10,000 users.

Ten percent of the data was then set aside to test against later, while the bulk 90 percent was analyzed layer upon layer to create the location-estimating formula.

The new formula has again raised questions about social media and privacy, especially for those who would rather their home location remained private

Key to the formula is the additional information users are including in their tweets – 100,000 pulled from the team’s data collection were submitted by users linking their Twitter accounts to the popular Foursquare location-based social networking platform, and in 300,000 other cases, users included the names of cities from the U.S. Geological Service gazetteer in tweets.

The team also found the national distribution of tweets was more or less constant on a daily basis, which allowed them to isolate user’s time zones based on their tweet pattern.

Even the specifically-worded content of posts themselves aided tracking when users would type in things like the name of a sports team, for example.

With their algorithm established, the team then used it on the 10 percent of data set aside before analysis, and found that in less than one second for each individual it was able to correctly identify a user’s home city 68 percent of the time, home state 70 percent, and time zone 80 percent.

@highlight

IBM researchers went through Twitter to find 100 different users in the 100 biggest cities in the US

@highlight

They downloaded the last 200 tweets posted by each user, giving them 1.5 million tweets

@highlight

100,000 of those were generated by Foursquare, giving an exact location

@highlight

Almost 300,000 tweets contained the name of cities listed in the US Geological Service gazetteer

@highlight

Other tweets contained clues to their location like phrases such as 'Let’s Go Red Sox'