By
Anders Sandberg, The Conversation

Predicting or worrying about disasters is a popular pastime.

But when somebody with money at stake becomes concerned, we really start to take notice.

Financial people likely sat up when Paul Singer, manager of the Elliott Management hedge fund, warned in his latest newsletter of the risks association with electromagnetic pulses.

The Earth has a vast natural magnetic field, courtesy of currents inside its core. As long as it is stable it is not noticeable except for turning compass needles. But if something forced it to move, the shift across miles of cable can induce currents strong enough to burn out fuses or damage transformers

'Even horrendous nuclear war, except in its most extreme form, can be a relatively localised issue, and the threat from asteroids can possibly be mitigated,' he wrote. 

'The risks associated with an electromagnetic pulse, or EMP, represent another story entirely.' 

Electricity and magnetism are tightly linked. Change an electric field – for example by moving charge – and a magnetic field appears.

Change a magnetic field – for example by rotating a magnet – and electric fields appear. 

This is why electromagnets, generators and antennas work. Electromagnetic waves, whether radio, light or X-rays, are just oscillating fields.

A sharper change– such as generated by a nuclear explosion - can produce currents that disrupt smaller devices.  In fact, microchips are easily burned out by a few volts in the wrong place

The Earth has a vast natural magnetic field, courtesy of currents inside its core. As long as it is stable it is not noticeable except for turning compass needles. 

But what if something forced it to move? The change would produce currents in long conductors such as power lines or telecoms cables. 

The field is weak, but a shift across miles of cable can induce powerful currents, strong enough to burn out fuses or damage transformers and other electronics.

A sharper push – such as generated by a nuclear explosion - can produce currents that disrupt smaller devices. In fact, microchips are easily burned out by a few volts in the wrong place.

What worries Mr Singer is either naturally occurring geomagnetic storms, caused by the solar wind interacting with the Earth's magnetic field.

He is also worried about deliberately produced electromagnetic pulses (EMPs) by nuclear weapons, or so-called e-weapons, devices that have been developed to disrupt enemy electronics.

If something causes widespread and persistent black-outs and equipment damage the economic damage – and human problems – would be enormous.

Naturally occurring geomagnetic storms, caused by the solar wind interacting with the Earth's magnetic field, could damage the Earth's magnetosphere causing widespread blackouts and travel chaos

Could something like this happen? In 1859 a solar storm, the 'Carrington event', named after an amateur astronomer, caused auroras down to the Caribbean, making telegraph systems across the world fail – pylons threw sparks and operators got electric shocks. 

It is worth noting that telegraphs are simple, sturdy systems compared to today's fine electronics.

In 1989, a solar storm blacked out the power grid in Quebec. Small storms, a recent study shows, can cause noticeable bumps in insurance claims for industrial electrical equipment.

More recently, a near-miss was reported in July 2012, where Earth dodged a plasma cloud ejected by the sun only by a few degrees. Had it hit, the consequences would be dire.

A report from Lloyds emerging risk group has reviewed the evidence. They find that a Carrington-level geomagnetic storm is almost inevitable. There predict there will be one about every 150 years.

This poses a threat to regions dependent on electricity. Such storms could cause outages lasting from two weeks to two years. The main problem is the availability of spare transformers.

When hurricane Sandy hit New York in 2012, the main reason power could not be restored on lower Manhattan – despite the obvious wealth of the place – was that ordering replacement transformers takes months.

Sandy's worst effects were in a single location. In the case of a big storm, replacements would be needed in hundreds of locations at the same time. 

Scientists are worried about deliberately produced electromagnetic pulses (EMPs) by nuclear weapons, or so-called e-weapons. These can cause widespread and persistent black-outs and equipment damage

The cost of a Carrington-like event to the US economy would likely cost up to $2.6 trillion (£1.55 trillion).

A report by the US National Academies was even more pessimistic, guessing at a higher range and a multi-year recovery. 

Besides disrupting electricity such storms can also destroy satellites, disrupt GPS navigation and make other parts of the infrastructure fail.

Singer is probably right to worry about solar storms. Estimates are that there is a 12 per cent risk over the next decade for a storm bad enough. 

Fortunately, we can improve our infrastructure when we recognise there is a problem. We can build more resilient systems, have a few back-up transformers in storage and harden devices. 

This costs money, but it is cheaper than a few weeks without power.

What is probably more worrying is the use of electromagnetic pulses created by weapons.

This is a real threat, which was discovered the hard way in 1962, when a high-altitude Pacific nuclear test caused electrical damage 870 miles (1,400km) away in Hawaii.

In fact, deliberate destruction of enemy power grids using high-altitude detonations soon became part of the strategy of the superpowers. 

In the case of nuclear war there will no doubt be more things to worry about than just the power grid, but it is worth recognising the threat posed to nearby nations. Electromagnetic fields know no boundaries..

Life has existed on the Earth for billions of years, during which there have been many reversals.

There
 is no obvious correlation between animal extinctions and those 
reversals. Likewise, reversal patterns do not have any correlation with 
human development and evolution.

It
 appears that some animals, such as whales and some birds use Earth's 
magnetic field for migration and direction finding.

Since geomagnetic 
reversal takes a number of thousands of years, they could well adapt to 
the changing magnetic environment or develop different methods of 
navigation.

Radiation
 at ground level would increase, however, with some estimates suggesting that overall 
exposure to cosmic radiation would double causing more deaths from 
cancer. ‘But only slightly,’ said Professor Richard Holme.

‘And
 much less than lying on the beach in Florida for a day. So if it 
happened, the protection method would probably be to wear a big floppy 
hat.’

Electric grid 
collapse from severe solar storms is a major risk. As the magnetic field
 continues to weaken, scientists are highlighting the importance off-the
 grid energy systems using renewable energy sources to protect the Earth
 against a black out.

'The very highly charged particles can 
have a deleterious effect on the satellites and astronauts,' added Dr 
Mona Kessel, a Magnetosphere discipline scientist at Nasa.

In one area, there is evidence 
that a flip is already occurring. ‘The increasing strength of the South 
Atlantic anomaly, an area of weak field over Brazil, is already a 
problem,’ said Professor Richard Holme. 

The
 Earth's climate could also change. A recent Danish study has found that
 the earth's weather has been significantly affected by the planet's 
magnetic field.

They 
claimed that fluctuations in the number of cosmic rays hitting the 
atmosphere directly alter the amount of cloud covering the planet.

Henrik
 Svensmark, a weather scientist at the Danish National Space Centre who 
led the team behind the research, believes that the planet is 
experiencing a natural period of low cloud cover due to fewer cosmic 
rays entering the atmosphere.

Electromagnetic pulses from non-nuclear devices are a real possibility, either based on an explosion compressing a magnetic coil or strong microwave fields. They have so far not been used for terrorism – presumably they are not bloody enough – but several countries have researched it.

Do we need to protect ourselves against e-weapons in the future? 

They are not lethal, the principles to build them are well known and it is not hard to imagine some people thinking they have good reasons for disrupting centres of power, finance or data. 

So, yes, defence against them would be a good idea.

That there are back-up copies and that data centres can be hardened might be less helpful than it looks if everybody needs new computers, networks, phones, cars and printers simultaneously – the disruption could be quite profound.

Building more resilient gadgets would be to our advantage.

In the end, an electromagnetic disaster might cost trillions, harm millions of people and weaken society – perhaps on a global scale.

It is a global catastrophic risk worth reducing. But it does not represent an existential risk just yet.

But we are rapidly becoming more dependent on our fragile and vast electrical infrastructure. Some insulation is needed.

This article was written for The Conversation by Dr Anders Sandberg, a James Martin Research Fellow, Future of Humanity Institute and Oxford Martin School at University of Oxford.

@highlight

Claim by Oxford University's Dr Anders Sandberg in The Conversation

@highlight

Solar storms and nuclear weapons can create electromagnetic pulses

@highlight

Geomagnetic storms, for instance, can cause power outages lasting years

@highlight

They destroy satellites, disrupt GPS and make parts of infrastructure fail

@highlight

Just as worrying is use of electromagnetic pulses created by weapons

@highlight

This is a real threat,  discovered the hard way in 1962, when a Pacific nuclear test caused electrical damage 870 miles (1,400km) away in Hawaii 