Famed thrill-seeking surfer Laird Hamilton helped rescue a man who was caught fighting for his life in historically powerful waves off the Malibu coast on Wednesday.

Hamilton, a big-wave chaser known for taking on the world's largest breakers, was at the surf mecca to experience the 20 foot waves kicked up by Hurricane Marie circling miles offshore.

Unfortunately, so was the inexperienced surfer he ended up rescuing after the man lost his board and was swept dangerously close to rocks.

Scroll down for video

Tropical storm Marie, off the west coast of Baja California, brought big surf to southern California beaches on Tuesday and Wednesday. The big wave swell prompted surfers and onlookers to south facing beaches like The Wedge in Newport Beach

Several hundred people gathered to watch body surfers, body boarders and surfers to get the perfect ride on Wednesday for what would be the biggest wave of this late summer swell

Surfers enjoy a second day of 20-25 foot waves at the Wedge, Newport Beach. Big Surf from Hurricane Marie hit Southern California on Wednesday

One surfer battles through the monstrous waves on the southern California beach. At least 60 surfers had to be rescued from the waves which reached up to 30ft

Hero: Famed extreme surfer Laird Hamilton (right) helped rescue a man struggling against dangerously high waves in Malibu on Wednesday

A fellow daredevil assisted Hamilton as he towed the stranded man in.

'Oh, he was happy, he was thankful,' Hamilton told KABC. 'His eyes were big and he was appreciative that he was back on the land.'

Despite the danger, surfers, body-boarders and body-surfers flocked to favorite spots such as the notorious Wedge at Newport Beach, where the interaction of swells and a jetty produced huge waves, and cars were backed up for miles along the only road to the narrow peninsula.

Big crowds watched surfers in the morning, while bodysurfers took on the surf in the afternoon.

Among them was Joshua Magner, 35, who has been surfing since he was 10, and said being in the water in Wednesday's waves was life-altering.

'It's like being born,' he said as he zipped his wetsuit and prepared to go back out. 'You don't know what the outcome will be, but when you do make it through all that pressure is alleviated, it's liberation, truly the feeling of liberation.'

Photo moment: Gerard Butler takes pictures of the massive waves at Surf-rider Beach in Malibu (right) before chatting with some beach friends (left).  The Scottish actor portrayed a surfer Frosty Hesson in the 2012 film Chasing Mavericks

Asked if he was afraid, he replied, 'I was scared leaving my house. Dude, I was scared last night. I couldn't sleep.'

Some gawkers had to park nearly two miles away and walk to the scene. One man rode a skateboard, carrying a baby. A man put a sign on his car offering his parking space for cash and another was selling commemorative T-shirts for $20 apiece.

Scottish actor Gerard Butler, 44, watched the big waves roll in at Surfrider Beach in Malibu.

The star played surfer Frosty Hesson in the 2012 biopic Chasing Mavericks about surfer Jay Moriarity.

Lifeguards up and down the coast sought to keep anyone out of the water who did not have strong experience and were kept busy making rescues all day.

In Malibu, a surfer died a day earlier after being pulled from the water but it was not clear whether the death was related to the surf or a medical condition. There were 60 rescues Wednesday in the area.

Residents of about four blocks of homes along Seal Beach, south of Los Angeles, swept seawater from ground-floor rooms after flooding overnight, and bulldozers reinforced a 6-foot-tall sand berm hastily built to protect shoreline structures.

The berm - a measure normally not needed until winter storms - and the use of pumps prevented more water intrusion during the morning high tide, and another test was expected close to midnight.

An unknown surfer is rescued by Newport Beach lifeguards after wiping out on a giant wave. After several attempts to get him to shore failed the lifeguards swam him out to a waiting boat just outside the lineup

The towering waves and rip currents were being produced by swells generated by Hurricane Marie in the Pacific Ocean about 800 miles west of the southern tip of Mexico's Baja California peninsula.

While Hurricane-generated waves reached California's shores, the storm itself would remain far from the state.

Marie will likely weaken to tropical storm levels, but life-threatening water conditions were expected to continue through Thursday.

Two cargo terminals at the Port of Long Beach stopped operations late Tuesday because surging, 10- to 15-foot-high waves endangered dockworkers.

The powerful surge also tossed heavy rocks from a seawall onto a road, causing damage and closing the roadway.

On Santa Catalina Island south of Los Angeles, a heavy surge Tuesday night sent sand, water and some 3,000-pound rocks into a boatyard, causing substantial damage and tossing some dry-docked boats off their stands, Avalon Harbor Master Brian Bray said.

A surfer separates from his board at the legendary California surf spot The Wedge which was experiencing the biggest waves in decades over the past two days

Huge 20-25 foot waves hit the Balboa pier, Newport Beach. Hurricane Marie has made for wild surfing conditions but has led to some narrow escapes for those more inexperienced

The surge also tore away a floating children's swim platform and closed several docks to incoming traffic.

Along the shoreline in Seal Beach, firefighters went door to door, dropping off more sandbags for residents and surveying damage after the initial surge late Tuesday that topped a 2 1/2 foot beach wall, causing flooding in or around the first row of homes.

About 100 residences were affected, Orange County Fire Authority Capt. Steve Concialdi said.

'This is our worst summer storm, and I've been here 42 years,' said resident Jerry Rootlieb, who was sweeping out his home Wednesday.

Jaime and Blanca Brown's seaside home had a foot of seawater throughout the home, garage and carport.

Soaked floor tiles in the hallway were buckled, and a dirty line marked the high point of water in almost every room and the garage.

Sodden mattresses and carpets were stacked outside.

'What can you do, man? We are just trying to win the war, and we're just bringing out water. Water, water, water,' said the Browns' nephew, Hector Brown.

The Malibu Pier was closed after pilings were knocked loose.

The pier's structural integrity remained sound because of redundancy but people were asked to stay away, State Parks Department official Craig Sap he said.

@highlight

Laird Hamilton plucked the inexperienced surfer out of the chilly Pacific early on Wednesday morning

@highlight

Surfers have swarmed to Southern California beaches where the biggest waves in decades are crashing thanks to Hurricane Marie miles offshore

@highlight

At least 60 people were rescued from the dangerous waters in Malibu as hundreds of people looked on (including surf fan, actor Gerard Butler)