By 
Martha De Lacey

PUBLISHED:

10:37 EST, 15 October 2012


| 

UPDATED:

11:24 EST, 15 October 2012

Feeling sniffly? A bit down in the dumps? Low on energy? If so, you could be suffering from a deficiency from the sunshine vitamin - vitamin D.

New figures have revealed the true extent of what the UK's so-called vitamin D deficiency 'epidemic', with one in nine people classed as 'deficient' and two thirds as 'severely lacking'.

A deficiency in vitamin D, 90 per cent of which is generated by sunlight, can cause depression, migraines, joint pain and low energy levels

Vitamin D is generated by sunlight (90 per cent) and diet (10 per cent).

But the survey by BetterYou found that 77 per cent of adults spend most of their
day indoors in office jobs, seldom seeing the sunshine.

Vitamin D boosts the immune system, and without sufficient intake, the body's cells are not able to react and fight off serious 
infections in the body.

Common medical conditions associated with vitamin D 
deficiency include fatigue, bone pain, muscle pain, joint pain, migraines, skin pigmentation problems and even rickets.

Many people with a vitamin D deficiency develop Seasonal Affective Disorder (SAD) and become depressed.

National Vitamin D Awareness Week, which begins on 28 October, aims to raise public understanding of the dangers of developing the deficiency through lack of sunlight

Over 70 per cent of people questioned in the survey for BetterYou said they spend most of their day indoors, a factor which can contribute to a deficiency in Vitamin D

Almost half of those surveyed also said 
they regularly suffer with low energy levels, and 40 per 
cent experienced regular aches and pains in their bones and joints. Both
are key symptoms of deficiency.

The findings, announced ahead of a National 
Vitamin D Awareness Week, suggest a massive proportion of the UK population are at risk 
of these debilitating symptoms.

Office lifestyles have contributed to the British vitamin D epidemic, with people spending less time in the sunshine than ever before

Of
those diagnosed as severely deficient, 71 per cent do not 
take any form of supplement - highlighting a clear link between 
deficiency and supplementation.

The findings come from a survey 
by health pioneers BetterYou, who are supporting National Vitamin D 
Awareness Week, which aims to raise public understanding of the dangers 
of deficiency.

Andrew Thomas, founder and managing director at 
BetterYou, said: 'Our findings further confirm what we have long 
suspected, that our nation is far more deficient in vitamin D than we 
would care to admit.

'Almost ninety per cent of people 
interviewed provided either classic symptoms of advanced vitamin D 
deficiency or listed multiple lifestyle conditions which would 
predispose them to be deficient.

'These include a combination of having 
darker skin pigmentation, spending daylight hours indoors and excessive 
use of UV sun cream.

'These findings simply reinforce our support
of the UK's first National Vitamin D Awareness Week.

The subject has 
been discussed in the House of Commons, leading to "at risk" groups 
being identified and supplementation recommendations made by our 
Department of Health.

'The awareness week is the natural next step to 
raise understanding with the general public.'

Earlier this year the
Chief Medical Officer for England, Dame Sally Davies announced her 
concerns to health professionals regarding a rise in vitamin D-related 
conditions, asking them to consider vitamin D supplementation for at 
risk groups, including pregnant mothers.

Following this, it was 
announced by Labour MP Kate Green in September, that cases of rickets 
have increased more than 400 per cent since 1996.

National 
Vitamin D Awareness Week runs from Monday 29 October to Sunday 4 
November

@highlight

Vitamin D, dubbed the sunshine vitamin, is generated by sunlight

@highlight

Over 70% of people in the UK spend most of their day indoors

@highlight

Deficiency can cause rickets, migraines, depression and joint pain