By 
Liz Thomas

PUBLISHED:

18:25 EST, 27 September 2012


| 

UPDATED:

05:32 EST, 28 September 2012

He is already the BBC’s highest paid star. Now Jeremy Clarkson is set for a £5million windfall after the Corporation bought out his stake in his production company.

The Top Gear presenter set up Bedder 6 five years ago with the show’s executive producer, Andy Wilman, to exploit the programme’s global brand.

Together the pair owned half the firm, while BBC Worldwide owned the other half. But now Clarkson and Wilman have given the BBC full control.

Scroll down for video

In the money: Jeremy Clarkson, pictured with fellow Top Gear stars (from left) Richard Hammond, The Stig and James May, has sold his production company to the BBC

It is understood the total deal for both men is worth around £8million. The money will come from the BBC’s commercial division. 

The production company set up by Jeremy Clarkson and Top Gear executive Andy Wilman, right, was formed for next to nothing in October 2006 and has now made them millions.

The pair went to the same prestigious private school in Repton, Derbyshire, where they were two years apart, before working together on various TV projects including Top Gear.

Bedder 6 was later bought into by BBC Worldwide in 2007, purchasing half the 10,000 shares and also handing over merchandising and some foreign sales rights to the company.

Its last publicly known financial results were released four years ago, where it made a £1.8million post-tax profit and paid out £700,000 to its shareholders.

And now the BBC has bought Clarkson out - making him £5million.

There is speculation about where the name Bedder 6 comes from, and it is believed it is a pun on 'better sex' - a reference to an in-joke about one of the dormitories at Wilman and Clarkson's former school.

Martin Robinson

Separately, Clarkson is believed to be paid a £500,000 talent fee by the BBC from the licence fee, which will remain fixed if the show continues until 2015.

In addition, Clarkson has signed a new deal with the corporation that will see him present Top Gear for another three years.

Bedder 6 has had huge success making money out of Top Gear merchandise, show tours, DVDs and international sales rights.

A BBC Worldwide spokesman said: ‘BBC Worldwide has agreed new commercial 
deals with Jeremy, James, Richard and Andy to secure Top Gear’s 
international future for another three years.

'This agreement secures the commercial future of Top Gear without using a penny of licence fee money and allows us to continue to grow the brand around the world and return profits to the BBC.’

He caused controversy when it emerged that he earned £3 million in the year to March because of his stake in Bedder 6, as the company made pre-tax profits of £15.2 million and is estimated to be worth more than £50 million.

It has had huge success making money out of merchandise, show tours, DVDs and international exploitation of the show.

But Clarkson and Wilman, who have been 
friends since their schooldays, resigned earlier this month, and BBC 
Worldwide now have total ownership of the company.

Showstopper: It has also been revealed Clarkson has signed up to present Top Gear for the next three years

Publicly the corporation is saying it cannot say how much the pair have paid for their stakes, but insiders say it is below £10 million.

Clarkson will still get a share of Top Gear commercial revenue generated by the show, in return for promoting the show worldwide.

His fellow presenters also signed a three-year deal with BBC Worldwide, suggesting that they will continue to work on the show until 2015, and will also receive money from commercial activities, in addition to the talent fee.

The money will be paid to them directly rather than through a private company.

Clarkson and Wilman’s windfalls because of Top Gear’s success have left many at the BBC uncomfortable as the organisation attempts to make cutbacks.

By Martin Robinson

Top Gear's success has a lot to do with Jeremy Clarkson's efforts as a presenter and writer.

But there have been plenty of problems along the way, and Clarkson has often been at the centre of the controversy.

In November 2008 he decided to make a joke about changing gear in a lorry and how tough a job it is - and linked it to the Suffolk Strangler Stephen Wright - who murdered several sex workers in Ipswich.

Complaining Clarkson said (pictured right and video below): 'Change 
gear, change gear, change gear, check mirror, murder a prostitute, 
change gear, change gear, murder.  That’s a lot of effort in a day.'

In February 2009, Clarkson famously called then-prime minister Gordon Brown a 'one-eyed Scottish idiot'.

A year later he made a joke about a woman in a
burka wearing a red G-string to illustrate dangerous driving conditions, which was branded 'distasteful'.

Spin doctor Alastair Campbell revealed on his blog in the same month that in an un-aired comment Clarkson was asked by him about gay rights and he replied 'I demand the right not to be bummed.'

In other gaffes he compared a Ferrari to a person with special needs, called Mexicans 'lazy', 'feckless' and 'flatulent', said long queues at airport control could be solved by 'a bit of racism' and was caught parking in a disabled driver bay while filming - receiving large numbers of complaints as a result.  

Earlier this year he compared a Japanese car to the Elephant Man and people with 'growths on their faces'.

But probably his most controversial moment came as he appeared on the One Show, where he said that striking public sector workers 'should be shot in front of their families' (video below).

Clarkson
was forced to apologise and the regulator launched an investigation 
after his remark, made on The One Show, sparked around 31,700 
complaints. But he was later cleared.

@highlight

Star sold his portion of Bedder 6 production company to corporation

@highlight

He set it up with Top Gear producer to exploit global brand

@highlight

Meanwhile Clarkson also signs up to three more years presenting the show with colleagues James May and Richard Hammond

@highlight

He will receive £500,000 'talent fee' funded by the British licence-payer