By 
Mark Prigg

PUBLISHED:

14:22 EST, 20 February 2013


| 

UPDATED:

14:28 EST, 20 February 2013

The smallest known planet outside our solar system has been detected by NASA's alien-hunting Kepler space telescope.

It is slightly larger than our Moon and orbits its host star every 13 days.

The planet, named Kepler-37b, has a surface temperature of more than of 400 degrees centigrade, making water, and therefore life, impossible.

An artist's conception for the planet Kepler-37b. This planet is slightly larger than our own Moon and orbits its host star every 13 days. It likely has a surface temperature of in excess of 400 deg C (700 deg F). Owing to its small size and hot surface the planet is very likely rocky with no significant atmosphere, similar to Mercury in our own Solar System.

The newly discovered planets are located in a system called Kepler-37, about 210 light-years from Earth in the constellation Lyra.

The smallest planet, Kepler-37b, is slightly larger than our moon, measuring about one-third the size of Earth.

It is smaller than Mercury, which made its detection a challenge.

Owing to its tiny size and hot surface, it is very likely rocky with no atmosphere, similar to Mercury in our own Solar System.

It orbits the Sun-like star with two other planets, one slightly larger and the other twice as big as Earth.

'Even Kepler can only detect such a tiny world around the brightest stars it observes,' said Jack Lissauer, a planetary scientist at NASA's Ames Research Center.

'The fact we've discovered tiny Kepler-37b suggests such little planets are common, and more planetary wonders await as we continue to gather and analyze additional data.'

Kepler-37b is about 80 percent the size of Mercury and is the first 'exoplanet' to be found that is smaller than any in our own Solar System.

Discoveries of exoplanets - those that lie outside the Solar System - have helped to increase our knowledge of planetary systems and have revealed they can look quite dissimilar to ours.

Until recently, researchers had only been able to detect and probe larger exoplanets, and none had been found that are smaller than those seen in the Solar System.

Astronomer Thomas Barclay, a research scientist at the NASA Ames Research Centre, said: 'Since the discovery of the first exoplanets, it has been known other planetary systems can look quite unlike our own.

'Until fairly recently, we have been able to probe only the upper range of the planet size distribution and, since last year, to detect planets that are the size of Earth or somewhat smaller.

'Hitherto, no planets have been found that are smaller than those we see in the Solar System.

'Here we report a planet significantly smaller than Mercury.

Two of the three planets orbiting Kepler-37 are smaller than the Earth while the third is twice Earth's size. Kepler-37b is about 80% the size of Mercury and is the first exoplanet to be found that is smaller than any planet in our own Solar System.

'This tiny planet is the innermost of three that orbit the Sun-like host star, which we have designated Kepler-37.

'Owing to its extremely small size, similar to that of the moon, and highly irradiated surface, the planet, Kepler-37b, is probably rocky with no atmosphere or water, similar to Mercury.'

He added: 'Although sub-Mercury-sized planets are expected from theory and their space-based detection has previously been predicted, our detection of Kepler-37b is remarkable given this transit signal would be detected in the data of fewer than 0.5% of the stars observed by Kepler.

'Although the detection of one planet cannot be used to determine occurrence rates, it does lend weight to the belief planet occurrence increases exponentially with decreasing planet size.'

The Kepler space observatory, named after the 17th century German astronomer Johannes Kepler, was launched on 7 March 2009 to survey a portion of the Milky Way for Earth-size planets that could harbour life.

In January astronomers used Kepler's data to estimate "at least 17 billion" such exoplanets reside in our galaxy.

The research team used data from NASA's Kepler space telescope, which simultaneously and continuously measures the brightness of more than 150,000 stars every 30 minutes.

When a planet candidate transits, or passes, in front of the star from the spacecraft's vantage point, a percentage of light from the star is blocked.

This causes a dip in the brightness of the starlight that reveals the transiting planet's size relative to its star.

The size of the star must be known in order to measure the planet's size accurately.

To learn more about the properties of the star Kepler-37, scientists examined sound waves generated by the boiling motion beneath the surface of the star.

They probed the interior structure of Kepler-37's star just as geologists use seismic waves generated by earthquakes to probe the interior structure of Earth.

The science is called asteroseismology.

The sound waves travel into the star and bring information back up to the surface.

The waves cause oscillations that Kepler observes as a rapid flickering of the star's brightness.

Like bells in a steeple, small stars ring at high tones while larger stars boom in lower tones.

The barely discernible, high-frequency oscillations in the brightness of small stars are the most difficult to measure.

This is why most objects previously subjected to asteroseismic analysis are larger than the sun.

With the very high precision of the Kepler instrument, astronomers have reached a new milestone.

'The star Kepler-37, with a radius just three-quarters of the sun, now is the smallest bell in the asteroseismology steeple,' Nasa said.

@highlight

The planet, named Kepler-37b, has a 
surface temperature of more than 400 degrees centigrade, making life impossible

@highlight

Discovered by Kepler telescope

@highlight

Is the first 'exoplanet' to be found smaller than any in our own Solar System