By 
Larisa Brown

PUBLISHED:

01:13 EST, 15 July 2013


| 

UPDATED:

01:13 EST, 15 July 2013

Disgraced: Stuart Hall, 83, is facing five new allegations of abuse - including the rape of a girl

Disgraced BBC presenter Stuart Hall is facing five new allegations of abuse - including the rape of a 12-year-old girl, it emerged last night.

The alleged rape is said to have taken place two decades ago after the shamed star met the girl through some relatives.

Police are investigating the allegation along with four other claims concerning sexual assaults.

In May, Hall, 83, admitted sexually abusing 13 girls, including one as young as nine, between 1967 and 1985.

He was jailed last month at Preston Crown Court but to the fury of victims and justice campaigners, he was sentenced to just 15 months’ imprisonment, of which he will serve half – meaning barely two weeks inside for each victim.

The new allegations - involving a rape - could spark a fresh wave of protests concerning his sentence.

A source told the Daily Mirror: ‘The (alleged) victim was the daughter of friends well known to some of his relatives. She’s now in her 30s.’

A Lancashire Police spokesman said: ‘We can confirm we have received further allegations against Mr Hall and we are working closely with the Crown Prosecution Service to determine the most appropriate course of action.

‘We take all allegations of sexual abuse seriously and we would encourage people with any information about sexual abuse or who has been a victim of sexual abuse to come forward and report their concerns confident in the knowledge it will be investigated with sensitivity.’

After sentencing Hall, the Recorder of Preston, Judge Anthony Russell QC, said he had to sentence Hall, of Wilmslow, Cheshire, according to the guidelines in place at the time of the offences.

Behind bars: Hall (left) was jailed last month at Preston Crown Court but to the fury of victims and justice campaigners, he was sentenced to just 15 months' imprisonment, of which he will serve half

But even then the maximum sentence for the most serious offences he committed was five years. Today it would be ten years.

The Government’s most senior law officer, Attorney General Dominic Grieve, was deluged with more than 150 complaints about the sentence.

Mr Grieve, who has the power to send cases to the Court of Appeal if he considers the sentence ‘unduly lenient’, announced last week that the Hall case would be referred.

The case will in due course be heard by three Court of Appeal judges who will decide whether or not the sentence is unduly lenient and whether they should increase the sentence.’

The case is expected to be heard in around six weeks’ time.

When the claims against Hall, 83, first emerged he flatly denied them and protested his innocence.

Senior law officer: Attorney General Dominic Grieve, who has the power to send cases to the Court of Appeal if he considers the sentence 'unduly lenient', announced last week that the Hall case would be referred

After he was first arrested last December, he told police his victims were all lying as part of a ‘vendetta going on against people in the public eye’.

But the publicity generated by his arrest led to more victims coming forward with overwhelming evidence of his guilt.

The court heard his crimes spanned nearly 20 years, between 1967 and 1986, with assaults taking place on BBC premises and at his home. He even abused family friends.

Earlier this month the Mail revealed the former It’s a Knockout presenter was trying to pay off his victims with ‘paltry’ out-of-court settlements.

The multi-millionaire signed over the deeds of his £2million house to his wife just before he was jailed, and is now offering those he abused as little as £2,000 to prevent them claiming compensation.

At least 17 women are suing him over the harm they suffered at his hands.

Susan Harrison, who was 16 when Hall lured her to BBC premises on the false pretext of helping her record a song, before attacking her in his car, has been offered just £5,000 in an out-of-court settlement.

Sorry we are unable to accept comments for legal reasons.

@highlight

Alleged rape by 83-year-old said to have taken place two decades ago

@highlight

Police probe allegation with four other claims concerning sexual assaults

@highlight

In May, Hall admitted sexually abusing 13 girls, including one aged nine