By 
Lee Moran

Last updated at 2:22 AM on 24th September 2011

The date for the eviction at Europe’s largest illegal traveller camp was becoming increasingly uncertain yesterday as legal challenges began to pile up.

Around 400 people on 51 plots at Dale Farm in Crays Hill, Essex, were due to be moved by bailiffs on Monday.

But a last-minute injunction was granted by the High Court in London after supporters of the travellers exploited a loophole involving the removal of structures not mentioned in an earlier court order.

'Brightening up the court': The Battle of Basildon continues at the High Court today, where five sisters wore matching floral tops in a 'show of solidarity'

Day out: Dale Farm residents pictured leaving their site and making their way to the High Court

Hopeful: Dale Farm travellers Serena (left) and Shannon McCarthy await a court ruling on their eviction

Five sisters who live at Dale Farm 
wore identical patterned blouses to show 'solidarity' at yesterday's 
hearing and Mr Justice Edwards-Stuart congratulated them for their 
'lovely turnout'.

The 
Travellers launched a series of extra legal challenges which will 
postpone a decision over an eviction to at least next week.

The travellers won a last-gasp 
injunction on Monday which prevented Basildon Council from clearing the 
UK's largest illegal site.

The authority was told by Mr Justice 
Edwards-Stuart that it had to specify what it wanted to do on each of 
the 51 unauthorised plots - which it has now done.

Travellers had also launched two 
legal actions - relating to questions about whether the council was 
acting in accordance with the terms of enforcement notices issued - and,
secondly, calling for a review of the validity of the notices.

If the council was successful at today's hearing, clearing of the site could have started as early as tomorrow.

But reports from the court at lunch-time suggested a decision would not be made until next week 'at the earliest'.

This is because a judge was told more legal challenges were being launched as he considered whether to extend an injunction preventing the council from clearing the site.

In addition to today's legal action, it emerged that at least two applications for judicial review were planned as part of the campaign to stop the evictions of travellers.

If they go ahead, the applications could add thousands of pounds more to the already huge legal bill generated by the Dale Farm saga.

Five sisters who live at Dale Farm donned identical short-sleeved blouses to show 'solidarity' at today's hearing.

The McCarthy sisters - Joanna, 38, Tina, 40, Margaret, 46, Kathleen, 50, and Marie, 55 - wore blue and pink floral-patterned tops as they sat in the front row of Court 4.

Mr Justice Edwards-Stuart congratulated the 'ladies for their lovely turnout' and added: 'It is very nice to see somebody brightening up the court.'

Day out: Residents, including Kathleen McCarthy (centre), pose for the cameras before setting off to hear their fate at the High Court

Nora Sheridan, who lives on Dale Farm, said before the start of today's hearing: 'We're just keeping our fingers crossed - praying for a good result. We don't know what's going to happen.'

Bailiffs working for Basildon Council had planned to start the clearance of the six-acre site on Monday, but the operation - which is estimated to be costing more than £1 million per day - was postponed while the legal wrangling was resolved.

Council leader Tony Ball said he was frustrated by the delay but added he was convinced the injunction would be overturned once the authority presented the full facts.

The clearance of Dale Farm follows a decade-long row over unauthorised pitches. There are 34 legal pitches on the neighbouring Oak Lane site.

Taking a stand: Travellers' children pose with their message 'We Love School, We Hate Eviction' after writing it on a blackboard at the entrance to Dale Farm settlemen

Plain talking: The children showed what the move will do to them and show banners protesting at the eviction

Travelling: Wearing more sombre attire, these Dale Farm residents were also pictured leaving their site this morning

Confident: Dale Farm residents flash the 'Victory' sign as they prepare to leave for the High Court

Members of the International Expert Group Meeting on Forced Evictions, meeting at the UN Human Settlements Programme in headquarters in Nairobi, has written to the traveller community of Dale Farm expressing sympathy, it emerged last night.

The letter was signed by more than 30 representatives from different countries.

It said: 'Repressive policies targeting Gypsies and Travellers disguised as planning regulations are discriminatory, whilst inclusive national strategies that are in line with human rights standards generate real progress in addressing issues of exclusion and marginalisation.'

Back at Dale Farm a resident waiting for the court ruling adjusts the aerial on a television

Anxious: Others sit, awaiting any news from London, pouring cups of tea

Lock down: Activists were this morning shutting the barricade of the main gate to Dale Farm

Some travellers had left the site last week in 
anticipation of the clearance but have returned this week in the hope 
they will be allowed to remain.

They upped sticks and set an illegal camp 55 miles away, leading residents to fear that many more were on their way.

Around 20 families moved from Essex to Stockwood Park, close to Luton in Bedfordshire, after gaining access to a 100-hectare piece of land.

Unlikely friendship: The former bare-knuckle boxer Paddy Doherty, who has struck up a bond with Sally Bercow, wife of the Speaker of the House of Commons, is backing the travellers of Dale Farm

Basildon Council has suggested a variety of temporary flats and houses 
over the past six months in an effort to resolve the decade-long 
stand-off.

But they were turned down for reasons
including because they smelled of smoke or were made of bricks and 
mortar, 'contravening' the travellers' desire to spend their life on the
road.

Fifty-one plots containing homes 
built without planning permission are set to be cleared from the 
six-acre site, along with their remaining residents, in an operation 
which could cost £18million

Danger: A sign of the barricade at Dale Farm warning that the 18-year-old girl attached by her neck will be killed if bailiffs open the gate

Dangerous protest: An 18-year-old known only as Emma, right, is attached to a scaffolding pole with a bike lock around her neck. She and fellow protester Dean, left, are also handcuffed together inside the barrel

@highlight

Decision today is 'unlikely' and will probably be made on Monday

@highlight

Injunction stopping clearing of site 'likely' to be extended

@highlight

Travellers launching 'even more' legal challenges

@highlight

Legal bill to increase 'substantially'

@highlight

Residents pictured making their way to High Court

@highlight

Judge compliments travellers wearing matching tops for their 'lovely turnout'

@highlight

Basildon Council may start site clearance today if successful