By
Rebecca Camber

PUBLISHED:
  
  
      12:20 EST, 15 January 2014
    
  
 | 
  UPDATED:
  
  
      03:36 EST, 16 January 2014

A drugs baron running a £1million a year cannabis empire boasted yesterday of peddling drugs to  primary school children.

Hiding behind a gas mask, the criminal showed a TV crew inside one of his three cannabis farms, which produce more than 1,000 plants a year.

Speaking anonymously, the masked man in his twenties boasted that he pocketed £250,000 every three months from his illegal crop.

Scroll down for video

Shameless: The TV report of the masked drugs baron, who yesterday boasted about his many 'customers'

Boastful: Hiding behind a gas mask, the criminal bragged that he had peddled drugs to  primary school children

Factory floor: The man boasted that he pocketed £250,000 every three months from his illegal crop

He took Sky News on a tour of a secret
 cannabis bunker in south London accessed through a hidden hatch in the 
floor of a shipping container.

The
 gangster also showed them around another house with boarded-up windows 
where the floor was littered with plants in plastic bags lying beside 
fertiliser and other equipment bought from garden centres.

In
 an echo of the hit TV series Breaking Bad – in which a high school 
chemistry teacher manufactures crystal meth in a hidden laboratory – 
the footage shows one of the dealer’s 30 staff tending to the plants, a 
bandana over his face, wearing a T-shirt and shorts in the heat 
generated by the powerful hydroponic lamps overhead.

Tour: He took Sky News on a tour of a secret cannabis bunker in south London accessed through a hidden hatch in the floor of a shipping container

Showing off: The gangster also showed them around another house with boarded-up windows where the floor was littered with plants in plastic bags lying beside fertiliser and other equipment bought from garden centres

Export: He claimed he exported a type of cannabis which he called 'English Cheese' to the Netherlands, Germany and Austria

Sophisticated: Dozens of plants are stacked up at the cannabis factory as well as equipment for the operation

The
 drugs baron, who could face up to 14 years in jail if caught, showed 
reporters how the cannabis is packed into £250 bags and sold 24 hours a 
day to customers.

He was 
later filmed in a cramped bedroom in a third property claiming the drugs
 trade in Britain is ‘the biggest it has ever  been’ despite continued 
police efforts to stamp it out.

Shamelessly,
 he bragged that dealers  connected to his organisation are peddling his
 drugs to children in London as young as ten.

He
 said of his customers: ‘You’ve got doctors, police, solicitors, 
teachers, bus drivers – everyone does it. Young kids, school kids, even 
primary school kids.’

Boss: The man said he employed 30 workers and that his firm had three cannabis factories

Sparking debate: Miley Cyrus controversially appeared to light up a joint of cannabis during her performance at the MTV Europe Music Awards in Amsterdam last November

He 
shrugged off any responsibility for children getting hooked on the drug,
 instead blaming pop stars such as Miley Cyrus for glamorising cannabis 
after the singer recently appeared to light up a joint at the European 
MTV awards in Amsterdam.

He
 said: ‘I blame it on the TV, the media, rap, YouTube, like Miley Cyrus 
on TV it is a common thing – they see it as the cool thing to do.

‘Instead of binge-drinking they’ll go and have a smoke.’

He
 bragged that his gang export the Class B drug to the Netherlands, 
Germany and Austria, and called for it to be legalised ‘so we don’t have
 to hide what we are doing’.

Fighting crime: Met Police Commander Steve Rodhouse disputed that cannabis should be made legal, saying that it fuels crime, violence and anti-social behaviour

Officers
 carried out 17 raids an hour across Britain last year, swooping on more
 than 100,000 growers, ranging from small suppliers who have converted 
their lofts and garages to huge marijuana factories.

Metropolitan Police
 Commander Steve Rodhouse yesterday said he was concerned by the claims 
that primary schoolchildren were being plied with the drug.

‘We are not 
hearing that is a common picture,’ he added. ‘Where we do hear about it,
 we tackle it.’

Illegal: Cannabis is currently categorised as a class B drug under the Misuse of Drugs Act 1971

Cannabis is currently categorised as a class B drug under the Misuse of Drugs Act 1971 and is listed in Schedule 1 to the Misuse of Drugs Regulations 2001.

It was upgraded from a Class C to a Class B drug in 2009 due to fears over its effect on mental health, and that stronger varieties of the drug were becoming more readily available.

Many campaigners for the legalisation of cannabis say that doing so would cut out the criminal gangs which supply the drug.

They also say that if legal it could be regulated, making it easier to stop children getting hold of the drug and prevent it from being cut with other harmful substances.

Pro-cannabis campaigners also say that the drug is not as dangerous as legal substances tobacco and alcohol.

Some research has also suggested the the THC compound in cannabis can be beneficial for conditions including chronic pain, Multiple Sclerosis, and reducing nausea in those undergoing chemotherapy or living with AIDS.

However, scientists say there are links between cannabis use and mental health problems, including short-term effects such as anxiety and paranoia, as well as contributing to a relapse in pre-existing conditions such as schizophrenia.

NHS guidelines also say that it can lead to dependency problems and lung damage due to chemicals in the drug.

Cannabis also affects co-ordination, increases the heart rate and can affect blood pressure.

@highlight

Drugs boss says he has three cannabis factories and employs 30 people

@highlight

He claims his dealers are selling the class B drug to young children

@highlight

Showed TV crew inside farms, which produce 1,000 plants a year

@highlight

Blames music and TV, including Miley Cyrus for boom in drugs trade

@highlight

Singer appeared to light a cannabis joint during MTV awards in Amsterdam

@highlight

London: 1m cannabis plants worth £2m seized by police in two years