Scientists from the University of Western Australia may found evidence that plants can 'talk' each other using microscopic sounds.

A study looking into how chilli plants grow has discovered that when seedlings are put next to so-called 'friendly' plants, they grow stronger.

Yet, when the seedlings were put near 'bad neighbours', such as fennel, germination was hindered.

Dr. Monica Gagliano and her research team at the University of Western Australia studied how chilli plant seedlings reacted when placed near other plants, such as basil and fennel. Basil encouraged the seeds to grow, whereas fennel hindered development. Scientists believe this could be due to microscopic sounds

The research team put one lot of chilli seeds in a locked container with basil, and then fennel. Another lot were left to grow outside. In both cases, the chilli seeds sprouted and grew when the basil neighbour was present, and were hindered by the presence of fennel. This suggests that the development differences had little to do with the growing environment, and more to do with how the plants interact with one another

The experiment was set up to block 
all possible known means of communication between plants, including 
chemical and light signals, and physical contact.

Chilli seeds were 
planted in isolated dishes around an adult basil plant that was either 
left open to the elements, or sealed in a cylindrical box covered in 
black plastic.

The cylinder blocked all airborne 
chemical signals, and all wavelengths of light.

As a comparison, other 
seeds were planted around a cylinder that was left empty.

More of the chilli seeds sprouted and 
grew when the basil neighbour was present, whether or not the plant was 
masked and cut off from them.

Sounds generated by microscopic movements within plant cells might be the key to the mystery, the scientists suspect.

The team, lead by researcher Dr Monica Gagliano, found that sprouting chilli plants grow more successfully next to 'friendly' neighbour, which in the chilli plant's case was an adult basil plant.

Yet place them next  a neighbour from hell, such as fennel, and germination is held back. 

The study even discovered that the plants recognise what kind of plant lives next door when they are still seeds.

Gagliano said: 'Our results show that plants are able to positively influence the growth of seeds by some as yet unknown mechanism.

'Bad neighbours, such as fennel, prevent chilli seed germination in the same way.

'We believe that the answer may involve acoustic signals generated using nanomechanical oscillations from inside the cell which allow rapid communication between nearby plants.'

Fennel is a bad plant neighbour because it competes aggressively, releasing chemicals that stunt the growth of its rivals.

Basil, on the other hand, produces helpful chemicals that keep out weeds and act as natural insect pest killers.

When the basil plant, pictured left, was near the chilli plant the seeds grew stronger because basil produces helpful chemicals that keep weeds out. Alternatively, fennel, pictured right, competes 'aggressively' and releases chemicals that stunt growth, which hindered the chilli plants development

'Interestingly, this was true even when all known signals from the basil were blocked, indicating that the facilitative interaction observed between these two species is mediated through a signalling modality other than those studied thus far.

'Most importantly, the fact that germination of chilli seeds did not differ between the masked and open treatment indicates that light, touch or chemical signals may be important but clearly not necessary for chilli seeds and basil plants to sense each other's presence.'

They added: 'The observed differences in germination between treatments were relatively small but even small differences in germination are likely to have significant effects on competitiveness and thus on fitness.'

Previous research by Dr Gagliano showed 
that, even when protected against fennel's chemical chilli seeds are 
reluctant to germinate when placed near the plant.

The new findings have been published in the online journal BMC Ecology.

@highlight

Australian scientists have found that plants talk to each other using microscopic sounds

@highlight

How well crops grow can depend on which other plants are nearby

@highlight

Fennel is 'aggressive', while basil acts as a natural pesticide