The Republican congressman tapped to deliver a Spanish-language version of his party's State of the Union rebuttal Tuesday night added in a little extra salsa, and it's causing the GOP some Wednesday morning heartburn.

Florida Rep. Carlos Curbelo's speech was billed as a 'Spanish-Language translated address' offered alongside the higher-profile English delivery of Iowa Sen. Joni Ernst. But he inserted lines about immigration and the White House's new Cuba policy days beforehand.

Speaking in Spanish, Curbelo said Republicans should 'work through the appropriate channels to create permanent solutions for our immigration system, to secure our borders, modernize legal immigration, and strengthen our economy.'

'In the past, the president has expressed support for ideas like these,' he said. 'Now we ask him to cooperate with us to get it done.'

Ernst didn't mention the contentious topic at all.

Florida GOP Rep. Carlos Curbelo gave a Spanish-language State of the Union response address on Tuesday night that didn't match the English version in several key respects – adding lines about Cuba and immigration

Iowa Republican Sen. Joni Ernst never mentioned President Obama's revamped Cuba policy, and didn't advocate for changes in US immigration policy, but both items made it into the Spanish 'translation'

Curbelo raised hackles in the Republican caucus after his election in November by suggesting that if President Barack Obama were to move unilaterally to mainstream millions of illegal immigrants, it might be perfectly legal.

'Yeah, it can be (legal),' he told The Hill newspaper in November, before Obama outlined his ambitious proposal to guarantee 5 million or more people living in the U.S. illegally that they won't be deported while he's in office.

Curbelo added that Obama should keep his powder dry and give the new Congress a chance to act.

But he has already voted against legislation to undo Obama's executive actions, indicating that he favors giving many illegal immigrants residency paperwork and work permits.

The 34-year-old Floridian also mentioned Cuba on Tuesday night, torching the Obama administration for pledging to reestablish diplomatic ties there and open an embassy in Havana.

Curbelo called it 'essential that the United States supports its allies and holds its enemies accountable.'

'We are disturbed by the administration's undeserved concessions to the regimes Iran and Cuba,' he said in his speech. 'Both countries are ruled by cruel dictatorships that decades have tried to harm our country and our allies.'

REALPOLITIK: Cuban and US delegations are meeting on Wednesday in Havana to take part in negotiations to restore diplomatic ties between the two countries and eventually normalize relations

Curbelo, 34, has already broken with his party on immigration and opposed a measure  blocking President Obama's executive 'amnesty' for millions of illegal immigrants

Ernst's only mention of the Islamic regime was a soft pledge to 'work to confront Iran's nuclear ambitions.' But she never brought up Cuba. 

Curbelo is Cuban-American, so his audience would likely have been surprised if he omitted talk of the island nation just 90 miles from Florida.

Obama, in fact, gave his rebooted Cuba policy two paragraphs – including four applause lines – in an already crowded State of the Union speech.

'We are ending a policy that was long past its expiration date,' he said. 'When what you're doing doesn't work for 50 years, it's time to try something new.'

'And our shift in Cuba policy has the potential to end a legacy of mistrust in our hemisphere. It removes a phony excuse for restrictions in Cuba. It stands up for democratic values, and extends the hand of friendship to the Cuban people. And this year, Congress should begin the work of ending the embargo.' 

Most Republicans and a sizable contingent of Democrats have approached the president's policy shift with suspicion, even as formal negotiations got underway on Wednesday between Cuban and American diplomats. 

Cuban dictator Raul Castro and his ailing brother Fidel are still Public Enemies No. 1 and No. 2 among Cuban emigres living in the United States. And Curbelo was talking directly to them.

House Speaker John Boehner's press secretary, Michael Steel, told DailyMail.com that any controversy generated by the two different speeches is much ado about nothing.

'As in previous years' State of the Union responses, Senator Ernst and Congressman Curbelo spoke of the GOP vision of commonsense solutions and greater opportunity for everyone in this country – framed by their unique stories and experiences,' Steel said.

Cuban dissident Jorge Luis Garcia Perez, known by the nickname 'Antunez,' was among pro-democracy activists invited to the State of the Union address by House Speaker John Boehner and other Republicans

BACK TO WORK: Ernst took her seat in the Senate Armed Services Committee hearing room on Wednesday less than 12 hours after her star turn as the GOP's official Obama-debater

Republican National Committee Chairman Reince Priebus shrugged it off during a Wednesday morning interview on MSNBC.

'I don't think it's that strange to have multiple people giving multiple responses,' he said of the mixed signals.

Curbelo himself told Politico that Democrats shouldn't gleefully 'criticize us for each of us having our own priorities and ideas and making them known.' 

He claimed the Republican leadership was aware of changes he had made and approved.'

'I did not get any pushback whatsoever,' Curbelo said.

He told The Miami Herald that party higher-ups 'had no problems. I don't want people to think there was a fight. There wasn't.'

However, he said, he didn't add in personal beliefs of his that might be too contentious for many Republicans.

The speaker's office doesn't seem concerned that Ernst didn't address Republicans' conflict with the president over his Cuba policy.

Boehner's guests at the Capitol on Tuesday night included two leaders of Cuba's resistance movement. 

Jorge Luis García Pérez spent 17 years as a political prisoner for publicly denouncing Fidel Castro's regime. (He was released in 2007.) His wife, Yris Tamara Pérez Aguilera, founded the Rosa Parks Feminine Civic Rights Movement to help homeless women and children in Cuba.

Obama, on the other hand, brought freed Cuban prison Alan Gross as a token of his own negotiating success. 

Florida Republican Sen. Marco Rubio also brought Cuban dissidents to the speech, as did Reps. Ileana Ros-Lehtinen and Mario Diaz-Balart.

@highlight

Sen. Joni Ernst delivered the Republicans' official response to President Barack Obama's State of the Union speech Tuesday night

@highlight

Rep. Carlos Curbelo was tapped to give a parallel version in Spanish, but decided on his own to insert lines about immigration and Cuba policies

@highlight

He blasted 'the administration's undeserved concessions' to Cuba and Iran, 'cruel dictatorships that decades have tried to harm our country'

@highlight

Also said Republicans should 'work through the appropriate channels to create permanent solutions for our immigration system'

@highlight

Curbelo insists the party leadership never objected

@highlight

But the GOP had promised a 'translated address,' not a separate speech for Spanish-speaking audiences