By
Richard Spillett

Wayne Ronayne has resigned as Mayor of Gosport after he was barred from the town's pubs over a row

A mayor has been forced to step down after he was banned from all his town's pubs following a alcohol-fuelled row on his first day in the job.

Wayne Ronayne quit as Mayor of Gosport, Hampshire after he and partner Paula Carter, both 54, were barred from every local pub.

It comes after he and Ms Carter were caught up in a row in a bar just hours after he took office, when the mayoress allegedly threatened to get a Wetherspoon's pub 'shut down'.

He announced his resignation just 40 days into the job, after being barred from the town's 36 pubs, bars and taverns.

Ronayne is believed to be the first mayor in the town's history to leave the civic position before his year-long term was up. 

He denies any wrongdoing and blames social media for his damaged public profile.

Ronayne said: 'My decision is not based on any admission of wrongdoing or my inability to undertake the role.

'It is based on the now-damaging public perception of me that has been vigorously generated by certain members of our community.

'I do not wish to bring the position of the mayoralty into disrepute nor tarnish the good reputation of Gosport.' 

Tory councillor Ronayne was given a six-month ban by local organisation Pub Watch, and his partner, Ms Carter, was barred for 12 months after police were called to a pub on June 4.

Speaking at the time, Stephen Brown, duty manager of the town's Nelson's pub, said: 'Ms Carter said to me "do you know who I am?", I said "no, I don't" and she said "I'm the mayoress of Gosport I can have you closed down".'

Ronayne and mayoress Paula Carter were asked to leave The Star pub before he was banned from other bars

Ronayne, pictured celebrating his election with Tory colleagues, has denied any wrongdoing over the row

The pub manager added: 'I politely said she still wouldn't be coming in, she was clearly drunk and then continued to be rude and had to be dragged away by one of the other members.'

Gosport Pub Watch defended their action to bar the former Royal Navy warrant officer.

Chairman Phil Cox said: 'Everybody is treated the same. People need to be treating licensees and staff with respect.

'But we don't expect the mayor of Gosport, who represents our town, to be involved in incidents like this.'

Ronayne will remain as a councillor on the town council.

Lib Dem rival councillor Peter Chegwyn said: 'He's done the right thing and the public will recognise that. But he should have done this a month ago.'

After continuing in the post for 40  days, he says he is resigning so as not to bring the 'mayoralty into disrepute'

 

@highlight

Mayor and mayoress involved in argument shortly after he was installed

@highlight

He denies any wrongdoing but pub say mayoress was 'drunk and rude'

@highlight

Official was barred from all 36 pubs in the town after the incident

@highlight

Despite protesting his innocence, he has now stepped down from role

@highlight

He says he did not want to 'tarnish the good reputation of Gosport'