By 
Ben Spencer

PUBLISHED:

19:28 EST, 14 June 2013


| 

UPDATED:

04:35 EST, 17 June 2013

Prince Charles bought a 396,000 sq ft warehouse complex in a vast supermarket depot near Milton Keynes

Prince Charles famously abhors modern architecure - especially the boxy ‘monstrous carbuncle’ buildings that he believes have  blighted the face of Britain.

But his strong views have not stopped the heir to the throne investing £38million in a vast supermarket depot near Milton Keynes, it emerged last night.

The Prince bought the sprawling 396,000 sq ft warehouse complex from an Anglo-Indian property fund, one of the single largest acquisitions by his Duchy of Cornwall estate.

The deal was competed 18 months ago but has only emerged now.

Like other significant deals, the purchase of the warehouse in November 2011 from Indian property fund Meghraj Properties had to be approved by the Lord Commissioners of the Treasury.

The depot is currently leased to Waitrose, who use it as a lorry distribution hub.

Prince Charles sent shock waves through the architecture world in 1984 when he used a speech to the 150th anniversary of the Royal Institute of British Architects to lambast modern design, describing a towering extension to the National Gallery as a ‘monstrous carbuncle on the face of a much-loved and elegant friend’.

His views have changed little since then.

In 2009 he opposed a £1billion housing scheme at the former Chelsea Barracks in London.

In the same year, he said: ‘I don’t go around criticising other people’s private artworks. I may not like some of them very much, but it is their business what they choose to put in their houses. 

‘However, as I have said before, architecture and the built environment affect us all.’

Land Registry records list the distribution centre Brinklow in the name of the Duchy of Cornwall and the Prince’s full titles - ‘His Royal Highness Charles Philip Arthur George, Prince of Wales, Duke of Cornwall and Rothesay, Earl of Chester and Carrick, Baron of Renfrew, Lord of the Isles and Great Steward of Scotland’.

The Prince called the Salisbury sing of the National Gallery a 'monstrous carbuncle' in a controversial speech

The sale price was £38,385,500.

The Duchy’s full holdings are worth £693million and include Dartmoor Prison, the Oval cricket ground in central London, a Holiday Inn in Reading, the Prince’s private homes such as Highgrove and land in the Scilly Isles.

Between 2009 and the end of 2012 the Duchy conducted property transactions worth at least £102million, the Independent reported last night.

The management of the Duchy - including investment decisions on commercial - is carried out by a professional managerial team. 

But Prince Charles is known to take a close personal interest in the running of the estate. 

He voluntarily pays income tax on the income he receives from the Duchy - including £4.5million last year from income of £18.3million.

The Prince of Wales has also criticised the redevelopment of the Chelsea Barracks

Last night a Duchy of Cornwall spokeswoman said the Milton Keynes property was acquired as ‘a commercial property investment.’

She added: ‘The Duchy of Cornwall is a private estate not a public body and is not funded by the taxpayer. 

‘The Prince of Wales chooses to use his private money from the estate to pay for his public duties, as well as those of The Duchess of Cornwall, The Duke and Duchess of Cambridge and Prince Harry. ‘He also chooses to pay income tax on the income generated by The Duchy.

‘The Duke of Cornwall manages the estate for present and future Dukes, and for the wider benefit of tenants, communities and the environment.’

@highlight

Prince Charles spent £38million in a supermarket depot near Milton Keynes

@highlight

The deal was competed 18 months ago but has only emerged now

@highlight

Depot is currently leased to Waitrose, who use it as a lorry distribution hub

@highlight

He once described the National Gallery Extension as a 'monstrous carbuncle'