Blue light-emitting diodes (LEDs) have been receiving positive attention after its inventors were awarded the Nobel Prize in physics last week.

They use around 90 per cent less energy than incandescent bulbs and last for 100,000 hours compared with  1,000 hours for tungsten filament light bulbs.

But while they may be good for the environment, a new study claims that the discovery may a problem for insects, which are more strongly attracted to the LED spectrum of light.

Scroll down for video 

While blue LEDs may be good for the environment, a new study claims that the discovery may a problem for insects, which are more strongly attracted to the LED spectrum of light

The research, by New Zealand-based institute Scion, found traps placed near LEDs captured 48 per cent more insects than traps near sodium-vapour lights.

Sodium vapour bulbs, which emit yellow light, are commonly used in street lighting as they are more efficient than pre-LED lights.

Insects are attracted to both white and yellow light, but it seems they are even more attracted to blue light which is generated by LED bulbs.

Overall, the researchers caught and labelled more than 20,000 insects, with moths and flies  the most common group of bugs.

They claim the attraction can be fatal, causing flies to be thrown off their usual path and into the jaws of predators, disrupting the food chain.

Three Japanese-born scientists have won the Nobel Prize in physics for inventing blue-light emitting diodes (LEDs) that have revolutionised the lighting industry.

Isamu Akasaki and Hiroshi Amano of Japan and U.S. scientist Shuji Nakamura won the award for their 1990s invention, which has led to the use of environmentally-friendly light sources worldwide.

But when Nakamura invented the technology in 1993, the company he worked for at the time awarded him the equivalent of just £125 ($200) - despite the idea being worth a potential £50 billion ($80 billion) by 2020 according to estimates.

Shuji Nakamura invented the blue light-emitting-diode while working for the Nichia Corporation in Tokushima, Japan in 1993.

But when he first came up with Nichia rewarded him with just 20,000 yen (£125 or $200), as Japanese firms favoured the mentality that work for an employer was not a means for personal glory.

However Nakamura quit and moved to the US in 2000, before counter-suing in 2001 after Nichia attempted to sue him for infringing trade secrets.

He was ultimately awarded £5.04 million ($8.1 million) for the idea, reported as the largest payout ever made to an employee for an invention. 

Shuji Nakamura (left), Isamu Akasaki (centre) and Hiroshi Amano (right), all born in Japan, have won the 2014  Nobel Physics Prize, for their  environmentally-friendly blue LEDs. The lighting breakthrough creates more energy-efficient home lighting, and can improve keyhole surgery techniques

Another concern is that LED lights near ports could attract flying pests, such as the gypsy moth, that are accidentally transported by ships.

'The behavior of many animals is influenced by light in the blue portion of the spectrum. For example, insects have specific photoreceptors for blue light,' Stephen Pawson, an entomologist at the New Zealand research institute Scion, told Smithsonian.

'Thus large-scale adoption of 'white' lighting is likely to increase the impacts of nighttime lighting on all species sensitive to 'blue' light.

The tests showed that simply changing the spectrum of LEDs did not reduce their attractiveness to insects.

The use of LED lighting is set to increase. Estimates suggest the technology, used in everything from homes to billboards today, will be worth £50 billion ($80 billion) in 2020.

The research, by New Zealand-based institute Scion, found traps placed near LEDs captured 48 per cent more insects than traps near sodium-vapour lights

A major concern is that LED lights near ports could attract flying pests, such as the gypsy moth (pictured), that are accidentally transported by ships

@highlight

LED bulbs use around 90 per cent less energy than incandescent lights

@highlight

But insects are more strongly attracted to the LED spectrum of light 

@highlight

Scientists caught and labelled around 20,000 insects attracted to LEDs

@highlight

The attraction can be fatal, causing more flies to be eaten by predators

@highlight

Scientists say this can disrupt food chains and damage local ecosystems

@highlight

Another concern is that LED lights near ports could attract flying pests, such as the gypsy moth, that are accidentally transported by ships 