The first full-scale tidal generator in Wales has been unveiled in an attempt to reduce the UK's carbon emissions.

The device, an underwater turbine mounted on a free-standing base, will be installed in Ramsey Sound, Pembrokeshire.

Its backers say it will be among the world's first demonstration devices connected to the grid to generate green, renewable and predictable tidal power.

Scroll down for video 

The first full-scale tidal generator in Wales, which could produce power for 10,000 homes, has been unveiled

Enery generated by the 400kW demonstration device, which will be installed within weeks, will be used to power 100 nearby homes.

After a 12-month testing period, up to nine tidal devices will be installed off St Davids Head in Pembrokeshire to form a 10 megawatt array.

The DeltaStream device, developed by Tidal Energy (TEL) weighs 150 tonnes, and has a 52ft by 66ft (16 metre by 20 metre) frame.

Cardiff-based Tidal Energy claims its tidal generator is at the cutting edge of green technology, with three separate horizontal axis turbines mounted on a common triangular frame.

Cardiff-based
 Tidal Energy claims its tidal generator is at the cutting edge of green
 technology, with three separate horizontal axis turbines mounted on a 
common triangular frame. Each turbine has a 49ft (15 metre) diameter 
rotor which is connected to a generator to produce electricity both the 
ebb and flood tides

The DeltaStream device developed by tidal stream technology company Tidal Energy will be among the world's first demonstration devices connected to the grid to generate green, renewable and predictable tidal power

Each turbine has a 49ft (15 metre) diameter rotor which is connected to a generator to produce electricity both the ebb and flood tides.

It does not require expensive drilling into the seabed, the company claims, and has features to minimise impacts on the environment.

'The imminent launch of DeltaStream, and the supply chain that now exists as a consequence of its development, marks the birth of the tidal industry in Wales,' said Tidal Energy's managing director Martin Murphy.

'We remain committed to leading the expansion of the industry and to the creation of green jobs by building on the wealth of expertise present in the UK and the country's plentiful resources.'

The  DeltaStream tidal turbine will be installed in Ramsey Sound in Pembrokeshire on the Welsh coast

Strong tides and crashing waves can produce huge amounts of energy – and the UK, with its long coastlines, is in an ideal position to harness this power.

Tidal Energy received £8 million funding for the project from the European Regional Development Fund, and match-funded by majority shareholder Welsh renewables company Eco2, which will join forces with TEL to install the further devices.

Renewable Energy Association chief executive Dr Nina Skorupska said: 'Many of our ocean energy members are currently racing to deploy the first wave or tidal farm, with several of these types of devices instead of just one.

'When that happens the sector will move into mass production, costs will fall dramatically, and wave and tidal will be well on their way to becoming major players in the UK energy system.'

Overall, the marine energy industry has been forecast to be worth £6.1 billion ($10.3 billion) to the UK economy by 2035, creating nearly 20,000 jobs. 

In February, plans were submitted to develop the world's first tidal lagoon energy project in the UK.

The project could provide renewable power for 120,000 homes in Swansea, Wales for 120 years.

Developers behind the  Swansea Bay project believe it could be the first step in developing lagoon technology that could meet 10 per cent of the UK's electricity needs from the tide.

The scheme would involve a six-mile (9.5km) wall built around Swansea Bay, which would create a lagoon in the Severn Estuary with turbines that could harness the incoming and outgoing tides to generate power 14 hours a day.

If it gets the go-ahead, the lagoon could be the first of a series of five developments around the UK, coast which could generate as much as 10 per cent of the UK's electricity by 2023.

Tidal Lagoon Power, the company behind the project, said it hopes that 65 per cent of expenditure will be in the UK, boosting a home grown supply chain and creating a possible future export market.

@highlight

The first device will be installed in Ramsey Sound, Pembrokeshire

@highlight

It is among the world's first tidal power devices connected to the grid

@highlight

After a year of testing, up to nine tidal devices will be installed off St Davids Head in Pembrokeshire to form a 10 megawatt array