Thierry Henry has urged England's rising stars to make the most of their time with Wayne Rooney before he calls it a day.

Henry has hailed Rooney as one of the greats of the game with the 29-year-old England captain just two goals from equalling Sir Bobby Charlton's record of 49 goals for his country.

And the former Arsenal and Barcelona striker insists that young players like Harry Kane and Raheem Sterling must not waste their training sessions alongside Rooney.

Thierry Henry (right) and Wayne Rooney pictured alongside each other during a Premier League match in 2002

Wayne Rooney celebrates his 47th goal for England against Lithuania on Friday night

Henry wrote in The Sun: 'You will only truly appreciate Rooney when he has retired. It's a shame but it's always like hat.

'I would absolutely urge all those youngsters in the squad, such as Raheem Sterling and Harry Kane, to watch and learn off Rooney from this day onwards.

'They are extremely lucky to be on the same training pitch as this guy and they must make the most of it. It will be a real waste if they do not.

'They must try to copy him. In terms of his dedication and the way he plays. I would also say this to the young lads at Manchester United.

Rooney heads in the opening goal past Lithuania goalkeeper Giedrius Arlauskis at Wembley

Rooney heads the ball past Arlauskis to give England the lead in Friday's Euro 2016 qualifier

'To play well for six months or a season in football is nothing. To do so for over a decade like Rooney is extraordinary. I know what it takes and it isn't easy.

'Trust me, people talk about him outside of this country. In Spain and France, he is appreciated as a top, top player.'

Meanwhile, Rooney has admitted that the excitement generated by Kane, who scored just 79 seconds after coming on as a substitute in the 4-0 win over Lithuania, reminds him of his early games for England at the age of 17.

Rooney was a teenage sensation for England twelve years ago and caused even more of a stir when he starred in England’s 2-0 win over Turkey in 2003.

Rooney said: ‘There was one stage in the game, after his [Kane's] goal, where he ran down the left and took a few players on which reminded me of that.

Tottenham striker Harry Kane celebrates scoring his first goal for England on his debut  

Kane (left) headed in England's fourth against Lithuania shortly after replacing England captain Rooney

Wayne Rooney (right) praised Harry Kane's immediate impact for England against Lithuania 

‘But he will tell you himself he still has a lot to learn but at the minute he is scoring goals left right and centre and it is great for us as a nation to have that excitement around us.

‘It's incredible really. You can feel the excitement around the country. You could tell when he came on everyone wanted him to come on and even he himself didn't think he'd score so quick, but we are all delighted for him.

'He's an exciting player. When you speak to him you can see he is a level headed guy and I am sure he has good people around him so will be able to cope with it.

Rooney starred on his England debut against Turkey in 2003, at the age of 17

Rooney (centre) said Kane's debut reminded him of his early games for his country

‘There are things I could say to advise him but I think there are things you have to learn on your own, which I am sure he will do in the next year or two.

'He is obviously a little bit older than I was and a bit wiser as I was 16 or 17 when I came in. But he is level headed and can cope.

‘I think people try to help you but it is best to learn on your own. When you are a young lad you do make mistakes and you have to learn from them because it will make you a better player.’

@highlight

Thierry Henry says England's rising stars must learn from Wayne Rooney

@highlight

Rooney is just two goals short of Sir Bobby Charlton's goalscoring record

@highlight

Henry has hailed the England captain as one of the greats of the game 