By 
Daily Mail Reporter

PUBLISHED:

03:18 EST, 17 October 2012


| 

UPDATED:

07:37 EST, 17 October 2012

An Earth-sized planet has been found orbiting a star in Alpha Centauri, our nearest neighbouring solar system.

The mystery world circling Alpha Centauri B is thought to be much too hot to support life, with surface temperatures of around 1,500C.

But astronomers say it is likely to be part of a more extensive solar system containing other planets, one or more of which might be habitable.

Next-door neighbour: An artist's impression of the recently found planet orbiting Alpha Centauri B, a member of the triple star system that is the closest to our own

At just 4.3 light years from the Sun, Alpha Centauri B is only a step away in astronomical terms; still, with current propulsion technology it would take a probe 40,000 years to get there.

Nevertheless, astronomers described the discovery as 'extraordinary' and did not rule out the possibility of sending an unmanned space mission there in the not-too-distant future.

Xavier Dumusque, of the Geneva Observatory in Switzerland, said: 'This result represents a major step towards the detection of a twin Earth in the immediate vicinity of the Sun. We live in exciting times.'

The planet was detected by European Southern Observatory (ESO) astronomers who measured tiny wobbles in the motion of Alpha Centauri B caused by a gravitational tug of war with the orbiting planet.

The planet orbiting Alpha Centauri B was found using a high-precision instrument called Harps on the ESO's 3.5m telescope at La Silla in Chile, pictured above.

Harps measures the radial velocity of a star — its speed towards or away from the Earth — with extraordinary precision.

A planet in orbit around a star causes the star to regularly move towards and away from a distant observer on Earth.

Due to the Doppler effect, this radial velocity change induces a shift of the star’s spectrum towards longer wavelengths as it moves away (called a redshift) and a blueshift (towards shorter wavelengths) as it approaches.

This tiny shift of the star’s spectrum can be measured with a high-precision spectrograph such as Harps and used to infer the presence of a planet.

A high-precision instrument called Harps 
on the ESO's 3.6m telescope at La Silla in Chile was used to spot minute
light wave fluctuations generated by the wobbles.

Data published today in the journal Nature show that the as-yet unnamed planet is unusually light, containing only a little more material than the Earth. It is the lightest exoplanet ever found orbiting a Sun-like star.

The planet hugs its parent star at a distance of just six million kilometres - much nearer than Mercury is to the Sun - making a complete orbit every 3.2 days.

Its surface is so hot it would probably resemble molten lava, the researchers say.

However previous experience tells the scientists that when you find one low-mass exoplanet of this kind, it is likely to be part of a bigger family.

The astronomers also know that Alpha Centauri B has a stable 'habitable zone', also known as the 'Goldilocks zone'. This is the orbital band where conditions would be 'just right' to support surface water and, potentially, life.

Leading U.S. planet hunter and astronomer Professor Greg Laughlin, from the University of California at Santa Cruz, said: 'I think the prospects are excellent for finding further planets in this system.

'Everything we know indicates that when you find one planet like this you're very likely to find additional planets further out, so it's very exciting in terms of looking forward to further detection.

'Alpha Centauri is our closest neighbour. This is our back yard, and to find out that planet formation is occurring there is just extraordinary.'

Alpha Centauri in the constellation of Centaurus (The Centaur): The star Alpha Centauri, marked with a red circle, is one of the brightest stars in the southern sky. It lies just 4.3 light-years from the Earth and one component in a triple star system

The scientists say they are '99.9 per cent' sure they have not been fooled by a false result caused by background noise in the data.

Co-author Dr Stephane Udry, also from Geneva Observatory, said: 'This is the first planet with a mass similar to Earth ever found around a star like the Sun.

Amateur astronomers have discovered a new planet that not only orbits two suns but is simultaneously being orbited by two other suns.

The incredible four sun solar system, the first of its kind ever discovered, was found as part of the Planet Hunters project led by a team from Yale University.

Amateur enthusiasts work alongside professional scientists to analyse data collected by NASA's Kepler space telescope and find evidence of new worlds

The planet, called PH1, a gas giant slightly bigger than Neptune, has being likened to Tatooine, the fictional two-sun planet and childhood home of Luke Skywalker from the Star Wars films.

But while Tattoine is a circumbinary planet, the likes of which have been known to scientists for some time, PH1 takes things even further with an extra two suns orbiting the entire set-up.

It means if someone were able to stand on PH1, they would be able to see a double sunset as well as two extremely bright stars far off in the night sky.

The quadruple star system, roughly 3,200 light-years from Earth, has been named KIC 4862625.

'Its orbit is very close to its star 
and it must be much too hot for life as we know it, but it may well be 
just one planet in a system of several.'

Further 'wobble' observations will difficult to carry out until the two A and B Alpha Centauri stars move further apart in a few years time.

But if the astronomers are lucky they might spot a 'transit' - the crossing of a planet in front of its star as seen from the Earth. When this happens the star light dims very slightly, betraying the planet's presence.

Increasing numbers of planets are now being detected in this way.

Members of the same European team made the first confirmed discovery of an extrasolar planet in 1995. Since then there have been more than 800 confirmed finds, but none so close to home.

Most are much bigger than the Earth, and many are as big as Jupiter.

The challenge astronomers now face is to detect and characterise a planet of mass comparable to the Earth that is orbiting in the habitable zone around another star.

Travel to the stars is the stuff of science fiction, but in the case of Alpha Centauri it might not be out of the question, according to Professor Laughlin.

He said: 'Using our current technology, the kind of space missions being sent to Mars and planets in our own solar system, it would require 40,000 years to get to Alpha Centauri. That's not really an option.

'I think if a potentially habitable planet is found orbiting Alpha Centauri A or B you might see a ground-swell of excitement and a look at new kinds of propulsion technologies, leading to a mission to send an unmanned probe there in the period of a lifetime.

'There have been design studies on the time scale of decades. They remain speculative and far-fetched, but it's not impossible.'

@highlight

Newly found world orbits Alpha Centauri B, 4.3 light years from our Sun

@highlight

It is the lightest exoplanet yet found orbiting a Sun-like star

@highlight

It is thought to be too hot for life, and there is likely no water present

@highlight

But presence suggests there may be other planets within the same system