By
Jonathan O'Callaghan

Earth's magnetic field is a protective shield for our planet from cosmic radiation, but it's also somewhat of a mystery - scientists aren't sure why it moves and changes in intensity.

And now the first set of high-resolution results from Esa’s three-satellite Swarm constellation reveal that the field is actually getting weaker, albeit by a small amount.

Measurements
 made over the past six months confirm the general trend of the field’s 
weakening, with the most dramatic declines over the Western Hemisphere.

Scroll down for video

Esa's Swarm constellation of satellites have measured changes in Earth's magnetic field from January to June 2014. These changes are based on the magnetic signals that stem from Earth's core. Shades of red represent areas of strengthening, while blues show areas of weakening, measured in nanoteslas

Launched in November 2013, Swarm is providing unprecedented insights into the complex workings of Earth’s magnetic field, which safeguards us from the bombarding cosmic radiation and charged particles.

The magnetic North pole has been moving for at least 100 years since measurements began.

It is near the Geographic North Pole but, unlike the latter, does not stay in the same place.

Having recently departed the Canadian Arctic it is now moving towards Siberia.

It can move as much as 37 miles (60 kilometres) a year, but in recent times it has begun to slow down, suggesting it may double back on itself.

The reason for its movement, however, is unknown.

In some areas, such as the southern Indian Ocean, the magnetic field has strengthened since January - although the overall trend is a weakening.

The latest measurements also confirm the movement of magnetic North towards Siberia.

These changes are based on the magnetic signals stemming from Earth’s core.

Over the coming months, scientists will analyse the data to unravel the magnetic contributions from other sources, namely the mantle, crust, oceans, ionosphere and magnetosphere.

This will provide new insight into many natural processes, from those occurring deep inside our planet, to space weather triggered by solar activity.

In turn, this information will yield a better understanding of why the magnetic field is weakening.

'These initial results demonstrate the excellent performance of Swarm,' said Rune Floberghagen, Esa’s Swarm Mission Manager.

'With unprecedented resolution, the data also exhibit Swarm’s capability to map fine-scale features of the magnetic field.'

The results were presented at the Third Swarm Science Meeting in Copenhagen, Denmark.

The data collected by the Swarm satellites will help scientists better grasp how our magnetic field works, how it is affected by solar activity, and why large tracts of it are weakening.

Esa says the field can be thought of as a huge bubble, protecting us from cosmic radiation and charged particles that bombard Earth in ‘solar winds’.

Without it, those particles would hammer away at the atmosphere, leaving Earth much like Mars.

Swarm is a ESA satellite mission that launched on 22nd November 2013 (illustrated right).

The
 mission consists of three identical satellites that are precisely measuring the strength and direction of Earth's magnetic field.

The new 
data is being processed by the British Geological Survey to produce an 
accurate map of this field.

In
 order to best measure the field, the satellites orbit in a unique 
configuration.

Two satellites will fly side-by-side at height of 280 miles (450km),
 while the third satellite will fly at an altitude of 330 miles (530km).

The
 lower two satellites allow very fine measurements of the magnetic 
field generated by the rocks in the Earth's crust, which are difficult 
to detect otherwise.

The upper satellite gives a simultaneous 
measurement at a different location.

Swarm (illustration shown) is Esa's first Earth observation constellation of satellites. The three identical satellites were launched together on one rocket. The satellites' orbits drift, which will result in the upper satellite crossing the path of the lower two at an angle of 90° in 2016

This 'snapshot' of the main magnetic field at Earth's surface as of June 2014 is based on Swarm data. The measurements are dominated by the contribution from Earth's core (about 95%) while the contributions from other sources (the mantle, crust, oceans, ionosphere and magnetosphere) make up the rest

The agency said the field is particularly weak over the South Atlantic Ocean - known as the South Atlantic Anomaly.

Many glitches or ‘hiccups’ are caused by this anomaly, as satellites are exposed to strong radiation over this area.

Some experts believe the overall weakening heralds the reversal of Earth’s magnetic field, where the north becomes south and south becomes north - a process that is thought to take several hundred thousand years to complete.

Almost all of the observed changes are based on the magnetic signals that originate in Earth’s core.

Over the coming months, scientists will analyse the data to better understand the magnetic contributions from other sources.

Apart from understanding our world better, scientists believe measurements obtained by Swarm will have a number of real world applications, including improving the accuracy of navigation systems, advanced earthquake prediction and better efficiency in drilling for natural resources.

The magnetic field and electric currents near Earth generate complex forces that have immeasurable impact on our everyday lives. Although we know that the magnetic field originates from several sources, exactly how it is generated and why it changes is not yet fully understood

@highlight

Esa's Swarm satellite constellation reveals data on Earth's magnetic field

@highlight

The results, presented in Denmark, show the field is weakening in places

@highlight

The Western Hemisphere, in particular, is dramatically getting weaker

@highlight

But other places, including the east coast of Africa, are becoming stronger

@highlight

This is seen by some as a sign the magnetic field will soon reverse

@highlight

And areas of different intensity can also be harmful to other satellites

@highlight

The three satellites also accurately tracked the magnetic North pole