By 
Rob Waugh

UPDATED:

13:42 EST, 26 March 2012

Fundamental unanswered questions 
about our universe could finally get answered – thanks to a £1.3bn 
telescope called the Square Kilometre Array (SKA).

The directors of the project are to meet in Amsterdam on 3 April to discuss the location of the huge telescope, scattered across 1,900 square miles of Earth's surface. It will start building in 2016.

'It will have a deep impact on the way we perceive our place in the universe and how we understand its history and its future,' says Michiel van Haarlem, interim director general of the SKA project.'We know we are going to discover things.'

Numbers game: This artist's impression shows the SKA's dishes, which will scan space for electromagnetic radiation - and hopefully reveal the universe's secrets

Sensitive: The SKA's dishes will be able to detect an airport radar on a planet 50 light years away

The final location for the Square Kilometer Array has yet to be decided

It
will scoop up so much information about the cosmos that a supercomputer
equivalent in power to a staggering one billion PCs will be needed to 
process it all.

The
SKA will consist of thousands of dishes across 1,900 miles, with a 
total surface area of one square kilometre, that will provide so much 
data that one astronomer has declared it will completely change our view
of the universe.

Dr Ian Griffin, from the UK 
Association of Science and Discovery Centres, told MailOnline: ‘The SKA 
project will provide astronomers with a fantastic new tool which may 
well revolutionise our understanding of the universe.

‘With its huge area the telescope 
will show incredibly fine detail in galaxies, help test the theory of 
relativity by studying exciting and mysterious objects like black holes 
and allow astronomers to learn more about the early history of the 
universe.'

The
scientific community also believe that the SKA represents our best ever
chance of finding out if there’s life beyond our solar system.

To
do this will require ground-breaking technology. The SKA’s 15m-dishes, 
which will detect electromagnetic radiation emitted by objects in space,
will be the most sensitive ever built - able to detect an airport radar
on a planet 50 light years away.

These
dishes will be complemented by low and medium frequency aperture 
arrays, which provide a large field of view and are capable of observing
more than one part of the sky at once.

Medium frequency aperture arrays: These are capable of scanning more than one part of the sky at once

Space-aged kit: An artist's impression of SKA's low-frequency aperture arrays

Good spread: This graphic illustrates how the dishes and apertures will be arranged as they scan the heavens

Heavens above: SKA will peer deep into space telling us about black holes, how stars are born and if there is alien life out there

The volume of data produced 
from the dishes will be mind-boggling – many Petabits per second, or 
around 100 times the current global internet traffic and enough to fill 
15million 64GB iPods every day.

It will be carried on enough optical fibre cable of such quantity that it could be wrapped twice around the world.

And a super-computer capable of one million trillion operations per second will have to be built to analyse it - that's 1000 times faster than the most powerful we have today.

A
lot of brainpower will be needed to build the SKA and there are 67 
organisations in 20 countries contributing to its design and 
manufacture.

As yet, a location for it hasn’t been decided, but Southern Africa and Australia are all in the reckoning.

They
all offer areas with ideal conditions for telescopes, which must be 
well clear of electronic interference, such as that generated by mobile 
phones.

It’s hoped that construction will begin in 2016, with the dishes coming online eight years later.

A prototype of SKA called KAT-7, which consists of seven 16-metre dishes, is undergoing testing in South Africa's Karoo desert.

Spaced out: The KAT-7 prototype in South Africa's Karoo Desert

@highlight

It will gather so much data that a super-computer equivalent to one billion PCs will be needed to process it

@highlight

Will cover 1,900 square miles

@highlight

Project to meet in early April to discuss location

@highlight

Will be in South Africa or Australia

@highlight

Telescope will start building in 2016