Robbie Williams documented his wife Ayda Field's labour in a number of YouTube videos so it's not surprising the couple chose to announce their son's name in the same way. 

But now the singer is facing a backlash because some fans claim he has used the birth of Charlton to promote his upcoming European tour, which kicks off in March 2015 and was announced yesterday. 

The Candy hitmaker posted a humorous video to his official account, showing Ayda pushing him and their son in a wheelchair out of hospital and captioned it, 'Charlton Valentine Williams has left the building.'

However, Robbie also uploaded yet another video which he used to reveal that he would be embarking on a world tour titled, Let Me Entertain You.

Scroll down for video 

Surprise: Robbie Williams has used the interest generated by the birth of his son, Charton Valentine, to announce his plans to go on a new tour

Meet Charlton Valentine Williams: Robbie Williams posted this humorous video of his wife Ayda Field pushing him and their newborn son out of hospital after she gave birth 

Twitter user Jennifer 0693 said: 'How disgustingly tacky to use your wife's labour to promote a world tour. Bore off.'

Rob Shepherd added: 'If that is where "celebrity" has reached bring back punitive pop taxes.' 

The couple already have daughter Theodora 'Teddy' Rose Williams, two, together and welcomed Charlton on Monday, with the tot weighing eight pounds and two ounces.

The video shows Ayda pushing a wheelchair through the hospital, and when she turns the corner, Robbie can be seen sitting in it with Charlton in his lap. 

Robbie shared clips of Ayda's labour on his official YouTube account and later spoke about his 'astonishing' wife.

Doing all the work: After giving birth, Ayda was roped in to push her two boys out of hospital in a wheelchair in this hilarious new video 

He said: 'I've never been more in love, and I've never been more proud of my wife. She's been absolutely astonishing.'

Robbie added: 'The universe has presented itself to us again and it's been a very emotional, amazing few hours and we're really happy and honoured that you experienced the journey with us.'

The 40-year-old singer  married Ayda in 2010.

Happy day: Robbie Williams praised his wife after she gave birth to a little boy - their second child on Monday

Crazy! The star has spent the day posting videos and pictures of his wife as she prepared to give birth

All that dancing has worn him out: Robbie and Ayda wore matching eye masks as they had a little snooze

'When Ayda goes into labour she comes correct,' the funny man wrote as he posted a snap of his wife's heels 

Robbie had been entertaining his fans  with amusing videos from the hospital room, including a video which showed him doing a rendition of Let It Go from the hit movie, Frozen, whilst his wife appeared to be giving birth.

One picture showed her on a bed wearing high heels with the words: 'When Ayda goes into labour she comes correct,' the funnyman wrote as he helps his wife get through the experience. 

He also published videos showing the pair of them dancing in their hospital room and another where he jokingly tells fans: 

'It's quarter past seven, we've been here since ten o'clock last night and I know you're really concerned and worried and thinking about what's going on. I need you to know I'm doing great.' 

Getting into the spirit of things: Ayda appeared to be having just as much fun as she danced upon her husband's lap 

Another video, called A River Runs Through It, appears to show a doctor preparing to break his actress wife's waters. 

Williams broke the news on Twitter earlier this year that the couple, who live in Los Angeles with daughter Teddy, were expecting another baby.

The Stoke-born singer first hit the headlines in Take That but quit the group in 1995 and embarked on a hugely successful solo career.

Check out my bump: The lovely lady was most amused by the moves she was making

He told The Sun on Sunday newspaper: 'I'm hooked on anything that takes my mind off me.

'It used to be food, drugs, sex, the internet, smoking or TV. Now it's my daughter.' 

He said: 'I'm in a content stage of my life. That's because I'm married with a kid. I'm less reckless. I thought it was all about the cars and the clothes, the girls and the house. But none of that is for me.

'With a baby girl there's a point to it other than my own ego. I'm now tethered to the planet.'

Loving life: The star recently revealed how much he loves being a dad (pictured here with his first born Teddy)

 

@highlight

Singer released showing Ayda pushing him and their son in a wheelchair

@highlight

However, Robbie also uploaded yet another video to announce tour

@highlight

One Twitter user called the move 'disgustingly tacky' 