By 
Anna Edwards

PUBLISHED:

05:05 EST, 23 September 2013


| 

UPDATED:

05:08 EST, 23 September 2013

A powerful typhoon that slammed into southern China with winds that blew cars off the road has caused more deaths, bringing the toll in Asia to at least 33.

Typhoon Usagi, which was the season's strongest storm at its peak, forced hundreds of flight cancellations and shut down shipping and train lines before weakening to a tropical depression over the southern Chinese province of Guangdong today.

China reported 25 deaths in Guangdong, where the typhoon made landfall late last night near Shanwei with record sustained winds for the city of 109mph.Scroll down for video

A Filipino man sits on a inflated tyre in a flooded street in Quezon City, east of Manila, Philippines

At least 33 people have died after Typhoon Usagi swept across southern China's Guangdong province, while the landslide cause by storm left fifteen people dead in the Philippines, officials said

Residents use a small boat for transport through a flooded street at suburban Quezon city, northeast of Manila

On Saturday the storm had been a super typhoon when it passed between Taiwan and the Philippines, sparing both of them the brunt of the winds.

However, Philippine officials said eight people were dead from drowning and landslides, and Taiwan authorities reported nine people hurt by falling trees.

The storm wreaked havoc on travel 
plans just as many passengers were returning home after an extended 
weekend for the Chinese mid-autumn festival.

More
than 250 incoming and outgoing flights were cancelled in Hong Kong, and
an additional 200 were delayed, Airport Authority Hong Kong said.

Huge: Super Typhoon Usagi is seen heading west-northwest through the Luzon Strait in this shortwave infrared satellite image. The strongest storm in the Western Pacific this year was today headed for Hong Kong

Intercity trains including the high-speed rail to Beijing, Shenzhen and Hong Kong were suspended until tomorrow, the official Xinhua news agency reported.

At least 13 of the 25 victims in China were killed in worst-hit Shanwei city, where winds blew cars off the road near a petrol station and houses were toppled, Xinhua said. One county's electricity and water supply were cut off.

In Hong Kong, dozens of trees were reported down and 17 people had sought medical treatment, with eight of them admitted to hospital, according to the Hong Kong government's information services department.

China's National Meterological Centre said the typhoon would continue to weaken as it moves north-west and bring heavy rains later today and overnight to five southern provinces.

Blow me down: People in Taipei hold their umbrellas tight against powerful gusts of wind generated by Typhoon Usagi as the storm passed 342 miles south, sparing the country's coast from the worst of its wrath

Better off with a macintosh: People in Taipei struggle to keep dry in the heavy rain brought by the storm

A woman and her child hold their umbrellas tight against powerful gusts of wind: Gusts of nearly 150mph were recorded further south on the Taiwanese island of Lanyu in the Luzon Strait

Further south: A three-wheeled taxi lies on its side after being blown over by winds from Typhoon Usagi in the town of Hengtsun in south-east Pingtung county today as it swept past the southern parts of Taiwan

Waterfalls cascade on to a road close to Hengtsun: Nearly 2,500 people were evacuated from flood-prone areas and remote mountainous regions as Taiwanese soldiers were deployed into potential disaster zones.

In the Philippines, parts of the capital remained submerged today and classes were cancelled.

The
landslide deaths occurred in two villages in Zambales province west of 
Manila, Subic town mayor Jeffrey Khonghun said. Two drowning deaths were
reported previously.

Usagi had gusts exceeding 163 mph 
yesterday as it battered island communities in the Luzon Strait, 
according to the U.S. Navy's Joint Typhoon Warning Center.

China's
National Meteorological Centre announced a red alert, its highest 
level, as the storm maintained its track toward Hong Kong and the 
manufacturing heartland of the Pearl River Delta.

The
Hong Kong Observatory was yesterday maintaining a No. 1 Standby Signal 
and warned that the storm poses a 'severe threat' to the densely 
populated city, where windows were taped up in anticipation of the 
chaos. 

As the storm passed 342 miles south of Taiwanese capital Taipei, the country's Central Weather Bureau said it was veering west, mostly likely sparing the country's south from the most destructive winds near its eye.

Is that really a good idea? A man and a boy sit inside a makeshift raft as they paddle through rough waves brought by Super Typhoon Usagi along the coast of Manila Bay in Navotas City, Philippines

A boy clings to a concrete bank as rough waves 
crash into Manila Bay: Usagi slammed into the Philippines' northern 
islands today, cutting communication and power lines, triggering 
landslides and swamping rice fields

Filipino children scamper across wrecked floating shanties at a
village in Paranaque city, south of Manila: The Filipino 
weather bureau warned that storm surges and heavy waves could cause 
more heavy damage tonight

A Filipino girl walks away from a shack: The 
Office of Civil Defense in Manila, the Filipino capital, said landslides
damaged houses and roads, and pockets of power outages were reported in
at least five northern provinces

A man walks past crashing waves at Manila's Baywalk area: The Philippines has avoided the brunt of the storm

But gusts of nearly 150mph were 
recorded on the Taiwanese island of Lanyu, and the bureau warned that 
dangerous winds were buffeting the holiday resort of Kending on the 
Hengchun peninsula.

In the 
Philippines, the storm triggered landslides and power outages in parts 
of the north of the country, including the Batanes island group, where 
it made landfall early this morning.

The
Filipino weather bureau warned that storm surges and heavy waves could 
cause damage in the Batanes and other islands in the Luzon Strait before
Usagi blows past the country by tonight.

In Taiwan, nearly 2,500 people were 
evacuated from flood-prone areas and remote mountainous regions as the 
government deployed military personnel into potential disaster zones.

The
storm system has dumped more than 8in of rain along the eastern and 
southern coasts in a 13-hour period, with officials warning that a total
rainfall of 39in could drop before the storm leaves.

Local
officials closed mountain highways blocked by landslides and suspended 
train services connecting the east and west coasts as power outages 
affected thousands of homes.

Usagi
has a massive diameter of 680 miles, with its outer rain bands 
extending across Luzon and all of Taiwan across to the Chinese coast.

The Office of Civil Defense in Manila 
said landslides damaged houses and roads, and pockets of power outages 
were reported in at least five northern provinces, where several roads 
and bridges were impassable.

Frightening: An image taken from space by the Japanese Meteorological Agency's MTSAT-2 satellite yesterday

Getting ready: A man leaves a Hong Kong shopping mall where entrances are taped up in anticipation of the expected chaos that Usagi will bring when it makes landfall there on Sunday evening

@highlight

Typhoon Usagi hit southern China with winds that blew cars off the road

@highlight

Gusts exceeded 163mph today as it swept through the Luzon Strait

@highlight

China announces red alert for Pearl River Delta manufacturing heartland

@highlight

Hong Kong Observatory warns of 'severe threat' to densely peopled city