Think of a deadly predator and you may imagine a powerful shark or ferocious lion.

But dragonflies are nature’s most successful predator when it comes to catching prey, scientists have revealed.

The winged insect catches more than 95 per cent of the prey it targets - making it twice as successful as a great white shark, and four times as effective as the king of the jungle.

Dangerous: Dragonflies are nature’s most successful predator when it comes to catching prey, scientists claim. They affixed tiny reflective markers to insects bodies and filmed them in slow motion to measure their head and body orientation during flight

Dragonflies eat mosquitoes and other small insects such as flies, bees, ants and wasps, as well as the occasional butterfly, which they hunt around marshes, lakes, ponds, streams and wetlands.

The reason the dragonfly is such as effective hunter is that when targeting its prey, the insect keeps it in sight while adjusting its flight, and can predict how it will move before catching it.

Scientists at the Howard Hughes Medical Institute in Virginia likened the insect’s calculations - about its own movements and those of its target - to those used by a ballet dancer to catch his partner. 

It’s the first example of such skill in invertebrates.

Its huge eyes provide an almost spherical view of the world while the insect perches on a leaf waiting for prey to fly overhead. 

Agile: The dragonfly's body and head move independently, with the latter locking on to the target while its body manoeuvres to the best position for capture prey

The best: The winged insect catches more than 95 per cent of the prey it targets - making it twice as successful as a great white shark (pictured left) and four times as effective as the lion (right), based on calculations made by the researchers

There are 5,900 different species of dragonflies, which are characterised by their large multifaceted eyes, two pairs of strong wings and an elongated bodies.

They are among the largest flying insects in the world and can fly backwards, hover and change direction in mid-air.

They can fly at nearly 60mph (97km/h).

Dragonflies catch more than 95 per cent of the prey they target - making them the most accurate and deadly hunter.

They eat mosquitoes and other small insects such as flies, bees, ants, wasps as well as the occasional butterfly, which they hunt around marshes, lakes, ponds, streams and wetlands.

While predators themselves, they are food for lizards, birds, amphibians and fish.

When the time is right, it shoots off in pursuit, scooping up victims with its hairy legs in a fraction of a second.

Its visual sharpness and lightning-quick reflexes - thanks to specialised neurons that detect the motion of a target and instruct its wings to react = make it a formidable hunter.

High-speed measurements show how the dragonfly tracks the position of a fly and steers itself quickly towards it, relying on both prediction and reaction. 

Scientists fitted insects with tiny reflective markers and used motion-capture technology to record the insects in action at 1,000 frames-per-second, replaying the film 20 times slower to analyse tiny movements.

The footage demonstrated that dragonfly manoeuvres are generated by predictions of prey movement combined with visual reactions.

This allows the insect to estimate the position of a fly, for example, and determine the wing and head movements required to catch it.

To avoid detection, a dragonfly approaches from below and aligns its body to the prey’s direction of motion.

Keeping an eye out: The dragonfly's huge eyes provide an almost spherical view of the world while the insect perches on a leaf waiting for prey to fly overhead (pictured). When the time is right, it shoots off in pursuit of prey, scooping up victims with its hairy legs in a fraction of a second

Its body and head move independently, with the latter locking on to the target while its body manoeuvres to the best position for capture.

The study, published in Nature, indicates steering behaviour in dragonflies is more sophisticated than previously thought - but whether this is the case for other invertebrates remains to be seen.

‘The study highlights the role internal models play in letting these creatures construct such a complex behaviour. It starts to reshape our view of the neural underpinnings of this behaviour,’ Dr Anthony Leonardo said.

The researchers filmed dragonflies as they chased after either a fruit fly or a bead on a pulley system - artificial prey - which the scientists could precisely control.

It was clear from the videos that the dragonflies were not simply responding to the movements of the prey.

Instead they made structured turns that adjusted the orientation of their bodies, even when their prey’s trajectory did not change.

Dr Leonardo said: ‘Those turns were driven by the dragonfly’s internal representation of its body and the knowledge it has to rotate its body and line it up to the prey’s flight path in a particular way.

‘At the end of the chase the dragonfly makes a basket out its legs and the prey drops into it.’

@highlight

Winged insect catches more than 95 per cent of the prey it targets

@highlight

Dragonfly keeps its prey in sight at all times with its large eyes

@highlight

It adjusts its flight and can predict how its prey will move before catching it

@highlight

Scientists at the Howard Hughes Medical Institute in Virginia filmed the insect's flight in slow motion to reveal its effective hunting techniques