It is the ultimate in portable TVs - a giant screen you can simply roll up and take away with you.

LG today showed off a working 18inch version - and says a 60 inch screen could go on sale in 2017.

The Ultra HD screen uses a special film instead of plastic as backing to allow screen to be rolled into a tight tube for transport.

LG has revealed a working roll-up TV that is also transparent when not in use. The Ultra HD screen uses a special film instead of plastic as backing to allow screen to be rolled into a tight tube for transport.

LG Display used high molecular substance-based polyimide film as the backplane of the flexible panel instead of conventional plastic to achieve the maximum curvature radius.

The polyimide film also helped reduce the thickness of the panel to significantly improve its flexibility.

As for the transparent OLED panel, it boasts 30 percent transmittance, which was achieved by adopting the company’s transparent pixel design technology. 

The 
flexible OLED panel has a high-definition class resolution of 1200 X 810
 with almost 1 million mega-pixels.

The panel can be rolled up to a radius of 3cm without affecting the function of the display. 

This proves that LG Display can bring rollable TVs of more than 50 inches to the market in the future, the firm said.

'LG Display pioneered the OLED TV market and is now leading the next-generation applied OLED technology,' said In-Byung Kang, Senior Vice President and Head of the R&D Center at LG Display.

'We are confident that by 2017, we will successfully develop an Ultra HD flexible and transparent OLED panel of more than 60 inches, which will have transmittance of more than 40 percent and a curvature radius of 100R, thereby leading the future display market.'

The panel can be rolled up to a radius of 3cm without affecting the function of the display.

LG Display used high molecular substance-based polyimide film as the backplane of the flexible panel instead of conventional plastic to achieve the maximum curvature radius.

The polyimide film also helped reduce the thickness of the panel to significantly improve its flexibility.

As for the transparent OLED panel, it boasts 30 percent transmittance, which was achieved by adopting the company’s transparent pixel design technology. 

LG has revealed a working roll-up TV that is also transparent when not in use. The Ultra HD screen uses a special film instead of plastic as backing to allow screen to be rolled into a tight tube for transport.

LG Display has successfully lowered the haze of the panel which is generated by using circuit devices and film components to a level of 2 percent. 

With this breakthrough development, the company has been able to improve greatly the technology level of the transparent display. 

Samsung has already shown off a prototype flexing screen. However, the new mesh technology will allow screens that can be completely folded or rolled into a tight tube without damaging them.

Considering that the transmittance of existing transparent LCD panels is around 10 percent, this new panel offers significantly improved transmittance.

The University of Houston researchers have developed an entirely new stretchable and transparent electrical conductor, bringing the potential for a fully foldable cell phone or a flat-screen television that can be folded and carried under your arm closer to reality.The gold nanomesh electrodes produced by Ren and his research associates Chuanfei Guo and Tianyi Sun at UH, along with two colleagues at Harvard University, provide good electrical conductivity as well as transparency and flexibility, the researchers said in a paper in Nature Communications.

@highlight

LG have developed working 18inch version - and says 60 inch version will go on sale in 2017

@highlight

Uses special film instead of plastic as backing to allow screen to be rolled into a tube

@highlight

Finished screen with be Ultra HD resolution 16 times better than conventional HDTV

@highlight

Firm also showed is also transparent when not in use