By 
Daily Mail Reporter

PUBLISHED:

17:26 EST, 5 September 2012


| 

UPDATED:

17:48 EST, 5 September 2012

Fall from grace: A federal probe found former Harvard psychology professor Marc Hauser to be responsible for six cases of research misconduct

Federal investigators have found that a Harvard University psychology professor who resigned after being accused of scientific transgression fabricated data and manipulated results in experiments.

The findings detailing Marc Hauser's transgressions were contained in a report by the Department of Health and Human Services Office of Research Integrity (ORI) released Wednesday online.

Hauser, 52, left Harvard last summer, ten months after a faculty investigation found him ‘solely responsible’ for eight instances of scientific misconduct at the prestigious Ivy League school, the Boston Globe reported.

The federal document found six cases in which Hauser engaged in research misconduct in work supported by four National Institutes of Health grants. One paper was retracted and two were corrected. Other problems were found in unpublished work.

Hauser released a statement Wednesday, saying that although he has fundamental differences with the findings, he acknowledges that he made mistakes.

‘I let important details get away from my control, and as head of the lab, I take responsibility for all errors made within the lab, whether or not I was directly involved,’ he stated.

‘I am saddened that this investigation has caused some to question all of my work, rather than the few papers and unpublished studies in question.

‘I remain proud of the many important papers generated by myself, my collaborators and my students over the years. I am also deeply gratified to see my students carve out significant areas of research at major universities around the world,’ Hauser said.

Internal probe: A three-year investigation at Harvard found in 2010 that Hauser had committed eight instances of scientific misconduct

In one instance, investigators determined that Hauser fabricated half the data in a bar graph in a research paper on cotton-top tamarind monkeys’ ability to learn syllables that was published in 2002 in the journal Cognition.

According to the findings of the probe, the 52-year-old professor ‘falsified the coding’ of some monkeys’ responses to sound stimuli in two unpublished papers to ensure that a particular finding does not appear random, and ‘falsely reported the results and methodology’ for one of seven experiments in a paper published in Proceedings of the Royal Society B in 2007.

A paper examining monkeys’ abilities to learn grammatical patterns included false descriptions of how the monkeys’ behavior was coded, ‘leading to a false proportion or number of animals showing a favorable response,’ the report stated.

The document, which will be published in the Federal Register Thursday, comes on the heels of a three-year internal investigation at Harvard that found in 2010 that the popular professor had committed eight instances of scientific misconduct.

According to the report, Hauser ‘neither admits nor denies committing research misconduct but accepts ORI has found evidence of research misconduct.’ As part of a voluntary settlement, the former professor has accepted several professional restrictions for the next three years.

New job: Hauser currently works with at-risk youth at the Alternative Education Program at Cape Cod Collaborative

Hauser has agreed to have any research supported by the U.S. Public Health Service supervised, to exclude himself from serving as an adviser to the PHS, and to have his employer guarantee the accuracy of his data and methodology before applying for federal funding.

According to his LinkedIn profile, Hauser currently works with at-risk youth at the Alternative Education Program at Cape Cod Collaborative.

Houser, a published author of popular books favored by the media, gained wide recognition for his research into the evolutionary roots of human abilities, including language, and whether morality was inborn or learned.

Less than a week ago, Hauser's former Ivy League employer made national headlines after it has been revealed that 125 students at the prestigious institution are being investigated for allegedly cheating on a take-home exam.

 

 

@highlight

Marc Hauser, 52, researched evolutionary roots of human abilities

@highlight

Probe by Office of Research Integrity found Hauser responsible for six cases of scientific misconduct

@highlight

Allegedly fabricated data in a paper on monkeys' ability to learn syllables

@highlight

Currently works with at-risk youth at Cape Cod Collaborative