When BBC documentary Reinventing the Royals was first listed on TV schedules in Iate December, few paid it much attention.

But when claims that Clarence House  had refused to release archive footage and had tried to stop it from being aired emerged in the Radio Times, the programme suddenly became front page news.

Tonight, Reinventing the Royals, a two-part series written and presented by Panorama journalist Steve Hewlett will finally air, while Clarence House has denied ever trying to prevent it.

Scroll down for video 

Royal row: The Prince of Wales will feature in Reinventing the Royals, the BBC documentary airing tonight

So is it really as damaging as some have claimed? The series opens with the death of Princess Diana in 1997, with the first episode focusing on the brickbats hurled at Prince Charles in its wake.

With his personal popularity in the doldrums, Charles asked PR guru Mark Bolland, who was hired in 1996, to give his public image a makeover - and integrate Camilla Parker Bowles into palace life.

Dubbed 'Operation Mrs PB', the campaign is the source of one of the most embarrassing allegations aired in the programme - namely that Bolland leaked news of Prince William's first meeting with Camilla to the media.

Bolland has denied this incident ever happened, but the Duke of Cambridge was reportedly left angry and upset by the leak and is said to have nicknamed the PR supremo 'Blackadder'.

But even that has been overshadowed by the controversy over the programme itself, which Clarence House insists it never tried to interfere with.

'The original broadcast of the programme was delayed by mutual agreement (BBC and Clarence House) whilst permissions were sought,' said a Clarence House spokesman.

Investigation: The series, fronted by Steve Hewlett (c), delves into the media's relationship with the royals

Controversial: Hewlett was editor of Panorama when it broadcast the infamous 1995 Princess Diana interview

'All permissions were subsequently granted. We have not seen the programme yet and have no comment to make.'

Nevertheless, the ensuing row reportedly left Prince Charles 'furious' - all the more so when lurid claims of spats between the Buckingham Palace and Clarence House press teams emerged. 

Worse still, the row overshadowed what had been, until then, a successful year, with the royal widely praised for his hard work and the positive headlines generated by overseas tours to Colombia and Jordan among others.

For its part, the BBC says the documentary was always going to be aired, with a spokesman telling MailOnline that coverage is going ahead 'as planned'.

'Before Christmas it became clear that there were issues relating to the clearance of archive footage in the forthcoming programme Reinventing The Royals,' continued the BBC spokesman.

Campaign: Much of the controversy focuses on Mark Bolland (l) and Sandy Henney (r) also features

Unimpressed: The Duke of Cambridge (l) reportedly referred to Bolland as 'Blackadder'

'These issues have now been resolved and all the archive material we planned to use is included in the finished programme. 

'The first episode of Reinventing The Royals will be broadcast on 19 February and it will be the one that we always intended to show.'

The footage includes the first-ever television interview with Sandy Henney, who was press secretary to Prince Charles at the time of Princess Diana's death.

Even before the accident, the Prince was worried his image was 'in tatters' while the Royal family were also alarmed by the anti-monarchist feeling following the Diana's death in Paris.

'(Charles) was getting some pretty virulent criticism - bad father, unloving husband,' Ms Henney said in the documentary.

Furious: Charles was reportedly unhappy about the way the row overshadowed his work

Success: 2014 had been a successful year but ended on a sour note because of the controversy

'I think he was pretty hurt... if you've got a middle-aged balding man and a beautiful princess, it's a no-brainer as to who is going to get the media coverage.'

Steve Hewlett, the editor of Panorama at the time of the infamous 1995 interview with Princess Diana, presents the show and describes how Prince Charles hired Mark Bolland from the Press Complaints Commission to act as a spin doctor for the Royal family following Diana's death.

The younger royals also make an appearance in the documentary, among them Prince Harry who at one point opines: 'I don't believe there is any such thing as privacy anymore.'

Testament, if nothing else, to the sometimes troubled relationship between the royals and the Press.

@highlight

Charles was reportedly left fuming over controversy caused by the row

@highlight

Clarence House says it never tried to block transmission of the show

@highlight

Reinventing the Royals will air on BBC2 tonight at 9pm 

@highlight

Two part programme opens with the aftermath of Princess Diana's death

@highlight

Reinventing the Royals, tonight at 9pm on BBC2 