By
Ted Thornhill
and Jason Groves

Britain’s grieving families face the second highest death duties in the world, a new report has revealed.

Only Ireland has a higher rate of inheritance tax, with the treasury grabbing, on average, more than 25 per cent from someone with an estate worth £1.8m, according to a report by accountants UHY Hacker Young.

Britain has an inheritance tax threshold of £325,000, which may seem fairly high – but an increasing number of people are having the value of their assets diminished as the threshold hasn’t been kept in line with house price rises.

Taxing issue: Death duties in Britain are the second-highest in the world

Tax rates by the numbers

Over the next five years the taxman will rake in over £24.3billion from death duties.

The average global rate is 7.7 per cent, but it’s just one per cent in Brazil, Russia, India and China, while death duties have been abolished in Australia, Israel and New Zealand.

The Tories said they will raise the threshold to £1million at the next election.

David Cameron said recently that the threshold should rise to ensure only the rich pay death duties.

Without action, the number of families paying the 40 per cent levy will double to one in ten over the next five years.

Mr Cameron said the issue was ‘something we’ll have to address in our manifesto’. ‘I believe in people being able to pass money through the generations and pass things on to their children,’ he said.

‘You build a stronger society. Inheritance tax should only really be paid by the rich – it shouldn’t be paid by people who’ve worked hard and saved and who bought a family house.’

Mr Cameron’s statement of intent will cheer many traditional Conservatives.

Tory MP Douglas Carswell said: ‘It is very encouraging. The Prime Minister is starting to show us what a proper Conservative government would look like.

‘This is becoming a big issue again because rising house prices mean that a lot of people who are not rich are being caught up by a tax that was meant for the very wealthy.

‘It is a natural urge to want to leave something for your children and it is wrong that people of average means who have worked hard all their lives are facing these punitive tax rates.’

Former Tory Cabinet minister John Redwood gave a more cautious welcome to the announcement, warning that other tax cuts, such as raising the 40p threshold or reducing capital gains tax, might take priority.

He said: ‘All tax cuts are good news, but there will be plenty of competition for which will be the best tax cuts.’

Ladislav Hornan, Managing Partner of UHY Hacker Young, said: ‘Big inheritance tax bills can reduce the incentive to keep creating wealth in order to pass it on to your family.  They can also deprive the next generation of capital that traditionally has been key to funding the establishment of new businesses.

‘That is why dynamic developed economies like Australia have scrapped inheritance taxes altogether, and some emerging economies have never imposed them.

‘By contrast in the UK, the Exchequer has become increasingly reliant on the substantial income streams generated by inheritance tax.  It has been seen as a lucrative way to extract tax revenues from a relatively ageing population: retirees frequently have lower levels of taxable income, but substantial assets such as mortgage-free homes.

‘As more and more UK families are caught in the inheritance tax trap, pressure for major reform is growing.’

The Office for Budget Responsibility 
warned recently that the proportion of estates hit by death duties was set 
to double from almost one in 20 to nearly one in ten during the next 
five years.

Pledge: Prime Minister David Cameron has vowed to raise the inheritance tax threshold from £325,000 to £1m

@highlight

Only Ireland has a higher rate of inheritance tax than Britain

@highlight

Countries such as Australia and New Zealand have abolished death duties

@highlight

The Tories said they will raise the threshold to £1million at the next election