Controlling the mind, and actions, of another person sounds like something from a sci-fi film, but researchers have taken a step closer to making it a reality.

A student, fitted with an EEG cap, has successfully controlled the hand of a friend when playing a video game using direct brain-to-brain communication.

And the reaction was immediate, despite the two players being in different locations and not being told when the game would begin.

Scroll down for video 

Darby Losey (left) and Jose Ceballos (right) were sitting half a mile apart. The 'sender', which in this case was Mr Loser, thought about firing a cannon in a computer game. That signal was sent over the web directly to the brain of Mr Ceballos, known as the 'receiver', whose hand twitched, pressed a touchpad and fired the cannon

The researchers from the University of Washington successfully demonstrated that brains could directly communicate with each other using this technology in August 2013.

During these early tests, researchers used brain stimulation to control the hands of another on a keyboard.

To join the brains of University of Washington student Darby Losey and Jose Ceballos, they used electroencephalography (EEG) and transcranial magnetic stimulation.

Mr Losey was connected to an EEG machine, which reads brain activity and sends electrical pulses over the web in one room on the Washington-based campus.

These signals were sent to Mr Ceballos, sitting in another campus half a mile away, who was fitted with a transcranial magnetic stimulation coil placed near the part of the brain that controls hand movements.

Mr Losey was then told to think about firing a canon and intercepting rockets launched by a pirate ship on a video game.

Across campus, Mr Ceballos was sitting wearing headphones in a dark room - with no ability to see the computer game - with his right hand positioned over a touchpad.

When Mr Losey thought about firing the cannon, the signals were sent to Mr Ceballos, whose hand then twitched, which pressed the touchpad and fired the cannon. 

But these latest tests have improved the accuracy and effectiveness of the communication, and shown how it could soon be used in real-world examples.

To join the brains of UW student Darby Losey and Jose Ceballos, the research team used electroencephalography (EEG) and transcranial magnetic stimulation.

Mr Losey was connected to an EEG machine, which reads brain activity and sends electrical pulses over the web in one room on the Washington-based campus.

These signals were sent to Mr Ceballos, sitting in another campus half a mile away, who was fitted with a transcranial magnetic stimulation coil placed near the part of the brain that controls hand movements.

Mr Losey was then told to think about firing a canon and intercepting rockets launched by a pirate ship on a video game.

Across campus, Mr Ceballos was sitting wearing headphones in a dark room - with no ability to see the computer game - with his right hand positioned over a touchpad.

When Mr Losey thought about firing the cannon, the signals were sent to Mr Ceballos, whose hand then twitched, which pressed the touchpad and fired the cannon.

In total, three pairs of students took part in the experiment to test the technology’s accuracy across different groups. 

Mr Losey (pictured) was connected to an electroencephalography (EEG) machine, which reads brain activity and sends electrical pulses over the web in one room on the Washington-based campus

These signals were sent to Mr Ceballos, sitting in another campus half a mile away, who was fitted with a transcranial magnetic stimulation coil (TMS) (pictured) placed near the part of the brain that controls hand movements. TMS is a noninvasive way of delivering stimulation to the brain to elicit a response

Researchers found that accuracy varied among the pairs, ranging from 25 to 83 per cent.

Misses mostly were due to a sender failing to accurately execute the thought to send the ‘fire’ command.

The researchers were also able to quantify the exact amount of information that was transferred between the two brains.

The human brain is made up of billions of active neurons that have around 105,600 miles (170,000 km) of combined length.

Every time you have a thought, your brain produces weak but distinct electrical signals corresponding to it.

The electrical impulse is generated by the chemical reaction between neurons, which can be measured.

Recording and deciphering those signals is called electroencephalography (EEG), and it has been medically possible since 1924.

‘The new study brings our brain-to-brain interfacing paradigm from an initial demonstration to something that is closer to a deliverable technology,’ said co-author Dr Andrea Stocco, a research assistant professor of psychology and a researcher at UW’s Institute for Learning & Brain Sciences.

‘Now we have replicated our methods and know that they can work reliably with walk-in participants.’ 

Dr Rajesh Rao, a computer scientist and engineer at the University of Washington who led the work, added: 'Our results show that information extracted from one brain can be transmitted to another brain, ultimately allowing two humans to cooperatively perform a task using only a direct brain-to-brain interface.

'Such devices, which have been long cherished by science fiction writers, have the potential to not only revolutionise how humans communicate and collaborate, but also open a new avenue for investigating brain function.'

A separate research team, from Starlab in Barcelona, Spain, recently published results showing direct communication between two human brains. 

The technology makes it possible to control the body of another person with thoughts - something that Professor Xavier, played by Patrick Stewart (pictured centre) was able to do in the X Men films and comics

This graphic reveals how the process works. Brain signals from the 'sender' are recorded. When the computer detects imagined hand movements, a fire command is transmitted over the internet to the TMS machine, which causes an upward movement of the right hand of the 'receiver'

But that particular study only tested one sender brain, instead of different pairs, and was conducted offline instead of in real-time over the web.

The technology makes it possible to control the body of another person with thoughts - something that Professor Xavier was able to do in the X Men films and comics. 

The UW research team is planning to take the work a step further in an attempt to decode and transmit more brain processes. 

They are hoping to expand the types of information that can be transferred from brain to brain, including more complex visual and psychological phenomena such as concepts, thoughts and rules.

The technologies used by the researchers for recording and
stimulating the brain are both well-known.

Electroencephalography, or EEG, is routinely used by
clinicians and researchers to record brain activity noninvasively from the
scalp.

Transcranial magnetic stimulation is a noninvasive way of
delivering stimulation to the brain to elicit a response.

Its effect depends on where the coil is placed; in this
case, it was placed directly over the brain region that controls a person’s
right hand.

By activating these neurons, the stimulation convinced the
brain that it needed to move the right hand.

They’re also exploring how to influence brain waves that correspond with alertness or sleepiness.

Eventually, for example, the brain of a sleepy airplane pilot dozing off at the controls could stimulate the co-pilot’s brain to become more alert.

‘Imagine someone who’s a brilliant scientist but not a brilliant teacher.

‘Complex knowledge is hard to explain - we’re limited by language,’ said co-author Chantel Prat, a faculty member at the Institute for Learning & Brain Sciences and a UW assistant professor of psychology. 

Dr Stocco added: 'We have envisioned many scenarios in which brain-to-brain technology could be useful.

'A skilled surgeon could remotely control an inexperienced assistant’s hands to perform medical procedures even it not on the site, or a skilled pilot could remotely help a less experienced one control a plane during a difficult situation.

'It could help with neuro-rehabilitation. 

'After brain damage, patients need to painfully and slowly re-learn simple motor actions, such as walking, grasping, or swallowing.

'We suspect that the re-learning phase could be greatly sped-up if we could provide the damaged brain with a 'motor template', copied from a healthy person, or the healthy part of the patient's brain, of what the intended action should look like.

Earlier this year, a research team led by the University of Barcelona used EEG headsets to record electrical activity from neurons firing in the brain and send thoughts between participants (pictured). This was used to convert the words ‘hola’ and ‘ciao’ into binary

In the initial test, the greeting was sent from a volunteer, known as an 'emitter' (illustrated left) in Thiruvananthapuram, India to a 'receiver' in Strasbourg, France. There, a computer translated the message and then used electrical stimulation to implant it in the receiver’s mind

The research, published in Plos ONE, was funded by the US Army Research Office and the UW, with additional support from the Keck Foundation.

Earlier this year, a separate research team, led by the University of Barcelona, used EEG headsets to record electrical activity from neurons firing in the brain and send thoughts between participants. 

This was used to convert the words ‘hola’ and ‘ciao’ into binary. 

In the initial test, the greeting was sent from a volunteer in Thiruvananthapuram, India to Strasbourg, France. 

There, a computer translated the message and then used electrical stimulation to implant it in the receiver’s mind. 

@highlight

Student, fitted with an EEG cap, successfully controlled the hand of a friend

@highlight

The two students played a game in which cannons had to be fired on-screen

@highlight

‘Sender’ thought about firing a cannon, which moved the hand of a ‘receiver’

@highlight

Students were sat half a mile apart, and brains were connected by the web

@highlight

Receiver’s reaction was immediate and accuracy ranged from 23% to 83%

@highlight

Technology builds on similar research from Spanish computer scientists