By
Marie-louise Olson

PUBLISHED:
  
  
      01:45 EST, 19 December 2013
    
  

 | 
  UPDATED:
  
  
      08:27 EST, 21 December 2013

Two American astronauts will be sent into space this weekend on an urgent mission to repair a broken cooling line that led to the shutdown of several systems at the International Space Station.

Four spacewalks are necessary to replace the pump with a bad valve, NASA said on Wednesday.

But after a spacewalking astronaut nearly drowned in his helmet in July, the space agency has devised a plan to protect its crew when in space: snorkels

Scroll down for video

Space mission: Two American astronauts will be sent into space this weekend on an urgent mission to repair a broken cooling line (file photo)

Near death: Italian astronaut Luca Parmitano nearly drowned in July, when more than a gallon of water leaked into his helmet, filling it like a fishbowl

Italian astronaut Luca Parmitano nearly drowned in July, when more than a gallon of water leaked into his helmet, filling it like a fishbowl, according to Fox News.

NASA says it is now ready should a similar incident happen again.

‘Some smart engineers on the ground said, hey, this looks like a snorkel you’d use for scuba diving,’ explained Allison Bolinger, NASA's lead U.S. spacewalk officer.

NASA realized that a water-line vent tube could be snipped down and attached with Velcro within the spacesuit, between a water restraint valve and the astronaut.

‘This is your last resort … if water is in your suit you can lean down and use this to breathe,’ Bolinger said.

The space agency also installed 
absorptive pads in the back of each helmet, which will soak up any water
 that shows up like a sponge.

The
 spacewalkers have been trained to tilt their heads back periodically to
 test the pad, she said; if it sucks up around 6 and a half ounces of 
water, it will feel “squishy” -- a sure sign of trouble.

‘That’s a sign there is a problem in the EMU and it’s time to come inside,’ Bolinger said.

Rescue mechanism: Allison Bolinger, NASA's lead U.S. spacewalk officer, says the snorkel is the last resort for the astronauts should they get water in their suit

The solutions sound makeshift but the situation is real, though the faulty pump is far from life-threatening, according to Fox.

Astronaut Rick Mastracchio said last week that the station's navigation, lights, toilet and other vital systems still work.

The failed cooling unit is largely affecting the astronauts ability to do science aboard the orbiting space base, explained Dina Contella, ISS flight director.

The space station cooling system, which runs ammonia through the lines, is critical for dispelling heat generated by on-board equipment - mainly science projects at present.

‘The pump is actually running, but can’t integrate with internal water loop,’ Contella said. ‘We’re running cold, that’s the issue. We want to be able to close the valve and we can’t do it.’

When half of the station's cooling system shut down last Wednesday, it forced the six-man crew to turn off all nonessential equipment, including some science experiments. Because of the valve failure, one of the two cooling lines became too cold.

Space station: The failed cooling unit is largely affecting the astronauts ability to do science aboard the orbiting space base, which is why two spacewalkers are being sent out there to replace the fault valve

While the astronauts are safe and comfortable, NASA wants the system back up to full strength, in case of another failure that could leave the orbiting outpost even more vulnerable than it is right now.

Flight controllers tried in vain to fix the valve remotely, then came up with a plan to use another valve to regulate the temperature.

Some success was reported, and for a while, engineers thought the space station could limp along with the short-term solution. Instead managers have opted for spacewalks right now.

‘It’ll take about three [spacewalks], it could be less if we get lucky … or more if we’re not lucky,’ said Mike Suffredini, International Space Station program manager.

This is the same pump that was replaced by a pair of spacewalking astronauts in 2010, although different things malfunctioned at the time -- that was the pump itself, now it’s just a valve. But three spacewalks were needed then as well.

Potential danger: Mike Hopkins, one of the astronauts to be sent into space this weekend, will be wearing the very same suit that nearly flooded on spacewalker Parmitano

Mastracchio and astronaut Michael Hopkins trained for just such a repair before rocketing into orbit.

They have been prepping all week, just in case of just such a decision.

The potential risk of a flooded space helmet is very real, however; in fact, Mike Hopkins will be wearing the very same suit that nearly flooded on spacewalker Parmitano.

NASA has scrubbed the suit, added new parts to it, notably a fan pump separator, and considers it as good as a brand new one.

‘We think that’s an extremely clean suit and it's ready to go,’ Bolinger said. ‘We have high confidence that it’s essentially just like a unit that was refurbished on the ground.’

@highlight

Two American astronauts will be sent into space this weekend on an urgent mission to repair a broken cooling line

@highlight

A pump with a bad valve caused the shutdown of several systems at the International Space Station

@highlight

A spacewalking astronaut nearly drowned in his helmet in July, so NASA has given its crew snorkels in case it happens again

@highlight

One of the Americans will be given the same suit as the one worn in the July incident

@highlight

The space station cooling system is critical for dispelling heat 
generated by on-board equipment - currently that is mainly science projects