Many people say the first thing they'd do if they won the lottery would be to buy their own private island and move away from the rest of humanity.

Now house-hunters have the chance to do just that, after an Orkney isle off the north coast of Scotland went up for sale for £600,000.

The island of Hunda, which lies about 25 miles north east of the mainland port of Thurso, has no habitable property.

The uninhabited Orkney isle of Hunda, which is connected to the neighbouring island of Burray by a causeway, has gone up for sale for £600,000

Although there are no habitable buildings on the island, potential buyers get a six-bedroom farmhouse on the neighbouring isle of Burray

But its six-figure sale price does include a five-bedroom farmhouse on the neighbouring island of Burray, which is connected to Hunda via a causeway.

Plans have also been lodged to build a house on the isle, although, with no mains connection, electricity would have to be generated by building a wind turbine or bringing in a generator.

The asking price also includes a plot of land on Burray, a workshop, two livestock sheds, sheep handling pens and a variety of derelict cottages that could be transformed into homes.

Hunda and the farmhouse is currently owned by farmer George Rouse, who inherited it from his father George senior. He is now selling it so he and his wife can retire.

Mr Rouse, 71, said: 'I inherited the property from my father who was posted to Orkney with the army after the Second World War.

'He came up here in the late 1950s. After he worked here he was posted to Indonesia in 1957 and in that time he started looking for land up here in Orkney, and our local bank purchased the land on behalf of my father.'

The current owner, farmer George Rouse, says the island offers fantastic views of the surrounding coastline and marine wildlife such as whales and seals

The island comes with a plot of land on neighbouring Burray, a workshop, two livestock sheds, sheep handling pens and a variety of derelict cottages

He added: 'Until that point, we had been living on a house boat. I was 13 at the time so living in a house was quite a change but the area is beautiful and I soon got used to it. After Indonesia he started farming and that's how I got into it.

'I inherited it when my father passed away and I have enjoyed living here but my wife and I are looking for a change of scenery and we need to capitalise our pension. There's a strong sense of community here and you get to know everybody.

'There's a small school with just seven pupils and it's a fantastic place for children, it's a safe area and a great place to live.

'We get a lot of marine mammals like seals and occasionally some whales, but there are no foxes, badgers, snakes, or anything like that. It would be perfect for someone who lives in a big city like London and is looking for a change.'

A spokesman from estate agent Savills, who are handling the sale, said: 'Orkney has long been regarded as a very desirable place to live on account of the quality of life the islands offer and the strong sense of community.

'Hunda lies on the south western shores of Burray, in a beautiful and unspoilt corner of the island, at the end of a public road.

'This sale presents an unusual opportunity to acquire a coastal farm which includes its own private island linked by a causeway.'

The current owner says potential buyers will enjoy a close connection with those in the surrounding community and the islands are a great place to bring up children

The picturesque island, which is situated 25 miles from the port of Thurso, is accessed from Burray via a stone causeway (right)

@highlight

Island of Hunda off the north coast of Scotland goes up for sale - despite containing no habitable homes

@highlight

Asking price does include a farmhouse on a neighbouring isle, which is connected to Hunda by a causeway

@highlight

The isle also has no power supply and potential owners would have to bring in a generator or build wind turbine

@highlight

But current owner says the location offers incredible views of surrounding coastline and abundant wildlife