By 
Damien Gayle

PUBLISHED:

04:27 EST, 13 March 2013


| 

UPDATED:

07:20 EST, 13 March 2013

Japan has become the first country in the world to succeed in extracting methane gas from a previously untapped off-shore fossil fuel resource that has been dubbed 'fire ice'.

Methane hydrate, a sherbet-like substance buried beneath continental shelves around the world, has been tipped by energy experts to be the next major energy resource.

Consisting of methane trapped in ice, it was previously believed to only exist in the outer reaches of the solar system - but now scientists are saying it could be 'the new shale gas'.

Fire ice: Balls of methane hydrate are set 
alight as part of a demonstration. Japanese scientists have become the first to work out how to extract pure gas 
from the substance found under the continental shelves

State-run Japan Oil, Gas and Metals National Corp (JOGMEC) said the gas was tapped from deposits of methane hydrate near the country's central coast.

Japan, which imports nearly all of its energy needs, has since 2001 invested several hundred million pounds in developing technology to tap methane hydrate reserves off its coast.

Japan is the world's top importer of liquefied natural gas and the lure of domestic gas resources has become greater since the Fukushima nuclear crisis two years ago triggered a shake-up of the country's energy sector.

Japan's trade ministry said the production tests will continue for about two weeks, followed by analysis on how much gas was produced.

It is hoped that they can achieve commercial production within six years.

'The new shale gas': An aerial view shows deep-sea drilling vessel "Chikyu" in the Pacific, off Aichi Prefecture, central Japan, as it hunts for methane hydrate reserves to exploit

Gas flames expelled from a burner on the Chikyu: Methane hydrate, a sherbet-like substance buried beneath continental shelves around the world, has been tipped by energy experts to be the next major energy resource

Methane is a major component of 
natural gas and governments including Canada, the U.S., Norway and China
are also looking at exploiting hydrate deposits as an alternative 
source of energy.

In 
February last year UK government ministers and experts suggested that 
massive quantities methane hydrate could also be locked beneath the 
coast of western Shetland.

Energy
Minister Charles Hendry said at the time that the government believes 
it is ‘possible’ that the substance is buried in Scottish waters.

‘The presence of methane hydrates in deep waters west of Shetland is possible, but has not been established,' he said.

'In
the absence of any commercial technology for exploiting such resources,
no estimate of reserves can be made at the present time.’

That could be about to change thanks 
to the new method developed by Japanese scientists to extract gas from 
methane hydrate reserves off their country's coast.

Methane hydrate is formed within marine sediments or beneath permafrost where chemical reactions or microbes break down organic matter to produce gas which then freezes under high pressure

Distribution of known and suspected methane hydrate accumulations around the globe: It has been tipped by energy experts to be the world's next major energy resource

Methane hydrate has long been regarded by oil and gas companies as a nuisance, because it can block marine drilling rigs.

The substance is formed within marine sediments where the gas is generated by chemical reactions or by microbes breaking down organic matter.

The gas then works its way up to the sea bed where sediments tend to be much cooler.

The cooling allows the methane molecules to form weak chemical bonds with the surrounding water molecules, producing solid methane hydrate.

However, such bonds also require high pressure - so methane hydrate forms only in deep water.

Engineers used depressurisation to turn methane hydrate to methane gas, a process thought by the government to be more effective than using the hot water circulation method the country had tested successfully in 2002.

In 2008, JOGMEC successfully demonstrated for the first time a nearly six-day continuous period of production of methane gas from hydrate reserves held deep in permafrost in Canada, using the depressurisation method.

Methane hydrate, is formed from a mixture of methane and water under certain pressure and conditions.

A Japanese study has estimated the existence of at least 40trillion cubic feet (1.1 trillion cubic metres) of methane hydrates in the eastern Nankai Trough off the country's Pacific coast

That's estimate to equal about 11 years of Japanese gas consumption.

Japan's LNG imports hit a record 87.3million tonnes last year after Japan shut down most of its nuclear power plants following the Fukushima nuclear disaster two years ago.

@highlight

Methane hydrate has been tipped as the next major energy resource

@highlight

It was previously believed to exist only in outer space

@highlight

But scientists say there is enough near Japan for 11 years' gas usage