New DNA technology could help reveal the killer in an unsolved murder of a mother and her three-year-old daughter. 

The technique, known as Snapshot, can generate a digital mugshot of the suspect by using samples such as blood and strands of hair left at the scene. 

Investigators in South Carolina have used the analysis, generated by Parabon Nanolabs, in a bid to get a breakthrough in the slaying of Candra Alston, 25, and her toddler Malaysia Boykin four years ago.

Their bodies were found in the busy Brook Pines Apartments in Columbia on January 9, 2011. 

Unsolved: Investigators in South Carolina are hoping the DNA technique called Snapshot, generated by Parabon Nanolabs, leads to a breakthrough in the slaying of  Malaysia Boykin, three, and Candra Alston four years ago. There were no witnesses to their deaths in January 2011

Leads: There were no signs of forced entry at their home and police believe the toddler and her mother may have known the killer. More than 200 people have been interviewed in connection to their deaths 

Police have never revealed how they died and would only confirm it was by different means.  

There were no signs of forced entry - leading detectives to believe they knew the killer or killers. 

The only piece of evidence left at the scene was an unspecified DNA sample that has, until now, been untraceable.  

As there were no witnesses, authorities turned to the forensic phenotyping and found the suspect was dark-skinned with brown hair and brown eyes.

However the computer-generated image does not have an estimated height or age - traits which the company claim are 'very complex'.

Speaking to Fox News, Parabon's director of bioinformatics, Ellen McRae Greytak, said: 'This is particularly useful when there are no witnesses, no hits in the DNA database and nothing to go on.

Prediction: Using the phenotyping technique, investigators have been able to determine that the suspect is dark-skinned with brown eyes and brown hair 

'Traditional forensic analysis treats DNA as a fingerprint, whereas Snapshot treats it as a blueprint -- a genetic description of a person from which physical appearance can be inferred.

'Traits are generally predicted with more than 80 percent confidence, and importantly, Snapshot also reports which phenotypes can be excluded with more than 95 per cent confidence.'

Mark Vinson, a cold case investigator with the Columbia police department, said that more than 200 people were interviewed in connection with the mother and daughter's death.

Around 150 of them submitted their DNA - but none matched the sample left at the scene.  

 

@highlight

Technique known as Snapshot can create a digital mugshot using samples

@highlight

Traits such as skin and hair color can be predicted using hair and blood   

@highlight

Could lead to breakthrough in case of Candra Alston and Malaysia Boykin

@highlight

Bodies were found in their South Carolina apartment in January 2011  

@highlight

Only piece of evidence found was an unspecified DNA sample 

@highlight

Using the technology, authorities have been able to determine suspect was dark-skinned with brown eyes and brown hair