Cronyism? A solar energy project backed by Nancy Pelosi's brother has been granted a massive government loan (file picture)

Nancy Pelosi is facing accusations of 
cronyism after a solar energy project, which her brother-in-law has a stake in, landed a $737 
million loan guarantee from the Department of Energy, despite the 
growing Solyndra scandal.

The massive loan agreement is raising new concerns about the use of taxpayers' money as vast sums are invested in technology similar to that of the doomed energy project.

The investment has intensified the debate over the effectiveness of solar energy as a major power source.

The SolarReserve project is backed by an energy investment fund where the Minority Leader's brother-in-law Ronald Pelosi is second in command.

PCG Clean Energy & Technology Fund (East) LLC is listed as one of the investors in the project that has been given the staggering loan, which even dwarfs that given to failed company Solyndra.

Other investors include one of the major investors in Solyndra, which is run by one of the directors of Solyndra.

Steve Mitchell, who served on the board of directors at the bankrupt energy company, is also managing director of Argonaut Private Equity, which has invested in the latest project.

Since Solyndra has filed for bankruptcy has been asked to testify about the goings on at the firm by two members of the House and 'asked to provide documents to Congress'.

Generator: Artist's impression of the solar plant being constructed north west of Tonopah, Nevada

The artist's impression shows the 
incredible size of the giant solar power plant, which is being 
bankrolled by President Obama's green jobs fund.

Energy will be generated using 
concentrated solar power technology, in which a series of mirrors direct
 sunlight to a receiver at the centre of the plant.

The 'solar tower' in the middle, which will be taller than the Washington Monument, is the first of its kind to be built.

Stretching out across a plain in Tonopah, Nevada, the mind-bogglingly big project will generate enough electricity to power 43,000 homes.

But the joint announcement by Energy Secretary Steven Chu comes just two days after the doomed Solyndra project, which cost the taxpayer $528 million from the same cash pot, was meant to be completed.

The loan agreement comes as questions are raised about the effectiveness of solar power as a major energy source.

Although solar energy plants are typically comparatively cheap to operate, they are extremely expensive to build.

The proposed Nevada plant, which will provide power for 43,000 homes, is receiving a $737 million taxpayer loan, as well as private investment.

The low amounts of power generated by solar energy plants has also been criticised. To replace existing energy sources with solar plants would take up large amounts of land and cost vast amounts of money.

The project approval came as part of $1 billion in new loans to green energy companies yesterday.

Republican critics of the President 
Obama's solar energy program have voiced their outrage at the new loans 
while the Solyndra scandal is still being investigated.

They have raised concerns that the Department of Energy is rushing through the approval of loans before stimulus funds expire on Friday.

While the departments insists 
the projects are being properly vetted, some lawmakers have written to express concern that they vast loans are not being adequately scrutinised.

'The administration’s flagship project Solyndra is bankrupt and being investigated by the FBI, the promised jobs never materialised, and now the Department of Energy is preparing to rush out nearly $5 billion in loans in the final 48 hours before stimulus funds expire — that’s nearly $105 million every hour that must be finalised until the deadline,' said Florida representative Cliff Stearns, who is chairman of the investigations subcommittee of the House Committee on Energy and Commerce.

Tom Schatz, 
president of Washington-based 
advocacy group Citizens Against Government Waste, said: 'It is time for a full audit of their 
activities, their management and their results.

'Candidly,
 it might be time for the federal government to rethink the whole idea 
of loan programs.'

Energy Department spokesman Damien 
LaVera said the project, which was had extensive reviews that included 
scrutiny of the parent companies' finances.

Investigation: Solyndra CEO Brian Harrison and Chief Financial Officer Bill Stover are sworn in at a House Oversight and Investigations subcommittee hearing

The shocking scale of spending Solyndra  lavished on the factory it started building alongside Interstate 880 in Fremont, California, has been revealed.

When it was completed at an estimated 
cost of $733 million, including proceeds from the company's $535 million U.S. loan 
guarantee, it covered 300,000 sq ft, the equivalent of five 
football fields.

It had robots that whistled Disney tunes, spa-like showers with liquid-crystal displays of the water temperature, and glass-walled conference rooms.

John Pierce, 54, a San Jose resident who worked as a facilities manager at Solyndra, said: 'The new building is like the Taj Mahal.'

Designed to make far more solar panels than Solyndra got orders for, the site is now empty and U.S. taxpayers may be stuck with it.

Solyndra filed for bankruptcy protection on September 6, leaving in its wake investigations by Congress and the FBI.

Mr Chu said the two projects will create about 900 construction jobs and at least 52 permanent jobs.

He
 added: 'If we want to be a player in the global clean energy race, we 
must continue to invest in innovative technologies that enable 
commercial-scale deployment of clean, renewable power like solar.'

The
 110-megawatt Crescent Dunes project will use the sun’s heat to create 
steam that drives a turbine, SolarReserve, which is based in Santa 
Monica, California.

Senate
 Majority Leader Harry Reid is a strong supporter of the Nevada project,
 which he says will help his state's economy recover. Former Governor 
Jim Gibbons, a Republican, also supported the project.

Mr Pelosi is one of several controversial figures set to benefit from the huge loan agreement.

The
 loan approvals came just two days before the renewable energy loan 
program approved under the 2009 economic stimulus law is set to expire. 
At least seven projects worth more than $5 billion are also waiting to be approved.

California-based solar panel maker
 Solyndra Inc went bankrupt after receiving its money and laid off 1,100
 workers. The firm is now under investigation by the FBI.

It was the first renewable-energy 
company to receive a loan guarantee under a stimulus-law program to 
encourage green energy and was frequently touted by the Obama 
administration as a model.

President Barack Obama visited the 
company's Silicon Valley headquarters last year, and Vice President Joe 
Biden spoke by satellite at its groundbreaking ceremony.

Since then, the company's failure has become an embarrassment for Obama.

Nut
 Scott Crider, a spokesman for Sempra Generation, a Sempra Energy 
subsidiary that is developing the Arizona project, said its loan 
guarantee was not as risky as the Solyndra loan.

Most
 important, the project has a 20-year agreement with Pacific Gas & 
Electric Co. to buy power supplied by the solar plant, he said

Mr
 Crider claimed the purchase agreement is a key element of the project 
and will 'provide assurance that there are sufficient revenues in place 
to support the loan guarantee'.

A
 similar agreement is in place in Nevada. NV Energy, the state's largest
 electric utility, has agreed to buy power from the Tonopah tower, which
 will connect to NV Energy's power grid.

 

@highlight

Obama administration approved $1bn in green energy loans days after failed Solyndra project due to be completed

@highlight

$737m handed to Crescent Dunes project in Tonopah, Nevada, for 110-megawatt desert solar power plant

@highlight

Investors include firm Minority leader's brother-in-law and major Solyndra stakeholder

@highlight

Republicans warn Energy Department is 'rushing' $5bn in loans ahead of Friday deadline