Hundreds of viewers have complained that Ed Miliband was given a harder time in the first TV contest of the election campaign.

TV watchdogs were inundated with complaints as senior Labour figures accused presenter Kay Burley of intervening 'aggressively' on the Labour leader as he took questions from the studio audience.

But Burley brushed off the criticism, insisting she thought Mr Miliband 'did brilliantly' during the programme, as polls showed David Cameron secured a narrow victory over his opponent.

Hundreds of people have lodged complaints with TV watchdogs that Kay Burley and Jeremy Paxman were biased against Ed Miliband

Mr Cameron and Mr Miliband faced the wrath of voters - and Jeremy Paxman - last night as they were forced to defend their broken promises, judgement and ability to lead the country in the first prime-time TV contest of the general election.

They were interviewed by Paxman for 18 minutes each, and also took questions from a studio audience with Ms Burley acting as moderator on the show broadcast on Sky News and Channel 4.

This afternoon Ofcom had received 254 complaints  - all of which were about perceived bias against the Labour leader.

It is thought they have been generated by a social media campaign sharing a link to the watchdog's website and urging people to complain. 

An Ofcom spokesman said: 'We are assessing the complaints before deciding whether or not to investigate.'

A Channel 4 spokeswoman said it had received around 300 complaints, but was unable to say specifically what they were about.

'Both politicians, one of whom is likely to be the next Prime Minister, agreed to the format and were prepared for and actively participated in robust questioning about their policies and abilities. Neither party has expressed any dissatisfaction to Channel 4,' she added. 

Labour insiders privately noted that they thought Burley 'intervened and followed up aggressively a number of times'.

At one point Burley told Mr Miliband: 'That's a politicians answer there isn't it?' She also pressed him on the impact of his leadership victory over his brother David.

When the Labour leader said family relations had been strained, Burley responded: 'Your poor mum.' In a series of posts on Twitter, Burley took on her critics. 

Burley took to Twitter to hit back at her critics online, insisting she thought Mr Miliband 'did brilliantly with the audience'

While Mr Cameron was asked about treating the elderly with dignity and the depth of spending cuts, Mr Miliband faced a series of aggressive questions.

The Tory leader's first question from the audience was: 'What do you think are Ed Miliband’s best qualities?'

One of the few off-the-cuff questions from Burley to the PM was: 'Have you ever had three shredded wheat?'

When Mr Miliband face the audience, he was frist asked: 'You sound gloomy most of the time, are things really so bad?'

Another asked: 'Do you not think that your brother would have done a better job? He was better qualified and better positioned.'

Paxman suggested that even Labour MPs considered Miliband a 'liability' and that he was seen as 'a north London geek' by many voters, who thought: 'What a shame it's not his brother'

Mr Miliband faced a difficult ride time from both the studio audience and Paxman about whether he is tough enough to lead the country

Former England footballer Stan Collymore said Burley 'Virtually gave Dave a hug and a kiss. Embarrassing.'

Mocking him for not using her Twitter handle, she hit back: '@StanCollymore Stan, its @KayBurley if you need to slag me off directly. Surely you remember from when your were direct messaging me.'

The live 90-minute show, called Cameron & Miliband Live: The Battle For Number 10 pulled in an average audience of 2.6 million viewers on Channel 4 and a further 322,000 on Sky News.

Channel 4 boss Jay Hunt described the show as 'vintage Paxman'. 

During the Q&A Mr Miliband was challenged over why he is so gloomy, out of touch and not as good as his brother.

A snap poll showed 54 per cent of people thought Mr Cameron won on the night, with 46 per cent backing Mr Miliband.

In the ICM poll for the Guardian, Mr Cameron narrowly beat Mr Miliband on having the best arguments, seeming more convincing and having the more appealing personality. 

But out of those who said they may change their minds on which way to vote, 56 per cent said they could move to Labour against just 30 per cent for the Conservatives.

The two men vying for the keys to Number 10 on May 7 did not go head-to-head but instead appeared separately to be interviewed by Paxman and questioned by an audience of voters. 

Jeremy Paxman appears to scratch his head mid-way through interviewing Prime Minister David Cameron 

Mr Miliband was forced to insist that he 'tough enough' to be Prime Minister, including standing up to the likes 

But Mr Miliband faced a difficult ride time from both the studio audience and Paxman about whether he is tough enough to lead the country.

The Labour leader insisted: 'Am I tough enough? Hell, yes, I'm tough enough.'

Paxman suggested that even Labour MPs considered Miliband a 'liability' and that he was seen as 'a north London geek' by many voters, who thought: 'What a shame it's not his brother.'

Paxman told him how he had met a man on the tube who said the Labour leader would not survive an encounter with Putin.

Mr Miliband insisted: 'I don't care. I don't care what the newspapers say.'

Apparently taken aback by the onslaught, Mr Miliband claimed he did not read bad press about himself, adding: 'It's water off a duck's back, honestly.

'The thing I've learnt most in this job is to be yourself. That's what I am. People have to decide - do they want my ideas, do they want my principles when I stood up not just to President Obama, but Rupert Murdoch, the energy companies, the banks, fighting for ordinary people, which is what I believe in and what I came into politics for?'

@highlight

Ofcom receives more than 250 complaints that TV contest was biased

@highlight

All of the viewers claim that show was more aggressive towards Miliband 

@highlight

Kay Burley hits back at critics and insists she thought Ed did 'brilliantly'

@highlight

Jeremy Paxman call Labour leader a 'geek' who knifed his brother 