SEX AND FILM

by Barry Forshaw

(Palgrave Macmillan £19.99)

There was breathless excitement when an immensely raunchy, bestselling novel was adapted for the screen, with overwrought cinema-goers queuing in their droves to see it.

But this was not Fifty Shades Of Grey. This was The Sheik, in 1921. And it starred Rudolph Valentino, whose sex appeal was such that when he died only five years later, aged just 31, some of his more committed female fans responded to the news by killing themselves.

The history of sex on the big screen is about as old as the cinema itself. Barry Forshaw brings it wham, bam up to date, with analyses both of Fifty Shades and a much franker, darker exploration of sexual deviancy, Lars von Trier’s alarming 2013 film Nymphomaniac.

But for me, the real gems in this formidably well-researched and erudite book concern the earlier manifestations of sex on-screen. Or off-screen, in the case of The Sheik, in which a wryly unambiguous caption, ‘After a week of sullen obedience . . . ’, told audiences that Valentino’s desert predator had finally had his wicked way with the headstrong Lady Diana. Like Fifty Shades, the book itself was rather less coy.

The depiction of sex in the cinema has changed hugely over the years, the American film industry was notoriously cautious about what was shown - Jane Russell pictured in a poster for The Outlaw

By the Thirties, coyness was being forced onto Hollywood by increasingly vigilant censors, the so-called Hays Office.

The African jungle was deemed far enough from ‘civilisation’ to be permitted some erotic freedom in Tarzan The Ape Man (1932), in which Maureen O’Sullivan and Johnny Weissmuller wore skimpy outfits, which, from some angles, made them appear naked.

But then, the censors pounced. And by the next film in the series, they had ‘modestly covered Tarzan and Jane in almost comically baggy costumes’.

Unsurprisingly, it was randy Europeans who introduced sex to Hollywood. In Ekstase, a Czech film of 1933, a young Hedy Lamarr is shown in obvious post-orgasmic bliss. The film was duly seized by U.S. Customs and prosecuted for obscenity.

But America couldn’t keep out Marlene Dietrich, and they had their own sex goddess in the hourglass form of naughty Mae West, who had her own way of outfoxing the morality police.

In I’m No Angel (1933), she saucily adjusts her gown and then purrs, ‘Am I making myself clear, boys?’ There was nothing censorable about the line, but nothing wholesome, either.

Not much did get past the Hays Office — including Margaret Lockwood’s cleavage in The Wicked Lady (1945), the first British film to be cut before U.S. audiences were allowed to see it. Forshaw suggests the censors were so distracted by Jane Russell’s gravity-defying embonpoint in The Outlaw (1943) that they missed distinct hints of homoeroticism elsewhere in the film.

Today, the restrictions — no horizontal embraces, no ‘excessive’ kissing, no suggestion of intercourse outside marriage — seem comical.

In Casablanca (1942), there could be no hint of a ‘sex affair’ between Humphrey Bogart and Ingrid Bergman, so audiences had to decide for themselves what he meant when he said: ‘We’ll always have Paris.’ Memories of an outing up the Eiffel Tower? Probably not. In the Fifties and Sixties, such strictures began to crumble — not that the ‘sex comedies’ starring Doris Day and Rock Hudson were anything other than irreproachably conservative, prompting comedian Oscar Levant to say that he’d known Doris Day ‘before she was a virgin’.

Even in Britain, old censorship habits died hard, with county councils allowed to overrule certificates dished out by the British Board of Film Classification, as several did with Saturday Night And Sunday Morning (1960), on the grounds that Albert Finney’s priapic, working-class hero was an affront to the reputation of decent factory workers.

Throughout cinematic history, of course, the greater the puritanical outrage generated by a film, the more people have wanted to see it.

That was notably so of Bernardo Bertolucci’s film Last Tango In Paris (1972), starring Marlon Brando — and it also ‘possibly helped the sales of a certain kitchen commodity utilised as a sexual lubricant’. Butter, in short.

But Last Tango only pushed at certain boundaries, and obeyed the unwritten law that female nudity is more acceptable than male.

The tumescent penis to this day is not often seen in mainstream cinema (indeed, in Fifty Shades Of Grey, Jamie Dornan’s Christian seems to have no genitalia at all).

Forshaw offers one good explanation: limp apparatus in a sex scene would give the game away — the game being the many cameramen, boom operators and make-up artists who, by all accounts, make genuine arousal on a film set a near-impossibility.

Forshaw’s book is a work of scholarship, not gossip, but that doesn’t stop him dropping mischievous references to the rampant ironies yielded by more than a century of sex on the screen.

The thoroughly chaste Brief Encounter (1945) is often cited by moralists as a perfect example of how romance can be depicted without sex, but Forshaw notes gleefully that the film’s director, David Lean, was well-known for his energetic promiscuity, and its writer, Noel Coward, for his homosexuality.

An acquaintance of mine told me years ago that he’d once checked in at the Palace Hotel in St Moritz behind Noel Coward and his long-time companion, Graham Payn, and that Coward startled the stiff, Swiss receptionist by fruitily announcing himself and Payn as ‘Mr and Mrs Noel Coward’.

His was a very different world to that of Brief Encounter.

But then, sex on screen — or the lack of it — has always unfolded in a parallel universe. That’s the magic of the movies.

 

@highlight

The depiction of sex on the big screen has changed hugely over the years

@highlight

Censorship in American cinema was notoriously restrictive 

@highlight

In his new book Barry Forshaw explores Fifty Shades and others