By 
David Mccormack and Associated Press Reporter

PUBLISHED:

14:25 EST, 24 July 2013


| 

UPDATED:

15:11 EST, 24 July 2013

Tourism managers for Las Vegas are the latest to jump aboard the bandwagon of brands using the royal birth as a means of generating some cheap publicity for whatever they’re selling.

The Las Vegas Convention and Visitors Authority (LVCVA) expressed its congratulations to Prince George, born on Monday to Prince William and the Duchess of Cambridge, by posting a greeting on Facebook that read, ‘Congratulations on the royal addition. See you in 21 years.’

The wording is of course a cheeky reference to the new born baby’s Las Vegas-loving Uncle Harry who caused quite a stir when he visited Sin City last July.

The Las Vegas Convention and Visitors Authority has expressed its congratulations on the royal birth with a cheeky online marketing campaign

Too young for Vegas: The Duchess of Cambridge and Prince William pose with their new baby son Prince George on Tuesday

The LVCVA estimates that the publicity generated by Prince Harry's infamous trip - which included a scandalous game of strip billiards - was worth the equivalent of $23 million-worth of free advertising.

Little wonder then that the same organization has issued the tongue-in-cheek online ad in an attempt to get some mileage out of the latest addition to the British royal family.

A host of companies haven’t been shy about trying to make a buck from the new Royal birth.

Within hours of the announcement that the Duke and Duchess of Cambridge had welcomed their baby boy into the world on Monday, a raft of companies took to Twitter advertising their brands along with cute messages of congratulation.

Profitable: Prince Harry, pictured partying in a Las Vegas pool, caused a media storm last summer when pictures were published of him naked in a hotel room

The LVCVA exploited Prince Harry's infamous visit last July which they estimate generated the equivalent of $23 million-worth of free advertising for the city

Among the billion dollar firms hijacking the birth of the third in line to the British throne were Coca Cola, Starbucks, Play-Doh, Oreo and Charmin.

It would have been hard to miss the sensationalized media storm that erupted last summer when pictures of a naked Prince Harry in Vegas - with a young lady no less - were leaked to the world's press.

The slightly grainy snap shots were taken on a camera phone during a private party in the five-star Encore Wynn resort and while they didn't do much to enhance Harry's public image, they did wonders for the Las Vegas tourism industry.

The LVCVA estimated that the royal scandal generated an extra $23 million for the city in increased tourism in the months immediately following the incident.

The organization estimates that 154 million people worldwide saw the infamous pics in the two months following Harry's visit.

LVCVA
Board Chairman Tom Collins apparently was heard to say at a 
board meeting not long after the visit: ‘God bless Prince Harry. He made us a bunch of money.’

The organization welcomed almost 40 million visitors last year including more than 330,000 people from the United Kingdom.

Sin City tourism managers are banking on the new royal baby taking after his Las Vegas-loving uncle

@highlight

The Las Vegas Convention and Visitors Authority post the cheeky greeting on Facebook alluding to last year's infamous trip by Prince Harry

@highlight

A host of major brands have sought to get some marketing mileage out of the royal birth

@highlight

The LVCVA estimates that the coverage generated by last July's Harry incident was worth £23m of free publicity