By 
Jack Doyle

PUBLISHED:

06:10 EST, 11 July 2013


| 

UPDATED:

19:27 EST, 11 July 2013

Disgraced: The 15-month jail term handed to former BBC presenter Stuart Hall (pictured) is to be reviewed by the Court of Appeal following complaints that is was unduly lenient

Disgraced BBC presenter Stuart Hall could see his prison sentence increased after it was sent to be reviewed by senior judges.

In May, Hall admitted sexually abusing 13 girls, including one as young as nine.

But to the fury of victims and justice campaigners, he was sentenced to just 15 months’ imprisonment, of which he will serve half – meaning barely two weeks inside for each victim.

The Recorder of Preston, Judge Anthony Russell QC, said he had to sentence Hall, of Wilmslow, Cheshire, according to the guidelines in place at the time of the offences.

But even then the maximum sentence for the most serious offences he committed was five years. Today it would be ten years.

The Government’s most senior law officer, Attorney General Dominic Grieve, was deluged with more than 150 complaints about the sentence.

Mr Grieve, who has the power to send cases to the Court of Appeal if he considers the sentence ‘unduly lenient’, announced yesterday the Hall case would be referred.

A spokesman for Mr Grieve said: ‘Having carefully reviewed this case, the Attorney General, Dominic Grieve QC MP, has decided to refer the sentence of Stuart Hall to the Court of Appeal for review.

Locked up: Hall is desperately scrambling to save his fortune by trying to pay off victims of his sexual abuse, including Susan Harrison (right) with 'paltry' out-of-court settlements

‘The case will in due course be heard
by three Court of Appeal judges who will decide whether or not the 
sentence is unduly lenient and whether they should increase the 
sentence.’

The case is expected to be heard in around six weeks’ time.

When the claims against Hall, 83, first emerged he flatly denied them and protested his innocence.

After he was first arrested last 
December, he told police his victims were all lying as part of a 
‘vendetta going on against people in the public eye’.

But the publicity generated by his arrest led to more victims coming forward with overwhelming evidence of his guilt.

Convicted: The former It's A Knockout presenter is being sued by at least 17 women in relation to harm and injuries they suffered at his hands

The court heard his crimes spanned 
nearly 20 years, between 1967 and 1986, with assaults taking place on 
BBC premises and at his home. He even abused family friends.

On Wednesday, the Mail revealed the 
former It’s a Knockout presenter was trying to pay off his victims with 
‘paltry’ out-of-court settlements.

The multi-millionaire signed over the
deeds of his £2million house to his wife just before he was jailed, and
is now offering those he abused as little as £2,000 to prevent them 
claiming compensation.

At least 17 women are suing him over the harm they suffered at his hands.

Susan Harrison, who was 16 when Hall 
lured her to BBC premises on the false pretext of helping her record a 
song, before attacking her in his car, has been offered just £5,000 in 
an out-of-court settlement.

Shadow attorney general Emily Thornberry said: ‘A sentence of 15 months does not appear to reflect the gravity of his crimes.’

@highlight

Disgraced BBC presenter jailed for 15 months for sex attacks on young girls

@highlight

Attorney General refers case to Appeal Court after receiving 150 complaints

@highlight

Hall is being sued by at least 17 women for harm they suffered at his hands

@highlight

He is trying to offer them 'paltry' out-of-court settlements to avoid claims