The Met Office has warned that Britain could be facing one of its wettest winters ever, amid claims the conditions are perfect for a series of powerful Atlantic storms.

After a mild October, much of the country has been subjected to heavy rainfall in recent days, with some localised flooding, particularly in the south west  - a region among the worst hit by last year's winter floods.

And the latest three-month outlook from the Met Office, which covers November to January, suggests that the next three months will be wetter than average, with weather fronts coming in from the Atlantic ocean, bringing stormy conditions.

Scroll down for video  

Flood risk: The Met Office has warned that Britain could be facing its wettest winter for 33 years, giving rise to fears of flooding in areas hit by last year's winter storms - such as Muchelney in Somerset (pictured)

Jet Stream: Researchers have suggested that the jet stream (pictured), which carries weather systems to the UK from across the Atlantic has become stronger. It is caused when warmer air from over the Gulf Stream  meets colder air from the Artic

Misty morning: British Airways planes can be seen through the fog this morning at Heathrow

'The outlook suggests the continuing risk of our weather coming in from the Atlantic, which brings unsettled conditions, during the first part of the three-month period,' the outlook states.

And while the Met Office experts suggest that more unsettled conditions are typical for autumn, the outlook says 'spells of wet and windy weather may be more frequent than is typical'.

Last year's winter was the wettest ever on record, with the UK hit by 486.8mm of rain between December and February, narrowly above the previous record of 485.1mm set in 1995.

Temperatures are likely to be milder than average for the first part of the outlook, although colder weather is predicted for January, with the outlook adding: 'The risk of occasional colder outbreaks increases later in the period'.

Fog: Parts of the south east got off to a foggy start this morning, with some rain forecast for later

Autumnal feel: Boats moored on the River Nene in Peterborough, Cambridgeshire, this morning

Into the mist: A cyclist crosses the bridge between Overton and Gunwade lakes in Peterborough

Forecast: The start of the week will be unsettled, with rain forecast for Monday, but Tuesday will be drier

Researchers have suggested that the jet stream, which carries weather systems to the UK from across the Atlantic has become stronger, bringing sea temperatures and windspeeds which could lead to a particularly wet winter.

Adam Scaife, professor of applied mathematics at the Met Office, who specialises in modelling longer-term weather and climate patterns, said: 'The rainfall over the last few weeks has already been well above average.

'These storms are generated by the jet stream which also carries them eastwards towards us. The jet stream has recently got stronger and moved north, which could carry weather systems from the Atlantic right over the UK.' 

Last Friday saw Devon hit by winds of 93mph, Wales struck by 75mph gales and Hampshire suffering widespread flooding. 

Singing in the rain: People gather under umbrellas to watch the orchestra perform at the Bournemouth Christmas Market today

Wrapped up warm: A mother and her daughter don their waterproofs and wellies to stay dry in Bournemouth

The outlook's summary suggests that the probability that precipitation during the November to January period will fall into the wettest category is around 25 percent, although this comes with the caveat that the probability of it being in the driest category is 15 percent. 

Jet streams, which can reach speeds of 200mph, are caused by the temperature difference between tropical air masses and polar air masses and steer weather patterns around the globe.

An increased difference in temperature between the cold Artic region and the warm Gulf Stream ocean current and rising wind speed with altitude above the two stretches of water could also lead to storms in the UK.  

Cooler temperatures: People take an afternoon walk along the shoreline at Brighton beach, Sussex, despite the dropping temperatures

Beside the seaside: Although the weather has turned cooler, the beach was still a popular place to be today

Enjoying the view: A couple take time to sit and watch the sea, despite the dark clouds swirling overhead

The potential for these factors to combine, generating UK-bound storms is so great that Professor Scaife and his colleagues are promoting a new term - 'baroclinicity' - to describe it. The word could even be incorporated into TV forecasts.

Prof Scaife added: 'It's a word we might need to get used to - it means we are likely to get more wet and windy weather.'

In the more immediate future, the Met Office forecast for the next month predicts that the west of the country is most likely to see heavier rain and stronger winds, with frost more likely after next weekend. 

Walking the dog: These dog walkers took advantage of a break from the rain to stretch their legs

Sporting chance: A group of friends swapped wellies for shorts for a spot of beach volleyball in Brighton

Determined: Even a spot of rain could not stop this pair from visiting Brighton beach this afternoon

After weekend showers the Met Office told motorists to be wary of the conditions and warned of localised flooding nationwide.

They forecast a 'grey and miserable' rush hour tomorrow morning in the Midlands and east, with most of the UK soaked later.

Fronts originating in the Atlantic will dump 10-20mm of rain in the South-West and West on Wednesday, moving to the South and North on Thursday, and followed by further rain plus gales on Friday and again during the weekend in the West and North, with the East drier but still seeing showers at times. 

Chaos: Workmen fixing a pothole on the M25, which opened up on Friday morning after bad weather hit Leatherhead in Surrey

Met Office forecaster Emma Corrigan said: 'It will be a grey, miserable start on Monday, with an unsettled week ahead, windy at times.

'Parts are saturated and more prone to impacts such as localised water issues.

'Warnings have not issued but that may change, so people should monitor warnings.

'A system pushing in through Monday means rain will be falling in the morning rush hour. People should definitely be aware of the conditions.

'Monday’s rain will affect much of the UK, with heavier bursts and possibly persistent, particularly in the North-East, with 45mph wind gusts.

'An Atlantic band of rain comes in on Tuesday night into Wednesday, with 10-20mm falling.

'Low pressure arriving later on Thursday will affect the South-West and West, with the weekend seeing a front likely to come in from the Atlantic and move across parts of UK, wettest in the West with the East drier.

'Places have been wetter than average in the past week and unsettled weather is expected to continue to the start of December.

'We’ll be able to see how this year might fare compared to previous years when we get the November rainfall statistics at the end of the month.'

Torrential  rain overnight caused floods in some parts of Devon, where several properties in the seaside town of Sidmouth suffered flooding and electrical failure as heavy rain lashed the region from 10pm onwards.

Four people had to be rescued from their car trapped in floodwater in the town, while another driver also had to freed after his car was caught in floodwater at nearby Clyst St George near Woodbury just before midnight.

@highlight

After a mild October much of the country has been hit by heavy rain

@highlight

Met Office three-month outlook suggests more wet weather is to come

@highlight

Weather fronts coming from the Atlantic will bring stormy conditions to UK

@highlight

Temperatures are likely to remain mild, but could get colder in January 