By
Travelmail Reporter

The British countryside, fish and chips and real ale have been hailed among the things we love most about Britain.

A study of 2,000 people found British strawberries, beer gardens and a simple cup of tea all featured high in the top 50.

While the NHS, BBC and of the Queen herself all appeared inside the top 20, and the iconic red bus, the Cornish pasty and William Shakespeare all prompt a surge of pride in Brits.

Top love: The countryside - pictured in Dorset - has been named the number one things we love about Britain

Fry up: The Full English breakfast was ranked number six in the top 50 things we love about Britain

The research, which was commissioned by bookmakers William Hill, saw catching the football on Match of the Day, watching football live at the pub and hosting the Premier League all make the list of things we love about Britain.

And our sporting heritage still causes a surge of pride to this day with the 1966 World Cup win and the hosting of the London Olympics included among the moments that made the average person proud of their country.

A spokesman for bookmakers William Hill said: ‘We might be a small country but we’re a great one and the quirky list of British loves tells you something about our character.

Number 20: Brits voted Buckingham Palace in London in the top 50 things they love about Britain

Traditional British dish: Fish and chips was voted the second thing people love about Britain

1. Countryside2. Fish and chips3. Roast dinners4. Tea5. English history6. The English Fry up7. NHS8. Strawberries9. Lake District10. The beaches11. Cream tea12. Historic architecture13. The BBC14. Beer gardens15. The Queen16. Big Ben17. Proud heritage18. Wimbledon19. Stonehenge20. Buckingham Palace21. Red buses22. Cornish pasties23. Shakespeare24. James Bond25. The Spitfire

26. Winston Churchill27. Good music scene28. Stephen Fry29. Real ale30. Black cabs31. Prince William32. Dame Judy Dench33. Prince Harry34. Harry Potter35. Live football at the pub36. Cricket37. Cider38. Coronation Street39. The Premier League40. Match of the day41. Doctor Who42. Marmite43. Beefeaters44. The Proms45. Rolling Stones46. Unpredictable weather47. The Great British Bake Off48. Stephen Hawking49. Jessica Ennis50. Mr Bean

‘It’s a wide ranging list of food, sights and establishments that instil pride in us and with a proud summer of sport ahead it’s a timely reminder of all the reasons to be happy with where we live.

‘The results showed passion for sport and supporting your country, even against stronger opponents, is a key trait of the British people and the World Cup support will show that.’

With half of the top 10 biggest loves edible, our passion for food never dwindles - roast dinners and cream teas finished higher than The Queen, the study also found.

Nation of royalists?: The Queen, pictured at Paris' Gare du Nord station, was ranked number 15 on the list

Typical English scene: Playing cricket ranks in the top 50 things we love about being British

And Winston Churchill clearly remains an inspirational character and appears on the list, while Stephen Fry, Prince William and Dame Judy Dench are also clearly cherished.

The much-loved adventures of James Bond, Harry Potter and Doctor Who saw them place in the list of Britain’s biggest loves.

While Marmite, cider and even the unpredictability of our weather were also lauded as charming things about the country.

David Beckham, Mo Farah and Banksy all narrowly missed out on the top 50 British treasures.When asked about Britain’s strength, respondents said we are up there with the best in the world for theatre, healthcare and news media.

Best of Britain: A survey into what we love most ranks Stonehenge in 19th place

While over a third thought we punch above our weight in sport as a country.

A massive 78 per cent of the those who were polled said they were proud to consider themselves British.

And six in ten can feel themselves getting swept up in the buzz of the World Cup - 73 per cent said Brits are good at coming together to get behind their team for sporting events.

The William Hill spokesman added: ‘Sport is a huge part of our culture and the buzz generated by the World Cup is tangible.

‘Despite lower expectations we are still seeing significant support for England who are 25-1 to win the world cup and a win would already cost us a couple of million.’

@highlight

Prince William and Harry feature in the results of a survey of 2,000 Brits 

@highlight

Roast dinners, a cup of tea and British strawberries rank in top 10

@highlight

Wimbledon, live football in pubs and cricket also feature