Loft insulation may cut heating bills, but it is responsible for the decline of some of Britain’s most loved birds, a report claims.

By filling in gaps in roofs that leak heat, homeowners are unwittingly reducing the number of potential nesting spaces.

The energy-saving practice has so far contributed to a decline in the number of sparrows and house martins, among other species.

Scroll down for video 

Loft insulation has contributed to a decline in the number of sparrows (stock image) and house martins, among other species over the past 40 years, a new report suggests

The British Trust for Ornithology’s (BTO) BirdTrends report claims that sparrow numbers have dropped by 70 per cent since the 1960s, while starling and house martin populations are half of what they were 40 years ago.

It says that sparrows living in urban and suburban areas have been affected the worst.

Paul Stancliffe, a spokesman for the BTO, told the BBC: ‘As people are becoming more aware and better at insulating their lofts they are inadvertently taking away little nooks and crannies which have historically been used by the sparrow to nest.’

Paul Stancliffe, a spokesman for the BTO, said: ‘As people are becoming more aware and better at insulating their lofts (stock image)they are inadvertently taking away little nooks and crannies which have historically been used by the sparrow to nest.’

The report claims that sparrow numbers have dropped by 70 per cent since the 1960s (shown by this graph), while starling and house martin populations are half of what they were 40 years ago

The report summarises population trends for 120 breeding bird species across Britain & Ireland using data collected by volunteer surveyors.

It provides habitat-specific trends for many species, highlighting those environments where species are in trouble.

It says that many widespread and formerly common birds are experiencing severe declines, while targeted conservation is helping rare birds.

A total of 28 species – a quarter of those surveyed – have suffered a fall in numbers of greater than 50 per cent over the last 35-45 years.

As house martins also nest in holes, he believes they could have suffered because of insulation, as well as other factors such as less food at winter and people tidying up their gardens. 

Mr Stancliffe has recommended that people put up a nest box with a 32mm entrance as an alternative nesting space to holes in a roof.

However, a lack of nesting sites does not explain why some bird species are struggling, because sparrows have also disappeared from areas with plenty of suitable sites.

‘This implies that other factors are probably involved,’ Mr Stancliffe said.

The report suggests that many birds may benefit from help, as it found that 28 species were have been in decline over the past 40 years, including skylarks and cuckoos.

John Marchant, co-author of the report, said: ‘The range of garden birds experiencing population declines appears to be increasing.’ 

As house martins also nest in holes constructed on ledges and nooks, the expert believes they could have suffered because of insulation, as well as other factors such as less food at winter

‘While many will be familiar with the disappearance of house sparrow, starling and spotted flycatcher, it may surprise people to know that house martin, mistle thrush and greenfinch are heading in the same direction.

‘Again, there is evidence that house martin and mistle thrush declines are most pronounced around human habitation. The BTO will be launching a volunteer house martin survey in spring 2015 to find out more about the current distribution of breeding populations.’

However, the population of 18 birds such as magpies and wood pigeons doubled over the period.

Mr Stancliffe explained: ‘Because these birds are generalists and not tied to specific habitats it allows them breed over wider parts of the country and therefore they are doing much better.’ 

Home owners can put up bird boxes to give sparrows and house martins places to nest, particularly if they have had their lofts insulated.

Dave Leech, a Senior Research Ecologist at BTO said that more data is needed to help experts pinpoint specific problems and volunteers can help.

So far, information generated by ringing birds and monitoring their nests has been used to find that the majority of farmland bird declines were driven by a reduction in food availability during the winter, while garden birds such as house starlings and greenfinches have been hit by a combination of reduced winter food availability and disease. House sparrows are struggling to rear enough chicks.

‘Data gathered by BTO ringers and nest recorders will help us to identify the mechanisms underlying declines of other species,’ he said.

 

@highlight

Sparrow population has dropped by 70% because of lack of nesting sites

@highlight

Loft insulation is also thought to have halved house martin populations

@highlight

A total of 28 species living in Britain have been in decline over the past 40 years, including skylarks and cuckoos, but 18 have flourished

@highlight

 British Trust for Ornithology’s report says magpie population has doubled