The infrasonic shockwave caused by the explosion of the meteor which slammed into central Russia nearly a fortnight ago was the loudest sound ever recorded by the global nuclear testing watchdog.

Seventeen listening stations operated across the world by the Comprehensive Nuclear-Test-Ban Treaty Organisation (CTBTO) detected the sound wave as it traversed the planet.

The furthest station to record the sub-audible sound was more than 9,000 miles away in Antarctica.

Loudest ever infrasonic shockwave: This imge from a Russian driver's dashboard camera shows the explosion caused as a meteorite burned up in the atmosphere over central Russia a fortnight ago

Almost 1,200 people were injured when the untracked lump of space rock exploded over the Urals at 03.22 GMT on February 15, with the debris narrowly missing a direct and devastating hit on the industrial city of Chelyabinsk

Estimated by Nasa to have been 55ft-wide and with a weight of some 10,000 tons, the meteor is thought to have exploded above the Ural mountains with a force equivalent to about 500kilotons.

That makes its impact nearly 25 times more powerful than the atom bomb dropped on Nagasaki in 1945.

The low frequency waves emitted by the gargantuan blast were not audible to the human ear, but were recorded by the CTBTO's network of sensors as they travelled across continents.

Global tracking system: This Google Earth image has lines drawn to the 17 infrasound stations in the CTBTO's network that detected the infrasonic waves from the meteor as it broke up over Russia's Ural mountains

'We saw straight away that the event 
would be huge, in the same order as the Sulawesi event from 2009,' said 
Pierrick Mialle, an acoustic scientist with the agency.

'The observations are some of the largest that CTBTO's infrasound stations have detected.'

Until
 last week, the meteor explosion above Sulawesi, Indonesia, in October 
2009 was the largest infrasound event registered by 15 stations in the 
CTBTO's network.

Infrasound has been used as part of the CTBTO's tools to detect atomic blasts since April 2001 when the first station came online in Germany.

Data from the stations is sent in near real time to Vienna, Austria, for analysis at the CTBTO's headquarters. Both the raw and analysed data are provided to all Member States.

'We saw straight away that the event would be huge': A visual representation of the infrasonic shockwaves generated by the fireball, as recorded by the infrasound listening station in Kazakhstan

Questions are being asked as to why Russia's powerful missile defence radar systems did not detect the meteorite that exploded over the country this month.

In the aftermath of the impact Russian politicians called on the world's powerful nations to urgently develop technology to spot asteroids and meteorites that threaten our planet.

But with Russia having one of the most high tech early warning systems of any nation on Earth, many are wondering why the nuclear superpower was not able to detect the incoming object itself.

Experts from the Russian Nuclear Forces Project have claimed that despite the size of the meteor, early warning radars 'never had a chance' - since they were never designed to detect rocks hurtling in from outer space.

The group published an image, above, showing how far into space the country's radar systems can penetrate.

A project researcher writes: 'As can be seen from the picture, the meteorite was out of the field of view of the Pechora radar and it was below the horizon as seen from Moscow, so the Don-2N radar could not see it either.

'The Dnepr radar in Mishelevka might have detected the meteorite if it looked up, but it didn't - as an early-warning radar its mission is to search the narrow strip of space just above the horizon, which a ballistic missile would cross if it ever comes.

'They don't (and shouldn't) much care about anything else.'

'We know it's not a fixed explosion 
because we can see the change in direction as the meteorite moves 
towards the earth,' said Mr Mialle.

'It's
 not a single explosion, it's burning, travelling faster than the speed 
of sound. That's how we distinguish it from mining blasts or volcanic 
eruptions.

'Scientists all 
around the world will be using the CTBTO's data in the next months and 
year to come, to better understand this phenomena and to learn more 
about the altitude, energy released and how the meteor broke up.'

There are currently 45 infrasound stations in the CTBTO's network that measure micropressure changes in the atmosphere generated by infrasonic waves.

Like meteor blasts, atomic explosions produce their own distinctive, low frequency sound waves that can travel across continents.

Infrasound is one of four technologies (including seismic, hydroacoustic and radionuclide) the CTBTO uses to monitor the globe for violations of the Comprehensive Nuclear-Test-Ban Treaty that bans all nuclear explosions.

Seismic signals from the meteor were also detected at several Kazakh stations close to the explosion and impact area.

Days before the meteor, on February 12, 2013, the CTBTO's seismic network detected an unusual seismic event in the Democratic People's Republic of Korea (DPRK), which measured 4.9 in magnitude.

Later that morning, the DPRK announced that it had conducted a nuclear test.

The event was registered by 94 seismic stations and two infrasound stations in the CTBTO's network.

The data processing and analysis are designed to weed out natural events and focus on those events that might be explosions, including nuclear explosions.

@highlight

Furthest listening post to detect blast was 9,000 miles away in Antarctica

@highlight

Explosion above city of Chelyabinsk on February 15 hurt more than 1,200

@highlight

Low frequency infrasonic shockwave was not audible to the human ear