A futuristic trimaran yacht designed by London-based architect Dr Margot Krasojevic will operate 100 per cent self-sufficiently with power generated by solar panels on the wingsail and cost an estimated £9-£10million.

The Fresnel Hydrofoil Trimaran, set for construction starting April this year, has been designed for Holden Manz wine estate in Franschoek, South Africa.

Dr Krasojevic, who splits her time between London, Beijing and Belgrade, says the clients are racing fans, but will also use the yacht for cruising.

The boat’s most striking feature is a carbon fibre sail frame that curves around to form part of the hull, with a retractable Kevlar sail. The wing sail features solar panels that collect the sun's rays, helped by fresnel lens and holographic film on the outrigger that project further rays on the panels. 

The Fresnel Hydrofoil Trimaran is a solar-powered, perpetual motion yacht designed by Dr Margot Krasojevic

The sail's frame is a mechanical structure similar to an airplane wing made of carbon fibre with a retractable Kevlar sail

The yacht has a folding wingsail that allows a more efficient lift to drag ratio

'The fresnel lens and holographic film clad outrigger has never been used before as a means of running off concentrated solar power along with the form of the main hull, which acts as one unit,' Dr Krasojevic tells MailOnline.

'The wingsail (the main rigid sail) wraps into the main body of the hull so it is a continuous surface which, as a result of the motorised mast, can change the shape of the sail allowing it to catch more wind. This also hasn’t been done before.' 

When there is sun and no wind, the solar cells can be turned upwards to catch rays while when there’s wind it harnesses the best of both forms of energy. 

The double section vacuum bonded PVC-constructed outrigger hulls are detachable from the main hull 

'The trimaran harnesses wind, solar and kinetic energy to run the motors as and when necessary,' says Dr Krasojevic

When in monohull mode, a set of fold-out hydrofoils can be deployed to lift the main hull out of the water, reducing water resistance by up to 80 per cent and creating a faster and smoother ride.

‘The yacht attempts to run self sufficiently,’ Dr Krasojevic says. ‘The smart materials and vacuum formed PVcU cladding is currently being tested for solar efficiency with the aim of starting build in April 2015.

‘The boat transforms from racing multihull Trimaran to a cruise boat for leisure it harnesses renewable energy to run its motors. 

When in monohull mode a set of fold-out hydrofoils can be deployed to lift the main hull out of the water

The outrigger hulls are lined with Fresnel lenses and holographic film that focus the light back onto the sandwiched solar cells

The wingsail with rotatable solar cells and Kevlar-carbon fibre composite can be configured to best harness nature's energy 

‘The next stage of the design attempt to use kinetic movement to contribute to running the yacht as well as recycling the carbon fibre materials to reduce the environmental damage caused during curing.’

Unique, green energy-harnessing innovations are Dr Krasojevic’s specialty with other projects including a floating wine bar in Paris that harnesses natural light and boasts etched glass to resemble a bottle of bubbles.

She’s also designed a ‘jetway hotel’ that can be wheeled up to the door of a private jet so the owner need not leave the airfield for short stays and a vertical prison in the middle of the ocean that produces hydroelectricity with its own waterfall.

 

 

@highlight

The Fresnel Hydrofoil Trimaran has been designed by architect Dr Margot Krasojevic

@highlight

The self-sufficient craft for racing and cruising commissioned by Holden Manz wine estate

@highlight

Solar panels on the wingsail will help power technology on the craft