It’s every cyclist’s nightmare – discovering that they have run out of water half way up a hill on a sweltering day.

But the days of topping up water bottles may soon be over, now that one designer has created a bottle that collects and condenses moisture from the air while a bike is in motion.

The prototype ‘Fontus’ device uses the principle of thermoelectric cooling to fill up a bottle with water when attached to a bike frame.

The ‘Fontus’ bottle uses the principle of thermoelectric cooling to fill up with water when attached to a bike frame (pictured). It's named after the Roman god of wells and springs

Kristof Retezár, an industrial design student at the University of Applied Arts in Vienna came up with the idea, and a finalist in the 2014 James Dyson Award.

Named after the Roman god of wells and springs, the upper part of the bottle holder is cooled by electricity generated by solar panels, while the bottom heats up.

This means that as the bike moves, air is sucked inside and moves through the upper chamber of the holder, where it cools down. The air condenses into water and drips into the bottle attatched below.

‘Useful on long bike tours, the constant search for freshwater sources such as rivers and gas stations can cease to be an issue since the bottle automatically fills itself up,’ he wrote on the James Dyson Award website.

The upper part of the bottle is cooled by electricity generated by solar panels, while the bottom heats up. This means that as the bike moves, air is sucked inside and moves through the upper chamber of the bottle, where it cools down. It condenses into water and drips into the bottle (a cross section of the design is shown)

The bike-mounted device that the bottle attaches to, has a small cooler at its centre called Peltier Element.

This cooler is divided in two. Solar panels generate electricity to cool the upper part down, while the bottom side warms up.

As air enters the bottom chamber of the bottle at high speed - when the bike is moving forwards - the hot side of the device is cooled down, which in turn cools the cold side further.

When the air enters the top chamber it is stopped with 'little walls' that are perforated, and the water condenses.

Droplets flow through a pope into the bottle, which can be turned into a vertical position and loosened.

Any standard 500ml bottle can be used.

Mr Retezár said that the device can harvest half a litre of water in an hour under the right climatic conditions - in temperatures of around 20°C (68°F) and 50 per cent humidity.

The bottle has a filter to keep dust out of the water, but does not yet purify it, which may be important the Fontus bottle is used in a polluted city.

He told The Huffington Post that the prototype cost between $25 (£16) and $40 (£26) to make, but he plans on refining the design before bringing it to market and setting a price for consumers.

Mr Retezár has not ruled out raising money via crowdfunding and aside from consumer cycling applications, believes the product could be used to acquire fresh water in regions of the world where groundwater is scarce but air humidity is high.

‘Harvesting water from the air is a method that has been practised for more than 2,000 years in certain cultures mostly in Asia and Central America,’ he said.

‘The Earth’s atmosphere contains around 8,077 cubic miles (13,000 km3) of mostly unexploited freshwater. This project is an attempt to discover these resources.’

The bottle may be able to help the two billion people in more than 40 countries who live in regions with water scarcity. It is predicted that 47 per cent of the world’s population will be living in areas of high water stress in 2030.

Industrial design student, Mr Retezár said that the device can harvest half a litre of water in an hour under the right climatic conditions - in temperatures of around 20°C (68°F) and 50 per cent humidity. A diagram of the different parts of the device is shown

@highlight

‘Fontus’ bottle uses the principle of thermoelectric cooling to fill up with water when attached to a device on a moving bike frame

@highlight

It's the brainchild of a student at the University of Applied Arts in Vienna

@highlight

Prototype bottle is cooled by solar panels to help water condense inside it

@highlight

It's intended for long bike rides and works best at around 20°C (68°F)

@highlight

Bottle could also be used to  acquire fresh water in regions of the world where groundwater is scarce but air humidity is high