A new collapsible coffee cup gives drinkers a chance to grab their caffeine fix on the go - and then store the empty mug in their pocket.

Smash Cup is a portable, reusable and eco-friendly coffee cup which can collapse down when empty to fit in handbags, backpacks and even pockets.

At full height it stands at five inches (12.7 cm), holding a capacity of 12 ounces (340 ml) of hot or cold beverages, but collapses down to just 1.75 inches (4.4 cm).

Scroll down for video

A new collapsible coffee cup gives drinkers a chance to grab their caffeine fix on the go - and then store the empty mug in their pocket.  Smash Cup (shown) is a portable, reusable and eco-friendly coffee cup which can collapse down when empty to fit in handbags, backpacks and even pockets

With the average coffee drinker throwing away a total of 500 disposable cups every year, the reusable Smash Cup can apparently help to reduce waste.

The collapsible cup is the brainchild of Ben Melinger, 34, who believed there was a need for the standard travel cup to become more convenient.

His product combines an iconic design with a resuable body and a leak-proof lid - all of which promises to take up as little room as possible.

It takes apparently as much energy as smashing an egg on a table with your hand to close the cup.

'When we first came up with the idea we were amazed there were no similar products on the market,' said Melinger, a management consultant from New York.

'Smash Cup is reminiscent of disposable coffee cups, but upgraded for a more robust and modern aesthetic.

'We strove to create an iconic look that city commuters, busy parents and students alike would be proud to own and display.

'It takes years of effort to develop a product and there was so much self-doubt, and so many little hurdles that popped up during the process.

'But whenever we took a step back and had a look at the Smash Cup with fresh eyes, we always felt we had a winner.

'This kept us pushing ahead - one step at a time.'

The collapsible cup is the brainchild of Ben Melinger, 34, who believed there was a need for the standard travel cup to become more convenient. His product combines an iconic design with a resuable body and a leak-proof lid - all of which promises to take up as little room as possible

At full height (right) it stands at five inches (12.7 centimetres), holding a capacity of 12 ounces (340 millilitres) of hot or cold beverages (left).  But when empty, the simple looking design can collapse down to measure just one and three quarters of an inch in height

After two years developing the idea, Ben was surprised to see immediate success when he placed Smash Cup on crowdfunding site, Kickstarter.

You may currently grab a coffee while filling up your car at a petrol station, but in the future you could be refuelling your vehicle with the aromatic brown liquid too.

Scientists claim that a ‘green’ biofuel made from waste coffee grounds could power vehicles on our roads.

Around 22 pounds (10 kilograms) of leftover grounds, generated by the average coffee shop, produces around two litres of the biofuel.

The scientists believe that if this were scaled up nationally, popular high street coffee shops such as Starbucks, Café Nero and Costa Coffee could soon be rivalling oil giants like Shell, BP and Esso.

Researchers at the University of Bath said  such waste coffee grounds could be a sustainable fuel source for powering vehicles.

He set a goal of raising £6,000 ($10,000) in 30 days, enough to allow him to begin the production process in America.

But amazingly he reached his target after just one day - and he is now well above his original goal.

'I am floored by the response,' he said.

'I was actually concerned that the low price of the product would make it a struggle to reach $2,000 [£1,200] on the first day - let alone $10,000 [£6,000] in 30.

'But it all happened on day one! My friends and family have been really supportive and I find it funny when they tell me they're addicted to watching the screen tick up and up.

'But more than any amounts of money, I'm just happy to know that we're going to be able to make Smash Cup a real thing and put it on the market.

'I love to create things and it's a great feeling to know other people appreciate what you've created.'

Smash Cup has a water-tight seal, activated by closing the cup with a simple quarter turn.

With three parts made from silicone and plastic, Melinger says the cup is easy to clean and it is also dishwasher safe.

It comes in five different colours - red, green, blue, pink and orange - with the plastic lid available in white and dark grey.

And as a special tribute to its humble beginnings, Ben has also designed a limited edition version for Kickstarter - in the website's signature light green.

Smash Cup is currently only available to Kickstarter backers but Ben hopes to work with a UK or European distributor or team up with a coffee chain to reach customers worldwide.

@highlight

New York-based inventor has unveiled his coffee cup that collapses

@highlight

The 'Smash Cup' can be squashed down in size once it has been used

@highlight

Ben Melinger's £9 ($15) product recently reached its target on Kickstarter

@highlight

The cup is five inches high and can hold 12 ounces of beverages

@highlight

Inventor claims it could be a greener solution to throwing away cups