Eddie Hearn has submitted a formal proposal for a summer blockbuster between Carl Frampton and Scott Quigg.

Significant hurdles remain in making a June bout between these super-bantamweight world champions, most notably because they are backed by different broadcasters, with Frampton enjoying huge exposure on ITV while Hearn's fighters, including WBA (regular) champion Quigg, operate on Sky Sports.

The dilemma is between the lure of terrestrial television and the greater prize purses that would most likely be generated by a box office event on Sky. For his part, Hearn has now tabled a proposal and is waiting on a reciprocal suggestion from Barry McGuigan, who manages IBF champion Frampton.

Carl Frampton (left) and Scott Quigg (right) could be in line for a super-bantamweight bout in June 

Eddie Hearn has tabled a proposal for the fight but significant hurdles still remain 

Frampton's manager Barry McGuigan will talk with his boxer as a decision draws near 

It remains to be seen if there will be a way forward from there, with McGuigan adamant after Frampton's excellent win over Chris Avalos last month that the fight should prioritise exposure over 'greed'.

But Hearn told Sportsmail: 'Scott is not worried about where the fight is staged or what television channel it is shown on – we just want to make this fight. Of course the finances have to be right and we have submitted a proposal that will pay both fighters huge money. They (Frampton and McGuigan) will talk with their broadcaster and see what's on offer and then hopefully we will sit down as soon as possible.

'After that, we can push negotiations on. I'm not sure if we will ever find an agreed split - I would be happy for a 60-40 purse split in favour of the winner. If you really fancy it I can't see a problem with that. Let's see.

Frampton celebrates after his victory over Chris Avalos in Belfast, Northern Ireland in February

Frampton spins to address the crowd after stopping Avalos in the fifth round last month

'We can talk about world titles and legacy and exposure but ultimately this is a super fight – and in a super fight it is only right that these two great fighters get the best deal possible financially.'

Venues for what would likely be the biggest fight in Britain this year are currently under consideration in Belfast, where Frampton is from, as well as Manchester and the O2 Arena in London.

Hearn added: 'If we can all reach an agreement, then I would love to make this fight in June. We'd be happy to fight in Belfast if the numbers were right, but likewise Manchester would be brilliant and so would the O2 Arena in London. There is a long way to go but who wouldn't want to see this fight?'

After Frampton's thrilling ITV debut against Avalos on February 28, in which he extended his record to 20 wins from 20 fights, McGuigan said: 'Eddie thinks of the numbers all the time, let's think of the game, let's think of it being free-to-air and millions and millions of people enjoying watching it because it will be a great fight.'

@highlight

Eddie Hearn tells Sportsmail he wants the fight sorted for Scott Quigg

@highlight

Hearn describes the potential bout as a 'super fight' 

@highlight

Boxers are backed by different broadcasters but hope for a resolution  

@highlight

Frampton and Quigg wants a unification clash in the summer

@highlight

CLICK HERE for all the latest boxing news 