By
Associated Press

PUBLISHED:
  
  
      19:56 EST, 17 December 2013
    
  
 | 
  UPDATED:
  
  
      20:03 EST, 17 December 2013

After working for days without success to fix a cooling system problem that crippled the International Space Station, NASA announced today that a decision has been made to proceed with spacewalks in an effort to fix the problem externally.

NASA has ordered up a series of urgent spacewalks to fix a broken cooling line at the International Space Station.

Station managers decided on Tuesday to send two American astronauts out as soon as possible to replace a pump with a bad valve.

It's a major job that will require three spacewalks â€” Saturday, Monday and next Wednesday on Christmas Day.

Don't look down: NASA astronauts plan to perform three spacewalks, culminating in one on Christmas Day, to repair the International Space Station's coolant system

Chilly up here: A flow-control valve designed to carry ammonia along the outside of the station failed last week making it too cold

Expedition 38 crew members: NASA astronaut Rick Mastracchio (2nd from left, back row) and NASA astronaut Michael Hopkins (far right, back row), both flight engineers will take part in the spacewalk including one on Christmas Day

Walkies: US astronaut Rick Mastracchio is likely to be one of those who will take part in a spacewalk. NASA said the spacewalks were scheduled for Saturday, Monday and next Wednesday

'The next week will be busy with 
space walks so not much tweeting from here,' NASA astronaut Rick 
Mastracchio tweeted from space soon after the decision was announced.

The spacewalks are taking priority 
over the launch of a supply ship from Virginia. The commercial delivery 
had been scheduled for this week, but is now delayed until at least 
mid-January.

Half of the station's cooling system 
shut down last Wednesday, forcing the six-man crew to turn off all 
nonessential equipment, including some science experiments. Because of 
the valve failure, one of the two cooling lines became too cold.

The space station cooling system, 
which runs ammonia through the lines, is critical for dispelling heat 
generated by on-board equipment.

What a view! After working for days without success to fix a cooling system problem that crippled the ISS, NASA has announced that a decision has been made to proceed with spacewalks in an effort to fix the problem externally

If anyone can fix it, this man can: Expedition 38 astronauts Rick Mastracchio and rookie Mike Hopkins will attempt to remove an ammonia pump module on the station's starboard side and replace it with one of three spares

Houston, we have a problem: The space agency confirmed Tuesday afternoon the launch of a cargo resupply mission whose rocket rolled to its Virginia launch pad Tuesday morning would be postponed until January

Go-time: The decision to do a spacewalk came after efforts to regulate temperatures in one of the station's two external loops apparently were unsuccessful

Heading out: Astronaut Rick Mastracchio, Expedition 38 flight engineer, will be one of those who will take part in the spacewalk

While the astronauts are safe and 
comfortable, NASA wants the system back up to full strength, in case of 
another failure that could leave the orbiting outpost even more 
vulnerable than it is right now.

Flight controllers tried in vain to 
fix the valve remotely, then came up with a plan to use another valve to
 regulate the temperature. Some success was reported, and for a while, 
engineers thought the space station could limp along with the short-term
 solution. But on Tuesday, managers opted for spacewalks right now.

This is the same pump that was replaced by a pair of spacewalking astronauts in 2010. Three spacewalks were needed then.

Mastracchio and astronaut Michael 
Hopkins trained for just such a repair before rocketing into orbit. They
 have been prepping all week, just in case of just such a decision.

Orbital Sciences Corp., meanwhile, 
will stand down from its planned Thursday night launch of its Cygnus 
cargo ship from Wallops Island, Virginia.

The station crew includes three Russians and one Japanese, aside from the two Americans.

Upside down you're turning me: 
The spacewalks will repeat procedures performed three years ago in the same location when the previous pump module failed for different reasons

A picture of Earth taken by the International Space Station by night

@highlight

Astronauts will perform three spacewalks to try to remove ammonia pump module

@highlight

The spacewalks are scheduled for Saturday, Monday and Christmas Day

@highlight

Attempts to regulate temperatures in one of the external loops were unsuccessful

@highlight

Cargo resupply mission, scheduled for this week, will be postponed until January

@highlight

ISS has a mass of almost a million pounds and is the size of a football field

@highlight

Nasa says it is confident the habitat is safe to stay in orbit until 2028, and possibly much longer