By
Grace Mccann

Toby
 Hadoke has suffered with psoriasis since childhood. The condition, 
which causes red, scaly patches of skin, is distressing and can be 
painful.

'At its worst, I felt like I'd been stung by a thousand bees,' says Toby, a 40-year-old comedian and writer from north London.

But
 recently he's found a surprising treatment that has transformed his 
symptoms. Much of his skin used to be covered in flaky patches. Today, 
these areas are merely slightly pink and dry.

Toby Hadoke, 40, from London has suffered with psoriasis since childhood and has recently found a treatment

The difference is not 
down to a new ointment but, he says, it's thanks to a form of talking 
therapy, known as cognitive behavioural therapy (CBT).

'I tried 
everything - Chinese medicine, mud from the Dead Sea, bathing in  
lavender,' says Toby. 'But CBT has helped massively - I finally feel I'm
 in control of my psoriasis.'

It may seem surprising that a 
psychological treatment could have such a marked effect on a physical 
condition, but it is increasingly being used outside the mental health 
field.

Talking therapies such as cognitive behavioural therapy help 
people make positive changes to their thinking and behaviour and have 
been shown to be effective for a range of conditions including skin 
complaints, gut disorders and chronic pain.

What is striking is that 
psychological techniques are actively helping to reduce symptoms, rather
 than enabling patients to cope with having a long-term condition. 
Psoriasis is a chronic inflammatory condition where the skin renews 
itself too quickly. It is thought to be due to a problem with the immune
 system. Research has shown CBT can reduce its severity, an effect 
maintained six months on, says Dr Alexandra Mizara, a specialist 
psychologist who leads the psychodermatology service at the Royal Free 
Hospital in London, offering support for conditions ranging from acne to
 skin cancer. 

Psychological techniques are actively helping to reduce symptoms

About 60 per cent of psoriasis patients will find 
stress makes their condition worse, adds Dr Sandy McBride, a consultant 
dermatologist at the Royal Free. It's thought that this may partly be 
because when stressed, people with psoriasis produce less cortisol - a 
hormone that reduces inflammation.

'It's logical that if stress 
makes many psoriasis patients worse, modifying your stress response 
should make it better,' says  Dr McBride.

Toby was bullied at school and says that his psoriasis would flare up as a result.

He
 has two or three sessions a month of CBT with Dr Mizara, plus 
twice-monthly injections of an anti-inflammatory drug, and ointments for
 his arms and scalp. The CBT sessions have helped to reduce his stress 
levels by changing unhelpful ways of thinking.

'I might have a 
conversation with someone that's gone perfectly well, then remember 
something I said that the person didn't seem enthusiastic about and 
worry about it,' says Toby.

This tendency to fixate on such moments,
 perceiving them as failures, is known in psychology as catastrophising,
 in which unnecessary stress is generated.

'Dr Mizara's very good at offering perspective, such as the person I was talking to may just have been distracted,' says Toby.

Much
 of his stress is generated by psoriasis itself. 'I was once in a play, 
which required me to take my top off,' he says. 'I heard a bloke in the 
audience say loudly: "Well, I hope that's not catching." '

In the 
past, Toby would have dwelled on the comment, but CBT has given him 
techniques to get past it. Since starting sessions with Dr Mizara two 
years ago, his Psoriasis Area Severity Index (PASI) score - which 
measures the severity of psoriasis - has improved and he is using less 
ointment.It is also accepted that CBT can be an effective treatment 
for some patients with irritable bowel syndrome (IBS), says Dr Anton 
Emmanuel, a consultant gastroenterologist at University College 
Hospital, London.

IBS refers to symptoms such as stomach cramps, 
diarrhoea, constipation and bloating. It is estimated to affect up to a 
third of the population at some point in their lives. Stress is a 
trigger.

'We know psychological therapies can work for the symptoms 
of IBS, as they have an effect on the autonomic nervous system, which 
regulates automatic functions such as digestion,' says Dr Emmanuel, who 
is also the medical director of the gut and liver disease charity, Core.

Brain
 scans of IBS patients have shown increased activity in parts of the 
brain that process messages about pain. This appears to be reduced by 
therapy.

Michael Wyatt, an 18-year-old student from Surrey, 
developed an irritable bowel last year during a severe case of 
ulcerative colitis, an inflammation of the colon, which led to him 
needing the loo up to 20 times a day.

Michael had already been having
 CBT for anxiety and to cope with his colitis. When his irritable bowel 
developed, his phsychologists treated it with CBT, too. 'My therapist 
looked at things I was doing to give myself more stress,' he says.

Part of the problem was Michael's rigid ideas about how he should look and behave.

CBT helped his accept his condition rather than focus on it

His
 therapist encouraged him to challenge these rules by deliberately 
breaking them. 'One of my rules was always to look classy, so instead, 
when I had my driving theory test I wore tracksuit bottoms,' he says.

'CBT helped me accept my condition rather than focus on it, and my symptoms have died off.'

It
 has been established that talking therapy can help people who suffer 
with chronic pain. Annabel Gray, 42, had suffered with a lower back 
problem for ten years and had struggled to get a clear answer as to what
 was causing it.

'I was told I had a prolapsed disc at one point; 
another doctor said it was a muscular problem. When it's been bad I've 
been either hobbling around or completely unable to move,' says the 
mother-of-two.

Last year Annabel, an administrator from Portsmouth, 
took part in a study comparing the efficacy of contextual cognitive 
behavioural therapy (CCBT), a new form of talking therapy that focuses 
on mindfulness and accepting problems rather than obsessing about them, 
with physiotherapy in people suffering chronic back pain.

Mindfulness is a meditative technique to develop awareness of the present moment as an antidote to worry.

Annabel received eight one-to-one sessions of CCBT with a psychologist.

Professor
 Tamar Pincus, a health psychologist at Royal Holloway, University of 
London, who co-ran the as-yet-unpublished study, described how the 
therapy is designed to help people who struggle to cope psychologically 
with a physical condition.

'They tend to be people with negative thinking styles,' says Professor Pincus. Tensing  up against pain increases it,  he adds.

In
 her sessions, Annabel would be asked to close her eyes and focus on the
 pain. 'To feel it for what it is, accept it and let it be,' she says. 
'It's been amazingly helpful. A few weeks ago I had a bad episode with 
my back. Whereas before I would probably have lain on the sofa, taken 
painkillers and worried about the pain, I took my dog for a walk and 
felt better.'

Annabel credits CCBT for the change in her mindset and is in less pain now. 'It's turned my life around,' she says.

@highlight

Toby Hadoke, 40, from London has suffered with psoriasis since childhood

@highlight

Has recently found a surprising treatment - cognitive behavioural therapy