By 
Steve Doughty

Last updated at 11:21 AM on 11th October 2011

The extent of the UK’s reliance on the South to prop up the economy was laid bare by official figures yesterday.

They showed that only two areas in the north of England and one in the Midlands could match the wealth creation per worker of London and the South.

And only four of Scotland’s towns and cities and one in Wales could do so. The Midlands area is the Birmingham suburb of Solihull, while the two in the north are Cheshire and Derby.

Wealth creation was measured using a 
complicated formula taking into account the amount of the nation’s GDP 
created per region, the number of workers there and the number of hours 
they work.

It excluded the effects of unemployment, so only measured the value of those in work.

The analysis by the Office for National 
Statistics concluded: ‘The highest productivity levels are found in 
inner London, with productivity in Inner London West 56 per cent above 
UK average and Inner London East 33 per cent above UK average.’

South props up economy: Only two areas in the north of England and one in the Midlands could match the wealth creation per worker of London and the South. (Data from the Office for National Statistics)

The analysis found that the highest productivity levels are found in inner London

Economist Ruth Lea, of the Arbuthnot 
Banking Group, said: ‘There is no doubt that workers in the south are 
supporting those in the rest of the country.’

And Rob Harbron, of City think-tank 
the Centre for Economics and Business Research, said: ‘Other regions 
have a high dependence on public sector spending.’

People
working in Berkshire, Surrey and Swindon also brought in productivity 
returns that put their value at more than 15 per cent above average.

The
new official demonstration of the concentration of wealth creation in 
London and the South was published in the wake of the latest European 
attempt to cream off profits from the City and financial industries.

Lower levels of productivity: Wealth creation was measured using a complicated formula taking into account the amount of the nation's GDP created per region, the number of workers there and the number of hours they work

Worst-performing: Bottom of the pile for worker productivity per hour was Blackpool

The transactions tax proposed by European Commission president Jose Manuel Barroso would fall heavily on England, with finance industries in the south of England paying up to 70 per cent of the tax proceeds across Europe.

Profits generated in southern England already heavily subsidise life in the rest of the country: most other regions are dependent on taxes paid in the south, and three have economies in which 60 per cent of all spending is provided by the state.

The ONS analysis examined gross value added per hour worked – the amount of wealth generated by a worker every hour in 2008, the first full year of the recession.

The method eliminates the effects of unemployment and worklessness and measures only the value produced by those who are actually in jobs.

The worst-performing areas were largely rural or tourist regions and depressed cities.

Bottom of the pile for worker productivity per hour was Blackpool, 67 per cent of average, followed by Cornwall, East Cumbria, Torbay, Northumberland, Lincolnshire, Herefordshire, Blackburn, Shropshire and Stoke-on-Trent.

The lowest-place major city was the northern side of Manchester: Greater Manchester North returned 83 per cent of average productivity.

In Scotland just four areas: Edinburgh, Falkirk, East Lothian and Midlothian, and Aberdeen, were above average. Cardiff and the Vale of Glamorgan were the only part of Wales to top the average.

@highlight

Highest productivity levels are found in inner London

@highlight

Bottom of the pile for worker productivity is Blackpool