This £23million private jet flew Tesco executives around the world in luxury for years but is now up for sale after the supermarket giant's profits, sales and share price all dive-bombed.

The Gulfstream G550 is one of four private planes now on the market as the grocer is facing the biggest crisis in its 95-year history.

The decision to put them up for sale marks the end of excesses enjoyed by Tesco's bosses while sales and profits have tumbled in recent years. 

New chief executive Dave Lewis has called for austerity, which means selling off the jets that used to fly up to 14 executives at a time across the globe.

Scroll down for video 

High life: This seven-year-old Gulfstream G550 flew up to 14 Tesco executives around the world but is now up for sale for £23million

Change of direction: Tesco has a fleet of jets but amid falling sales and profits they are being sold as its new CEO demanded austerity

Jet-lagged: Executives could also retire for some sleep on the plane, which has full-length beds, TVs and other entertainment

This seven-year-old jet, with a 580mph top speed generated by two Rolls-Royce engines, flew management from Britain's biggest retailer on business trips. 

They would lounge in large leather armchairs while being served food and drink by cabin staff.

On longer journeys to America and Asia they would be able to head off to cabins for some sleep in full sized beds.

Max range: 7697 miles - London to Johannesburg

High speed: 560mph

Passenger capacity:14

Interior seating length: 35.35ft

Overall cabin length: 50.1ft

Cabin height: 6.2ft

Cabin width: 7.3ft

Baggage Capacity: 226 cubic ft

For entertainment, the jet has DVD players, several widescreen TVs and a bar stocked with wine and spirits. It also has more than 226 cubic feet of luggage space, ample room for 20 suitcases and several sets of golf clubs.

Gulfstream, which is based in the United States, said they may be close to finding a buyer. 

Tesco owns two Gulfstream G550s, the one pictured and another new £30million model, which was delivered this year but now also up for sale. It also has a Hawker and a Cessner worth up to £10million.

The supermarket giant revealed last week that its half-year profits slumped by 91.9 per cent and its £263million accounting scandal was even worse than predicted.

The bad news sent the markets into a panic and its shares plunged, dropping below £1.70 for the first time since 2003.

On Friday they were available for £1.65 but a year ago they were worth £3.70, meaning Tesco has had £4billion wiped off its stock market value in just 12 months. 

Millions of customers have switched to budget rivals like Aldi and Lidl or high-end Waitrose and Marks and Spencer because Tesco has failed to deliver on price, service or quality, 

But CEO Dave Lewis yesterday refused to be drawn on what he would do to win back shoppers.

He said: 'Everybody's been saying to me, 'Dave, when are you going to reveal your strategy – when is there going to be an announcement about what you're going to do?' And I won't be doing that because strategies are constantly evolving.

However, Mr Lewis has been clear on one thing, that executives should forget the past high life they enjoyed, and he is swapping his company car for the train.

The former boss of consumer goods giant Unilever said he wanted all staff to examine whether a cost was absolutely necessary and something customers would think felt right. 

Top executives at Tesco have been forced to shop and cook like housewives as part of a plan to put them back in touch with their customers.

The bosses were sent food shopping at Tesco and at all its main rivals then whisked away to a small, remote holiday cottage in Norfolk. 

Excesses: Executives would on long and short haul trips in the plane, and were served food and drink from this galley by a team of staff 

Bathroom: Passengers had access to a wide range of products and facilities, including a shower and full-size toilet

For his part, in what most will see as a symbolic gesture, Lewis said wherever possible he would forgo his company Mercedes Viano people carrier and take the train to London from the head office in Cheshunt, Hertfordshire.

In particular he is seeking to unwind some of the largess of former boss Philip Clarke, who was sacked a month before the private jets went on sale.  

Philip Clarke still retains the use of a company chauffeur despite having not set foot in the firm’s head office since August.

The Mail understands that Ferrari-driving Clarke is still entitled to all the trappings of his previous position as chief executive despite having stepped down in August ahead of the financial scandal.

This includes a driver, membership to clubs, security, health insurance and even a staff discount.

He gets this on top of a £1.1m salary which continues to be paid until January.

Tesco operates a pool system of cars and drivers which include Mercedes saloons and mini vans. It is also thought Tesco is paying his membership of the exclusive private dining club 5 Hertford Street, based in Shepherd’s Market, London.

The perks, sanctioned by chairman Sir Richard Broadbent will anger investors who have seen Tesco shares lose 53pc of their value over the past year.

It also brings into question Broadbent’s judgement given the scandal that has since engulfed the grocer.

Broadbent, who quit after the Tesco's disastrous results were revealed on Thursday, announced in July that Clarke would be replaced following a string of profit warnings.

Change of culture: New boss Dave Lewis, left, is said to be seeking to unwind some of the largess of former boss Philip Clarke, right, who was sacked a month before the private jets went on sale

Running for cover: Departing Tesco chairman Sir Richard Broadbent raced out of a press briefing last week having quit over poor results

Stark: Tesco was considered untouchable but its profit fall in the past year has been unprecedented

A Tesco spokesperson said: ‘Philip Clarke remains a Tesco employee on his existing terms.’ Since his departure it has emerged that shareholders were misled over the true state of Tesco’s financial health going back what could have been years.

In August the firm inflated its profits by a phantom £263m and as many as eight executives have been suspended.

The City watchdog, the Financial Conduct Authority, has launched an investigation.

Broadbent, who last week was also forced to announce plans to step down amid accusations he had been ‘incompetent’, had agreed that Clarke should continue to be paid more than £90,000 a month until the end of the year. 

 

@highlight

Gulfstream G550 one of four private planes now on the market as Tesco faces the biggest crisis in its 95-year history

@highlight

Planes flew up to 14 executives at a time across the globe but new CEO Dave Lewis is selling them to save cash 

@highlight

Jet, with 560mph top speed, signals end of luxury travel for Tesco because of falling sales, profits and share price