By
Sarah Griffiths

PUBLISHED:
  
  
      12:36 EST, 4 March 2014
    
  

 | 
  UPDATED:
  
  
      13:09 EST, 4 March 2014

Twitter can be used to track HIV outbreaks and could one day help prevent them, scientists claim.

It may be possible to predict sexual risk and drug use by monitoring tweets and mapping where they come from and comparing them with data on the geographical distribution of HIV cases, according to a new study.

A team of U.S. scientists examined almost 10,000 tweets with sexual and drug-related themes and found that their locations were a good predictor for statistics on HIV prevalence.

A team of U.S. scientists examined almost 10,000 tweets with sexual and drug-related themes and created a map of them. They found that their locations were a good predictor for statistics on HIV prevalence

Researchers found 8,538 tweets indicating sexually risky behaviour and 1,342 suggesting drug use.

The states with the largest proportion of geo-located tweets denoting risky behaviour were California and Texas, which both had over nine per cent of the tweets.

New York had almost six per cent and Florida just over five per cent.

On a per capita basis, the largest raw number of HIV risk–related tweets came from Columbia, Delaware, Louisiana and South Carolina.

‘Ultimately, these methods suggest that we can use “big data” from social media for remote monitoring and surveillance of HIV risk behaviours and potential outbreaks,’ said Sean Young, co-director of the Centre for Digital Behaviour at the University of California, Los Angeles (UCLA).

Other studies have examined how Twitter can be used to predict outbreaks of infections like influenza.

‘But this is the first to suggest that Twitter can be used to predict people's health-related behaviours and as a method for monitoring HIV risk behaviours and drug use,’ he said.

HIV is mainly spread by people having unprotected sex or sharing drug-use equipment with someone with the HIV virus.

Substance use can contribute to these risks indirectly because 
alcohol and other drugs can lower people’s inhibitions and make them 
less likely to use condoms, Centres for Disease Control and Prevention (CDC) said.

Researchers collected more than 550 million tweets between May 26 and December 9, 2012 for the study.

They then created an algorithm to pick out words and phrases in the tweets suggesting drug use or potentially risky behaviours, such as ‘get high’ and ‘sex’.

The study is the first to suggest that Twitter (pictured)can be used to predict people's health-related behaviours and as a method for monitoring HIV risk behaviours and drug use, the researchers said

The scientists plotted tweets identified as risky on a map of the U.S. to discover where they originated and then ran statistical models to see if these were areas where HIV cases had been reported.

The algorithm captured 8,538 tweets indicating sexually risky behaviour and 1,342 suggesting drug use.

The states with the largest proportion of geo-located tweets denoting risky behaviour were California and Texas, which both had over nine per cent of tweets, New York with almost six per cent and Florida with just over five per cent.

On a per capita basis, the largest raw number of HIV risk–related tweets came from Columbia, Delaware, Louisiana and South Carolina.

When the researchers linked the tweets to data on HIV cases, they found a ‘significant relationship’ between those indicating risky behaviour and counties where the highest numbers of HIV cases were reported.　

This map was generated by using social media updates to pinpoint where people were suffering from flu on Christmas day

A Baltimore-based start-up called Sickweather created an influenza map of the U.S. in October 2012 based on people tweeting and posting to Facebook about their illness.

The founder of the small firm, Graham Dodge, discovered that social media reports of the flu spiked 77 per cent between August and October - before the flu season was predicted to begin.

While an increase in the number of ill people is normal during that time period, the numbers found by Sickweather were 30 per cent up from the previous year.

Social media sickness mentions are one of the few signals that can be tracked in real time as doctors attempt to understand how a sickness moves.

@highlight

Scientists from UCLA examined almost 10,000 tweets with sexual and drug-related themes to map their locations

@highlight

They found the map was a good predictor for statistics on HIV prevalence

@highlight

Other studies have examined how Twitter can be used to predict outbreaks of infections like influenza