By
Simon Tomlinson

The former military dictator of Panama is suing the makers of Call Of Duty over its portrayal of him as 'a kidnapper, murderer and enemy of the state' in the hit video game.

General Manuel Noriega has been in jail since 1989 on drug trafficking, racketeering and money laundering charges after being driven from power in a U.S. invasion.

The 80-year-old has now filed a lawsuit against publishers Activision Blizzard for creating a villain in his name and image which he claims has boosted their profits and damaged his reputation.

Battleground: Former Panama dictator Manuel Noriega pictured (left) in 1989 before he was ousted from power by the U.S. and (right) as he appears in the video game Call Of Duty Black Ops II, a depiction he is suing over

In the game, Call of Duty: Black Ops II, he is described by characters as 'a piece of s*** and old pineapple face himself, Manuel Noriega'.

The latter insult refers to his pockmarked face which gave rise to the nickname at the height of his power.

He also randomly shoots members of the Panama Army, his 'own private police force', according to the Independent.

The lawsuit, filed at the Los Angeles Superior Court, says the makers used his image to 'heighten realism in its video game... this translates directly into heightened sales for defendants'.

Cashing in on his image? In the game, Call of Duty: Black Ops II, the jailed 80-year-old is described by characters as 'a piece of s*** and old pineapple face himself, Manuel Noriega', the latter in reference to his pockmarked appearance. He claims the makers have profited from the 'heightened realism'

According to the Courthouse News Service, it adds: 'In an effort to increase the popularity and revenue generated by Black Ops II, defendants used, without authorization or consent, the image and likeness of plaintiff in Black Ops II.

'Defendants' use of plaintiff's image and likeness caused damage to plaintiff.

'Plaintiff was portrayed as an antagonist and portrayed as the culprit of numerous fictional heinous crimes, creating the false impression that defendants are authorized to use plaintiff's image and likeness.

'This caused plaintiffs to receive profits they would not have otherwise received.'

He is seeking damages for 'unjust enrichment, unfair business practices, and violation of common-law publicity rights.'

@highlight

Manuel Noriega, now 80, was ousted from power in U.S. invasion in 1989

@highlight

Been in jail ever since on drug trafficking and money laundering charges

@highlight

His character in Call of Duty: Black Ops II is described as 'a piece of s***'

@highlight

Also seen shooting members of his own army at random in video game

@highlight

Claims developers have damaged his reputation and profited from his image