By 
Mark Prigg

PUBLISHED:

13:10 EST, 18 April 2013


| 

UPDATED:

19:07 EST, 18 April 2013

Two planets found around a distant star have been described as the most similar to Earth yet discovered.

The planets in the newly found Kepler 62 system are made of rock and ice, and researchers believe they could contain water.

Kepler-62e and Kepler-62d are among five new planets found within the 'habitable' zone of a Sun-like star.

The newly discovered planets named Kepler-62e and -f., two of the five planets found around a far-off star have been described as the most similar to Earth yet discovered

Nasa’s Kepler mission has discovered two new planetary systems that include three super-Earth-size planets in the 'habitable zone,' the range of distance from a star where the surface temperature of an orbiting planet might be suitable for liquid water.

The Kepler-62 system has five planets; 62b, 62c, 62d, 62e and 62f.

The Kepler-69 system has two planets; 69b and 69c. Kepler-62e, 62f and 69c are the super-Earth-size planets.

Two of the planets, named Kepler-62e and Kepler-62f, are rocky or made mostly of ice, and are believed to be the most likely to be earth 'doubles'.

Physicist Professor Justin Crepp said: 'From what we can tell, from their radius and orbital period, these are the most similar objects to Earth that we have found yet.'

They were identified by data from the Kepler mission launched in 2009 to identify extrasolar planets.

It has so far resulted in several dozen of some 3,000 'Kepler Objects of Interest' having been studied in detail but of those the 'five-planet system' is the most important.

Crepp noticed a faint dot near Kepler-62 a year ago, leading to months of detailed study to confirm the planet interpretation.

The discovery was made by astrophysicists at the University of Notre Dame.

The findings were published in Science magazine.

Researchers use fluctuations in the brightness of a star to identify the presence of a potential planet whose transit periodically dims the light of the star.

Crepp uses large ground-based telescopes to image the host star and analyzes the system to make sure other astronomical phenomena, such as nearby eclipsing binary stars, are not causing the fluctuation, a common 'false positive' encountered in the research.

'What really helped is that this star has five planets,' he said.

Relative sizes of Kepler habitable zone planets discovered: Left to right: Kepler-22b, Kepler-69c, Kepler-62e, Kepler-62f, and Earth (except for Earth, these are artists' renditions)

'You can mimic one planet with another event, but when you have five of them and they're all periodic, that helps to put the nail in the coffin.

'It's hard to make that kind of signature with anything else that you can dream up.'

Kepler-62 and the Solar System
The diagram compares the planets of the inner solar system to Kepler-62, a five-planet system about 1,200 light-years from Earth in the constellation Lyra

Kepler-69, the second new system revealed today, a two-planet system about 2,700 light-years from Earth in the constellation Cygnus. The two planets of Kepler-69 orbit a star that belongs to the same class as our sun, called G-type.

The Kepler space observatory, named 
after the 17th century German astronomer Johannes Kepler, was launched 
on 7 March 2009 to survey a portion of the Milky Way for Earth-size 
planets that could harbour life.

The research team used data from 
NASA's Kepler space telescope, which simultaneously and continuously 
measures the brightness of more than 150,000 stars every 30 minutes.

When
a planet candidate transits, or passes, in front of the star from the 
spacecraft's vantage point, a percentage of light from the star is 
blocked.

This causes a dip in the brightness of the starlight that reveals the transiting planet's size relative to its star.

The size of the star must be known in order to measure the planet's size accurately.

To
learn more about the properties of the stars, scientists 
examined sound waves generated by the boiling motion beneath the surface
of the star.

They 
probe the interior structure of stars just as geologists use
seismic waves generated by earthquakes to probe the interior structure 
of Earth.

The science is called asteroseismology.

The sound waves travel into the star and bring information back up to the surface.

The waves cause oscillations that Kepler observes as a rapid flickering of the star's brightness.

Like bells in a steeple, small stars ring at high tones while larger stars boom in lower tones.

The barely discernible, high-frequency oscillations in the brightness of small stars are the most difficult to measure.

This is why most objects previously subjected to asteroseismic analysis are larger than the sun.

Eric Agol, a Univeristy of Washington  associate professor of astronomy, identified Kepler 62f, a small, probably rocky planet orbiting a sunlike star in the Lyra constellation.

The planet is about 1.4 times the size of Earth, receives about half as much solar flux, or heat and radiation, as Earth and circles its star in 267.3 (Earth) days.

It's one of two "super-Earth" planets discovered in the star Kepler 62's habitable zone, that swath of space the right distance from the star to potentially allow liquid water to exist on a planet's surface, thus giving life a chance.

A super-Earth is a planet greater in mass than our own but still smaller than gas giants such as Neptune.

Kepler 62's other super-Earth, nearby 62e, is 1.61 times Earth's size, circles the star in 122.4 days and gets about 20 percent more stellar flux than the Earth.

The two are the smallest exoplanets — planets outside the solar system — yet found in a host star's habitable zone.

'The planets this small that we have found until now have been very close to their stars and much too hot to be possibly habitable.

The artist's concept depicts Kepler-62e, a super-Earth-size planet in the habitable zone of a star smaller and cooler than the sun, located about 1,200 light-years from Earth in the constellation Lyra.
Kepler-62e orbits it's host star every 122 days and is roughly 60 percent larger than Earth in size. Scientists do not know if Kepler-62e is a waterworld or if it has a solid surface, but its discovery signals another step closer to finding a world similar to Earth.

Kepler-62f, a super-Earth-size planet in the habitable zone of a star smaller and cooler than the sun, located about 1,200 light-years from Earth in the constellation Lyra.
Kepler-62f orbits it's host star every 267 days and is roughly 40 percent larger than Earth in size. The size of Kepler-62f is known, but its mass and composition are not. However, based on previous exoplanet discoveries of similar size that are rocky, scientists are able to determine its mass by association.

The artist's concept depicts Kepler-69c, a super-Earth-size planet in the habitable zone of a star like our sun, located about 2,700 light-years from Earth in the constellation Cygnus.
Kepler-69c, is 70 percent larger than the size of Earth, and is the smallest yet found to orbit in the habitable zone of a sun-like star. Astronomers are uncertain about the composition of Kepler-69c, but its orbit of 242 days around a sun-like star resembles that of our neighboring planet Venus.

'This is the first one Kepler has found in the habitable zone that satisfies this small size," Agol said.

'Kepler 62f is the smallest size and the most promising distance from its star, which by these measures makes it the most similar exoplanet to Earth that has been found by Kepler.'

Agol is the second author of a paper documenting the discovery published April 18 by Science Express, the online edition of the journal Science.

While the sizes of Kepler 62e and 62f are known, Agol said, their mass and densities are not — but every planet found in their size range so far has been rocky, like Earth.

'Based on its size, our best guess is that it's rocky and has some atmosphere, but not a thick gaseous envelope, like Neptune,' Agol said.

The Kepler telescope was launched in 2009 with the aim of finding Earthlike planets beyond the solar system.

It detects planets by 'transits' that cause their host stars to appear fainter when the planets pass in front as they orbit.

Kepler 62f was a late-arrival in terms of its discovery.

Its planetary siblings were found by a team of researchers led by William Borucki of the NASA Ames Research Center, principal investigator for the Kepler Space Telescope. Kepler 62 b, c and d are 1.31, 0.54 and 1.95 times the size of the Earth, respectively, but orbit the star too close to be in the habitable zone.

'This type of discovery is the reason we launched the Kepler spacecraft —
to find small, Earth-sized, potentially Earth-temperature planets," 
Agol said.

'At the same time, though, it isn't exactly the same as 
Earth.

'It is slightly larger and cooler than Earth.

'It tells me how 
special the Earth is and how it may take some time — hopefully not too 
long — to find its exact twin.'

@highlight

Discovery of five new planets made by Nasa's Kepler telescope

@highlight

Two of the planets, named named Kepler-62e and Kepler-62f, are rocky or made mostly of ice

@highlight

All five are within the 'habitable' zone of a Sun-like star