Children who are given anti-racism lessons in school are more likely to be intolerant outside the classroom, a major study found yesterday.

It said accusing white pupils of racism causes animosity, and discussing sensitive ethnic concerns such as honour killings paints minority group children in a bad light.

The survey said children who live in mixed neighbourhoods are often free of hostility towards other racial groups.

Counter-productive: A Dutch study has found children who are given anti-racism lessons in school are more likely to be intolerant outside the classroom

But it found that ‘when more attention in class is being paid to the multicultural society, the liberalising effect of positive contact in class on youngsters’ xenophobic attitude decreases’.

The project carried out in the Netherlands comes at a time of controversy over the place of multiculturalism – which blames Britain for historic racism and demands the encouragement of minority cultures – in the national curriculum and teaching in British schools.

Education Secretary Michael  Gove has been under fire from Left-wing academics over plans to stop teaching teenagers about topics such as ‘the wide cultural, social and ethnic diversity of Britain from the Middle Ages to the twentieth century and how this has helped shape Britain’s identity’.

Instead, in future pupils will be taught much more British history. The study, published in the European Sociological Review, was based on a survey of 1,444 pupils aged 14 and 15 in ten schools in the city of Nijmegen.

Education Secretary Michael  Gove has come under fire from Left-wing academics over plans to stop teaching teenagers about multicultural topics

The teenagers, drawn from different class and racial backgrounds, and with differing academic abilities, were questioned on their attitudes to those from different ethnic backgrounds and about multicultural teaching in their schools.

It said boys tended to be more intolerant of other groups than girls, and intolerance was greatest among those with strong religious or ethnic identity, among those from Turkish or Moroccan backgrounds, and those with the lowest educational achievements.

But it said the teaching of multiculturalism had an ‘unexpected negative effect’.

It added: ‘The impact of positive inter- ethnic contact in class disappears  or even reverses when multiculturalism is more emphasised during  lessons. Discussing discrimination and the customs and habits of  other cultures during lessons affects the youngsters’ xenophobic attitudes indirectly.’

The report added that bad feelings among minority groups could be generated by discussion of topics such as honour killings or female  circumcision. Animosity could also be caused by ‘a one-sided offender- victim approach to racism’.

The findings echo the views of Bradford head teacher Ray Honeyford, who was driven from his job nearly 30 years ago over his claim that multicultural teaching was harming pupils.

Mr Honeyford said that pupil performance was hindered by ‘the notion of the multi-racial curriculum urged by the authorities, and of making colour and race significant, high-profile issues in the classroom’.

Patricia Morgan, an author on  the family and education, said  yesterday: ‘If you rub children’s noses in their supposed racism, they resent it.

‘Pupils are being accused of things they haven’t thought or done. Multiculturalism attempts to manipulate children’s thoughts, beliefs and emotions, it amounts to indoctrination, and it doesn’t work. It is counter-productive.

‘This study shows that when people try to manipulate children’s minds, it bounces back on them.’

@highlight

Dutch study finds discussing sensitive ethnic concerns can be counter-productive

@highlight

Education Secretary Michael Gove under fire over plans to stop teaching teenagers about multicultural topics