By
Stephen Adams

Worried that Mum’s forgotten to take her medication today? Well, soon there will be no need to be – because scientists have invented a pill that sends a text to say it has  been swallowed.

Doctors believe the novel device could prolong countless lives and save the NHS millions by cutting the amount  of medicines that go to waste.

Each of the ‘texting pills’ contains a tiny metal sensor, the size of a grain of sand, that emits a signal when it gets wet in the stomach. It then passes harmlessly through the body.

The pill’s signal is picked up by a patch on the arm, which transmits the message by wireless Bluetooth technology to the person’s mobile. The phone then texts the patient’s contacts – such as a loved-one and their doctor or nurse – telling them it has been taken.

Lloydspharmacy and Oxford University have been involved in UK pilots of the technology, called Helius, which is being developed by US firm Proteus Digital Health.

Professor Lionel Tarassenko, from the university’s Institute of Biomedical Engineering, said: ‘Elderly people sometimes have to take six, seven, or eight pills a day. 

‘But if someone doesn’t take their pills that can be a very, very serious thing. If you have an elderly parent who is not taking their pills, you might want to know.’

He is hoping to start a UK trial next year using the texting pills with heart failure patients. 

So far he has been limited to testing the patch itself, which can track and relay other information about the patient such as their pulse, activity levels and sleeping patterns.

Doctors believe the novel device could prolong countless lives and save the NHS millions by cutting the amount  of medicines that go to waste

Lloydspharmacy has completed a UK pilot with patients who have high blood pressure. They often need to take several medicines a day. The test-run – like others in the US – has involved patients taking an extra ‘dummy pill’, containing just the sensor, in addition to their medication.

But Proteus soon hopes to embed their tiny sensors in pills containing active drugs.

CEO Andrew Thomson said: ‘When you swallow one of our digital drugs it will say, “Hello I’m here, I’m Novartis, I’m Diovan, 1.2mg, I’m from plant number 76, I’m batch number 12 and I’m pill number two.” ’ He claimed the invention could save the NHS ‘hundreds of millions of pounds’.

A university study found we spend £300 million a year on medicines that end up being thrown away. Part of the wastage is due to people not taking medication, called ‘non-compliance’. The texting pills could combat a number of serious ailments, from mental health problems to tuberculosis, added Prof Tarassenko.

He said: ‘TB patients have to take a six-month course of pills. Part of the problem is that after three or four months the patients feel so much better they stop taking them. But they are not cured by then and it’s very important that they keep taking the medication.’

Privacy campaigners do have concerns about the security of sensitive health data generated by the sensor pills

Privacy campaigners do have concerns about the security of sensitive health data generated by the sensor pills.

But the academic said: ‘Personally, I believe it’s utterly ludicrous to think that way.

‘I ask them if they do internet banking and of course 99 per cent say yes. And anything to do with healthcare data has at least the same level of security as internet banking does.’

A Lloydspharmacy spokesman said its pilot had generated ‘very positive feedback’ from patients, their families and health professionals.

It wants to get NHS doctors to recommend the technology to appropriate patients.

She said: ‘Proteus Digital Health and Lloydspharmacy believe that a doctor-oriented approach opens opportunities to collaborate with the NHS and make the service more accessible and therefore allow more people to benefit from the technology. ‘

By Dr Ellie Cannon

Motion sensors, blood-pressure monitors and even machines that screen for diseases like diabetes from the comfort of your living room are already part of thousands of British homes.

Two years ago David Cameron publicly backed tele-health: remote monitoring that allows vital checks by these gadgets.

Everything is sent to a call centre which can tell if a prescription needs tweaking, or if a family member or the doctor needs to be called.

It sounds like sci-fi, but early trial results have been promising, showing a drop in emergency admissions.

Everything is sent to a call centre which can tell if a prescription needs tweaking, or if a family member or the doctor needs to be called

There are more than 15 million Britons who have a chronic condition that requires self-management.

It’s early days for the Helius, but ingestible microchip tablets that tell the doctor they’ve been taken may prove valuable.

Coming up with a drug for an illness is just part of the battle. One of the biggest difficulties is actually getting patients to take them.

Figures show up to half of patients don’t. The beauty of this technology is that we would be perfectly clear what dose and regime our patients were using.

This could be especially effective in elderly patients with mental health problems.

But the new technology is far from perfect. At the moment the microchip is contained within an extra dummy pill. If it’s hard enough to get Mum to take five pills, is adding another really making life simpler? And what if she gets confused and takes the dummy, and not the real pill?

I’m all for scientific advance, but it mustn’t overshadow often cheaper basics. Perhaps there are simpler ways to help patients, such as a humble dosette box and an alarm clock.

As exciting as it is, I envisage a long wait before this technology is part of my daily routine in clinic.

@highlight

Scientists invented a pill that sends a text to say it has been swallowed

@highlight

Novel device could prolong countless lives and save the NHS millions

@highlight

The invention will cut the amount of medicines that go to waste

@highlight

Each of the ‘texting pills’ contains a 
tiny metal sensor that emits a signal when
 it gets wet in the stomach