The dispute over World Cup compensation between the Rugby Football Union and Premiership Rugby has been settled after a package worth up to £13million was agreed.

The 2015-16 league season will start from the weekend of October 17 after the International Rugby Board granted dispensation for club games to be staged during the knockout phase of the tournament.

Alarmed by the possibility of five income-free months because of England 2015 and the off-season, the Premiership clubs sought £14million in lost revenue from the RFU.

Prince Harry, the England Rugby 2015 honorary president, holds the ball for World Cup ambassador Jonny Wilkinson during a photo call at the Rugby School

Head coach Lancaster says he has instilled a strong sense of national pride in his players

Some owners threatened to flout IRB regulations by playing throughout the entire World Cup if their demands were not met, but a complex agreement that is part-incentivised has now been reached.

As part of the settlement, England head coach Stuart Lancaster will name his next elite player squad on October 22, delayed from its traditional slot in August.

The additional time enables Lancaster to select from those players who are in form for November's QBE Series against New Zealand, South Africa, Samoa and Australia.

'It's a reflection of the strength of the partnership that once again we have managed to come to an arrangement that benefits both the RFU and clubs,' RFU chief executive Ian Ritchie said.

'We're very happy to continue to invest significant sums into Premiership Rugby and to support their desire to be successful on and off the pitch.'

The agreement is made up of two parts with £6million generated by the re-allocation of match revenues for both union and clubs to increase income for 2015/16 and £7million in payments for the absence of Premiership rugby during the group stage of the World Cup.

Whether the entirety of the £7million will be paid is subject to World Cup ticket sales and gross profit targets being met and on the signature of a new heads of agreement that covers areas such as player release and season structure.

England players wear the new England rugby home kit, which has caused controversy over its design

England's players model the alternative red kit they will wear, with Victoria Cross design on the top half

'By the very nature of the deal, the more successful the RFU is, the more the clubs benefit, while it is good that Premiership Rugby continue to use Twickenham to develop their competition,' Ritchie said.

'It is also significant that there is an incentive to conclude negotiations swiftly around a new long-term 'heads of agreement' that has proved so successful to date.'

It has yet to be decided how England's 12 top-flight clubs will divide the income generated from the package.

'We have resolved a challenging issue in a mutually beneficial way through productive discussions over the last few months, largely behind the scenes,' Premiership Rugby chief executive Mark McCafferty said.

'This announcement underlines the partnership between Premiership Rugby and the RFU to help England's bid to achieve our goals in 2015 and beyond, as well as to support our clubs.

'The delay of the announcement of the elite player squad until October 22 has allowed the first six rounds of the Premiership to be a live trial for players striving to make that EPS.'

Stuart Lancaster insists England will give everything to fill the nation with pride at the 2015 World Cup

England have not won the World Cup since 2003 when they triumphed against then-hosts Australia 

@highlight

Dispute over World Cup compensation between the Rugby Football Union and Premiership Rugby has been settled

@highlight

A package worth up to £13million has been agreed between the bodies

@highlight

The 2015-16 league season will start from the weekend of October 17 