Prince, Paris and Blanket are still waiting for their payday as Michael Jackson's $600million estate is still stumbling to pay off his debts and fund their long-anticipated trust fund.

Sources told the Daily News that the King of Pop's attorneys and financial managers have to settle more than $100million in debt before anyone in the family can touch it, forcing the three children to live off of a meager salary of just $70,000 a month.

It could take two to five more years for everything to be resolved, upon which case the three kin of the King will share 50 per cent of the assets while Katherine Jackson will get the other half.

Siblings: Prince, Paris and Blanket are still waiting for their payday as Michael Jackson's $600million estate is still stumbling to pay off his debts and fund their trust. Paris, center, and her brothers  Prince, 15, right, and Blanket, 10, left, are pictured taking part in the four-day tribute to Michael Jackson on his birthday last week

Allowance: The King of Pop's attorneys and financial managers have to settle more than $100million in debt before anyone in the family can touch it, forcing the three children to live off of a meager salary of just $70,000 a month

'The probate is still pending, and although almost all of Michael’s personal debt has been or is about to be paid in full, the estate is technically still in debt,' estate lawyer Howard Weitzman said to the Daily News.

'Once all of the creditors’ claims, taxes and pending litigation have been resolved, the trusts will be funded per court order.'

The estate has been raking in money since Jackson died on June 25, 2009, thanks to revenue generated by his music, likeness and salvaged assets worth an unknown fortune.

'(It’s) too early to speculate on any precise number for a value. It will be a substantial number, I’m certain,' Mr Weitzman said.

But the three scions of the star have to live on a tightly-controlled allowance overseen by a judge and the estate's executors.

Katherine Jackson, the 82-year-old matriarch of the clan, has also not received any money from the trust.

Split: It could take two to five more years for everything to be resolved, upon which case the three kin of the King will share 50 per cent of the assets while Katherine Jackson will get the other half

King: The three scions of the star have to live on a tightly-controlled allowance overseen by a judge and the estate's executors

Drama: Earlier this year, a judge ruled Michael Jackson's nephew TJ, left, should permanently share guardianship responsibilities with Katherine Jackson, right, for the King of Pop's three children

The 'Michael Jackson Family Trust' dictates that the singer's three kids and Mrs Jackson divide the funds.

'To some of Katherine’s children, this is a shocking situation. They see on paper that Michael has made $600 million and cannot understand why all of it is not going to the family,' a separate source told The Daily News.

Revenue: The estate has been raking in money since Jackson died on June 25, 2009, thanks to revenue generated by his music, likeness and salvaged assets worth an unknown fortune

'This has been the case for a long time. They always think the worst is happening and people are taking money.'

Earlier this year, Randy, Jermaine, Janet and Rebbie squabbled over Katherine's share, luring her to Arizona for a 'spa treatment'.

With Katherine indisposed, the siblings demanded the estate executor's John Branca and John McClaine resign over fraud allegations and managed to get Katherine's custody of the children revoked.

A judge then ruled Michael Jackson's nephew TJ should permanently share guardianship responsibilities for the King of Pop's three children.

Other sources say that the siblings want to expedite Katherine's access to the money, insisting that she would be more likely to share her fortune with the whole family if given the chance.

But don't feel too bad for the 'paupers', all three enjoy a lavish lifestyle in a gated mansion with round-the-clock security, private schooling and over-the-top vacations.

And if everything goes according to plan, all three will end up as multimillionaires thanks to their father's popularity as well as his wise investment in the Beatles' music catalog.

The kids will have to wait until their 21 to control their assets, but after that, they will get major payouts at ages 30, 35 and 40.

Blanket could get an unbelievable 40th Birthday present: $250million.

Paris Jackson is 14

Prince is 15

Blanket is 10

I love you daddy! Paris shared this picture of herself next to one of 
Michael Jackson as she and her siblings celebrated his 54th birthday

Katherine Jackson's attorney Perry Sanders is arranging an audit of the money so when it starts flowing, every cent will be accounted for.

'My audit is being done to see the details of where the money is coming from and where it is going,' he said.

'The beneficiaries should be entitled to all detailed documentation so they can see what their money is paying for.'

Jackson would have celebrated his 54th birthday on August 29.

@highlight

Paris, Prince, and Blanket's trust fund has yet to be set up and three live on 'meager' allowance

@highlight

Michael Jackson's $600million fortune still frozen as lawyers sort through it

@highlight

Eventually, three kids will get 50 percent while Katherine Jackson will get the other half