By 
Matt Chorley, Mailonline Political Editor

PUBLISHED:

23:31 EST, 28 October 2013


| 

UPDATED:

13:51 EST, 29 October 2013

David Cameron today launched a bold pitch for more investment from Muslim countries, insisting Britain had nothing to fear from foreign money,

The Prime Minister defended overseas investors buying up UK businesses, infrastructure and even football clubs insisting it 'creates wealth, jobs and growth'.

He stressed that Britain's 'unique selling points is its openness' as he said the UK hopes to offer a £200 million Islam-friendly bond as early as next year.

Launch: David Cameron told the World Islamic Economic Forum in London that Britain will become the first non-Muslim country to issue Islamic bonds, known as sukuk

Line-up Leaders attending the World Islamic Economic Forum, including Britain's Prime Minister David Cameron (10th L), pose for a family photo in London

A ground-breaking new Islamic index on the London Stock Exchange is to be launched to establish the City as one of the world's leading centres of Islamic finance.

Addressing the World Islamic Economic Forum (WIEF) meeting in London, the Prime Minister said that the UK also intends to become the first country outside the Islamic world to issue its own Islamic bonds, known as sukuk.

He said: 'I know some people look at foreign companies investing in our businesses, financing our infrastructure or taking over our football clubs and ask – shouldn’t we do something to stop it?

'Well, let me tell you, the answer is “no.”  One of Britain’s unique selling points is its openness and this openness is a vital part of how we ensure our country is a great success story in the global race.

'Foreign investment creates wealth, jobs and growth. And far from weakening our industrial base, that investment actually strengthens it. Islamic investment is already fundamental to our success.'

Defence: Mr Cameron said Britain should be open to foreign investment

The announcements reflect the Government's determination to tap into the fast-growing global market in Islamic investments, which have risen by 150 per cent since 2006. They are expected to be worth £1.3 trillion next year.

'Already London is the biggest centre for Islamic finance outside the Islamic world. And today our ambition is to go further still,' Mr Cameron said.

'Because I don't just want London to be a great capital of Islamic finance in the Western world.

'I want London to stand alongside Dubai as one of the great capitals of Islamic finance anywhere in the world.

The announcements reflect the Government's determination to tap into the fast-growing global market in Islamic investments. File picture

A sukuk is an Islamic bond. It generates returns to investors without breaking Islamic law that prohibits interest.

The essential difference with a conventional bond is that each sukuk represents a share of ownership of the asset you are investing in. Regular bonds represent a share of debt.

Whereas normal bonds do not give the investor a share of ownership in the project they support, sukuk investors get partial ownership.

The criteria for what you can invest in with a sukuk is limited. It must be sharia-compliant. Conventional bonds which can be used for anything.

Bond holders receive regularly scheduled interest payments for the life of the bond - often at a fixed rate - and they are not affected by costs related to the asset.

Sukuk holders receive a share of the profit and accept a share of any loss incurred.

'There are some countries which 
naturally look inwards, pull up the drawbridge and refuse to recognise 
that the way the world is changing affects their future success.

'But Britain will not make that mistake.'

The creation of a new stock exchange index listing Islamic compliant companies is intended to attract more Islamic investors to London.

Experts claim the stock will make it easier for them to identify suitable investment opportunities.

At the same time the Treasury is working on the issue of a bond-like sukuk, worth around £200 million, which could be launched as early as next year.

It will be structured so that investors are paid a fixed return based on the profit generated by an underlying asset.

This is in line with Islamic principles which forbid interest-bearing bonds.

The WIEF, which is being held for the first time in a non-Islamic country, is expected to bring 15 world leaders to London.

More than 1,800 delegates are said to be coming from 115 countries - many of them from the Government's priority high-growth markets.

The UK is also giving £4.5 million - matched by a donation from the Shell Foundation - to the Nomou fund to support 600 medium-sized businesses with the aim of creating more than 15,000 jobs in unemployment-hit Jordan and Egypt as well as other countries in the region.

The Department for International Development is also more than doubling its contribution to the Arab Women's Enterprise Fund to £10 million from £4 million - matched by the Islamic Development Bank.

The Arab world has the lowest rates of female participation in the global labour force and the initiative seeks to help female entrepreneurs from poor communities and rural areas in Jordan, Egypt and Libya.

International Development Minister Alan Duncan said: 'Jobs and growth are critical to the stability of the Middle East and North Africa.

'We are pleased to be working with the Shell Foundation to create thousands of jobs that will contribute towards the stable economic environment needed for growth and prosperity in the region.

'Women are the engine of growth and it is not possible for a country to develop without investing in women.

'We are delighted to be working with the Islamic Development Bank to design and implement exciting projects that will strengthen women's economic contribution to the Middle East and North Africa.'

@highlight

PM announces plans for London to become a centre of Islamic finance

@highlight

UK will become first outside Muslim world to offer Islamic bonds, or 'sukuk'

@highlight

Cameron insists Britain should be open to foreign investment