Sir Bradley Wiggins cycling success is believed to be behind the increase in middle-age men buying bicycles

You can perhaps blame cycling knight Bradley Wiggins for them clogging up the country roads every weekend.

Now MAMILs – or middle-aged men in Lycra, to give them their full name - have pedalled into the latest edition of the online Oxford Dictionary too.

It defines as a MAMIL as 'a middle-aged man who is a very keen road cyclist, typically one who rides an expensive bike and wears the type of clothing associated with professional cyclists'.

The word is among 1,000 new entries added today(thurs) to the free online dictionary OxfordDictionaries.com, which is updated quarterly and prides itself on tracking new and emerging word trends.

MAMIL has been in use since at least 2010 after research by retail analyst Mintel suggested there had been a surge in men of a certain age taking up cycling when they might once have invested in a motorcycle or sports car.

The phenomenon of middle aged men buying an expensive bicycle then intensified after Sir Bradley's success in the Tour de France and Olympics in 2012.

Celebrity fans of slipping on the Lycra and saddling up include actor and Spandau Ballet guitarist Gary Kemp, 55, who once said: 'I'm obsessed, I've done all the major routes of the Tour de France, including the hill climbs.'

But while there is an amusing side to words such as MAMIL and other new entries like 'al desko', an adjective referring to eating while working at one's desk in an office, or 'fresh-air fiend', meaning a person who is very keen on outdoor activities, some other new entries have been criticised because they risk encouraging children to spell common words incorrectly.

The Plain English Campaign said the inclusion of 'fone' (meaning phone), 'hawt' (a chiefly US spelling of hot), 'mahoosive' (meaning exceptionally big) and 'tomoz' (an informal version of tomorrow) could cause problems if youngsters see them and think those are the correct spellings.

Another new entry is 'duck face', defined as 'an exaggerated pouting expression in which the lips are thrust outwards, typically made by a person posing for a photograph'.

Yesterday(wed) Judy Pearsall, editorial director for Oxford Dictionaries, said: 'One of the benefits of our unique language monitoring programme is that it enables us to track in detail how English language evolves over relatively short periods of time. For instance, in this age of the selfie perhaps it's no surprise that average monthly usage of the term duck face is 35 per cent higher in 2014 than it was last year.'

Now MAMILs – or middle-aged men in Lycra, has been added as a new word in the Oxford English Dictionary. Pictured Sir Bradley Wiggins

Finance and business remains a major influence on English, with many terms from there included in the online dictionary today for the first time too.

These include 'flash crash', which is Stock Exchange slang for an extremely rapid decline in the price of a commodity, and 'misery index', an informal measure of the state of an economy generated by adding together its rate of inflation and its rate of unemployment.

New words, senses, and phrases are added to OxfordDictionaries.com once its editors have gathered enough independent evidence from a range of sources to be confident that they have widespread currency in English, a spokesman said.

 

@highlight

Mamils is among 1,000 new words added to the free online dictionary

@highlight

It stands for middle-aged men in lycra and has been used since 2010  

@highlight

Other new words added inlcude al desko, duck face, and mahoosive  