Former Chelsea defender Graeme Le Saux expects Jose Mourinho to target another Wembley final success in the Capital One Cup.

The Premier League leaders play at Championship promotion hopefuls Derby on Tuesday night in the quarter-final stage of the knockout competition.

The final silverware of Mourinho's trophy-laden first spell was an FA Cup success at Wembley in May 2007, but his two League Cup wins came in Cardiff, in 2005 and 2007.

Chelsea boss Jose Mourinho won the League Cup in 2005 and 2007 during his first spell at the club

The likes of Michael Ballack and Arjen Robben (both pictured) helped Chelsea win the League Cup in 2007

Unlike some bosses, Mourinho placed importance on the League Cup during his first spell, with the momentum generated by success aiding his side in the closing months of the season.

Le Saux, speaking on behalf of Capital One, credit card company and sponsor of the League Cup, said: 'It was the first trophy he won with Chelsea.

'I'm sure he enjoyed that experience so much and once you've tasted it you want to experience it again.

'It's something that I'm sure they're as focused on as all the other competitions they're in.'

Le Saux won the competition with Chelsea in 1998.

He added: 'Walking out at Wembley in front of 80,000 people with half the stadium blue and half the stadium red, because we played Middlesbrough, and then going on to win the cup goes down as one of my great memories. It's something that everybody has ambitions to play for.'

Chelsea have stuttered of late, drawing at Sunderland and losing at Newcastle in the Premier League.

Sunderland beat the Blues in the Capital One Cup last term, while Manchester City beat them in an FA Cup run which began at Derby in January.

Mourinho will be hoping to guide his side to a Capital One Cup final at Wembley after winning the FA Cup at the prestigious venue in 2007

Derby boss Steve McClaren will be hoping to upset the odds by knocking Chelsea out of the cup

The Rams are riding high in the second tier and can go into the game with confidence, according to Le Saux.

'For Derby there is the opportunity to prove to themselves that they're more than capable of competing against players of the calibre that Chelsea have,' the former England left-back added.

'The template that Sunderland and Newcastle used against Chelsea is a great opportunity for (Derby boss Steve) McClaren to look at that and use the same blueprint.'

Le Saux is also intrigued by the Premier League after Chelsea's commanding advantage was cut to three points.

He said: 'Credit to Man City for staying in there. Manuel Pellegrini wanted eight straight wins and they're on the way to achieving that.

'They've turned a corner. They were winning games, but their performance has changed: the level of performance, the energy, the ambition and determination is back.

'Rather than us looking at Christmas thinking Chelsea could extend their lead, any one of four teams could be back in the race come the new year.'

Graeme Le Saux was speaking on behalf of Capital One, credit card company and sponsor of the League Cup

 

@highlight

Jose Mourinho won the League Cup at Chelsea in 2005 and 2007

@highlight

Chelsea take on Derby in the quarter-final stage of the cup competition 

@highlight

Graeme Le Saux insists Derby will want to prove themselves against Blues