To Ally McCoist, a rough calculation of how much Scottish football has missed Old Firm competition can be made by adding empty blue seats to empty green seats.

There were plenty of those for the midweek League Cup ties that took Rangers and Celtic into the last four of the competition. Combine the swathes of space at Ibrox on Tuesday night with the similar scene at Parkhead the following evening and another 70,000 spectators could have been accommodated.

McCoist knows full well, however, that there are few stadiums on the globe with the capacity to accommodate demand if Saturday's semi-final draw brings about a first meeting since April 2012.

Ally McCoist believes a Rangers vs Celtic League Cup semi-final could fill the Maracana in Rio

‘The irony is not lost on me,’ said the Rangers manager. ‘You had 16,000 at the Celtic game on Wednesday. You had 13,000 at our game on Tuesday night.

‘But if Rangers play Celtic in the semi-final or the final you could play the game at the Maracana.

‘In terms of the greater good of Scottish football it would be a good thing. Everybody would look forward to the game.’

There would doubtless be some willing to incur the travelling expense even it was Sugarloaf Mountain, rather than Mount Florida, forming the backdrop to the semi-final.

The odds on a long-awaited derby encounter are shorter than they have ever been since Rangers were last resident in the top flight.

The club’s financial meltdown of 2012 – which eventually saw an asset transfer to a new company set up by Charles Green and his backers - left the other 11 top flight sides with a decision to make. Ten decided to vote against their re-admission to what was then the SPL, leaving Rangers to eventually find a place in the old Third Division.

McCoist has made his views clear on that process, believing it was fuelled by a form of blood-lust that defied the best interests of the Scottish game.

The excitement generated by the possibility of the Old Firm locking horns once more is, he feels, further evidence of how misguided some were.

McCoist would relish the return of the Old Firm clashes but must rely on cup competitions 

‘I can understand the interest,’ he said. ‘Gone are the days of “we don’t need Rangers in the top flight”.

‘Sadly, because it’s too late, there is now a little bit of common sense being shown.

‘It’s clear we do need Rangers, Hearts and Hibs in the top-flight.

‘Gordon (Strachan) is doing a fantastic job for the national team, but in the best interest of Scottish football we need our big clubs in the top flight.

‘With Rangers being in the lower divisions there was clearly going to be no scope for an Old Firm game unless we drew each other in the cups.

‘The majority of people, if we do draw each other, can actively look forward to an Old Firm game and I more than anyone can appreciate that.

‘I have great pals who are Celtic supporters as well. I’ve had boys coming up to me in the street and they are dying for you to get back. Celtic supporters, and Rangers supporters obviously, who miss the intensity and excitement of that Old Firm game and the chase for the title.’

The absence of the fixture has also been felt financially. It was what drove the television deal as far as satellite broadcasters were concerned, as witnessed by the subsequent renegotiation.

Remarkably, the Premiership is also without title sponsor for a second season. So, does McCoist feel those most vocal about demoting Rangers in 2012 may now regret their stance? 

Kenny Miller (left) celebrates with goalscorer Lewis Macleod as Rangers beat St Johnstone in the League Cup

‘Knowing the pig-headedness of some of the people involved, no they won’t,’ he insisted.

‘But let’s be honest, was it for the greater good of Scottish football? Of course it wasn’t. Absolutely wasn’t.

‘But we are where we are and things have happened. There is no use in looking back the way because we can’t change anything.’

The significance of the Old Firm being drawn together would clearly extend way beyond the Hampden pitch – just ask Police Scotland – but ultimately it would be about the two biggest clubs in the country being reunited in a sporting contest.

Celtic would obviously start as clear favourites, hence McCoist suggesting in midweek that he would rather avoid them to bolster chances of winning the tournament.

Yet the 52-year-old is also growing in confidence about his side’s chances should it happen and admits part of him longs for the renewal of old rivalries. The scorer of 27 Old Firm goals as a player, he recorded two wins and two defeats against Celtic during his one season of top-flight management.

‘I’ve missed the games and I think Scottish football has missed them,’ he added.

‘Contrary to what one or two people might have said at the time, it still was one of the biggest club matches in the world.

Celtic's John Guidetti scored three against Partick Thistle to send his side into the last four

‘You can talk about differences of quality, absolutely. But in terms of atmosphere it is certainly up there with anything.

‘I didn’t miss them two years ago because I didn’t really fancy playing Celtic or indeed any real top-flight club.

‘Last year we were better and competed reasonably well against Dundee United. This year, we feel we are slightly better again to handle the threat of a Celtic, an Aberdeen or a Dundee United.’

The possibility of an all-Glasgow semi-final has, for however short a time, removed the focus from the off-field turmoil at Ibrox.

Two associates of Mike Ashley - Derek Llambias and Barry Leach - this week started work as consultants in the first moves to form a new regime heavily influenced by the Sports Direct billionaire.

McCoist, though, will head into today’s William Hill Scottish Cup third round tie at Dumbarton without any fresh information about the way ahead for the club.

‘I spoke to the chairman yesterday on the phone and he was just keeping me up to speed about the board and the search for a chief executive,’ added McCoist.

‘Again, he just said to concentrate on things we can effect, which is following on from Tuesday’s result with a performance that can hopefully get us into the next round of the Scottish Cup.’

 

@highlight

Rangers could draw Celtic in the League Cup semi-finals 

@highlight

There has been no Old Firm derby since April 2012

@highlight

Rangers would welcome a distraction to their off-field problems 