Britain faces its first dose of deflation for more than 50 years, the Bank of England declared yesterday.

In a boost to family finances in the run-up to the general election, Governor Mark Carney said prices generally would probably fall in the coming months as the cost of essentials such as petrol and food come down.

Inflation has already fallen to 0.5 per cent following an oil price slump from $115 a barrel last summer to below $60 last night.

Mark Carney has said inflation rates could turn negative in 2015

Mr Carney said the falling oil price was ‘unambiguously good’ for the economy, adding: ‘It is more likely than not that headline inflation will turn negative at some point in the spring and will remain subdued for much of the rest of the year.’

An inflation rate below 0 per cent marks the onset of deflation, when the price of goods and services across the board falls.

If prices do drop, then rising wages and the first bout of deflation since 1960 will push household incomes up at the fastest rate for more than a decade, according to the Bank.

It also opens the door to a further cut in interest rates, a move all but ruled out by the Bank until now. David Cameron and George Osborne will hope that the feel-good factor generated by the boost to family budgets will translate into votes on polling day in May.

However, Mr Carney said that if falling prices become ‘self-fulfilling’ – and risk triggering a dangerous bout of the deflation seen in Japan – then interest rates could once again be cut. 

This would make mortgages even more affordable for borrowers already benefiting from some of the cheapest home loans in history. But it would be a blow to savers, who have lost out since rates hit a record low of 0.5 per cent in March 2009.

The 0.5 per cent interest rates are already an historic low after soaring to 17 per cent in the 1980s

Mr Carney said if the Bank needed to tackle deflation, its monetary policy committee could cut interest rates and add to the £375billion of emergency funds it has already printed through quantitative easing.

But he warned: ‘Negative inflation rates are unlikely to endure for very long. It is pretty clear that the most likely next move is an increase in interest rates.’

As he published the Bank’s forecasts in its quarterly inflation report, Mr Carney said any rate rise would be ‘limited and gradual’.

Investors do not expect the first rate rise since 2007 to come until April 2016. Rates are not forecast to reach 1.5 per cent until 2019.

Chancellor of the Exchequer George Osborne (right) will be hoping the feel-good factor generated by the boost to family budgets will translate into votes on polling day in May

Mr Carney said the prospect of a temporary dose of deflation ‘masks stronger underlying dynamics’ in the UK.

The Bank estimated the economy grew by 3.1 per cent in 2014 – stronger than the 2.6 per cent rise reported by the Office for National Statistics and the best performance since 2003. It predicted growth of 2.9 per cent till the end of 2016.

Incomes after tax are expected to grow by 3.5 per cent this year – the best performance since 2001 – leaving families feeling richer.

Mr Carney said: ‘The combination of rising wages and falling energy and food prices will help household finances and boost the growth of real take-home pay this year.’

But a feel-good factor ahead of the election could hit Labour leader Ed Miliband, who has railed against a ‘cost of living crisis’. 

Sorry we are not currently accepting comments on this article.

@highlight

Mark Carney said inflation 'likely' to turn negative within months 

@highlight

As a result rates could be cut from the current record low of just 0.5% 

@highlight

The Bank of England chief said falling prices would boost the economy 

@highlight

He said inflation is likely to stay at around zero between April and October

@highlight

Boost to family finances in run-up to the General Election

@highlight

But the Bank warned it is still more likely that rates will rise over time 