Leaked documents from the NSA recently revealed a covert USB stick that could be used to target secure, offline networks.

But the device costs a staggering $20,000 (£13,200).

Now, a team of hackers has created its own version of the surveillance kit using a cheap circuit board and other parts that total just $20 (£13).

Scroll down for video 

The Turnipschool device was demonstrated at the SchmooCon hacking convention. It features a radio-frequency implant inside a USB stick (stock image pictured), alongside a circuit board, transceiver and a cover. It can be connected to a network and potentially used to attack the PC. The parts total around $20 (£13)

Called Turnipschool, the project was demonstrated at the SchmooCon hacking convention in Washington at the weekend.

Last year, German computer scientists proved that malware can travel between machines using sound waves that are inaudible to unsuspecting humans.

Using built-in microphones and speakers in laptops, the researchers managed to transmit passwords and small amounts of data between machines 65ft (19 metres) away from each other.

They came up with a hack using sound to steal data from protected machines and suggested that noise could be used to pass data between target computers and the ‘hacker’ machine.

The researchers chose to use sounds that are too high pitched for humans to hear and harnessed the microphone and speakers in a Lenovo T400 computer to transmit keystrokes from one computer to another.

The NSA hardware it is based on was dubbed Cottonmouth-I.

It lets hackers launch a man in the middle-style attack by plugging into a keyboard or mouse, for example, and installing malware on computers.

The device was designed to also be able to control the malware, even on so-called ‘airgapped’ computers.

An air-gap or air wall is a network security measure.

The gaps were designed to make sure secure computer networks are physically isolated from unsecured networks, such as the internet or a local area network.

Turnipschool was set up deliberately to see if a hobbyist could create something similar to Cottonmouth-1, in terms of size and functions.

It is part of a wider project called the NSA Playset that attempts to recreate NSA surveillance tools.

The project was presented at the convention by wireless security researcher Michael Ossman, with collaborators Dominic Spill and Jared Boone.

The tool features a processor with a built-in radio on a circuit board that fits inside a moulded USB plug.

The Turnipschool project was inspired by a covert stick called Cottonmouth-I that appeared in recently leaked NSA documents (pictured) and cost $20,000 (£13,200) each. It is part of a wider project called the NSA Playset that attempts to recreate NSA surveillance tools

An air-gap or air wall is a network security measure. 

It was designed to make sure secure computer networks are physically isolated from unsecured networks, such as the internet or a local area network.

Researchers from Israel recently designed computer software that logs keystrokes.

This software transmits strokes via FM radio signals generated by the PC's graphics card.

The data is picked up by a nearby mobile, equipped to pick up radio signals. 

This can be done without being detected by the user, but does rely on the software being installed on the computer in the first place.

Since FM radio signals travel over long distances, the receiver could be placed in another building. 

The circuit board is custom printed and costs $1.50 (99p) to make.

The microcontroller is made by Texas Instruments, with a radio-frequency transceiver that costs around $4 (£2.65).

Other parts include a 3D-printed injection mould and plastic cover.

At the moment, Turnipschool has the potential to connect and ‘sniff’ the network, and the next step is to make it attack the computer its connected to.

‘USB implants were among the most talked about gadgets in the NSA catalogue after it leaked last year,’ said the researchers.

‘Concealed in cables and connectors, these devices appear to be designed primarily to provide covert communication channels to malware operating on a host computer.

‘Secondarily it seems that they could be used to implement USB attacks or to monitor connected USB devices.

‘[We] demonstrate tools we've built for the same capabilities.’

 

@highlight

NSA uses a covert surveillance device in a USB stick called Cottonmouth-I

@highlight

Leaked documents recently revealed the spy tool costs $20,000 (£13,200)

@highlight

A team of hackers has created its own version of the surveillance kit

@highlight

They put a radio-frequency implant inside a USB stick

@highlight

This involved a circuit board, transceiver and a cover - totalling $20 (£13)

@highlight

Called Turnipschool, the team demonstrated it at SchmooCon, Washington