By
Ellie Zolfagharifard

PUBLISHED:
  
  
      08:00 EST, 26 February 2014
    
  

 | 
  UPDATED:
  
  
      08:22 EST, 26 February 2014

The mystery surrounding a whale graveyard found beside the Pan-American Highway in Chile has finally been solved.

Scientists believe the remarkable fossil site, dating from between six and nine million years, is the first example of repeated mass strandings of marine creatures.

Hidden in Atacama Desert for millions of years, the fossils came from four separate whale strandings, suggesting they were killed by a similar cause: toxic algae.

Scroll down for video...

Pictured is a graveyard of whales found beside the Pan-American Highway in Chile. Scientists now think they can explain how so many of the animals came to be preserved in one location millions of years ago

The find, made in 2010, has been described as the most extraordinary marine mammal fossil site on the planet.

It included the remains of 10 kinds of marine vertebrates from the site, named Cerro Ballena which is Spanish for ‘whale hill.’

In addition to the skeletons of more than 40 baleen whales, the team found the remains of a species of sperm whale and a walrus-like whale, both of which are now extinct.  They also found skeletons of billfishes, seals and aquatic sloths.

The team of Chilean and Smithsonian paleontologists made 3D digital models of the skeletal remains on sites and then removed the bones for further study in the lab.

The skeletons are well preserved at four distinct levels. Most of the creatures were belly-up, suggesting death at sea or shortly after washing ashore

Researchers only had two weeks to analyse the fossils as the site was soon to be covered by the Pan-American Highway.

A major solution came in the form of 3D technology. Professor Pyenson brought a team of Smithsonian 3D imaging experts to Chile, who spent a week scanning the entire dig site.

Although all the fossils found from 2010 to 2013 have been moved to museums in the Chilean cities of Caldera and Santiago, the Smithsonian has archived the digital data, including the 3D scans, here.

Anyone can download or interact with 3D models of the fossil whale skeletons, scan Google Earth maps of the excavation quarries, look at a vast collection of high-resolution field photos and videos or take 360-degree tours of the site.

The enormous wealth of fossils that the team examined represents only a fraction of the potential at Cerro Ballena, which remains unexcavated. The scientists believe that the entire area preserves several hundred fossil marine mammal skeletons, awaiting discovery.

What intrigued them most was how the skeletons were arranged and the fact that they were nearly all complete.

Many had come to rest facing in the same direction and upside down, suggesting that they died from the same cause.

The four different fossils levels indicated it was not one episode but four separate events that took place over a period of several thousand years.

Scientists believe these animals were all poisoned by the toxins that can be created in some algal blooms. This is the main cause for repeated mass strandings in today's marine animals.

 ‘There are a few compelling modern examples that provide excellent analogues for the patterns we observed at Cerro Ballena, said  Nicholas Pyenson, paleontologist at the Smithsonian’s National Museum of Natural History and lead author of the research.

‘In particular, one case from the late 1980s when more than a dozen humpback whales washed ashore near Cape Cod, with no signs of trauma, but sickened by mackerel loaded with toxins from red tides.’

‘Harmful algal blooms in the modern world can strike a variety of marine mammals and large predatory fish. The key for us was its repetitive nature at Cerro Ballena: no other plausible explanation in the modern world would be recurring, except for toxic algae, which can recur if the conditions are right.’

Paleontologists estimate that the skeletons are between 6 million and 9 million years old. Scientists think the mass strandings occurred over a period of more than 10,000 years

Algal blooms are common along the coasts of continents. They are fed by vital nutrients, such as iron, released during erosion and carried by rivers flowing into the ocean.

Because the Andes of South America are iron-rich, the runoff that has occurred along the west coast of South America for more than 20 million years has long provided the ideal conditions for harmful algal blooms to form.

From their research, the scientists believe that toxins generated by harmful algal blooms poisoned the creatures near Cerro Ballena five–11 million years ago, causing relatively rapid death at sea.

Their carcasses then floated toward the coast, where they were washed into a tidal flat by waves. 

In this image, the whale fossils undergo 3D surface scanning in order to create a digital record of the arrangement of the skeletons

The fossils were uncovered in the Atacama Desert, next to the Pan-American Highway in Chile

Once stranded on the tidal flat, the dead or dying animals were protected from marine scavengers, and there were no large-land scavengers in South America at this time.

‘Cerro Ballena is the densest site for individual fossil whales and other extinct marine mammals in entire world, putting it on par with the La Brea Tar Pits or Dinosaur National Monument in the U.S.,’ Professor Pyenson said.

‘The site preserves marine predators that are familiar to modern eyes, like large whales and seals.

'However, it also preserves extinct and bizarre marine mammals, including walrus-like whales and aquatic sloths.

‘In this way, the site is an amazing and rare snapshot of ancient marine ecosystems along the coast of South America.’

Chilean and Smithsonian paleontologists are pictured studying several fossilized whale skeletons at Cerro Ballena, also known as 'Whale Hill'

 

@highlight

Fossils found in Atacama Desert next to Chile's Pan-American Highway

@highlight

Skeletons were all resting in the same way and found in 4 different layers

@highlight

Scientists say this suggests that creatures died in four mass strandings

@highlight

The toxins generated by harmful algal blooms poisoned the creatures near Cerro Ballena, causing relatively rapid death at sea