The new year is expected to bring rising chicken egg prices across the U.S. as California starts requiring farmers to house hens in cages with enough space to move around and stretch their wings.

The new standard backed by animal rights advocates has drawn ire nationwide because farmers in Iowa, Ohio and other states who sell eggs in California have to abide by the same requirements.

To comply, farmers have to put fewer hens into each cage or invest in revamped henhouses, passing along the expense to consumers shopping at grocery stores. California is the nation's largest consumer of eggs and imports about one-third of its supply.

Caged chickens lay eggs in a chicken house built decades ago at an egg farm in San Diego, California

Jim Dean, president and CEO of Centrum Valley Farms in Iowa and Ohio, said one of his buildings that holds 1.5 million hens is now about half full to meet California's standards, and another building may have to be completely overhauled.

Farmers like him in cold climates will have to install heaters to replace warmth formerly generated by the chickens living close together. Dean said that's something people in sunny California didn't consider.

'You're talking about millions upon millions of dollars,' he said. 'It's not anything that's cheap or that can be modified easily, not in the Midwest.'

California voters in 2008 approved the law backed by animal rights advocates to get egg-laying hens out of cramped cages and put them by Jan. 1, 2015, in larger enclosures that give them room to stretch, turn around and flap their wings.

State legislators followed with the companion piece in 2010 requiring the out-of-state compliance.

In anticipation, egg prices have already risen, said Dave Heylen of the California Grocers Association, adding that the holiday season, cold weather across the country and increased exports to Mexico and Canada also contributed to a year-end price spike. He said he expected that supplies would remain adequate to meet demand.

A farm worker collects eggs in an old-fashioned chicken house at an egg farm in California

Daniel Sumner, an agricultural economist at the University of California, Davis, said prices initially could rise dramatically this year but he expects them to eventually settle anywhere from 10 and 40 percent higher in California and return to their normal price elsewhere in the country.

If farmers cut back the number of chickens so they can comply with California's cage law, Sumner said that could reduce the number of eggs available.

'When there's that much uncertainty, I'm thinking there may be some disruption in the market,' he said.

Farmer Frank Hilliker had take a loan of $200,000 to comply with the new requirement, and is in the process of converting to a cage-free system

Wayne Pacelle, president and CEO of the Humane Society of the United States, said he believes the costs to consumers will be minimal and worth it for the welfare of chickens, which provide enough eggs for each person to consume on average 250 a year.

For decades, he said, farmers have crammed six to eight chickens in small cages without room to move.

'This is the last bastion of cage confinement in industrial ag,' said Pacelle, whose organization led the reforms. Starbucks in December said it will eliminate the sale of eggs from caged hens, he said, following the lead of Burger King and Whole Foods.

The California Department of Food and Agriculture, independent of the voter initiative, implemented rules that give chickens 70 percent more room, which Pacelle said is better but not enough.

Low-income people who rely on eggs as an economical source of protein may be hurt the worst by California's cage law, says a report this week by the Egg Industry Center at Iowa State University. Anticipating a 15 percent increase, the cost of a dozen eggs could rise by 27 cents, and a family of four could pay $15.93 more a year, the report says.

California has prevailed in lawsuits, including six from major egg-producing states that argued the state is dictating market prices in other states in violation of the Commerce Clause of the Constitution. Appeals are pending.

Ken Klippen of the National Association of Egg Farmers said California's egg law, in addition to driving up the cost at the grocery store and putting pressure on egg supplies, will result in more injuries to chickens because housing them in larger pens means they are more likely to run, breaking a leg or wing.

'You're not going to help the chicken,' he said. 'You're not helping consumers.'

 

 

@highlight

The new standard is backed by animal rights advocates but has has drawn ire from farmers in other states who must to comply to sell in California

@highlight

Added cost of rehousing chickens will contribute to higher prices at the grocery stores

@highlight

California is the nation's largest consumer of eggs and imports about one-third of its supply

@highlight

Prices will rise 'dramatically' at first, but then settled at 10 to 40percent higher than before 