By 
James Chapman And Tim Shipman

PUBLISHED:

09:45 EST, 11 June 2012


| 

UPDATED:

05:44 EST, 12 June 2012

George Osborne yesterday admitted he played a key part in the ‘risky’ appointment of former News of the World boss Andy Coulson as the Tories’ chief spin doctor.

The Chancellor said he had accepted an assurance from Mr Coulson, who had resigned from the newspaper in the wake of the phone hacking allegations, that there were no more revelations to come.

In evidence to the Leveson Inquiry, Mr Osborne revealed that around a third of his meetings with media owners and editors since 2005 were with News International – including one meeting with the Murdochs at a ski chalet in Davos, Switzerland, in early 2009.

No secret pact: Mr Osborne denied that a meeting with the Murdochs, him and David Cameron to seal election backing never happened

Pals: Mr Osborne said he remained friends with Andy Coulson but 'sadly' had not been able to talk to him for more than a year

Mr Osborne also said he had been at a crucial No 10 meeting where it was decided to remove responsibility for deciding the BSkyB bid from Business Secretary Vince Cable and handing it to Culture Secretary Jeremy Hunt.

That idea, he said, had come from Sir Jeremy Heywood, then No 10’s Permanent Secretary and now the Cabinet Secretary.

The Chancellor said his main concern when Mr Cable was caught boasting he had ‘declared war’ on the Murdoch empire in 2010 was to come up with a solution that would not mean the Business Secretary being sacked or having to resign.

Mr Osborne suggested that would have threatened the Coalition.

Claims: Former Prime Minister Gordon Brown, leaving the Leveson Inquiry and his wife Sarah today said the Tories had done a deal with News Corp, which Mr Osborne said was nonsense

Mr Osborne dismissed the idea that the Tories entered into some sort of deal, either explicit or implied, with Rupert Murdoch to hand him full ownership of BSkyB in return for the support of his papers.

In an apparent reference to Gordon Brown, who suggested in evidence to the inquiry that he believed such an arrangement had been made, Mr Osborne said only a ‘real fantastist’ could believe such a ‘vast conspiracy theory’.

Controversy: Leveson heard that Mr Osborne had fought to save Vince Cable's job despite his going to war with Murdoch comments

He said the Conservatives would have had to have somehow arranged for Mr Cable to be ‘secretly recorded’ by a newspaper saying he had declared war on the Murdochs so that responsibility could then be handed to Mr Hunt.

‘It is complete nonsense and the facts simply don’t bear it out,’ he said. Mr Osborne insisted he had not had a strong view about the merits of the Murdochs’ £8billion takeover bid for BSkyB, adding: ‘As far as I could see it was just going to cause us trouble one way or the other.’

The Chancellor said it had been clear that if the deal was approved by the Government, it would offend one set of newspapers and broadcasters who were opposing the takeover, while if it was blocked it would offend the Murdoch camp.

Pressed on his own attitude to the proposed takeover, the Chancellor replied: ‘As far as I could see, it was about increasing the shareholding in a company that most people would think they ran anyway.’

On Mr Coulson’s appointment, Mr Osborne said the former editor denied knowing anything about phone hacking at the News of the World going beyond one single reporter.

As shadow chancellor, he said he briefly asked Mr Coulson about phone hacking in March 2007, when he was attempting to recruit him for the job of director of communications for the Conservative Party.

Links: Lobbyist Fred Michel gave evidence to Leveson last month and had sent hundreds of texts and e-mails to the Government about the BSkyB bid

He said he had asked Mr Coulson ‘in a general sense, as you might do in a social encounter, whether there was more in the phone hacking story that was going to come out, that was not already public, that we needed to know about – and he said no’.

He said he had been aware of the ‘risks’ and potential controversy that would be generated by hiring Mr Coulson, but recommended to David Cameron that he should get the job. ‘It was not a consideration: let’s hire the ex-News International man. It was: let’s hire this very experienced ex-newspaper editor,’ Mr Osborne added.

He said he still regarded Mr Coulson as a ‘personal friend’, but added: ‘Sadly I’ve not been able to speak to him for a year.’

Big Day: The Chancellor pictured arriving at the Royal Courts of Justice to appear after former Prime Minister Gordon Brown

The Chancellor yesterday sent the strongest signal yet that the Government will not adopt plans for regulating the Press that stifle freedom of speech.

George Osborne rejected proposals to separate news and comment, the ‘kitemarking’ of newspapers or allowing ‘class action’ complaints by offended groups.

He also warned against attempting to draw up a code that defined what was in the national interest.

Mr Osborne said that if the Leveson Inquiry came up with proposals that target print media but exclude the internet, everyone involved would have been wasting their time.

His remarks echoed those of Education Secretary Michael Gove, who insisted press freedoms must be preserved at all costs and warned Lord Justice Leveson that any cure could prove ‘worse than the disease’. They suggest an emerging consensus among Tory ministers appearing at the inquiry.

On Thursday, David Cameron is also expected to ‘put down a marker’ that the Government will not accept over-the-top proposals on press regulation.

Lord Leveson said he had heard evidence from groups who felt ‘very disadvantaged’ by how they were portrayed in the Press, mentioning the disabled, migrants and those who change gender.

Asked if he agreed there should be some mechanism for such groups to complain about or prevent negative coverage, Mr Osborne replied: ‘There are laws to prevent racial discrimination or sexual orientation discrimination.

'You mention immigrant groups – they are obviously some of the most vulnerable people in our society. Equally there’s a huge concern out there ... about immigration controls.

‘If that’s not allowed to be aired, then I think we stifle public debate.’

He insisted it was vital that the Press could air views that were not fashionable or shared by the Establishment – citing the example of Eurosceptic opinion.

He said that a decade ago it was regarded as ‘faintly eccentric’ to be against British membership of the euro, with such views disparaged by the BBC.

But newspapers including the Daily Mail, the Daily Telegraph and The Sun had campaigned against euro membership and contributed to what ‘in hindsight was one of the most important economic and political decisions’ ever made by Britain.

However, Mr Osborne said the Press Complaints Commission required a ‘complete overhaul’ and that victims of press mistreatment needed ‘better redress’.

@highlight

Andy Coulson was 'the best man for the job,' he told the Inquiry, discussing why he appointed him as No. 10 spin doctor

@highlight

He added that he wanted Vince Cable to keep his job despite saying he had 'declared war' on Murdoch

@highlight

Any conspiracy to hand the decision to Jeremy Hunt was nonsense, he added