By 
Daily Mail Reporter

PUBLISHED:

14:02 EST, 8 January 2013


| 

UPDATED:

16:28 EST, 8 January 2013

The problem-plagued Boeing Co 787 Dreamliner suffered another scare today as a fuel leak forced a Japan Airlines flight to be cancelled at Boston's Logan International Airport.

It's the second problem with the jet class in as many days as another plane caught fire Monday when a battery exploded shortly after landing at the same airport.

Today's incident occurred after the plane left the gate prior to takeoff for Tokyo and it was discovered that about 40 gallons of fuel had split, officials said.

WATCH VIDEO BELOW

Boston firefighters work on Monday to douse a fire in a Japan Airlines 787 Dreamliner's cargo hold

No fire or injuries occurred in today's incident.

The U.S. National Transportation Safety Board, which 
is investigating the fire that occurred on Monday, said the latest problem wouldn't warrant an investigation because there was no accident, according to Reuters.

Monday's fire was discovered when a
mechanic inspecting the Japan Airlines Co Ltd jet saw the smoke in 
the cockpit while performing a routine post-flight inspection.

Smoke continues to billow out from the jetliner on Monday

Passengers had just exited the plane 15 minutes before the blaze broke out.

A fire crew responded and determined 
that a battery used to power the plane's electric systems when the 
engines are not running had exploded, authorities said.

The mechanic was the
only person on board the plane when the smoke was discovered and no one
was hurt by the blaze.

The
fire was the latest reported mechanical failure in a string of incidents
affecting the Dreamliner, which was also plagued by production problems
that delayed initial delivery by 3-1/2 years.

The design project began in the late 1990s. Boeing finally rolled out its first Dreamliner last year.

There are currently 13 Dreamliners in service.

Monday's explosion caused a fire but no passengers were hurt

The U.S. jet maker's shares fell more than 3 percent to $75.34 on the news.

Boeing spokesman Marc Birtel said of Monday's fire, 'We are aware of the event and are working with our customer.'

The company has yet to respond to today's incident.

The
787 relies heavily on electrical power to drive onboard systems that in
other jet models are run by air pressure generated by the engines. It 
also suffered electrical problems during testing that prompted a 
redesign.

The
aircraft is Boeing's first to be made of carbon composites rather than 
aluminum, a change that lowers the plane's weight and allows it to burn 
less fuel.

Boeing stock dropped 3 points on the news of the fire

The
Dreamliner has suffered a string of mishaps with electrical systems in 
recent weeks.

On Dec. 4, a United Airlines flight from Houston to 
Newark, New Jersey, made an emergency landing after it appeared that one
of its power generators failed.

On Dec. 13, Qatar Airways said it had 
grounded one of its three 787 jets because of the same problem United 
had experienced.

On Dec. 17, United said that a second 787 in its fleet 
had developed electrical issues.

Boeing
Chief Executive Jim McNerney last month argued that the 787 has not 
experienced an unusual number of problems for a new aircraft.

Boeing competes with European jet maker Airbus.

WATCH VIDEO HERE

@highlight

New jet has had a history of mishaps, design problems and delays

@highlight

Latest two incidents were both Japan Airlines flights

@highlight

Recent mechanical failure forced jet to make emergency landing

@highlight

United Airlines grounded entire Dreamliner fleet after electrical problems

@highlight

Boeing stock drops 3 points on news of fire