Footballer Nicolas Anelka is facing a police investigation after he celebrated a goal with a ‘reverse Nazi salute’.

The European Jewish Congress called for him to receive the same punishment that would be handed down for a Nazi salute, while a senior French politician said the gesture was ‘clearly anti-Semitic’.

The 34-year-old West Bromwich Albion striker claimed he performed the gesture as a ‘special dedication’ for his comedian friend Dieudonne M’bala M’bala, who invented it.

Scroll down for video

Investigation: The FA is continuing its investigation into the seriousness of Nicolas Anelka's goal celebration

Racist or harmless? The gesture made by West Brom striker Nicolas Anelka after scoring his first goal

France's sports minister took to Twitter tonight to condemn the Anelka's behaviour. Valerie Fourneyron said: 'Anti-Semitism and incitement to hatred have no place on a football field'

French authorities have been debating whether the comic's performances should be banned, while anti-racism groups say it is regularly used to bait Jews.

A spokesman for the Met Police said they take all allegations of hate crime seriously.

The spokesman added: 'We will consider whether any police action is required after consultation and consideration of the circumstances.

'We are aware of the level of concern generated by any high profile incident and therefore take a proactive approach, working with our partners to establish what course of action is most appropriate.'

But the striker's coach has stood by him saying claims that it was anti-Semitic are 'absolute rubbish'.

West Brom coach Keith Downing said former French international Anelka was 'totally surprised' by the furore he had provoked.

'Racist': Comedian Dieudonne M'Bala M'Bala, who has been fined several times for defaming Jews

'I'm aware of it but it has got nothing to do what is being said,' Downing replied when asked about the gesture.

'It
 is dedicated to a French comedian he knows very, very well. He uses it 
in his act and I think speculation can be stopped now, it is absolute 
rubbish really.

'He is totally unaware of what the problems were or the speculation that has been thrown around, he is totally surprised by it.'

An undated photo circulated on Twitter claims to show Anelka, a practicing Muslim, and 47-year-old Dieudonne making the gesture together.

It comes after French Interior Minister Manuel 
Valls said yesterday that he was considering banning Dieudonne's upcoming shows because they 
regularly attack the memory of Holocaust victims.

'Dieudonne has been repeatedly convicted for defamation, insulting behaviour and incitement to racial hatred,' said Mr Valls.

'This is a repeat offender and I intend to act with the greatest firmness, under the law,' Mr Valls added.

More
 than 70,000 French Jews died during the Second World War, and Dieudonne
 has been fined in France six times for defaming Jews.

In 2008 he was fined the 
equivalent of just over £6,000 for describing Holocaust remembrance
 as 'memorial pornography'.

The comedian insists that the gesture is anti-establishment, not anti-Semitic. 

Friends: West Brom acting head coach Keith Downing says that the gesture was a dedication from Anelka (right) to his French comedian friend Dieudonne (left)

Dieudonne calls the gesture 'la quenelle' - the word for an elongated creamed fish dumpling - and says it stands for his anti-Zionist and anti-establishment views, not anti-Semitism.

The gesture has gone viral on social media recently, with mostly young fans displaying it at parties and sports events. Some do it while in the audience at live television shows.

Two soldiers were sanctioned by the army in September for making the gesture in uniform in front of a Paris synagogue.

When Radio France's Patrick Cohen asked on air last week if the media should pay so much attention to him, Dieudonne suggested the journalist should get ready to emigrate.

'When I hear Patrick Cohen speaking, I say to myself, you see, the gas chambers ... too bad,' he said.

However, Mr Valls added: 'Dieudonne M'bala M'bala doesn't seem to recognise any limits anymore.

'From
 one comment to the next, as he has shown in several television shows, 
he attacks the memory of Holocaust victims in an obvious and 
unacceptable way.'

The 
'quenelle' is a key component of the Dieudonne act, and he has himself 
threatened to sue those who object to it.

Dieudonne is particularly critical of Israel's occupation of Palestine territories.

A Paris-born son of a 
Cameroonian father and French mother, he began his comedy career with a 
Jewish sidekick in the early 1990s and appeared in several films.

Originally
 active with anti-racist left-wing groups, he began openly criticizing 
Jews and Israel in 2002 and ran in the European elections two years 
later with a pro-Palestinian party.

Police broke 
up his one-man-show in a Brussels theatre last year for suspected 
anti-Semitic hate speech, but he was not convicted.

France's sports minister took to Twitter tonight to condemn the Anelka's behaviour.

Valerie Fourneyron said: 'Anti-Semitism and incitement to hatred have no place on a football field.'

Roger
 Cukierman, president of the Paris-based council of French Jewish 
organisations, the CRIF, said of the comedian: 'It's the Nazi salute in reverse. Very 
clearly, Mr Dieudonne is developing a nearly professional anti-Semitism 
under the cover of telling jokes.'

Doubling up: Anelka (left) is on the spot to score West Brom's second goal of the afternoon

Anelka could face punishment in France if his actions can be shown to be offensive, insulting, abusive or political.

Almost all English Premiership games are shown live in France, where Paris-born Anelka is a household name.

France
 has experienced rising levels of violence against its Jewish population
 in recent years. In March 2012, a rabbi and three students were killed 
at a Jewish school in Toulouse. 

@highlight

West Brom striker, 34, caused outrage by performing a 'quenelle' today

@highlight

'Reverse Nazi salute' involves touching right shoulder with left hand

@highlight

Coach Keith Downing said claims it was anti-Semitic are 'absolute rubbish'

@highlight

Gesture popularised by the firebrand comic Dieudonne M'bala M'bala

@highlight

French authorities have debated if his performances should be banned

@highlight

France's sports minister condemned Anelka's behaviour tonight on Twitter