A total of five possible Republican presidential candidates have now entered the minefield of vaccine politics, with Ben Carson, Ted Cruz and Carly Fiorina joining in the fight launched Monday by Gov. Chris Christie and Sen. Rand Paul.

The scrum grew as news emerged that President Barack Obama's $4 trillion 2016 budget proposal cut $50 million from federal government vaccination programs. 

Fiorina, a former CEO of Hewlett-Packard who is busily burnishing her conservative credentials in advance of the 2016 race, said 'parents have to make choices for their family and their children' about whether to have them immunized against measles, mumps, rubella and other deadly diseases.

She spoke to a Buzzfeed writer last month.

'I think vaccinating for measles makes a lot of sense. But that's me,' Fiorina said. 'I do think parents have to make those choices. I mean, I got measles as a kid. We used to all get measles ... I got chicken pox, I got measles, I got mumps.'

Scroll down for video 

Carly Fiorina, former CEO of Hewlett-Packard, said she supports parents' 'choices' in whether or not to vaccinate their children

SILLINESS: Texas Sen. Ted Cruz defended New Jersey Gov. Chris Christie on Tuesday, saying it was 'silliness to suggest either of them wanted to leaev children without immunizations against deadly diseases

Dr. Ben Carson, another possible 2016 presidential candidate, carefully threaded the needle between libertarianism and public health – erring on the side of medical science

Buzzfeed published the interview on Monday, shortly after Christie insisted that governments should give parents 'some measure of choice' in the matter.

Paul, an eye surgeon, stirred the pot hours later with a claim that he knew of cases of 'walking, talking, normal children who wound up with profound mental disorders after vaccines.'  

Carson, a world-renowned pediatric neurosurgeon before his retiement, tried to sidestep the controversy Monday night with a statement to reporters that leaned toward medical science.

'Although I strongly believe in individual rights and the rights of parents to raise their children as they see fit, I also recognize that public health and public safety are extremely important in our society,' he said.

'Certain communicable diseases have been largely eradicated by immunization policies in this country and we should not allow those diseases to return by foregoing safe immunization programs, for philosophical, religious or other reasons when we have the means to eradicate them.'

Texas Sen. Ted Cruz told Daily Mail Online that every child should be vaccinated – but left the door open for parents with religious objections to say no.

'Most states include an exception clause for good faith religious convictions, and that’s an appropriate judgment for the states to make,' he told Daily Mail Online. 

'But on the question of whether kids should be vaccinated, the answer is obvious, and there’s widespread agreement: of course they should. We vaccinate both our girls, and encourage all parents to do the same.'

On Capitol Hill, Cruz told reporters that the sudden focus on the issue generated by Christie's gaffe 'is largely silliness stirred up by the media.'

'Nobody reasonably thinks Chris Christie is opposed to vaccinating kids other than a bunch of reporters who want to write headlines,' he said.

America is facing a measles outbreak that has hit at least 102 people, including a large cluster centered on the Disneyland theme park in California.

According to the Centers for Disease Control and Prevention, most of the California cases involved children who never received the MMR vaccine, which protects against measles, mumps and rubella.

House Speaker John Boehner said Tuesday morning during a press conference that 'I don't know that we need another law, but I do believe that all children ought to be vaccinated.'

And Travis Considine, a spokesman for likely presidential contender and former Texas Gov. Rick Perry, told Daily Mail Online that Perry backed efforts to boost vaccination numbers.

'Governor Perry strongly believes in protecting life and has sought to improve the health and well-being of Texans in a variety of ways,' the spokesman said, 'including increased immunization rates.'

In 2003, at the height of the national smackdown over vaccinations and autism, Perry signed an executive order directing his government to adopt a comprehensive plan to increase immunization rates statewide. 

In a 'Today' show interview that aired Monday, President Barack Obama agreed that parents should vaccinate their kids: 'There is every reason to get vaccinated, but there aren't reasons to not.'

That pronouncment left conservatives in a tricky spot. A YouGov poll published last week showed that Republicans are more likely than Democrats – by a 35-19 per cent margin – to believe parents should be permitted to opt out of government-mandated vaccines for their children.

Concerns have run rampant sine the mid-1990s over thimerosol, a mercury-based preservative that was used in live vaccines until a decade ago. Anti-vaccine activists, relying on science that was later debunked, claimed the ingredient was tied to a spike in autism diagnoses.

The biggest cheerleader for that idea was Robert F. Kennedy Jr., the lawyer-turned-green-avenger who also argued that a different, organic form of mercury was contaminating ocean fish. 

ACTUALLY ... the earth is somewhat egg-shaped and the sky is black – it only looks blue because of hwo the atmosphere interacts with light. But Hillary Clinton's larger point is sound: Vaccines work

ANTI-VACCINE GODFATHER: Robert F. Kennedy Jr. (center) posed with his mother Ethyl (right) and Hillary Clinton (left) at last year's 'RFK Ripple of Hope' gala; Kennedy, mroe than anyone else, was responsible for spreading the discredited theory that vaccines cause autism

Kennedy wrote a conspiracy-minded article in 2005, published in print by Rolling Stone and online by Salon.com, in which he claimed scientists and government agencies were colluding with vaccine makers to cover up evidence of a brain-wasting epidemic.

Salon.com withdrew the article six years later and deleted it from its website, although copies have survived online elsewhere.

Even though liberals originated the idea that vaccines caused autism, the fallout has left some conservatives who crusade against government overreach lining up behind discredited theories, and threatening to punish candidates who disagree.

AsBuzzfeed's political editor explained on Monday, anti-vaccine advocacy remains largely 'a liberal fringe issue.'

'The people not vaccinating their kids against the diseases once declared defeated don't live in South Carolina or Indiana or a particularly conservative part of Ohio or Florida,' she wrote. 

'The strongholds are in places like Newport Beach, Santa Monica, and Marin County, California. The affluent, the educated, the enlightened, the ones who believe in purity and science – people in liberal enclaves are the ones rejecting one of the 20th century's major scientific achievements.' 

After the facepalm moment: New Jersey Governor Chris Christie (right) and his wife Mary Pat (center) posed Tuesday with Britain's Chancellor of the Exchequer George Osborne (left) as they arrived for lunch at number 11 Downing Street in London

Christie made his jaw-dropping statement Monday morning while touring a flu vaccine manufacturing facility in England.

'It's much more important, I think, what you think as a parent than what you think as a public official,' he said.

'I also understand that parents need to have some measure of choice in things as well. So that's the balance that the government has to decide.' 

His spokesman blasted out a correction of sorts after the comment caught fire online.

'To be clear: The Governor believes vaccines are an important public health protection and with a disease like measles there is no question kids should be vaccinated,' the qualification read.

'At the same time different states require different degrees of vaccination, which is why he was calling for balance in which ones government should mandate.'

Christie wrote an open letter to New Jersey voters in 2009, saying he had 'met with families affected by autism' and heard 'their concern over New Jersey’s highest-in-the-nation vaccine mandates.'

'I stand with them now, and will stand with them as their governor in their fight for greater parental involvement in vaccination decisions that affect their children,' he wrote then.

The Wall Street Journal editorial page castigated the governor on Monday night, pointing to 644 U.S. measles deaths last year in 2014, 'the most in a quarter-century.' 

Outbreaks like this year's measles cases 'are the result of plunging vaccinations rates,' the Journal opined, 'as more parents believe false information about vaccines, including claims that they cause autism.'

Rand Paul ended up pushing forward and doubling down on his libertarian views in a CNBC interview.

'The state doesn't own your children,' he declared. 'Parents own the children, and it is an issue of freedom and public health.'

Hillary Clinton, the Democrats' likely standard-bearer for 2016, tweeted Monday night that 'The science is clear: The earth is round, the sky is blue, and #vaccineswork. Let's protect all our kids. #GrandmothersKnowBest.'

Daily Mail Online reached out to representatives of other potential presidential candidates, including Bobby Jindal, Scott Walker, Ted Cruz and Marco Rubio. None of them responded to questions about vaccine politics.

@highlight

Former Texas Gov. Rick Perry 'strongly believes in protecting life and has sought to improve the health and well-being of Texans in a variety of ways, including increased immunization rates,' according to a spokesman

@highlight

Chris Christie and Rand Paul had leaped into the growing fracas over mandating childhood immunizations, leaning toward 'optional' vaccines

@highlight

Sen. Ted Cruz said the sudden focus on the issue generated by Christie's gaffe 'is largely silliness stirred up by the media'

@highlight

Barack Obama seemed to evolve on the issue, saying in 2008 that research on vaccine safety was inconclusive but insisting the opposite on Monday

@highlight

Hillary Clinton, too, pandered to anti-vaccine activists the last time she ran for president – but now says the science is settled 

@highlight

House Speaker John Boehner said Tuesday that 'I don't know that we need another law, but I do believe that all children ought to be vaccinated'

@highlight

White House's 2016 budget CUT $50 million from federal government's vaccination programs 