By
Sarah Griffiths

Adverts have appeared in people’s Facebook feeds since 2007, but you might notice that not all of them seem relevant to your interests - especially if you have not 'liked' many products.

However, this is about to change as Facebook will show adverts relating to which websites you visit outside of the social network.

While some people might find this useful, others may find it intrusive and a bit creepy.

Facebook will show adverts relating to what you have already searched for online outside of the social network. Users who find this intrusive will be able to opt out and Facebook claims that a new 'Ad preferences' tool (pictured) will let people change their preferences easily

Adverts are currently generated by which brands' Facebook Pages you 'like' as well as other signals.

Soon they will be chosen based on information from some of the websites and apps you use.

Other sites already use this interest-based advertising.

Facebook users will be able to opt-out of the new advertising system.

A new feature called 'Ad preferences' will also allow people to manage their brand 'likes' to change the type of adverts they will see.

Facebook claims that people want to see adverts that are relevant to their interests and, at the moment, the social network learns about your interests from the Pages you 'like,' demographic information and using Facebook Exchange.

Facebook Exchange marks visitors to third party websites with a cookie so that people see adverts relating to the website they have already visited when they return to Facebook.

But the company said: ‘Starting soon in the U.S. we will also include information from some of the websites and apps you use.’

Facebook continued that many companies already use this type of interest-based advertising, which is thought to be more effective.

‘Let’s say that you’re thinking about buying a new TV, and you start researching TVs on the web and in mobile apps. We may show you ads for deals on a TV to help you get the best price or other brands to consider.

‘And because we think you’re interested in electronics, we may show you ads for other electronics in the future, like speakers or a game console to go with your new TV,’ the company explained.

Facebook claims that people want to see adverts that are relevant to their interests and, at the moment, the social network learns about your interests from the Pages you 'like' and how you interact on its website or app. The 'like' logo is displayed outside Facebook's headquarters in Menlo Park, California

While UK users may not be affected by the change for a while yet, as more users become affected, they can choose to opt out of the advert targeting.

To do so, users have to look in their web browser to use the Digital Advertising Alliance opt out tool. Similar controls are also provided on iPhones and Android mobiles.

Another new feature, called ‘Ad preferences’, will also give people more control over the adverts they see, Facebook said.

The tool can be accessed from every advert shown on Facebook and it explains why that person is  seeing specific ads, as well as letting them remove interests used by the site to select relevant adverts.

‘So if you’re not interested in electronics, you can remove electronics from your ad interests,’ Facebook said.

Ad preferences will roll out in the U.S. in the next few weeks and Facebook said it is working on expanding the new advertising system globally ‘in the coming months’.

@highlight

Ads are currently displayed on Facebook according to Pages people 'like' as well as a number of other signals such as Facebook Exchange

@highlight

Starting in the U.S. they will soon be generated from which websites and apps people use, outside the social network

@highlight

People can opt out of the changes using tools on their smartphones

@highlight

Facebook announced it is also rolling out an 'ad preferences' feature

@highlight

It claims this will give users more control over the adverts they see

@highlight

Changes will begin in the U.S.and roll out globally 'in the coming months'