A Florida gun show was cancelled after organizers publicly announced Trayvon Martin killer George Zimmerman would be a guest at the event - but Zimmerman will still make a public appearance.

‘The New Orlando Gun Show,’ scheduled for this weekend at Orlando’s Majestic Events Center, was cancelled Thursday despite more than 100 vendors threatening to take the owners to court if the show did not go on.

Organizer Mike Piwowarski, who also owns a local gun store, told ClickOrlando that the show was cancelled because of the announced Zimmerman appearance, and Zimmerman posted emails to his Twitter account backing up that claim.

The guest of honor: George Zimmerman, pictured with Mike Piwowarski and two other individuals, caused a gun show to be cancelled after he was named the 'featured guest'

‘We've had discussions with The Majestic and they decided to cancel the event because George Zimmerman was making an appearance,’ said Piwowarski.

When contacted by MailOnline, Piwowarski clarified that Zimmerman was to be a paying vendor who wanted to attend for a meet and greet - he would not have charged for any autographs.

Zimmerman's intent was to be able to attend an event where he would be more free to be himself, where there would be less negativity than he has encountered in other settings, according to Piwowarski.

When asked if organizers had considered possible backlash to Zimmerman's attendance, Piwowarski replied 'I’m not sure that we were gauging reaction at all.. it was someone who was legally
able to have a table.'

Not allowed: Majestic's owners said in an email posted online by Zimmerman that the gun aficionado is not allowed on their property

Piwowarski was notified of the event's cancellation via email, but the Majestic's owners are not returning any of his messages.

'it was very detrimental to Majestic's image as a local business for Arms Room to post on Twitter saying that George Zimmerman would be a guest of honor without confirming that with Majestic and without getting prior approval from Majestic management,' general manager Vikash Mahadeowrite in an email provided to MailOnline.

Piwowarski was also quick to point out that, per the terms of their contract with the Majestic's owners, they were not required to clear any vendors with management ahead of time.

He also refuted claims the announcement was posted on Twitter and said the backlash was generated by Majestic management's reaction, not by the Arms Room post on Facebook.

A picture posted to the Facebook page for The Arms Room, Piwowarski’s gun shop, shows Zimmerman recently visiting the store with the caption ‘we had a friend stop by recently.’

Comments on the picture ranged from surprise to outrage, and that is what led Majestic’s owners to call off the whole thing, according to the station.

‘The event center asked us to do a few things when they found out Mr. Zimmerman was present; pull down posts, pull down announcement that he was going to be there.,’ Piwowarski recalled during a ClickOrlando interview.

‘We did all of that when they asked us to do it,’ Piwowarski continued. ‘They rescheduled the event. Then they later went on to cancel it again, after we complied with all of their requests.’

The organizers and more than 100 gun vendors had a year-long contract with the Majestic and plan to go to court if the show does not go on as scheduled, Piwowarski told the station.

The show will not go on: The gun show's organizers have confirmed the show has been cancelled and have plans to take the Majestic's owners to court

The show’s cancellation will cost the vendors a combined $100,000, Piwowarski claims, and organizers plan to move forward with a lawsuit to recoup that money.

'The attorneys are down at the courthouse right now,' he said while speaking to MailOnline.

‘Mr Zimmerman will not be permitted on Majestic’s property for the gun show,’ manager Vikash Mahadeo wrote in an email posted online by Zimmerman.

Zimmerman also tweeted ‘another company bowing to threats of being labeled racist’ in response to the show’s cancellation.

Messages left with Majestic’s owner by MailOnline seeking further comment have not yet been returned.

The quarterly gun shows will need to find a new home, Piwowarski explained, and Zimmerman is free to attend and will make an appearance Saturday morning at 10.00am at a mini event at the store featuring a few of the other vendors slated to attend the bigger show.

'If Mr Z desires to be there, and
he can legally be there…we don’t do any discrimination.’

@highlight

'The New Orlando Gun Show' was cancelled after organizers announced George Zimmerman would be in attendance

@highlight

Zimmerman was a paying vendor whose attendance did not need to be cleared with the event space's owners, organizers claim

@highlight

They are planning to sue to recoup losses, and Zimmerman is welcome at any of their future events as long as he is legally able

@highlight

Organizer Mike Piwowarski, who owns local gun shop The Arms Room, says Zimmerman will make an appearance Saturday at the store