An eager and diligent student forever searching for ways to improve his game, Jonny Gray has turned to a few different mentors in his time; be it Al Kellock at Glasgow or Jim Hamilton in the Scotland squad, the callow young second row has been blessed to be taken under the wing of hardened veterans.

When it comes to an inspirational role model, though, Gray makes no apologies for stating the blooming obvious when he singles out older brother Richie as the person most responsible for lighting the path to international rugby.

Not 21 for another month, the younger of the instantly recognisable brothers will win only his 10th cap when he plays against Wales on Sunday, almost certainly partnering his sibling in the middle of the pack.

Scotland lock Jonny Gray (right) puts in a strong tackle on France winger Yoann Huget in Paris 

While big bro Richie, now 25 and homing in on a half century of caps, may stand a few inches taller, it's the kid who calls the line-outs. The youngster who appears driven to emulate — and maybe even surpass? — the achievements of the elder.

'Rich, for me, is the biggest role model I've had growing up,' said Jonny. 'It's just great to have a guy like that by my side.

'It's still pretty surreal to be playing together for Scotland. And it's hard to describe. Just to be involved in the set-up is a special feeling — but to have him here as well, it's incredible. It's something I never thought would happen.

'Just growing up watching Rich, I've been lucky to have him there and to see first-hand how hard he had to work to get where he is.

Gray lines up France loosehead Alexandre Menini during his mammoth shift at the Stade de France 

'His diet, his extras, his training. For me to see that first-hand, there were no excuses for me.

'And he's the same here, still out doing his extras, still out there working hard. So that's a great example and to have someone like that around is amazing.'

Asked if he thought his own rise through the ranks may even be providing a spur for Richie to work even harder, Jonny insisted: 'No. I think Rich is a top-class player. I'm always learning from him.

'But throughout the team there is a great team spirit, the work in training that everyone does for each other is great, everyone working to help each other.

'I've been very lucky to work with Jim. He's like Al at Glasgow for me, great to sit down and talk with, share his experiences at line-outs and in other areas.

Jonny Gray (left) lines up to sing the Scotland national anthem alongside older brother Richie in November 

'There are examples of that throughout the squad. To have someone like that for me is amazing.'

Now, if young Jonny ever starts to speak with the effusive sense of adventure he brings to his on-field performances, he'll be guaranteed a good living on the lecture circuit; Carnegie Hall — the one in New York, rather than Dunfermline — would await any talker able to convey the kind of excitement generated by his rampaging playing style.

At the moment, though, nearly everything Gray says seems determinedly downbeat, his bland answers to even the most gently inviting questions suggesting either an overload of PR training — or some worrying early signs of concussion. Muhammad Ali in his prime, he ain't.

Fortunately, none of that matters once he crosses the white line. The fact that he either cannot or will not go into detail about Scotland's plans for the Welsh, even turning the subject of the visitors' apparent weakness in the line-out into words of praise for their efficacy at that particular set-piece, is neither here nor there.

Jonny Gray drives forward with ball in hand as Scotland pushed France all the way before losing 15-8 

He isn't paid to share tactical insights, doesn't pull on the jersey for a chance to get all touchy-feely. Unless by that you mean getting hold of an opponent and feeling the will drain out of him — just ask Yoann Huget…

So yes, there has been work done on stopping the driving maul that France used to such good effect last week. And no, there isn't anyone in the Scotland camp who believes Wales are the least bit predictable.

'When you look at Wales, their games in the autumn and then against England last week, you can see how direct they are,' said Gray. 'They're very physical, they're tough around the breakdown and they've got dangerous runners throughout the team. So we know how hard the game is going to be.

'The team spirit here is very strong. We go into every game thinking we can win. But we know how tough it's going to be. It's going to be a massive challenge. Wales are going to be hurting after their loss to England, so we need to prepare as best we can. We've looked at the France game and, ultimately, we're disappointed we didn't get the result.

'There are a lot of positives to take but, at the same time, a lot of improvements need to be made.

'We know how dangerous Wales are going to be this week so we need to get our preparations right going into that.'

With that, Gray retired to — for all we may know — eat a whole cow, perform a couple of thousand press-ups, do an extra hour of core work and start kicking down solid oak doors by way of preparation for welcoming the Welsh.

Sounds daft? If Richie started doing any or all of the above, you can be sure that Jonny would follow suit. Why change a winning formula, right?

 

@highlight

Jonny Gray will win his 10th cap against Wales on Sunday 

@highlight

Jonny and his brother Richie have formed a solid second row paring for Vern Cotter's new look Scotland side   

@highlight

Gray cites fellow locks Al Kellock and Jim Hamilton as big influences on his career 