By 
Kate Bevan

PUBLISHED:

05:48 EST, 7 February 2013


| 

UPDATED:

09:42 EST, 7 February 2013

Germans are the most forward-thinking people on the planet, overtaking Britons who fell to fourth place, according to researchers.

The scientists, based in the UK, Switzerland and the US, correlated data from Google searches and national economic performance.

They looked at the 'mammoth amounts of data' generated by our internet use, and discovered that there are 'strong links between changes in the information users are seeking online and events in the real world'.

Which nation has the most forward-looking citizens? Researchers linked economic performance to optimism about the future and found that Germany led the way, with Britain dropping to fourth place

They analysed some 45 billion Google search queries and found 'a striking correlation' between the per capita GDP of a nation and the inclination of people to look to the future.

Dr Suzy Moat, co-author of the report, says the findings could reflect international differences in the type of information that people search for

Lead researcher Professor Tobias Preis of Warwick Business School said: 'In general, we find a strong tendency for countries in which Google users enquire more about the future to exhibit a larger per capita GDP.

'There seems to be a relationship with the economic success of a country and the information seeking behavior of its citizens online.' 

The team first published a set of results last year.

For this year's results, the team 
looked at data from Google Trends for 45 countries, and found that 
Germany is the most forward-looking nation - knocking the UK off the top
spot from last year.

Brits topped the league table last year as people looked forward to the London 2012 Olympics and Paralympics.

This year Britain has dropped down to fourth place, swapping places with the Germans as they romp into the lead.

The league table: Germany leads the way, while Pakistan and Vietnam languish at the bottom for the second year running

Google has been accused of racism after allegedly linking names usually associated with black people to adverts related to criminality.

A Harvard University professor found 'significant discrimination' after comparing the adverts which appear when searching a typically black name compared with those for typically white names.

Findings showed that names typically associated with black people were 25 per cent more likely to bring up adverts related to criminality.

Findings showed that names typically associated with black people were 25 per cent more likely to bring up adverts related to criminality.

The findings raise 'questions as to whether Google's advertising technology exposes racial bias in society and how ad and search technology can develop to assure racial fairness,' Professor Sweeney said in a blog post.

Google defends the process as race-neutral, saying outcomes are driven by decisions by advertisers.

That could be because the Germans are focused on their federal elections later this year.

The biggest climbers on the Future Orientation Index are Nigeria and Japan.

However, right down the bottom of the list for the second year running is Pakistan, with Vietnam again in the penultimate slot.

To create the league table, the team counted the number of searches done about previous and forthcoming years - for example, searches done in 2009 on 2008 or 2010.

Then they divided the results by country and mapped them against each country's per capita GDP - the measure of a country's economic output divided by the number of people who live there.

Co-author Dr Suzy Moat added: 'We see two leading explanations for this relationship between search activity and GDP.

'Firstly, these findings may reflect international differences in attention to the future and the past, where a focus on the future supports economic success. 

'Secondly, these findings may reflect international differences in the type of information sought online, perhaps due to economic influences on available Internet infrastructure.'

Leading the way: Upcoming federal elections could be the reason that the Germans are first as the most forward-looking people on the planet

Troubled times: Pakistan is at the bottom of the optimism league for the second year running

@highlight

Researchers shifted through 45 BILLION search queries

@highlight

Biggest climbers are Nigeria and Japan on previous year