By 
David Baker

PUBLISHED:

19:05 EST, 30 November 2012


| 

UPDATED:

09:31 EST, 1 December 2012

Andrew Flintoff's wife had to watch on tentatively as her husband was put through the mill after he launched his much criticised foray into boxing.

The former England cricket star was floored in his first professional contest watched not only by his wife Racheal from the stands but celeb pals Jack Whitehall, John Bishop and Darren Gough.

Flintoff has received criticism from a number of corners for the sports switch and many assumed he would be handed an easy bout to launch his new career.

Scroll down to hear from Freddie after the bout

Celebrations: Andrew Flintoff celebrates his win while wife Rachael cheers as his victory is announce on points in the International Heavyweight Contest

Job done: Andrew Flintoff celebrated after beating Richard Dawson in the four-round bout

Winner: Flintoff sports a cut near his eye as he arrves at the after fight party at The Arora Hotel in Manchester

Fighting fit: Flintoff gets out of a taxi outside the Arora Hotel where he celebrated after the bout

If that was the case he made hard 
work of it, having been floored by his American opponent Richard Dawson 
at the Manchester Arena.

The former England captain, and his 
impressive support, went from the agony of the second round flooring 
however to ecstasy, when he claimed the win on the referee's scorecard.

Even then it was by the narrowest of margins, however, as he took the tie 39-38.

Flintoff entered the ring weighing 
considerably less than his American opponent, having tipped the scales 
25lb lighter at the weigh-in on Thursday.

Embrace: Flintoff leans over to see his wife, Rachael, after the bout

Gracious: Flintoff consoles his defeated opponent

Whoops: Flintoff was caught flush in the second round

The former England cricket captain 
had been training under the tutelage of Barry McGuigan and his son Shane
and had shed over three stone over four-and-a-half months.

His decision to take up the sport, 
particularly at a professional level, had been widely criticised, 
particularly by British and Commonwealth heavyweight champion David 
Price who stopped Matt Skelton earlier in the evening in Liverpool.

But Flintoff had insisted his venture
was not a stunt, despite the presence of Sky television who chronicled 
his progress for a three-part documentary.

And despite poor projections, the 
Arena was close to full, although the atmosphere was some way short of 
that generated by Ricky Hatton's comeback at the same venue last 
Saturday.

Nervous? Rachael Flintoff took her seat before the fight

Celebrity fan: John Bishop was in the Manchester Arena to support his friend Flintoff

And there's more: Bishop's fellow comedian Jack Whitehall turned up

Me too! Former cricketer and radio broadcaster Darren Gough

Dawson, from Oklahoma, had been 
hand-picked to face Flintoff and brought over an unbeaten record after 
three fights.

The 23-year-old was raised by his 
sister and brother-in-law until he was 18 while his mum and dad both 
served time in prison. He was shot four times in the back when working 
as a driver in the drugs trade but turned the corner when he took up 
boxing.

He had the added benefit of 
experienced trainer Bob Shannon, who trained Hatton for his unsuccessful
comeback, in his corner after his trainer was unable to obtain a visa.

But when he came out at the first 
bell, Dawson looked the less experienced as Flintoff led with his jab 
and looked to land with his right hand. He had his man on the ropes and 
edged the opening session.

Winner: Andrew Flintoff

Eagle-eyed: Flintoff picked the American off in one of his flurries

Flush: Flintoff lands a straight

Contrast: The two fighters strike a pose after the bout

But Dawson threatened to spoil the 
party in the second when he landed a right that send Flintoff to 
the canvas.

He rose quickly however and beat the count and normal 
service was resumed in the third as Dawson was forced back on to the 
ropes time and time again.

The American seemed content to hold 
and try to land another big shot but his lack of activity was never 
going to catch the referee's attention and it came down to a 
winner-takes-all final round which Flintoff controlled, using his right 
hand effectively.

@highlight

His wife Racheal watched on as Freddie recovered from a knockdown to win his first fight

@highlight

He was also cheered on by celebrity friends Jack Whitehall, John Bishop and Darren Gough