By
Kerry Mcqueeney


  Updated:
  09:01 EST, 20 October 2011

Some might not believe the bare-faced cheek of these two students.

However, faced with the prospect of an 'incredibly hostile' jobs market, graduates Ed Moyse and Ross Harper knew they had to come up with something particularly enterprising to pay off their combined university debt of £50,000.

The former Cambridge students are selling advertising space on their own faces, painting company logos on their cheeks and foreheads.

The cheek of it! Graduates Ross Harper (left) and Ed Moyse are hoping to pay off a combined student debt of £50,000 with their money-making scheme

Enterprising: The former Cambridge students claim they made £3,500 in the first 10 days of selling advertising space on their faces

Anyone can buy the advertising space,
 from businesses to individuals or groups, on a day-to-day basis. The 
logo is then seen by everyone the friends pass as they go about their 
daily business.

The
 graduates, who met on their first day at Selwyn College, Cambridge, 
started the business on October 1 and said they made £3,500 in the first
 10 days.

The boys said they
 are 'armed only with massive student debt and a firm grasp of the 
principles of viral advertising' as they attempt to survive for a year 
solely on income generated by transforming themselves into walking 
advertisements.

Mr Harper, 
21, from Greenwich, south London, who studied neuroscience, said: 'It's 
our unconventional way of paying off our student debt.

Walking advertisements: Anyone can 'buy' space on the friends' faces - from businesses to individuals or groups - on a day-to-day basis. Logos are then seen as the graduates go about their business

'The graduate job market is incredibly hostile, and so we thought we'd try and bypass it altogether.

'We've
 seen so many students unsuccessfully applying for jobs, only to 
eventually settle in a career that they never really wanted. It's just 
something a bit different and has taken off quite nicely.'

Mr Moyse, 22, from Poole, Dorset, said: 'It has exceeded expectations, but we always knew it had value and is novel and crazy.'

So far, one of the main contributors has been online betting agency, Paddy Power, Mr Harper said.

Mr
 Moyse, who studied economics, and Mr Harper came up with the idea after
 graduating in the summer as a scheme which would not require much 
investment.

The pair sold 
their first face ads to friends and family for just £1 a day but said if
 the days stayed at this price it would take a very long time to pay off
 their university debt. The price of days will increase gradually 
throughout the year.

People can log on to their website www.buymyface.co.uk where their painted faces are on display.

'Armed only with massive student debt and a firm grasp of the principles of viral advertising': They will attempt to survive for a year solely on income generated by transforming themselves into walking advertisements

Easy money? The pair enjoy a visit to a theme park while hard at work selling advertising space

@highlight

Former Cambridge students attempt to survive for one year on proceeds of enterprise

@highlight

Pair charge businesses by the day to paint their company logos on their face and forehead