By 
Sarah Griffiths

PUBLISHED:

11:26 EST, 26 August 2013


| 

UPDATED:

11:35 EST, 26 August 2013

The flight of the bumblebee might seem effortless to humans, but to stay airborne and give the impression of gliding along, the insects beat their tiny wings two hundred times a second.

Scientists have long pondered just how the bees have the energy to achieve such a feat but now two biophysicists have studied the mechanics behind the insect's flight by capturing the action in molecular detail.

The researchers filmed live bumblebees at 5,000 frames per second to conclude the insects' muscles might work by using 'stretch activation' - the same mechanism that makes vertebrate's muscles move.

The researchers filmed live bumblebees at 5,000 frames per second to conclude the insects' muscles might work by using stretch activation - the same mechanism that makes vertebrate's muscles move

Dr Hiroyuki Iwamoto and Dr Naoto Yagi at the Japan Synchrotron Radiation Research Institute, explored whether insects have a special mechanism to stay airborne, or if they use nervous signals that lead to muscle contractions, like vertebrates.

'Once the insect flight muscles are activated by nerves, they oscillate simultaneously' Yale Goldman, a muscle physiologist at the University of Pennsylvania, told Nature.

He said the oscillations are triggered by
'stretch activation,' which means the force generated by the 
antagonistic flight muscles increases in strength when they are 
extended, to pull the wing back.

The same technique is used in the human heart and other muscles that beat rhythmically, according to Kenneth Taylor, a molecular biologist at Florida State University.

But because of difference in how the technique works in insects, there is 'no upper limit to the wing-beat frequency,' he said.

To investigate what triggers stretch activation, Dr Iwamoto and Dr Yagi measured changes in the insects' muscles while they were trying to fly, at molecular level.

To do this, they glued live bees onto the end of a thin metal tube and then put the insects in the path of an X-ray beam.

They then studied the pattern of bright spots formed when the X-rays were scattered by the muscles, which they recorded at 5,000 frames per second.

They concluded stretch activation is caused by the interaction of actin and myosin in the muscle- which is the same trigger as in vertebrates, suggesting that insects do not have a special technique to keep them airborne.

@highlight

Biophysicists have studied the mechanics behind the insect's flight by capturing the action in molecular detail

@highlight

The scientists at the Japan Synchrotron Radiation Research Institute studied the pattern of bright spots formed by X-rays

@highlight

The researchers filmed live bumblebees at 5,000
frames per second to conclude the insects' muscles might work by using 
stretch activation