By
Louise Boyle

PUBLISHED:
  
  
      00:00 EST, 8 August 2012
    
  

 | 
  UPDATED:
  
  
      00:08 EST, 8 August 2012

If you thought the former college roommates of Facebook billionaire Mark Zuckerberg might be living a little in his shadow, then you'd be wrong.

For Samyr Laine, who lived with 
the Facebook founder at Harvard and was the 14th person to join the social network, has an Olympic gold medal firmly in his sights.

Laine, 28, was born in the U.S. but is competing in the triple jump for Haiti as his parents come from the Caribbean nation.

Leap for glory: Samyr Laine, who roomed at Harvard with Mark Zuckerberg, is hoping to win a medal for Haiti at the London 2012 Olympic Games

Olympic standard: Laine, 28, chose to compete for Haiti, the country where his parents were born

Laine believes he could have made Team USA - he competed nationally and internationally while at college and then Georgetown law school - but chose to fly the flag for his ancestral home.

The New Yorker first visited Haiti following its devastating earthquake in 2010 which ravaged the country, leaving 300,000 dead and thousands more homeless.

Now the triple-jumper hopes to return with the country's first Olympic medal in 84 years.

Four of Haiti's five Olympians competing at the London Games were not raised in the country. With millions of Haitians living on $2-a-day or less and hundreds of thousands of people rendered homeless by the earthquake, the country struggles to produce world-class athletes.

Giving back: The Olympic triple jumper visited Haiti for the first time in 2010 following the earthquake which killed 300,000. He hopes to start a charity in the country to promote sports

Going for gold: Samyr with MoÃ¯se Joseph, Haitian middle-distance runner, on the beach

Three of the country's five competitive running tracks are home to thousands of people in tents and shanties who were displaced by the natural disaster in January 2010.

The office of the Haitian Olympic Committee overlooks a hillside shantytown and has a budget of only $400,000 - compared to the U.S. team's $170 million fund.

Laine's personal best in the triple jump is 17.39 meters. He goes up against American world champion Christian Taylor - who has leapt 17.96 meters and British athlete Phillips Idowu who has reached 17.81 meters.

He made it through the qualifying stages last night, ranking 6th with a jump of 16.81. Laine will compete in the triple jump final on August 9.

Flying high: Laine hopes to use the Olympic attention to start a charity helping Haitian children to become engaged in sports

Alumni: Mark Zuckerberg, who lived with the Olympic triple jumper at Harvard, said he was 'proud of him'... on Facebook, of course

He hopes to use the attention generated by the Olympics to form a nonprofit group called the Jump for Haiti Foundation, a sports program that would try to produce future Olympic athletes from the country through camps and clinics.

The goal is to have future teams made up of athletes who were born and raised in Haiti.

Laine said he plans to call on friends, including his roommate-turned-billionaire, to donate a few dollars.

'I hope they see the merits of my cause,' Laine said. 'I will definitely try to reach out to Mark as well.'

According to the Wall Street Journal, Zuckerberg said he was proud of his college friend, writing on Facebook: 'He was always incredibly hard working and
 serious, both as a student and as an athlete. He's 
also just a really nice guy.'

@highlight

Samyr Laine, 28, born in U.S. to Haitian parents

@highlight

Chose to compete for ancestral home of Haiti at London 2012

@highlight

He competes in the triple jump final on August 9

@highlight

First visited Haiti after devastating 2010 earthquake which killed 300,000