By 
Gerri Peev

PUBLISHED:

20:34 EST, 15 December 2013


| 

UPDATED:

04:36 EST, 16 December 2013

Britain pays four times as much for its wind energy as Brazil, thanks to uncompetitive subsidies.

A damning report from the Policy Exchange urges the government to hold the wind industry to its pledge to slash costs by the end of the decade.

UK families are paying £95 per MWh for onshore wind, compared to £27 MWh in Brazil, according to its report.

Gap: UK families are paying £95 per MWh for onshore wind, compared to £27 MWh in Brazil

It argues that the government should hold an auction of renewable technologies to allow the industry to compete for state support.

This could start as early as next year for projects which would begin in 2017.

Currently, ministers only plan to introduce energy auctions in 2018 for projects that will be commissioned after 2020.

But this week Energy Minister Michael Fallon is set to unveil detailed plans about how to make subsidies more competitive.

Announcement: Energy Minister Michael Fallon is set to unveil detailed plans about how to make subsidies more competitive this week

Critics fear this could mean more onshore windfarms by the backdoor as they are cheaper to run compared to offshore wind, which costs about 50 per cent more to generate.

But government sources insisted that the plan will make it more difficult for the onshore windfarms to get state handouts because they will be subject to a ‘constrained allocation’.

In Brazil, prices for onshore wind have dropped to world record lows since auctioning was introduced.But in Britain, ministers are much keener on more expensive offshore wind because it is less politically controversial.

While onshore windfarms trigger fury from local communities due to their visual blight and noise, offshore windfarms are far away enough from homes not to spark protest.

But offshore wind is about 50 per cent as expensive as onshore wind, with a strike price of £155 MWh.

The most expensive technologies are tidal and wave power, which cost around £305 MWh.

Simon Moore, author of the report said: ‘The government needs to act more ruthlessly to reduce household energy bills by cutting state support for renewable technologies that do not come down in price.

He added: ‘Offshore wind may play an important role in our future energy mix. But it should not be given favourable treatment at the expense of other low carbon technologies which could reduce our carbon emissions at a much cheaper price.’

The report said of offshore wind, that ‘at its current costs it is simply too poor value an investment to be allowed to continue much longer’.

The Policy Exchange also called for the government to abolish the EU Renewable Energy Target which it said imposed unnecessary costs on Britain’s energy.

In its report, it said: ‘While the renewable energy target exists, introducing effective means of competition, or of cost-control more broadly, is seen as impossible. The legally-binding target makes no allowance for the potential high expense of meeting it.’ 

Future: Currently, ministers only plan to introduce energy auctions in 2018 for projects that will be commissioned after 2020

The EU Renewable Energy Target decrees that 15 per cent of all energy in the UK - or 30 to 35 per cent of electricity - is generated by renewable sources by 2020.

But emissions from the electricity sector are already capped by a separate European Emissions Trading System.

Average electricity bills are already £563 a year, out of a total dual fuel bill of £1255.

By 2020, this will rise to £598 out of a total bill of £1331. Various renewables targets are already contributing to £37 of this rise, and will account for £110 in 2020.

‘A policy that imposes higher-than-necessary costs risks failing if public support is lost,’ the report said.

Part of the reason for Brazil’s low wind energy prices has been put down to unusually high wind speeds, a surplus of wind turbines and hidden incentives.

Its wind turbines have much better capacity of up to 65 per cent, compared to up to 35 per cent in the UK and much of Europe.

@highlight

UK families pay £95 per MWh for wind, compared to £27 MWh in Brazil

@highlight

Damning report by Policy Exchange urges government to slash costs

@highlight

Energy Minister Michael Fallon is set to unveil detailed plans about how to make subsidies more competitive