By
Sean Poulter

PUBLISHED:
  
  
      15:49 EST, 19 March 2014
    
  

 | 
  UPDATED:
  
  
      18:36 EST, 19 March 2014

Industry chiefs insist the bill for converting parking meters, vending machines and phone boxes to take the new £1 coin could be as much as £100million.

More than 100,000 parking machines will need to be changed at a hefty cost to local council tax payers, diverting cash from other work, such as filling pot holes.

Alternatively, councils may try to recoup the cost by raising parking charges and fees for resident permits.

Prototype: The new £1 coin will be introduced from 2017, George Osborne announced today

The cost of re-calibrating each parking machine is estimated at £500 a time, which means converting every one across the UK in time for the switch in 2017 would add up to £50million.

On top of that, private companies operating more than 400,000 vending machines offering everything from train tickets to hot drinks and snacks will also have to be altered.

Payphones, betting shop fruit machines, launderette washing machines and supermarket trolleys will also have to be upgraded to take the new 12-sided coin.

Today, officials from the Royal Mint suggested the cost of converting machines to cope with the new coins would be around £20million. However, this is disputed by the industry experts such as the British Parking Association.

The British Parking Association, whose members run car parks and on-street parking machines for councils and private firms said the bill will be far higher.

Spokesman, Jo Audley, said: ‘We have estimated that about 100,000 parking machines will need to changed.

Costly: More than 100,000 parking machines across the UK will have to be re-calibrated, at a cost of £500 a time

‘That is lower than a few years ago when there were 750,000 parking meters which have been replaced, in most areas, by pay and display machines.

‘The last time machines were changed was two years ago to cope with new 5p and 10p coins. At the time we estimated the cost was £350 each. Now, two years on, we are looking at £500 per machine, which adds up to around £50million.’

However, he said that one benefit of the change will be to stop around 40million counterfeit coins going in to parking machines each year, which would offset the cost. The association said some councils and car park owners might decide to switch to cashless machines, which would be expensive to install.

Asked who would foot the bill, he said: ‘We know local authorities are suffering cutbacks. If they have to spend extra money upgrading parking machines, those costs are going to be passed on to motorists in higher charges.

‘What we don’t want to see is a motorist finding their new £1 coin is rejected by a parking machine and they are then hit by a penalty notice when they go off to get change.’

Small firms, such as laundrettes, also have concerns about the cost.

Chairman of the Federation of Small Businesses, John Allan, said: ‘Small firms who deal with low priced items are more likely to be effected by fake currency but we do have concerns about the extra costs of introducing a new pound coin.

‘For example, small firms may have to pay out to replace machinery. But, there’ s no doubt counterfeit coins and notes can seriously damage small businesses.

‘Not only are they worthless but a business could be prosecuted if it passes them on.’

Announcement: The new pound coin was one of the measures Chancellor George Osborne revealed in his Budget 2014 speech

It is thought the new design coins will be cheaper for the Treasury and the Royal Mint to manufacture than the existing gold version, which replaced the £1 note in 1983.

However, any change to the nation’s coins always brings a huge logistical exercise and cost with the result local councils are expected to ask the Treasury to cover the bill.

The Budget announcement yesterday included the establishment of a new £200million fund which councils will be able to bid against in order to fill pot holes made worse by the heavy rain and floods of the winter.

Councils complained bitterly when new thicker 5p and 10p coins were introduced in the spring of 2012 with the result that thousands of parking and vending machines had to be altered.

At the time, they warned they would need spend scarce resources on the task rather than important jobs such as mending the roads.

In the past, the trade body representing the vending machine industry has been critical of the Government for springing coin changes on them without sufficient notice. This time, they are being given a three years period to prepare.

In 2010, the Automatic Vending Association (AVA) said the introduction of new 5p and 10p coins would cost its members £42million and the coin machine industry as a whole as much as £100million. It seems unlikely the bill generated by the new 12 sided coin will be any less.

The AVA said it accepted there is a need for a new £1 coin in order to combat counterfeiting, however it is keen to keep down the cost.

A spokesman said: ‘It is imperative that the vending industry works with all the other interested parties to ensure that the security and implementation can be undertaken at the lowest possible cost to industry.

‘The AVA supports the development of a new coin which is more secure than its predecessor and can incorporate new technologies in the future and works through the existing machine base at minimal cost.’

Upgrade: Telephone boxes across the UK will also have to be upgraded to accept the new £1 coin, which is due to be brought into circulation in 2017

Out with the old: The present £1 coin, left, 
will be replaced to allay concerns about counterfeiting. Its replacement
 will be a reworking of the old-fashioned threepenny bit, which last 
circulated in 1971

The British Retail Consortium said 
supermarkets might get around the need to change trolleys by allowing 
customers to buy plastic tokens that fit the security chain slots.

Andrew
 Mills of the Royal Mint stressed the decision on the change has been 
made by the Treasury and the Chancellor, George Osborne.

He
 said there is a problem with the existing £1 coin because it is 
relatively easy to counterfeit with the result there are as many as 45 
million in circulation.

Asked
 about the cost of changing equipment, he put the average conversion fee
 at £10-£12. ‘Over the three years before introduction it will probably 
cost the economy as a whole around £15m-£20m,’ he said.

‘We have to look at the benefits and we have to make sure the change-over goes as smoothly as possibly. That is why we are engaging very closely with all stake-holders in the industry and the general public.’

Speaking to the BBC’s Today programme, he dismissed the idea that the new coin is similar to the euro and insisted it looks ‘suitably British’.

The Treasury’s impact assessment of the changes made to the 5p and 10p coins two years ago suggested a total cost to councils and businesses of £80million. Industry experts believe the bill this time will be higher still.

The AVA calculates that some 450,000 vending machines will need to be changed on top of 100,000 parking machines and around 60,000 payphones.

@highlight

George Osborne announced the new coin in his Budget speech today

@highlight

New pound, introduced to combat counterfeiting, will be introduced in 2017

@highlight

12-sided design will resemble coin last used before decrimalisation in 1971

@highlight

But more than 100,000 parking machines will need to be changed

@highlight

Phone boxes, shopping trolleys and vending machines will need upgrading