By
Alan Roden

PUBLISHED:
  
  
      07:38 EST, 13 March 2014
    
  

 | 
  UPDATED:
  
  
      10:41 EST, 13 March 2014

More than £65billion was spent in Scotland in 2012-13 by Westminster and Holyrood but only £53billion was raised through taxes

Scotland plunged more than £12billion into the red last year following a catastrophic collapse in oil revenues that leaves Alex Salmond’s independence plans in chaos.

Over £65billion was spent north of the Border in 2012-13 by Westminster and Holyrood, but just £53billion was raised through taxes.

The growing ‘black hole’ has destroyed Nationalist claims that Scotland pays more towards the UK than it receives back, and exposes the dangers of building an economy on such a volatile resource as oil.

The amount of tax generated by Scotland’s North Sea fields plummeted from £10billion in 2011-12 to just £5.6billion – a 41.5 per cent fall – in the wake of unplanned stoppages. Economic experts last night warned that oil revenues are ‘likely to have fallen again’ this year.

At the same time, the cost of Scotland’s massive welfare state continues to grow – increasing by nearly £1.3billion to an eye-watering £22.4billion. As a result, the country’s deficit has risen from 5.8 per cent to 8.3 per cent, compared to a fall from 7.6 per cent to 7.3 per cent across the UK as a whole.

The official figures – unveiled by First Minister Mr Salmond yesterday morning – mean that every man, woman and child would have been the equivalent of £283 worse off in 2012-13 if Scotland was independent. And according to the Treasury, the figure could actually be as high as £500.

However, in an example of the strength of remaining in the Union, that overspend was effectively paid for by taxpayers across the UK.

In a major miscalculation by separatist campaign chiefs, the findings came as they launched an advertising campaign asking Scots: ‘What would you say to living in one of the world’s wealthiest nations?’ The official Yes Scotland website was quietly altered yesterday after the figures destroyed claims that Scotland pays more in tax than it receives in spending.

Mr Salmond yesterday insisted that Scotland’s public finances have been healthier than the UK’s ‘over the past five years’.

But Chief Secretary to the Treasury Danny Alexander said: ‘Whatever the Scottish Government says now, the government of an independent Scotland would be forced to raise taxes and cut public services.’

Lib Dem Chief Secretary to the Treasury Danny Alexander warned an independent Scotland would have to cut spending and put up taxes

She was the poster girl for Team GB at London 2012.

Now Olympic gold medallist Jessica Ennis-Hill has joined the independence debate by saying she would prefer that the team stayed together.

The pregnant heptathlete and Glasgow 2014 ambassador visited the Hampden Park Commonwealth Stadium and Athletes Village yesterday.

She was joined by Team Scotland star and Commonwealth silver medallist Eilidh Child, with whom she shared a room at London 2012.

When asked how she would feel about losing some of her team mates if Scotland votes Yes, Ennis-Hill said: 'I definitely think one team is a great way to go forward.

'Even though at this Commonwealth Games Eilidh will be competing for Scotland and some of my other team mates will be competing for England, we still very much feel like one team.

'In sport, I would definitely like to stay as one team.'

Former Chancellor Alistair Darling, 
who is leading the pro-Union Better Together campaign, said: ‘This is a 
landmark moment in the debate. This is the day that Alex Salmond’s own 
figures made the case against independence.

‘If
 Scotland was independent today we would have no option but to cut 
spending on services like schools and hospitals or put up taxes – or 
probably both. Today as part of the UK we don’t have to do that.

‘Oil
 revenues are a major source of Scotland’s income, but are a relatively 
small part of the UK economy. The drop in oil revenue is so big that it 
is the equivalent of the entire budget for Scottish schools.’

Scottish
 LibDem leader Willie Rennie added: ‘If this was the first day of 
independence, Scotland’s chancellor of the exchequer would be announcing
 an emergency budget to increase taxes or cut spending on schools, 
hospitals and universities.’

The figures are contained in the annual ‘government expenditure and revenue Scotland’ (GERS) accounts, released by the country’s chief statistician.

Including a geographical share of North Sea oil, Scotland’s deficit was £12.1billion in 2012-13, compared to £8.6billion in 2011-12. That is the equivalent of 8.3 per cent of GDP, while the UK’s £114.8billion deficit was equivalent to 7.3 per cent.

That 1 percentage point difference is equivalent to £1.5billion, or £283 per head.

However, Treasury chiefs yesterday used a different calculation as they pointed out that Scotland’s GDP-per-head is higher than the UK. Due to North Sea oil, the amount of tax raised north of the Border was £800-per-head higher than the UK as a whole, but spending-per-head was around £1,300 higher – leaving a shortfall of £500 for every man, woman and child.

John McLaren, a leading economist at Glasgow University’s Centre for Public Policy for Regions (CPPR), said: ‘Measuring Scotland’s fiscal position relative to the UK depends heavily on North Sea oil revenues. Recent years have, on average, shown the fiscal balance relative to the UK to be marginally in Scotland’s favour but, in 2012-13 the reverse is now true. This is likely to remain the case in 2013-14, as North Sea revenues are projected to fall again.’

David Phillips of the Institute for Fiscal Studies (IFS), added: ‘In planning for independence, the Scottish Government should be cautious in its fiscal assessment, and avoid building its budget on the back of optimistic forecasts for North Sea revenues.’

But Mr Salmond said: ‘Scotland is one of the wealthiest countries in the world.

‘The figures show that tax revenues generated in 2012-13 were £800 higher per head in Scotland compared with the UK, meaning that now for every one of the last 33 years, tax receipts have been higher in Scotland than the UK.

‘Over the past five years, Scotland’s public finances have been relatively healthier than the UK’s by a total of £8.3billion - the equivalent of nearly £1,600 per person.’

He said the ‘net fiscal deficit’ in Scotland in 2012-13 reflected the ‘higher level of capital spending in Scotland which will boost the economy in the long term’.

He added: ‘North Sea revenues fell by 41.5 per cent between 2011-12 and 2012-13. This - in part - was caused by unplanned disruption to production and record capital investment by the oil and gas industry which has doubled since 2010. This will reduce tax receipts in the short-term but maximise tax revenues in the future.’

@highlight

State spent £65billion in Scotland in 2012-13 but tax raised only £53billion

@highlight

Leaves the SNP's claims about relying on oil wealth in tatters

@highlight

UK government wants an independent Scotland would have to hike taxes