By 
Amanda Williams

PUBLISHED:

18:20 EST, 21 January 2013


| 

UPDATED:

16:16 EST, 22 January 2013

It is the brutal murder of two innocents which has outraged Guatemala - a country where thousands of women have been killed in the past decade, but where 90 per cent of cases are not investigated.

Two little girls - one six years old, one 11 -  their tiny dead bodies still wearing pyjamas and clutching rosary beads - dumped in a Guatemalan city street, apparently strangled.

Elsewhere in Zona 11, a southern district of Guatemala City,  two women also lay murdered, both shot, one reportedly in the face. Today, as their bodies are laid to rest six days after they were found - they are revealed as family.

Scroll down for video

In a brutal murder which has shocked Guatemala - the bodies of a woman, her two children, aged 6 and 11 years old, and her niece, were found on January 16, 2013 in streets south of Guatemala City

Local media named the victims as Carmen Virginia Tuez Franco, 35, her daughters Marbella del Rosario Raymundo Tuez, 6, and Andy Briseida Guadalupe Raymundo Tuez, 11, along with Carmen's niece Silvia Matilde Gaitan Franco, 22

The little girls Marbella del Rosario Raymundo Tuez, 6, and Andy Briseida Guadalupe Raymundo Tuez, 11, were the children of Carmen Virginia Tuez Franco, 35, who was found murdered nearby alongside her niece Silvia Matilde Gaitan Franco, 22  on January 16. 

Emotional scenes filled a cemetery in Barberena, 50 km (31 miles) from Guatemala City, as the coffins were carried aloft by crying women before being brought before a mass as family and locals paid their last respects.

And although it is not yet known why the girls met their violent end, the pictures of today's emotional funeral serve as a poignant reminder of Guatemala's so called 'war on women'.

The deaths of the girls come as Guatemala experiences a surge in the number of murdered women.

Some 707 women were killed in Guatemala in 2012, a significant increase from 431 in 2011, according to the human rights group Mutual Support, which tracks violence in that nation, CNN reports.

At the time of their killing, the murders of 32 women had already been reported so far this year in just 15 days, while 216 men have been killed in the same period, the human rights group said.

People carry the coffins with the bodies of the two women and two girls killed. Although it is not yet known how the girls met their violent end or why, the pictures of today's emotional funeral serve as a poignant reminder of Guatemala's so called 'war on women'

A child stands over a grave during the funeral of two women and two girls killed on Wednesday, at a cemetery in Barberena, 50 km (31 miles) from Guatemala City

Women place candles outside the Public Ministry building as they demand justice for the deaths of the two girls

According to Amnesty International most cases are not effectively investigated and less than four per cent of all homicides in Guatemala result in perpetrators being convicted.

Sebastian Elgueta, Guatemala researcher at Amnesty International, said: 'There is no let-up in the cases of killings of women and girls recorded every month, despite the national scandal this has become for Guatemala.

The little girls - one six years old, one 11 - were still wearing pyjamas and clutching rosary beads when dumped in a Guatemalan city street, apparently strangled

'Thousands of cases of killings of women and girls dating from the last decade are still unresolved or end up being archived due to inefficiencies.'

Jorge Cabrera, director of Guatemala's National Institute of Forensic Sciences confirmed the children had died from asphyxiation.

He said he suspects that organised crime is behind the killing of the two girls, specifically drug trafficking groups who do not care about age or gender, he said.

In recent years, Guatemala has had one of the highest per capita murder rates in the world, according to the United Nations: 40 homicides per 100,000 inhabitants in 2010.

The country is believed to have struggled to cope with an increase of violence generated by drug gangs operating throughout Central America, such as the Zetas from neighbouring Mexico.

From 1960 to 1996, Guatemala was engulfed in civil war between left-wing guerrillas and the government. Rape was widely used as a weapon of war to intimidate opponents. More than 200,000 people were killed, most of them by the army.

In 2008,  Guatemala passed a law aimed at violent crimes against women, but Amnesty has said the authorities are not making full use of powers.

Since 2008 a UN-backed International Commission Against Impunity (CICIG) has been supporting Guatemala's justice system and trying to end a deeply-entrenched culture of impunity.

But Amnesty says more needs to be done.

Elgueta  said: 'By failing to prevent violence, mount effective investigations and ensure those responsible face justice, authorities in Guatemala are sending the message that abusing and murdering women is allowed.

'Amnesty International calls on the authorities to fully investigate the latest killings of the two girls and two women, and to bring those responsible to justice.

@highlight

The bodies of two girls were found dumped on a street in Guatemala, dressed in pyjamas

@highlight

The children, one of whom was still clutching Rosary beads, had been strangled

@highlight

The incident shocks the nation, but violence has long been a problem and thousands of women have been murdered in the past decade

@highlight

However human rights groups say the killers are unlikely to face punishment