By 
Sophie Borland

PUBLISHED:

18:51 EST, 19 October 2012


| 

UPDATED:

18:51 EST, 19 October 2012

Hospital car parks have raked in more than £1billion from patients, relatives and staff in the last ten years, figures revealed yesterday.

Drivers are now stumping up £160million a year in charges – more than double the amount of a decade ago.

One in four hospital trusts raise at least £1million a year in fees, with some pocketing nearly £4million. Critics describe the charges as a ‘tax on the sick’ and have called for them to be abolished.

Worst offender: The Heart of England Hospital Trust in Birmingham brings in the most in parking charges a year in the UK

England is the only country in the UK where hospitals still charge for parking – Scotland and Wales outlawed the practice in 2009.

Figures obtained by Tory MP Chris Skidmore show that an average hospital trust now collects £1.055million a year from parking, more than twice as much as in 2001/2 when it was just over £400,000.

Top of the list is the Heart of England NHS Trust in Birmingham, which last year raked in £3.9million.

Leeds Teaching Hospitals collected £3.4million, closely followed by Nottingham University Hospitals on just over £3million.

Worry: Tory MP Chris Skidmore said the NHS needs to look at time spent in hospital less stressful by slashing charges

Mr Skidmore, who is a member of the 
Commons Health Select Committee said: ‘Attending a hospital can be a 
difficult and stressful experience without having to worry about being 
heavily charged for parking or fined. Many patients will need repeated 
treatment and require frequent visits to hospitals.

‘Many trusts have found effective 
local solutions to ensuring patients and their families are not 
penalised, but it is clear that the NHS as a whole should look at what 
works in the best trusts in order to ensure that hospital visits are as 
comfortable as possible.’

Robert
Oxley, of the Taxpayers’ Alliance, said: ‘Parking charges are a 
disgraceful tax on the sick and their visitors. They target the most 
vulnerable and those who are often already under increased financial 
pressure that illness can bring.

‘The
huge increase in money generated by the charges suggest hospitals are 
using them more and more as a revenue-raiser rather than just paying for
parking facilities.’

Katherine
Murphy, chief executive of the Patients’ Association, added: ‘Parking 
charges hit patients hard – particularly the elderly or those who are 
vulnerable and unable to use public transport.

‘Also
affected will be those with chronic conditions who go to hospital 
regularly. It’s the last thing patients, relatives and carers need.’

Mr Skidmore obtained figures from two-thirds of hospital trusts.

Based
on the average charges, hospitals in England last year collected more 
than £160million compared to £63million ten years ago.

And in the last decade they have pocketed just over £1billion, the figures show.

Labour
had promised to scrap the charges in 2009, but the following year the 
Coalition announced they would stay, claiming the NHS could not afford 
to lose the income.

Separate figures from the Department of Health show that 45 trusts – more than a quarter – have increased their fees.

At Wirral University Teaching Hospital NHS Trust, they went up from 83p an hour to £2.50.

The most expensive rate is found at Chelsea and Westminster Hospital in London, which charges £3.50 an hour. But some trusts have broken ranks and scrapped the charges in spite of the loss of income.

In 2010, Trafford Hospital in Manchester announced parking would be free as fees were an ‘unnecessary stress, expense and hassle.’

Others have caps including Hinchingbrooke in Cambridgeshire, where patients only pay a maximum of £2.50 no matter how long they stay.

 

@highlight

The Heart of England Hospitals Trust in Birmingham pockets the most in charges a year at nearly £3.9million

@highlight

Taxpayers’ Alliance slam parking charges as 'a disgraceful tax on the sick'