By
Sarah Griffiths

PUBLISHED:
  
  
      09:55 EST, 31 January 2014
    
  

 | 
  UPDATED:
  
  
      10:14 EST, 31 January 2014

The European Space Agency’s (ESA) huge horn is part of the most powerful sound system in Europe.

But, according to the agency, no human can survive hearing it when it is turned to its maximum volume.

Instead, the massive machine, which is used to blast satellites and spacecraft with sound, is shut away behind reinforced walls.

Engineer Kees van Zijtveldt (pictured) stands beside the largest sound horn of ESA's Large European Acoustic Facility (Leaf), which is capable of subjecting satellites and spacecraft to the same noise a launcher produces as it takes off and flies through the atmosphere

Any sound above 85 Decibels can cause hearing loss in humans and the pain threshold is between 120 and 130 Decibels, according to Listverse.

A 400,000 watt speaker used at rock concerts can generate around 135 Decibels of noise.

Theoretically, fireworks and gunfire can create a staggering 145 Decibels but you can't stand next to them to be exposed to that level of sound and survive.

The call of the blue whale reaches levels of up to 188 decibels so it can travel for hundreds of miles under water.

Humans tend to stand around half a mile away from a shuttle launch as if they were very close they would be exposed to up to 170 Decibels of sound.

ESA's Leaf sound system can generate over 154 decibels of noise.

ESA's Large European Acoustic Facility (Leaf) is used to subject satellites to the same level of noise as a rocket makes when it takes off and flies though the atmosphere.

It is housed at ESA’s ESTEC Test centre where there is a collection of spaceflight simulation facilities, in Noordwijk, the Netherlands.

One wall of the sound chamber that houses the massive horn stands 16.4metres tall and 11metres wide by nine metres deep.

Nitrogen shot through the horns can produce a range of noise up to more than 154 Decibels – which is like standing close to multiple jets taking off.

The Herschel spacecraft (pictured) successfully passed its acoustic tests in June 2008. During the tests it was subjected to acoustic noise generated by the Leaf sound system

That level of noise is more than enough to permanently deafen a human.

To prevent this from happening, it can only be operated when all the safety doors are closed – so that no human will ever hear the true power of the vast stereo system.

Steel-reinforced concrete walls are used to safely contain its noise.

They are coated with epoxy resin to reflect noise to produce a uniform sound field within the chamber.

The room of sound is also supported on rubber bearing pads to isolate it from its surroundings.

Extremely high-power sound waves can disrupt or destroy the eardrums and cause severe pain or disorientation.

Less powerful sound waves can cause humans to experience nausea or discomfort.

The use of these frequencies to incapacitate people has been used both in counter-terrorist and crowd-control settings.

The possibility of a device that produces a frequency that causes vibration of the eyeballs - and therefore distortion of vision - has also been shown to work.

High-amplitude sound of a specific pattern at a frequency close to the sensitivity peak of human hearing (2-3 kHz) is used as a burglar deterrent.

Some police forces have used sound cannons against protesters, for example during the G20 summit in Pittsburgh.

'Acoustic grenades' generate between 120 decibels and 190 decibels.

German researchers showed that a blast of 210 decibels or more affects the inner organs and can cause internal injury that could lead to death. A blast impacts the body, and does so very violently.

@highlight

Large European Acoustic Facility sound system is capable of generating more than 154 Decibels and is housed in a special room in the Netherlands

@highlight

The sound is the equivalent to standing next to several jets taking off

@highlight

It is used to blast satellites and spacecraft with sound

@highlight

Large horns are housed in a sound-proofed room that is 16.4metres tall