Bosses of nuisance call companies could be hit with £500,000 fines in a Government crackdown on unwanted calls and texts.

Up to one billion cold calls are received by British families each year leaving many elderly people 'too scared to answer the phone', ministers said.

Culture Minister Ed Vaizey said nuisance calls were a 'plague' on families and had to stop.

Ministers want to to impose tougher regulation on call centres amid growing public anger at the nuisance calls

The Government's Nuisance Calls Task Force said new rules should be introduced to make company bosses  responsible for cold-callers causing ‘severe distress’ to families.

Under the plan, Payment Protection Insurance cold-callers could face fines of up to 20 per cent of their annual turnover.

Which? executive director and taskforce chairman Richard Lloyd said many British firms were ‘breaking the law’.

He told BBC Radio 4's Today programme the way in which the law was enforced had not been good enough.

Mr Lloyd said the trade in personal data, responsible for the vast majority of nuisance calls, was ‘out of control’. He also called on regulators to clamp down on the abuse of existing legislation.

‘We want to see business with good reputations that aren't keeping a close enough eye on this making sure that there is someone senior on their board who will be held to account if those nuisance calls are being generated by that businesses activity,’ Mr Lloyd said.

Between April and June this year, 40,000 people complained to the Information Commissioner about unwanted live or automated calls to their phones.

Most focused on accident or PPI claims, as well as some debt consolidation company calls.

The Nuisance Call Task Force said many consumers did not know that they had unwittingly given their consent to be contacted by these companies.

Conservative MP Ed Vaizey, the Minister for Culture and the Digital Economy, said nuisance calls were a 'plague'

Mr Vaizey said: ‘For too long, nuisance calls have plagued consumers, often at very inconvenient times of the day and in some cases, leaving vulnerable people like the elderly too scared to answer the phone.

‘That's why we're determined to tackle this scourge through the first-ever nuisance calls action plan.

‘We've already made progress, including making it easier for Ofcom to share information with the ICO about companies breaking the rules, and we're currently looking at lowering or removing the legal threshold before firms could be hit with fines of up to £500,000.’

 

@highlight

Up to one billion unwanted phone calls are received by families each year

@highlight

Culture Minister Ed Vaizey said nuisance calls were a 'plague'

@highlight

The Government's Nuisance Calls Task Force unveils plan to end scourge 