Human trafficking gangs are getting away with millions of pounds in profits because the police have no incentive to freeze their assets, Home Secretary Theresa May is warned today.

MPs warn new laws to tackle modern-day slavery do not enough to hit gangmasters 'where it hurts' by confiscating cash immediately.

They urge Mrs May to follow the example of US gangster Al Capone who was 'brought down in the 1930s through his finances'.

Home Secretary Theresa May says the Modern Slavery Bill will ensure those involved in the 'disgusting trade' will be arrested, prosecuted and jailed

The Modern Slavery Bill gets its third reading in the Commons today, with the government boasting that it will ensure those involved in the 'disgusting trade' will be arrested, prosecuted and jailed.

But amendments to the bill tabled by a cross-party group of MPs warn it fails to target the root of the trade in vulnerable people, by seizing profits made by traffickers.

They argue that profits generated by trafficking gangs can run to million pounds a week in single towns, but police fail to follow the money.

A major obstacle is said to be rules which mean most of the money which is recouped is taken by the Home Office, leaving police forces with little incentive to prioritise the funding.

Tory MP Stephen Barclay, who has backed changes to the law with Labour MP Frank Field, said: 'For too long, illegal gangmasters have been getting away with keeping their massive profits even on the rare occasion they get caught'.

In an article for MailOnline he added: 'The police need the ability to freeze the assets of illegal traffickers within the first 24 hours. 

'At present it takes many months and by then offenders have dissipating their assets before they can be confiscated.

'A further change needed to the Bill is for assets that are recovered to be returned - after compensating victims - to the investigating Police force and the Gangmaster’sLicensing Authority (GLA) rather than the Home Office.'

Critics warn not enough is done to seize the assets and cash of those involved in trafficking, because police forces are not incentivised to do so

He adds: 'The Home Secretary is to be commended for delivering the Anti Modern Slavery Bill. Yet only if it tackles organised crime through more effective financial controls will it deliver the operational change that is required.'

Under the Bill, the maximum sentence for the most serious offenders is increased from 14 years to life imprisonment.

Those who have a previous conviction for a serious sexual or violent offence face an automatic life sentence.

Ministers say it will also ensure that perpetrators convicted of slavery or trafficking 'face the toughest asset confiscation regime'. 

Launching the bill in June, Mrs May said: 'Modern slavery is an appalling crime that has no place in today’s society. 

'It is an affront not just to the dignity and humanity of the people crushed by it but to every one of us.

'This Bill presents an historic opportunity to get legislation on the statute books specifically targeting the scourge of modern slavery.' 

Tory MP Stephen Barclay warned the legislation fails to 'follow the money' of gangmasters

The gangster Al Capone was brought down in the 1930s through his finances, but modern police forces are slow to follow suit when fighting today's organised criminals.

The Modern Slavery Bill Third Reading before Parliament today is the perfect opportunity to change the law so that those exploiting vulnerable workers can be targeted through their finances.

For too long, illegal gangmasters have been getting away with keeping their massive profits even on the rare occasion they get caught. 

These profits can run to several million pounds a week in one rural town alone in my farming constituency, according to local Police sources.

The crux of the problem is the speed at which assets are frozen before crooks and their advisors can move them, and the lack of financial incentives for enforcement agencies investigating complex financial arrangements.

First, the police need the ability to freeze the assets of illegal traffickers within the first 24 hours. At present it takes many months and by then offenders have dissipating their assets before they can be confiscated. This requires the Bill to lower the evidential burden, so that it can be presumed assets have been obtained illegally through trafficking in certain scenarios.

Yet making it quicker and easier to freeze the assets of traffickers is not enough if the incentivises for law enforcement to investigate are not in place. 

A further change needed to the Bill is for assets that are recovered to be returned - after compensating victims - to the investigating Police force and the Gangmaster’sLicensing Authority (GLA) rather than the Home Office. 

At present there is little incentive for a Chief Constable under resource pressure to appoint additional financial investigators, if it takes years to recover the money and this is then largely swallowed up by the Home Office.

The role of supposedly respectable financial advisors to illegal traffickers also needs to be addressed in the Bill. Criminal accounts by their nature are profitable. Too many financial firms hide behind the simple process of filing a suspicious activity report before continuing to trade - and taking their commission.

So a higher duty of care is needed for financial institutions when arrests are made but prior to a restrain order being granted. Clearer disclosure requirements are also needed for financial institutions regarding patterns of client activity in known trafficking hot spots - such as a trafficker who has ownership of workers bank cards and makes multiple withdrawals from the same cash point using the same pin but with a multitude of different cards.

Likewise rogue gangmasters are able to make multiple payments into a single bank account which should trigger action by the bank.

The way that gangmaster’s pay their workers also needs to change so there is a clearer audit trail - as has recently been introduced for the scrap metal industry. 

At the moment, a farmer may pay a gangmaster for work in cash, in the form of say 15 brown envelopes with £150 in them each for each of the workers. 

However, instead of this going to each worker the exploiter will cross off £20 for accommodation, £30 for travel after they are given the envelope so that what the workers are ending up with is only a fraction of what the farmer thinks he is paying.

By workers being paid either through electronic transfer or by cheque the power is removed from the hands of the Gangmaster and means not only should the worker receive their proper wage, but there is a documented trail of payments for the police to investigate if irregularities are suspected. 

If a rogue gangmaster then wanted to take these wages, they would have to take their workers to a bank or cash point, and take the money directly off them, at which point the police would have a strong case to prosecute them for theft.

The Home Secretary is to be commended for delivering the Anti Modern Slavery Bill. Yet only if it tackles organised crime through more effective financial controls will it deliver the operational change that is required. 

According to the GLA, those trafficked to the UK for labour exploitation exceeded those for sexual exploitation for the first time last year. It is time to follow the money.

 

@highlight

Call for police forces to keep cash and assets taken from gangmasters 

@highlight

Minsters insist Modern Slavery Bill will lock up those in 'disgusting trade'

@highlight

Tory MP Stephen Barclay says tougher law must 'follow the money'

@highlight

Likens crackdown to how Al Capone was 'brought down by his finances' 