By
Jonathan O'Callaghan

Got a pair of old trainers you think are rubbish? They’ve got nothing on these, which literally are made of garbage found out and about.

The bizarre footwear might at first look like they were crafted from high-end materials, but closer inspection reveals their trashy beginnings.

The project called ‘Everything you buy is rubbish’ used waste found on UK shores such as the Thames to make the attire.

Scroll down for video

Charles Duffy, William Gubbins and Billy Turvey created shoes made from rubbish (pictured) to highlight our waste culture. They say the exercise was a satirical look at how often we throw away things such as old shoes in favour of getting a new pair, where once we would buy products that were long-lasting and reliable

The purpose of the creation was to show how plastic is having a negative effect on our environment.

Scientists claim that a ‘green’ biofuel made from waste coffee grounds could power vehicles on our roads.

Researchers at the University of Bath said  waste coffee grounds could be a sustainable fuel source for powering vehicles.

Around 22lbs (10kg) of leftover grounds, generated by the average coffee shop, produces around two litres of the biofuel.

The scientists believe that if this were scaled up nationally, popular high street coffee shops such as Starbucks, Café Nero and Costa Coffee could soon be rivalling oil giants like Shell, BP and Esso.

London students Charles Duffy, William Gubbins and Billy Turvey devised the idea together to highlight our waste culture.

‘Whether dumped in a landfill or washed up on the shoreline, everything that you buy will inevitably end up as rubbish,’ they write.

‘With the development of plastic came a utopian promise - that this revolutionary material would change our lives.

‘It has now become so materially ingrained in our lives and environment that it’s becoming increasingly indistinguishable and inseparable from nature.

‘We made these shoes completely out of rubbish we trawled from UK shorelines as a satirical communication tool to convey the direct correlation between waste and consumerism, and the disposability of contemporary products.

The multi-coloured shoes were made from trash found on UK shores including the Thames. 'With the development of plastic came a utopian promise - that this revolutionary material would change our lives,' the team said. But they say this has been for the worse, with plastic waste now found everyhwere

The team also made satirical posters to highlight some of the effects of waste and show how they made the shoes. Using twists on popular slogans such as Nike's 'Just do it' the team explained how the trainers are 'a product of your consumption' and representative the negative effect we are having on our environment

The team says the humble shoe is a prime example of the ‘out of sight and out of mind’ legacy of the modern consumer.

They say shoes were once hand crafted items that were not only durable but repairable, but now people discard them as soon as they become slightly damaged.

And shoes are now so mass produced that it is becoming common to throw them away regularly and get a new pair, rather than getting an existing pair fixed.

‘After you've finished with them they're just another (two) piece(s) of rubbish that are likely to still be around long after your own body has decomposed; we're all leaving behind ourselves a rubbish legacy,' they write.

'We made these shoes completely out of rubbish we trawled from UK shorelines as a satirical communication tool to convey the direct correlation between waste and consumerism, and the disposability of contemporary products,' said the team. There's no news if they have plans for more such clothing in future, though

The team adds that modern culture dictates that people often buy new clothing to maintain their appearance, but it is at the detriment of the environment.

‘We reflect an image of ourselves through our clothing,' they say.

‘The first of our clothing to show signs of damage is footwear.

‘In the eyes of the consumer, a superficial blemish or a shift in the latest trend is all that’s needed to warrant a new purchase.

‘Contemporary footwear spends barely a fraction of its life hugging a foot.

‘For the majority of its life it is rubbish.

‘Whether in a landfill or washed up on a shoreline, the synthetics within the shoes - in addition to the plethora of plastic we discard - will take centuries to break down.'

@highlight

Three London students have created shoes made from plastic waste

@highlight

They collected the trash on shores in the UK including the Thames

@highlight

Using the rubbish they found they then created a pair of colourful footwear

@highlight

A series of satirical posters show the negative effects of consumer culture

@highlight

The project is intended to highlight our habits of throwing things away