From riding a jet-pack to work and skiing on top of recycling plants to never having to worry about upgrading your smartphone again, the future is not doom and gloom, according to one renowned environmentalist.

Jonathon Porritt is determined to show people that a sustainable and eco-friendly future could be enjoyable and not full of sacrifices to save humanity.

As well as technological advances, he believes the UK will be a better place to live if steps to tackle climate change are taken - and we could even be working less.

From rising a jet-pack to work and skiing on top of recycling plants (the structure is illustrated) to never having to worry about upgrading your smartphone again, the future is not doom and gloom, Jonathan Porritt said

The World We made is written from the perspective of character Alex McKay, a 50-year-old history teacher working in Ashton Vale school in the year 2050

'A more sustainable world is a more enjoyable one that shows the dynamism of human spirit and not a sense of sacrifice,' he told MailOnline.

Mr Porritt's latest book, The World We Made, is written from the perspective of character Alex McKay, a 50-year-old history teacher working in Ashton Vale school in the year 2050.

It explores his reality, living in the UK 37 years from now, in 50 snapshots ranging from clever building designs and energy solutions, to ways of shaking up the working week and technology that lasts for life.

'People are recognising change is necessary,' said Mr Porritt.

'The trouble is that people don’t think 
the world will be better and don’t believe they can have as good a life 
as they do today, so they put it [change] off until a bit later,' he added.

In his vision of 2050, upgrading to the 
latest smartphone handset is a thing of the past as the device is 
updated constantly and is designed to last for life.

The aircraft of the future? An illustration of BoeingAir's imagined C2050, which in the book is the first commercial hybrid electric plane that runs on a biofuel mix and has super efficient engines

'What consumers would really love is what
 the physical product does. If you could make a smartphone for life and have 
just as much aspiration for software as a shiny new handset  - why wouldn’t people be happy 
with that?' he asked.

Mr Porritt's organisation, Forum for the
 Future, is working with Sony to explore whether the habit of 
'upgrading' technology, which sees millions of devices thrown into 
landfill, could be consigned to history and whether a 'handset for life' is possible.

An illustration of a vertical greenhouse in 2038. More than 30 per cent of food consumed in 2050 is grown in urban environments, such as edible 'green corridors' and vast greenhouses as well as on roofs and allotments

In 2050 everyone will have their genome sequenced and take personalised medicine.

More than 132,000 people in the UK will be over 100 years old.

The UK will increasingly be a nation of vegetarians as meat consumption drops and half of 'meat' is made in the lab.

Less people will suffer from diabetes after numbers peaked in 2030, causing governments to tax sugar, salt and fat in processed food.

In 2022 all the leaders of the world's religions and major faith groups will sign a declaration to cut food wastage.

Renewable energy will provide the bulk of the UK's power after a flirtation with nuclear power ends in cyber attacks, which causes terror and disruption.

By 2050 a unit of electricity generated by solar farms costs no more than electricity from any other source.

Upgrading to the latest smartphone handset will be a thing of the past as the device is updated constantly and is designed to last for life.

Nearly everything is recycled, repaired or reused thanks to laws and standarised components.

Robots will help with domestic tasks and even care for the elderly.

In 2050 humans work shorter hours - just under 25 hours a week - in a bid to distribute paid work more fairly.

In the book, the protagonist, Alex, writes: 'All the devices I use today are at least 10 years old, quite simply because they still do everything I need them to do ... They're all but indestructible and the software on which they run is updated automatically or on command and works just as eell at home, at work or play on display screens, handheld or retinal, activated by voice, movement and thought.'

The vision of 2050 is a world where 'nearly everything is recycled, repaired or reused' as laws have been passed and components standardised to cut waste.

While there is a lot of emphasis on less electrical devices, robots feature heavily in Mr Porritt's vision of the future.

Alex writes that they are 'as much part of our lives as our pets are, both in the home and the workplace, where remote-controlled telepresence robots became increasingly commonplace from the early 2020s onwards.'

In 2050, many families have a domestic robot which has more computer power than the human brain, despite the fact they are very much 'helpers'.

'Robots have simply become as natural an extension of our lives as a car or a fridge and there's no denying the fact that people do get very attached to their robots, Alex writes.

'As the "companionability" of very 
cheap standard robots has increased, it's become more and more natural 
to think of them as "friends" of a sort - but somehow not as people.'

The
 robots are used to care for elderly people and to provide healthcare as
 well as to control artificial limbs by brain signals alone.

In the vision of the UK in 2050 humans are doing less work - and not just because of robots.

In the fictional future, the EU's 
'Maximum Working Time Directive' is introduced and in 2045 
people work for just under 25 hours a week in their regular job, 
compared to an average of 36.4 hours in 2010.

The book's protagonist is a teacher at 'Ashton Vale School' in 2050. This is an image of the classroom, where students learn sciences, computer programming and farming, amongst other life skills

Jet packs, public transport and car pooling are popular ways to get to work in the future

Alex
 writes that the change came about as unemployment continued to rise in 
the 1920s and there were protests to distribute jobs more fairly, 
resulting in GDP being scrapped in 2029 as a way of measuring a 
country's wealth.

The 'index of sustainable economic 
well being' and a new model of working came in, which saw people swap 
labour for services via a local 'time bank' and earn extras outside 
their regular work.

In Porritt's vision for the future, all young people do compulsory national 
service on environmental and community schemes and 'overtime is banned.'

The
 commute to work has also changed as there is no car ownership. The only
 cars available are electric and operate as part of share schemes, while
 using jet packs, walking, cycling and public transport is the norm.

Talking to MailOnline about his radical vision for the UK workforce in the future, Mr Porritt said: 'People in the
 UK do amazing work on a voluntary capacity and it shows there are lots 
of ways to boost communities and lives, which is where quality of life 
comes from. Money is not the only thing.

In the fictional future the EU's 'Maximum Working Time Directive' is introduced in 2050 and in 2045 people work for just under 25 hours a week in their regular job, compared to an average of 36.4 hours in 2010

'We
 can make material economies super efficient so that we can have the 
same standard of living  with less cost on the environment.

'I
 can’t see how the rich world can keep increasing the levels of material
 consumption – with a rising population the sums don’t add up.'

In China, complex sea defenses were erected to mitigate flood damage and tree-planting programmes increased so that the country now has a 'Great Green Wall' that covers 300 million hectares, providing some measure against encroaching deserts

An illustration of the urban farms of Detroit, which in the book was transformed in the 2020s. the city has 100 square kilometres of community farm land, which as well as providing food for city dwellers, gives them more of a work life balance

He told MailOnline that he chose the 25-hour-week as he didn't want 2050 to look unrecognisable but wanted people to see the social and economic benefits of a sizable shift in the way we work and measure productivity.

He said that if he had set his novel beyond 2050 pushes it would have pushed it into the realms of science fiction.

'I don't want people to think that I've conjured it up,' he said.

However, if the date was nearer, there wouldn't be enough time to change the UK's reliance on fossil fuels and the nature of the working week and many other entrenched systems, he added.

A conventional cargo vessel harnessing wind and solar power using a sky sail and solar panels. It also has an anti-drag water-repelling polymer coating on its hullfor efficiency and is self-cleaning like a shark

Not all future scenarios in the book are positive:  Sana, Yemen is deserted in 2050 due to water shortages. From 2015 water had to be tankered in at great cost and the population exodus began

@highlight

Environmentalist Jonathon Porritt has imagined how the UK might look in 2050 and wants to show that sustainability is not about 'giving things up'

@highlight

We could be flying in futuristic hybrid jets, growing food in giant urban greenhouses and skiing on recycling depots, according to his latest book