Voyager 1 appears to have at long last left our solar system and entered interstellar space… Or has it?

The spacecraft, which carries Earthly greetings on a gold plated phonograph record, has travelled farther from Earth than any other human-made object.

Its current mission, along with Voyager 2, is to explore the outermost edge of the sun's domain and beyond.

Scroll down for video

A massive 36 years of scientific data generated by Nasa's Voyager spacecraft has been transformed into a powerful piece of orchestral music. Voyager 1's current mission (illustrated) along with Voyager 2, is to explore the outermost edge of the Sun's domain and beyond

And now, Maryland and Boston University researchers say it has begun the first exploration of our galaxy beyond the sun's influence.

But this contentious claim is at odds with a recent report from Nasa which claimed Voyager 1 was still exploring the final frontier of our solar system. 

‘It's a somewhat controversial view, but we think Voyager has finally left the solar system, and is truly beginning its travels through the Milky Way,' said Maryland University research scientist Marc Swisdak.

Mr Swisdak and fellow plasma physicists James Drake, also of the University of Maryland, and Merav Opher of Boston University have constructed a model of the outer edge of the heliosphere.

This artist's concept shows NASA's two Voyager spacecraft exploring a turbulent region of space known as the heliosheath, the outer shell of the bubble of charged particles around our sun

 In the 36th year after their 1977 launches, the twin Voyager 1 and 2 spacecraft continue exploring where nothing from Earth has flown before.

Their primary mission was the exploration of Jupiter and Saturn.

After making a string of discoveries there -- such as active volcanoes on Jupiter's moon Io and intricacies of Saturn's rings -- the mission was extended.

Voyager 2 went on to explore Uranus and Neptune, and is still the only spacecraft to have visited those outer planets.

The current mission for both spacecraft, the Voyager Interstellar Mission, is to explore the outermost edge of the Sun's domain and beyond.

Their model indicates Voyager 1 actually entered interstellar space a little more than a year ago.

But NASA and other scientists believe the spacecraft is still in a fuzzily-defined transition zone between the Sun's sphere of influence and the rest of the galaxy.

The problem is scientists do not know exactly how far Voyager 1 has to go to reach interstellar space.

In reality, there isn’t a clear boundary that defines the limits of our solar system 11 billion miles away. 

The sun’s pocket, also known as the heliosphere, is relatively well-understood as the region of space dominated by the magnetic field and charged particles emanating from our star. 

Outside the heliosphere, interstellar space is filled with matter from other stars and the magnetic field present in the nearby region of the Milky Way. 

Voyager is bathed in solar wind from the southern hemisphere flowing northward

The Voyager 1 spacecraft explored a new region in our solar system called the magnetic highway. In this region, the sun's magnetic field lines are connected to interstellar magnetic field lines, allowing particles from inside the heliosphere to zip away and particles from interstellar space to zoom in

According to conventional wisdom, scientists will know when Voyager has passed through this mysterious boundary when they stop seeing solar particles and start seeing galactic particles.

They will also be a change in the prevailing direction of the local magnetic field.

The problem is Nasa believes that the direction of magnetic fields in the solar bubble run in a different directional pattern to the fields found in interstellar space.

The University of Maryland argues that the magnetic fields inside and outside of the solar bubble run in the same direction.

They claim that because of this, there is an area where the solar bubble and interstellar space overlap, meaning the limits of our solar system are closer and that Voyager has already crossed it.

Voyager 1 is capable of returning scientific data from a full range of instruments, with adequate electrical power and attitude control propellant to keep operating until 2020.

In a statement Nasa's Voyager project scientist, Ed Stone said: ‘The fine-scale magnetic connection model will become part of the discussion among scientists as they try to reconcile what may be happening on a fine scale with what happens on a larger scale.

‘The Voyager 1 spacecraft is exploring a region no spacecraft has ever been to before. We will continue to look for any further developments over the coming months and years as Voyager explores an uncharted frontier.’

Voyager 1 and Voyager  2, which were launched in 1977, are capable of returning scientific data from a range of instruments and have enough power to remain operational until 2020.

This artist's impression shows how plasma flows around NASA's Voyager 1 spacecraft as it gets close to entering interstellar space

 

@highlight

Scientists claim Voyager 1 entered interstellar space more than a year ago

@highlight

But Nasa argues that the spacecraft is still in a fuzzily-defined transition zone between the sun's sphere of influence and the rest of the galaxy

@highlight

Debate has arisen because our solar system has no clear boundary