For many people swimming with sharks with no safety net is the stuff of nightmares.

But for Lesley Rochat - known as the 'shark warrior' - that is the problem. She is trying to convince people that the creatures are not the man-eating monsters depicted in Jaws and are crucial to the health of the world's oceans.

These incredible shots show the moment the South African free diver swam with tiger sharks, considered one of the most deadly species in the world.

Scroll down for video

'Shark warrior': Lesley Rochat said she wanted to make herself as vulnerable as possible to the tiger shark by swimming in a bikini

Double trouble: The incredible shots were taken off Tiger Beach in the Bahamas where there is still a relatively high number of tiger sharks

Campaigning: The conservationist wants to raise awareness of the harm shark nets do to the magnificent creates

Inspirational: Rochat said she is surprised at the positive reaction the pictures have had and said she did not realise they would 'inspire' people in the way they have

Watch the full video here 

Dressed only in a bikini, Rochat said she wanted to make herself as vulnerable as possible to the shark.

She hopes that by swimming with the creatures she can show they are not as dangerous as people think.

In the stunning pictures shot off Tiger Beach, Rochat comes with inches of the tiger sharks and even touches them in some images.

Rochat, who runs the campaign organisation AfriOceans, wants fewer shark nets in the sea to protect swimmers.

She says they are mainly unnecessary and actually kill sharks, which get caught up.

Rochat said the nets are 'wiping out 
our tiger shark population' and said it also harms humans because of the
 amount of money generated by eco-tourists who come to see them.

Conservationists say the nets also kill large numbers of dolphins, turtles and rays.

Determined: Lesley Rochat (right) quit her job 
to set up the AfriOceans organisation in 2003 and campaign for the 
protection of shark

Free dive: Rochat said she hoped images such as these of her with a lemon shark will help change perceptions about these important creatures

Camouflage: Tiger sharks are perfectly hidden in the ocean because they look blue from the top and white from underneath them make them hard to see

Underwater: Rochat (pictured in a different shoot wearing a wetsuit) says shark nets kill the different species of shark as well as dolphins and turtles

Rochat said she been surprised at the reaction to the stunning photographs.

She wrote: 'Little did I know that [the photos] would inspire people the way they have.

'I had the photos taken to show 
people that despite making myself as vulnerable as I could by wearing 
only a bikini and freediving with the sharks, they still did not harm 
me.

'They are powerful images and they have worked well to support my efforts in changing people's perceptions of sharks.'

Tiger sharks are second on the list of recorded attacks on humans, behind the great white shark.

However most attacks are not fatal. The species is classed as a near threatened species and it
 is under pressure of over fishing and illegal finning. They are also 
hunted for their distinctive striped skin.

Beautiful: Rochat set up the AfriOceans organisation to fight for shark species across the world and campaign against nets

Serene: The conservationist gets close to sharks to try and prove that they are not the man-eating monsters portrayed in films like Jaws

Stunning: The conservationist said shark nets, finning and over-fishing are 'wiping out' the crucial shark population

@highlight

Lesley Rochat said she wanted to be as vulnerable as possible to show sharks are not born man-eaters

@highlight

The shots of the conservationist, who founded AfriOceans, were taken near Tiger Beach in the Bahamas