By 
Tom Gardner

UPDATED:

04:00 EST, 2 March 2012

This is the aircraft that will be on the frontline in the mission to protect spectators and athletes from terrorism during the Olympics.

The Boeing E-3 Sentry has helped the military carry out thousands of missions in war zones across the globe, including Bosnia, Afghanistan and Iraq.

But now, this state-of-the art aircraft,   is set for a crucial role closer to home, guarding against threats during this summer's London Games.

The £179m plane, which features an all-seeing radar housed in the distinctive dome, enables armed forces to find, target and neutralise threats from land, sea or air from hundreds of miles.

Defence chiefs have drafted the fearsome aircraft in to help orchestrate the enormous task of keeping the public safe from all form of attack.

Scroll down for video

Keeping a watch: A British Royal Air Force E-3D Sentry AEW aircraft has the distinctive dome. The unpressurized dome is 30 feet in diameter, six feet thick at the center, and is held 11 feet above the fuselage by two struts. It tilts down at an agle of 6° at the front to reduce its air drag during take-offs, and while flying endurance speed. The dome uses both bleed-air and cooling doors to remove the heat generated by electronic and mechanical equipment. The hydraulically-rotated antenna system spins six times per minute above the fuselage and houses pulse-Doppler detector enabling it to pick up dozens of air and land threats from hundreds of miles

Control centre: The normal 18 man crew comprises four flight-deck crew, three technicians and an 11-man mission crew. The mission crew comprises a tactical director, a fighter allocator, three weapons controllers, a surveillance controller, two surveillance operators, a data-link manager, a communications operator and an electronic-support- measures operator

The RAF operates seven E-3D Sentry 
aircraft in the airborne surveillance and command-and-control role. The 
aircraft are based at RAF Waddington, in Lincolnshire, where they are operated by number 8 and 23 Squadrons.

Engines: Four CFM 56 2A-3 turbofans

Thrust: 24,000lbs each

Max speed: 460kts

Length: 46.68m

Max altitude: 35,000ft

Span: 44.98m

Aircrew: 18

E- 3D has been extensively employed in the Airborne Warning and Control System (AWACS) role.

The
E-3D Sentry, known to the RAF as the AEW1, is based on the commercial 
Boeing 707-320B aircraft, which has been extensively modified and 
updated to accommodate modern mission systems.

Mission endurance is approximately 11 hours or more than 5,000 nautical miles without the need to refuel.

But
the E-3D is the only aircraft in the RAF’s inventory capable of 
air-to-air refuelling by both the American ‘flying-boom’ system and the 
RAF’s ‘probe-and-drogue’ method.

Yesterday, Defence Secretary Philip Hammond visited the base to observe an air security training exercise 
and meet members of the armed forces who will be providing airborne 
security throughout the summer.

During the visit he stressed that security plans have been put in place 
for the Olympic Games to make sure the UK is ‘prepared in every respect’
to deal with any threats.

Philip Hammond said the potential of 
any outside threat or danger at this summer's Games was ‘hopefully very 
unlikely’ but said a huge operation was ready to deal with anything that
might go wrong.

He said: ‘Part of this exercise is making anyone with ill intention aware of the layered air defence that will be in place.

‘We've
got no specific threat to the Olympics at all and certainly no specific
threat of any kind of airborne threat, but we want the world to know we
will be prepared in every respect so that we will be able to ensure 
that the London Olympics are safe and secure.’

He added: ‘Ever since 9/11 we've had a routine plan in place to deal with the possibility of a rogue airliner.

‘What we're doing for the Olympics is 
lifting the profile of that and adding additional layers of defence to 
the routine air defence strategy that we have in place 365 days a year.’

Mr Hammond sat with General Sir Nick 
Parker and E-3D Sentry personnel in the mission crew area and viewed a 
scenario in which a rogue aircraft headed towards a target area and RAF 
Typhoons were scrambled from Coningsby in Lincolnshire, as well as a 
helicopter and sniper who could either ‘take out’ the pilot or the rogue
aircraft's engine.

Mr 
Hammond said a ‘number of ministers’ would be involved in the 
decision-making process if such action was needed and was confident 
military personnel could deal effectively with all scenarios.

Yesterday's exercise was also to provide reassurance to ‘friends and allies’ who were sending teams to the Games, he added.

Eye in the sky: The aircraft’s mission systems can separate, manage and display targets 
individually on situation displays within the aircraft, or it can 
transmit the information to ground-based and ship-based units using a 
wide variety of digital data link. This data can be displayed, interpreted and acted upon within seconds

Friend or foe: The plane is equipped with six colour display screens displaying radar and Identified Friend or Foe ground and aircraft, in real time, to the crew. This is processed and overlaid onto geographical maps to provide crew with a 3-D layout of the battle field and where the enemy and friendly troops and aircraft are operating

Briefing: Defence Secretary Philip Hammond, front left, gets talked through the two-hour test run of the exercise, codenamed Taurus Mountain, over Leamington, Dishforth, by crew members on the E-3D Sentry aircraft

Crucial role: The highly trained 18 man crew, seen leaving the one of seven E-3D Sentry aircraft at RAF Waddington, Lincolnshire, have carried out countless hours of training in preparation for their vital job during the Games this summer

The
E-3D Sentry carried out a two-hour test run of the exercise, codenamed 
Taurus Mountain, over Leamington, Dishforth and the east coast of the UK
yesterday morning.

The
plane's Northrop Grumman AN/APY-2 high-performance, multimode lookdown 
radar is able to separate airborne and maritime targets from ground and 
sea clutter.

One E-3D flying at 30,000ft can scan at distances of over 300 nautical miles.

It
can detect low-flying targets or maritime surface contacts within 215 
nautical miles and it can detect medium-level airborne targets at ranges
in excess of 280 nautical miles.

The
multi-mode radar provides lookdown surveillance to the radar horizon 
and an electronic vertical scan of the radar beam provides target 
elevation and beyond-the-horizon operation for long-range surveillance 
of medium and high-altitude aircraft.

These attributes allow it to determine the location, altitude, course and speed of large numbers of airborne targets.

Flight 
Lieutenant Craige Curry said the plane and crew acted as the ‘eyes in 
the sky’ for areas where low-level radars could not reach and fed data 
back to the ground so a full security picture could be seen.

He
said: ‘We've been involved in supporting numerous Olympics events over 
the years,’ he said. ‘We call them 'high visibility events', which the 
Olympics is this year.

‘We're reasonably well-practised in terms of this kind of operation.’

Flt Lt Curry said the crew would be looking for anything and everything in the air during the Games.

‘Anything that flies we'll be trying to build a picture of,’ he said.

Aircraft
and ground units will be part of the multi-layered air defences for the
Games, including RAF Typhoon interceptors, RAF E-3D Sentry and Royal 
Navy Sea King surveillance aircraft.

Sniper-carrying
RAF Puma and Navy Lynx helicopters, as well as RAF radar systems and 
air defence missile systems, will all be in place.

Once
the flight had finished and landed back at RAF Waddington Mr Hammond 
viewed a number of military aircraft and met personnel.

Air
Vice Marshal Stuart Atha said the principles that underpin air security
plans for the Olympics meant extra assets were able to be brought in, 
and ‘rapid and appropriate’ decision making was the same as on any other
day of the year.

Asked if 
he was confident air crews could manage and maintain security, he said: 
‘That's what today's about - it's about exercising.

‘It's just like Olympic athletes are preparing for the Games - well so are we.

‘We're
preparing for the Games to bring all these different assets together so
that we can be prepared to deliver a safe and secure Olympics, but also
doing it from the air in a way that preserves the spirit and the 
culture of the Games.

‘Hopefully you won't see us, we will be above and beyond your awareness.’

Drill: Aircraft and ground units will be part of the multi-layered air defences for the Games, including RAF Typhoon interceptors, RAF E-3D Sentry and Royal Navy Sea King surveillance aircraft

Defence Secretary Philip Hammond stands in front of a Rapier System ground-to-air missile launcher. The Rapier is the British primary anti-aircraft weapon. The surface-to-air missile was developed for the British Army and Royal Air Force. It is designed to be able to strike against longer-range and higher-altitude targets as well as close, low flying threat and will be deployed at strategic locations across London

Strike force: Two British Royal Air Force Typhoon FGR4 aircraft fly over RAF Waddington near Lincoln, will form part of the force to counter terrorist threats during the Olympics. The £125m twin-engine Typhoon are the RAF's multi-role fighter meaning they can carryout air-to-ground bombing raids as well as engage other aircraft in a dog fight

The armed forces have been keen to show off their capability to counter terrorism in the build up to the Games.

Around 100 marines and 50 officers 
rehearsed a string of high-speed drills amid fears attackers could use 
the waterways to launch onslaughts on London landmarks, earlier this 
year.

About 50 marine police officers in 
rigid inflatables and fast response boats were joined by up to 100 
military personnel and a Royal Navy Lynx helicopter for the exercises.

The Thames runs directly past the O2 
Arena, which will be known as the North Greenwich Arena for the purpose 
of the Games, when it will host events including gymnastics.  The river 
will also be used to transport tourists between venues via water buses 
and a new cable car.

Typhoon jets and HMS Ocean, the 
largest ship in the Royal Navy’s fleet, will eventually be deployed to 
protect the London 2012 Games along with up to 13,500 military 
personnel.

@highlight

RAF's fearsome Boeing E-3D Sentry takes part in two-hour test run - codenamed Taurus Mountain - as forces gear up to combat terrorist threats

@highlight

Aircraft and ground units hone skills during major multi-layered air defence drill

@highlight

Show of military force as Defence Secretary declares: 'want the world to know we will be prepared in every respect'