They were the two standout teams of last season’s absorbing Premier League. Manchester City ended up pipping Liverpool to the title, but Brendan Rodgers’ side are intent on exacting revenge. 

The Reds boss has been handed the staggering revenue generated by Luis Suarez’s sale to Barcelona – and a little bit more - to make sure the Merseysiders top the pile for the first time since 1990. 

Here, Sportsmail looks at the two probable starting XIs ahead of Monday night's clash at the Etihad Stadium.  

Goalkeeper: Joe Hart - 8.5 / Simon Mignolet - 7

It’s been a while since Joe Hart was seen as undroppable, but he is a top-quality goalkeeper and his confidence appears to be back where it should be. With it, some of the decision-based mistakes have gone away. Simon Mignolet is a good all-round keeper. He is comfortable in possession and passing, as Brendan Rodgers expects of his keepers, and a top shot stopper. Faced criticism last season.

Stoppers: Simon Mignolet (left) and Joe Hart are both solid goalkeepers for their respective clubs 

Right back: Pablo Zabaleta - 8.5 / Glen Johnson - 7

Zabaleta is one of the best defenders in the Premier League. An excellent tackler, he passes well, reads the game superbly and scores the occasional goal. Johnson is excellent at getting forward, very comfortable in possession. But defensively he is open to serious questioning, which he appears to resent somewhat.

Centre half: Vincent Kompany - 9 / Dejan Lovren - 7.5

Kompany is the best centre-half in the top flight and one of the finest in the world. Lovren had an unhappy time in his last season at Lyon, but was superb for Southampton last season. A fine reader of the game, he can tackle and pass and has the tactical intelligence to play a key role for Rodgers.

Running machine: Right back Pablo Zabaleta is one of City's more consistent performers 

Struggle: Joe Allen fails to impose himself properly on games in the middle of midfield for Liverpool 

Captian Fantastic: Belgian Vincent Kompany is City's leader from the centre of defence

Centre half: Martin Demichelis - 6.5 / Martin Skrtel - 7

Despite his late-season revival, Demichelis inspires little confidence. He is prone to bad errors, even if he did pick up significantly towards the end of the last campaign. Skrtel is better than he is given credit for, but their back four represented a major weakness of Liverpool’s side from last season.

Left back: Aleksandar Kolarov - 7.5 / Alberto Moreno - 7

Kolarov has emerged as one of the Premier League’s top left backs after a tricky start at City. So much so that the Serbian is keeping Gael Clichy kicking his heels on the bench. For all the £12million signing Moreno’s undoubted quality going forward, the Spain international is an unknown quantity going the other way – particularly against a side who don’t operate with genuine width.

Centre midfield: Fernandinho - 8 / Joe Allen - 6.5

Last season it was all too obvious when Fernandinho wasn’t in the Manchester City midfield. Perhaps that was down to the alternatives available – Javi Garcia to name one – but the Brazilian is a holder who came to the fore in big games for Manuel Pellegrini. Liverpool find themselves in a similar position without Jordan Henderson alongside Steven Gerrard; Allen allows games to pass him by far too easily. Neat and tidy, but not imposing enough.

Centre midfield: Steven Gerrard – 9 / Fernando – 7.5

Yes, we all remember that slip, but Gerrard’s drive and determination carries the Reds through games and he was a major factor in Rodgers almost clinching the title last season. Fernando has begun life in England solidly at Newcastle last week and comes with a huge reputation from Porto.

Glider: French midfielder Samir Nasri is one of the first names on Manuel Pellegrini's team sheet 

Blink and you'll miss him! Yaya Toure's strong running adds an extra dimension to City's game 

Centre midfield: Yaya Toure – 9 / Philippe Coutinho – 8.5

There is no other man in the Premier League who can turn a game like Yaya Toure. The pace, the power, the sheer brute strength with the ball at his feet, Toure has it all. It was so crucial that City kept hold of him this summer – despite birthday blues – to send out a message that they continue to become stronger. Coutinho, meanwhile, is coming into his own as a Liverpool player – a jinking midfielder able to spot the unspottable and unravel defences.

Right wing: Jordan Henderson – 8 / Samir Nasri – 8.5

A happy Nasri is a dangerous Nasri. That was patently evident in the run-in when the Frenchman swooned around the box to assist Edin Dzeko and Sergio Aguero. He also popped up with a huge later equaliser against Sunderland and is one of the first men on Pellegrini’s team sheet - a far cry to the problems under Roberto Mancini. Henderson is similar. Written off by the majority as a hugely expensive flop, the 24-year-old has grown into a midfielder capable of excelling at both sides of the game and providing defensive width away from home. 

Heartbeat: Liverpool are reliant on Steven Gerrard and Raheem Sterling performing this season 

Hotshot: Daniel Sturridge is taking on the mantle of Liverpool's main man after Luis Suarez's departure 

Supply and demand: Toure and Edin Dzeko linked up persistently during the charge to the title last year

Left wing: David Silva – 8.5 / Raheem Sterling – 8.5

A tricky one to judge. Sterling’s blistering pace and direct running make him one of the most exciting wingers in the country, but he remains raw. Silva is a knitter, stitching play together, a sauntering star able to change direction at will and pick the exact moment to play a killer final ball. If there is one criticism of the Spaniard it is that he doesn’t find the net enough.

Striker: Edin Dzeko – 8 / Daniel Sturridge – 9

Luis Suarez’s departure will see Sturridge score even more goals and develop into an even more important player for Rodgers. The striker was a goal machine last year – even with Suarez in tow – and should hit 20 this campaign. Dzeko is perhaps the most underrated player in the top flight. Just the 26 goals in 48 games for him last year – an incredible record for a man lamented by many.

Total: Manchester City 7.5 – 3.5 Liverpool (City have seven players with higher ratings than their Red counterpart)

PS… there’s Mario still to come!

Liverpool have a certain Mario Balotelli on his way from AC Milan, but they arguably needed to do better business strengthening elsewhere instead of splashing out on the enigmatic Italian.

On his way in: Mario Balotelli will offer Liverpool something extra when he signs this week 

@highlight

Yaya Toure and Daniel Sturridge to be key men at the Etihad Stadium 

@highlight

City and Liverpool were the top two in the Premier League last season 

@highlight

Steven Gerrard and Vincent Kompany will lead their teams out  