A sitting U.S. congressman suggested on Wednesday that the Secret Service would be better able to protect the president and his family if the White House went old school with its security measures – and installed a moat around 1600 Pennsylvania Avenue.

Tennessee Democratic Rep. Steve Cohen made the idea part of his brainstorm in a Q-and-A session with Acting Secret Service Director Joseph Clancy during a Capitol Hill hearing.

'Would a moat – water, six feet around, be kind of attractive and effective?' a straight-faced Cohen asked.

Clancy replied that changes to the presidential mansion's perimeter fence was the main upgrade under consideration.

'Like a higher fence?' Cohen followed up.

'You're right sir, a higher fence would certainly help us,' the Secret Service director told him.

SCROLL DOWN FOR VIDEO 

A JOKE, SORT OF: One television network mocked up what 1600 Pennsylvania Avenue might look like surrounded by a ditch filled with water to deter would-be intruders

NO DRAWBRIDGE (YET): Tennessee Democratic Rep. Steve Cohen asked during a congressional hearing if the White House needed a six-foot moat to deter deranged people from sprinting across the president's lawn and bursting into his home

Secret Service Acting Director Joseph Clancy is playing mop-up after former chief Julia Pierson's resignation, apologizing to Congress for hooker scandals, security breaches and a shooting, and explaining what policies have changed in their wake

Clancy appeared before a House Judiciary subcommittee, promising that he would root out the bad actors behind a series of scandals plaguing the storied agency that has protected every president since Grover Cleveland.

Texas Republican Congressman Louie Gohmert, on the other hand, used talk of a fence upgrade as an opportunity to slap the Obama administration's approach to securing America's southern border.

Federal officials have argued that fencing along the U.S.-Mexico border would be worthless.

'I would think that if the admin's gonna being consistent,' Gohmert said, 'it's now time to remove the fence from around the White House – 'cause if it isn't good enough for our border, it shouldn't good enough for our White House.'

Or else, the conservative firebrand added, Obama's policymakers should admit that 'maybe there really is some real virtue in having a fence that slows people down.' 

In his testimony, Clancy claimed the Secret Service conducts 'some of the best law enforcement work in the world,' but conceded that it has 'fallen short' with a series of public embarrassments that led to the resignation of former director Julia Pierson. 

He also told lawmakers his agency was working with the National Park Service to come up with plans for new protective barriers around the White House complex that would be aesthetically pleasing but more effective than the permanent fencing currently in place.  

An ashen-faced Clancy recounted a 2011 shooting, a series of fence-jumping security breaches and Secret Service agents' use of prostitutes while on overseas postings – potential security disasters for the president.

He described them as 'missteps,' saying that he is 'conducting a comprehensive, bottom-to-top assessment to determine the root cause.'

Clancy was named the interim chief in October after Omar Gonzalez, a knife-carrying military veteran, scaled the White House's fence.

Gonzalez sprinted into the mansion itself, reaching the storied East Room before an off-duty Secret Service agent subdued him. An agent who should have been the first line of defense was busy with a personal cell phone call at the time.

The negative public attention generated by that case, Clancy said Wednesday, had 'detrimental effects on workforce morale and operational security, both with potentially dire consequences.' 

Cohen, the moat-proposing Tennessean, found it amusing.

'This guy got further in the White House than some of my Republican colleagues have ever gotten,' he said, laughing.

VIGILANT, MOSTLY: Secret Service details protect the White House, the president and the first family

Other security lapses – Clancy called them 'unacceptable' and 'simply inexcusable' – have added to the sense of crisis that has enveloped the service for most of 2014.

One involved a November 2011 shooting on Constitution Avenue in Washington, D.C. that wasn't considered an attack on the president until bullet damage and broken glass was discovered days later on the White House's upper floor.

'The delay in identifying evidence of bullet impacts on the structure of the White House is unacceptable,' a contrite Clancy said. 'As a result, the agency contemporaneously instituted a systematic process to search the exterior of the White House Complex following any reported shootings in the immediate vicinity of the property.'

He also fell on his sword with respect to a security breach surrounding  Obama during a September 16 visit to the Centers for Disease Control and Prevention in Atlanta, Georgia.

As the president was whisked into an elevator to attend a briefing on the Ebola virus epidemic, an armed private security guard was allowed to join him even though the Secret Service 'advance team' had not screened him and wasn't aware he was carrying a gun.

That incident 'was self-reported,' Clancy said, 'and prompted an immediate after action review within hours of the president’s departure from the area.'

'While the actions of individuals are still being evaluated,' he added, 'the Office of Protective Operations provided guidance and additional written procedures to clarify and reinforce existing policies regarding armed contractors in proximity to the President to prevent similar incidents.'

Texas GOP Rep. Ted Poe told Clancy during the hearing that Secret Service cannot make, and should never have made, the mistakes that got him hauled before Congress.

'There can't be mistakes, and if there are mistakes but for some other intervening reason, bad things are gonna happen,' Poe said. 

'The can be no mistakes ever. You cannot do a redo if there is a mistake of security of the president and the president's family.'

LOW-TECH FENCE: Omar Gonzalez scaled the wrought-iron barrier in front of the White House on September 19 and ran all the way into the White House while carrying a knife in his pants pocket 

Wednesday's command performance  marked Clancy's first scheduled tap-dance before impatient lawmakers since Obama plucked him out of retirement to succeed Pierson, whose stock seemed to plummet monthly after a much-ballyhooed start as the Secret Service's first female director.

Before his retirement, Clancy had led Obama's personal protection detail, the visible-yet-invisible cadre of armed and earpiece-wearing agents trained to take a bullet for the president.

Now he's in the position of arguing that the service is stretched too thin to perform its core functions with sufficient integrity.

After the 9/11 terror attacks in 2001, the agency was tapped to provide security screening for large public events that could been seen as juicy follow-on targets for al-Qaeda, including the 2002 Winter Olympics and the two major political parties' quadrennial nominating conventions.

And in addition to the 27 people who receive full-time, 'round-the-clock protection – the Obama and Biden families, former presidents, and key current government officials – the agency provided specific protection to dignitaries on 5,700 occasions during the 12 months that ended on September 30.

Those included at least 390 stops during American officials' overseas trips.

House Judiciary Committee member Rep. Jason Chaffetz, right, greeted Clancy before Wednesday's hearing

Clancy said Wednesday that the Secret Service has 'fallen short' with a series of public embarrassments

Clancy said the Secret Service needs, at minimum, the 6,572 paid 'full-time equivalent' positions the White House has requested in its 2015 budget. In addition to the beginning of the 2016 presidential campaign season, he noted, the agency will be expected to protect Pope Francis when he visits the U.S. next year.

In stark contrast to the confrontational grilling Pierson received before a congressional committee the day before her resignation, lawmakers largely took it easy on Clancy Wednesday, noting that the breaches he was there to discuss all took place before his time at the helm.

Even conservative attack dogs like House Oversight and Government Reform Chairman Darrell Issa and Benghazi Select Committee Chairman Trey Gowdy respectfully held their tongues.

'Let the record reflect I was fair at least on [this] one occasion,' Gowdy said when his time for questioning expired.

Gowdy used his allotted questing period to express his concerns that the Secret Service not only has training issues that are negatively affecting agents' ability to do their jobs correctly but also 'moral' and 'character' issues that stem from their hiring practices.

The South Carolinian said he was bothered by reports of agents drinking on the job and sexually harassing female officers  – systemic problems that he said wouldn't be cured with any amount of retraining.

If you need to go to training to learn to not send explicit texts,' Gowdy insisted, 'you have no business being in the Secret Service.'

@highlight

Tennessee Democratic Rep. Steve Cohen asked the acting Secret Service director if 1600 Pennsylvania Avenue needs a six-foot moat to protect the president – but stopped short of recommending a drawbridge

@highlight

Joseph Clancy fell on his sword before Congress, promising to fix the flailing agency while he asked for more personnel to run it 

@highlight

Secret Service agents let a fence-jumper get into the White House and were caught paying for sex while on a presidential 'advance' trip in Colombia

@highlight

Agency is being squeezed as it covers more and more public events, including the coming presidential elections and a 2015 Papal visit 

@highlight

Acting director was put in place after Julia Pierson, the service's first female chief, quit last month following a series of security lapses