Banks have experimented with card readers and even fingerprint scanners but in the near future you could access your accounts using your heartbeat.

Halifax has recently completed a successful trial of 'cardiac authentication' for its online accounts using the Nymi band.

Nymi reads  the wearer's heart rhythms, which is said to be as unique as a person's fingerprint, to authenticate who they are.

Halifax (branch pictured) recently completed a successful trial of 'cardiac authentication' for its online accounts using the Nymi band. Nymi reads the wearer's heart rhythms, which is said to be as unique as a person's fingerprint, to authenticate who they are

A built-in proximity sensor can then detect where they are, and when the wearer is close to a paired device, will automatically confirm their identity and unlock the account.

In particular, the bracelet contains a HeartID sensor that measures the amount of electrical power generated by a human heart, called a cardiac rhythm tracked on an electrocardiogram, or ECG. 

This ECG differs from person to person and depends on the location and size of the their heart.

Nymi only works with a registered person's cardiac rhythm, meaning if the bracelet is stolen it can't be hacked. The technology was developed by Toronto-based Bionym.

A built-in proximity sensor can then detect where the wearer is are, and when they are close to a paired device, will automatically confirm their identity and unlock the account. The bracelet contains a HeartID sensor that measures electrical power generated by a human heart tracked on an electrocardiogram, or ECG

When the wearer clasps the Nymi around their wrist, the bracelet powers on.

By placing a finger on the topside sensor while the wrist is in contact with the bottom sensor, it completes an electrical circuit.

When the wearer clasps the Nymi around their wrist, the bracelet powers on.

By placing a finger on the topside sensor while the wrist is in contact with the bottom sensor, it completes an electrical circuit.

Nymi will then vibrate and built-in LEDs light up to tell the wearer the device has successfully authenticated them. 

Users will stay authenticated until they remove their Nymi and the electrical circuit is broke.

The Nymi functions on a three-factor security system - the bracelet, a unique heartbeat and an Authorized Authentication Device (AAD), which is a device registered with the app.

Nymi vibrates and built-in LEDs light up to tell the wearer the device has successfully authenticated them.

Users stay authenticated until they remove their Nymi and the electrical circuit is broke.

The Nymi functions on a three-factor security system - the bracelet, a unique heartbeat and an Authorized Authentication Device (AAD), which is a smartphone or device registered with the app. 

When the Nymi authenticates a user it looks at the shape of their ECG wave, not their heart rate.

It can therefore adjust to typical variations in heart rate, even if the wearer has an irregular ECG as a result of a medical condition.

The product's site said: 'Nymi offers security without compromising convenience, putting you, and only you, in control of your identity.

'As you head out the door, you’ll be able to interact with the world around you through the power of simple gestures.

'With accurate and convenient authentication technology there is no end to the possibilities. 

'The Nymi can replace everything from the PIN on your credit card to the account information on your gaming console without sacrificing security, privacy or convenience.'  

In the first-of-its-kind trials by a UK bank, Halifax asked customers to use the wristband to login to their online accounts.

When connected to an account, the band could also be used to pay for goods using contactless readers too. 

Marc Lien, Halifax's director of innovation and digital development, said: 'Exploring innovative technology is a real focus for us at the bank.

In the first-of-its-kind trials by a UK bank, Halifax asked staff and customers to use the wristband to login to their online accounts. When connected to an account, the band could, in theory, be used to pay for goods using contactless readers too (example shown)

An ECG differs from person to person and depends on the location and size of the their heart. Nymi only works with a registered person's cardiac rhythm, meaning if the bracelet is stolen it can't be hacked. The technology (pictured) was developed by Toronto-based Bionym

The bank said the band (illustrated) only works when worn by the account owner and it must be paired with the device being used

'We are in the very early stages of exploring potential uses for the Nymi Band and wearable technology more widely.'

The bank - owned by Lloyds Banking Group - said the technology  only works when worn by the account owner and the band has to be paired with the device being used to access the account. 

Lloyds recently updated its online banking app with a similar feature that pairs and recognises the phone or tablet it is being used on. 

This removes the need to enter the username, password and memorable information every time. Instead the app just asks for the latter. 

The Nymi bracelet can be pre-ordered for $79 (£50). Devices were due to ship in December but the site has not updated when it will go on general sale.  

  

 

 

@highlight

Halifax has completed a successful trial of the tech using the Nymi band

@highlight

It reads the wearer's cardiac rhythm, which is said to be as unique as a person's fingerprint, to authenticate who they are 

@highlight

Nymi measures the amount of electrical power generated by a human heart

@highlight

This is called a cardiac rhythm and is tracked on electrocardiogram (ECG)

@highlight

ECG differs from person to person and depends on size of their heart

@highlight

And because it only works with a registered person's cardiac rhythm it can't be hacked if the bracelet is stolen 

@highlight

Makers Bionym said it is more secure than iris and fingerprint scanners