A new test could be used to warn if smokers are likely to develop lung cancer.

Scientists have discovered that cells taken from the mouth and nose react differently to infrared light in people vulnerable to the disease. 

The results of these tests could help target CT scans more effectively - and potentially lead to earlier diagnosis and improved outcomes for lung cancer patients in the future.

Compared with some other types of cancer, the outlook for lung cancer has not improved greatly over the decades. 

Scroll down for video 

Scientists have discovered a test that could warn smokers if they are likely to develop lung cancer. They discovered cells taken from the mouth and nose react differently to infrared light in people vulnerable to developing the disease

Only 10 per cent of patients will live for five years or more from being diagnosed. This is mainly due to the disease being diagnosed at a late stage.

Professor Sam Janes, from University College London, said: 'This non-invasive test can help identify those who are at greatest risk within adult smokers, and may help target CT screening far more effectively.

'Our vision for the future is that smokers could get a test in the GP or pharmacy, swab their mouth or nose, and the sample is then sent off for analysis. The earlier lung cancer is detected the better the outcome. '

Patients who develop lung tumours may have subtle abnormalities in all cells in their lungs, mouth and nose.

This signature of abnormality can be seen – very subtly – by shining light on the cells. The cells reflect or refract the light differently when compared to those who do not have lung cancer.

Professor Janes added: 'Tobacco smoke exposure seems to cause a different type of injury to cells in those that go on to develop lung cancer.

'If we can use this detection system early enough maybe we can spot lung cancer at a much earlier stage or even inform whether an individual is at risk of lung cancer.

'Our study, using infrared light to examine such cells for the first time, revealed that the cells of smokers with lung cancer could be differentiated from those without lung cancer with an accuracy of 80 per cent.'

The scientists studied samples from 76 smokers, half of whom had been diagnosed with lung cancer.

Lung cancer can remain dormant for 20 years before it is triggered into an aggressive form of the disease, a study has warned.

The first genetic mutations which cause the cancer could go undetected for up to two decades before additional faults trigger cancer cells to grow rapidly.

During this expansion there is a surge of different genetic faults appearing in separate areas of the tumour.

Each distinct section evolves down different paths - meaning that every part of the tumour is genetically unique.

Researchers hope the new discovery will lead to earlier detection.

Two-thirds of patients are diagnosed with advanced forms of lung cancer, when treatments are less likely to be successful.

Over 40,000 people are diagnosed with the disease each year, but fewer than a tenth survive for at least five years after being diagnosed.

Previous research had shown that the way very pure light generated by a synchrotron particle accelerator is scattered by human cells may indicate the presence of the disease.

Further work showed that infrared light can produce the same results in a laboratory setting.

Professor Janes, a member of the British Thoracic Society, added: 'Our vision for the future is that smokers could get a test in the GP or pharmacy, swab their mouth or nose, and the sample is then sent off for analysis.

'The earlier lung cancer is detected, the better the outcome.'

The research was presented at the British Thoracic Society's Winter Meeting in London.

Next the scientists plan to analyse samples from a larger population and monitor participants over time to see how many develop lung cancer.

The results could help identify which patients should be referred for CT (computed tomography) X-ray scans.

The work was funded by the Roy Castle Lung Cancer Foundation.

In lung cancer, cells in the lungs start to multiply in an uncontrolled way, forming a growing area called the primary cancer or primary tumour. 

This is a malignant cancer that can cause symptoms such as a persistent cough, coughing up blood, and shortness of breath.

Another study, also by University College London, supported the need for screening and early diagnosis. 

The study highlighted that patients with no symptoms have better chances of a cure from lung cancer than those who are diagnosed later and with symptoms.

A five year study revealed that 61 per cent of patients treated surgically for lung cancer were diagnosed 'incidentally' through investigations performed by other specialties in the hospital. 

The patients who came to hospital with cancer-related symptoms had a significantly higher chance of dying from cancer.

Compared with some other types of cancer, the outlook for lung cancer has not improved greatly over the decades. Pictured, is a human lung cancer cell under a microscope

Professor Janes added: 'This research clarifies the need for early screening, as certain forms of lung cancer can only be surgically treated in the earliest stages.

'More needs to be done to reach those in the community with have high risk factors, and encourage early screening to detect lung cancer as quickly as possible.'

The sooner we can treat, the better the chance of survival for these patients.' 

Dr Penny Woods, Chief Executive of the British Lung Foundation, said: 'Being able to screen people with a higher risk of developing lung cancer, such as people who smoke, before they present with symptoms, could potentially help us save the lives of thousands of people.

'Late presentation and diagnosis are key reasons for the very poor survival rates from this disease, which are worse in the UK than in Europe and the US. 

'Diagnosing lung cancer at an earlier stage could greatly improve the chances of successful treatment and, therefore, survival.

'Studies such as this further emphasise the need for more investment in lung cancer research, funding for which is significantly lower than for most other forms of the disease. 

The greater the investment, the greater our chances of achieving more potentially landmark breakthroughs such as this'. 

@highlight

Test involves looking at cells from the mouth and nose under infrared light 

@highlight

Cells in people vulnerable to lung cancer react differently to this light 

@highlight

Results of tests could help target CT scans more effectively, experts said

@highlight

Scientists' vision is for smokers to be tested in a GP practice or pharmacy 

@highlight

Outlook for lung cancer has not improved greatly over the decades

@highlight

In the UK, only 10% of patients will live for 5 years after being diagnosed 