James Bond may have liked his shaken, not stirred, but now there’s a machine that makes cocktails that float in mid-air.

British scientists have created what they claim is the world’s first levitating cocktail machine, which uses sound waves to suspend tiny droplets of alcohol that drinkers can lick out of the air.

So far  inventor Charlie Harry Francis has served Gin and Tonic and Bloody Mary cocktails using the quirky machine.

Bottoms up! British scientists have created what they claim is the world’s first levitating cocktail machine, which uses sound waves to suspend tiny droplets of alcohol that drinkers can lick out of the air (pictured)

He came up with the idea for the Levitron along with Professor Bruce Drinkwater of Bristol University.

It uses ultrasonic sound waves to generate a levitating field capable of trapping tiny alcohol droplets and floating them in mid-air.

‘It's a pretty powerful machine. So far we've made a levitating Gin and Tonic at 70 per cent proof and a levitating Bloody Mary cocktail using Vodka at 160 per cent proof which will blow your socks off,' Mr Francis said.

Professor Drinkwater explained: ‘Sound waves, even in the form of your voice have an inherent amount of power.

Work in progress: So far inventor Charlie Harry Francis (pictured right, alongside Professor Bruce Drinkwater) has served Gin and Tonic and Bloody Mary cocktails using the bizarre machine (also shown)

A device called Le Whaf, which looks like a goldfish ball containing smoke, lets people inhale cocktails and food such as lemon tart.

It was invented by a Harvard University professor and aerosol scientist.

Liquid such as whisky is poured into the base of the machine, which when switched on, creates a cloud of tiny droplets suspended in a glass dome.

Like the levitating cocktail maker, it uses ultrasonic sound waves, which are generated by vibrating piezoelectric crystals.

The waves alternate low and high pressures through the liquid, which make it bubble and form tiny droplets that behave like a cloud.

The device can be bought for around $167 (£104).

‘The Levitron uses very powerful sound waves in the ultrasonic spectrum which crucially are beyond the range of human hearing, otherwise it would seriously damage your ears when the machine was switched on.’

The machine is the first step in a wider project to create contactless cutlery and levitating popcorn.

The team plan on eventually being able to float an entire roast meal into hungry diner’s mouths.

Currently, the Levitron costs around £30,000 but they are working on cutting the cost.

Mr Francis has previously invented edible mist machines, an ice cream pottery gramophone wheel and glow in the dark ice cream, at events company Lick Me I’m Delicious, which he founded.

The company is now working on developing a jellybean waterfall, whirlwind popcorn storm and an edible aftershave range. 

Choice: So far inventor Charlie Harry Francis has served Gin and Tonic and Bloody Mary cocktails (pictured) using the quirkly machine. He hopes one day to be able to levitate a whole roast dinner

@highlight

So far  inventor Charlie Harry Francis has served Gin and Tonic and Bloody Mary cocktails using the bizarre machine

@highlight

'Levitron' machine was developed with help from a Bristol University expert

@highlight

It uses ultrasonic sound waves to generate a levitating field capable of trapping tiny alcohol droplets and floating them in mid-air 

@highlight

Experts one day hope to be able to levitate a whole roast dinner for diners