By
Rosie Taylor

Wind turbines could warm local climates up to ten times faster than the natural rate, a study has shown.

Air temperatures around four of the world’s largest wind farms have increased by up to 0.72C in a decade, researchers have found.

In contrast, Earth’s average temperature has warmed by only 0.8C since 1900.

In a spin: Researchers found air temperatures around four of the world's
 largest wind farms had increased by up to 0.72C in a decade. In 
contrast, Earth's average temperature has warmed by only 0.8C 
since 1900

As more wind farms
 are built, temperature increases may have a long-term impact on wildlife and regional weather 
patterns, with experts warning that the effects from large farms could 
alter wind and rainfall patterns.

Scientists at the State University of New York at Albany studied satellite data of the areas around the wind farms, in Texas, from 2003 to 2011.

Publishing their findings in the scientific journal Nature, they said: ‘We attribute this warming primarily to wind farms.

‘The temperature change could be due to the effects of the energy expelled by farms and the movement and turbulence generated by turbine rotors.

‘These changes, if spatially large enough, may have noticeable impacts on local to regional weather and climate.’

But they warned that firm conclusions should not be drawn until more research had been carried out.

As more wind farms are built, temperature increases may have a long-term impact on wildlife and regional weather patterns

Some scientists have suggested that giant wind farms, comprising hundreds of thousands of turbines, would not only alter the weather but could be used to control it.

Britain currently has about 3,500 wind turbines, but there are plans to increase this to 10,000 onshore machines and 4,300 offshore by 2020.

The world’s wind farms last year had the capacity to produce 238 gigawatts of electricity at any one time – a 21 per cent rise on 2010.

Capacity is expected to reach nearly 500 gigawatts by the end of 2016 as more turbines are built, according to the Global Wind Energy Council.

@highlight

Air temperatures around four of the 
world's largest wind farms have increased by 0.72C in a decade

@highlight

Earth's average temperature has risen by 0.8C since 1900