Experts predict 2015 will be the year when people forsake gadgets, social networks and other technology in favour of a simpler lifestyle

Having the latest gadget or app has been a status symbol for years, but all that could be about to change.

Experts predict 2015 will be the year when people forsake gadgets, social networks and other technology in favour of the simple life.

Recent figures have already revealed that certain social networks are losing favour, and now a digital trends report believes we are entering the era of the ‘neo-Luddite’.

The prediction was made by London-based communications agency Hotwire in its sixth annual Digital Trends Report.

‘While there are many early adopters out there scrambling around to get their hands on the latest smartwatch or iPhone, there are a group of much cooler kids working out ways to kill tech altogether,’ explained the report.

‘Welcome to the era of the neo-Luddite. They’re here to make sure you switch off.’

One reason given for the decline  is the growing irritation of adverts on apps, sites and other screens.

‘Overall we accept that there is an unspoken contract between us and the web,’ continued the report.

‘We can access content for free, in exchange, brands can make us look at adverts for a bit of time.

‘But there are a growing number of people who want to take that virtual contract, burn it and dance around its ashes.

‘So much so that they will be more than happy to part with a bit of up front capital in exchange for the facility to get rid of adverts from their online experience altogether.

‘Ad blocking, as it’s known, is at an all-time high. What’s more it’s not grumpy 40-something IT managers that are doing this - it’s the youth.’

Neo-Luddite is a slang term used to describe someone who believes that using science and technology has moral and social implications. 

It is used to describe those who are considered to be anti-technology, or those who dislike or have a difficult time understanding and using modern science and technology. 

One reason given for the decline in the report is the growing irritation of adverts on apps, sites and other screens. Hotwire's prediction follows official figures from Ofcom’s International Communications Market Report that found the number of weekly visitors to social networks is dropping year-on-year

Hotwire's prediction follows official figures from Ofcom’s International Communications Market Report last week.

Neo-Luddite is a slang term used to describe someone who believes that using science and technology has moral and social implications. 

It is used to describe those who are considered to be anti-technology, or those who dislike or have a difficult time understanding and using modern science and technology. 

It is the modern-day term used to describe a Luddite. 

It found the number of weekly UK visitors to social networks is now 56 per cent, a drop from 65 per cent this time last year.

The US, China and Japan saw similar decreases - but to a lesser extent.

Elsewhere, in August, a team of developers launched a Kickstarter campaign to fund production of its noPhone - a fake handset designed to wean people off their tech addiction.

Originally created as a spoof, the handset’s popularity led the designers to create a real version.

As the site explains, ‘the noPhone has superior features to a normal smartphone, because it's totally wireless, battery-free, doesn't require software updates, and is shatterproof and waterproof.

'With a thin, light and completely wireless design,the noPhone acts as a surrogate to any smart mobile device, enabling you to always have a rectangle of smooth, cold plastic to clutch without forgoing any potential engagement with your direct environment.

In August, a team of developers launched a Kickstarter campaign to fund production of its noPhone - a fake handset designed to wean people off their tech addiction (pictured). Originally created as a spoof, the handset’s popularity led the designers to create a real version

Recent research found that more than half of gadget owners (53 per cent) worldwide admit to suffering anxiety when they can’t use their phones. This chart reveals how much time residents of different countries spend looking at screens each day 

'Never again experience the unsettling feeling of flesh on flesh when closing your hand.

The noPhone simulates the exact weight and dimensions of a phone ‘to alleviate any feelings of inadequacy generated by the absence of a real smartphone.'

Doctors have also voiced concerns about the number of people being treated for tech addiction.

Recent research found that more than half of gadget owners (53 per cent) worldwide admit to suffering anxiety when they can’t use their phones.

Recent research found that more than half of gadget owners (53 per cent) worldwide admit to suffering anxiety when they can’t use their phones.

It found having a tech detox was ‘as stressful as a trip to the dentist or even their own wedding day.’

The number of people being treated for this addiction has risen over the past year and around 1 in 8 people in the UK now exhibit signs of being hooked on their gadgets.

The Capio Nightingale Hospital has an online test that assesses the extent of a person's relationship with technology.

Dr Graham from the hospital advises taking this test as an important first step in ascertaining whether technology use is abnormal or problematic.

Although the test is primarily aimed at adults, Dr Graham adds it might help parents who are concerned about their children’s behaviour. 

And it found having a tech detox was ‘as stressful as a trip to the dentist or even their own wedding day.’

The number of people being treated for this addiction has risen over the past year and around 1 in 8 people in the UK now exhibit signs of being hooked on their gadgets.

‘It’s becoming a bit of a statement to announce you’re no longer on Facebook, and many once-upon-a-time techy people are booking retreats that disconnect you from the internet, focusing on meditation or juicing instead,’ continued the Hotwire report.

‘There’s an anti-tech digital trend, who’d have thought?’

Despite its claims of a digital switch off, the Hotwire report also revealed how technology will advance in other areas next year.

More than 60 per cent of people already use more than one device and the report believes this will rise as tablets become cheaper and wearables become more widely adopted.

‘The connected car has been touted around for even longer than the dreaded self-ordering fridge,’ continued the report.

‘[And now] we’re now beginning to see real intent from automotive brands, although interestingly the focus isn’t on the connected car, but the content car - one that delivers relevant media throughout your journey.’

Apple’s HealthKit and Google Fit are also said to be bringing digital health to the forefront, and providing the ability to share body data with healthcare professionals.

Hotwire believes the more data doctors have, the better, and the next step will be for healthcare systems to be able to handle all this user generated data.

It also predicts  MPs will use digital platforms to communicate with voters even more next year, allowing them to express opinions faster and reach a bigger audience.

 

@highlight

Experts predict 2015 will be the year when gadget use declines 

@highlight

People will take breaks from technology in favour of a simpler lifestyle

@highlight

Figures have already shown certain social networks are losing favour

@highlight

Now a trends report believes we are entering the era of the ‘neo-Luddite’

@highlight

Prediction was made by Hotwire in its sixth annual Digital Trends Report