A three-month-old baby boy is recovering in hospital after allegedly spontaneously catching fire - for the fourth time.

Rahul, was admitted for treatment of ten degree burns at an intensive care unit in Chennai, India last week, and doctors at the hospital say he suffers from 'spontaneous human combustion'.

Medical staff alleges that - for the fourth time in his short life - Rahul has burst into flames with no external source of ignition.

Scroll down for video

Rare case: Rahul, three months, is receiving treatment for his burns at a hospital in Chennai, India, after allegedly self-combusting

According to doctors Rahul may have caught fire due to the excretion of gases through his skin, which has led to him suffering burns on his chest and head.

‘The baby is stable and treatment is on for burn injuries and scars. Life-saving support systems are there for Rahul in the intensive care unit,’ said R. Narayana Babu, head of paediatrics at the hospital.

To watch the report in full click here

He told IBN Live that the baby will be under observation and may be discharged after two weeks depending on his condition.

Rahul, from Villupuram, an area 100miles from Chennai, suffered the first incident when he was just nine days old.

Fire boy: Rahul is being examined by a doctor with his mother by his side, who claims this is the fourth time her son has burst into flames

‘People thought I set him on fire deliberately,’ his mother, Rajeswari told IBN Live.

According to the parents, their community ostracized them, and 
Rahul’s father, a farm worker, says they have lost everything as a 
result of his son's condition.

Spontaneous human combustion (SHC) has been implied as a cause of death in a number of documented cases where burned corpses have been found without an apparent external source of ignition.

An estimated 200 cases have been found throughout history and victims are often elderly, sick, or under the influence of alcohol, which woudl explain why they have not been able to escape the flames.

Puzzled scientists have come up with the ‘wick theory’ to explain such events. The theory is that the human body can become an ‘inside out’ candle

The person’s clothes are the wick, while their body fat is the wax or flammable substance,  that keeps the blaze going.

Limbs may be left intact because of the temperature gradient, with the bottom half of the body being cooler than the top.

Some have postulated that static electricity could cause the needed spark.

Rajeswari alleges
 that Rahul has suffered four episodes of  spontaneous fire and suffered
 burn injuries, the last incident taking place last month.

However,
 doctors at Kilpauk Medical College Hospital in Chennai treating Rahul 
say they only have the mother's version of events to go on as the baby 
boy does not have any medical records.

'The baby has to be carefully observed. We
 have to investigate whether the ailment is genetic,' Prof. R. Jayachandran of the department of pediatrics at Kilpauk Medical College Hospital said.

'We will carry out 
tests to find out the kind of gases generated by the baby’.'

Not all believe the mother's story of self-combustion.

'Spontaneous Human Combustion-syndrome is a hoax theory,' the hospital's burns specialist Dr J Jagan Mohan told The Times of India.

'A baby catching fire spontaneously is not possible.

'Alcoholics have a very small percentage of alcohol secreted in their sweat but even that wouldn't generate a fire.'

Until a proper diagnosis is made, Rahul is given treatment that is only symptomatic, with the administration of antibiotics.

@highlight

Three-month-old admitted to Indian hospital with ten degree burns

@highlight

Doctors claim he suffers from spontaneous human combustion

@highlight

Baby boy has allegedly self combusted four times in his short life