The smell of books that lingers in second-hand book stores is distinctive, but it is hard to know exactly what creates the nostalgic aroma.

Now one British chemistry teacher has created an infographic to explain how and why the scent of antique and new books differ.

Old books have a sweet smell with notes of vanilla flowers and almonds, caused by the breakdown of chemical compounds in the paper, while new books smell like they do because of chemicals used in their manufacture.

One British chemistry teacher has created an infographic to explain the scent of antique and new books. The anonymous blogger started publishing his infographics six months ago after creating some posters to brighten up his classroom and hopes to explain the chemistry of everyday substances.

'Old book smell' is generated by the breakdown of cellulose and lignin in paper, which produces organic compounds.

Benzaldehyde adds an almond-like scent, vanillin smells of vanilla and ethyl hexanol has a ‘slightly floral’ scent. Ethyl benzene and toluene, which are also produced give off impart odours.

These volatile organic compounds are created by reactions known as ‘acid hydrolysis’ and  together make up the smell of old books along with other alcohols produced by the reactions.

No-one is sure of exactly which chemical compounds contribute to 'new book smell'.

The scent differs from book to book as different chemicals are used in the making of different volumes.

It is thought the smell derives from three main sources: The paper, inks used to print the book and the adhesives used in book binding.

The anonymous blogger said the chemical breakdown of compounds within paper leads to the production of ‘old book smell’.

Paper contains cellulose and small amounts of lignin - a complex polymer of aromatic alcohols – and finer papers contain less lignin than cheaper material like newsprint.

Lignin is what makes paper yellow with age because oxidation reactions cause it to break down into acids, which then help break down cellulose, he explained in the Compound Interest blog.

The smell of old books comes from chemical degradation and a number of compounds have been pinpointed.

Benzaldehyde adds an almond-like scent, 
vanillin smells of vanilla and ethyl hexanol has a ‘slightly floral’ 
scent. Ethyl benzene and toluene, which are also produced give off sweet
 odours.

Old books (stock image) have a sweet smell with notes of vanilla flowers and almonds, caused by the breakdown of chemical compounds in the paper, while new books smell how they do because of chemicals used in their manufacture

These volatile organic compounds are created by reactions known as ‘acid hydrolysis’ and together make up the smell of old books along with other alcohols produced by the reactions.

Some compounds such as furfural are useful to determine the damage to antique volumes. It can be used to date tomes as well as to determine their composition. Books published after the mid-1800s emit more furfal than older volumes which are composed of cotton or linen paper.

The anonymous blogger said that it is difficult to pinpoint specific compounds found in new books, mainly because the chemicals used to manufacture books vary, meaning the smell differs between literary works.

‘Add to this the fact that there are literally hundreds of compounds involved and it becomes clearer why it evades attribution to a small selection of chemicals,’ he wrote.

Benzaldehyde adds an almond-like scent, vanillin smells of vanilla and ethyl hexanol has a 'slightly floral' scent. Ethyl benzene and toluene, which are also produced give off sweet odours

It is thought that ‘new book smell’ derives from three main sources: the paper, inks used to print the book and the adhesives used in book binding.

Lots of chemicals are used to make paper, which is largely manufactured from wood pulp. Chemicals such as sodium hydroxide – which is often known as caustic soda – can be added to decrease the acidity and cause fibres in the pulp to swell.

The fibres are bleached with a mixture of other chemicals including hydrogen peroxide and are mixed with water, which itself contains additives.

Some of these chemicals react and release volatile organic compounds into the air, which create the distinctive smell that varies from book to book depending on the adhesives, ink and paper used.

@highlight

Old books have a sweet smell with notes of vanilla flowers and almonds, caused by the breakdown of chemical compounds in the paper

@highlight

The smell of new books depends on chemicals used in their manufacture and this can vary from volume to volume

@highlight

British chemistry teacher created the infographic to demystify the differing smells of old and new books and to reveal their chemical compounds