Anxiously waiting for a phone call home is a scenario that any parent will understand.

This evening that call was coming from 500 million miles, after a decade away and two and half years without contact. And it was late.

The Rosetta spacecraft was due to send in a signal to the European Space Agency at 5.30pm this evening.

Scroll down for video...

Rosetta was launched in 2004 and has since travelled around the sun five times, picking up energy from Earth and Mars to line it up with its final destination: Comet 67P/Churyumov/Gerasimenko. it is due to arrive at the comet in August this year

Rosetta, named after a block of stone that helped archeologists decipher ancient Egyptian hieroglyphs, will seek to help scientists unlock the composition of comets and thereby understand more about the origins and evolution of our solar system. 

The probe was launched in 2004 and has since travelled around the sun five times, picking up energy from Earth and Mars to line it up with its final destination: Comet 67P/Churyumov–Gerasimenko.

For the coldest, loneliest leg of the mission, as Rosetta travelled out towards the orbit of Jupiter, the spacecraft was put into deep-space hibernation.

Later this year, Rosetta will complete its cruise towards the comet, meeting with it in August, before putting its Philae lander onto the comet’s surface in November.

‘It could come any moment now,’ said operations manager Andrea Accomazzo.

‘We could get the signal at any time.’

Eventually, at 6.18pm, a tiny beep came through, a spike on a graph that showed the £1billion spacecraft was still intact.

A few seconds later the all-clear message ‘Hello World!’ was sent out on social networking sites.

The Rosetta craft is hurtling through space in a ten-year long pursuit of an icy comet.

For
 the last 31 months it has been in hibernation, too far away from the 
sun for its solar panels to generate enough power to keep it going.

But today, as it closed in on its target, it was woken up to prepare for several months of delicate manoeuvres.

At 10am an alarm triggered a process by which its systems were slowly warmed up and turned on.

The process was due to have taken just over seven hours before a signal was sent to Earth, a process that took 45 minutes.

The European Space Agency (ESA) received the all-clear message 'Hello World!' from its Rosetta spacecraft, 500 million miles away, shortly after 6pm

The signal was received by Nasa's Goldstone ground station in California at 18:18 GMT, during the first window of opportunity the spacecraft had to communicate with Earth. It was immediately confirmed in ESA's space operations centre in Darmstadt (pictured)

A screenshot of the moment the signal was received from Rosetta. The spacecraft's orbit has brought it back to within 673 million km from the sun

The Rosetta mission will perform several historical firsts, including the first time a spacecraft orbits a comet rather than just whizzing by it to snap some fly-by pictures, and the first time a probe has landed on a comet's nucleus.

Rosetta is also the first mission to venture beyond the main asteroid belt relying solely on solar cells for power generation, which is also why it had to be put into a deep sleep for 957 days.

'It has been so far away from the sun that the solar rays were not able to generate enough energy to safely operate the spacecraft, said Rosetta spacecraft operations manager Andrea, who has been working on the Rosetta mission since 1997.

But either Rosetta’s four clocks had fallen out of sync way out in space, or the warm-up took a little longer than anticipated.

Eventually, 48 minutes behind schedule, the message came through to the operations centre in Darmstadt, Germany, to huge cheers.

‘It has been a fantastic few moments of pure terror,’ said one exhausted organiser.

Rosetta is now around 5.6 million miles from its destination, the comet Churyumov-Gerasimenko, and closing on the object at half a mile a second.

The spacecraft, which was launched by in French Guiana in 2004, will now spend several months approaching and orbiting the comet.

Once it has found for a suitable landing site for the box-like Philae lander it will attempt a landing in November.

Philae will also capture panoramic images of the view from the comet’s surface with an on-board camera.

Scientists hope Rosetta will answer important questions about the origins of the solar system and the way comets evolve and develop.

Rosetta was put to sleep to conserve power as it headed to regions as distant as the planet Jupiter, where the sun’s weak rays provide only limited amounts of energy.

Unlike other long-distance space probes the craft has no nuclear batteries and instead relies on electricity generated by ultra-sensitive 15-metre long solar panels.

Scientists planned to hibernate Rosetta for 957 days before bringing its main systems back on line.

For the coldest, loneliest leg of the mission, as Rosetta travelled out towards the orbit of Jupiter, the spacecraft was put into deep-space hibernation

Later this year, Rosetta will complete its cruise towards the comet, meeting with it in August, before putting its Philae lander onto the comet's surface in November

Rosetta
 is now around 5.6 million miles from its destination, the comet 
Churyumov-Gerasimenko, and closing on the object at half a mile a 
second.

The spacecraft, 
which was launched by in French Guiana in 2004, will now spend several 
months approaching and orbiting the comet.

Once it has found for a suitable  site, it will attempt a landing in November.

Scientists are particularly keen to conduct organic chemistry experiments on samples from the comet's body.

One of Rosetta's first tasks will be to scout for a suitable landing location for its piggyback-riding Philae probe.

Scientists are particularly keen to conduct organic chemistry experiments on samples drilled out from inside the comet's body.

‘It would be really interesting to find out whether the organic chemistry that is relevant for life is there on comets,’ Professor Ulamec said.

Engineers who designed the lander did not know what type of terrain they would find on the comet's surface.

It is outfitted with twin harpoons laced with tethers that will be fired into the comet's surface to anchor Philae and keep it from bouncing back into space after touchdown.

The spacecraft will be involved a high-speed chase later this year followed by a delicate dance around comet 67P/Churyumov-Gerasimenko. Pictured is an artist's impression of the comet

@highlight

Rosetta spacecraft aims to better understand the composition of comets

@highlight

It launched in 2004 and has since travelled around the sun five times

@highlight

Probe has been hibernating for most of the past three years to save power

@highlight

Its alarm sounded at 10am but its signal to Earth didn't arrive until 6pm 

@highlight

The probe will land on comet 67P/Churyumov–Gerasimenko in November

@highlight

Scientists hope the mission will provide more clues about how the solar system came into existence