By 
Rebecca English

PUBLISHED:

06:56 EST, 2 July 2012


| 

UPDATED:

05:49 EST, 3 July 2012

The Queen is counting the cost of her globe-trotting family as spending on royal travel rose to £6.1million last year.

Among the biggest spenders was the 
Duke of York who – despite standing down as a controversial global trade
ambassador – managed to rack up £378,249 on taxpayer-funded flights.

The newly-wed Duke and Duchess of 
Cambridge also make their first appearance in the books, spending 
£51,410 on a one-way flight from LA to London for themselves and seven 
staff.

Scroll down for video

Despite standing down as a controversial global trade ambassador the Duke of York still managed to rack up £378,249 on taxpayer-funded flights

High fliers: Prince William and his wife Kate, pictured leaving Los Angeles last July, spent an incredible £52,000 on the one-way flight from LA to London for themselves and their seven-strong entourage

On the up: The Queen's official expenditure increased from £32.1million in 2010/11 to £32.3million in 2011/12

The second most expensive trip of the year was taken by Prince Harry 
whose successful jubilee tour to Belize, the Bahamas, Jamaica and Brazil
cost taxpayers £107,098 plus a further £18,101 on flights for staff 
conducting reconnaissance.

Andrew managed to spend £236,088 on foreign tours for UK Trade and 
Industry, even after stepping down as its Special Representative in 
July.

This includes £19,987 in October last year on scheduled flights to and 
from the Far East and a further £72,250 on a private jet for the same 
tour which took in China, Hong Kong and Malaysia – £92,237 in total.

He also spent £81,000 last September on a private jet to Saudi Arabia, a
further £18,709 on scheduled flights to Singapore and £14,196 on 
tickets to Qatar and Abu Dhabi in November. Then there was £29,946 on 
scheduled flights to Thailand in February.

Royal aides stressed yesterday that the trips were already in the 
prince’s diary and that he was duty-bound to meet those commitments.

Details of the trips emerged in the annual Royal Public Finance Report, 
which lays bare how much the Queen gets from the public purse over the 
year 2011-2012 and how she spends it. 

Official expenditure rose marginally to £32.3million – up £200,000 or 0.6 of a per cent.

But Buckingham Palace aides stressed that they had actually realised a 
26 per cent reduction in spending over the last three years in real 
terms. They say the monarchy costs just 52p a head for every man, woman 
and child in the country – although this does not include the estimated 
£200million bill for security.

Prince Andrew, pictured in 2009, is nicknamed Air Miles Andy because of his love of travelling by helicopter. Taxpayer cash used to pay for official Royal Family air and rail travel at home increased to £6.1million in 2011/12

The Prince of Wales and the Duchess of Cornwall mingle in Tanzania last October during a tour that also took in the Middle East and South Africa. Their private jet for the trip cost taxpayers £460,387

Making friends: Prince Harry poses with Usain Bolt in Kingston, Jamaica, during his jubilee tour on behalf of the Queen in March. The trip cost £107,098

‘The Queen was very keen that the Royal Household should play its part 
in reducing expenditure and she is pleased that this has been achieved,’
said Sir Alan Reid, Keeper of the Privy Purse.

Sir Alan said they had cut their costs by freezing staff pay and 
generating more income by renting out royal property. But he also 
revealed they would need to eat into their savings by £3million to meet 
the cost of the Diamond Jubilee celebrations.

The report only details 
journeys by air or on the royal train costing £10,000 or over – 72 in 
all this year.  Easily the most expensive trip of the year was Prince 
Charles’s tour of the Middle East and Africa last November with the 
Duchess of Cornwall. It cost £460,387 to hire the couple a jet.

The prince and his wife also spent £19,583 taking the Royal Flight down 
from Scotland, where they were on holiday, last August to visit some of 
London’s riot-hit streets.

Younger members of the Royal Family were also clocking up the air miles –
although the publicity and goodwill generated by Prince Harry’s 
inaugural royal tour earlier this year is said by Foreign Office sources
to be ‘incalculable’.

William and Kate are also likely to raise eyebrows over the bill for 
their first tour as a royal couple to Canada and the US last year, 
booking business class flights home from LA for themselves and seven 
staff costing £51,410.

William and Kate and their adviser, Sir David Manning, were then given a free upgrade to first class by British Airways.

A senior royal aide defended the costs saying that William, Kate and 
Harry in particular had shown enormous willingness to embrace ‘a 
different style of travel’ – for that read less expensive – to ‘older 
members of the Royal Family’.

Aides stressed all foreign trips were taken at the request of the 
Government and Foreign and Commonwealth Office and were rubber-stamped 
by the palace’s visits committee to ensure they were as cost effective 
as possible.

Anti-monarchist group Republic rejected palace claims of frugality and 
accused it of being ‘one of the most profligate institutions in the 
world’.

Expensive upkeep: Royal 'bean counters' said they had managed to reduce their spending by 26 per cent in real terms over the last three years

Cuts: The cost of running the Buckingham Palace press office, maintaining the official website (pictured) and providing information to the public fell from £500,000 to £400,000

@highlight

Buckingham Palace releases Annual Report into Royal Public Finances for 2011/12 tax year

@highlight

Prince Andrew clocked up £378,000 bill on flights in his last few months as a controversial global ambassador for UK trade and industry

@highlight

Prince of Wales and Duchess of 
Cornwall's private jet for tour of Middle East, South Africa and Tanzania cost taxpayers £460,387

@highlight

Prince Harry's jubilee tour on behalf of the Queen in March cost £107,098

@highlight

But accounts show that Royal Family cost Britain just 52p per head which amounts to £32.3million, up £200,000 on previous year