By
Ryan Lipman

A Northern Territory man tried to illegally sell a wallaby joey on Facebook.

The animal was rescued uninjured from a Broome car park by  Department of Parks and Wildlife officers and Western Australia Police last Thursday.

Despite the sale being illegal, the man advertised the joey for $3,500 (Â£1,926) and received an offer of up to $10,000 (Â£5,500) from a visiting overseas buyer.

Shocking: A Western Australia Parks and Wildlife Department officer seized a wallaby joey (pictured), which was rescued from a Broome car park after it was posted for sale on Facebook

A wildlife officer took part in a covert operation to seize the animal, by posing as a potential buyer in plain clothes.

Wildlife officer Peter Carstairs said the 26-year-old man would be charged with offences including possession, importation and selling of protected wildlife.

'It is illegal to sell or possess any part of a native animal in Western Australia unless you have a wildlife licence,' he said.

The man imported the wallaby from the Northern Territory into Western Australia, where he then tried to sell using Facebook.

A Parks and Wildlife spokeswoman said it was not known how the man got the joey or how long he had it for.

Outrage: The animal attracted bids as high as 10,000 before the man was caught (Wallaby pictured)

'There is a black market trade in Australian wildlife and it is a practice that must be stopped,' Mr Carstairs said.

The department was altered to the man's actions after residents' concerns, which lead them to make complaints.

'The community outrage generated by this incident shows that people really care about protecting our native wildlife,' he said.

The man could be charged with up to five offences under the Wildlife Conservation Act 1950 and face penalties of up to $4,000 (Â£2,200) for some charges.

The spokeswoman said the wallaby was being cared for by a wildlife rehabilitator, but sustained no significant injury in the man's care.

Black market trade: A Parks and Wildlife spokeswoman said it was not rare for people to attempt to sell native Australian animals, such as the pictured wallabies, on social media and consumer sites such as Gumtree (library image)

'It's diet while in the man's care wasn't great,' she said. 'It's now healthy and doing great.'

The animal is expected to soon be returned to the Northern Territory when rehabilitation treatment finishes.

'We will contact our counterpart agency in the Northern Territory to arrange the wallaby's return,' she said.

The spokeswoman said incidents of people using social media and sites such as Gumtree to sell native animals was not rare. 'It's something that does happen... It's not a new thing,' she said.

Last year, a Japanese man was caught trying to smuggle lizards from the state.

'He received a suspended sentence and a fine. He was trying to take them from Western Australia back to Japan because they're quite valuable there,' she said.

The wallaby joey was illegally imported from the Northern Territory, to Broome, pictured, in Western Australia

@highlight

A Northern Territory man  tried to sell a wallaby joey on Facebook

@highlight

He was caught by a wildlife officer in plain clothing, who posed as a buyer

@highlight

The man will be charged with offences including selling protected wildlife

@highlight

Despite being illegal, the sale attracted bids of up to $10,000 for the animal

@highlight

The joey is safe and currently being cared for by a wildlife rehabilitator