Genius: Alan Turing, who certainly earned his stripes in the scientific world

For the first time experimental evidence has been put forward confirming great British mathematician Alan Turing’s theory of how biological patterns such as tiger stripes or leopard spots are formed.

Turing, whose centenary falls this year, put forward the idea that regular repeating patterns in animals are generated by a pair of morphogens that work together as an ‘activator’ and ‘inhibitor’.

Now researchers from King’s College in London have validated the famous code-breaker’s 60-year-old theory in tests that also advance regenerative medicine.

To test the theory the researchers studied the development of the regularly spaced ridges found in the roof of the mouth in mice.

Carrying out experiments in mouse embryos, the team identified the pair of morphogens working together to influence where each ridge will be formed. These chemicals controlled each other’s expression, activating and inhibiting production and therefore controlling the generation of the ridge pattern.

The researchers were able to identify the specific morphogens involved in this process – FGF or Fibroblast Growth Factor, and Shh, which stands for Sonic Hedgehog – so-called because laboratory fruit flies lacking the fly version have extra bristles on their bodies.

Cat's amazing: Tigers have stripes because of the behaviour of specific morphogens

Turing was one of the great unsung heroes of World War II.

He broke the German military's secret codes - created using the famous Enigma machine - that helped British Intelligence stay one step ahead of Hitler, allowing the Navy to defeat his U-boats and win the Battle of the Atlantic.

Turing's work even laid the foundation for the creation of modern computers, leading Time magazine to name him one of the 100 most important people of the 20th century.

'Everyone who taps at a keyboard, opening a spreadsheet or a wordprocessing program, is working on an incarnation of a Turing machine,' it said.

But Turing was shamefully ignored by the British Establishment, and then killed himself in 1954 after being convicted of being a homosexual and forced to undergo hormone therapy.

They showed that when these morphogens’ activity is increased or decreased, the pattern of the ridges in the mouth palate are affected in ways predicted by Turing’s equations. 

For the first time the actual morphogens involved in this process have been identified and the team were able to see exactly the effects predicted by Turing’s 60-year-old speculative theory.

Dr Jeremy Green from the Department of Craniofacial Development at King’s Dental Institute said: ‘Regularly spaced structures, from vertebrae and hair follicles to the stripes on a tiger or zebrafish, are a fundamental motif in biology. T

'There are several theories about how patterns in nature are formed, but until now there was only circumstantial evidence for Turing’s mechanism. Our study provides the first experimental identification of an activator-inhibitor system at work in the generation of stripes – in this case, in the ridges of the mouth palate.

‘Although important in feeling and tasting food, ridges in the mouth are not of great medical significance. However, they have proven extremely valuable here in validating an old theory of the activator-inhibitor model first put forward by Alan Turing in the 50s.

‘Not only does this show us how patterns such as stripes are formed, but it provides confidence that these morphogens (chemicals) can be used in future regenerative medicine to regenerate structure and pattern when differentiating stem cells into other tissues.

‘As this year marks Turing’s centenary, it is a fitting tribute to this great mathematician and computer scientist that we should now be able to prove that his theory was right all along!’

Results of the study were published this week in Nature Genetics.

 

@highlight

Alan Turing's 60-year-old theory is validated