It looks unlike any other skyscraper ever designed - and appears at first glance to be wearing a giant wig.

However, experts say this bizarre design could be the future of high rise buildings.

The 'hairs' are in fact thin fibres that convert movement as they are blown about into energy, taking advantage of the winds on the higher levels of the building.

An artist's impression of the 'hairy skyscraper' planned for Stockholm. The 'hairs' are in fact thin fibres that convert movement into energy as they are blown by the wind

The straws of the facade 
consist of a composite material with piezoelectric properties that can 
turn motion into electrical energy.

Piezoelectricity is created when 
certain crystals’ deformation is transformed into electricity.

The 
technique has advantages when compared to traditional wind turbines 
since it is quite and does not disturb wildlife. 

It functions at low 
wind velocity since only a light breeze is sufficient for the straws to 
start swaying and generate energy.

The plans have been created by Belatchew Arkitekter, who called the project 'Strawscraper'. The new tower is designed to be built on top of a building in the centre of the city.

'Belatchew Arkitekter wants to give 
Söder Torn its original proportions and at the same time explore new 
techniques that could create the urban wind farm of the future,' the 
firm says.

'By using piezoelectric technology, a 
large number of thin straws can produce electricity merely through small
 movements generated by the wind.

'The result is a new kind of wind power plant that opens up possibilities of how buildings can produce energy.

'With the help of this technique surfaces on both old and new buildings can be transformed into energy producing entities.'

The plans also include a top floor restaurant where diners can peer out between the 'straws'

The firm says the bizarre coating can even be used as a tourist attraction.

'The constant movement of the straws creates an undulating landscape on the facades.

'What is usually considered to be the
 most static of all things, the building, suddenly comes alive and the 
construction gives the impression of a body that is breathing.

'The straws swaying in the wind gives 
the building a constantly changing facade further reinforced at 
nighttime with lighting in changing colors.'

The facade can be lit up at night using different coloured LED lights. creating huge light shows

@highlight

Building planed for Stockholm could be a blueprint for rest of the world

@highlight

Covered in thin 'straws' that produce energy as they are moved by the wind

@highlight

The straws can be lit up at night