By
Jonny Singer for MailOnline

Follow @@Jonny_Singer

Arsenal owner Stan Kroenke has caused outrage among fans by taking £3million out of the club, the side's accounts show.

'Silent' Stan, as he is sometimes known, has always suggested he would not take dividends when addressing the Arsenal fans.

But the American received a payment to his company KSE LLC for 'strategic and advisory services', according to The Guardian.

Kroenke (bottom right) was at the Emirates Stadium to watch Arsenal draw with Manchester City this month

The Arsenal majority shareholder has invested in the likes of Alexis Sanchez over the summer

The move has sparked outrage among Gunners fans, as the money is the same amount generated by a 3 per cent rise in the price of season tickets this season.

Arsenal fans already pay the highest price for an average ticket of any Premier League club. 

The club's AGM, which has seen the American majority shareholder questioned about his intentions in previous years, takes place in three weeks, and will be a chance to voice their concerns with the payment.

Kroenke owns NFL team the St Louis Rams and the NBA's Denver Nuggets, and has never taken a dividend from either franchise.

Kroenke (left) has never taken money out of his American franchises including the NFL's St Louis Rams

Arsenal fans already pay the most in the league for tickets and have seen them rise this season by 3 per cent

Like our Arsenal Facebook page here. 

@highlight

Stan Kroenke has never taken a dividend from American teams he owns

@highlight

Arsenal season ticket cost went up by 3% this season - in total this was also worth £3m 

@highlight

Money paid for 'strategic and advisory services' 