By 
Sam Webb

PUBLISHED:

10:00 EST, 3 November 2012


| 

UPDATED:

10:01 EST, 3 November 2012

This incredible image shows a the sun adorned with a glittering halo - a rare phenomenon called a 'sun dog'.

It was taken in the aftermath of Superstorm Sandy by NASA solar physicist David Hathaway in Huntsville, Alabama two days ago.

The effect is generated by plate-shaped hexagonal ice crystals in 
high and cold cirrus clouds or, during very cold weather, by ice 
crystals called diamond dust drifting in the air at low levels.

Blinding beauty: Nasa scientist David Hathaway captured the incredible phenomenon, believed to be caused by Superstorm Sandy

Science blog Spaceweather writes that the extremely rare apparition was 'almost certainly connected to Hurricane Sandy'.

The core of the storm swept well north 
of Alabama, but Sandy’s outer bands did pass over the area, leaving 
behind a thin haze of ice crystals.

NASA’s Meteoroid Environment Office head Bill Cooke says that he had 'never seen anything quite like it'.

Another onlooker, Kyle Winkleman, called it a 'once-in-a-decade event'.

A sun dog, scientific name parhelion from Greek 'beside the sun', creates bright spots of light in the sky, often on a luminous ring or halo on either side of the sun

Sundogs may appear as a colored ball of light to the left or right of the sun and in ice halos.

They can be seen anywhere in the world and are most dazzling when the sun is low.

Halo: A sundog (parhelion) is seen around the sun over the Malaysian island of Langkawi in 2007

@highlight

Rare optical effect causes a halo of light around the sun

@highlight

NASA scientist took breathtaking image after storm that ravaged U.S.