A businessman funded his lavish lifestyle using a £1.6million scam that tricked investors into thinking they were saving the rainforest, a court has heard. 

Mathew Ames, 38, is accused of persuading a number of people to plough their life savings and pensions into two investment schemes that he claimed would provide 15 per cent annual returns through Sri Lankan teak trees or carbon credit.

Instead the Essex-based Forestry for Life and The Investor Club were part of an elaborate Ponzi scheme which Ames used to hire a Lamborghini, rent Caribbean accommodation and make use of an executive lounge at Colombo Airport in Sri Lanka, Isleworth Crown Court was told.

Sham: Mathew Ames (left) is accused of setting up a £1.6 million Ponzi scheme. He enlisted the support of celebrities, with former footballer Jack Charlton (right) attending the opening of Forestry for Life

The court heard Ames, of Thundersley in Essex, got well known faces including veteran sports executive Sir Rodney Walker and industry experts to help promote the schemes.

The property mogul and charity trustee is one of 20 witnesses called by the prosecution and the court was he had been recruited as chairman of Forestry for Life, but never registered as a director.

Former footballer Jack Charlton was among the guests at the opening of Forestry for Life.

Prosecutor Stuart Biggs said: 'The method was to create an enticing glossy brochure. It included quotes from Prince Charles, Tony Blair and referenced the Kyoto Protocol and Harvard University. There was an added bonus you were doing something ethical.'

He added: 'In truth no investments were made by either company, not a single piece of land was purchased abroad or a tree planted, or money kept safe in a separate account. It was used to pay company expenses, staff, and to support Mr Ames and his lifestyle.'

The court also heard that in 2010 Ames bragged to top racing driver David Brabham about how well his companies were doing before any land had even been bought.

Ames
 said in an email to the sports star: 'David you just caught me out of 
the Lamborghini after ordering my new one. I had a meeting about you the
 other day and I have opened offices in Dubai, Singapore and Sri Lanka.'

Reward: Mathew Ames is accused of using the income from fraudulent businesses to fund a lavish lifestyle, including this home in Thundersley, Essex. He allegedly claimed investors would see 15 per cent returns

Stuart Biggs prosecuting told the jury it was to give the false impression of a successful business to attract investment.

City of London investigators found evidence £250,000 was paid out to investors, but it came from other clients’ deposits and not generated by any investment. 

Mr Biggs added: 'This is often referred to as a Ponzi scheme, taking from Peter to pay Paul out of new creditors’ money that is being shuffled around.'

Mr Biggs said while running both companies Ames dishonestly represented what invested money would be used for, the level of return, and misappropriated cash for other uses. 

The court heard one agent, who also invested, was shown title deeds for land in Brazil which Ames’ companies never bought, while an industry advisor who suggested it may be a Ponzi scheme was sacked. 

By late 2010 interest payments to clients stopped and both firms were liquidated in March 2011 after the Financial Services Authority got wind of the unregulated investments. 

Ames was arrested in September that year and denies two counts of fraudulent trading between 2008 and 2011. 

The trial continues.

Sorry we are not currently accepting comments on this article.

@highlight

Mathew Ames, 38, is accused of setting up an elaborate Ponzi scheme

@highlight

His Essex-based businesses were allegedly part of a £1.6 million scam

@highlight

Conman enlisted celebrities and experts to support fake investment

@highlight

Ames is believed to have used money to fund international jet setting