Florida State quarterback Jameis Winston was cleared of the accusations he faced at a student code of conduct hearing involving an alleged sexual assault two years ago, according to documents obtained by The Associated Press on Sunday.

Former Florida Supreme Court judge Major Harding wrote in a letter to Winston that the evidence was 'insufficient to satisfy the burden of proof.' Prosecutor Willie Meggs made a similar decision a year ago when he decided not to criminally charge Winston, citing a lack of evidence.

This month, a two-day hearing was held to determine whether Winston violated four sections of the code of conduct - two for sexual misconduct and two for endangerment.

The ramifications for Winston ranged from a reprimand to expulsion from school.

The woman can request an appeal within five days.

Scroll down for video 

Cleared: Florida State quarterback Jameis Winston was cleared of the accusations he faced at a student code of conduct hearing involving an alleged sexual assault two years ago

'We will consider an appeal but right now we feel a little duped,' said Baine Kerr, one of the woman's lawyers. 'At some point we have to recognize that Florida State is never going to hold James Winston responsible.'

AP is not identifying the woman because it does not identify people who say they are victims of sexual abuse.

Kerr said in the emailed statement that between his client, Winston, and two teammates that were at the off-campus apartment - Chris Casher and Ronald Darby - only the woman would answer questions about what happened.

'Somehow Jameis Winston still wins,' Kerr said. 'The order doesn't even follow the Student Conduct Code and it ignores the bulk of the evidence.'

Florida State president John Thrasher said in a statement that the university selected the former state Supreme Court justice to remove any doubt about the integrity of the process.

'He (Harding) conducted a thorough Student Conduct Code hearing and reviewed more than 1,000 pages of evidence generated by three other investigations, and we would like to thank him sincerely for his service,' Thrasher said.

Harding wrote that both sides' version of the events had strengths and weaknesses, but he did not find the credibility of one 'substantially stronger than the other.'

Game time: Florida State faces Oregon in the College Football Playoffs semifinal on January 1. Before the ruling, there were questions whether Winston would be available to play

Ruling: This month, a two-day hearing was held to determine whether Winston violated four sections of the code of conduct - two for sexual misconduct and two for endangerment

'In sum, the preponderance of the evidence has not shown that you are responsible for any of the charged violations of the Code,' Harding wrote.

Winston family adviser David Cornwell did not respond to requests for comment.

Cornwell has contended that attorneys for the former student pushed for the hearing after they were rebuffed in an attempt to reach a settlement with Winston.

Florida State faces Oregon in the College Football Playoffs semifinal on January 1. Before the ruling, there were questions whether Winston would be available to play. The Seminoles won a national championship with Winston at the helm last season and have not lost a game since he earned the starting job before the beginning of the 2013 season.

Florida State is currently being investigated by the Department of Education on how hit handles possible Title IX violations. The woman who said Winston assaulted her filed a complaint with the U.S. Department of Education Office for Civil Rights, which decided the university should be investigated for possible Title IX violations over the way it responds to sexual violence complaints.

Title IX is a federal statute that bans discrimination at schools that receive federal funding. The Department of Education in 2011 warned schools of their legal responsibilities to immediately investigate allegations of sexual assault and domestic violence, even if the criminal investigation has not concluded.

 

@highlight

Jameis Winston was cleared of the accusations he faced at a student code of conduct hearing involving an alleged sexual assault two years ago

@highlight

Former Florida Supreme Court judge Major Harding wrote in a letter to Winston that the evidence was 'insufficient to satisfy the burden of proof'

@highlight

Prosecutor Willie Meggs made a similar decision a year ago when he decided not to criminally charge Winston, citing a lack of evidence

@highlight

This month, a hearing was held to determine whether Winston violated four sections of the code of conduct

@highlight

The woman can request an appeal within five days 