By 
Daniel Miller

PUBLISHED:

08:53 EST, 15 March 2013


| 

UPDATED:

13:17 EST, 15 March 2013

A shadow has fallen over Middle Earth, battle lines have been drawn and a daunting quest to protect the good names of Gandalf and the Hobbits of the Shire is currently underway.

But it isn't the dark forces of Sauron or the fiery breath of Smaug the dragon that threatens the peace of J.R.R. Tolkien's mystical land, but the hideous spectre of Lord of the Rings branded fruit machines.

The Tolkien estate, which is fiercely protective of the late author's work, is up in arms following the appearance of the gambling machines in Las Vegas casinos.

Wrangle: The Estate of J.R.R. Tolkien author of 'The Hobbit' and 'The Lord of the Rings' Gollum is locked in a legal battle with Warner Bros, makers of The Lord Of The Rings and the Hobbit films over gambling machines

Threat: The Tolkien estate is unhappy about the appearance of Lord of the Rings-themed gambling machines in Las Vegas casinos

They claim the use of Tolkien's characters to promote gambling is a clear breach of contract and that it damages the good name of Tolkien and the reputation of the books.

Last year just days before the November premier of the Hobbit, they sued Warner Bros, In Line Cinema and Saul Zaentz owner of MIddle Earth Enterprises (MeE) which owns worldwide rights to elents of the Hobbit and the Lord of the Rings for at least $80million (£53million) over alleged exploitative 
merchandising.

Prized: The Tolkien estate is fiercely protective of the late author's work

The lawsuit claims the production of Tolkien based gambling games 'has outraged Tolkien's devoted fan base, causing irreparable harm to Tolkien's legacy and reputation and the valuable goodwill generated by his works.'

Tolkien's family contends their merchandising agreement with Warner Bothers extends only to tangible products such as 
figurines and clothing and not to electronic rights.

But now Warner Brothers have counter sued  claiming they have lost out on millions of dollars of revenue as a result of the Tolkien estate preventing from using the characters to the extent they might have wished.

But the Tolkien Estate's legal team say this amounts to bullying and that they intend to dismiss Warner Bros's counterclaims.

Their US attorney, Bonnie Eskenazi, said: 'The defendants’ amended counterclaims are nothing more than an effort to sue the Tolkiens and HarperCollins for suing them. 

'They are entirely without merit and are a classic example of studio “bullying tactics.” 

'The Tolkiens and HarperCollins filed this lawsuit in order to force Warner Bros and Zaentz to live within the boundaries of the contract to which they agreed. 

'Warner Bros’ and Zaentz’s amended counterclaims are simply an attempt to punish the Tolkiens and HarperCollins for having the nerve to stand up to the studios and tell them that they can’t take more rights than were granted to them by contract. 

Blockbuster: The first part of the Hobbit Trilogy has reportedly already grossed $1bn

'Luckily, the law protects people like the Tolkiens and HarperCollins from these kinds of intimidation tactics.'The adaption of the Tolkien's novels to the big screen has proved an impressive money-spinner for the Hollywood studio.

The Lord of the Rings film trilogy, directed by Peter Jackson, earned an estimated $6 billion from 
movie tickets, DVDs and merchandise.

Money: The Tolkien estate was seeking $80 million from Warner Bros., its New Line subsidiary and producer Saul Zaentz (pictured)

And the adaption of Tolkien's first Middle Earth book The Hobbit appears to be set for equally impressive results with the first of that trilogy already pulling in an estimated $1billion.

Film fans and critics have accused Warner of being greedy by stretching the Hobbit, which as a book is roughly half the size of a single Lord of the Rings volume, into three films.

It is not the first time Warner Bros have become caught up in legal proceedings with the Tolkien estate.

Tolkien's
heirs settled a lawsuit over the 'Lord of the Rings' movies for an 
undisclosed amount in 2009, allowing production to proceed on 'The 
Hobbit'.

That lawsuit against New Line Cinema 
claimed Tolkien's trust received only an upfront payment of $62,500 for 
the three movies before production began but was due 7.5 per cent of the 
gross receipts.

And last year none other than Gandalf actor Sir Ian McKellen had to step in after MeE demanded a Southampton pub called the Hobbit changed its name.

After Sir Ian accused MeE of 'unnecessary pettiness', the company offered the bar a nominal licensing fee to settle the row.

Warner Bros has been unavailable for comment.

@highlight

Warner Bros studio counter sue Tolkien estate following $80m claim

@highlight

Estate says this amounts to bullying and they will dismiss counterclaim