3D printing has been used to make everything from toys and plaster casts to parts for jet engines.

And now one German automotive company has unveiled a revolutionary conceptual car body that it claims will only be made possible by using what is termed as 'additive manufacturing' or large-scale 3D printing.

The internal structure is inspired by the shape of a turtle skeleton and is designed so that it will provide incredible protection and cushioning, just like the animal’s shell.

Scroll down for video

A German automotive company has unveiled a conceptual futuristic car body (pictured) that it claims will only be possible thanks to the 3D printing process

EDAG created the concept to show what it thinks will be possible in the way of car manufacturing using 3D printing.

Its structure is inspired by the shape of a turtle shell and is designed to provide protection and cushioning.

In the future the car's internal body could be made using high-resolution fuse deposition modelling (FDM) machines.

The internal structure would be 3D printed using a mixture of thermoplastic materials and carbon fibre.

A metal casing would shield the 3D printed internal frame.

Experts believe the concept is over a decade away from becoming reality.

In the future the car body could be made in one piece using high-resolution fuse deposition modelling (FDM) machines and then sheathed in metal to protect it.

EDAG’s ‘Genesis’ concept has gone on show at the Geneva Auto Show, which is focused on the future of car design.

The car body is intended to be built using 3D printing and a mixture of carbon fibre and plastic.

The company says its concept is ‘designed to demonstrate the revolutionary potential of additive manufacturing.’

The structure (illustrated bottom) is inspired by the shape of a turtle shell and is designed so that it will provide protection and cushioning, just like the animal's shell (pictured top)

In the future the car body (illustrated) could be made in one piece using high-resolution fuse deposition modelling (FDM) machines

EDAG claims that cars based on organic structures ‘cannot be built using conventional tools’.

The firm believes that 3D printers will one 
day manufacture a car's entire body and envision a continuous strand of carbon
 fibre being used within the printing process, helping to create an ultra-  strong outer shell of a vehicle in one piece.

While hi-tech plastic might seem like an odd choice of material to build a car’s body from, the company said: ‘Unlike other technologies, FDM makes it possible for components of almost any size to be produced, as there are no pre-determined space requirements to pose any restrictions.

'Instead, the structures are generated by having robots apply thermoplastic materials.’

Cars need to be strong to withstand collisions so the German firm plans to introduce 'endless carbon fibres' to the 3D printed frame (illustrated) during the production process, which they say will give the body the strength and stiffness needed

Cars need to be strong to withstand collisions so the German firm plans to introduce ‘endless carbon fibres’ during the production process, which they say will give the body the strength and stiffness needed.

Designers used a turtle shell to inspire the shape of the car body to create a body that ‘cushions and supports’ an interior carriage, surrounded by reinforcing metals for an outer shell.

Designers used a turtle shell to inspire the shape of the car body to create a body that 'cushions and supports' an interior carriage, surrounded by reinforcing metals (illustrated)

Experts believe the concept is over a decade away from becoming reality, but production of components is feasible at the moment.

‘As for the target of using additive manufacturing to produce complete vehicle bodies, there is still a long way to go before this becomes an industrial application, so for the time being, it remains a vision,’ the firm said.

Experts believe the concept (pictured) is over a decade away from becoming reality, but production of components using FDM machines is feasible at the moment

@highlight

German auto firm EDAG unveiled concept car at the Geneva Auto Show

@highlight

Its internal frame is designed to be 3D printed from a mixture of thermo- plastic materials and carbon fibre for strength and cushioning

@highlight

A conventional metal frame, also inspired by a shell, would protect the 3D printed internal structure