Stephen Hunt, 38, is believed to have died after being engulfed by some kind of 'super heat'

Two teenage girls have been arrested over the death of a fireman in a massive blaze at a hair products warehouse.

The fire is thought to have been started by youngsters smoking cigarettes and discarding them.

Former soldier Stephen Hunt, 38, was among 60 firefighters sent to tackle the inferno at Paul’s Hair World in central Manchester.

He is thought to have been enveloped in a cloud of ‘super-heat’ caused by steam or chemicals.

He and another fireman were pulled from the building and taken to hospital.

Mr Hunt, the father of two teenagers, was pronounced dead, while his colleague remains in hospital.

Two 15-year-old girls who were arrested on suspicion of manslaughter have been bailed until September pending further inquiries.

A police source confirmed that youngsters may have been smoking behind the building moments before the fire started.

Mr Hunt’s family paid tribute to him, saying: ‘Stephen was an old-fashioned gentleman with manners that are rare in this day and age, with core values which included loving his family, being the best father that he could be, loving and affectionate to those that were close to him.

‘Stephen lived to serve his country having served for seven years in the Royal Signals and then becoming a firefighter, which was a career that he was very proud of.

‘The whole family will miss spending time with Stephen, none more so than his son, daughter and grandmother. We loved his sense of humour and are very proud of him and what he brought to our lives.’

Scroll down for video

Firefighter Stephen Hunt has died after he was pulled from the wreckage of a wig shop in Manchester

Mr Hunt and a colleague got into difficulties shortly before 9am but he later died in hospital

The fire broke out on Saturday 
afternoon in a basement store-room at the warehouse, which supplies hair
 extensions and hair products.

Witness Ava Smart said: ‘People came 
running outside. I asked them what happened and they said someone was 
standing out the back smoking.

‘It happened so fast. It was horrendous.’

Owner Paul Barnett desperately tried 
to tackle the blaze with an off-duty fireman, but both were overcome and
 were taken to hospital suffering from smoke inhalation.

Store manager Nicola Purcell said: ‘They did everything they could with extinguishers and water until the fire brigade arrived. 

Staff from Paul's Hair World arrive with tributes, at the scene of the fire in Manchester

The fire service are still tackling the blaze and said the complex layout of the building has hindered efforts

The fire broke out at Paul's Hair World on Saturday afternoon and more than 60 firefighters were sent to the scene

‘Paul wasn’t well enough to come down today but wanted to pay his respects and asked the staff to lay flowers.’

The fire spread rapidly and around 
five hours later at 8.30pm a ‘BA emergency’ was declared – a signal for 
everybody to evacuate the building.

Steve McGuirk, Manchester’s county 
fire officer, said: ‘We had some real problems. This was a building 
stacked full of hair products, chemicals and a huge amount of 
combustible materials.

‘For some reason we don’t know, the 
situation rapidly deteriorated and we took the decision to evacuate the 
building.  It was during this evacuation that two firefighters  were 
pulled out by colleagues. First aid was given and they were whipped off 
to hospital, but tragically Stephen was declared dead on arrival.’

Fire service paid tribute to Mr Hunt (not pictured) and his colleague's 'professionalism and courage'

He said Mr Hunt appeared to have been enveloped by ‘an absolutely massive, ferocious and sudden build-up of heat’.

He did not rule out that it may have 
been generated by steam or chemicals inside the building. He added: ‘We 
are devastated by the loss of one of our colleagues in the line  of 
duty.

‘It brings home the dangers that our firefighters put themselves in every day to keep the community safe.’

The fire was still being damped down 
yesterday, while flags at fire stations all over Greater Manchester flew
 at half mast, including the one at Philips Park where Mr Hunt was 
based.

Sorry we are not currently accepting comments on this article.

@highlight

Stephen Hunt, 38, was tackling fire at Paul's Hair World in Manchester

@highlight

Fire service said father-of-two was engulfed by a 'super heat'

@highlight

Two 15-year-old girls arrested on suspicion of manslaughter

@highlight

He and colleague got into difficulties before being rescued by firefighters

@highlight

Both were taken to hospital but Mr Hunt was pronounced dead

@highlight

Greater Manchester Fire and Rescue Service said they 'are devastated'