By 
Steve Nolan

PUBLISHED:

11:50 EST, 29 November 2013


| 

UPDATED:

11:51 EST, 29 November 2013

A picture circulating on social media appearing to show Syrian rebels butchering a zoo lion is the latest evidence that residents of the war torn country are starving, according to activists.

The photograph, which has not been independently verified, shows three men standing around the body of a lion.

One of them is holding the lion's head while another appears to be cutting meat from the animal's hind legs.

A picture circulating on social media appearing to show Syrian rebels butchering a zoo lion is the latest evidence that residents of the war torn country are starving, according to activists

What appears to be a chunk of meat can be seen laying on the ground next to the emaciated looking lion.

The animal is thought to be from the Al-Qarya al-Shama Zoo.

While some reports suggest that the men are skinning the animal to use its coat to keep warm, others have suggested that the animal was already dead.

Residents in areas hardest hit by the civil war, including the eastern area of Ghouta, were residents have reported desperate food shortages.

Last month a cleric issued a fatwa to allow starving people in the region to eat cats and dogs.

'We issued a religious edict allowing people to eat dog and cat meat. Not because it is religiously permitted, but because it is a reflection of the reality we are suffering,' said Sheikh Saleh al-Khatib.

'People here have nothing for their children. I am on strike because I want to help save food for others.'

Hunger: A boy eats maize as people shop in Aleppo but many others are said to be struggling for food in areas of Syria

According to the Daily Telegraph, the United Nations said today that civilians are going hungry in beseiged areas as they are inaccessible.

The UN handed out food to 3.3million people in Syria in October.

The World Food Programme added that the nutritional state of those trapped by fighting in parts of Damascus and rural areas has deteriorated significantly in recent months.

The picture has emerged as a report by the UN High Commissioner for Refugees has revealed that a growing number of Syrian refugee children in Lebanon and Jordan are fast becoming primary providers for their families.

With the Syrian conflict in its third year, the 61-page report highlights the plight of the children, who are growing up in fractured families, missing out on education and increasingly going out to work to help support extended families in exile.

More than two million Syrians fled their homes because of the country's raging conflict, seeking shelter in neighboring countries such as Jordan, Lebanon, Turkey and Iraq. At least half of the refugees - 1.1 million - are children.

Refugees: A UN report has revealed that children are becoming the main providers for many refugee families at makeshift camps in countries such as Lebanon and Jordan. Pictured is a camp in Lebanon

Of those, some 75 percent are under the age of 12, the UNHCR report said.

Children as young as seven work long hours of manual labor in fields, farms and shops for little pay, sometimes under dangerous or exploitative conditions, the report added.

In Jordan's sprawling Zaatari refugee camp, most of the 680 small shops employ children, the report also said.

A UNHCR assessment of refugee children living outside of the camp found that in 11 of the country's 12 provinces, nearly every second refugee household surveyed relied partly or entirely on income generated by a child.

End of training: Islamist fighters hold up their weapons during their 'graduation ceremony' at a camp in eastern al-Ghouta, near Damascus

Combat ready: Islamist fighters demonstrate their skills during their graduation ceremony at a camp in eastern al-Ghouta

In Lebanon, hundreds of refugee children - many of them girls aged seven to 12 - are picked up daily at dozens of informal refugee settlements dotting the Bekaa Valley and border areas in the north, loaded onto trucks and taken to the fields where they work for six to eight hours and earn up to 6,000 Lebanese pounds per day.

Many Syrian refugee children in Lebanon also fall into the hands of criminal gangs specialized in exploiting the most vulnerable victims of the conflict.

They are seen begging on the streets of Beirut or more frequently selling flowers and gum for their often abusive patrons.

Meanwhile, photographs emerged today of a sinister 'graduation ceremony' from a combat training camp in al-Ghouta.

Islamist fighters were pictured carrying weapons and their freshly learned military skills as they marched during the ceremony near Damascus.

The newly graduated fighters, who went through military training, will operate under the Islamist Ahrar al-Sham brigade.

Masked: The newly graduated fighters, who went through military training, will operate under the Islamist Ahrar al-Sham brigade

@highlight

The graphic photograph has been circulating on social media websites

@highlight

It is believed that the emaciated animal is from the Al-Qarya al-Shama Zoo

@highlight

A UN report reveals that growing number of children in refugee camps becoming main provider for their families