By
Ap  Reporter

Southern California coastal areas filled sandbags and built sand berms Tuesday to ward against possible flooding from big and potentially damaging surf spawned by Hurricane Marie spinning off Mexico's Pacific coast.

A large southerly swell was expected to produce large waves, rip currents and strong longshore currents in Los Angeles and Ventura counties through Thursday, according to the National Weather Service.

'These areas will potentially see the largest surf seen in recent years, with breakers of 10 to 15 feet possible,' a Weather Service advisory said.

Scroll down for video 

Breakers: Beachgoers watch large waves crash on the shore at Seal Beach, California on Tuesday as Southern California prepares for some of the biggest waves in years thanks to offshore Hurricane Marie

Making the most of it: A body surfer swims through a wave at Seal Beach in Southern California. A large southerly swell was expected to produce large waves, rip currents and strong longshore currents in Los Angeles and Ventura counties through Thursday

Taking precaustions: Residents in Southern California coastal areas filled sandbags and built sand berms Tuesday to ward against possible flooding from big and potentially damaging surf spawned by Hurricane Marie off Mexico's Pacific coast

Swimmers and surfers were urged to be aware of dangerous conditions, and minor coastal flooding and beach erosion is possible, forecasters said.

In the city of Long Beach's Peninsula neighborhood, residents watched as bulldozers built huge sand berms between the ocean and their homes. Several took the warning to heart and shoveled sand into bags to place around their garage doors and entryways.

Big Wednesday: Californians are preparing for some of the biggest waves in years on Wednesday, calling to mind the 1978 surfing classic starring Gary Busey, Big Wednesday

Deborah Popek, who's lived in the area 20 years, took a walk along the boardwalk with her cat, Sophie, to check the surf and see how neighbors were preparing. She's had flooding in the past, she said, especially in her garage.

'It's always at the last minute that everybody panics because, you know, we don't expect things to happen,' she said. 'But they're really taking things seriously because the sandbar is as high as they've ever built it right now. I've never seen it this high.'

A few yards down the boardwalk, resident Corey Nelson shoveled sand into 10 sandbags with a friend's help. A firefighter had been to his home Monday with a warning and although the surf was quiet so far Tuesday, he chose to take it seriously.

'He said supposedly the waves come over the breakwater wall and there will be flooding,' he said, adding that the firefighter had talked about 10 to 15 foot waves at a breakwater that protects the Long Beach shoreline.

'We've had the water go over the breakwater right here and into our planter, and I mentioned that to him and he said, `Well expect that times three.''

The high surf advisory will be in place for several counties north and south of Los Angeles, including Orange County. But Los Angeles and Ventura counties will likely see the biggest storm surge, according to the NWS advisory.

Swells generated by Category 2 Marie were expected to reach Southern California by Tuesday, and could cause life-threatening surf and rip currents, as well as minor coastal flooding, the hurricane center in Miami said.

The U.S. Hurricane Center in Miami said Marie's maximum sustained winds decreased to 105 mph (165 kph). Additional weakening was forecast and the storm was expected to lose hurricane status in the next day or so.

Marie was centered about 550 miles (880 kilometers) west-southwest of the southern tip of Baja California and was moving northwest near 14 mph (22 kph).

Swells provoked by the storm were affecting much of Mexico's Pacific coast and the Hurricane Center was warning of dangerous surf and rip current conditions.

Hurricane-force winds extended up to 60 miles (95 kilometers) away from the storm's center, with tropical storm-force winds reaching out to 275 miles (445 kilometers).

Wet: Residents shelter from heavy rain brought by hurricane Marie, in Puerto Vallarta, Jalisco state, Mexico, on Sunday. Hurricane Marie intensified its activity throughout the day, reaching category five before eventually weakening once again as California prepared to face its impact later in the week

The southern Pacific coast state of Oaxaca requested federal disaster relief after about 10,000 homes were either damaged, flooded or cut off by mudslides on the state's mountainous rural roads due to rains associated with Marie last week. One man was injured in a mudslide but there were no reported deaths, the state government said late Sunday.

The government of Baja California Sur, closer to the hurricane's current location, said it would cancel some classes in the resort cities of Los Cabos as a precautionary measure.

Swells generated by Marie were expected to reach Southern California by Tuesday, and could cause life-threatening surf and rip currents, as well as minor coastal flooding, the hurricane center in Miami said.

@highlight

National Weather Service says breakers of 10-15 could come Wednesday

@highlight

Hurricane Marie is spinning in the Pacific and could kick up rip currents and strong currents in the LA area and Ventura through Thursday

@highlight

The massive storm formed Wednesday and is now bigger than Alaska