By 
Ray Massey, Transport Editor

PUBLISHED:

07:11 EST, 17 May 2012

 | 

UPDATED:

11:32 EST, 17 May 2012

Long summer holidays are cancelled for thousands of Vauxhall workers – but they’re still celebrating a famous victory and massive boost to the UK economy that has left German rivals reeling.

Scrapping the ‘traditional’ long car industry factory summer shutdowns is a central part of a ‘ground-breaking’ new round-the-clock flexibility deal which has secured its future,

Vauxhall’s Ellesmere Port plant has been handed £125million investment to build the new Astra model from 2015, with the creation of 700 direct jobs on top of the 2,100 already secured.

Driving forward: American bosses at Vauxhall's US parent company General Motors judged that British workers are more flexible, competitive and efficient - and less militant - than their counterparts in Germany

There will also be 3,000 more indirect jobs with suppliers thanks to £1billion of parts business generated by the deal.

The deal led Vauxhall’s giant American parent company General Motors to choose it to build the next generation Astra ahead of a rival German factory judged less efficient, competitive, hard-working or flexible  – and in a country struggling with a deepening Euro crisis.

Prime Minister David Cameron hailed it as ‘excellent news’ for the factory and for UK manufacturing on the same day it was announced  that export-driven UK car production, soared by nearly 10 per cent in April. Business Secretary Vince Cable said it was ‘fantastic news’ while Vauxhall bosses called it ‘a historic day.’

One insider said: ‘The German trade unions will go bonkers.’

Under the ‘unprecedented ‘ flexibility deal on pay and conditions agreed with a 94 per cent  majority by the workforce, the plant will  work 51 weeks a year,  increase the number of shifts from two to three per day, and  have a long-term four year pay agreement to ensure stability.

There is also the option for Saturday working and a 40 hour week when demand requires. The traditional summer shutdown in July and August will be scrapped to allow production to run through. But there will be a short shut-down between Christmas and New Year, said Vauxhall.

The four year pay deal also comprises a two year pay freeze from 2013 followed by two years of real terms increases of RPI inflation plus 1 per cent.

The new workforce agreement comes into force in 2013 and runs through the life of the next generation Astra, into the early 2020s.

Production will soar from 140,000 now to 160,000 and up to a capacity of 225,000.

Vauxhall chairman Duncan Aldred, who first worked at the Ellesmere Port factory 20 years ago as a graduate, said it was a ‘historic day’ for Vauxhall.

Busy: Production at the Ellesmere Port factory is to soar from the current 140,000 cars a year to 225,000

Of the flexibility deal he said: ’It will do away with the somewhat old fashioned factory shut-downs which have been in place in the UK workplace for centuries.’

Mr Aldred said: ‘It really does put Vauxhall Motors  at the forefront of  manufacturing, not only in this country but across Europe.’

Vauxhall will also raise the amount of ‘British-sourced components in the Astra to at least 25 per cent which will create further employment locally and in the UK overall and further increase the plant's competitiveness.

Ellesmere Port will be the lead plant to build the next generation five-door Astra hatchback  plus one other variant – either the Sports Tourer estate or the sporty GTC. That is to be decided.

But it means a German factory at Bochum – which was also bidding to build the next generation Astra – now faces the axe with the loss of more than 3,000 jobs.

Currently German workers at Bochum produce just 30 cars a hour over three shifts. By contrast, Ellesmere Port  workers produce 47 cars an hour on just two shifts – and will boost that even more when they move tho round the clock working of three shifts.

The deal turns on its head the notion that British plants  are first in line for closure because their ‘flexibility’ means they are easier and cheaper to shut than in Germany where the cost of lay of are significantly more expensive. Instead, the flexible agreements have proved a magnet for foreign investment.

Prime Minister David Cameron said: ‘This is excellent news for Ellesmere Port and for UK manufacturing.

‘Once again we have seen the success of the UK automotive industry and the crucial role it plays in growing and rebalancing our economy.’

He added: ‘This has been a real team effort with the Government, the company, unions and workers all focused on keeping production in the UK.

‘And the workforce at Ellesmere Port should take great pride in their skill, hard work and commitment which has proved vital to ensuring this great result today.’

Business Secretary Vince Cable said he was ‘proud’ to be at the factory for the announcement, describing it as a ‘very great day’.

‘The fact that big American car companies are making big investments in Britain is a good signal.’

Mr Cable stressed how productive the Ellesmere Port factory is when he held talks in New York with bosses from Vauxhall's parent firm General Motors

Mr Cable said there were no major taxpayer subsidies but that Vauxhall was free to apply for regional grants for training: ’We’ve not been waving a cheque book.’

He said that while the fate of the Euro might have played a part in GM’s decision, he did not believe it was the deciding factor. Competiveness was.

Leading motor industry expert Professor Garel Rhys said he was sounded out by General Motors’ American bosses about the relative efficiency of the UK and German factories adding: ‘They have looked rationally and forensically at the data.

Vauxhall’s Ellesmere Port factory has the second lowest unit costs for production anywhere in Europe. The Germans have had a shock.’

Prof Rhys, director of the Centre for Automotive Industry Research at Cardiff Business Schoolpredicted UK car production could hit a record 2.4million by 2015, beating the previous record of 1.92million set in 1972.

The official projection for this year is 1.55million.

‘The UK motor industry is on a roll, he added.

'Some 80 per cent of UK-built cars are now exported - the highest in Europe. We’re faring far better than the Continent and the Euro-zone which is struggling.’

Latest motor industry figures showed a near 10% rise in the number of cars built in Britain compared to a year ago - boosted by strong export demand, new figures showed. There were 94,352 cars produced in April, an increase of 9.3% on the same month in 2011, and up by 11.8% for the first four months of the year.

The Society of Motor Manufacturers and Traders (SMMT) said the figures showed that the UK remained one of the most competitive countries for car firms.

Almost half a million cars were built in the UK in the first four months of the year, with more than 400,000 for export.

The number of engines built increased by 1.2% last month to 192,408, while commercial vehicle production rose by 3.2% to almost 9,000, although it was 9% down in the year to date.

Paul Everitt, SMMT chief executive, said: ‘It is great news that Vauxhall will retain its Ellesmere Port plant and another important vote of confidence for the UK automotive industry, adding to the wave of recent investment decisions that have backed our facilities and workforce. 

“Manufacturing is now core to our country’s economy and the partnership forged between companies, employees, trades unions and government in the UK automotive industry demonstrates that the country is a globally competitive place to do business.’

@highlight

Announcement ends months of nail-biting over future of Cheshire plant

@highlight

Vauxhall's American owners are to close factory in Germany with loss of thousands of jobs after backing UK site

@highlight

British workers found to be more flexible, competitive and efficient than German counterparts