By
Emma Innes

PUBLISHED:
  
  
      08:31 EST, 11 March 2014
    
  

 | 
  UPDATED:
  
  
      14:37 EST, 11 March 2014

A great-grandmother can see her husband clearly for the first time in 15 years after she had a tiny telescope fitted in her eye - and says he's as lovely as he's ever been.

Margaret Ward, 90, lost her sight in 1999 after the gradual onset of late-stage macular degeneration.

It left her with no central vision in her left eye and only partial sight in the corner of her right eye.

Margaret Ward, 90, can see her husband, Charles, 95, clearly for the first time in 15 years after she had a tiny telescope fitted into her eye during a pioneering procedure. She said: 'I can see he hasn't changed at all in the past 15 years. He doesn't have any wrinkles and he's lovely'

As a result, she was unable to cook or read or recognise her husband Charles' face.

But she has become one of just seven people in the country to undergo pioneering surgery and have a pea-sized telescope - an Implantable Miniature Telescope, from CentraSight - implanted in her right eye.

She said: 'I am still in love with my husband Charles and it has been awful not seeing him properly for the past 15 years.

'I can see he hasn't changed at all in the past 15 years. He doesn't have any wrinkles and he's lovely.

'I am not one just to go on looks alone, so it's not just that he's gorgeous, he's just a wonderful person.'

The surgery Mrs Ward had involves removing the eye's natural lens and replacing it with a tiny telescopic lens - this is done under local anaesthetic.

Image shows how the telescopic lens magnifies the images that are projected onto the retina. It projects images onto the healthy part of the retina which is not degenerated by the disease

Mrs Ward had her right lens removed and replaced with a pea-sized telescopic one (pictured). This magnifies everything three times and is enabling her to recognise faces again for the first time in 15 years

This lens magnifies objects by three times and also projects images onto a healthy part of the retina instead of the areas damaged by the disease.

The patient then use the eye with the telescope for detailed central vision and the other eye for peripheral vision.

Mrs Ward, who has eight great-grandchildren, said: 'I can now see my great-grandchildren's faces properly and that is really exciting.'

The Implantable Miniature Telescope, from CentraSight, is implanted in place of the eye's lens - this has to be removed first.

The operation takes place under local anaesthetic while the patient is awake.

The new telescopic lens magnifies everything by three times.

The eye with the implanted telescope is then used for central vision while the other eye is used for peripheral vision.

Before the full benefits are reaped, the patient's brain has to get used to blending the magnified image with the image from the other eye.

The telescope is ideal for macular degeneration patients as the condition causes them to lose their central vision, but not their peripheral vision.

She added: 'Charles and I can watch 
sports on television – snooker and darts – without me having to 
constantly ask him who is playing.

'I can make out the difference and see who is taking the shot. We're sports mad, Charles and I, so this is really important to us.'

Mrs Ward, of Aylesbury, Buckinghamshire, underwent the surgery at the Spire Dunedin Hospital in Reading in August.

She says she only found out about it because she heard a news story about the procedure.

She said: 'I was getting desperate, I was struggling to cope and felt really in the doldrums.

'The first thing we knew about the CentraSight IMT telescope was one morning when we were having our early morning tea in bed with the television news on – I don't take much notice about it and heard something about macular degeneration and something about a telescope.

'I asked one of our granddaughters, Heather, who is an optometrist, to look into it.

Mrs Ward's granddaughter discovered that the new procedure had just started to be offered in the UK so the great-grandmother contacted a doctor to discover if she would be eligible.

She added: 'Before the surgery I struggled to see people properly, even people that I knew well.

'I never knew who was speaking and I would have to say who are you - which was awful when it was someone I knew well. This has given me my social life back.'

Mrs Ward is only the seventh person in the UK to have the lens fitted. Image shows a cross section of the lens in place in the eye

Mrs Ward said: 'I am still in love with my husband and it has been awful not seeing him properly for the past 15 years'

Mr and Mrs Ward met while they were both stationed in North Africa during the Second World War and they married in 1946.

They celebrated their 68th wedding anniversary last weekend.

Macular degeneration is a painless eye condition that generally leads to gradual loss of central vision, but can sometimes cause a rapid reduction in vision.

It causes the central vision to become increasingly blurred and causes difficulty reading and recognising faces.

Mrs Ward had the procedure under local anaesthetic and says it is wonderful to be able to see her great-grandchildren properly. All of them were born after she lost her sight so she has never seen them clearly

It usually affects both eyes but the speed at which it progresses can vary from eye to eye.

It does not affect the peripheral vision so it will not cause complete blindness.

It occurs when the macular - the part of the eye responsible for central vision - becomes less effective and it is most common in older people.

Oscar-winning actress Dame Judi Dench, aged, 79, is among those who suffer from it and she has said it has left her unable to read scripts and struggling to watch films.

For more information about the procedure, call the CentraSight Patient Helpline on 0800 002 9998.

@highlight

Margaret Ward, 90, lost her sight in 1999 after getting macular degeneration

@highlight

She was unable to read, cook or to recognise even familiar faces

@highlight

Has become one of seven people in the UK to have pioneering surgery

@highlight

She had a pea-sized telescopic lens implanted into her right eye

@highlight

She says she can now see her husband, Charles, 95, clearly again