By
Daily Mail Reporter

PUBLISHED:
  
  
      00:57 EST, 6 December 2013
    
  

 | 
  UPDATED:
  
  
      08:55 EST, 6 December 2013

Researchers in Ohio have found a revolutionary way to let amputees feel what they're touching with prosthetic hands.

The team from Cleveland Veterans Affairs Medical Center and Case Western Reserve University has created a means of letting users feel more sensations, better, and with more sustained results than ever before.

While others have hade lukewarm success at connecting nerves with electrodes, this team's special technique has created remarkable results.

Scroll down for video...

Common problem: Test subject Igor Spetic demonstrates his inability to pluck the stem from a cherry without crushing it when the sensors in his hand are turned off

Messy issue: Without sensation, Spetic is unable to determine the softness or size of an object

The breakthrough can be mostly attributed to a tiny, 7 millimeter connection called a cuff electrode.

Placed in a user's body and connected to nerve bundles through the arm stump, the electrodes convey sensations from sensors on a prosthetic hand or fingers.

The sense of touch is felt from 20 different spots on the hand, another feat on the part of its developers.

What's more, the results have been found to last past 18 months whereas other such trials have ended with degraded sensation in the nerves.

'It’s real exciting to see what they 
are doing, and I hope it can help other people,' Spetic says. “I know 
that science takes a long time. If I don’t get something to take home, 
but the next person does, it’s all to the better.”

Neuroscience
 professor at Northwester University Lee Miller told MIT Technology 
Review just how exciting these results really are.

Revolutionary: With the sensation on, Spetic is able to actually feel the cherry and control his grip accordingly

New technique: The remarkable results are thanks to a new technique of connecting electrodes to bundles of nerves in the arm

'This is the greatest number of distinct touch sensations generated by peripheral nerve stimulation that I know of, and the 18-month-long stability is also unsurpassed,' Miller said.

Two people have thus far been fitted with the device, including Madison, Ohio man Igor Spetic.

Spetic is the subject of videos made by the researchers that first show him attempting to take the stem from a cherry while the sensation is turned off in his hand.

As would often be the case for many prostetic hand users, he's unsable to complete the take without crushing the cherry.

With the hand turned on, it's a different story. Spetic is able to remove the stem, leaving the cherry intact.

'It’s real exciting to see what they are doing, and I hope it can help other people,' Spetic said. 'I know that science takes a long time. If I don’t get something to take home, but the next person does, it’s all to the better.'

@highlight

Researchers at the Cleveland Veterans Affairs Medical Center and Case Western Reserve University have created a new way to connect prosthetic hands to human nerves