By
Kieran Corcoran

An 'audacious' gang dressed in burkas and posed as wealthy Muslim women to steal designer watches worth more than £1.4million from Selfridges, a court heard today.

Customers and staff in the world famous department store on London’s Oxford Street were left 'terrified' by the smash and grab raid, the court was told.

Some of the all-male gang, armed with axes and other equipment, also allegedly wore burkas to fleece a jewellery store in Windsor two months earlier.

Scroll down for video

Smash and grab: An eyewitness films one of the burka-clad robbers fleeing Selfridges

Caught on camera: This cameraphone video shows one of the robbers running for the exit

Escape: The burka-clad raider clutches what appears to be an axe while fleeing the scene

Four men are standing trial over the attempted robbery at Kingston Crown Court, a year after four other men were convicted for their part in the event.

Ramela Gordon, 18, Ritchie Graham, 24, Vincent Bellamy, 37 and Leon Wright, 
25, all from North Londoner, deny conspiracy to rob.

Gordon and Graham are also accused the £170,000 of watch haul in Windsor.

Roger Smart, prosecuting, told Kingston Crown Court that the gang first carried out a 'well-planned robbery' at Robert Gatward jewellers in King Edward Court, Windsor.

Mr Smart said: 'The robbers, all of whom were male, wore burkas in order to disguise their identities and the equipment that they had taken with them in order to carry out the robbery.

'They smashed their way into display cabinets whilst staff and customers were inside the premises and bystanders looked on in fear as they carried out their well-executed plan.

Response: The court heard how getaway drivers crashed and were apprehended

'They stole a total of 19 Rolex watches with a value of between £3,000 and £31,650 per item.

'The robbers quickly made off, running through the streets of Windsor, one of them with an axe raised above his head, warding off anyone who may have sought to impede their escape, to a nearby parked getaway car that took them and their property back towards London from where they had first come.'

As well as stealing £175,000 of watches, the thieves caused £41,361 worth of damage to the jewellers, meaning it suffered £216,361 worth of loss, the court heard.

Mr Smart said that less than two months later the same gang, along with some new faces, 'doubtless buoyed by the success of the robbery in Windsor' targeted Selfridges on Oxford Street in central London on June 6th last year.

He said: 'The plot to rob was audacious, well-planned and carried out with the same degree of professional execution as the previous robbery.

'They made their way inside the store and smashed at showcases containing high value watches of a variety of makes.

'Members of the public and staff were terrified by their actions. The robber used the burka to disguise their identities and hide their equipment.

Destruction: A man looks at the damage left after an armed robbery at Selfridges on Oxford Street, London

Evidence: A forensic officer photographs the wreckage in Selfridges left after an armed robbery

Broken glass: The scene of a smash and grab robbery in Selfridges on Oxford Street in central London

Guns: Police officers at the scene of a smash and grab robbery in Selfridges on Oxford Street in central London

'Such was their behaviour and appearance that it crossed the minds of many of those who were forced to witness the robbery that the men dressed in burkas were using them in order to hide their identities while perpetrating a terrorist atrocity.'

The gang escaped using two motorbikes, a motor scooter and a BMW car, all of which were stolen.Sam Curtin, who was still wearing his burka, and Connor Groake, a getaway driver, were arrested when their moped crashed at the corner of Goodge Street junction with Charlotte Street and they were seized by passers by, the court heard.

Mr Smart said: 'It was the quick thinking and bravery of members of the public that lead to both of them being detained, some of the watches being recovered and aided the police investigation.'

The thieves stole 143 watches worth £1,496,280 and damaged others worth £1.1million.

Onlookers: A crowd at the scene of a smash and grab robbery in Selfridges on Oxford Street in central London

Mr Smart added: 'The Windsor offence was a carefully planned, sophisticated and targeted robbery.

'The robbers carried out in advance reconnaissance of intended started on April 5 2013, and an aborted attempt on April 11, before the actual robbery on April 12.

'The sophisticated and targeted planning, the use of new tools and the choice of the disguises at the Selfridges robbery show the same preparation as before.'

Mr Smart then showed the court the telephone cell site analysis of calls made by Murrain and Gordon during the reconnaissance mission on April 5th, together with data generated by automatic number plate recognition devices.

Police on scene: Officers are seen in the iconic London department store

Targeted: The gang of armed robbers targeted Selfridges Department Store on Oxford Street in June 2013

This showed both men had made a journey to Windsor from north London and back at the same time, while remaining in constant contact.

He said: 'It is more than coincidence the telephones moved with the vehicles from the north London area to Windsor and the cells providing best coverage round Richard Gatward were used.'

A ninth man, Andre Murrain, is also accused of involvement in both crimes, and will appear in court at a later date.

The trial continues.

Sorry we are not currently accepting comments on this article.

@highlight

Store on Oxford Street, central London was robbed last June, court hears

@highlight

Four men accused of being in gang which tried to steal haul of watches

@highlight

Kingston Crown Court hears they posed in burkas to steal designer gear

@highlight

Strategy had allegedly worked for them before robbing a shop in Windsor

@highlight

Four different men have previous been jailed for their parts in the raids

@highlight

Defendants in this case have all deny conspiracy to rob