By
Freya Noble

Prime Minister Tony Abbott has started a war with renewable energy companies after he blamed them for the increase in power prices

Tony Abbott has hit out at the green energy sector claiming the renewable energy target (RET) is the cause of rising energy prices in Australia.

The Prime Minister said the country is well on its way to being 'the unaffordable energy capital of the world' and that's the reason for the government's review of the RET, report The Financial Review.

'We should be the affordable energy capital of the world, not the unaffordable energy capital of the world and that’s why the carbon tax must go and that’s why we’re reviewing the RET,' he told the publication.

Clean energy companies have responded to these claims saying Mr Abbott completely exaggerated the impact that the target would have, and in the long run the nation would be better off financially and environmentally from the scheme.

The RET currently states that by 2020, 20 percent of energy should come from renewable sources, however this could be subject to change under the government's upcoming review.

In the Senate next week the government will try to abolish the carbon tax, but opposition leader Bill Shorten has vowed to continue the crusade for action against climate change.

Clive Palmer is set to block the government from lowering or abandoning the RET until after the election in 2016.

Infigen, Pacific Hydro, Senvion and the Clean Energy Council are all among the companies who have disagreed with the Prime Minister's comments, and a spokesperson for Senvion said if the RET is kept in place the price of power bills will drop off by 2020.

The government is currently looking to review the renewable energy target which is set to see 20 percent of energy come from green sources by 2020

Clean Energy Council director Russell March agreed, claiming the only other alternative to the target is a switch to gas-fired power, but the price of that resource is on the up.

The consensus in the renewable energy industry is that power prices will drop as more forms of renewable energy are being utilised, with some companies citing the decrease in power bills around the $50 mark.

This week saw the Crawford Australian Leadership Forum take place in Canberra, and economists from around the world including Nobel Prize recipient Joseph Stiglitz and former Reserve Bank of Australia board member Warwick McKibbin were among the experts calling for Australia to have a price on carbon, according to AFR.

Economists have warned against scrapping the carbon tax saying a price on carbon would be taking a step forward for Australia

Professor Stiglitz described putting a price on carbon as a 'no-brainer' and said it is more practical than taxing labour or capital, plus it would set Australia up for the future.

By pricing carbon now Australia would be taking a step forward to combating climate change he said, and the world would soon follow.

Aluminium refineries are also a big player in the RET debate, which are currently said to be 90 percent exempt from paying for renewable energy.

The government is expected to make a move from the backbench to completely clear the refineries from paying for any form of green energy.

According to Origin Energy:

'The RET is a mandatory scheme and energy retailers (on behalf of their customers) must source a set proportion of their electricity from renewables. Retailers purchase a renewable energy certificate for each megawatt hour of electricity generated by government-accredited renewable electricity sources.'

Despite aiming to deliver 20 percent renewable energy, if continued the RET is forecast to deliver a higher rate, up to 27 percent.

@highlight

The Prime Minister has blamed the renewable energy target (RET) for increasing power prices

@highlight

Clean energy companies hit back saying Abbott exaggerated the impact

@highlight

Economists say Australia needs a price on carbon

@highlight

Clive Palmer will block proposed changes to the RET until 2016 election