By
Richard Spillett

An England fan who was caught on TV apparently flirting with a Brazilian woman at the World Cup has denied he was 'chatting her up'.

Carl Wenz was at England's opening match with Italy on Saturday when TV cameras filmed him holding a mobile phone as he spoke to a female Brazilian fan.

Mr Wenz, who has four children with his long-term partner Nicola Moore and lives in Harlow, Essex, was seen wearing an England strip as he chatted to a woman in a blue and yellow Brazil t-shirt.

Scroll down for video

Rumbled: Carl Wenz was seen by millions of TV viewers chatting to a Brazilian woman on Saturday

The images were shared more than 2,000 times on Twitter, with the tagline accompanying the photo reading 'LAD: An England fan asks for this Brazilian fan's phone number mid-match'.

Twitter users joked that his 'other half' would go mad after seeing him cosying up to 'the enemy', with Tony Scott writing: 'Hope his girlfriend/wife's not watching!'

A website user called the Spin Doctor added: 'I wonder if his wife back home will mind?' and Ronnie MacKay wrote: 'What goes on in Brasil, stays in Brasil. Play by the rules boys!'

But butcher and avid England fan Mr Wenz has told his local newspaper that he is 
always keen to talk to locals in the countries he visits while following
 the team.

He told the Harlow Star: 'The girl in the photo asked if she could have a picture taken 
with me, of which I said yes, her brother took the photo and I am seen 
looking at it on her phone.'

Jonathan Greig, a friend of Mr Wenz's, said he spoke to him after the game and he insisted he was simply showing the Brazilian fan a photo on his mobile phone.

Mr Greig said: 'He's an old fashioned person and this would only happen to someone like him. He's in a long-term relationship and would consider the interest generated by the picture hilarious.'

Friend Jonathan Greig rushed to Mr Wenz's aid after the picture of him was sent around the internet

Mr Wenz was among the thousands of fans watching England's game with Italy in Manaus on Saturday

Today, the blinds were down at Mr Wenz's Ye Olde Churchgate Butchery, which has been closed since he went to the World Cup.

A friend, who asked not to be named, said: 'He's a massive football fan and follows England all across the world.

'I think he's even shut up the shop front while he is away. I know Carl as a proper family man so I don't think there's anything dodgy about the picture.

'He wouldn't save up to travel halfway across the world just to get a Brazilian girl's number. I bet he was showing her pictures of his kids.'

Neighbour Sally Mackown, 49, added: 'Carl just seems to work 24 hours a day for his kids.'I think he's got four girls and is a very devoted father. I'm sure there's an innocent explanation.'

Mr Wenz's long-term partner, Ms Moore, refused to comment when approached at her home in Chelmsford, Essex.

@highlight

Carl Wenz filmed chatting to woman during England game on Saturday

@highlight

The images were beamed around the world and were picked up on Twitter

@highlight

Fans joked that they hoped his long-term partner was not watching

@highlight

Friend comes to his aid, insisting Mr Wenz was not swapping numbers

@highlight

Wenz says he was just showing the woman a photo they had taken together

@highlight

His long-term partner, Nicola Moore, refuses to comment on footage