By 
Daily Mail Reporter

PUBLISHED:

11:13 EST, 4 April 2013


| 

UPDATED:

06:19 EST, 5 April 2013

In a land where most young girls continue to be denied an education, it is a truly heartwarming sight.

Rows of eager students, their textbooks open, eyes fixed to the front, settling down for another busy school day.

But these young learners, almost all girls, have a rather unusual benefactor to thank, Hollywood superstar Angelina Jolie.

Ready to learn: Children attend class at the Afghan school that was funded by Hollywood actress Angelina Jolie

Charity: Angelina Jolie in Afghanistan last year where she funded the new primary school for girls

Ms Jolie, a goodwill ambassador for the United Nations High Commissioner for Refugees, not only  funded the project but now plans to set up more with the proceeds of her jewellery line.

The
actress, 37, has has been spending her own money to 
promote female education in the poverty-stricken war zone.

And when her new jewellery collection, 
entitled 'Style of Jolie', goes on sale this week, all the profits will 
go towards the needy in Afghanistan.

While massive progress has been made since the fall of the Taliban, according to one charity still only 40 per cent of Afghan girls attend elementary school.

Eager to learn: A young student asks a question during a class at the new school

Angelina Jolie funded the school with her own money and now plans to open more using the profits generated by her new jewellery line

Pay attention class! A rather strict-looking teacher makes sure he gets his message across

Most of the students are girls who are slowly beginning to enjoy the right to education after the Taliban government collapsed

A young Afghan girl attends a class at the school funded by Angelina Jolie

Many have to sneak out of the their homes to attend class and in most area there are simply aren't any schools for girls at all.

In extreme cases schools for girls have been burned down with the teachers threatened or even killed.

Ms Jolie opened the primary school for girls in an area outside Kabul with a large refugee population, and it boasts a plaque honouring the star's 'generous contribution'.

It is the second school in Afghanistan funded by Ms Jolie, after one in the east of the country was set up in 2010.

The actress plans to foot the bill for further school by selling the 'Style of Jolie' line, designed with the help of top jeweller Robert Procop, who made the engagement ring Ms Jolie was given by Brad Pitt last year.

Haven: An Afghan teacher stands in front of the bright blue school building built with the proceeds of Hollywood star Angelina Jolie's acting career

Concentrate: An Afghan teacher teaches during a class School that was funded by Angelina Jolie in Kabul, Afghanistan

Break-time: Students pull water from a pump set up in the School grounds

While there are a few boys in the school the vast majority, some 400 students, are girls

Plaque: This stone monument honours Angelina Jolie's 'generous contribution' to the school's construction

'Beyond enjoying the artistic satisfaction of designing these jewels, we are inspired by knowing our work is also serving the mutual goal of providing for children in need,' she told E!.

Mr Procop's website said the 'first funds from our collaboration together have been dedicated to the Education Partnership for Children in Conflict to build a school in Afghanistan.'

The newly expanded collection includes versions of the black and gold necklace that the actress wore to the premiere of her 2010 movie Salt, a pear-shaped citrine and gold necklace, and rose gold and emerald tablet-shaped rings, earrings and bracelets.

The jewellery will go on retail sale for the first time on Thursday through Tivol, a store in Kansas City.

Roughly 40 per cent of Afghan girls are still being denied an education

It is the second school in Afghanistan funded by Angelina Jolie, after one in the east of the country was set up in 2010

Mr Procop told E! that it was 'an honour to
have the opportunity to be part of creating this line with Angie, as we
both believe every child has right to an education.'

Ms
Jolie is not the first celebrity to open schools in faraway places. 
Oprah Winfrey and Madonna have funded the building of schools in South 
Africa and Malawi, although both ran into trouble.

Madonna's
project provoked controversy over its high costs and alleged 
mismanagement, while a staff member at Ms Winfrey's school was arrested 
on charges of assault and abuse of students.

Philanthropy: This emerald necklace is part of the 'Style of Jolie' collection which will fund more schools

Beneficial: The pieces were designed by Angelina Jolie and Robert Procop, one of the world's top jewellers

@highlight

Ms Jolie is an ambassador for the UN High Commissioner for Refugees

@highlight

She funded the school near the capital Kabul and plans to set up more

@highlight

Tragically still only 40 per cent of Afghan girls get to attend school

@highlight

'Style of Jolie' jewellery range will help to fund female education in country