By
Sean Poulter

The makers of Cow and Gate baby milk claimed their product provides calcium for 'strong bones' and iron for 'brain development'

A TV advert for Cow & Gate baby milk has been banned for exaggerating the product’s health benefits.

The commercial said that the powdered formula provides calcium for ‘strong bones’ and iron for ‘brain development’.

But pro-breast feeding campaigners said it suggested an added advantage, when nutrients added to the product only play a part in the ‘normal’ development of the bones and brain.

A ruling published by the Advertising Standards Authority today says  manufacturer Danone misrepresented the health effects.

The
 group Baby Milk Action, which brought the complaint, insists breast 
milk followed by a mixed diet is better for developing babies and said 
Danone is ‘ripping parents off’.

Its
 campaigns chief, Mike Brady, said: ‘Advertisements such as Danone’s 
suggest that follow-on milks provide health benefits, but they are 
unnecessary products and Danone is simply ripping parents off, using 
false claims to make them think they need these milks.

‘Yes,
 calcium is needed for normal growth and bone development in children 
and iron contributes to normal cognitive development, but these are 
provided by a normal diet and Danone’s products offer nothing special 
other than a way for the company to fill its pockets.

‘The cost of these multi-million pound advertising campaigns goes onto the price of the milks making them even more expensive.’

He
 complained that the ASA system for policing commercials does not work 
in the consumer interest. The commercial has already appeared many times
 and there is no sanction against Danone, other than the publicity 
generated by the ASA decision.

Mr
 Brady said: ‘We have won repeated cases proving that claims made for 
baby formula do not stand up to scrutiny, but the firms continue using 
them regardless because the ASA is a toothless body requiring no 
corrections and levying no fines.

‘Many
 of these practices also break the law in our view, but Trading 
Standards and the Department of Health are failing to hold companies to 
account. Companies should be prosecuted and fined for repeated 
violations.’

Scroll down for video

The group Baby Milk Action, which brought the complaint, insists breast milk followed by a mixed diet is better for developing babies

Danone said it had simply re-phrased a number of health claims that have been approved for use by the European Food Safety Authority(EFSA).

EFSA has approved the phrase - ‘calcium is needed for normal growth and development of bone in children’. Danone said its phrase - ‘provides calcium for strong bones’ - means the same thing.

Similarly, EFSA has approved the sentence -  ‘Iron contributes to normal cognitive development of children’. Danone argued its phrase - ‘iron for brain development’ - includes better, more consumer friendly, language.

However, the ASA rejected the firm’s explanation and said the wording in the commercial implied a greater health effect than is allowed. Consequently, it said it should not be shown again in its current format.

@highlight

Ad for Cow & Gate baby milk criticised by pro-breast feeding campaigners

@highlight

Anger over claim it provides calcium for 'strong bones' and iron for 'brain development'