By 
Daily Mail Reporter

PUBLISHED:

19:58 EST, 9 July 2013


| 

UPDATED:

19:58 EST, 9 July 2013

Low level exposure to traffic fumes is enough to raise the risk of lung cancer, scientists reported yesterday.

Air pollution may even have to be added to smoking as a recognised cause of the disease, it is claimed.

Lung cancer is the biggest cancer killer in the UK, claiming almost 35,000 lives in 2010. In the same year, 42,000 Britons were diagnosed with the disease.

Danger: New research suggests even low exposure to car fumes could increase the risk of lung cancer

An estimated 86% of cases are believed to be a direct result of smoking. Other potential triggers include exposure to natural radioactive gas from the ground and toxic substances in the work place, such as asbestos.

The new research, reported in the journal The Lancet Oncology, analysed pooled information from 17 studies in nine European countries. In total, the data covered almost 313,000 individuals.

Air pollution levels were estimated at people’s home addresses and cancer diagnosis rates obtained from national and local registries.

Over an average 13 year follow-up period, 2,095 study participants developed lung cancer.

People’s chances of having the disease rose with greater exposure to small sooty particles generated by diesel exhausts which are known to lodge in the lungs.

Two size grades of particle were studied, tiny PM 2.5s and somewhat larger PM10s.

For every density increase in PM10s of 10 micrograms per cubic metre of air, the risk of lung cancer rose by 22%. For PM2.5s, every five microgram per metre cubed increase led to an 18% increase in risk.

Deadly: An estimated 86 per cent of lung cancer cases are thought to be caused by smoking

The trend was seen below the air quality limits set by the European Union of 40 micrograms per cubic metre for PM10s and 25 micrograms for PM2.5s, according to the study authors.

Lead scientists Dr Ole Raaschou-Nielsen, from the Danish Cancer Society Research Centre, said: 'We found no threshold below which there was no risk. The results showed a picture that ‘the more the worse, the less the better’.'

Traffic pollution was mostly linked to adenocarcinoma lung cancer, the only form of the disease to affect significant numbers of non-smokers.

Commenting in the journal, Japanese expert Dr Takashi Yorifuji from Okayama University wrote: 'At this stage, we might have to add air pollution, even at current concentrations, to the list of causes of lung cancer and recognise that air pollution has large effects on public health.'

A second study published in a sister journal, The Lancet, links air pollution with a higher chance of heart failure patients being hospitalised.

Researchers combined data from 35 studies and estimated that a modest reduction in fine particulate pollution levels could prevent 8,000 heart failure hospitalisations each year in the US.

Dr Anoop Shah, from the University of Edinburgh, who co-led the British Heart Foundation-funded study said: 'We already know that air pollution is associated with an increased risk of having a heart attack. Our study suggests that air pollution also affects patients with heart failure.'

Heart failure occurs when the heart is too weak to pump blood efficiently round the body. It affects more than 750,000 people in the UK.

@highlight

Even low level exposure can increase risk of illness

@highlight

Lung cancer is the biggest cancer killer in the UK

@highlight

Sooty particles from traffic fumes known to lodge in lungs