CVS and Rite Aid have joined a long list of the world's largest retailers who will not be accepting Apple Pay.

At its launch, Apple boasted there are 200,000 retail stores now ready and willing to let you give them your cash using just a flick of your iPhone and a tap of your finger to prove your identity.

But retail giants Walmart, Target, Kohl's. Dunkin' Donuts are not among them. These retail giants and dozens more are part of a group developing their own mobile payment scheme.

Scroll down for video 

Dead on arrival? CVS stores, along with rival Rite Aid, have joined a long list of retailers that simply won't be accepting Apple Pay

The Merchant Customer Exchange, a consortium of retailers creating their own mobile payment app, includes dozens of companies, many of which are among America's largest retailers:

Best Buy, Lowe's, Kmart, Kohl's, Dunkin' Donuts, Gap, Sam's, Walmart, Target, Wendy's, 7-Eleven, Exxon, Publix, Shell, Sheetz, Shop-Rite, Conoco, Wawa, Dick's, Olive Garden and more.

It comes after the system hit several glitches following its launch last week.

Some Apple Pay users in the US have been double-charged for purchases.

The Californian tech giant has admitted there is a problem with its mobile payment system, but says it only affected ‘a very small number’ of Apple Pay users with Bank of America accounts, and is working to refund all faulty transactions.

CVS and Rite Aid initially accepted Apple Pay, but quickly turned heel and no longer take the payment system. 

The chains disabled the system in their stores over the weekend, reports the New York Times.

The retailer group to which both companies belong, the Merchant Customer Exchange (MCX), is creating CurrentC--a system similar to Apple Pay that will be owned by a consortium of retailers rather than a third party, i.e. Apple.

Like Apple Pay, CurrentC allows consumers to quickly and securely pay for goods and services with the aid of an app on their cell phones.

Obstacles: Apple Pay lets users pay with their phones at some 200,000 retail stores. Consumers may use whatever credit cards they'd like. While the system appears seamless, retailer opposition is a serious hurdle for the Silicon Valley giant

Apple Pay is compatible with the iPhone 6, iPhone 6 Plus and the Apple Watch.

The mobile system works by holding the phone up to a card reader and pressing a finger on the TouchID button.

This confirms the person's identity, and the payment is simply made as if the user had presented and signed their card.

All details are encrypted and the system stores payment information securely.

If an iPhone is lost, users can suspend all payments via the Find my iPhone service.

CurrentC, however, appears to work in an opposite way from Apple Pay. 

While the former uses what's called an NFC chip, which is scanned by the retail kiosk, the MCX system has the phone scan a code generated by the kiosk.

Not only is CurrentC hoping to leave Apple out in the cold, it's trying to circumvent credit cards completely.

While Apple Pay allows users to store whatever credit cards they'd like in their phones, CurrentC taps directly into the user's bank account.

Results, though, are the same: a seamless and safe purchasing process.

CurrentC is set to hit smartphones in 2015.

Apple said it had found most retailers were enthusiastic.

'The feedback we are getting from customers and retailers about Apple Pay is overwhelmingly positive and enthusiastic,' it told MailOnline.

'We are working to get as many merchants as possible to support this convenient, secure and private payment option for consumers. 

'Many retailers have already seen the benefits and are delighting their customers at over 220,000 locations. 

Apple Pay (screenshots pictured above) stores Visa, MasterCard and American Express credit card information and works with the iPhone 6's touch ID fingerprint recognition system so users can touch their phone on a contactless reader to pay for goods. Stores such as McDonalds, Macy's and Walgreensare involved

And that may be Apple's one advantage, it's pay system is already here.

Apple Pay made its debut last week. 

Now you can flash your new iPhone in the checkout line to pay for food, clothing and other goods.

There's no need to pull out your credit card.

But don't leave your wallet or purse behind quite yet: Despite a few dozen retail chains pledging support for Apple Pay, so-called contactless payments are still new. 

Smaller merchants, in particular, aren't likely to have the necessary equipment right away. 

All told, there are more than 200,000 payment terminals that should accept Apple Pay in the U.S. Apple has announced about two dozen leading retail chains accepting Apple Pay at launch, and others are planning to do so by the end of the year.

Apple said it has worked with several retailers to make sure most of their stores, if not all of them, were ready at Monday's launch: Aeropostale, American Eagle Outfitters, Babies R Us, BJ's Wholesale Club, Bloomingdale's, Champs Sports, Chevron and Texaco retail stores including ExtraMile, Disney Store, Duane Reade, Footaction, Foot Locker, House of Hoops by Foot Locker, Kids Foot Locker, Lady Foot Locker, Macy's, McDonald's, Nike, Office Depot, Panera Bread, Petco, RadioShack, RUN by Foot Locker, SIX:02, Sports Authority, Subway, Toys R Us, Unleashed by Petco, Walgreens, Wegmans and Whole Foods Market.

Bright side: Dozens of retailers will be accepting Apple Pay, the biggest of which include Subway, Whole Fooods, Walgreens, McDonald's and Macy's

Apple also said that the following merchants plan to add support by the end of the year: Anthropologie, Free People, Sephora, Staples, Urban Outfitters and Walt Disney Parks and Resorts.

For online payments, Apple said the following merchants have apps ready for Apple Pay: Chairish, Fancy, Groupon, HotelTonight, Houzz, Instacart, Lyft, OpenTable, Panera Bread, Spring, Staples, Target and Uber.

Others expected by year's end include: Airbnb, Disney Store, Eventbrite, JackThreads, Levi's Stadium by VenueNext, Sephora, Starbucks, StubHub, Ticketmaster and Tickets.com.

Of course, Apple's retail stores and the Apple Store app will also take Apple Pay.

Apple Pay is designed to protect the user's personal information. It doesn't collect any transaction information that can be tied back to a user and payment transactions are between the user, the merchant and the user's bank.

Apple doesn't collect its users' purchase history, so when they are shopping in a store or restaurant it doesn't know what they bought, where they bought it or how much they paid for it.

Card numbers are not stored on the device, instead, a unique Device Account Number is created, encrypted and stored in the Secure Element of the device.

The Device Account Number in the Secure Element is walled off from iOS and not backed up to iCloud.

Users can make purchases in stores and within apps, with credit cards issued by many US banks , which make up 83 percent of the credit card purchase volume in the country.

The mobile system works by holding phone up to a generic card reader and pressing a finger on the TouchID button. The NFC chip is fitted across the top of the phone.

All details are encrypted and the system stores payment information securely. It uses the Passbook app and cards that are already on file with iTunes can be saved to it.

Users can also take a picture of their own credit card and add it to the account. 

This is verified by the card's bank before being accepted.

If an iPhone is lost, users can suspend all payments via the Find my iPhone service. This won't cancel the cards, either, because the card details themselves are not stored on that device.

Apple said it is 'working hard' on bringing it to the UK, although a date has yet to be announced

 

@highlight

Apple's mobile payment system is not being accepted at the drug store chains

@highlight

Neither are Wal-Mart, Kmart, Lowe's, Gap, Target or dozens of other giants

@highlight

CVS and Rite Aid are part of the Merchant Customer Exchange, a group developing its own payment system using cell phones 

@highlight

Comes after some customers were double charged for payments using the new system 