It may sound like a plot straight out of a science fiction novel, but a U.S. mission to blow up the moon with a nuke was very real in the 1950s.

At the height of the space race, the U.S. considered detonating an atom bomb on the moon as a display of America's Cold War muscle.

The secret project, innocuously titled 'A Study of Lunar Research Flights' and nicknamed 'Project A119,' was never carried out.

Plot: The U.S. was planning to launch an atomic bomb, like Fat Man, pictured above, that would be launched into space in a scrapped plan to blow up the moon

Brains of the operation: Astronomer Carl Sagan, 
left, was involved in the planning of the mission and physicist Leonard
 Reiffel, right, was the man in charge

However, its planning included calculations 
by astronomer Carl Sagan, then a young graduate student, of the behavior
 of dust and gas generated by the blast.

Viewing the nuclear flash from Earth might have intimidated the Soviet Union and boosted U.S. confidence after the launch of Sputnik, physicist Leonard Reiffel told the AP in a 2000 interview.

Reiffel, now 85, directed the inquiry at the former Armour Research Foundation, now part of the Illinois Institute of Technology. He later served as a deputy director at NASA.

Would you miss it? American scientists were looking to blow up the moon to get an edge of the Soviet Union in the space race

Sagan, who later became renowned for popularizing science on television, died in 1996.

The author of one of Sagan's biographies suggested that he may have committed a security breach in 1959 after revealing the classified project in an academic fellowship application. Reiffel concurred.

Under the scenario, a missile 
carrying a small nuclear device was to be launched from an undisclosed 
location and travel 238,000 miles to the moon, where it would be 
detonated upon impact.

The planners decided it would have to be an atom bomb because a hydrogen bomb would have been too heavy for the missile.

Reiffel
 said the nation’s young space program probably could have carried out 
the mission by 1959, when the Air Force deployed inter-continental 
ballistic missiles.

Military officials apparently abandoned the idea because of the danger to people on Earth in case the mission failed.

The scientists also registered concerns about contaminating the moon with radioactive material, Reiffel said. 

When contacted by the AP, the U.S. Air Force declined to comment on the project.

@highlight

Scientists were hoping for giant flash on the moon that would intimidate the Soviet Union

@highlight

Aim of mission was to launch the nuke by 1959

@highlight

Plan was later scrapped due to possible danger to people on Earth