By 
Rob Waugh

UPDATED:

03:38 EST, 25 June 2012

A helicopter powered by a student pedalling on a lightweight bicycle-style frame has stayed airborne for 50 seconds - smashing the team's previous record of just 11 seconds.

The record but the team posted a video online showing the craft wobbling into the air under pedal power, piloted by  University
of Maryland engineering student Kyle Gluesenkamp.

The students hope to win a $250,000 prize for human-powered flight - but the helicopter, Gamera II, has to stay in the air for a further 10 seconds to meet the standards for the American Helicopter Society Prize.

Scroll down for video

The students hope to win a $250,000 prize for human-powered flight - but the helicopter, Gamera II, has to stay in the air for a further 10 seconds to meet the standards for the American Helicopter Society Prize

The flight, by a craft built by University of Maryland engineering students, hasn't yet been validated, but the team posted a video online showing the craft wobbling into the air under pedal power, piloted by student Kyle Gluesenkamp

‘Over the last few days we have witnessed top Clark School student engineers flying an amazing craft they designed and built, resulting in an unofficial new world record of 50 seconds,’ stated Clark School Dean Darryll Pines.

‘If you want to know where to find the future of engineering and great new technologies that will make our lives better, this is it.’

With its 50-second flight, Gamera II has come closer to the flight duration requirement than any other craft.

The craft's predecessor, Gamera I, first took off in 2011.

Liftoff: Judy Wexler, 24, pedalled furiously and managed to get the craft 'Gamera' up in the air

First: Maryland students believe they achieved the first human-powered helicopter flight with a female pilot

Gamera - named after a huge 
flying turtle from Japanese films - was designed with lightweight 
materials and weighed only 140lbs without the pilot.

We did it: Take-off was scheduled for Wednesday morning, but they eventually succeeded on Thursday

‘It was beautiful,’ Brandon Bush, 29, a doctoral student and project manager said. ‘It jumped up, and it stayed there,’ he told the Washington Post.

Gamera is a huge 60ft long and each 
rotor is 42ft in diameter. The model is made from carbon fibre, foam and
balsa wood, weighs just 140lbs.

A
flight tape will have to be verified, but a National Aeronautical 
Association judge says it appears the students have set a record.

However
they fell short of winning the $250,000 Sikorsky Award, which is run by
the American Helicopter Society and was issued in 1980.

The prize is for the first engineers who
can build a human-powered helicopter reaching an altitude of at least 
three meters and hovering for at least one minute.

Third time: The students' attempt was the third known time a human-powered craft has left the ground

Hard task: It is hard to achieve flight with a human-powered helicopter because they do not have a fixed wing

The students’ attempt was among the first times a human-powered craft has left the ground, but nobody has yet won the prize.

A Japanese team of engineers have come closest, flying their helicopter in 1994 for 19.46 seconds at a height of 8in.

It is difficult to achieve flight with a human-powered helicopter because they do not have a fixed wing, like planes.

By pedalling, pilots can gather enough 
thrust to overcome the drag holding them back and lift forward into the 
air.

But because helicopters take off by going up, rather than forward, 
thrust alone is not enough.

Materials: The model is made from carbon fibre, foam and balsa wood and weighs just 140lbs without humans

Dr Antonio Filipponee, from the
UK's University of Manchester, said: 'With the fixed wing, you need 
essentially to provide the thrust to overcome the drag, whilst lift is 
generated by the wings.

'With
the helicopter you've got them both. If you want to go forward - you 
have to try lift yourself and the weight of the machine.

‘So
the amount of force you need to create is at least 15 times bigger than
the fixed wing aeroplane. So that's a huge challenge.'

@highlight

Pedal-powered craft smashes team's previous record of 11 seconds

@highlight

Record-breaking flight to be validated by National Aeronautic Association

@highlight

Longest flight by man-powered helicopter