By
Daily Mail Reporter

PUBLISHED:
  
  
      11:48 EST, 27 January 2014
    
  

 | 
  UPDATED:
  
  
      12:23 EST, 27 January 2014

While machines seem to be taking over our lives, one area they could never compete is in the creative art of poetry.

Or could they?

A developer has created a machine-learning algorithm capable of collaborating with one of the greatest writers of all time: William Shakespeare.

Machine-learning software, dubbed ‘Fluency’, analysed the style of Shakespeare's sonnets. Nathan Mathias was then able to write a new sonnet choosing words from the suggestions generated by the algorithm

When I in dreams behold thy fairest shade

Whose shade in dreams doth wake the sleeping morn

The daytime shadow of my love betray’d

Lends hideous night to dreaming’s faded form

Were painted frowns to gild mere false rebuff

Then shoulds’t my heart be patient as the sands

For nature’s smile is ornament enough

When thy gold lips unloose their drooping bands

As clouds occlude the globe’s enshrouded fears

Which can by no astron’my be assail’d

Thus, thyne appearance tears in atmospheres

No fond perceptions nor no gaze unveils

Disperse the clouds which banish light from thee

For no tears be true, until we truly see

According to Natasha Lomas at TechCrunch, SwiftKey’s machine-learning software, dubbed ‘Fluency’, was trained to learn the style of Shakespeare’s sonnets.

The group’s keyboard software is usually found in Android mobiles learning the users syntax and style to help them type faster.

Using word suggestions generated by the algorithm, Mr Matias was able to compose a new sonnet in the style of Shakespeare.

‘As might be expected from an artificial intelligence, the result is full of mixed metaphors,’ Mr Matias said, writing in SwiftKey’s blog.

‘But it was a fantastic start, and I couldn’t wait to try it on other famous writers.’

As well as using SwiftKey’s engine, Mr Matias also built a visual interface to help in poetry creation and named this project ‘Swift-Speare.’

Using this interface, he was able to co-create poetry in the style of various authors including William Gibson and John Denham.

Using the Fluency algorithm, Mr Matias was able to co-create poetry in the style of various authors including William Gibson and John Denham

‘Virginia Woolf rightly said that studied poets usually feel the presence of other writers’ words,’ said Mr Matias.

‘With Fluency, I sometimes feel as if I have a backseat driver, one who never stops giving very specific suggestions.’

Mr Matias doesn’t see anything wrong with letting machines doing the hard work in composing poetry. He says a good arrangement of words will always resonate with someone.

‘I think I’ll see a successful automated poet in my lifetime,’ Mr Matias told TechCrunch.

‘It won’t be easy: a poet is more than someone who makes poetry. Yet that doesn’t rule out algorithms,’ he said.

 

@highlight

Machine-learning software, dubbed ‘Fluency’, analysed the bard's style

@highlight

Same software is used in Android phones to predict a user's typing style

@highlight

Nathan Mathias was able to write a new sonnet choosing words from the suggestions generated by the algorithm