By
Ellie Zolfagharifard for MailOnline

Humans have used up the natural resources the world can supply in a year in less than eight months, campaigners have warned.

The world has now reached 'Earth Overshoot Day', the point in the year when humans have exhausted supplies. 

This includes natural resources such as land, trees and fish, and means today we have outstripped the planet's annual capacity to absorb waste products such as carbon dioxide.

Scroll down for video

Humans have used up the natural resources the world can supply in a year in less than eight months, campaigners have warned. For the rest of the year, the world is in ecological debt

For the rest of the year, the world is in ecological debt, with food stocks and forests being depleted, land degraded and carbon dioxide building up in the atmosphere.

The problem is worsening, with the planet sliding into 'ecological debt' earlier and earlier.

This means the day on which the world has used up all the natural resources available for the year has shifted from early October in 2000 to August 19 in 2014. 

In 1961, humans used only around three-quarters of the capacity Earth has for generating food, timber, fish and absorbing greenhouse gases, with most countries having more resources than they consumed. 

The world has now reached 'Earth Overshoot Day', the point in the year when humans have exhausted supplies. This includes natural resources such as land, trees and fish, and means today we have outstripped the planet's annual capacity to absorb waste products such as carbon dioxide

But now 86 per cent of the world's population lives in countries where the demands made on nature - the nation's 'ecological footprint' - outstrip what that country's resources can cope with.

The Global Footprint Network, which calculates Earth overshoot day, said it would currently take 1.5 Earths to produce the renewable natural resources needed to support human requirements.

Also known as Ecological Debt Day, this year, Earth Overshoot Day is on the 19th of August. 

In fewer than eight months, people use more natural resources than the planet is able to produce in a 12 month period.

For the remainder of 2014, we will be living on resources borrowed from future generations, scientists claim.  

It is calculated by dividing the world's biocapacity – the amount of natural resources generated by the planet that year – by   humanity's natural consumption of Earth's resources for 12 months.

It is then multiplied by 365, the number of days in a year. 

The concept for Earth Overshoot Day was created by Andrew Simms, climate economist at Global Witness, a London-based think tank. 

The network warned that governments that ignore resource limits in decision-making are putting long-term economic security at risk.

Mathis Wackernagel, president of the Global Footprint Network, said: 'Global overshoot is becoming a defining challenge of the 21st century. It is both an ecological and economic problem.

'Countries with resource deficits and low incomes are exceptionally vulnerable.

'Even high-income countries that have had a financial advantage to shield themselves from the most direct impacts of resource dependence need to realise that a long-term solution requires addressing such dependencies before they turn into a significant economic stress.'

Andrew Simms, climate economist at Global Witness, who came up with the concept of Earth overshoot day at UK think tank the New Economics Foundation, said last year that the government  seems intent on pushing people to break our environmental budget.

'The maths is simple - the UK consumes and produces waste at a rate three and a half times greater than we can sustain, and today humanity has already exhausted what the planet's ecosystems can provide in a year,' he said.

'We're in the red and gambling with ecological bankruptcy, as the fracking debate shows. If it chose to, the Government can always print more money, but it can't print more planet. Ecological overshoot should lead the political agenda.'

Earth Overshoot Day is calculated by dividing the world's biocapacity – the amount of natural resources generated by the planet that year – by humanity's natural consumption of Earth's resources for 12 months. It is then multiplied by 365. The day is getting earlier and earlier each year

 

 

@highlight

The world has now reached 'Earth Overshoot Day' claim campaigners

@highlight

This is point in the year when humans have exhausted natural supplies

@highlight

For the rest of the year, food stocks and forests are being depleted, land degraded and carbon dioxide will build up in the atmosphere, they claim

@highlight

Problem is worsening, with Earth in 'ecological debt' earlier each year