By 
Nadia Gilani

Last updated at 10:27 AM on 25th October 2011

Passenger planes of the future could be able to take people directly to their front door, a report suggests today.

Commercial jets could also be made that fly five times the speed of sound - meaning they could fly from London to New York in 
less than an hour.

Such aircraft could come into construction by the end of the century and would be part of efforts to place the UK at the forefront of future aerospace innovation,  a report by the Institution of Mechanical Engineers says.

The passenger drop-off idea would use what has been called 'a sort of Ark Royal for the skies'.

Scramjet planes like this one designed by NASA are among the speediest of aircraft

Looking towards 2075 and beyond, the 
report talked of advances that could be made in aircraft design.

It talks of passenger scramjet planes able to 
fly at around 4,000mph - five times the speed of sound - and commercial 
aircraft flying in a V-shaped formation that could to save power by 
making use of airflow generated by the plane in front, similar to the 
way migrating birds support one another in the air.

Scramjets - short for supersonic 
combustion ramjet - contain a 'air-breathing' jet engine, that allows 
them to combust fuel and decelerate the incoming air to produce speed 
and thrust.

The fastest current 'air-breathing aircraft' is a scramjet designed by NASA, which reached a velocity of Mach 9.8 - or 7,000mph.

So far, though, these hi-tech aircraft are unable to carry passengers. NASA's record-breaking X-43A aircraft looks more like a missile than a plane. Passenger jets would necessarily be a little hair-raising - and travel at a more 'moderate' speed of 4,000mph.

New York to Sydney21 hours down to 2.5 hours

London to New York7 hours down to 55 minutes

London to Singapore13 hours down to 1hr 40mins

NASA's hypersonic jets are designed to 
fly through the Earth’s atmosphere and slash flight times around the 
world to a few hours at most.

Travelling at such speed would reduce 
the flight time from New York to Sydney to around two-and-a-half hours, 
from the 21 hours it is now.

The report also discusses looking at 
ways to create an 'aircraft carrier' system in which a large aircraft 
carries individual units that can be released over a destination to 
float down to the designated area where a passenger needs to go - as if dropping passengers 'at their door'.

Other ideas are a 'flying wing' 
design, where the plane's main body, wings and engine blended together 
and a 'flying fuel station' so future planes do not have to take off 
with full tanks.

A graphic of the airflow over a Nasa scramjet

Scramjet engine 'combusts' fuel and decelerates the incoming air to produce speed and thrust

IME chief executive, Stephen Tetlow 
chief executive of UME said that even in the next 20 years, there were 
potential sales of 25,000 new aircraft set to be worth more than 
£2,000billion.

He said: 'Now is the time for industry and government to focus on sectors that can help lift the country's economy.

'The UK aerospace sector already 
employs over 100,000 people around the country and is worth over £29 
billion a year to our economy, but we need to take action now to ensure 
this sector can continue to thrive and grow.

'There is great potential for new UK 
aerospace technologies, but in order to compete with emerging nations, 
we need to set up a strategic vision for UK aerospace, establish a new 
dedicated aerospace research body and restore research and development 
funding to pre-recession levels.'

@highlight

Commercial aircraft of the future could drop passengers off at the door

@highlight

4,000mph 'Scramjets' could carry people from London-New York in under an hour