By 
Daily Mail Reporter

PUBLISHED:

10:36 EST, 14 October 2013


| 

UPDATED:

13:06 EST, 14 October 2013

Squeeze: Social Security recipients face historic low increases as Government struggles to balance its books

Millions of Americans are facing the second year of near record low social security rises.

More than one-fifth of the country are bracing themselves for a 1.5 per cent increase - one of the smallest since 1975, according to an analysis by The Associated Press.

Since then, when annual rises, called the cost-of-living-adjustment (COLA), were introduced, Social Security increases have averaged 4.1 per cent.

Nearly 58 million, including disabled veterans, retirees, handicapped workers, spouses and children, will be affected by the historic lows.

The average monthly payment is $1,162. A 1.5 per cent raise would increase the typical monthly payment by about $17.

The COLA also affects benefits for more than three million disabled 
veterans, about two and a half million federal retirees and their 
survivors, and more than eight million people who get Supplemental 
Security Income, the disability program for the poor.

The exact COLA report will not be known until the Labor Department releases the inflation report for September which has been delayed due to the partial government shutdown.

Automatic
COLAs were adopted so that benefits for people on fixed incomes would 
keep up with rising prices. 

Lower prices for gasoline is one of the factors helping to contribute to holding down inflation, according to experts. 

But some experts fear the measure used 
to calculate Social Security payments is not keeping pace with the rise 
in the cost of living.

David Waugh of Bethesda, Md., told The Associated Press he 
can handle one small COLA but several in a row make it hard to plan for 
unexpected expenses.

'I'm not one of those folks that's going to fall into poverty, but it is going to make a difference in my standard of living as time goes by,' said Waugh, 83, who retired from the United Nations.

'I live in a small apartment and I have an old car, and it's going to break down. And no doubt when it does, I'll have to fix it or get a new one.'

Only six times have they been less than two percent, including this year, when the increase was 1.7 percent. There was no COLA in 2010 or 2011 because inflation was too low.

By law, the cost-of-living adjustment 
is based on the Consumer Price Index for Urban Wage Earners and Clerical
Workers, or CPI-W, a broad measure of consumer prices generated by the 
Bureau of Labor Statistics. It measures price changes for food, housing,
clothing, transportation, energy, medical care, recreation and 
education.

The COLA is 
calculated by comparing consumer prices in July, August and September 
each year to prices in the same three months from the previous year. If 
prices go up over the course of the year, benefits go up, starting with 
payments delivered in January.

Cost of living: Experts fear Social Security payments are not keeping pace with the rising cost of living, such as food prices (File photo)

This year, average prices for July and August were 1.4 percent higher than they were a year ago, according to the CPI-W.

Once the September report, the final piece of the puzzle, is released, the COLA can be announced officially. If prices continued to slowly inch up in September, that would put the COLA at roughly 1.5 percent.

Several economists said there were no dramatic price swings in September to significantly increase or decrease the projected COLA.

That means the projection should not change by more than a few tenths of a percentage point, if at all.

Polina Vlasenko, a research fellow at the American Institute for Economic Research, projects the COLA will be between 1.4 percent and 1.6 percent.

The exact COLA figure has been delayed due to the partial shutdown of Federal Government

Her projection is similar to those done by others, including AARP, which estimates the COLA will be between 1.5 percent and 1.7 percent. The Senior Citizens League estimates it will be about 1.5 percent.

Lower prices for gasoline are helping to fuel low inflation, Vlasenko said.

'In years with high COLA's, a lot of 
that had to do with fuel prices and in some cases food prices. Neither 
of those increased much this year,' Vlasenko said. 'So that kept the lid
on the overall increase in prices.'

Gasoline
prices are down 2.4 percent from a year ago while food prices are up 
slightly, according to the August inflation report. Housing costs went 
up 2.3 percent and utilities increased by 3.2 percent.

Advocates
for seniors say the government's measure of inflation doesn't 
accurately reflect price increases older Americans face because they 
tend to spend more of their income on health care. Medical costs went up
less than in previous years but still outpaced other consumer prices, 
rising 2.5 percent.

'This (COLA) is not enough to keep up with inflation, as it affects seniors,' said Max Richtman, who heads the National Committee to Preserve Social Security and Medicare.

'There are some things that become cheaper but they are not things that seniors buy. Laptop computers have gone down dramatically but how many people at 70 are buying laptop computers?'

The cost of personal computers dropped by 10.6 percent over the past year, according the CPI-W.

That's a small consolation to Alberta Gaskins of the District of Columbia, who said she is concerned about keeping up with her household bills.

'It is very important to get the COLA because everything else you have in your life is on an upward swing, and if you're on a downward swing, that means your quality of life is going down,' said Gaskins, who retired from the Postal Service in 1989.

@highlight

58 million Americans on Social Security are set for 1.5% increase

@highlight

Government shutdown has delayed publishing of exact figure

@highlight

Average annual rise since 1975 is 4.1% to keep pace with cost of living

@highlight

Rise amounts to just $17 per month extra for average recipient

@highlight

Lower prices for gasoline are helping to fuel low inflation

@highlight

Experts fear Social Security is not keeping up with rising price of goods