Carl Froch and George Groves are expected to confirm within 24 hours that their grudge re-match will take place at Wembley.

Assuming there are no last-minute hitches, this will be the first fight at the new stadium and the first to take place on the fabled turf this century.

It is a thrilling prospect for the public and an historic occasion for the two fighters - but a brave, high-risk gamble by the promoter.

VIDEO Scroll down for Groves and Froch's press conference

Part II: Carl Froch and George Groves are expected to confirm that their grudge re-match will be at Wembley

Scores to settle: Groves was desperate for another pop at Froch after impressing last time out

Not wrong! Sportsmail columnist Eddie Hearn (centre) promised an 'audacious' venue choice

1963: Henry Cooper v Cassius Clay

Our ’Enery knocked Clay down in the fourth round with a vicious left hook, but through fair means or foul, trainer Angelo Dundee revived Clay. He won in the fifth.

1994: Lennox Lewis v Oliver McCall

Lewis was WBC heavyweight champion but suffered a shock second-round knockout.

1995: Frank Bruno v Oliver McCall

A year on from beating Lewis, McCall returned to Wembley but lost his title to Bruno on points.

Eddie Hearn had promised ‘an audacious’ choice of arena for his May 31 spectacular.

That, it certainly is. All the more so given the minimal amount of time Wembley will have to convert the stadium for boxing following England’s pre-World Cup warm-up game against Peru the previous evening.

Wembley staff are on alert to work through the night but that will increase the cost of renting this already expensive site.

Hearn is convinced that the excitement and controversy generated by the first fight – won by Froch with a somewhat premature stoppage after Groves had knocked him down and built a points lead – will galvanise a crowd approaching Wembley’s 90,000 capacity.

If the attendance falls significantly short of that, in a venue this huge, he risks a drop in atmosphere as well as a fall in revenue.

Not much time: Wembley would have just one day to prepare for the fight after England v Peru on May 30

Under the weather: Froch controversially stopped Groves in the ninth round in November

Stopped: Many believe referee Howard Foster should have allowed the November fight to continue

Past records indicate the scale of the gamble.

The biggest fight ever to take place in the old stadium was that in which Henry Cooper sat Cassius Clay briefly on his famous backside, 51 years ago this month.

Yet despite the British public’s love affair with Our 'Enery and its fascination with the brash young American who would become The Greatest, it drew just 40,000 – Richard Burton and Elizabeth Taylor prominent among them.

After Cooper retired and the nation transferred its affections to Frank Bruno, a gathering of similar size watched his failed attempt in the summer of 1986 to wrench the world heavyweight title from Tim Witherspoon.

When Our Frank finally fulfilled his championship dream nine years later, by defeating Oliver McCall, there were only 23,000 in the stadium.

Figures: Henry Cooper's bout against Cassius Clay drew a crowd of 40,000 at Wembley 51 years ago

Famous: Cooper sat The Greatest on his backside during the non-title fight

New hero: Frank Bruno attracted a similar crowd in 1986 when he lost against Tim Witherspoon

Missed opportunity? Ricky Hatton's fight with Floyd Mayweather Jnr would have drawn record numbers

Support: Around 30,000 fans folowed Hatton and would've drawn plenty more fighting at home

Ricky Hatton, who was followed to his fights in America by an army of more than 30,000 fans, would surely have surpassed all those numbers had Floyd Mayweather not refused to leave his home comforts of Las Vegas.

For big fights these days the media hype is more frenzied and there is more time to sell the event. 

Even so, a live gate of 60,000 would represent an enormous achievement by Hearn.

Wembley became the front runner after Froch and Groves had vetoed each other’s preferred venues, respectively Nottingham Forest’s City Ground and Stamford Bridge, Chelsea.

Two other stadia - Arsenal’s Emirates 
and Cardiff’s roofed Millennium – were under consideration but Hearn 
worked long and hard to pull off his Wembley coup.

Under consideration: Arsenal's Emirates Stadium was thought of as a potential venue for the fight

No thanks! Groves vetoed Froch's preferred stadium - Nottingham Forest's City Ground

Another veto – that of England manager Roy Hodgson in refusing a proposal to shift the Peru date – has been overcome by Wembley calculating they can re-configure for boxing in no longer than 18 hours.

The cheaper seats high in the stands are a considerable distance from the ring but the ‘I was there’ attraction of attending an occasion of such historic significance should help boost sales.

The official announcement is scheduled to be made at Wembley at 11 am Tuesday morning by Sky, who will be broadcasting the fight on their pay-per-view Box Office channel.

Elsewhere, Froch and Groves are already in training for their second world super-middleweight title slugfest.

Amir Khan is unlikely to respond to Floyd Mayweather’s latest provocation by helping the American boost his pay-TV income from his May 3 fight with Marcos Maidana.

Mayweather picked Maidana months after Khan was promised the fight of a lifetime if he waited for this spring date.

Star appeal: Amir Khan will want to top his own bill

Now the world’s top pound-for-pound boxer has told Bolton’s former two-time world champion he can earn a September clash with him by appearing on his undercard.

Mayweather tweeted a challenge to Khan to fight his friend and protegee Adrien Broner, saying he would fight the Englishman next ‘if you beat him, which you won’t.’

Maidana secured his Mayweather pay-night by beating Broner but it is by no means certain that an Argentine will prove a sizeable attraction to Hispanic viewers.

Khan versus Broner would help sell the event. But unless Mayweather is prepared to sign the pre-contract this time, which is improbable, Khan will want to top his own bill this spring.

Broner remains a potential opponent, along with Devon Alexander, Shawn Porter, Luis Collazo and a re-match with Lamont Peterson.

The need for Anthony Joshua to step up in class was evident in his fifth quick KO victory – this one over a lumbering Hector Avila – on Saturday night.

Awesome prospect:  Anthony Joshua (black trunks) was too strong for Hector Avila on Saturday

Britain’s Olympic super-heavyweight gold medallist is an awesome prospect but needs testing. To that end promoter Eddie Hearn is thinking of pitching him against one of two veteran British heavies – Matt Skelton or Michael Sprott – on the undercard of Scott Quigg’s world title fight on April 19.

That looks like a sensible route towards a British title fight later this year.

@highlight

A crowd of 60,000 could watch fight at Wembley Stadium on May 31

@highlight

Groundstaff will have just 18 hours to convert stadium after England face Peru in football friendly

@highlight

Official announcement scheduled to be made at Wembley at 11am on Tuesday morning

@highlight

Khan considers options despite offer to face Mayweather's protegee Broner

@highlight

Joshua must take step up after quick KO of lumbering Avila