Scientists at University College London have hacked a pair of sandals which they claim will allow people to 'hear themselves happy'

Forget meditation and self-help books, the key to a happy life could be down to the sounds you hear.

Scientists in London have hacked a pair of sandals which they claim will allow people to 'hear themselves happy'.

The sandals link to headphones which change the sound of each footstep to gradually make a person feel lighter.

Volunteers who wore the sandals said they felt slimmer, with longer legs and looser knees. They also reported feeling happier and more energised.

The shoes were created by Ana Tajadura-Jiminez at University College London's Hearing Body Project.

'It would give the same benefits as the sandals when walking or running, perhaps in the gym to feel lighter and more motivated,' Ms Tajadura-Jiminez said in an interview with New Scientist.

'We are finding that sound is affecting not just the perception of our body shape but our physical capabilities. Understand these sounds and we could change our feelings in a positive way.'

The sandals exploit a phenomenon called 'predictive coding' in which the brain makes decisions based on past experience.

Ms Tajadura-Jiminez explained that if the sensory feedback you get is not what you were expecting you update your predictions.

Technology such as this could help people with as body dysmorphia, where a mental illness makes them unable to see themselves correctly.

Scroll down to watch the video and try the experiment yourself

During the test, a participant was asked to run her finger across a strip of smooth plastic (pictured). As she moved her hand, headphones played the sound of a finger moving across different surfaces.  Experts believe that auditory changes confuse and disrupt the brain, and this creates a mismatch between the senses

'Something that enhances runner's perception would be very popular,' Sports Engineer Steve Haake at Sheffield Hallam University told the Telegraph. 

In a separate experiment in particular, Ms Tajadura-Jiminez proved that sounds can trick the brain into thinking they're touching a variety of different surfaces. 

During the test, reported in New Scientist, a participant was asked to run her finger across a strip of smooth plastic.

As she moved her hand, headphones played the sound of a finger moving across paper, sandpaper and velvet.

When the sound of a finger moving across sandpaper (stock image left) and velvet (right) were played, the participant reported noticeable changes in how the plastic felt beneath her finger. Researchers want to study how  sounds can be manipulated to affect a person's mood and perception

The participant reported noticeable changes in how the plastic felt beneath her finger after each sound.

Dr AnaTajadura-Jiménez believes that auditory changes confuse and disrupt the brain, and creates a mismatch between the senses.

This is a similar experience people get when viewing optical illusions.

In the case of optical Illusions, colour, light and patterns are used to create images that deceive or mislead the brain.

The information collected by the eye is processed by the brain.

In the process of converting what it sees, the brain tries to make sense of the different colours and patterns. 

This creates a perception that doesn't match the image, and confuses the brain.

Similarly, in terms of audio changes, the information collected by the ear is processed by the brain, which then tries to make sense of the differences.

As the brain tries to account for discrepancies, it produces a variety of sensations.   

As part of the project, Dr Tajadura-Jimenez also studies how auditory information generated by the human body affects how that person comes across, and how people see them.

'This mental representation we have of our bodies is essential for successful interaction with the environment,' explained Dr Tajadura-Jimenez.

Previous studies have highlighted the role that sight, touch and a person's own perception - known as proprioception - play in representation.

But, the effect sounds have on these senses and experiences haven't been investigated in depth.

'Interestingly, the sounds that accompany almost every bodily movement are highly rich in information about the body and the space immediately surrounding it,' continued Dr Tajadura-Jimenez.

She used the example that the sounds produced when tapping on a surface tells people about the length and strength of their arm.

Dr Tajadura-Jiménez believes that auditory changes confuse and disrupt the brain, and creates a mismatch between the senses.

This is similar to the experience people have when viewing optical illusions.

In the case of optical Illusions, colour, light and patterns are used to create images that deceive or mislead the brain.

The information collected by the eye is processed by the brain.

In the process of converting what it sees, the brain tries to make sense of the different colours and patterns. This creates a perception that doesn't match the image, and confuses the brain.

Similarly, in terms of audio changes, the information collected by the ear is processed by the brain, which then tries to make sense of the differences.

As the brain tries to account for discrepancies, it produces a variety of sensations. 

The sensations are similar to those experience when people watch optical illusions (pictured). In the case of optical Illusions, colour, light and patterns are used to create images that deceive or mislead the brain. The information collected by the senses processed by the brain, which then tries to make sense of it 

In another experiment, the pitch created by a person's footsteps was made higher or lower. When lower, the footsteps produced a sound that suggested the person was heavier than they were. This caused participants to report that their legs felt heavier and the steps felt laboured. Higher pitches made people feel lighter

@highlight

Scientists at University College London linked sandals to headphones

@highlight

They changed sound of each footstep to make a person feel lighter

@highlight

Volunteers who wore sandals said they felt happy and more energetic

@highlight

As part of same study, a participant ran her finger across  smooth plastic

@highlight

Headphones played sound of finger across paper, sandpaper and velvet

@highlight

The participant reported noticeable changes in how the plastic felt 

@highlight

The tests were devised by Dr Ana Tajadura-Jimenez for her Hearing Body project at the University of College London