By
Daily Mail Reporter

PUBLISHED:
  
  
      04:33 EST, 22 January 2014
    
  
 | 
  UPDATED:
  
  
      11:45 EST, 22 January 2014

Surfers trying to tackle a monster wave have been put through their paces by a pod of dolphins.

Showing them who really owns the ocean, the porpoises dived and twisted in the surf in San Diego, California.

Spectators watching from the beach were treated to a comical show as the professional surfers were put to shame by the flipping and soaring creatures at Black's Beach, as large surf started to roll into the county.

A dolphin jumps out a back of a wave at Black's Beach as large surf started to roll into San Diego

Surfers were put through their paces by the creatures, who showed them who really owns the ocean

But the National Weather Service warned beach users that the surf could be dangerous.

A meteorologist said: 'A series of large long-period northwest swells generated by storms moving over the North-Central Pacific will bring high surf and strong rip currents to portions of the Orange and San Diego County coast though most of this week.'

The carnivore mammals, which weigh around 1,100lbs, can breach up to 16 feet out of the water and this pod showed off their streamlined skill.

Dolphins can reach speeds of more than 18 mph and travel in social groups, communicating with each other by a complex system of squeaks and whistles.

A series of large long-period northwest swells generated by storms moving over the North-Central Pacific have brought high surf and strong rip currents

Spectators watching from the beach were treated to a comical show as the professional surfers were put to shame by the flipping and soaring creatures, as large surf started to roll into the county

They cover huge distances during migration and at this time of year they head south to the cooler waters.

Feeding habits and food fish movements may also account for the seasonal movements of some dolphins.

@highlight

Showing them who really owns the ocean, porpoises dived and twisted

@highlight

Comical scenes caught at Black's Beach as large surf rolled into county