By 
Simon Tomlinson

PUBLISHED:

06:40 EST, 12 July 2012


| 

UPDATED:

07:09 EST, 12 July 2012

Ballet thriller Black Swan received the most complaints in 2011 in large part because of its lesbian sex scene, the UK's ratings body has revealed.

The film generated 40 objections to the British Board of Film Classification (BBFC), most of whom took a dislike to the raunchy interactions between Natalie Portman as Nina Sayers and fellow dancer Lily, played by Mila Kunis.

Some described the scene as 'pornographic', but the BBFC said it came within the bounds of the film's 15 rating.

'Pornographic': This lesbian scene between Natalie Portman as Nina Sayers and Mila Kunis as Lily made Black Swan the most complained-about film of 2011, according to the UK ratings body's annual report

Disconnect: The British Board of Film Classification said other viewers complained that they had expected to see a film about ballet rather than 'the story of a young woman's mental disintegration'

'While the scene is visually discreet, narratively justified and within the 15 guidelines criteria, some correspondents felt it was pornographic in nature,' it said in its annual report.

'That it was a sex scene between two women was an aggravating factor for some who argued that portrayals of homosexual activity should either be restricted to the 18 category, or not shown at all.'

Others complained that they had 'expected to see a film about ballet rather than the story of a young woman's mental disintegration', the BBFC said its annual report.

The BBFC added: 'The high number of complaints for Black Swan demonstrates the disconnect that sometimes occurs between a viewer's expectations of a film and its actual content.'

'Gratuitous': Hanna (above), which features a genetically engineered 'super-soldier', received 29 complaints, the second-highest for 2011, over its perceived 'sadistic violence'

'Too raunchy': Sucker Punch (pictured), which charts the fantasies of a young woman committed to a mental institution, was condemned by 15 viewers for its sexual suggestiveness

But it said the number of complaints was far fewer than the 120 generated by horror The Woman in Black this year because of its 12A rating.

The report was released as the BBFC announced it had commissioned major research into public perceptions of sexual violence in films - the first for ten years.

The film generating the second-highest number of complaints last year was Hanna, which features a genetically engineered 'super soldier'.

It received 29 objections from viewers who found the violence 'sadistic and gratuitous'.

The Twilight Saga: Breaking Dawn - Part 1 garnered 16 complaints because of the storyline where heroine Bella and her vampire lover Edward, played by Robert Pattinson, marry and consummate their relationship.

Objections: Robert Pattinson as vampire Edward and Kristen Stewart as his lover Bella in Twilight Saga: Breaking Dawn - part 1, which generated 16 complaints from viewers

Sucker Punch, which charts the fantasies of a young woman committed to a mental institution, was condemned by 15 viewers for its sexual suggestiveness and threats targeted at female characters.

The BBFC said it refused to grant a certificate for The Human Centipede II (Full Sequence) because of its horrific plot where a man achieves sexual gratification from the stapling together of victims to form a human centipede. But it was later rated 18 after editing.

The Bunny Game - which sees a truck driver abduct and sexually abuse and tortures a prostitute - was refused a certificate.

It was as a result of those two films that the BBFC decided to commission new research into 'depictions of sadistic, sexual and sexualised violence, mainly against women'.

The body said it wanted to determine what the British public today believes is potentially harmful and therefore unacceptable for classification.

The research will be completed later this year.

@highlight

Oscar-winning movie generated 40 objections in 2011

@highlight

Some viewers thought scene between Nina and Lily was 'pornographic'

@highlight

Others 'expected ballet, but got story of woman's mental decline'

@highlight

Figures released in report by British ratings body

@highlight

Other films receiving complaints include Hanna, Twilight Saga and Sucker Punch

@highlight

British Board of Film Classification commissions major study into attitudes about film violence