 

A small tsunami has hit the coast of northern Japan after a 6.9 magnitude earthquake struck on Tuesday morning. 

A wave of 10 centimetres was observed on the shore of Miyako, a small city of approximately 60,000 people on the eastern-most coast of Honshu, eastern Iwate, at 8:47 am. 

It followed a quake at a depth of about 10 km on Tuesday at 08:06 JST.

The Japan Meteorological Agency issued tsunami advisories and evacuation orders for coastal towns in north-eastern Japan.

The agency said a possible 1-meter (3-foot) tsunami was expected. 

Scroll down for video 

A handout image made available by the U.S. Geological Survey  of a shake map showing the location of an earthquake that struck 77km East North East of Miyako, Japan

This photo shows the Iwate Prefecture area where many train lines were wiped out in the tsunami generated by the Great East Japan Earthquake of March 11, 2011

The US Geological Survey said the quake struck 77km east-northeast of Miyako. 

People on the coast of Iwate Prefecture were warned: 'Get out of the water and leave the coast immediately. As the strong current will continue, do not get in the sea or approach coasts until the advisory is cleared.'

A rise in sea level was observed on the coast of Miyako, Kamaishi and Kuji-ko but no tsunami damage is expected.

A wave of 10 centimetres was observed on the shore of Miyako, northeastern Japan

No tsunami warning has been issued for the Australian mainland or islands.   

Tuesday's earthquake struck in the same region that was hit by a magnitude 9 quake on March 11, 2011, unleashing a devastating tsunami.

More than 18,000 people were killed in the disaster. 

Members of Japan's Self-Defence Force search for bodies in Akahama District, Otsuchi-cho, Iwate Prefecture in the aftermath of the earthquake and tsunami in 2011

Collapsed homes in Akahama District, Otsuchi-cho, Iwate Prefecture, in 2011

 

@highlight

Japan issued a tsunami advisory for the north east coast

@highlight

A tsunami of up to one metre was forecast to hit the coast of Iwate

@highlight

A 10 centimetre wave was then observed on the shore of Miyako 

@highlight

Quake struck 77km east-northeast of Miyako, on the east coast of Honshu