There was no roar from the engine as this super-charged sports car topped 150mph on its record-breaking run yesterday.

Only the relatively gentle sound of tyre rolling over road disturbed the peace and quiet as the UK land speed record for an electric car was shattered.

The team behind a supercar powered by energy from wind turbines believe they have smashed the UK land-speed record for an electric car.

Their recorded speed of 148.7mph breaks the record of 137mph set by Don Wales, the grandson of speed ace Sir Malcolm Campbell, 10 years ago.

Scroll down for video

The Nemesis, driven by Nick Ponting, 21, hit 148.7mph - breaking the 137mph set by Don Wales, the grandson of speed ace Sir Malcolm Campbell, 10 years ago

Journey complete: Driver Nick Ponting and Dale Vince of Ecotricity with the Nemesis electric car after breaking the land speed record for an electric car at Elvington airfield in Yorkshire

The Nemesis, driven by Nick Ponting, 21, hit 148.7mph during a run at Elvington airfield, near York, today.

But today’s achievement still needs to be ratified by the Motor Sports Association before the record can be officially declared.

The makers of the Nemesis say it is the first electric supercar to be built in the UK and they hope it will 'smash the stereotype' of electric-powered cars as boring and slow.

It is the brainchild of Dale Vince, founder of green electricity company Ecotricity, of Stroud, Gloucestershire.

Now called 'the Nemesis', the car was originally a second-hand Lotus Exige which was bought on eBay for £10,000.

Another £750,000 was spent modifying the car over a two-and-a-half year period with the aim of changing the image of electric vehicles.

Stereotype smash: The team home the Nemesis will put paid to the stereotype that electric cars are 'boring'

Powered by battery using electricity from wind turbines, the car averaged 151 mph over two runs of the one mile course.

Mr Vince has said: 'We built the 
Nemesis to smash the stereotype of electric cars as something Noddy 
would drive - slow, boring, not cool.'

Mr
 Vince said the Nemesis is powered entirely by electricity generated by 
Ecotricity’s network of 53 wind turbines around the UK.

It was designed and built in less than two years by a team of leading British motorsport engineers in Norfolk.

Mr Vince said he wanted to stimulate a debate about how everyone will move around when the world runs out of oil.

He said the Nemesis is capable of 0-100mph in 8.5 seconds and, on paper, is capable of topping 200mph.

The Nemesis can travel from 100-150 miles between charges, depending on driving style, and can be charged from empty in less than 30 minutes.

Mr Ponting, who lives in Gloucester and works for an estate agency in Stroud, has had many years of experience racing a range of cars since his early teens.

He said the amazing thing about the car was its consistent acceleration at all speeds.

Last summer Mr Wales attempted to break his own record but ran into trouble on the beach at Pendine Sands in Carmarthenshire.

Ready to break the record: Racing driver Nick Ponting wilth Dale Vince of Ecotricity, moments before the attempt at Elvington airfield in Yorkshire

Mr Vince said the Nemesis is powered entirely by electricity generated by Ecotricity's network of 53 wind turbines around the UK.

It was designed and built in less than two years by a team of leading British motorsport engineers in Norfolk.

The car began life as a second-hand Lotus Exige bought on eBay and rebuilt from the ground up.

Mr Vince said he wanted to stimulate a debate about how everyone will move around when the world runs out of oil.

He said the Nemesis is capable of 0-100mph in 8.5 seconds and, on paper, is capable of topping 200mph.

The Nemesis can travel from 100-150 miles between charges, depending on driving style, and can be charged from empty in less than 30 minutes.

Mr Ponting, who lives in Gloucester and works for an estate agency in Stroud, has had many years of experience racing a range of cars since his early teens.

He said the amazing thing about the car was its consistent acceleration at all speeds.

Last summer Mr Wales attempted to break his own record but ran into trouble on the beach at Pendine Sands in Carmarthenshire.

@highlight

Creators want to 'smash the sterotype that electric cars are 'slow and boring cars that Noddy would drive'

@highlight

Team also wants 'debate about how everyone will move around when the world runs out of oil'