By
Associated Press
and Kieran Corcoran

When Vincent van Gogh cut off his own left ear in a moment of madness more than a century ago, he wanted it to make a big impact.

However, even the great artist could not have anticipated that his severed organ - wrapped up and delivered to a French brothel - would be grown afresh and put on display a year later.

But now, thanks to new technology, a replica has been generated by a 3D-printer from genetic material donated by one of van Gogh's living relatives.

Undated picture shows an ear made of human cells grown from samples provided from a distant relative from Dutch artist Vincent van Gogh, in the center for art and media in Karlsruhe, Germany, Tuesday, June 3, 2014.  US based artist Diemut Strebe said she wants to combine art and science with the installation. (AP Photo/Diemut Strebe.Sugababe)

Lieuwe van Gogh, the 
great-great-grandson of Vincent's brother Theo, donated cartilege from 
his own ear, which was replicated by the machine into an accurate 
re-creation.

The Center 
for Art and Media in Karlsruhe, Germany, grew the ear in a U.S. hospital and are keeping it in a biological preservative.

Diemut Strebe, who is behind the project, said: 'I use science basically like a type of brush, like Vincent used paint'.

Van Gogh was a Dutch painter who was most active in the 1880s, and had a major influence on 20th Century art.

He is best-known for still life paintings - particularly a vibrant painting of sunflowers in a vase - and self-portraits. He was also noted for his tumultuous personal life, and killed himself aged 37.

Artist: Vincent Van Gogh, as pictured in a self-portrait. He hacked his own ear off in 1888

An entry on the museum's website explains: 'The ear is grown from tissue engineered cartilage and is “identical” in shape to van Gogh’s ear by using computer imaging technology.

'It is composed of living cells that contain natural genetic information about him as well as engineered components, replicating in the ear as a “living art-piece”.'

According to Ms Strebe, Lieuwe van Gogh 'loved the project right away'.

Lieuwe and Vincent van Gogh share about 1/16th of the same genes, including the Y-chromosome that is passed down the male lineage.

But hopes of using genetic material that belonged to the post-Impressionist master himself were dashed when DNA extracted from an envelope turned out to belong to someone else.

Still, work is underway with a female relative to include mitochondrial DNA - passed down the mother's line - for future installations.

The exhibition, at which visitors can speak into the ear through a microphone, lasts until July 6.

Strebe said she plans to display the ear in New York next year.

@highlight

Center 
for Art and Media in Karlsruhe, Germany, grew new organ in hospital

@highlight

The Dutch artist cut off his left ear in a moment of madness in 1888

@highlight

It was recreated from ear cartilage donated by a distant male relative

@highlight

Organ will be displayed in preservative liquid and visitors invited to talk to it