By
Ellie Zolfagharifard

Sound waves may not appear to hold much power, but scientists believe directing them in the right way could allow them to hide objects and even levitate them in the air.

Researchers in the US have developed technology to manipulate sound waves on fixed paths around an acoustic 'bottle'.

The technique could be used to re-route sound waves around an object making them invisible to sonar detection.

This animation shows the self-bending and obstacle-circumventing capabilities of the acoustic bottle  compared to a conventional  beam (top). Sound energy can be seen flowing through the shell of the bottle

The acoustic bottle could also help in levitation, where sound waves are used to lift and manipulate objects like particles, micro-organisms and drops of water.

Researchers at the Lawrence Berkeley National Laboratory in California developed the acoustic bottle, which is a three dimensional structure made up of high pressure acoustic waves.

These acoustic bottles in open air can bend the paths of sound waves along preplanned paths.

Sound waves move much like light waves. They travel on a straight path but this path – through reflection, diffraction or refraction – can be bent.

Directed sound energy from speakers forms a 3D acoustic bottle consisting of high-pressure walls and a zero pressure region in the middle. Pressure field at bottom shows self-bending ability of the bottle

'We need to find ways to bend acoustic wave fields without depending on the use of a highly engineered medium,' says Xiang Zhang, director of Berkeley Lab's Materials Sciences Division.

'With our bottle beam technique, we can design and synthesise acoustic bottles that are capable of directing sound waves along paths of desired curvature through homogeneous space without the need of metamaterials or any other highly engineered medium.'

In this latest project, Professor Zhang's research group, created an acoustic 'bottle' that features a three-dimensional curved shell.

At the centre of this shell is of high acoustic pressure is a region of zero pressure.

This image shows the sound intensity distribution of self-bending bottle beam. The trajectory the researchers aimed for is in the red-dashed curve, and the direction of the beam in the grey-dashed curve

Sound waves forming the bottle are concentrated into a beam that travels through the high pressure wall of its curved shell.

The sound waves are generated by an array of loud speakers, 1.5cm in diameter and spaces 2.5cm apart, operating at a frequency of 10 kilo Hertz (kHz).

The high pressure wall of the acoustic bottle exerts a pulling force, which means there are no sound waves passing through the centre, making it ideal for trapping sound.

'We can also levitate much larger 3D objects than can be lifted and manipulated with other acoustic levitation techniques,' said researcher Jie Zhu.

It might look like a quirky plastic model of an ancient Egyptian pyramid, but this model is in fact a 3D 'acoustic cloak', created using just a few perforated sheets of plastic.

The device reroutes sound waves to create the impression that both the cloak and anything beneath it are not there.

Like the 'acoustic bottle', a refined version of the technology could one day be used for sonar avoidance and to refine noise in concert halls.

Engineers from Duke University in North Carolina, claim that unlike other efforts, the acoustic cloaking device works in all three dimensions, no matter which direction the sound is coming from.

‘The particular trick we’re performing is hiding an object from sound waves,’ said Steven Cummer, professor of electrical and computer engineering.

The pyramid is constructed using plastic plates with a repeating pattern of holes that are stacked on top of one another. Its design means that sound waves can be manipulated by plastic and air.

The cloak alters the sound waves’ trajectory to match what they would look like had they had reflected off a flat surface.

The 'invisible' pyramid: The world's first 3D acoustic cloak (pictured) was created by U.S. engineers using just a few perforates sheets of plastic and a great deal of number crunching.

The device reroutes sound waves to create the impression that both the cloak and anything beneath it are not there

 

@highlight

Researchers at the Lawrence Berkeley National Laboratory in California developed the 'acoustic bottle' to make objects invisible to sonar detection

@highlight

Bottle is made up of high acoustic pressure around zero pressure region

@highlight

Sound from speakers is directed in a specific way to create bottle shape

@highlight

The force of the outer shell can also be used to levitate objects such as particles and drops of water 