It could be bad news for professional race car drivers - a self driving car has beaten one of their ranks for the first time.

Researchers at Stanford have been working with Audi to develop a high speed self driving car.

The team has designed an Audi TTS dubbed 'Shelley' which has been programmed to race on its own at speeds above 120 mph at Thunderhill Raceway Park in Northern California.

It its latest test, it was pitted against  David Vodden, the racetrack CEO and amateur touring class champion - and was faster by 0.4 of a second.

Scroll down for video

The team has designed an Audi TTS dubbed 'Shelley' which has been programmed to race on its own at speeds above 120 mph at Thunderhill Raceway Park in Northern California

Shelley was named after Michele Mouton, the first woman to win the race up Pikes Peak in the Rocky Mountains. It its latest test, it was pitted against David Vodden, the racetrack CEO and amateur touring class champion - and was faster by 0.4 of a second.

Shelley knows exactly where she is on the road by using a differential GPS. 

Unlike a standard GPS system, hers corrects for interference in the atmosphere, showing the car's position on the Earth with an accuracy of about 2 centimeters. 

Shelley measures her speed and acceleration with wheel-speed sensors and an accelerometer, and gets her bearings from gyroscopes, which control equilibrium and direction.

'The typical male response is, it'll never beat me,' David Vodden admitted to NBC.

The white Audi TTS was last year put through its paces on the Thunderhill Raceway, north of Sacramento, California. 

Affectionately named Shelley is the result of a collaboration between Stanford's Dynamic Design Lab, led by mechanical engineering design graduate Chris Gerdes, and the Volkswagen Electronics Research Lab. 

The results were revealed during a briefing at the American Association for the Advancement of Science's annual meeting in San Jose. 

In a computerized comparison of Shelley's and Vodden's performance, Vodden picked up time on some turns - but Shelley was able to battle back, beating Vodden by four-tenths of a second.

'Now to be totally honest and open about this, I can start this competition at a different point on the track, and David wins by 0.4 seconds, so there is still not a clear victory here,' Gerdes said. 

'But the point we wanted to make is that we've gotten fairly comparable to an expert driver in terms of our ability to drive around the track.' 

As the pair race, sensors record variables such as the driver's body temperature and heart rate.

Scalp
 electrodes will be used to register the driver's brain activity as they
 race against other humans to determine which driving manoeuvres require 
the most concentration and brainpower.

However, despite the autonomous car's sophisticated technology, it still can't quite compete with human-driven equivalents. 

As the pair race, sensors record variables such as the driver's body temperature and heart rate.

Graduate research team leader Chris Gerdes shows off the systems carried onboard the autonomous car, a modified Audi TTS

Despite the loss, Vodden and his fellow race drivers have built up an instinctive sense about when and how far to push their vehicles. 

'Shelley doesn't have what I call the 'butt sense' yet,' Vodden said. 

'Once she does get that butt sense, I'll be enthralled.' 

'Human drivers are very, very smooth,' said Gerdes.

Shelley computes the fastest line around a course and executes the exact corrections required to stick to it.

A person relies more on feel and intuition, and thus may, for example, allow the car to swing too wide in one turn if he knows it sets him up better for the next.

'Human drivers are ok with the car operating in a comfortable range of states,' said Gerdes. 

'We're trying to capture some of that spirit.' 

'We need to know what the best drivers do that makes them so successful,' said Gerdes. 'If we can pair that with the vehicle dynamics data, we can better use the car's capabilities.'

The team believes that the experience and the data they have gained can be used to develop autonomous vehicles for use on public roads.

Shelley measures her speed and acceleration with wheel-speed sensors and an accelerometer, and gets her bearings from gyroscopes, which control equilibrium and direction. 

In the nearer term, the technology could be used as an onboard co-pilot that helps the driver steer out of a dangerous situation.

The reality of racing a car round a track and pushing that vehicle to its absolute limit means that it will be subjected to exceptionally high levels of stress.

One recent test left Shelley without any brake pads due to the intense heat generated by friction between the tyres and the pads themselves.

Pushing a car to the limit on the racetrack is one of the best ways to find out what type of stress that car is under in a crisis.

'If we can figure out how to get Shelley out of trouble on a race track, we can get out of trouble on ice,' said Gerdes.

 

@highlight

Audi TTS dubbed 'Shelley' raced at Thunderhill Raceway Park in California

@highlight

Raced against David Vodden, amateur touring class champion

@highlight

Shelley was found to be faster by 0.4 of a second