By
Sarah Michael
and Louise Cheer

Fatima Dyczynski was travelling to Perth to start a new life as an intern for IBM on flight MH17

The Perth-based parents of Fatima Dyczynski, who is believed to be a MH17 victim, are on their way to the flight's Ukrainian crash site, still holding onto the hope that their daughter is alive.

Miss Dyczynski's father, Dr Jerzy Dyczynski - also known as George - told Daily Mail Australia, from the Schiphol Airport in the Netherlands, that despite the dangers of the war zone he and his wife were travelling to, it was something they had to do.

'Every day we believe she is still alive,' he said.

'We believe our daughter is alive and we’re going to look after her.

'We know it’s a dangerous place but we have to go because she is our daughter.'

A promising space engineer and aspiring astronaut, Fatima Dyczynski, 25, was moving from Germany to start a new life in Perth when she boarded the Malaysia Airlines flight along with 297 other people.

Despite authorities advising that there were no survivors of the crash, Angela Rudhart-Dyczynsk said she held hope her daughter might be alive because her mobile phone continued to ring after the plane was downed, The West Australian reported.

'We believe that Fatima could be alive - this is why we're going on this trip,' she said.

Mrs Rudhart-Dyczynsk and her husband Jerzy (George) Dyczynski, who live in Mosman Park, left Perth Airport to fly Amsterdam on Thursday wearing t-shirts emblazoned with their daughter's picture and the words 'Fatima We Love You'.

Dr Dyczynski vowed he and his wife would 'go on our own' to the Ukrainian war zone where MH17 was shot down if it is discovered Miss Dyczynski's body is among the 100 feared missing, after officials warned victims' families against travelling to the region.

Former Perth talkback radio host Howard Sattler, who is close friends with Dr Dyczynski and Mrs Rudhart-Dyczynsk and has spent every day with them since the crash, said they believed there was a remote possibility she could have survived.

Mr Sattler said that since Friday the 'deeply religious' couple had been watching footage about the crash on television hoping to see anything that might say their daughter is alive.

Scroll down for video

Dr and Mrs Dyczynski arrived at Schiphol Airport in the Netherlands on Thursday and walked past the MH17 memorial

Dr Dyczynski and his wife, Angela, still hold onto hope that their daughter, Fatima, is alive

'Their faith is keeping them going,' he told Daily Mail Australia.

'They believe the freezing temperatures up there would be counteracted by the explosion and on that basis she may have survived.

'People may say "How could she survive a fall of 30,000 feet?" but it has happened in extremely rare cases that the seat has remained intact.

'There are still 16 people confirmed to not have been found at all.'

Mr Sattler became friends with Dr Dyczynski, a cardiologist and acupuncture practitioner, after seeing him as a patient.

He said the couple moved to Australia after their daughter 'fell in love with the place' when she spent a year as a student at Perth's John XXIII College in Year 11.

Mr Sattler said all three had applied for permanent residency and had received it this week.

'Posthumously she's an Australian I guess,' he said.

Mr Sattler said the couple would arrive in Amsterdam on Thursday afternoon AEST, and their plans depended on whether Miss Dyczynski's remains were among those transported to The Netherlands.

Miss Dyczynski Perth-based parents arrived in Europe to find their daughter

59908

143802

60651

71425

29443

'It depends a lot, totally, on the fact if she's there she's there if not they make look elsewhere,' he said.

Since Friday Miss Dyczynski's parents have been at home reflecting on stories about her.

'Some of her old school friends have visited, friends of the family, people from their church,' Mr Sattler said said.

'She was so brilliant and remarkable.

'She is an amazing young woman for whom it was often said nothing was impossible for her.'

Mr Sattler has written a blog post explaining why Mr Dyczynski's believes she may have miraculously survived.

'He theorises that she may have been catapulted into the sky, still strapped to her seat and if it had remained intact it could have cushioned the impact of falling to ground from such a great height,' Mr Sattler wrote.

'The freezing temperatures encountered by anyone exposed to the atmosphere at over ten thousand metres could have caused the brains of any survivors of the initial blast to "hibernate", at the same time countering the heat generated by the explosion, he says.

Miss Dyczynski, who is trained in aerospace, aeronautical and astronautical engineering, was moving to Perth to start an internship at IBM 

'With time crucial, Dr Jerzy has sent urgent messages to Prime Minister Abbott, Foreign Minister Bishop and international news outlets detailing his theories and calling for the search to be upscaled.'

Dr Dyczynski is also critical of the fact that there were no medical personnel at the crash site in case 'life-saving measures' were needed.

'These are not the ramblings of a mad man, just the overwhelming feeling of grief, finding an avenue to soften the excruciating horror that has befallen him,' Mr Sattler wrote.

Dr Dyczynski and Mrs Angela Rudhart-Dyczynski are some of the first people to take up the Australian government's offer to fly victims' families to the Netherlands to accompany their loved ones home, if they so wish.

Miss Dyczynski, who was trained in aerospace, aeronautical and astronautical engineering, was moving to Perth to start an internship at IBM.

Miss Dyczynski was the chief executive and founder of Xoterra Space, a high-tech start-up company developing means to create tiny satellites which would connect mobile phones to directly to space technology.

@highlight

George Dyczynski and his wife Angela are now on their way to the crash site

@highlight

Dr Dyczynski said: 'Every day we believe she is still alive.'

@highlight

The couple left Perth Airport on Thursday to fly to the Netherlands

@highlight

Fatima Dyczynski, 25, was moving from Germany to start a new life in Perth when she died on the Malaysia Airlines flight along with 297 other people