An ax-wielding man is on the loose following an unprovoked attack on a Washington, D.C. cop just days after a rookie NYPD officer was hacked by a radical Muslim convert while on patrol. 

The officer was sitting in a marked police car when the suspect shattered the driver's side window at 3.20am on Friday morning.

Following the ambush, the officer chased the subject and tackled him to the floor, but the suspect was able to escape.

Unprovoked: The officer was sitting in a marked police car when the suspect shattered the driver's side window at 3.20am on Friday morning in Washington, D.C. 

Officials in the District of Colombia stressed there was no evidence linking the two attacks, but contacted the New York City police's counter terrorism unit, who have now put their officers on high alert.

The department released an advisory saying uniformed officers saying they should 'remain vigilant' and approach all situations 'tactically'. 

According to the New York Daily News they will not be allowed to patrol alone, with officials fearing they could be targeted by terrorists in random attacks.

Last Thursday, Zale Thompson targeted a group of four rookie officers while they were out on patrol in Jamaica, Queens. 

Photographer Dominick Williams spotted the officers and asked them to stand for a picture. Seconds later, Zale Thompson ran up to the cops - who where standing against a wall in Jamaica, Queens - and started swinging a sharp hand ax. 

Officer Kenneth Healey, 25, was taken to the hospital in critical condition, but is expected to survive the injury. 

Scene: Following the ambush, the officer chased the subject and tackled him to the floor, but the suspect was able to escape

Washington, D.C, Police Chief Cathy Lanier said: 'A lot of these radical organizations, terrorist organizations are very vocal about targeting first responders. It's no secret. It's not new. But it certainly has ramped up,' Lanier said. 'We're on extremely high alert.'

Lanier said she spoke with John Miller, New York City's top counterterrorism official, to go over any investigative details that might be helpful.  

The officer spotted the man briefly before the attack and believed he was carrying a baseball bat, Lanier said. 

The officer drove into an alley in an attempt to follow him but did not see the man again until the ax hit the car, Lanier said.

The officer chased the man and tackled him and was injured in the struggle, police said.

Police don't have a good description of the man, and Lanier said investigators were pursuing 30 to 40 leads, including some generated by tips from the public. 

The FBI offered help with the investigation if needed. 

Fanatic: Last Thursday Muslim convert Zale Thompson attacked a group of four rookie NYPD cops in Jamaica Queens, critically injuring one

Sorry we are not currently accepting comments on this article.

@highlight

Suspect smashed the window of a marked police car at 3.20am on Friday

@highlight

Officer then chased the man and tackled him - but suspect escaped 

@highlight

NYPD released a memo telling their officers to 'remain vigilant' 

@highlight

Follows attack by Muslim convert Zale Thompson in Queens last week

@highlight

Uniformed cops have been prohibited from patrolling alone in the city