Coral reefs are known as the ‘rainforests of the sea’ and although they only occupy a total area half the size of France, they provide a home for a quarter of all marine species on the planet.

It's well known that reefs are under threat from acidification as the oceans warm up, but now there is a quirky new plan to grow new reefs from scratch – and it involves electricity.

One architect has shared designs for a futuristic manmade reef with an electric field designed to attract calcium carbonate from the water in a bid to form new reefs quickly.

The future of the ocean? One architect has shared designs for a futuristic manmade reef (illustrated) with an electric field designed to attract calcium carbonate from the water in a bid to form new reefs quickly

If built, Margot Krasojevic’s artificial reef could play a role in role in protecting the Indonesian coastline from tsunamis, as well as providing homes for countless marine animals.

In her vision, the reef would be formed from a framework of moveable steel girders and steel ball structures, designed in a way to support the growth of natural coral.

Large ‘metal balls’ would be connected by cables to floating solar panels on the water’s surface so an electrical current can be generated.

If built, Margot Krasojevic's artificial reef (pictured) could play a role in role in protecting the Indonesian coastline from Tsunamis, as well as providing homes for countless marine animals

The current would draw particles of calcium to small pieces of natural coral attached to steel frames below the water, in a bid to stimulate further growth.

It would be low enough for divers to swim around the structure - which looks as it if comes from a sci-fi film – but strong enough to create an electric field around the frame.

The field would condense dissolved calcium carbonate in the seawater so that it could attach itself to the steel frame in order to build the limestone skeleton.

In her vision, the reefs would be formed from a framework of moveable steel girders and steel ball structures, designed in a way to support the growth of natural coral

The 'meta balls (pictured) would be connected by cables to floating solar panels on the water's surface so an electrical current can be provided

And the coral fragments tied to the calcium carbonate-covered frame would help limestone skeleton growth, which is the foundation for natural corals.

The reason natural and artificial coral is so important is that it buffers the impact of hurricanes and tsunamis in coastal regions.

It does this by slowing down and reducing the force of waves as they approach the shore so that reefs can diminish the distance and amplitude of the waves travelling inland.

The electric current generated by the strange structure (pictured) would attract helpful natural particles to small pieces of natural coral attached to steel frames below the water, in a bid to stimulate further growth extra quickly

The healthier and more structurally complex a reef is, the more friction it provides and the better it protects the coastline and damage onshore.

The project is also designed to support the growth and protection of coral reefs for their beauty and biodiversity.

Corals can be found in both shallow and deep ocean water and the concept would cater to both as it would be anchored into the ocean bed using flexible steel ties, which would allow for it to move slightly with currents.

The electric current would be low enough for divers to swim around the structure - which looks as it if comes from a sci-fi film ¿ but strong enough to create an electric field around the frame

The coral fragments tied to the calcium carbonate-covered frame (illustrated) would help limestone skeleton growth which is the foundation for natural corals, which are important is that it buffers the impact of hurricanes and tsunamis in coastal regions

They provide shelter for marine life, are valuable sources of organisms for potential medicines, create sand for beaches and serve as a shock absorber for shorelines.  

Healthy reefs provide twice as much protection from tsunamis as unhealthy or dead reefs because they have rougher surfaces, which provide friction that slows the waves substantially in comparison with smoother, unhealthy ones.

The design of the reef station uses complex geometries like Voronoi patterns – a mathematical way of dividing space into a number of regions that correspond to each other and a set of points in a particular way – to be able to provide enough drag to slow down waves passing over it.

The innovative design, planned for the Indian Ocean, would provide shelter for marine life and serve as a shock absorber for Indonesian shorelines in the form of a tsunami

The artificial reef could also include laminated sections of glass that would shatter into small pieces if a large force is exerted. They would be made from holographic yellow filters to focus and disperse sunlight into the shallower waters providing photosynthesis for the corals that help speed up the process of reef building.

Rusty cars, tanks and old decommissioned ships are currently used as a starting point for the formation of artificial reefs, but some experts fear that they are just an excuse to dump rubbish in the sea.

The design of the reef station uses complex geometries like Voronoi patterns - a mathematical way of dividing space into a number of regions that correspond to each other and a set of points in a particular way - to be able to provide enough drag to slow down waves passing over it

@highlight

Belgrade architect Margot Krasojevic's concept incorporates an electric field which is designed to attract calcium carbonate from the water, to form new reefs quickly

@highlight

If built, the artificial reef could play a role in role
 in protecting the Indonesian coastline from tsunamis, as well as 
providing homes for countless marine animals

@highlight

The reef would be formed 
from a framework of moveable steel girders and steel ball structures, 
designed in a way to support the growth of natural coral and the electric field would be generated by connected floating solar panels