Rosetta has captured a selfie of its shadow on comet 67P in what is the highest-resolution image to be taken by the probe.

The image was taken during a Valentine's Day flyby when Rosetta passed within just four miles (6 km) from the surface of the icy comet.

As well as the craft's shadow, an 'alien' glow is seen reflected onto the comet, which scientists believe is caused by a trick of the light from the sun.

Scroll down for video 

Rosetta has captured a selfie of its shadow (bottom of image) on comet 67P in what is the highest-resolution image to be taken by the probe. The image was taken during a Valentine's Day flyby when the Rosetta passed just four miles (6 km) from the surface of the icy comet.

The glow causes the shadow to be fuzzy and somewhat larger than Rosetta itself, measuring approximately 65ft by 165 ft (20 by 50 metres).

If the sun were farther away, the shadow would be sharp and almost exactly the same size as Rosetta, which is around 2 x 32 metres.

However, even at 215 million miles (347 million km) from 67P/C-G on 14 February, the sun appeared as a disc about 0.2 degrees across.

This is about 2.3 times smaller than on Earth - resulting in a fuzzy 'penumbra' around the spacecraft's shadow.

With Rosetta just four miles (6km) above the surface, the penumbra effect adds roughly 65ft (20 metres) to the spacecraft's dimensions, which 

This graphic shows the difference between how a sharp shadow is generated by a point source (left) and a fuzzy shadow by a diffuse source (right)

The view, which shows the detail in features down to 11cm, is of a region on the bottom of the comet. The OSIRIS narrow-angle camera image from the close flyby shown here in context with a NAVCAM image

If you were standing on the surface with Rosetta high above you, there would be no place in the shadow where the entire sun would be blocked from view. 

The view, which shows the detail in features down to 11cm, is of a region on the bottom of the comet. 

Other images reveal boulders on the comet's surface, as well as 'stunning details of the contrasting terrain,' the European Space Agency said.

The boulders in these images range in size from a few metres to a few tens of metres, and lay scattered across the comet's surface.

Images taken from this viewpoint are of high scientific value,' says OSIRIS Principal Investigator Holger Sierks from the Max Planck Institute for Solar System Research (MPS) in Germany. 'This kind of view is key for the study of grain sizes.' 

Esa's Rosetta spacecraft launched on 2 March 2004 aboard an Ariane 5 rocket, on a mission to visit comet 67P/Churyumov-Gerasimenko.

It took more than ten years to reach the comet, and on the way it flew past Mars and two asteroids.

On 6 August 2014 it entered orbit around the comet, beginning a series of complex manoeuvres to get the best views possible.

On 12 November 2014 Rosetta successfully released a smaller vehicle it had carried called Philae. This small probe bounced twice on the surface before coming to rest.

Although Philae's landing did not go as planned, it was still able to complete more than 90 per cent of the science it was intended to do before its main batteries died, sending the probe to sleep.

The location of the lander is currently unknown. It is thought to be in partial shadow near a cliff but, as the comet approaches the sun, the additional light may charge its solar panels enough for the lander to wake up.

Rosetta, meanwhile, is continuing its mission around the comet. 67P is approaching the sun and, by August this year, it is thought its activity will have dramatically increased.

This will release much more ice, vapour and other materials from the surface - and Rosetta will be there to watch it all happen. 

This OSIRIS shape model is marked with the position of the narrow-angle camera field of view taken during the 14 February flyby

A four-image montage of Comet 67P/Churyumov–Gerasimenko comprising images taken on 14 February 2015 during the first dedicated close flyby. This image set was taken at 10:32 GMT from a distance of 7.8 miles (12.6 km) from the comet centre. Using the surface distance, the image scale is 0.9 m/pixel

The closest approach took place at 12:41 GMT over the Imhotep region on the comet's large lobe.

Rosetta's parting shot following the close flyby features the comet's small lobe at the top of the image, with the larger lobe in the lower portion of the image set.

As well as providing the opportunity to take close-up high-resolution images of the comet surface, flybys like this also allow Rosetta's instruments to sample the innermost parts of the comet's atmosphere, or coma.

Rosetta is now moving out for a far view of the comet – it will reach a distance of about 160 miles (255km) from the comet centre tomorrow.

Last month, Nasa said the structure of Comet 67P resembles ice cream.

In an experiment, they found that while the exterior of a comet is encased in a hard, outer crust, the interior would mostly be fluffy ice.

Rosetta's parting shot following the close flyby features the comet's small lobe at the top of the image, with the larger lobe in the lower portion of the image set

'A comet is like deep fried ice cream,' said Dr Murthy Gudipati of Nasa's Jet Propulsion Laboratory in Pasadena, California, corresponding author of a recent study appearing in the Journal of Physical Chemistry.

'The crust is made of crystalline ice, while the interior is colder and more porous. The organics are like a final layer of chocolate on top.'

To come to the conclusion, astronomers used an icebox-like instrument nicknamed Himalaya.

They showed that fluffy ice on the surface of a comet would crystallise and harden as the comet heads towards the sun and warms up.

The composition of comets is important to understanding how they might have delivered water and organics to the young, hot Earth.

New results from the Rosetta mission show that asteroids may have been the primary carriers of life's ingredients; however, the debate is ongoing and comets may have played a role. 

New results from the Rosetta mission show that asteroids may have been the primary carriers of life's ingredients; however, the debate is ongoing and comets may have played a role. This image set was taken at 4:32 GMT from a distance of 22 miles (35km)

@highlight

The halo is believed to be created by a trick of light from the sun

@highlight

Sun over comet appears 2.3 smaller than on Earth, causing the effect

@highlight

Valentine's day swoop was the first dedicated close flyby of the mission

@highlight

Rosetta passed just four miles (6 km) from the surface of the icy comet

@highlight

Imaged boulders range in size from a few metres to a few tens of metres 