 It is a rare meeting of two of the most beautiful phenomenon on Earth.

Nasa astronaut Barry 'Butch' Wilmore captured the amazing moment an aurora and a sunrise 'collide'

'All we need now are angels singing,' Wilmore wrote.

Scroll down for video 

Nasa astronaut Barry 'Butch' Wilmore captured the amazing moment an aurora and a sunrise 'collide' - here the sunrise can be seen beginning to creep in on the right of the image.

The video, taken by astronaut Barry 'Butch' Wilmore aboard the ISS, follows the aurora borealis, or Northern Lights, and captures the moment 'sunrise touches aurora.'

Nasa filmed the footage over Virginia, Delaware, New Jersey, New York and Massachusetts before the clip was sped up and posted online.

Northern Lights is the common name for Aurora Borealis, a light show of varying colours caused by collisions between electrically-charged particles from the sun that enter the Earth's atmosphere.

Aurora are one effect of energetic particles which can speed out from the sun both in a steady stream called the solar wind and due to giant eruptions known as coronal mass ejections, or CMEs.

After a trip toward Earth that can last two to three days, the solar particles and magnetic fields cause the release of particles already trapped near Earth.

As the video progresses, Virginia, Delaware, New Jersey, New York and Massachusetts are passed over - as the sunrise 'touches' the aurora.

This in turn trigger reactions in the upper atmosphere in which oxygen and nitrogen molecules are released a particles of light.

The strong solar flare which created this aurora triggered a radio blackout for parts of Earth over the weekend, according to an alert from the U.S. Space Weather Prediction Center.

Usually the best spots to see the lights are those places close to the North Pole, such as Iceland and Norway.

In the southern hemisphere, they are known as the Aurora Australis and can often be mirror-like images that occur at the same time as in the north.

Clear winter nights tend to be better for observing the sky due to less haze and water vapour in the air.

The colour of the aurora depends on which gas - oxygen or nitrogen - is being generated by the electrons. It also depends on how fast the electrons are moving.

As well as Earth, any planet with a magnetic eld and an atmosphere should have auroras, including Jupiter, Saturn, and Uranus. 

 

 

 

 

 

 

@highlight

Captured by by astronaut Barry 'Butch' Wilmore aboard the ISS

@highlight

Filmed over Virginia, Delaware, New Jersey, New York and Massachusetts

@highlight

Clip was sped up and posted online by Nasa 