Skaters are often music lovers, so it was only a matter of time before the two hobbies were combined. 

A student has created a modified skateboard that has speakers built into the base - and even a dock for a mobile phone or music player.

And, in addition to playing music from the docked device, the Chargeboard can charge its battery using kinetic energy generated by the board's spinning wheels.

Scroll down for video 

A student at the Willem de Kooning Academy of art and design in Rotterdam has designed an electric skateboard called the Chargeboard (shown). The device has a docking station for the iPhone 4 and 4S. When turned on its side it can charge the phone and it also has speakers to play music

The Chargeboard was created by Bjorn van den Hout as part of a graduation project at the Willem de Kooning Academy of Art and Design in Rotterdam.

He is now seeking funding for the project on Kickstarter. 

The two dynamo’s in the rear axles of the board generate 6V each.

This electricity is then converted back to a 5V current and gets stored in to a powerbox.

When a user docks their iPhone into the board, the powerbox automatically begins charging it. 

While in the dock, users can also play tracks using a speaker in the base.

It is currently a prototype, but its designer plans to launch a Kickstarter campaign to fund production. 

In the wheels. two dynamos generate 6V when they spin, which is converted to a 5V current in the box of the skateboard.

Aside from powering the speakers, this also charges the phone when it’s plugged in.

The Chargeboard docking station is currently compatible with the iPhone 4 and the iPhone 4S, although a 3.5mm headphone jack and a USB 2.0 port means other devices can also be used.

 

The wheels of the board charge a battery pack in the board as it moves. One hour of riding can completely charge a phone. The board also has a 3.5mm headphone jack and USB port for use with other devices

In the wheels (pictured) two dynamos generate 6V when they spin, which is converted to a 5V current in the box of the skateboard. Aside from powering the speakers, this also charges the phone when it’s plugged in

Riding the board for one hour generates enough power to fully charge a phone, while the built-in battery can charge a phone eight times over.

‘I really want to develop it further, and bring it to market,’ van den Hout told MailOnline.

‘So I’m looking for a team of people who want to technically develop Chargeboard, and an investor would be great to get the project off the ground!

‘Because I just graduated I don’t have the financial capacity to finance it on my own.’ 

Designer Bjorn van den Hout plans to start a Kickstarter campaign on Monday 29 September to raise funding for production of the Chargeboard (pictured)

 

@highlight

Chargeboard was built at the Willem de Kooning Academy in Rotterdam

@highlight

The device has a docking station for the iPhone 4 and 4S

@highlight

When turned on its side, the electric board can charge the phone

@highlight

It also has underside speakers  that play music from a docked phone

@highlight

The wheels of the board charge a battery pack in the board when it moves

@highlight

Student inventor claims an hour of riding can completely charge a phone

@highlight

It also has a 3.5mm headphone jack and USB port for other devices

@highlight

Designer Bjorn van den Hout is now seeking funding on Kickstarter