Wearing clothes made from cloth covered with tiny silver wires may reduce your heating bills in the future.

This is because scientists have found that a new material made of cotton coated in silver nanowires, effectively traps heat inside a person’s clothing, to keep the wearer cosy.

The say it is also breathable and lightweight, making it comfortable to wear.

Scientists have found that a new material made of cotton coated in silver nanowires, effectively traps heat inside a person’s clothing, to keep the wearer cosy. These images show the wires under the microscope at different magnifications, which because they are closely packed together, form a conductive network

Scientists from Stanford University in California developed the prototype material using silver because it reflects infrared radiation back towards the body, Popular Science reported.  

In order to make the metallic material comfortable to wear, they dipped cotton into a solution of silver nanowires that can sit on top of everyday clothing, according to the study published in Nano Letters.

They created a fabric that’s able to trap 80 per cent of body heat. 

The fabric is able to trap 80 per cent of body heat, because the tiny silver wires reflect infrared radiation back towards the body (shown in a diagram on the left). A piece of the new cloth was cut out in an 'S' shape and placed in the palm (top right). Using heat-sensitive camera, the researchers showed it is able to block all uman-radiated IR, keeping the heat inside so that the S-shape looks blue (bottom right)

Tiny antibacterial particles from silver are woven into the fabric of some socks to kill bacteria that makes them smell.

The silver in the particles doesn't kill bacteria by touching it, but instead produces soluble ions that reduce the pong.

Studies concluded that some of the particles come out in the wash, with some of them warning that when the toxic metal dissolves in water and releases silver ions, it can enter the food chain, poisoning small creatures. 

However, others have said silver nanoparticles don't harm humans or the environment.

Research published in 2012 warned that bacteria may become resistant to silver if used in lots of everyday situations, which could have important implications, because the metal is used as an anti-bacterial in healthcare.

Silver is also rare and it's estimated that global resources could run out in as little as 30 years.

It is as efficient as a bulky fleece when worn like a normal piece of clothing, emitting infrared radiation emitted by a wearer, back to their body.

But the clothes could be plugged into a computer, for example, to keep wearers even warmer.

The idea is that a small amount of electricity could effectively turn a jacket into an electric blanket.

Extra heat can be generated by harnessing the movement of electricity across the fabric.

And because the cloth is thin and breathable, it could one day replace bulky outdoor ski coats.

The researchers say that the clothes could also be worn indoors to negate the need for heating.

While it’s easy to imagine that cloth made from silver may be expensive, the researchers claim the total cost of silver needed to make a complete body suit would only cost $1 (66p).

The researchers claim that wearing such clothes could save a person $200 a year in heating costs, or save enough energy to power 1,000 light bulbs for 10 hours.

The cloth is not yet on sale and requires more testing, but the scientists are already working on another coating to keep clothes and their wearers cool in hot temperatures.

@highlight

Prototype cotton fabric is coated in silver nanowires to trap body heat

@highlight

It's as effective as a thick fleece, trapping 80% of heat 

@highlight

Material uses silver because it reflects infrared radiation back to the body

@highlight

A small electric charge can be applied so it works like an electric blanket

@highlight

Experts from Stanford University say the cloth's breathable and lightweight

@highlight

It was developed to save energy produced by central heating