By
Mark Prigg

Glass is set to come to Oakley and Rayban thanks to a deal between Google and Italian fashion giant Luxottica.

The firms are set to work together in a bid to make Glass, Google's wearable computer, more fashionable.

The pair are set to develop a new eyewear brand for the project - but promised it would include Raybans's fashion frames and Oakley's sports glasses.

Scroll down for video

RayBan's famous aviators: the firm is now working with Google to develop a version with a wearable Glass computer built in

Next generation: Google Glass has revealed the new look of its high-tech device

'We are thrilled to announce our partnership with Google, and are proud to be once again setting the pace in the eyewear industry,' said Andrea Guerra, Chief Executive Officer of Luxottica Group.

'We live in a world where technological innovation has dramatically changed the way in which we communicate and interact in everything that we do.

'More importantly, we have come to a point where we now have both a technology push and a consumer pull for wearable technology products and applications.

'We believe that a strategic partnership with a leading player like Google is the ideal platform for developing a new way forward in our industry and answering the evolving needs of consumers on a global scale.'

Google has come under fire for the unfashionable look of Glass, although has developed its own frames for the system which allow prescription lenses.

'Luxottica has built an impressive history over the last 50 years designing, manufacturing and distributing some of the most successful and well-known brands in eyewear today,' said Google Vice President and head of Google X Astro Teller.

'We are thrilled to be partnering with them as we look to push Glass and the broader industry forward into the emerging smart eyewear market.'

'The first collection generated by this partnership will combine high-end technology with avant-garde design offering the best in style, quality and performance,' the firm's say.

Stylish: The frames will be available in a range of colors and will work with prescription glasses

Those who currently own the device paid $1,500 to be part of the development process, exchanging ideas on improvements to the design and function in return for the coveted device.

With the release of the second-generation, those already enrolled in the Google Explorer program  will be able to 'invite' three of their friends to the scheme, according to ABC News.

Reaction to the new design was mixed, with some critics saying changes to the device looked bulky.

However, the updates were welcomed by those who have a first-generation device, with comments on its Google + page commenting that the changes would improve user experience.

One owner, Dawn Martin, commented: 'My glass has been useless for phone calls and nav because I can't hear it well enough ... yay for updates/upgrades!'

Improved: The slightly bulkier design comes with a detachable ear piece to improve commands

Upgrade: Big Bang Theory's Kunal Nayyar wearing the Google Glass at the Emmys in September. Those with the earlier design will be able to swap their old device for the new one

Another fan of the device, Jeremiah Townsend, commented: 'Can't wait ... now that we'll be able to use them with prescription glasses, they'll be glued to my face.'﻿

Others however complained that the device was still not widely available.

However, the Google Explorer program has been praised for using a clever marketing model where people buy a product at its developmental stage so they can contribute to shaping its design.

'In essence Google has crowdfunded Glass and has shown big business how crowdfunding can be done. In essence it is a giant kickstarter campaign in all but name,' according to Forbes. 

It estimated that Google would have earned about $50 million during the development phase as well as enhancing the desirability of the product.

@highlight

Luxottica will work with Google to create glasses using the technology

@highlight

Will include sports glasses and 'luxury' eyewear

@highlight

Google already offers prescription glasses for the system