By 
Associated Press

PUBLISHED:

16:17 EST, 15 November 2013


| 

UPDATED:

14:43 EST, 16 November 2013

Macy's is moving rocker Joan Jett off the South Dakota tourism float in its Thanksgiving Day parade after ranchers complained about having a vegetarian and animal rights advocate representing their state.

Orlando Veras, Macy's parade spokesman, said today that Jett and her band, the Blackhearts, will be moved to another float.

Veras said that the annual parade in New York City is about entertainment, not advocacy, and that Macy's was making the change 'to prevent any further distraction from our entertainment mission.'

Joan Jett (seen in Baltimore in April) will no longer be park of the Macy's tourism float in their Thanksgiving Parade in South Dakota

'The Parade has never taken on, promoted or otherwise engaged in social commentary, political debate, or other forms of advocacy, no matter how worthy,' Veras said in a statement.

'Macy's intention is only to provide a range of entertaining elements and performers free of endorsements or agendas.'

A new performer for the South Dakota float will be announced later, Veras said.

Some South Dakota farmers and ranchers voiced concern about the choice to put Jett on the float because she is a supporter of People for the Ethical Treatment of Animals, which promotes a vegetarian diet and criticizes livestock production practices.

South Dakota Cattlemen's Association President Cory Eich, who farms and ranches near Canova in eastern South Dakota, said earlier this week that he thinks it was a mistake to select Jett because her stands don't mesh with a state where the cattle industry makes up a huge part of the economy.

Dan Mathews, PETA's senior vice president, said Friday to Associated Press that he's happy with the publicity generated by the controversy.

Macy's Thanksgiving Day Parade (seen in New York) wants to keep its entertainment value and not be distracted by other issues

'Thanks to South Dakota's reactionary ranchers, people across the country have learned why Joan Jett supports PETA,' Mathews said.

'The meat trade can't stand any scrutiny of its cruelty,' he said.

South Dakota Tourism Secretary Jim Hagen has said that many people mistakenly assumed state officials selected Jett to appear on the float.

None of the artists the state proposed were available or willing to appear in the parade, so Macy's selected Joan Jett and the Blackhearts, he said.

Kristen Foster, a spokeswoman for Jett said earlier this week that Jett has played in South Dakota countless times and is a fan of the state.

Jett just accepted a gracious offer to appear on South Dakota's float, Foster said.

The state pays $175,000 to support the Macy's Thanksgiving Day Parade and have a float in the event, and $5,000 of that goes to pay expenses for the artist on the float, officials have said.

The South Dakota float, which has appeared each year since 2010, features Mount Rushmore, the Badlands, the Black Hills and more.

Don McLean, the singer of American Pie, appeared on the float last year. Previous years' entries featured Neil Diamond and Mannheim Steamroller.

More than 3 million people are expected to watch the parade on the streets of New York, with more than 50 million watching the event on television nationwide.

@highlight

Ranchers had complained about having a vegetarian and animal rights advocate representing their state

@highlight

Jett and her band will be moved to another float

@highlight

Macy's wants to 'prevent any further distraction from our entertainment mission', they said