By 
Stuart Woledge

PUBLISHED:

10:53 EST, 17 September 2013


| 

UPDATED:

10:26 EST, 18 September 2013

Rising 175 metres into the Mississauga skyline, these two blocks of high rise apartments dubbed the 'Marilyn Monroe of architectural world' have been named Skyscraper of the Year.

So called because their hourglass figure bears a similar shape to that of the legendary Hollywood film star, each of the flats in The Absolute World Towers, near Toronto in Canada, are said to be unique.

Designed by 6 MAD and Burka Architects they twist 209 degrees from their base to the top floor, 56 storeys up.

Shapely: Rising 175 metres into the Canadian skyline, they have been likened to Marilyn Monroe

Absolute winner: The towers in Mississauga twist 209 from their base to the top, 56 floors up

Awarding the title Emporis Skyscraper of the Year, a panel of experts said: 'The way the 
two structures twist organically by up to eight degrees per floor is not
just a superb technical achievement, but also a refreshing change to 
the set forms of high-rise routine.'

Second place went to Al Bahr Towers in Abu Dhabi, with the its 145-metre high towers, complete with translucent facade which runs off power generated by solar energy.

The Burj Qatar, a 238-metre high, £80 million structure, took third place in the Emporis awards.

Designed by French architect Jean Nouvel, the Burj Qatar is topped by a dome with a spire that acts as a lightning conductor.

Runner-up: Al Bahr Towers in Abu Dhabi was pipped at the post to first placer by Absolute Towers

Electric: The Burj Qatar, finished with a lightening rod, was named the third best skyscraper of 2012

There were no spots in the top ten for new buildings opened in Britain, but the UK played an important role in architecture.

The Bow, a 236-metre high skyscraper in Calgary, came fourth in the list and was designed by London-based Foster and Partners.

Making up the top five was House on Mosfilmovskaya 1, in Moscow, with the rhomboid base turning slightly anti-clockwise from floor to floor, creating the its twisted appearance.

The Bow: No British buildings made onto the list, but this one in Calgary, Canada, was designed by a UK firm

Tall storey: With 71 floors over 310 metres, Pearl River Tower in China, was the highest on the list

A credit to the architect: UniCredit Tower in Milan was named in eighth spot by the panel of judges

The tallest building on the list was the Pearl River Tower, in Guangzhou, China, with the 71-storey scraper 310-metres high.

It is the 68th tallest skyscraper in the world, significantly behind the Burj Khalifa in Dubai, which has a height of 828 metres.

Absolute World Towers is the second building in Canada to win the Emporis Skyscraper Award following Vancouver's One Wall Centre which took the prize in 2001.

The two towers were selected by an international jury of experts from more than 300 skyscrapers at least 100 metres tall that were completed last year.

Despite being the home of the skyscraper and boasting last year's winner in Manhattan's Eight Spruce Street, there were no places in the top ten for the USA.

Dizzy heights: Renaissance Barcelona Fira Hotel (left) and House on Mosfilmovskaya in Moscow (right)

Grand designs: Dumankaya Ikon in Istanbul (left) and Zhengzhou Greenland Plaza in China (right)

@highlight

The shapely Absolute World Towers was named Skyscraper of the Year

@highlight

The buildings in Mississauga saw off competition from 300 entries

@highlight

It is the second time a skyscraper in Canada has won the coveted title