The personal data and private online conversations that the National Security Administration is accused of mining could be stashed in a one million square-foot, $1.9 billion facility in the Utah Valley.

Concerns over what the government will store at the Utah Data Center have been reinvigorated by the revelation that U.S. intelligence agencies have been 
extracting audio, video, photos, e-mails, documents and other 
information to track people's movements and contacts.

Apple, Facebook, Microsoft, Google, Yahoo, 
YouTube, Skype, AOL and the lesser known Internet company PalTalk are all involved with the PRISM program, which the government insists is for national security.

The Utah Data Center which is being constructed on Camp Williams on the Salt Lake-Utah County line will be completed in October - but officials have been tight-lipped about what will be stored there.

More:The Utah Data Center, near Bluffdale, was rumored to be one of the sites where personal data extracted by the NSA was stored

Storage: An aerial photograph shows the center

Stash: The government has been tight-lipped about what will be stored in the center's four 'data halls'

Plans released by the U.S. Army Corps of Engineers, which is handling the construction, show the center will have four 'data halls' to store information and two substations to power the facility.

The spy center is being built at 
an estimated cost of $1.9 billion, and is expected to employ 100 to 200 
permanent employees after its completion. The plans note they must all be U.S. citizens.

Despite the boom for the local economy, the American Civil Liberties Union of Utah has expressed their fears over what will be stored at the center.

'We're mining data, we're gathering data and it's all done secretly,' ACLU of Utah director Karen McCreary told Fox13. 'We don't even know what's going on.'

Plans: Sketches released by Army engineers show the massive center, which is believed to cost $1.7 billion

Will your information be in there? Another drawing shows halls where the data will be kept

Site: The center overlooks the Utah Valley and will employ up to 200 people when it is complete

'When the NSA facility in Utah was announced, local officials praised it for the jobs it would bring,' Libertas director Connor Boyack added.

'As Americans are now learning, those jobs entail harvesting the data generated by innocent Americans not suspected of any crime, in contradiction to the Fourth Amendment.'

The fears come as The Washington Post reported that for the past six years, U.S. intelligence agencies have been extracting personal information from across the country.

The PRISM program was launched in 2007 with the blessing of special federal judges under the Foreign Intelligence Surveillance Act. The Post said that several members of the U.S. Congress were made aware of the classified data-gathering program, but were sworn to secrecy.

Mystery: A close-up section of NSA's Utah Data Center is shown in Bluffdale in July

Powerhouse: These images were released last year as it emerged the government is secretly collecting the telephone records of millions of Verizon customers, as well as data from companies including Facebook and Google

PRISM has been described by NSA officials
 'as the most prolific contributor to the president's Daily Brief' and 
the 'leading source of raw material', the Post reported.

On Friday, President Obama delivered a passionate defense of national security programs that secretly acquire information about Americans' phone calls, saying criticism of them is all 'hype.'

'My assessment and my team's assessment was that [the programs] help us prevent terrorist attacks and that the modest encroachments on privacy that are involved in getting phone numbers or duration [of calls] without a name attached... It was worth us doing.'

In practice, if collection managers in 
the NSA's Special Source Operation Group, which manages PRISM, have 
suspicion that their target is a foreign national engaged in terrorism 
or a spy, they move ahead to draw in all the data which would often net in information on the suspect's contacts.

President Obama has maintained that data mining 'was worth us doing' to halt national security threats

Bombshell: A leaked powerpoint slide shows how the NSA and FBI have been extracting audio, video, photos, e-mails, documents and other data from large Silicon Valley companies for six years

'I think it’s important to understand
 that you can’t have 100 percent security and then have 100 percent 
privacy and zero inconvenience,' Obama said. 'We’re going to have to 
make some choices as a society.'

Obama said the PRISM program does not
 involve monitoring the email content of U.S. citizens or anyone living 
in the U.S., and he repeatedly stated that both programs - the phone 
spying and PRISM - have been approved by Congress.

'You can complain about "big brother"
 and how this is a potential program run amuck,' Obama added, 'but when 
you actually look at the details, then I think we've stuck the right 
balance.'

The
 Post noted that the tech companies are knowingly taking part in PRISM, 
but The Guardian, which also received a leaked NSA report, reported than
 all nine pleaded ignorance of the program.

The companies denied any knowledge of the program, with spokespeople saying they had not even heard of it.

@highlight

Government will complete its data storing facility in Utah this October

@highlight

Concerns about what personal information will be stored there as it emerged the government has been extracting data from big companies