Street cleaning budgets have been slashed in many parts of the country, fuelling fears about the worsening blight of litter.

In some local authorities, spending on clearing rubbish is down by more than 80 per cent, figures out today show.

Freedom of information requests to all 326 councils in England show there has been a 16 per cent cut overall in real terms since 2010.

Scroll down for video 

In some local authorities, spending on clearing rubbish is down by more than 80 per cent, figures have shown

In the worst-affected regions, spending on keeping streets clean has dropped by almost a third. Some individual councils, however, have cut budgets by more than 80 per cent.

Last week, a report suggested that living in a neighbourhood scattered with rubbish can hit property prices by almost 12 per cent. The study also indicated a link between high levels of litter and crime.

The survey of councils was conducted by Hilary Benn, shadow communities and local government secretary.

He said: 'Clean streets help to engender a sense of civic pride but this is being undermined by reductions to the very frontline services that David Cameron said he would protect.

'Labour would devolve power and money to local areas and work with them to find savings through collaboration, allowing them to protect the frontline services residents expect and rely on.'

Last week, a report suggested that living in a neighbourhood scattered with rubbish can hit property prices by almost 12 per cent

Today, Labour will promise to carry out the biggest devolution of economic power and funding to English city and county regions for generations if it returns to power in May.

Shadow chancellor Ed Balls will set out plans to devolve £30billion over five years, including funding for housing, transport, business support, employment and adult skills.

The party would also allow city and county regions which unite in combined authorities to keep 100 per cent of extra business rates revenue generated by additional growth.

Today's survey of local authorities shows that the deepest cuts in street cleaning budgets have been in the West Midlands, which has seen a 30 per cent real terms drop since 2010.

Second was the South West, with spending down 28 per cent followed by the North East, where the cut was 27 per cent.

The South East had the smallest reduction – 6 per cent – while spending in the East of England, was down 9 per cent.

Freedom of information requests to all 326 councils in England show there has been a 16 per cent cut overall in real terms since 2010

The Keep Britain Tidy campaign said suburban homes with a litter problem could be worth 2.7 per cent to 11.8 per cent less than they otherwise would be.

The average home in England and Wales is worth £176,581 so a serious litter problem could take £20,837 off the value. For a £500,000 property, the loss in value could be £58,823.

Overflowing wheelie bins on pavements outside houses can also affect the value of properties, according to the research.

Tim Burns, from Keep Britain Tidy, said: 'When people are looking to buy a home, they want to feel they are buying in a nice place, where the community is cared for.

'There's a lot of evidence to show in a more littered environment, people are less helpful to each other. Crime breeds litter and it might be that litter breeds crime. The knock-on is people don't want to move there and prices are reduced. If you clean up the neighbourhood, it can improve your bank balance.'

 

@highlight

There has been a 16 per cent cut overall in real terms in England since 2010

@highlight

Some individual councils, though, cut budgets by more than 80 per cent

@highlight

Last week study indicated a link between high levels of litter and crime  