By
Chris Pleasance

A drugs gang who made more than £2.3million in a massive country-wide heroin racket have been ordered to pay back just £24.

Mark Gale, Ivan Wood, Craig Corrigan, John Pogue, Ryan Morgan and Steven Blundell were all found guilty of conspiracy to supply class A drugs in April last year.

But at a proceeds of crime act hearing, a judge at Exeter Crown Court was told the men had 'spent all the money' with the exception of Morgan, who had just £20 in his bank account.

A gang of heroin smugglers who made £2.3million have been fined just £24 after a judge was told they had 'spent all their money'. Steven Blundell, 35 (left), was not at the proceeds of crime hearing as he is currently on the run in Spain, while Craig Corrigan (right) was fined a nominal £1

Drug courier Pogue (pictured) was also fined £1, as were fellow criminals Mark Gale and Ivan Wood. Another gang member, Ryan Morgan, was fined £20 after the court heard that was all he had left in his bank account

As a result, the court reclaimed just £24 after taking Morgan's money, and fining Wood, Corrigan, Gale and Pogue a nominal £1 each.

That is despite the fact that the 
Proceeds of Crime Act (POCA) confiscation proceedings could have cost 
the taxpayer £20,000 per defendant, if not more.

Fellow criminal Blundell, 35, was not at the hearing as he went went on the run before being sentenced and is now thought to be in Spain.

Before his arrest, Blundell lived the high life with luxury cars and designer clothes as he oversaw an operation that channelled heroin from Merseyside to the South West.

A damning audit report earlier this year revealed just 26p for every £100 generated by criminals is recovered through POCA legislation.

The men were all arrested last year after detectives in Operation Raby established that the heroin was being transported from Liverpool to addresses in Devon before being distributed across the South West.

During Blundell's trial at Exeter Crown Court, jurors were told how he lived the high-life with a fleet of expensive cars including a Porsche, and Audi, and a collection of BMWs and 4x4s

Police said Steven Blundell had a fleet of luxury cars including a Porsche Boxster, Audis, BMWs and Volkswagen 4x4s.

He also spent £11,000 in cash on foreign travel in a three-month period, but had no obvious income or employment.

He involved his cousins Paul Blundell, 24, and Morgan, 29, as well as drug courier Pogue, 24, all of Halewood, Liverpool, in the operation. The gang got sentences ranging from two to nine years.

DC Jason Braund from Devon and Cornwall Police said: 'Unfortunately these defendants had no available assets and therefore were ordered to pay nominal amounts of £1 each, with the exception of Morgan who had access to £20.

'It does, however, come with a warning that these individuals can be re-visited in the future should they come into wealth or any assets are later identified, as we can take it from them.'

An investigation into the finances of Blundell is likely to be launched when he is traced and  extradited back to Britain.

He is set to be sentenced in his absence next month.

 

@highlight

Six gangsters jailed for conspiracy to supply class A drugs in April last year

@highlight

Gang made £2.3million in country-wide heroin dealing operation

@highlight

Steven Blundell, 35, owned a  fleet of cars including Porsche and Audi

@highlight

But today they were fined £24 after court heard they had spent the cash

@highlight

Ryan Morgan, 29, had last £20 in his bank account confiscated by judge

@highlight

Mark Gale, Ivan Wood, Craig Corrigan and John Pogue fined £1 each

@highlight

Blundell was not at the hearing as he is believed to be on the run in Spain