Britain's first bus powered by human waste has taken to the streets.

The 40-seater 'Bio-Bus' is fuelled by biomethane gas, generated by the treatment of sewage and food waste at a processing plant in the south west. 

And a single tank of the gas - produced using the typical annual waste of just five people - is enough to power the vehicle for 190 miles (305km).

Scroll down for video 

An environmentally-friendly bus that developers say will improve air quality runs on a rather unlikely fuel - human poo, among other sewage. Commuters today boarded the first bus in the UK to be powered by this waste from local residents

Bosses said the groundbreaking vehicle will improve air quality, and proves that their is value in human faeces.

Today's maiden voyage saw the first passengers travel on the route from Bristol Airport to Bath, Somerset -  a distance of around 20 miles (32km).

Faeces could soon be used to power a future generation of mobile phones, scientists from the University of East Anglia have claimed.

The researchers discovered a natural process that occurs within the bacteria found in poo, that could help improve ‘bio batteries’.

It is hoped the discovery could produce energy for portable technology, such as smartphones, mobiles, tablets and laptops. 

The gas is being produced at a Wessex Water sewerage plant, run by energy firm GENeco.

Mohammed Saddiq, director of GENeco, told Bristol Post: 'Gas powered vehicles have an important role to play in improving air quality in UK cities.

'But the Bio-Bus goes further than that and is actually powered by people living in the local area, including quite possibly those on the bus itself.'

The annual waste of a bus-load of people would provide enough power for a return journey from Land's End to John O'Groats, while producing fewer emissions than a diesel engine.

Charlotte Morton, chief executive of eco-friendly organisation Anaerobic Digestion and Bioresources Association, said: 'The bus also clearly shows that human poo and our wasted food are valuable resources.

'Food which is unsuitable for human consumption should be separately collected and recycled through anaerobic digestion into green gas and biofertilisers, not wasted in landfill sites or incinerators.'

The 40-seater 'Bio-Bus', pictured here preparing for its maiden trip from Bristol to Bath, runs on gas generated by the treatment of sewage and food waste at a nearby processing plant. It comes complete with an interesting design on the side of the vehicle

Bio-fuel promoters said that the bus, which is expected to ferry up to 10,000 passengers a month, shows the 'value' of waste and heralds a more sustainable future for public transport

GENeco this week also became the first company to start delivering gas generated from human waste directly to 8,300 homes by the national grid.

The waste plant in Avonmouth, Bristol, treats 75 million cubic metres of sewage waste, and 35,000 tonnes of food waste, every year.

Using anaerobic digestion - the process of using bacteria to break down substances in the absence of oxygen - the plant is able to produce 17 million tonnes of biomethane a year.

The annual waste of a bus-load of people would provide enough power for a return journey from Land's End to John O'Groats while producing fewer emissions than a diesel engine

Today's maiden voyage saw the first passengers travel on the route from Bristol Airport to Bath, Somerset. Charlotte Morton of Anaerobic Digestion and Bioresources Association, said: 'The bus clearly shows that human poo and our wasted food are valuable resources'

@highlight

Bus powered by human waste takes maiden journey from Bath to Bristol

@highlight

The Bio-Bus is fuelled by biomethane gas from sewage and food waste 

@highlight

A single tank of 'gas' is the equivalent annual waste from five people

@highlight

But the bus produces less emissions than those from a diesel engine 

@highlight

It's hoped the bus could herald more sustainable fuels for travel

@highlight

'The bus also clearly shows that human poo and our wasted food are valuable resources,' said one expert