By
Associated Press
and MailOnline Reporter

Thrill-seeking surfers hit southern California's beaches on Tuesday and Wednesday, riding the big waves churned up by Hurricane Marie.

However, the hurricane did prove more troublesome for beachfront homeowners who became inundated with saltwater, and the storm-roiled Pacific knocked out a piling at Malibu Pier.

But the attitude was much more cheerful at hotspots like The Wedge in Newport Beach, where crowds egged on bodysurfers brave enough to take on the big surf.  Lifeguards on both sea and shore kept a watchful eye on the crowd.

The bold also flocked to Surfrider beach in Malibu, where a surfer died Tuesday after being pulled from the water. It was not clear whether the death was related to the surf or a medical condition. 

'It's very hectic, stormy and dangerous, really,' said Scott Bosco, 26, who surfed Seal Beach for an hour but only managed to catch two waves because of the roughness. 'You live for days like this. I'm definitely coming back later after school.'

Scroll down for video 

A surfer flies off a wave at the Wedge in Newport Beach, California on Wednesday as Hurricane Marie churns up a swell off shore. Several surfers and bodysurfers came out on Tuesday and Wednesday to experience the large waves 

One surfer was pulled dead out of the water on Tuesday, but it was immediately clear if it was related to the surf or a medical condition. Above, A bogie-boarder flies over a wave a surfer rides underneath a wave at the wedge in Newport Beach, Calif

'It's very hectic, stormy and dangerous, really,' said Scott Bosco, 26, who surfed Seal Beach for an hour but only managed to catch two waves because of the roughness. 'You live for days like this. I'm definitely coming back later after school.' Above, a bogie-boarder rides a wave in Newport Beach

Lifeguards were only letting experienced surfers and body-boarders into the water on Tuesday and Wednesday.  Above, A surfer cuts through a wave at Venice Beach

In this Tuesday photo, a surfer falls from a wave at El Porto in Manhattan Beach, California. The National Weather Service said beaches stretching 100 miles up the Southern California coast would see large waves and rip currents. Swimmers and surfers were urged to be aware of the dangerous conditions

A body surfer swims through a wave at Seal Beach on Tuesday. A large southerly swell was expected to produce large waves, rip currents and strong longshore currents in Los Angeles and Ventura counties through Thursday, according to the National Weather Service

Huge crowds came out to watch the surfers take on the big waves this week. Above, the group that gathered to watch from a safe distance at Newport Beach on Tuesday

'We are pretty careful about who we let in the water,' Lifeguard Capt. Boyd Mickley told KCAL-TV. 'We look everyone over, talk to them briefly and find out what their experience level is. And we will suggest strongly that today's not the day for them to go in.' Above, beachgoers watch large waves crash on the shore at Seal Beach on Tuesday 

 At the Wedge, a huge crowd watched surfers take on ferocious waves for a second day. Lifeguards dove into the surf there as well to save a person with the help of a rescue boat.

Lifeguards sought to keep anyone out of the water who did not have strong experience.

'We are pretty careful about who we let in the water,' Lifeguard Capt. Boyd Mickley told KCAL-TV. 'We look everyone over, talk to them briefly and find out what their experience level is. And we will suggest strongly that today's not the day for them to go in.'

The towering waves and rip currents were being produced by swells generated by Hurricane Marie in the Pacific Ocean about 800 miles west of the southern tip of Mexico's Baja California peninsula. Although Marie will likely weaken to tropical storm levels, life-threatening water conditions were expected to continue through Thursday.

A group of surfers wait for the next swell of waves generated out in the Pacific Ocean by Hurricane Marie, near Solana Beach, California on Wednesday

A bogie boarder and a surfer ride a wave at the wedge, on Wednesday

A surfer rides a wave at the wedge in Newport Beach on Wednesday. Southern California beachgoers experienced much higher than normal surf 

A large crowd gathers to watch surfers and body surfer ride waves at the wedge on Wednesday in Newport Beach

Surfers and body borders come out of the ocean after riding big waves off the coast of Newport Beach, California on Wednesday

Along the long arc of Southern California coastline, high surf warnings were posted for Los Angeles County south through Orange County, with lesser beach-hazard advisories down to San Diego and as far northwest as San Luis Obispo County on the state's central coast. The fiercest surf primarily affected south-facing beaches.

At one point in Seal Beach, a lifeguard climbed from the beach to the deck of the pier, sprinted to the end and dove in to rescue a swimmer. That man was successfully brought ashore well down the beach. Orange County Fire Authority Capt. Steve Concialdi said the man was OK. 

Residents of about four blocks of homes along Seal Beach, south of Los Angeles, swept seawater from ground-floor rooms after flooding overnight, and bulldozers reinforced a 6-foot-tall sand berm hastily built to protect shoreline structures.

A lifeguard tower knocked over by high tides sits on the beach as people stand on the sand wall on Wednesday.

Hector Brown sweeps out his aunt and uncle's house in Seal Beach on Wednesday. The entire house and garage was flooded by a foot of water and muddy sand late Tuesday night after low-lying streets in the Southern California coastal community was inundated by a surge of rising seawater brought on by Hurricane Marie

Resident Jerry Rootlieb points to the high water line on his gate Wednesday,  after heavy flooding in Seal Beach

The berm - a measure normally not needed until winter storms - and the use of pumps prevented more water intrusion during the morning high tide and another test was expected close to midnight.

Along the shoreline, firefighters went door to door, dropping off more sandbags for residents and surveying damage after the initial surge that arrived late Tuesday and topped a 2 1/2 foot beach wall, causing flooding in or around the first row of homes. About 100 residences were affected, Concialdi said.

'This is our worst summer storm and I've been here 42 years,' said resident Jerry Rootlieb, who was sweeping out his home on Wednesday.

In this Tuesday photo, a woman drives through a flooded street after high tide and large waves caused heavy flooding in Seal Beach

Residents sweep out flood water from a home in Seal Beach on Tuesday after high tide and large waves caused heavy flooding

Jaime and Blanca Brown's seaside home had a foot of seawater throughout the home, garage and carport. Soaked floor tiles in the hallway were buckled, and a dirty line marked the high point of water in almost every room and the garage. Sodden mattresses and carpets were stacked outside.

'What can you do, man? We are just trying to win the war and we're just bringing out water. Water, water, water,' said the Browns' nephew, Hector Brown.

The Malibu Pier was closed after seven pilings were knocked loose. State Parks Department official Craig Sap said rangers noticed three more pilings missing on Wednesday. The pier's structural integrity remained sound because of redundancy but people were asked to stay away, he said.

A previously closed pier at Port Hueneme in Ventura County also lost pilings.

Catalina Express, which ferries tourists between Santa Catalina Island and the mainland, stopped its morning runs because of the heavy seas but said it hoped to run an afternoon boat from Avalon to Long Beach

Residents carry sandbags to protect homes after high a tide and large waves caused heavy flooding in Seal Beach on Tuesday

This image provided by NASA shows Hurricane Marie taken from the International Space Station on Tuesday

@highlight

Hurricane Marie is currently hitting off the coast of Mexico, causing a giant swell to hit Southern California

@highlight

 One surfer died in the surf on Tuesday, but it wasn't immediately clear if it was related to the waves or a medical condition