By 
Daily Mail Reporter and Associated Press

PUBLISHED:

10:06 EST, 8 October 2013


| 

UPDATED:

02:07 EST, 9 October 2013

Middle class families today resemble the poorest Americans from the 1970s, former President Jimmy Carter has claimed. 

Carter, 89, said Monday that growing economic inequality in the United States has left middle class families financially unstable and eroded their economic security. 

'Even in one of the wealthiest parts of the world there is a 
great deal of foreclosures and now a great deal of people who are 
fortunate to own their own houses owe more on them than the houses are 
worth in the present market, and that's all changed in the last eight 
years,' Carter said during an exclusive interview with The Associated 
Press.

Scroll down for video

Interview: Jimmy Carter says the middle class have spiraled into economic insecurity in the last eight years - on par with the poor when he was president

'The disparity between rich people and 
poor people in America has increased dramatically since when we 
started. The middle class has become more like poor people 
than they were 30 years ago. So I don't think it's getting any better.'

Carter offered his assessment of the nation's economic challenges Monday at a Habitat for Humanity construction site in Oakland, California - the first of five cities he and wife Rosalynn plan to visit this week to commemorate their three-decade alliance with the international nonprofit that promotes and builds affordable housing.

The recent economic downturn revealed that families living in even comparatively well-off, but expensive regions like the San Francisco Bay Area are economically insecure, he said.

Taking a break from framing windows at a new 12-unit town house development in a section of East Oakland where Habitat already has built or repaired 115 homes, the 89-year-old former Democratic president said the federal government is investing less in affordable housing at a time of greater need.

Carter said the poor were as well off when he was president as the middle class are now

Carter blamed years of tax breaks for the wealthy, a minimum wage untethered from the inflation rate and electoral districts drawn to maximize political polarization. He said those factors have reduced the quality of life for all but a small fraction of Americans and imperiled the nation's standing as 'a real superpower,' he said.

'Equity of taxation and treating the middle class with a great deal of attention, providing funding for people in true need, like for affordable housing, those are the sort of things that would pay rich dividends for Americans no matter what kind of income they have,' said Carter, looking relaxed in a baseball cap, blue jeans and white sneakers.

'The richest people in America would be better off if everybody lived in a decent home and had a chance to pay for it, and if everyone had enough income even if they had a daily job to be good buyers for the products that are produced.'

Habitat for Humanity was founded in Georgia, the home state of the Carters. They first joined a Habitat for Humanity work site in 1984 in New York and have spent a week every year working on construction sites in the U.S. and abroad.

On Tuesday, the former president and first lady are scheduled to help renovate homes in a section of Silicon Valley that has remained immune to the wealth generated by the high-tech industry.

After that, they intend to travel to Denver, Colorado, New York and Union Beach, New Jersey, where they will help rebuild homes wiped out by Hurricane Sandy.

Carter continues to help build houses with Habitat for Humanity - despite being 89 years old

@highlight

Former President blames tax breaks for the wealthy, a stagnant minimum wage and political polarization for the slippage of middle class

@highlight

Claims middle class Americans are as financially shaky as the poor were when he was president more than three decades ago