By
Richard Spillett

A Second World War gun tower has sold for an astonishing £200,000 - despite having no running water or toilet.

The tiny seaside property, last used as an artist's gallery, has no parking and is only ten foot by ten foot in size.

But that didn't stop potential buyers queuing up to hand over its six-figure asking price.

The seafront property (circled) commanded a large asking price despite being only ten foot by ten foot in size

Estate agent Katherine Edwards says the property attracted interest from around the country

The Gun House on Marine Parade, Shaldon, near Newton Abbot, Devon, is the latest unusual property to attract a huge asking price in the highly sought-after seaside village.

The one up-one down former wartime tower has only one real luxury - the use of an outside tap.

But buyers were attracted by planning permission to convert the tower into a one-bedroom holiday home for tourists visiting the area.

Estate agent Katherine Edwards said: 'It is the location that sold it and the views are amazing.

'We got a lot of interest from so many people up and down the country from people who wanted to use it as a second home or holiday let.

'It is a completely individual property which has a lot of character and will be used as a holiday home.'

The property, once an artist's studio, has no running water, toilet or parking

It is thought the building, with has good views of the nearby coastline, will be converted into a one-bedroom holiday home for tourists

The white-walled property was constructed during the war as part of the Shaldon coastal defences.

It was originally used as a guard room topped with a searchlight and small gun used to protect the mouth of the River Teign.

It does have a power supply and a small outside area which, if carefully landscaped, could provide space for a small table and chairs.

Shaldon is a highly desirable seaside village which attracts top prices. The five luxury beach huts on the nearby Strand were sold for up to £250,000 each in 2011.

Ms Edwards added: 'Shaldon continues to be popular. It is right on the waterside and the village has a lovely community feel.

'It is starting to get a foodie reputation too with lots of restaurants and cafes and everyone says hello, even if they don’t know you. That is what people like.'

Homes in the seaside village of Shaldon, Devon often command huge prices. A beach hut in the area sold for £250,000 in 2011

@highlight

Ten foot wide property, part of wartime sea defences, only has outside tap

@highlight

Interest generated by building's location in upmarket Shaldon, Devon

@highlight

Estate agents say the seaside building has beautiful views of the coast

@highlight

Buyers attracted by potential to turn it into a one-bedroom holiday home