Dylan Hartley is bracing himself for bad news. The euphoria generated by an Aviva Premiership title triumph is in danger of being shattered by an almighty comedown this week.

The grim reality of England’s two-tier tour is becoming apparent and players are coming to terms with the consequences of an administrative shambles far beyond their control. Arguably the most brutal selection of Stuart Lancaster’s tenure looms.

There are those who performed with distinction at Eden Park on Saturday, as the depleted visitors came agonisingly close to shocking the All Blacks in the first Test.

Fighting for his place: Dylan Hartley runs with the ball during the England training session on Monday

Men such as Freddie Burns, Kyle Eastmond and James Haskell are likely to be ‘rewarded’ for their sterling efforts by being removed from England’s starting XV to make way for some influential reinforcements.

The other category contains those players who arrived here late having taken part in the Premiership final.

Hartley may be among that number. The Saints captain was in jubilant mood winning at Twickenham, but now the occasion may cost him the England No 2 shirt.

Training: Danny Care put through his paces ahead of Saturday's second showdown against New Zealand

Chase: Henry Thomas runs with the ball during the training session at the Onewa Oval on Monday

History: Kyle Sinckler trains with England, who have won just twice on the All Blacks' patch - in 1973 and 2003

Round two: England prepare ahead of the second of their three-test series against the All Blacks

Pass: Billy Twelvetrees back in training after overcoming an ankle injury that ruled him out first time around

Rob Webber of Bath was superb as England’s starting hooker at Eden Park and has a strong chance of being retained for this Saturday’s second Test in Dunedin.

Hartley may have to patiently await the chance to reclaim his lost status and said: ‘You just bide your time and wait for an opportunity and when it comes, you take it. That’s what Rob’s done. He waited for the opportunity and stepped up at the weekend.’

Asked how he would respond, Hartley quipped: ‘Well, I can’t go and take him down in training,’ before adding: ‘Me and Tom Youngs have had it for two years now. You slip up, you give the other guy an opportunity. In my case, slipping up was having to stay behind to play a game.

‘Rob took an opportunity, he played well and I wouldn’t be surprised if we stick with him. There’s the bigger picture as well. It’s good for Tom and myself to know there’s someone else who can step up in that position, it pushes us on. It’s good for the team and with the World Cup we’re going to need three strong hookers.’

Hartley’s refusal to condemn the farcical circumstances is admirable. At least that showpiece final provided him with a high-stakes comeback from a shoulder injury and extra time also worked in his favour.

Close: Owen Farrell hopes to cause another upset - but this time with it ending in England victory

Working hard: Anthony Watson trains ahead of the second clash with New Zealand on Saturday morning

Preparation: Tom Wood (left) and Dylan Hartley (right) return to training after the Premiership final clash

Top team: New Zealand won all 14 of their matches in 2013 but England want to give them a dose of reality

Decisions: Stuart Lancaster must choose his side for the second test against New Zealand

‘The game went for 100 minutes so I got 50 minutes in the end which was good preparation,’ he added. ‘In terms of intensity and being in that environment, a Premiership final with extra time set me up pretty well. I feel fit and strong, the shoulder is not giving me any gyp so I’m ready.’

It may be that the most he is asked to do is take a place among the replacements, a fate which beckons at least one other late arrival who was so impressive during the Six Nations — Billy Vunipola.

Hartley warned that  England must be wary of assuming the cavalry charge of reinforcements will lead to a rise in performance in Dunedin.

‘France toured here last year — they were quite competitive in the first game, their Top 14 finalists turned up and they got humped 30-nil or something,’ he said. ‘So, just because the Premiership finalists are back in, doesn’t mean it will automatically happen. We have to be prepared.’

England’s performance in the first Test was an indication of the strides they are making but there is an acceptance that it is high time to claim a meaningful prize. A series victory over the world champions would fit the bill.

‘We need to get over the line somewhere and here is the perfect place to do it,’ said Hartley. ‘By doing it against the All Blacks, it would be a hell of a statement. We’ve only ever won two Tests here, so we’re literally going to make history if we do it.

‘I think, as a team, we’re being talked about. We’re playing good rugby, we’re picking up good wins.’

Exeter hooker Luke Cowan-Dickie flew home from the tour on Monday night to have treatment on a knee injury.

@highlight

Stuart Lancaster's England train at Onewa Oval ahead of Saturday's game against New Zealand at Forsyth Barr Stadium in Dunedin

@highlight

All Blacks beat a weakened England side 20-15

@highlight

They have won just twice in New Zealand - in 1973 and 2003