By 
Richard Price

PUBLISHED:

19:52 EST, 14 January 2013


| 

UPDATED:

04:04 EST, 15 January 2013

Devoted: Comedian Michael McIntyre and his wife Kitty

Michael McIntyre likes nothing better than to remind his detractors of his humble beginnings as a comic.

Stories abound of counting the pennies, looking for supermarket bargains and running out of petrol because the fuel gauge was broken in his rusty old Austin Metro.

But how things have changed.

His latest tour earned £21 million — making him the most successful stand-up comic in the world.

Gone is the old Metro. Instead, he purrs down the street in a top-of-the-range Jaguar sports car, or his sporty BMW X5 or the latest addition to the family fleet: a Porsche Cayenne.

To his neighbours in well-heeled Hampstead, North London, the 36-year-old comic and his cars have become a familiar sight.

They have witnessed the transformation from scruffy chancer to showbusiness royalty.

For, six years ago, he was on the brink of bankruptcy with debts of £30,000.

He was living in a one-bedroom flat with his wife Kitty and their newborn son.

Money was so tight they used an old microwave oven (found in salvage) as a dining table.

Today, home is a £3.5 million property and his watch is a £10,000 Breitling. Yet for all that, his is still a discreet kind of wealth.

Not for him the ‘look at me’ behaviour of his friend, TV presenter Jonathan Ross. McIntyre favours the subtle yet expensive styles of Prada over more ostentatious designers.

Even the cars, in their own way, are an example of financial prudence. As a child, he always wanted a Ferrari, but despite easily being able to afford one, he has yet buy one.

Indeed, eschewing the normal star’s perk of a chauffeur, he drives himself (the logic being that since he has invested so much money in his cars, he should get maximum value out of them).

When not away on tour — which obliges him to live in hotels for much of the year — he spends time quietly with his family.

Rather than dining at posh West End restaurants, his favourite haunt is his local Café Rouge. His only noticeable extravagances are bouquets of flowers for his wife.

Even his decision to use celebrity personal trainer Matt Roberts — David Cameron is also a client — was pragmatism rather than indulgence.

McIntyre’s father died at 53 from a heart attack, and having inherited a tendency to put on weight, Michael believes he owes it to his children (Lucas, seven, and Oscar, four) to look after his health.

This is a man who still keeps a spreadsheet in which all household expenditure is logged — incoming and outgoing funds balanced to make sure he will never again be on Skid Row.

Big business: Michael McIntyre's latest tour brought in £21million making him the world's most successful stand up comic

Back from the brink: Six years ago Michael McIntyre was in £30,000 of debt and close to bankruptcy

Still, the revenue generated by his success has to go somewhere, and the mortgage on his glorious home — all six bedrooms and three bathrooms of it — was paid off in full within a year.

His company, Buddywaldo, files only abbreviated records to Companies House (wags might suggest his accounts could be a little late this year because the book-keepers are still counting the money), but documents for 2011 show profits of £1.1 million, with £1.6 million cash in the bank.

These figures don’t take into consideration a bumper 18 months, with that record-breaking tour, proceeds from his autobiography (for which he was reportedly paid a £2 million advance) and a lucrative contract with the BBC.

Clearly, McIntyre works hard for his money, and that £21 million has not all gone into his bank account.

It was undoubtedly a gross figure and doesn’t take into account fees for venues, rehearsal costs, the travel and all the wages of all the people who work on the show. Such tours are very expensive to stage.

After years of being on the breadline, he is haunted by the fear that the good times could end tomorrow. This awareness stems from a privileged childhood followed by those tough years in his 20s.

The son of a Canadian comedy producer and one of Kenny Everett’s dancers, he grew up in a large home in Hampstead, not far from where he lives now, and was sent to Merchant Taylors’ private school in Middlesex.

Much loved: After years on the breadline, the hard-working comedian is haunted by the fear that the good times could all end tomorrow

But when his parents split up and his father hit hard times, he was sent to a state school and the house was sold.

Thankfully, the young Michael was sheltered from economic reality by his wealthy and indulgent — yet highly eccentric — Hungarian grandmother. He went to Edinburgh University to read sciences, but dropped out to pursue a career in comedy.

Unfortunately, his grandmother didn’t approve of his choice of girlfriend and cut off his supply of funds. Undeterred, he went on to marry Kitty, despite failing to make it in stand-up.

They borrowed £10,000 for a honeymoon in the Maldives, but he was barely able to half-fill the upstairs room in a pub. Earning a pittance, he must have regretted his previous profligacy.

Forget dreams of a Ferrari. The couple shared a beaten-up old Mini before downgrading to the Austin Metro Princess (top speed 72mph).

Staring into the abyss, McIntyre set up the spreadsheet he still uses — logging every penny earned and spent, and set about hauling the family out of debt.

No stone was left unturned. He trawled supermarkets for bargains, comparing the cost of baked beans.

Most importantly, he finally applied himself seriously to his career, which began to pick up.

He switched agents to one of the biggest in the business — Addison Cresswell, who looks after Jonathan Ross and Jack Dee — who got him out of the clubs and on TV and, in particular, the Royal Variety Performance.

Pragmatic: Michael McIntyre has moved to the same agent as friend Jonathan Ross, left, and enlisted the services of fitness guru Matt Roberts, right to stave off weight gain

Since then, he has worked tirelessly. His income is supplemented by a steady stream of lucrative corporate engagements (he can easily command £30,000 for trotting out an hour of material).

His is very much a one-man show. He never hires writers, preferring to compile his own act, and using his wife as a guinea pig for jokes.

Indeed, his family is a rich source of comic material, and he likes to tell tales of his wife’s love of expensive handbags.

Showman: Michael McIntyre was a judge on Britain's Got Talent alongside Amanda Holden, centre, and David Hasselhoff, right

One routine involves a story about her buying a £500 clutch bag. McIntyre jokes: ‘For £500 I can hire a human being to walk alongside you holding your lipstick, your keys and your phone!’

The gags, though, belie a deep financial caution. Friends say he is genuinely appalled by the price of designer handbags, and that no one in his family other than his adored wife would be allowed to get away with such profligacy.

Nevertheless, one aberration was the new four-wheel-drive Porsche. Perhaps such indulgences can be forgiven in a man who, for all his wealth, retains a self-effacing and modest nature.

For example, a photographer who took a picture of McIntyre in the street recently was met with a broad smile, a trademark giggle and the comic saying: ‘I feel like Madonna, having the paparazzi chasing me.’

But that nagging fear of failure means even though he has the millionaire lifestyle, he cannot slow down. He admits to having what he calls ‘catastrophic thinking’ — an incurable fear of ‘everything going wrong’.

This keeps him touring, despite those weeks away from his family while on the road.

In a recent interview, he publicly apologised to his sons ‘for leaving them so much’, while in the next breath admitting: ‘I can’t retire.’

He has no ambitions to go into acting, but identifies Billy Connolly, 70, as his role model because of the longevity of the Scottish comedian’s career.

Who knows, perhaps when Michael McIntyre reaches 70 himself, he might feel sufficiently confident of financial solvency to buy that long-lusted-after Ferrari. Perhaps.

@highlight

Michael McIntyre's last tour made him the world's most successful comic

@highlight

But he is haunted by the fear that the good times could end tomorrow

@highlight

Just six years ago he was living on the breadline in a one-bedroom flat