By 
Damien Gayle

PUBLISHED:

11:35 EST, 27 February 2013


| 

UPDATED:

03:23 EST, 28 February 2013

A freelance Lego designer has used the popular plastic bricks to build a robot version of Leonardo da Vinci.

Legonardo is Italian teacher and inventor Daniele Benedettelli's fourth-generation drawing machine and is inspired by the famous artist and inventor of (nearly) the same name.

He unveiled the robot this week, with a YouTube video showing the machine drawing his own logo, which is a stylised rendition of Mr Benedetelli himself.

Legonardo: This incredible robot, built entirely from Lego, is able to draw pictures like a real artist

'Ladies and gentlemen, here is LEGONARDO, a portrayer robot,' Mr Benedettelli wrote on his website. 'It is my fourth generation drawing machine.

'It is inspired by the work of 18th Century Swiss watch and automata makers Pierre Jacquet-Droz and Henri Maillardet.

'After reading The Invention of Hugo Cabret, I completely redesigned my portrayer into this shape.

'The name is a tribute to Leonardo Da Vinci, Italian artist and inventor. The drawings are generated by a custom software I wrote, similar to the one used for my first portrayer robot.'

Portrayer: Legonardo is the fourth-generation portrayer robot developed by Italian inventor Daniele Benedettelli

Talented: A video uploaded by Mr Benedettelli shows Legonardo as it draws a copy of the inventor's own logo

According to the biography on his website Mr Benedettelli is a robotics engineer, inventor, high school teacher and freelance Lego designer, with a masters in robotics.

He has since 2007 been a Lego Mindstorms Community Partner, a role developed by the Danish company to get help from expert users.

Legonardo is based on a Lego NXT, a computer-controlled brick which can be programmed via USB to direct robotics.

Using the NXT brick, it can be instructed to draw portraits based on digital photographs of subjects in which the edges have been extracted and the resulting lines turned into a vector-based image.

Expert: Mr Benedettelli, who has a masters in robotics, has since 2007 been a Lego Mindstorms Community Partner, a role developed by the Danish company to get help from expert users

Mr Benedettelli's other robots include JOHNXT, a replica of Johnny 5 robot from Short Circuit movie; the LEGO RUBIK UTOPIA, the first NXT Rubik's cube solving robot ever made; and CYCLOPS, a MINDSTORMS-Android-hybrid humanoid robot that can walk, gesticulate, talk and listen in natural language.

Filmed by Francesco Rossi

@highlight

Drawing robot designed by Italian high school teacher Daniele Benedettelli

@highlight

Mr Benedettelli works as a freelance designer in partnership with Lego

@highlight

The robot is built entirely from the bricks, with a Lego NXT 'brain'