A canoeist managed to paddle to safety after being attacked by a 6ft shark that knocked her into the water off the coast of California.

The woman, who has not been named, told authorities that she was paddling her outrigger canoe about about three miles north of Santa Barbara Harbor, when a shark began biting her boat.

She was thrown into the sea during the attack, the local harbor patrol said, but the woman managed to scramble back into her canoe and paddle it back to shore as the shark swam away.

The woman was pitched into the water during the attack by a 6ft long blue-gray shark (file picture)

The canoeist described the shark as six feet  long and blue-gray in color.

Earlier this month, a surfer was attacked by a shark on the central California coast, prompting the closure of three public beaches in the area controlled by Vandenberg Air Force Base.

The attack occurred around 30 miles north of Santa Barbara, according to a report by the Shark Research Committee.

The surfer suffered lacerations to his knee, and his surfboard was scraped in the attack by a shark measuring 8 to 10 feet in length.

California's last fatal shark attack was in 2012. At the time three beaches were closed for 72 hours

Vandenberg Air Force Base closed Surf, Wall and Minuteman beaches following the attack but they were reopened 72 hours later. 

The report did not specify the type of shark involved but local media described it as a Great White.

Despite intense media attention generated by shark attacks on humans, such incidents are fairly rare along the U.S. Pacific Coast. 

There were 39 reported shark attacks in California from 2001 to 2013 - or 3.25 per year - and five of them resulted in fatalities, according to data tracked by the Florida Museum of Natural History.

The data shows East Coast swimmers are much more likely to wind up the victims of a shark attack, the Los Angeles Times reported.

Ralph Collier, president of the Shark Research Institute, told the newspaper that a person is more likely to die by being struck by a falling coconut than being attacked by a shark.

He said officials have logged 50 to 100 shark attacks per year worldwide since record-keeping began. Of those attacks, only eight to 12 have been fatal.

But with more beachgoers heading to the shore and seals and sea lions - a main food source - on the rise in California, the chances of a shark encounter have jumped, Mr Collier added.

California's last fatal shark attack was in 2012, when a 16-ft great white mauled Francisco Javier Solorio Jr. in front of his friend while he was surfing near Lompoc. 

The 39-year-old suffered a severe wound to his torso and died shortly after. 

Two years earlier, in 2010, another shark attack killed a 19-year-old college student off the same beach at Vandenberg.

Lucas McKaine Ransom  was Boogie Boarding with a friend when he was bitten in the leg by a shark described as being 14 to 20 feet long. 

A map shows the location where a canoeist was attacked while about three miles off the coast of California

The woman was canoeing off the coast of Santa Barbara when the shark appeared and began biting her boat

 

@highlight

Canoeist was paddling outrigger three miles north of Santa Barbara Harbor

@highlight

Shark began biting the canoe and the woman was tipped into the water

@highlight

But she managed to scramble back into canoe and paddle to safety

@highlight

Shark attacks are rare on the Pacific Coast with five fatalities since 2001