From being cut off in the middle of an important call, to finding yourself stranded, everyone has experienced the frustration of their smartphone running out of battery at the most inconvenient moment.

But this could be a thing of the past, as scientists in the US have developed a device that could charge your phone at a distance - even while it’s still in your pocket – so you will never run out of juice again.

The prototype MagMIMO wireless charger can charge an iPhone 4 battery  in  five hours, at a distance of 12 inches (30cm) away.

Running out of phone battery at the most inconvenient moment (illustrated) could become a thing of the past because scientists in the US have developed a device that could charge your phone at a distance, while it’s still in your pocket – so you will never run out of battery again.

While wireless chargers already exist, they require a phone to be placed directly on a charging ‘pad’ so users still have to remember to charge their phones and place them on the device in the right way.

Dina Katabi, of the Massachusetts Institute of Technology (MIT) who is behind the new technology, told New Scientist: ‘In our vision we wanted to have people's phone charge the minute they are sitting next to their desk: they go to a meeting, they come back, the phone starts charging again.’  

The prototype uses a magnetic coil to beam energy to a phone around 12 inches away and it doesn't matter how the phone is positioned – so it could be lying on a desk or in someone’s pocket.

The idea is that coils could one day be placed around homes and offices to top up the batteries of devices detected nearby.

The prototype uses a magnetic coil to beam energy to a phone around 12 inches away and it doesn't matter how the phone is positioned – so it could be lying on a desk or in someone’s pocket. It means that users wouldn't have to use a lead (pictured) and remember to charge devices as they do now

MagMIMO uses magnetic fields to charge a mobile. 

The MagMIMO transmitter has a number of coils to generate a magnetic field.

Coils could one day be installed around the home and offices.

When a phone enters that field its presence is detected.

The transmitter varies the field generated by each coil to focus the magnetic field in the area of the phone. 

‘MagMIMO consumes as much power as existing solutions, yet it can charge a phone remotely without being removed from the user's pocket,’ Dr Katabi and her team wrote in a paper which they shared at the International Conference on Mobile Computing and Networking in Maui, Hawaii.

MagMIMO's transmitter has a number of  coils inside to that generate a magnetic field.

When a phone enters that field, its presence is detected by the transmitter.

It then focuses its energy on the phone that is within range by generating varying frequencies.

This  creates a stronger overall magnetic field that can reach the phone.

In the experiment to demonstrate an early prototype, Dr Katabi connected a small wire coil to an iPhone’s charging point. The magnetic field induced a current in the coil to charge the phone.

Unlike strongly focused Wi-Fi, focused magnetic fields do not have a heating effect on human skin.

The technology could be made available to consumers relatively quickly, because a number of smartphones already have a coil built in. Nokia’s Lumia range as well as several Samsung devices and the LG G3 can be charged using current wireless charging pads.

It could also help speed the take-up of smart watches, which will likely need to be charged daily, such as the Apple Watch, which supports wireless charging.

The wearable devices have little room for batteries, so it would be ideal for a small battery to be frequently recharged from a distance without a wearers having to take them off.

 A Carphone Warehouse spokesman told MailOnline: 'This is a very exciting development and could be the first step in alleviating one of our customers’ biggest bugbears – smartphone battery life.

Imagine a world where handsets charge automatically when in range of these wireless devices – it means phones will run for much longer without ever having to be hard-wired to the mains. It will also make it much easier to use a phone while it is charging, however it may be slower to reach full charge than a wired connection.' 

@highlight

Prototype MagMIMO wireless charger can charge an iPhone 4 battery in five hours, at a distance of 12 inches (30cm) away

@highlight

It was developed by scientists at the Massachusetts Institute of Technology

@highlight

Prototype uses a magnetic coil to beam energy to a phone to recharge it

@highlight

Phone can be positioned in any way and even placed in a pocket

@highlight

In the future, coils could be placed in homes and offices so that phones detected nearby would be automatically recharged