More than a fifth of Britain’s stores will close by 2018 as increasing numbers of customers switch  to internet shopping, experts  warn today.

As a result, swathes of Britain’s high streets may have to be knocked down to make way for housing and other uses as a predicted 62,000 shops go to the wall.

In particularly deprived areas, such as Wales and the North West, up to three in ten stores could close.

Death of the High Street: A predicted 62,000 shops are set to close by 2018, and around 316,000 workers are expected to lose their jobs as Britain switches to online shopping

Around 316,000 workers are expected to lose their jobs in the high street Armageddon, according to a study published today by the Centre for Retail Research.

The independent retail analysis group says the country needs a £320million redevelopment programme to build 20,000 homes on redundant shopping streets and convert disused outlets to doctors’ surgeries, community and leisure centres, nursery schools and offices.

The centre’s founder, Professor Joshua Bamfield, said that Britons are leading the exodus from  bricks-and-mortar stores to making purchases online.

Websites already take 12.7 per cent of  Britain’s retail spending. But this  is expected to surge to at least 22  per cent by 2018.

Major chains such as Tesco, Wickes, Asda and B&Q are opening fewer large stores, and Marks & Spencer is to stop building big outlets in 2016.

New trend: Both customers and retailers turn to online shopping and as a result, thousands of shops are set to close within the next five years

Professor Bamfield’s report, Retail Futures 2018, says the first closures will be pharmacies and health and beauty stores, followed by  those selling music, books, cards, stationery and gifts, as well as DIY outlets.

He added: ‘The total number of UK retail stores will fall by 22 per cent over the next five years from 281,930 to 220,000 in 2018.

‘If no action is taken, store vacancy rates could almost double to 24 per cent. Already this year, 16 major retailers have gone into administration operating 1,985 shops and employing 14,719 staff.

‘By the end of 2018, research predicts that a further 164 companies will go bust, taking 22,600 stores and 140,000 employees with them.’

As customers go online, the cost of running a town centre store has risen far faster than increases in pay and takings.

For example, a small shop on a Midlands high street costs around £10,000 a month to rent.

The equivalent space in a warehouse on the outskirts of Corby, Northamptonshire, achieving the same sales online would cost up to £1,800 a month, with lower business rates and no parking charges for customers.

The amount of consumer spending on the high street  is down from around 50 per cent in 2000 to an estimated 40.2 per cent today.

Last year, the Government hired TV retail expert Mary Portas– the self-styled Queen of Shops – to devise an action plan to revitalise town centres.

Some areas subsequently  won small rejuvenation  grants, but the resulting initiatives were dismissed as merely window dressing.

Key recommendations, such as business rate controls and restrictions on the building of out-of-town supermarkets, were left on the shelf.

Professor Bamfield said: ‘High streets need to combine the enthusiasm generated by Mary Portas with realistic and well-managed plans.

‘The March 2013 budget saw the Government promising to invest £130billion to help people buy property. Our proposal would actually help create new accommodation.’

@highlight

A fifth of Britain's high street shops - 62,000 - are set to close by 2018

@highlight

An estimated 316,000 workers may lose their jobs as a result

@highlight

Up to three in five stores to close in Wales and North West England