By 
Matt West

PUBLISHED:

03:46 EST, 16 June 2013


| 

UPDATED:

06:56 EST, 16 June 2013

A plumber has built what he himself admits is probably the most dangerous bicycle in the world, powered by a homemade jet engine, which can achieve speeds of 50mph.

Colin Furze, who already holds three Guinness World Record titles for his inventions, including the world's fastest mobility scooter, modified his friend's mother's old Rayleigh pushbike.

The 32-year-old, who has nicknamed the modified bicycle Norah after her, attached a jet engine to the back and extended the frame so the rider is supposedly a ‘safe’ distance away from the heat generated by it.

Worlds most dangerous bike: as this picture shows Mr Furze's new jet powered bike is anything but safe

But as the picture below shows neither 
Mr Furze nor his friends are wearing safety clothes or equipment and at 
one point come very close to blowing themselves up.

The British inventor is well known online for his outrageous, and often dangerous stunts.

He
last achieved notoriety when he debuted his gas powered 53mph pram last 
year, shortly after becoming a father for the first time.

The video of him testing that invention, fortunately not with his newborn baby inside the pram, gained over 1.4 million 
views.

Mr Furze also features on Sky TV's Gadget Geeks and gained
his first Guinness world record for making the world's largest bonfire 
in 2006.

He spent four months working on the bicycle, before testing it out in a local airfield.

Jet propelled: the view from the seat of the jet powered bike shows how close the rider is to the exhausts and fuel canister

Dangerous: As this image shows the exhaust pipes are glowing red from the amount of heat generated by the jets

Remodelled: Colin Furze took four months to build hid bike extending it at the back to protect riders from the heat generated by the jets but still extremely close to the gas canister holding the fuel

The pulse jet uses the same technology as the V1 Doodlebug bombs, used during the Second World War.

‘This is my craziest creation yet and the scariest one to ride," said Colin, from Stamford, Lincolnshire, ‘Mr Furze admitted.

‘My
friend's mum was throwing out her bicycle, which she had ridden into 
town every day and loved so I decided to give it a new life.

‘I 
had to lengthen the frame by about a metre as the heat the jet engine 
chucks out is immense and I didn't want to be sitting on top of it.

‘It's
quite pleasant to ride at speeds of up to 35mph but after 40mph it is 
very shaky and extremely difficult to control. It has a mind of its own 
and goes where it wants.’

Colin has also invented the world's fastest pushchair and longest motorbike. He unveiled his latest creation on YouTube and the video has already been viewed 150,000 people in the last week.

‘Made from an old ladies bike with a 
jet engine whose roots come from a bomb this really is the most 
dangerous,  unsafe bike ever,’ he added.

He’s not the first to invent the jet 
powered bicycle, however. That honour belongs to teenage Romanian 
inventor Raul Oaida, who spent three years developing his jet engine 
propelled mountain bike to speeds of up to 26 mph on a flat road.

Mr
Oaida road-tested his jet engine bike for the first time in January on a
road behind his house in the city of Deva, where the spectacle 
attracted a small crowd of onlookers.

@highlight

32 year-old plumber, Colin Furze, builds jet powered bicycle nicknamed Norah

@highlight

Tests the bike at a local airfield WITHOUT safety equipment

@highlight

Inventor already holds three Guinness World Records for other inventions