By 
Daily Mail Reporter

PUBLISHED:

15:58 EST, 7 January 2013


| 

UPDATED:

10:38 EST, 8 January 2013

The U.S. National Transportation Safety Board has opened an investigation into the fire on a Boeing Co 787 Dreamliner aircraft at Boston's Logan International Airport on Monday, the agency said.

The fire marks the fourth mechanical problem in as many weeks for Boeing's new problem-plagued Dreamliner 787.

A mechanic inspecting the Japan Airlines Co Ltd jet discovered smoke in the cockpit while performing a routine post-flight inspection.

Passengers had just exited the plane 15 minutes before the blaze broke out.

WATCH VIDEO BELOW

Boston firefighters work to douse a fire in a Japan Airlines 787 Dreamliner's cargo hold

A fire crew responded and determined 
that a battery used to power the plane's electric systems when the 
engines are not running had exploded, Donahue said.

The mechanic was the
only person on board the plane when the smoke was discovered and no one
was hurt by the blaze, he added.

Smoke continues to billow out from the jetliner

'Passengers were in no danger as this event had happened at least 15 minutes after they deplaned,' Donahue said.

The
fire is the latest reported mechanical failure in a string of incidents
affecting the Dreamliner, which was also plagued by production problems
that delayed initial delivery by 3-1/2 years.

The design project began in the late 1990s. Boeing finally rolled out its first Dreamliner last year.

There are currently 13 Dreamliners in service.

The small explosion caused a fire but no passengers were hurt

The U.S. jet maker's shares fell more than 3 percent to $75.34 on the news.

Boeing spokesman Marc Birtel said, 'We are aware of the event and are working with our customer.'

Japan Airlines representatives did not immediately respond to a call for a comment.

Officials
with the Federal Aviation Administration are now looking into what 
caused the fire, Donahue said.

The National Transportation Safety Board 
also announced it was opening an investigation.

The
787 relies heavily on electrical power to drive onboard systems that in
other jet models are run by air pressure generated by the engines. It 
also suffered electrical problems during testing that prompted a 
redesign.

The
aircraft is Boeing's first to be made of carbon composites rather than 
aluminum, a change that lowers the plane's weight and allows it to burn 
less fuel.

Boeing stock dropped 3 points on the news of the fire

The
Dreamliner has suffered a string of mishaps with electrical systems in 
recent weeks.

On Dec. 4, a United Airlines flight from Houston to 
Newark, New Jersey, made an emergency landing after it appeared that one
of its power generators failed.

On Dec. 13, Qatar Airways said it had 
grounded one of its three 787 jets because of the same problem United 
had experienced.

On Dec. 17, United said that a second 787 in its fleet 
had developed electrical issues.

Boeing
Chief Executive Jim McNerney last month argued that the 787 has not 
experienced an unusual number of problems for a new aircraft.

Boeing competes with European jet maker Airbus.

WATCH VIDEO HERE

@highlight

New jet has had a history of mishaps, design problems and delays

@highlight

Recent mechanical failure forced jet to make emergency landing

@highlight

United Airlines grounded entire Dreamliner fleet after electrical problems

@highlight

Boeing stock drops 3 points on news of fire