By 
Alex Ward

PUBLISHED:

15:53 EST, 9 February 2013


| 

UPDATED:

17:10 EST, 9 February 2013

More wind turbines are being built in Britain than ever before as the country becomes the third highest wind power generator in Europe.

More than 1,200 turbines are set to start generating power over the next 12 months in a trend thought to be motivated by a planned cut in subsidies, due to come into effect in April.

New figures also showed that the UK has overtaken Italy and France, generating 8.4 gigawatts of wind energy, according to the European Wind Energy Association (EWEA).

Wind power: More wind turbines are being built in Britain than ever before in a trend thought to be motivated by a planned cut in subsidies, due to come into effect in April

The building of onshore turbines is up 60 per cent since last year with 763 turbines due to be built, while another 7,843 have building approval but are yet to be constructed, according to The Daily Telegraph.

A Department of Energy and Climate Change spokesperson said that 63 per cent of onshore wind planning applications were approved last year.

The wind power generated by the 4,369 turbines already in operation in Britain is enough to power an equivalent of more than 4.6 million homes.

Maf Smith, deputy chief executive from RenewableUK, which provides energy sector data said: ‘The Government is calling for the UK to quadruple the amount of wind installed between now and 2020.

‘Wind as a crucial part of our energy 
mix and is becoming more important as extra onshore and offshore 
capacity is added to the system.

‘The industry can achieve 31 gigawatts onshore and offshore by the end of the decade, but only with clear cross-party political support.’

'We can attract billions of pounds worth of investment to the UK and create tens of thousands of jobs, but only if the signals from Westminster are right. 

‘The proof of this will be in the Energy Bill, which is due to become law by the end of the year. So the decisions taken by Government over next few months are absolutely crucial for the UK’s wind industry.'

The Department of Energy and Climate Change announced the 10 per cent subsidy cut to onshore wind turbines last year, in a move they say will encourage up to £25billion in new investment in generating energy.

Extreme weather: Just last week a 115ft, £250,000 wind turbine in Bradworthy, Devon was blown over by high winds, three years after it was built

Dr John Constable, director of the Renewable Energy Foundation, was quoted in the Daily Telegraph saying: ‘The UK's wind power deployment on and offshore is way ahead of the learning curve and needs to slow down to a rational pace to avoid insupportable burdens on the consumer and the risk of major malinvestment the unwinding of which will be painful and embarrassing.’

According to RenewableUK, the numbers of small scale wind turbines and wind farms increased by 50 per cent last year, but projects have divided opinion with many communities fighting against the erection of turbines, considered to be a visual blight on the landscape.

Just last week a 115ft, £250,000 wind turbine in Bradworthy, Devon was blown over by high winds.

Experts believe the winds were so strong the blades span out of control causing the massive structure to catch fire and collapse. It was supposed to have a life expectancy of 25 years – but has lasted just three.

The Government hopes that wind energy will play a vital part in Britain's 2020 target for energy from renewable sources, contributing up to 14 per cent of the total required energy which could power an equivalent of 7.7 million homes.

A department spokesperson said: 'We 
expect to need up to 13GW of onshore wind to help meet our 2020 
renewables targets. We currently have 5GW operational, 6GW consented, 
and 7GW in planning.

'However, not everything in planning will be consented, and not everything consented will be built.'

@highlight

Over 1,200 wind turbines are to become operational over the next 12 months

@highlight

The UK has become the third highest wind power generator in Europe

@highlight

Turbines already in use generate enough energy to power over 4.6m homes