As a large light is wheeled into the room, 66 year old Larry Hester's face suddenly lights up and a huge smile spreads across his face.

The patient at Duke Eye Center in North Carolina is one of the first in the world to be given a bionic eye - and cameras were there to capture the moment he saw for the first time in 30 years.

As his wife rushed over to hug him, he told surgeons the good news, telling them 'Yes! Oh my goodness, yes!' moments after surgeon's pressed a button, activating Hester's newly implanted bionic eye.

Scroll down for video 

Paul Hahn, MD, a retinal surgeon at the Duke Eye Center, switches on the bionic eye - and 66 year old Larry Hester sees for the first time in 30 years

'Can I kiss him?' his wife, Jerry Hester, exclaimed as she heard him say he saw flashing lights for the first time

The Argus II Retinal Prosthesis Device incorporates technology initially developed by researchers then at the Duke Eye Center.

Using wireless technology, a sensor is implanted in the eye to pick up light signals sent from a camera mounted on special eyeglasses. 

Its sophisticated features were further enhanced and marketed by a company called Second Sight Medical Products.

On Oct. 1, 2014, Hester became only the seventh person in the United States to have a so-called bionic eye - an Argus II Retinal Prosthesis Device – activated as a visual aid to send light signals to his brain.

Paul Hahn, MD, a retinal surgeon at the Duke Eye Center, counted backward from three and pressed a button, activating Hester's newly implanted bionic eye.

The device incorporates technology initially developed by researchers then at the Duke Eye Center; its sophisticated features were further enhanced and marketed by a company called Second Sight Medical Products.

Using wireless technology, a sensor is implanted in the eye to pick up light signals sent from a camera mounted on special eyeglasses. 

Hahn implanted the sensor on Sept. 10, and activated the device on three weeks later – to the sheer delight of Hester and his family.

'Can I kiss him?' his wife, Jerry Hester, exclaimed in the moment she heard him say he saw flashing lights for the first time.

However,  the device will not restore normal eyesight, but instead provide a visual aid that could help Hester distinguish a door from a wall, or a crosswalk painted in a roadway. 

Hahn implanted the sensor on Sept. 10, and activated the device on three weeks later – to the sheer delight of Hester and his family. 

Using wireless technology, a sensor is implanted in the eye to pick up light signals sent from a camera mounted on special eyeglasses.

Hester describes seeing flashes of light that are more intense when he aims the camera at lights or light-colored objects.

During a clinic visit on Monday, Hester described 'seeing' sights he had long believed were past memories – a white duck swimming in a pond, the harvest moon, his wife's yellow chrysanthemums.

In a healthy eye, the rods and cones convert light into tiny electrochemical impulses that are sent through the optic nerve and into the brain, where they are decoded into images. 

If the photoreceptors no longer function correctly the first step in this process is disrupted, and the visual system cannot transform light into images.

The Argus II Retinal Prosthesis System ("Argus II") bypasses the damaged photoreceptors altogether. 

A miniature video camera housed in the patient’s glasses captures a scene. 

The video is sent to a small patient-worn computer (i.e., the video processing unit – VPU) where it is processed and transformed into instructions that are sent back to the glasses via a cable. 

These instructions are transmitted wirelessly to an antenna in the implant. 

The signals are then sent to the electrode array, which emits small pulses of electricity. 

These pulses bypass the damaged photoreceptors and stimulate the retina’s remaining cells, which transmit the visual information along the optic nerve to the brain, creating the perception of patterns of light. 

Patients learn to interpret these visual patterns.

Using wireless technology, a sensor is implanted in the eye to pick up light signals sent from a camera mounted on special eyeglasses.

Jerry Hester said her most cherished moment came while they were watching a football game on Sunday. 

She was sitting in a dark chair, and her skin was enough of a contrast that Larry could see flashes.

He reached out and touched her face.

'It was just a beautiful touch,' she said.

Hester will return to the Duke Eye Center regularly for additional training on the device, learning to discern shapes and objects from the flashes generated by the device. 

He said is eager to provide researchers with information they can use to enhance the technology, so that the next generation of patients will benefit from his pioneering effort.

'I just wonder how I have been so lucky,' he said. 

'Why me? But if I can use what I learn from this to help others with RP, it will not just be for my benefit.'

 

@highlight

66 year old Larry Hester was blind for 30 years due to a degenerative disease

@highlight

'Bionic eye' can send light signals to his brain

@highlight

He can now discern simple shapes 