Train passengers in England could cut their fares by more than 60 per cent - by buying their tickets a few miles over the border in Wales.

A study has found that English commuters are shelling out more than those in Wales because of subsides on Welsh rail travel - funded by the taxpayer. 

The survey has found that people travelling from Bristol - 20 miles from the Welsh border - are paying over £50 more for journeys to major UK cities such as Manchester, Leeds and Sheffield.

Scroll down for video 

Train passengers in England could cut their fares by more than 60 per cent - by buying their tickets a few miles over the border in Wales

The survey has found that people travelling from Bristol - 20 miles from the Welsh border - are paying over £50 more for journeys to major UK cities such as Manchester, Leeds and Sheffield

Whereas peak time tickets bought in Newport or Cardiff to the same destinations are up to £58.60 cheaper.

It comes as figures from the Office of Rail Regulation reveal huge disparities between the government funding for passenger journeys, varying from an average of £2.19 per journey in England to £9.33 in Wales.

Consequently Welsh provider Arriva Trains would be able to claim 13.07 pence per kilometre travelled by passengers from the taxpayer, on top of the fares passengers have already paid to travel.

English train providers, like First Great Western and CrossCountry, receive far less, with CrossCountry receiving 1p per passenger kilometre in England.

As a proportion of total income in the last financial year, Wales received 56 per cent in subsidies, compared with 27 per cent in England.

A trip to Manchester during morning rush hour on Monday next week will cost £80.70 from Bristol Temple Meads, according to the research by the Bristol Post newspaper.

But in Newport, peak time tickets to major cities are up to £58.60 cheaper than those bought in Bristol

But a train leaving Newport just four minutes later travelling to the same destination will cost less than half the price - only £32.

A four-hour journey from Bristol to Sheffield will cost £92.60, but a train leaving 10 minutes earlier from Newport or Cardiff would cost just £34 - a saving of £58.60.

Services from Cardiff to Manchester, Birmingham, Leeds, Liverpool and Blackpool also proved cheaper than travelling from Bristol, but with just minutes added to the journey. 

Tickets from Bristol to Newport are £11.20 while fares from Bristol to Cardiff are £12.40, 

Christopher Irwin, a director of Travel Watch South West, said difference in ticket price is a legacy of the system used by nationalised operator British Rail, which was privatised during the 1990s. 

He said: 'The history of British Rail helps us understand how fares are priced.

'Before the railway was privatised, lines used to be classified in three categories; intercity fares, South East fares, which covered a lot of lines to and from London, and regional railway fares.

'Traditionally regional lines would charge less, as those journeys would contain more stops and take slightly longer.

'Something like Bristol to Manchester would be classed as an intercity line, whereas something leaving from Newport and travelling through Wales is likely to be a regional line and would cost less.

'Lines, or flows, are still considered when setting ticket prices.'

Market demand as well as the rail provider, reliability, choice and comfort affect the cost of tickets, according to Mr Irwin.

He said: 'There are also many other factors that contribute to how rail tickets are priced and it has a lot to do with the service provider.

'For example bigger service providers often offer more flexibility in their tickets and can be more luxurious, which means they cost more.

'You also pay for market demand. I expect these routes from Newport and Cardiff are less popular than from Bristol.'

@highlight

There are huge disparities between tickets bought in Bristol and Newport

@highlight

Government subsidies for Welsh and English passengers also vary hugely

@highlight

People travelling from Bristol  paying £50 more for journeys to major cities

@highlight

But in Wales, the same destinations are up to £58.60 cheaper 

@highlight

Ticket prices for the morning of Monday, January 12, generated by the Bristol Post newspaper. 