By 
Jenny Hope Medical Correspondent

PUBLISHED:

18:06 EST, 14 October 2013


| 

UPDATED:

18:11 EST, 14 October 2013

A Europe-wide study found pregnant women exposed to 'safe levels' of pollution still have an increased risk of giving birth to small baby

Pregnant women exposed to ‘safe’ levels of air pollution still have an increased risk of giving birth to small babies, researchers have warned.

Nitrogen oxides and fine particles produced by traffic pushed up the risk of low birth weight by almost 20 per cent, a study found.

But the impact also persisted at levels well below those imposed by EU air quality directives.

In addition, the average size of babies’ heads was found to decrease, despite accounting for factors such as smoking, age, weight, and education, the study of 74,000 women from 12 European countries found.

Experts have now called for new measures to reduce levels of microscopic particles known as PM 2.5.

The study by a Europe-wide group of researchers and published in The Lancet Respiratory Medicine journal, found that raising the exposure to pollutants by five micrograms per cubic metre caused an 18 per cent greater risk of small babies.

Newborns weighing under 5lb 8oz can suffer health problems later in life.

But simply cutting levels of PM 2.5 to 10 micrograms per cubic metre could prevent more than one in five cases of low birth weight, say experts.

Lead author Dr Marie Pedersen from the 
Centre for Research in Environmental Epidemiology in Barcelona, Spain, 
said: ‘Our findings suggest that a substantial proportion of cases of 
low birthweight at term could be prevented in Europe if urban air 
pollution, particularly fine particulate matter, was reduced.’

Lower birthweight may cause the child health problems immediately after birth and while growing up.

Microscopic particles largely generated by diesel exhausts have previously been shown to damage the lungs and cause harmful changes in blood vessels and clotting.

Dr Pedersen said ‘The widespread exposure of pregnant women worldwide to urban ambient air pollution at similar or even higher concentrations than those assessed in our study provides a clear message to policy makers to improve the quality of the air we all share.’

Nitrogen oxides and fine particles produced by traffic pushed up the risk of low birth weight by almost 20 per cent

Previously exposure of pregnant women to 
traffic-related air pollution has been linked to pre eclampsia, and to 
asthma and autism in offspring.

Professor John Wright from the Bradford Institute for Health Research, said: ‘Unlike risk factors such as diet and smoking, air pollution is an exposure that we cannot reduce through individual actions.

‘Our research provides a wake-up call to policy makers.’

Dr Patrick O’Brien, spokesperson for The Royal College of Obstetricians and Gynaecologists, said ‘Exposure to some level of air pollution is unavoidable in day-to-day life and the risk still remains fairly low. Other factors, such as smoking, high blood pressure or excessive alcohol consumption, may contribute more to the risk of having a low birth weight baby.’

Dr Jenny Myers, NIHR Clinician Scientist/Clinical Senior Lecturer, Maternal & Fetal Health Research Centre, University Of Manchester, said ‘The size of the effect of air pollutants on birthweight was smaller than the effect associated with maternal smoking, so for individual women smoking has the largest effect on low birthweight.

‘For the whole population, however, air pollution has a greater effect because more women are exposed to air pollution than do smoke.

‘The mechanism by which air pollutants cause growth restriction is unknown, but it is plausible that environmental toxins could have a toxic effect on placental growth and function.’

@highlight

A Europe-wide study traffic pollution increased low birth rate by 20%

@highlight

Experts called for measures to reduce levels of microscopic particles

@highlight

Researchers said the study was a 'wake-up call to policy makers'

@highlight

Lower birthweight can cause health problems while growing up