By 
Daily Mail Reporter

PUBLISHED:

11:38 EST, 1 July 2012


| 

UPDATED:

11:42 EST, 1 July 2012

Four British men, including a retired judge, are being extradited to Italy to face Mafia money laundering charges.

Colin Dines, 68, his son Andrew, 31, and their colleagues Andrew Neave, 44, and Paul O’Connor, 41 are accused of using companies they run to launder Mafia money.

They intend to plead not guilty, insisting they are completely innocent - but face spending 18 months in jail with hardened criminals before their case even comes to trial.

The men are being extradited under a controversial European Arrest Warrent (EAW) system that allows foreign authorities to demand suspects without providing any evidence against them.

Retired judge Colin Dines, centre, with his son Andrew and wife Sarah. The two men are being extradited to Italy on Mafia money laundering charges

The case is the latest in a string of controversial extraditions enforced using EAW’s. which were introduced in 2002 by the EU, following the September 11 terrorist attacks.

The warrants were intended as a means to deal with terror suspects in other countries, but critics claim they are being abused to arrest and extradite people accused of far lesser offences, many of whom are innocent.

Parliamentary figures back up the suggestion, revealing Britain surrenders 11 people under EAWs for every one brought to the UK - prompting Conservative MP Dominic Raab to campaign against the unfair use of the warrants.

Mr Neave was put on an flight from Heathrow to Rome on Friday.

The other three men are expected to join him over the coming days - including Mr Dines snr, a former 
criminal barrister, who spent eight years as a judge in courts across 
London and the South East -

They will then be held at Rebibbia prison on the outskirts of the capital, where they face a wait of a year and a half before they get the chance to prove their innocence in court.

The four men are alleged to be involved in a £344 million money laundering scheme, through London-based commodity brokerage and telecoms firms companies they run.

It’s claimed the companies engaged in carousel VAT fraud in Italy - acting as ‘fictitious clients so that money generated by the fraud was laundered through the companies’ accounts.’

They were arrested in February 2010 in a raid on their homes by officers from the Serious and Organised Crime Agency (Soca) armed with European Arrest Warrents issued by a magistrate in Italy.

Incarcerated: The four men face spending 18 months in Rome's Rebibbia Prison before their case even comes to trial

Their assets were frozen and restraining orders were placed on their homes, to stop them from being sold.

The men, who have nine children between them, are particularly concerned about the fate of their families - who have only been able to draw £300 a week from their frozen assets

They fought extradition but lost that battle in January 2011, when Westminster magistrates ruled they should travel to Italy to face trial for involvement in what an Italian judge described as a ‘transnational criminal organisation consisting of more than 10 people' and 'complicit in money laundering.’

They appealed and appeared at the High Court in February before Lord Justice Hooper, a former colleague of Mr Dines', who denied the appeal, insisting there was sufficient evidence to warrant further investigation.

Last ditch approaches to the European Court of Human Rights and Home Secretary Theresa May failed and the extradition is going ahead - despite the fact the men claim they have never been charged or shown any evidence against them.

Mr Dines snr, from Slapton, Devon, told the Telegraph: ‘We were dragged out of bed at 5am, yet we’ve never been questioned by the prosecutors in the case. We have never been charged or shown details of the case against us. As a result we have not been able to put up any defence.’

Speaking before his extradition, he added: ‘We have conducted our business dealings with the Italian companies impeccably, but the investigating magistrate looking into them on another matter came across our names on a number of documents. As a result, instead of coming over here and talking to us about it, he has sought a warrant for our arrest.

‘We will be thrown into Rome’s worst prison for what our Italian lawyers say could be up to six months before being charged and another year of pretrial detention. Italy has the worst legal system in Europe, where the standard practice is to threaten and induce detainees in order to obtain admission of guilt in exchange for a reduced sentence. It’s worse than plea bargaining, because we are going to be locked up in a foreign country without access to proper legal representation, no bail and our assets frozen.'

@highlight

Four men are being extradited under controversial European Arrest Warrant

@highlight

They include Colin Dines, a 68-year-old former judge

@highlight

Accused of using companies they run to launder Mafia money

@highlight

Men insist they're innocent and have never been shown the evidence against them