By 
Daily Mail Reporter

Last updated at 4:51 PM on 21st June 2011

In a little over two weeks, an era in space travel will come to a close.

Nasa's scheduled launch of Atlantis on July 8 will be watched around the world as the U.S. space agency embarks on the final chapter of its 30-year shuttle programme.

Officials yesterday began a full dress rehearsal for the launch of mission STS-135 at Kennedy Space Center in Florida.

The four-strong Atlantis crew landed on the Cape Canaveral runway in T-38 jets as final mission testing gets underway.

Two weeks to go: Nasa's scheduled launch of Atlantis on July 8 will be the final chapter of the U.S. space agency's 30-year shuttle programme

Led by Commander Chris Ferguson, the astronauts will partake in the programme's 135th and final mission.

Commander Ferguson said they are trying to 'savour the moment'.

This week, the crew will undergo a 
number of training activities before suiting-up and climbing aboard 
Atlantis on Thursday to start their pre-launch check lists.

Workers at the Kennedy Space Center last Wednesday filled the shuttle's fuel tank in a key test ahead of its scheduled launch.

The test was added after structural 
problems were found last year on a tank later used for the February 
launch of sister ship Discovery. Nasa reinforced metal supports inside 
both tanks.

Last week's test was to verify the Atlantis tank repairs ahead of its lift-off.

Final preparations: Astronauts Sandra Magnus, Doug Hurley, Commander Chris Ferguson and Rex Walheim are raring to go

'It's very straightforward,' said 
launch director Mike Leinbach. 'We fill it up, send the final inspection
team out to the pad, they'll do their walk-down... and then we'll get 
the 'go' for drain. That's it.'

A
week's worth of X-ray photography followed to ensure that the metal 
struts withstood the extreme temperatures generated by 500,000gallons 
(1.89million litres) of liquid oxygen and liquid hydrogen inside the 
tank.

The test is one of 
the final milestones before Nasa launches Atlantis and four astronauts 
on a supply run to the International Space Station, a 12-day mission 
that is set to close out the 30-year-old U.S. space shuttle program.

An
Italian-built shipping container holding 9,500lbs (4,275kg) of food, 
clothing, science gear and supplies for the station is due to arrive at 
the launch pad on Thursday and be loaded into the shuttle's payload bay 
on Friday.

In addition to 
the cargo, the shuttle is set to deliver an experiment to demonstrate 
how satellites can be robotically refuelled in orbit, a potential 
game-changer in an industry worth more than $160billion a year.

Off to a flying start: The four-strong Atlantis crew landed on the Cape Canaveral runway in T-38 jets as final mission testing gets underway

Hundreds
of communications, weather and other satellites are currently circling 
Earth but none are designed to be refuelled. Once their fuel is spent, 
they can no longer reboot themselves or change position and manoeuvre, 
and they become expensive space junk.

The
Robotic Refueling Mission is a special assignment for Dextre, the 
Canadian-built robot attached to the space station's 55ft external 
crane. Over the next two years, ground controllers will use Dextre to 
demonstrate how the robot can handle various tasks associated with 
fueling a satellite and handling minor repairs.

Nasa
is retiring its three-ship shuttle fleet due to high operating costs. 
It has hired two commercial companies, Space Exploration Technologies 
and Orbital Sciences Corp (ORB.N), to take over cargo deliveries to the 
station and hopes to do the same for crew transportation within five 
years.

Until then, the U.S. will pay Russia to taxi astronauts to the station, at a cost of more than $50million per person.

@highlight

Lift-off from Kennedy Space Center is scheduled for July 8