By
Ellie Zolfagharifard

PUBLISHED:
  
  
      08:23 EST, 6 January 2014
    
  
 | 
  UPDATED:
  
  
      12:45 EST, 6 January 2014

The 2014 World Cup in Brazil will provide incredible displays of physical skill - but the most impressive performance won’t come from the likes of Rooney or Ronaldo.

It will instead be delivered by a paralysed teenager, who, during the opening ceremony in June, will kick a ball using a robotic body suit controlled by his or her brain.

The exoskeleton, which has been designed as part of the international 'Walk Again Project', will use motorised metal braces to support and bend the teenager’s legs.

Scroll down for video

Scientists from around the world are working to enable a young Brazilian paraplegic to kick off the opening game of the FIFA World Cup 2014. The teenager will wear an exoskeleton, artists' illustration pictured, that will be controlled by patterns of brain activity detected

The suit itself will be controlled by patterns of brain activity detected by electrodes placed either on the scalp or within the brain itself. 

These signals will be sent wirelessly to a computer worn by the wearer, converting them into movement.

The team behind the suit is a collaboration between various universities including Duke University in the U.S., the Technical University of Munich and the Swiss Federal Institute of Technology in Lausanne among others.

It plans to incorporate sensors into the exoskeleton that feed information about touch, temperature and force back to the wearer. The feedback is expected to come through a visual display or a vibrating motor.

‘The vibrations can replicate the sensation of touching the ground, rolling off the toe and kicking off again,’  Gordon Cheng, at the Technical University of Munich, Germany said in an interview with the New Scientist.

The body suit is the result of research from the Duke Nicolelis lab that looked into hair-thin and flexible sensors, known as microwires, implanted into the brains of rats and monkeys. These wires were used during tests to simultaneously control movements of both arms of a virtual monkey avatar, pictured

The exoskeleton, which has been designed 
as part of the international 'Walk Again Project', will use motorised 
metal braces to support and bend the teenager’s legs.

The suit itself will be controlled by 
patterns of brain activity detected by electrodes placed either on the 
scalp or in the brain itself. 

These signals will be sent wirelessly
 to a computer worn by the wearer, converting them into movements. 

The
 team plans to incorporate sensors into the exoskeleton that feed 
information about touch, temperature and force back to the wearer. The 
feedback is expected to come through a visual display or a vibrating 
motor.

The teenager - who is yet to be selected 
from a group of 10 hopefuls - will undergo training in a virtual reality
 simulator to translate thoughts into signals to the robotic armour.

The teenager - who is yet to be selected from a group of 10 hopefuls - will undergo training in a virtual reality simulator to translate thoughts into signals.

‘We want to galvanise people’s imaginations,’ Miguel Nicolelis, the Brazilian neuroscientist at Duke University added to the Washington Post.

‘With enough political will and investment, we could make wheelchairs obsolete.’

The body suit is the result of research from the Duke Nicolelis lab that looked into hair-thin and flexible sensors, known as microwires, implanted into the brains of rats and monkeys.

These flexible electrical prongs can detect minute electrical signals generated by hundreds of individual neurons in the animals’ frontal and parietal cortices - the regions that control a vast brain circuit that is responsible for voluntary movements.

In 2000, Professor Nicolelis’ lab reported that a monkey had been able to use power of thought to control a robot arm using these sensors.

More recently, his lab has shown that monkeys can control the movement of both arms on an avatar using just their brain activity. 

To enable the monkeys to control two virtual arms, researchers recorded nearly 500 neurons from multiple areas in both cerebral hemispheres of the animals’ brains, the largest number of neurons recorded and reported to date.

VIDEO: Miguel Nicolelis at TEDMED 2012

Several human quadriplegics have also received implanted brain chips in clinical trials. For instance, Matt Nagle, who was paralysed after being stabbed in the spine, learned to raise, lower and drop after objects after electrodes were implanted in his brain.

Professor Nicolelis is now developing  a new kind of electrode that branches like a tree into a vast network covering a larger volume of the brain.

He hopes this network will help make deliver more complex exoskeletons that can control a greater number of limbs using the power of thought.

 

@highlight

The kick will take place during the opening ceremony in Sao Paulo, Brazil

@highlight

Exoskeleton will use motorised 
metal braces to bend the teenager’s legs

@highlight

Its movement will be controlled by brain activity detected by electrodes

@highlight

Sensors will feed information about touch and force back to the wearer