By 
Claire Bates

PUBLISHED:

04:37 EST, 26 October 2012


| 

UPDATED:

04:37 EST, 26 October 2012

Good for you? Experts say the potential for interactions between supplements and prescription drugs is substantial

Taking herbal or dietary supplements like echinacea , calcium or iron alongside prescription drugs could cause adverse side effects, as study warned.

Other remedies such as St John's Wort, flaxseed, magnesium or ginkgo could also be bad for you when mixed with these medicines, it is believed.

The research suggest combining the popular alternative remedies may cause mild-to-severe heart problems, chest pain, abdominal pain and headache, particularly among people receiving medication for problems with their central nervous or cardiovascular systems.

Those taking Warfarin, insulin, aspirin, digoxin and ticlopidine had the greatest number of reported adverse interactions with the remedies or supplements.

Combining the two affects the process by which some types of drugs are absorbed, distributed, metabolised and eliminated by the body, the study warned .

Yet scientists said the findings may just be the tip of the iceberg and said people needed to be aware of the health risks involved.

But it pointed out herbal and botanical remedies were more likely to have adverse effects than the other dietary supplements, such as vitamins, minerals and amino acids.

Emeritus Professor Edzard Ernst from the University of Exeter said: 'Survey after survey shows that large proportions of the population are trying 'natural' remedies for illness-prevention, all sorts of ailments, diseases or for states of reduced well-being.

'Most experts therefore agree that the potential for such interactions is substantial. Despite this consensus and despite the considerable amount of documented harm generated by such interactions, our current knowledge is still woefully incomplete.'

The number of interactions between herbal and dietary supplements and prescribed drugs could be under-reported and just the tip of the iceberg, he added.

Woman inside a greenhouse laboratory inspecting echinacea, a plant used to ward off colds by boosting the immune system

He called for greater government control and a need to warn of the potential dangers of mixing herbal and dietary supplements with prescribed drugs.

He said: 'Patients deserve reliable information, and it is our duty to provide it. We have to become vigilant and finally agree to monitor this sector adequately.

'Each individual doctor can contribute to this process by routinely including questions about alternative medicine use in their medical history taking.'

The study was carried out by Dr Hsiang-Wen Lin from the College of Pharmacy in Taiwan who said: 'Consumer use of herbal and dietary supplements has risen dramatically over the past two decades.

'In the USA, for example, it is estimated that more than 50 per cent of patients with chronic diseases or cancer use them and that many patients take them at the same time as prescribed medication.

'Despite their widespread use, the potential risks associated with combining herbal and dietary supplements with other medications, which include mild-to-severe heart problems, chest pain, abdominal pain and headache, are poorly understood.'

The study looked at previous research into 213 herbal and dietary supplements entities and 509 prescribed medications and compared the 882 incidents of adverse reactions.

More than 42 per cent of the drug interactions were caused by the herbal and dietary supplements altered the pharmacokinetics of the prescribed drugs - the process by which a drug is absorbed, distributed, metabolised and eliminated by the body.

Just over 26 per cent of the total were described as major interactions.Among the 152 identified contraindications, the most frequent involved the gastrointestinal system (16.4 per cent) and neurological system (14.5 per cent).

Flaxseed, echinacea and yohimbe had the largest number of documented contraindications.

Dr Lin said: 'Our extensive review clearly shows that some herbal and dietary supplements ingredients have potentially harmful drug interactions that are predominately moderate in their severity.

'It also showed that herbal and botanical remedies were more likely to have documented drug interactions and contraindications than the other dietary supplements, such as vitamins, minerals and amino acids.'

The findings are published in the International Journal of Clinical Practice.

@highlight

Herbal and botanical remedies were more 
likely to react badly with prescription drugs than vitamins

@highlight

Interaction side-effects include mild-to-severe heart problems, chest pain, abdominal pain and headache

@highlight

University of Exeter expert said reported cases 'could be tip of the iceberg'