By
Rebecca English, Royal Correspondent

The cost to taxpayers of refurbishing the Duke and Duchess of Cambridge’s new Kensington Palace home has hit £1million so far, officials revealed yesterday.

William and Kate are hoping to move into Apartment 1A, the 57-room residence once inhabited by Princess Margaret, with their new baby this summer.

Although the couple are personally paying for fixtures and finishing – such as curtains and soft furnishings – the cost of basic building work including new heating, electrics and plastering is being met by money given to the Queen by the Government.

Decorating: The taxpayer has spent £1million refurbishing Kate and William's new Kensington Palace home

Home sweet home: Kensington Palace, where the royal couple have given their apartment a £1million makeover, pictured shrouded in scaffolding and coverings

So far the internal refurbishments have cost £600,000 and the renewal of the roof a further £400,000.

A spokesman for the Duke and Duchess stressed that a close eye was being kept on costs but added that the work on the roof had been long overdue, while the cost of the internal refurbishments have been dramatically increased by the removal of asbestos.

‘This essential structural work needed to be completed whoever moved in. The last major works in the apartment took place around the time that Princess Margaret and Lord Snowdon moved in more than 50 years ago.

The cost of interior decorating and furnishing of course falls to the Royal Family privately.’

The spokesman also stressed that occupied royal palaces are held in trust for the nation, so William and Kate do not own the apartment, nor can they or the Royal Family sell it.

Facade: The fake frontage of Kensington Palace was erected while work was being carried out. The enormous canvas - measuring about 25,000 sq ft - covers the south side of the building

The fabric of all of these buildings must be maintained or otherwise fall into disrepair.

Apartment 1A is a spacious four-storey property with its own large south-facing walled garden.

It takes up half the Clock Tower wing designed by Sir Christopher Wren for King William and Queen Mary.

The living space has previously included five reception rooms, three main bedrooms, dressing rooms and bathrooms, a night and day nursery, nine staff bedrooms and more than 20 ‘ancillary’ rooms.

Princess Margaret and Lord Snowdon, who moved in following a £1.5million programme of refurbishment in 1963, famously installed a ‘futuristic’ kitchen complete with sleek Formica and teak units. It has since been ripped out.

Trip: At the weekend William, Kate and pet dog Lupo got a free ride back to London from a friend flying past their home in North Wales

Coming in to land: The Duchess of Cambridge can be seen through the helicopter window (right) as it touches down in Buckinghamshire

In recent years the property has been managed by the charity Historic Royal Palaces (HRP), which used it as office and exhibition space.

As HRP has already spent a substantial amount of its own money on remedial work, the Queen has been forced to compensate it for handing the building over to William and Kate.

This cost has also been met by taxpayers and while it has been described by palace sources as ‘fair’, it is understood to be more than £100,000.

According to Buckingham Palace’s annual accounts released yesterday the Cambridges were also responsible for the single most expensive foreign visit by members of the Royal Family over the last 12 months.

Pay rise: The Queen, pictured yesterday with the Grenadier in the gardens of Buckingham Palace, is to receive a five per cent rise in income

They racked up a bill of £370,590 on 
flights last autumn for their official Diamond Jubilee tour of Asia and 
the South Pacific, which saw them travel to Singapore, Malaysia, the 
Solomon Islands and Tuvalu.

Of that £107,958 was on scheduled 
flights plus a further £172,436 on a private jet and the cost of their 
entourage (but not their police protection officers) both in advance and
 during the tour itself.

Sources stressed that the value of 
the diplomatic and business benefits generated by the ten-day trip in 
September was ‘incalculable’.

@highlight

Government funding is being used to pay for building work

@highlight

Duke and Duchess of Cambridge paying for soft furnishings themselves

@highlight

57-room Apartment 1A used to be Princess Margaret's home