Duke University has canceled plans to use the tower of its chapel for a weekly, amplified call to prayer for Muslims - just a day after the idea was announced and following an outcry from a prominent evangelist.

The university said on Thursday that Muslims will instead gather on the quadrangle before heading into a room in the chapel for their weekly prayer service.

'Duke remains committed to fostering an inclusive, tolerant and welcoming campus for all of its students,' said Michael Schoenfeld, vice president for public affairs and government relations. 

Scroll down for video 

Duke University has canceled plans to use the tower of its chapel for a weekly, amplified call to prayer for Muslims - just a day after the idea was announced and following an outcry from a prominent evangelist

'However, it was clear that what was conceived as an effort to unify was not having the intended effect.'

Under the canceled plan, members of the school's Muslim Students Association would have recited the call lasting about three minutes from the bell tower. 

However, the plan drew the ire of evangelist Franklin Graham, the son of the Rev. Billy Graham, who urged Duke alumni to withhold support because of violence against Christians that he attributed to Muslims. 

He wrote on Facebook that the decision is playing out as 'Christianity is being excluded from the public square.'

The chapel is identified by the school as a Christian church but also hosts Hindu services and has been used for Buddhist meditations.

The chapel's associate dean for religious life, Christy Lohr Sapp, said before the plans were canceled that the move showed the school's commitment to religious pluralism. 

The university said on Thursday that Muslims will instead gather on the quadrangle before heading into a room in the chapel for their weekly prayer service

Evangelist Franklin Graham had called for donors and alumni to withhold support for Duke over the initiative

In a column written for the News and Observer in Raleigh, Lohr Sapp acknowledged the headlines generated by violence by extremists in ISIS, Boko Haram and al-Qaida, contrasting it to what's happening on campus.

'Yet, at Duke University, the Muslim community represents a strikingly different face of Islam than is seen on the nightly news: one that is peaceful and prayerful,' she wrote.

The private university in Durham, northwest of Raleigh, was founded by Methodists and Quakers, and its divinity school has historically been connected to the United Methodist Church. 

It has nearly 15,000 students, including about 6,500 undergraduates. The school's insignia features the Christian cross and a Latin motto translated as 'learning and faith.'

The university says it has more than 700 students who identify themselves as Muslim, and it hired its first full-time Muslim chaplain in 2009. 

Muslim students have been holding prayer services in the basement of the chapel for the past two years.

@highlight

University has canceled plans to use the tower of its chapel for a weekly, amplified call to prayer for Muslims

@highlight

Original idea had only been announced on Wednesday, but immediately faced criticism

@highlight

Evangelist Franklin Graham wrote on Facebook that the decision is playing out as 'Christianity is being excluded from the public square'

@highlight

Muslims will instead gather on the quadrangle before heading into a room in the chapel for their weekly prayer service