By 
Damien Gayle

PUBLISHED:

09:06 EST, 9 October 2012


| 

UPDATED:

09:06 EST, 9 October 2012

A civil rights group has devised a new kind of online test that measures a user's sense of human empathy to distinguish them from automatic spam posting programmes.

The Civil Rights Captcha asks users to take a moral stance on a real-world civil rights issue by offering them three options about how they feel about it.

Only one answer is correct, and that is the one which shows compassion and empathy.

Moral stance: A new kind of Captcha asks users to prove they are human by choosing the morally correct response from a choice of three

For example, the Captcha might ask a user: 'In Kosovo people are tortured in detention. How does that make you feel?'

It then asks them to enter either 'excited', or 'bothered', or 'great'.

A Captcha is a type of challenge-response test used in computing as an attempt to ensure that the response is generated by a person. 

The acronym, coined in 2000 by researchers from Carnegie Mellon University, is based on the word 'capture' and stands for 'Completely Automated Public Turing test to tell Computers and Humans Apart'.

A common type of Captcha requires the user to type letters or digits from a distorted image that appears on the screen, and the tests are commonly used to prevent unwanted internet bots from accessing websites.

Are you human? The test was designed by Swedish campaign group 
Civil Rights Defenders and draws from examples of incidents that breach 
the United Nations Universal Declaration of Human Rights

Devised by campaign group Civil Rights Defenders, an Swedish campaign group, the Civil Rights Captcha is intended to raise the profile of civil rights struggles worldwide.

'With over 200 million CAPTCHAs being solved everyday, we hope that by catching a tiny amount of those interactions we can help promote and empower our partners - brave human rights defenders, who often put themselves at great risk through their engagement for other people's rights,' they say.

Most of the situations presented by the Captcha are based on real events where the United Nations Universal Declaration of Human Rights has been breached.

Civil Rights Defenders add that there is no content related to their work on the app that is based on their 'subjective and personal' values.

The app is available as free code for any web developer to use on their site.

@highlight

Examples drawn from breaches of United Nations Universal Declaration of Human Rights

@highlight

Users must choose the one answer out of three that shows compassion and empathy