What's for dinner? How about leftover cartilage of skate with herring-head tartar sauce, cured tuna blood line aioli or a meat loaf of offal and slightly past-its-prime cow usually reserved for dogs?

Those and two dozen other dishes using scraps and usually ignored bits comprise the menu at chef Dan Barber's WastEDny, a pop-up project at one of his Blue Hill restaurants in New York intended to shed light on the many tragedies of food waste.

The farm-to-table guru, a multiple James Beard Award winner and author of The Third Plate: Field Notes on the Future of Food didn't have a hard sell on his hands when he invited 20 of his heavy hitter chef friends to join him in turning out $15 a la carte plates made from day-old bread, bruised beets, brine from the olive bin and the peels of pineapples.

Among the chefs backing the concept are Mario Batali, Dominique Ansel and Alain Ducasse, with each taking it in turn to take the lead.  

Grub's up: In this Thursday, March 19, 2015 photo, a waiter serves a couple at WastED in New York - the menu includes dishes using scraps and other ignored bits

Diners haven't been put off by the idea of 'dumpster dining' and there is currently a waitlist for WastEDny. The final sitting will take place on March 31 and there is no word if a repeat session will occur. 

Even Barber's tabletops and cocktails tell the story. The restaurateur had his Manhattan tables redone with tops from agricultural byproducts and mushroom mycelium for his two-and-a-half week pop-up.

His boilermaker libation included flat beer syrup and spent coffee grounds with the bourbon. Using such waste, of course, has been part of rustic cuisines around the world for centuries. 

And chefs like Barber, who has a second restaurant on a farm north of the city, are far more efficient than they're given credit for. 

But in the U.S., the land of abundant fast food, grocery aisles piled with perfect produce and home refrigerators stuffed with food never eaten, the distribution system has been deemed broken by activists in a waste movement more firmly taking root.

'Really, the larger issue is how do we create a culture of eating that utilizes the entirety of the food system. 

'To do that we need chefs and restaurants to start the conversation,' Barber said during a recent busy night of service at WastEDny, capitalized to emphasis his hope of educating the unenlightened.

Fine-dining restaurants are just a fraction in the food waste equation, however.

About 40per cent of food grown for human consumption in the U.S. is tossed, cramming landfills, and about a third of such food globally never makes it into human mouths. 

Dinner is server: Fried skate wing cartilage with smoked whitefish head tartar sauce

Novel idea: Chef (above) Dan Barber's WastEDny, a pop-up project at one of his Blue Hill restaurants in New York, is intended to shed light on the many tragedies of food waste

With nearly one billion people starving or food insecure around the world, much of the waste is generated by U.S. households and farms themselves, said Jonathan Bloom, an activist in Durham, North Carolina, and author of American Wasteland: How America Throws Away Nearly Half of Its Food (and What We Can Do About It).

'It's a system that is not serving anyone particularly well,' Bloom said, noting that waste is scattered throughout the distribution chain. 

'We have an obesity crisis on a global scale in addition to a hunger crisis, the scale of which we've never seen before, and at the same time we're overproducing, taxing our planet to an unnecessary and dangerous amount.'

Barber sees his pop-up as an extension of his 'third plate' philosophy that challenges Americans to radically rethink what is acceptable and unacceptable to eat while becoming better stewards of the land.

'In America we come with this blessed landscape, this Garden of Eden ... with incredible soils, temperate climate, predictable rainfall, and we produce a ton of food. 

'And because of that we were never forced into the kind of negotiations that suck up waste,' he said.

That goes a long way in explaining the 'wasted special' served up by one of Barber's guest chefs, Bill Telepan of the Upper West Side restaurant Telepan. 

He fashioned his plate of tuna on a bed of salvaged radish greens, incorporating them into a pesto, slicing the radish into the dish and using the usually tossed blood line of the fish in an aioli.

Chefs are trained to carve out the blood line and tuna overall is a good example of customer preference driving waste, he said.

'People look for that certain ruby red part of the tuna. They're not interested in paying top dollar for a piece on the side that may not look as beautiful but still is just as tasty,' said Telepan, hoping to sneak his WastED dish onto the menu of his own restaurant. 'I just won't call it blood line.' 

A rainbow of color: Ingredients used in the dishes at WastED are laid out in the kitchen 

Team work: Dan Barber, center and Bill Telepan prepare one of the dishes served at WastED

Grant Baldwin wouldn't mind. He and his wife live in Vancouver, British Columbia, and filmed themselves living on discarded and culled food for six months for their documentary Just Eat It. 

They did their share of dumpster diving - heading to unlocked bins of wholesalers for the best finds - and they came up with some treasures: cartons of eggs with plenty of time left on expiration, boxes of pricey chocolate bars tossed because they did not have the requisite English-French labeling required in Canada, and a mountain of packaged hummus still in containers but perfectly edible.

'The whole reason that we did the project was to prove the food was good,' Baldwin said. 

'Everybody talks about how 40per cent of food is wasted, but to see it in the bins is another thing. 

'Eating from dumpsters is not a good lifestyle for anyone. It's a terrible lifestyle. The point is the food shouldn't be in the bins to begin with.'

Advocates like Baldwin, Barber and Bloom applaud the higher visibility in recent years of sustainable farming techniques, as well as locavores who prefer eating food grown close to home. 

Enough for all: Chef Bill Telepan serves a taste of cured tuna blood line aioli to the waitstaff

But Baldwin thinks rigid standards for date labels on packaged foods serve to muddle the edibility issue, wrongly convincing people that perfectly good food is no longer safe to eat.

And appearance remains a huge stumbling block in the processing and packaging of food, with retailers demanding exacting uniform standards that have growers and middlemen tossing 20 to 70per cent of shipments in some cases.

Michael Muzyk knows that first-hand. He's the president of Baldor Specialty Foods, a distributor and processor of produce in the South Bronx serving high-end hotels and restaurants like those of Barber and Telepan. 

He signed on to supply WastEDny, providing the peels of pineapples, for instance, for a dessert served with candied mango skin and an ice cream flavored with lime leaves.

Baldor - as a middleman - has made strides in re-purposing his own food waste, using natural enzymes to dehydrate byproduct before it hits landfills. 

The company is also a major contributor to City Harvest, which feeds the hungry in New York City using rescued food.

'Will there be 100 chefs tomorrow saying I want to follow Dan Barber's lead? I hope so,' he said. 'I hope so.' 

@highlight

Dan Barber's WastEDny, a pop-up project at one of his Blue Hill restaurants in New York is intended to shed light on the many tragedies of food waste

@highlight

He invited 20 of his heavy hitter chef friends to join him in turning out $15 a la carte plates made from day-old bread and the peels of pineapples