In the dark world of George Orwell 1984, the ‘proles’ are forced to read meaningless poetry written by a computer.

It might seem like a far-fetched scenario, but Orwell may have touched upon a future trend when he published his novel in 1949.

Today, computers can do anything from interact with humans to predict their behaviour – and one could someday become the next poet laureate.

The site lets you play a game titled 'bot or not' to see if you can distinguish if a poem was written by a computer or a human

The Bot or Not website, created by Australians Benjamin Laird and Oscar Schwartz, reveals just how adept computers have become at writing poetry.

The site lets you play a game titled ‘bot or not’ to see if you can distinguish if a poem was written by a computer or a human.

It describes itself as a ‘Turing test for poetry’ and once you select your answer, it will reveal how the chosen poem was created.

The site describes itself as a 'Turing test for poetry' and once you select your answer will reveal how the chosen poem was created

In 1950, Alan Turing devised the Turing test as a way of verifying machine intelligence.

The Turing test is a proposed a situation in which a human judge talks to both a computer and a human through a computer terminal.

The judge cannot see the computer or the human, but can ask them questions via the computer. Based on the answers alone, the human judge has to determine which is which.

For instance, more than three-quarters of quiz-takers incorrectly predicted that that Deanna Ferguson’s ‘Cut Opinion’ was written by a machine.

‘Computer generated poetry means different things to different people,’ according to the website.

‘What we mean by “computer-generated poetry” is: text, that is generated through an algorithm, which is executed by a digital, electronic computer, which is intended, by whoever it may be, to be read as poetry.’

Computer-generated poems can be written using a variety of techniques. For instance, developers have created a machine-learning algorithm capable of collaborating with Shakespeare.

It isn't just poetry generated in human form that is gaining popularity. In December, Stanford University held its first code poetry slam to reveal the literary side of computer code

The machine-learning software, dubbed ‘Fluency’, analyses the style of Shakespeare's sonnets.

Developer Nathan Mathias was then able to write a new sonnet choosing words from the suggestions generated by the algorithm.

‘As might be expected from an artificial intelligence, the result is full of mixed metaphors,’ Mr Matias said, writing in SwiftKey’s blog.

As well as using SwiftKey’s engine, Mr Matias also built a visual interface to help in poetry creation and named this project ‘Swift-Speare.’

Using this interface, he was able to co-create poetry in the style of various authors including William Gibson and John Denham.

Machine-learning software, dubbed ‘Fluency’, 
analysed the style of Shakespeare's sonnets. Nathan Mathias was then 
able to write a new sonnet choosing words from the suggestions generated by the algorithm

And it isn’t just poetry generated in human form that is gaining popularity. In December, Stanford University held its first code poetry slam to reveal the literary side of computer code.

Leslie Wu, a student at the university, wore Google Glass as she typed 16 lines of computer code that were projected onto a screen while she simultaneously recited the code aloud.

She then stopped speaking and ran the script, which prompted the computer program to read a stream of words from Psalm 23 out loud three times, each one in a different pre-recorded-computer voice.

Ms Wu said the slam proved computers can be poetic, and as the Bot or Not website proves, it’s not always easy to tell the difference between man and machine.

@highlight

'Bot or Not' site was created by Benjamin Laird and Oscar Schwartz

@highlight

Test reveals how many people believe poem was by man or machine

@highlight

It reveals just how adept computers have become at writing poetry

@highlight

Earlier this year, a machine was shown to 'collaborate' with Shakespeare