Vince Cable today took aim at the leaders of the other main parties, claiming the Tories are merely 'UKIP without the beer'.

He also poked fun at Ed Miliband's Labour party as pursuing French President Francois Hollande's brand of 'socialism without the sex'.

In a well-received speech at the Lib Dem conference in Glasgow, Mr Cable also accused Chancellor George Osborne of 'lying' by claiming he could balance the nation's books without tax rises.

And he called for more open immigration to Britain, insisting migrants from both inside and outside the EU have brought 'tangible benefits' to the UK.

Scroll down for video 

Business Secretary Vince Cable made clear his ongoing discomfort with sharing power with the Tories, accusing them of 'arrogance' and being 'obsessed' with cuts

Mr Cable used his speech to announce a higher minimum wage for apprentices and a review of the law for up to 1million workers who 'fall through the cracks and don’t currently have full employment rights'.

But he turned his fire on both Labour and the Conservatives, as the Lib Dems try to make a clear pitch to voters to prevent a wipeout in 2015. 

Mr Cable said the two party conferences had helped the Lib Dems to understand their opponents better. 

'The Tories are reinventing themselves as UKIP but without the beer, while the Labour party is offering us Hollande Socialism, but without the sex.'

He insisted the Lib Dems had joined the coalition to rescue the economy, and have plenty to be proud of.

But he made clear his ongoing discomfort with sharing power with the Tories, accusing them of 'arrogance' and being 'obsessed' with cuts. 

He insisted the deficit 'has to be dealt with' but rejected plans set out by Tory Chancellor George Osborne last week for the full £25billion needed to eradicate the deficit to come entirely from spending cuts.

Mr Cable insisted the Lib Dems had joined the coalition to rescue the economy, and have plenty to be proud of

Mr Cable said Ed Miliband's Labour party is offering voters the socialism of French president Francois Hollande (right) 'but without the sex'

The Tories also came under fire, with Mr Cable claiming David Cameron's party is 'obsessed' with spending cuts and is no more than 'UKIP without the beer'

Mr Cable said key public services like legal aid, local government, policing and defence have already been 'cut to the bone'.

He went on: 'The Tories are ideologically obsessed by cuts because they see it as a way of destroying public service and the welfare state, which they detest.

'Let us be clear. The Tories’ proposal to take another £25 billion or more out of welfare and unprotected Government departments will do great harm to valuable services: to imagine otherwise is fantasy. I will categorically not go along with this.

Mr Cable called for more open immigration to Britain, insisting migrants from both inside and outside the EU have brought 'tangible benefits' to the UK

'So you might ask what is the alternative? The truth is more taxes will be needed. To contribute to deficit reduction and also to address unacceptable inequalities.'

In a direct swipe at Mr Osborne, he added: 'Any politician who tells you that the next Government can balance the budget and avoid tax increases is lying to you.'

However, the move raises the prospect of the Lib Dems going into the election promising to hike taxes if they return to power after the election.

Major splits have also emerged between the Tories and Lib Dems over immigration.

David Cameron promised to cut net migration to the tens of thousands, but since the coalition was formed the numbers arriving each year have topped more than 200,000, fueled mostly by large numbers arriving from elsewhere in the EU.

But Mr Cable said the Tories were trying to 'close the borders to skills and talents that Britain needs, by pursuing an absurd net migration target – plucked out of the air and totally unenforceable'.

He argued for more open immigration, accepting people coming to Britain to study or work.

'Overseas students, whose fees subsidise British students and earn £9bn a year for the UK, are discouraged and so go to the US or Australia instead. 

'Firms who need specialist skills from Japan, India or the US have to climb piles of red tape (far bigger than anything generated by Eurocrats in Brussels). 

'We then train Chinese engineers and insist they go home just when British industry can make good use of them. 

'But, of course, there is always a warm welcome isn’t there for dodgy billionaires willing to make a large party donation for a game of tennis with Boris and Dave.' 

Mr Cable said the Lib Dems have a responsibility 'to tell the uncomfortable truth that the vast majority of migrants coming to the UK from inside or outside the EU have brought tangible benefits to the economy, importing valuable skills and strengthening our civic culture'. 

He added: 'Of course immigration does have to be controlled at the point of entry and exit. And we must deal with abuse and crack down on ‘benefit tourism’. 

'But not at the expense of the EU Single Market, and its free movement of workers.'

Urging Lib Dems to stand up to their rivals, he added: 'We have a real record of achievement in Government. In very difficult circumstances we have brought compassion, common sense and competence into Government: we have maintained our liberal and social democratic values in doing so; and we have stood up to the born-to-rule arrogance of our coalition partners as well as the narrow tribalism of the Labour opposition.

'There is a lot to proud of: and we must be proud of it.'

@highlight

Business Secretary insists the Lib Dems have plenty to be 'proud' of

@highlight

Claims Tories 'obsessed' with cuts and 'lying' that tax rises are not needed

@highlight

Attacks 'narrow tribalism' of Labour with plea for long-term business plan

@highlight

Argues immigration has brought 'tangible benefits' to Britain  