The Queen is set to lose funding worth millions of pounds a year thanks to a republican snub by Nicola Sturgeon’s SNP government.

In a move that threatens an explosive cross-border row, Scottish Ministers have signalled they will refuse to contribute to the costs of running the Royal Family.

A deal to hand new devolved powers to Scotland after September’s referendum on independence will effectively rob the Royals of more than £2 million in cash a year.

Scroll down for video 

A republican snub by the Scottish government of Nicola Sturgeon (left)  to contribute to the running costs of the Royal Family will take out over £2million pounds a year from the Queen's (pictured right) Royal purse

The Mail on Sunday can reveal that the SNP is planning to reap the financial benefits of the new deal – while refusing to hand across the money to fund the Monarchy.

With the first formal meeting between new First Minister Ms Sturgeon and the Queen just three days away, the move threatens to provoke a major rift between the Scottish Government and the Royal Family. 

Ms Sturgeon’s calculated snub will also strain the fraught relationship between the governments in London and Edinburgh.

Labour said the First Minister’s refusal to pay Scotland’s share for the Royal Family showed the SNP’s ‘narrow’ view of the world, while the Tories accused the nationalists of deliberately trying to ‘undermine’ Scotland’s strong links with the Monarchy.

Ms Sturgeon has a history as a strong anti-Royalist, having boycotted a visit by the Queen to the Scottish Parliament in 2003 and also deliberately making her oath of allegiance in the Scottish Parliament to the sovereignty of the people, not the Monarch, when she was elected in 1999.

After the SNP lost the referendum on independence in September, David Cameron asked Lord Smith of Kelvin to draw up a list – with cross-party approval – of powers that should be devolved from Westminster to the Scottish Parliament.

The Scottish Government will take control of the property and land in Scotland, under new powers devolved to them under the Smith Commission report, including sites such as Tobermory on the Isle of Mull (pictured)

When the Smith Commission’s report was published last month, it transferred control to the Scottish Parliament of all the Scottish assets of the Crown Estate.

This means the Scottish Government will take control of the property and land in Scotland previously owned on behalf of the British state, as well as control of Scotland’s coastline, including mineral and fishing rights and the revenue from offshore wind farms.

However, the move also directly affects the Queen’s income, because the Crown Estate plays a vital role in funding the Royal Family.

Other assets belonging to the Crown Estate transferred to the Scottish Parliament, which were previously owned on behalf of the British state, include Dowsing offshore wind farm in the North Sea (pictured)

The Crown Estate, throughout the whole of the UK, makes about £240 million profit every year.

At the moment, these profits are handed to the Treasury. The Royal Family receives a ‘sovereign grant’ equivalent to 15 per cent of the profits. Currently, this agreement means the Royals receive about £36 million a year.

The Smith Commission report said the ‘management of the Crown Estate’s economic assets in Scotland and the revenue generated by those assets’ should be transferred to the control of the Scottish Parliament.

Scotland will also be given control of its coastline, including mineral and fishing rights, under new powers devolved to the Scottish Parliament. Here an angler fishes for salmon at the River Dee, Aberdeenshire

As a result, the profits of the residual Crown Estate in England and Wales will shrink – as will the 15 per cent share given to the Queen.

When the profits from the Crown Estate’s assets in Scotland are taken away, the residual Crown Estate will lose £14 million a year – and the Queen will lose about £2.1 million annually. Instead of going to the Treasury, the cash from Scotland will go straight into Scottish Government coffers.

Crucially Lord Smith’s report made it clear that a new deal would have to be put in place to ensure the Queen’s existing funding remained in place.

He stated: ‘Responsibility for financing the sovereign grant will need to reflect this revised settlement for the Crown Estate.’ 

However, Ms Sturgeon has apparently decided that she will not be sending any Scottish Crown Estate money south to make up the shortfall – and expects the Treasury to pick up the tab from general taxation.

A spokeswoman for the Scottish Government said: ‘The level of funding the Queen receives from the Treasury under the sovereign grant is set by reference to 15 per cent of the Crown Estate’s profits and does not come from Crown Estate profits themselves. 

'With 71 per cent of taxes paid in Scotland continuing to be controlled by the Treasury, Scotland will continue to make the same contribution to the Monarchy through general taxes.’

Publicly, UK Government Ministers would only say yesterday that they expected the Crown Estate in Scotland to continue to play some part in funding the Royal Family. A spokesman for the Scotland Office said: ‘Officials from the Treasury and Crown Estate will work with the Palace to determine exactly how funding will work in the new Scottish Crown Estate.’

But privately, it is understood that senior Ministers in Downing Street and the Treasury are very unhappy with Ms Sturgeon’s approach.

They believe that Ms Sturgeon’s dogmatic and unilateral approach has undermined much of the trust built up through the Smith Commission process. 

A spokesman for the Scottish Labour Party said: ‘The fact the SNP are saying they’ll make no contribution from their future Crown Estate income illustrates their narrow view of the world.

‘It should make for an interesting conversation when Nicola Sturgeon has her first audience with the Queen next week.’

Scottish Conservative deputy leader Jackson Carlaw added: ‘Despite all their assurances about the future of the Monarchy in Scotland, it seems SNP Ministers intend to grab all the income from the Crown Estates at the first opportunity.’

A spokesman for Buckingham Palace said: ‘Implementation of the Smith Commission’s findings, including those related to Crown Estate assets in Scotland, are a matter for the two governments and parliaments.’

 

 

@highlight

Ministers signal they won't contribute to cost of running the Royal Family

@highlight

Move comes as part of deal to hand over devolved powers to Scotland

@highlight

SNP plans to reap cash benefits of deal – while refusing to fund Monarchy

@highlight

Both Labour and the Tories round on SNP's 'narrow' view of the world 

@highlight

Crown Estate's profits will be down £14million a year after 'assets grab'  

@highlight

Scotland says 'we'll fund Monarchy to usual amount by general taxes'