As Andrew Luck prepares for his third NFL season, he finds himself being mentioned in same breath as Peyton Manning, Tom Brady, Aaron Rodgers and Drew Brees.

And just to increase the hype, Indianapolis’ past meets the present at Mile High as the Colts face the Denver Broncos.

It is Luck’s lot to endure constant comparisons with Manning.

Following in famous footsteps: Andrew Luck has had constant comparisons with Peyton Manning throughout his NFL career

After all, both are the offspring of NFL quarterbacks, Heisman runners-up and were taken by the Colts as the first overall draft pick.

‘If you are a fan of the NFL I am sure the storyline is intriguing,’ Luck says.

‘I know from my perspective I don’t have to worry about Peyton Manning, I have to worry about the Denver Broncos defense and it is a darn good one. I am sure it’s a fun storyline for the fans and media to get around.’

As Luck prepares to take his career to the next level, he can reflect on a successful sophomore season.

On the way to winning the AFC South, the Colts inflicted a first defeat on Manning’s Broncos and found a way to outscore eventual champions Seattle.

In the post-season, he orchestrated the second biggest play-off comeback in NFL history against the Chiefs, but threw seven interceptions in two games.

It was another seemingly evergreen quarterback in Brady who ended the Colts’ season and Luck would watch fellow 2012 draft classmate Russell Wilson helping Seattle to stampede the Broncos in February’s Super Bowl.

Does he fear a backlash following the one-sided rout?

‘I am not too worried about what their motivation is to come out and play well. I think any professional team is going in to come out and do their best to try to win, I am sure they are not happy about losing the Super Bowl but they are a great team still and I am sure they will play very hard.’

On the rise: Luck has 22 victories under his belt in his first two NFL seasons

With that in mind, what has Luck been addressing to help him and the Colts make the next leap?’

A big focus this offseason has been understanding situational football better. Third downs in the red zone in particular and figuring out how to get better in the red zone.

‘We need more touchdowns, can’t settle for field goal and definitely can’t turn the ball over – and how to convert third downs at a higher success rate. Offensively if we can do those I think we will be able to take the next step.

‘I know as quarterback a big part of that is understanding the situation and understanding how the defense change or adapt and what we need to do to be successful.’

The last time the Colts faced the Broncos, Robert Mathis was inspired, taking two sacks and a forced fumble. But he is suspended for four games after violating the NFL’s substance abuse policy.

But the Broncos are missing key players too: both receiver Wes Welker and Pro Bowl kicker Matt Prater are serving four-game bans.

And another hurdle for the Colts to overcome is the racket generated by Denver's fanatical fans.

‘We have had the speakers cranked up in practice to mimic the crowd noise every day. It is great preparation for how to handle communication. How you hand-check and audible at the line of scrimmage.

‘It will be a challenge but we will be prepared to handle that and as a player it is fun to play in a hostile environment, there is a little bit of a buzz in the air.’

And you suspect that buzz will be deafening if Luck gets the better of Manning again.

 

@highlight

Luck led the Colts to victory over Manning's Broncos last season 

@highlight

The teams meet again at Mile High in the 2014 NFL season curtain-raiser

@highlight

The Colts are the defending AFC South champions, while Denver were humbled by Seattle in the Super Bowl 