It may look like the control panel from a sci-fi spaceship, but this plethora of buttons and futuristic steering wheel is the cockpit of the Bloodhound supersonic car.

This is the view that driver Andy Green will see when he aims to become the first person in history to hit 1,000mph (1,609kph) on land.

The 51-year-old hopes to break the world land speed record with the £10 million rocket-powered car.

Click and drag to manipulate the cockpit below and scroll down for videos 

This is the view that driver Andy Green will see when he aims to become the first person in history to hit 1,000mph (1,609kph) on land. Click and drag to take a tour of Bloodhound SSC's cockpit

The SSC stands for ‘SuperSonic Car’ because the Bloodhound will be going faster than the speed of sound.

The vehicle has four wheels and is powered by both a jet and rocket.

It is designed to go over 1,000 miles (1,600 kilometres) per hour.

The slender body, 44 feet (14 metres) long, keeps the entire vehicle aerodynamic.

It weighs just over seven tonnes and the engines will produce more than 135,000 horsepower.

That’s more than six times the power of all the cars on a Formula 1 starting grid put together.

In the coming years the vehicle will begin test runs at lower speeds before attempting to set a new  land speed record.

The current land speed record stands at 763.035 miles (1,227.985 kilometres) per hour, set by former RAF pilot Andy Green (who will also drive the Bloodhound) back in 1997 in the ThrustSSC.

The Bloodhound will beat this record by some distance if it is successful.

The complex cockpit has been tailored to the needs of Wing Commander Green - an RAF fighter pilot - who will make his bid to smash the world record next year.

It has been made from five different types of carbon fibre weave and two different resins. It has taken more than 10,000 hours to design and manufacture in total.

Sandwiched between the layers of carbon fibre are three different thicknesses of aluminium honeycomb core, which provide additional strength. At its thickest point the hi-tech material is made up of 13 layers but measures just 24mm thick.

The structure weighs 441lbs (200kg) and bolts directly to the metallic rear chassis carrying the jet, rocket and racing car engine.

It has to be so strong as this front 
section will have to endure peak aerodynamic loads of up to three tonnes
 per square metre at 1,000mph (1,609kph) as well the considerable forces
 generated by the front wheels and suspension.

The 51-year-old RAF pilot hopes to break the world land speed record  - and with it the sound barrier - with the £10 million rocket-powered car. A model is pictured

It will also carry ballistic armour to protect Wing Commander Green should a stone be thrown up by the front wheels at very high speeds.

The roof of the cockpit has been designed to create a series of shockwaves that will channel the air into the Eurojet EJ200 jet engine.

The pencil-shaped car is 44ft (14 metres) long, 6.2 feet (1.9 metres) wide and weighs 14,158lbs (6,422kg) when fully fuelled. In its ultimate form, it is expected to generate the combined output of 95 Formula One cars.

‘Carbon fibre is an extraordinary material,’ said Wing Commander Green. ‘It is the same high-tech material from which we make jet fighters, F1 cars and in this particular case, the strongest safety cell in the history of motorsport.

‘It is a fantastic piece of technology and it needs to be phenomenally strong to take the load and thrust from 210 kilonewtons and 130,000 horsepower of engine thrust from the back of the car and to take the aerodynamic load of up to 12 tonnes per metre.’

The complex cockpit (pictured) has been tailored to the needs of Wing Commander Green, an RAF fighter pilot, who will make his bid to smash the world record next year

The car will also use a highly specialised windscreen, which has been custom-made from acrylic. The plastic is heated, stretched and then two layers are bonded together to create a 25mm section - thicker than a fighter jet’s windscreen and sufficient to withstand an impact from a 2.2lbs (1kg) bird at 900mph (1,448kph).

‘I am actually looking through two inches (5cm) of plastic which needs to be optimally perfect so I can see what I am doing,’ he said.

‘That kind of plastic is that thick and strong to survive a 1,000mph airflow and also, worst case, to take a bird strike from a big bird, maybe 4.4lbs (2kg) at 650mph (1,046kph) or half that weight approaching 1,000mph (1,609kph).’

The cockpit is positioned in front of three incredibly loud motors - the jet, a cluster of hybrid rockets and the racing car engine that drives the rocket’s oxidiser pump, which are expected to generate a noise level estimated at 140 decibels - the equivalent to a shotgun blast.

Wing Commander Green (pictured left) will wear a 
specially made in-ear communications system to protect his hearing and 
to ensure that he can communicate with mission control during his blisteringly fast drive (illustrated right)

The structure (pictured) weighs 441lbs (200kg) and bolts directly to the metallic rear chassis carrying the jet, rocket and racing car engine

Wing Commander Green will wear a specially made in-ear communications system to protect his hearing and to ensure that he can communicate with mission control.

He has drawn on his experience of flying fast jets and driving world land speed record winners Thrust SSC and JCB Dieselmax to design the dashboard and cockpit layout.

He will climb into the Bloodhound via a carbon fibre hatch, eight inches (50cm) in diameter, just below the jet air intake.

During a 1,000mph (1,609kph) run, Bloodhound will cover 12 miles (19km) in two minutes, exerting an acceleration force of almost 2G and peak deceleration force of 3G on its driver.

This long-duration G force is another experience unique to Bloodhound. Formula One drivers may experience higher G forces, but they only do so for a few seconds at a time.

Wing Commander Green said: ‘All of this technology will give me the most extraordinary working environment with which to get Bloodhound up to 1,000mph and also the highest level of protection we can possibly get. It’s a brilliant piece of engineering.’

The Bristol-based Bloodhound team will be attempting to break the 1,000mph (1,609kph) barrier on a purpose-built 12-mile track in the South African desert in 2015 and 2016.

The Bristol-based Bloodhound team will be attempting to break the 1,000mph (1,609kph) barrier on a purpose-built 12-mile track in the South African desert in 2015 and 2016. An illustration of the attempt is pictured

The team behind the Bloodhound SSC have revealed how they intend to slow it from 1,000 miles (1,600 kilometres) per hour to zero.

The engineers based in Bristol have been trying to find brakes that can withstand the huge temperatures and stresses of the vehicle - and they might now have the answer.

After the car reaches its top speed, air brakes and parachutes will slow it to 160 miles (260 kilometres) per hour.

Breaking to this speed is done at a constant 3G deceleration - equivalent to going from 60 miles (95 kilometres) per hour in a normal car to zero in one second - for 20 seconds.

This last stint to zero is where the problem lies, however. Even at this speed the cars wheels are still spinning 10,000 times per minute.

Attempts to use carbon rotors from a jet fighter in the form of car-like disc brakes shattered at speeds of just half this, so the team needed a new approach.

Instead, they switched to steel rotors from brake manufacturer AP Racing. In tests these proved much more promising, withstanding temperatures of up to 850°C (1,560°F). They even survived to such an extent that they can be used again.

The next step will be to test these brakes out at the full 10,000rpm that will be experienced. But hopes are high that they could be the solution to bring the Bloodhound safely to a halt.

@highlight

The cockpit of Bloodhound SSC is made from layers of carbon fibre

@highlight

It took 10,000 hours to design and manufacture

@highlight

The structure weighs 441lbs (200kg) and has to be strong to withstand forces generated by the front wheels and suspension

@highlight

Driver Andy Green will use the controls in a bid to become the first person in history to hit 1,000mph (1,609kph) on land

@highlight

He hopes to break the world land speed record with the £10 million car

@highlight

First record attempt will take place in the South African desert next year