By 
Jack Doyle and James Slack

PUBLISHED:

19:14 EST, 9 September 2013


| 

UPDATED:

02:06 EST, 10 September 2013

The Information Commissioner Christopher Graham will come under huge pressure from MPs today to release the list

The Information Commissioner will come under huge pressure from MPs today to allow the release of an explosive list of blue-chip companies who hired corrupt private detectives.

Christopher Graham is demanding the Home Affairs select committee withhold the list while he conducts a criminal investigation over potential breaches of data protection laws.

But the committee gave the Serious Organised Crime Agency (Soca) an ultimatum to publish the list or the MPs would do so.

Their deadline passed last night without Soca taking any action.

MPs on the committee were ready to publish the dossier, but have delayed after objections from police and Mr Graham, who will appear before MPs this afternoon after he was summoned late on Sunday night by committee chairman Keith Vaz.

They will want to probe his claim that they could scupper the investigation by publishing the list of 98 names compiled by the Serious Organised Crime Agency.

The number had been thought to be 102 but when Soca handed the list to the Information Commissioner’s Office (ICO), several names were withheld which are the subject of a separate Metropolitan Police investigation.

At least 33 names from the list have already leaked out, including that of X Factor creator Simon Cowell. Blue-chip firms also understood to feature include banking giant Credit Suisse, accountancy firm Deloitte as well as insurance company Allianz.

Last week, Mr Vaz said it was in the ‘public interest’ to name the firms and individuals who have paid private detectives convicted of corrupt practices. However, Mr Graham has insisted doing so could undermine his investigation.

In a blog post on Sunday he wrote: ‘It’s not clever to start a criminal investigation by publishing the names of everyone and everything you’re investigating.’

Keith Vaz (left) said last week it was in the 'public interest' to name the firms who have paid private detectives convicted of corrupt practices. At least 33 names have already leaked out including Simon Cowell (right)

He said it was ‘not fair’ those on the list could learn of their inclusion from a committee of MPs.

He added: ‘We have to start from the central principle of  British justice that some of the 98 may not have broken any law.

'The criminal offence associated with “unauthorised disclosure” of personal information depends on the prosecution establishing that the clients knew that the information they were seeking would be, or could only be, obtained by unlawful means. That will be central to the ICO’s investigation.’

Mr Graham’s office was belatedly handed the list by Soca at the end of August after weeks of pressure.

The ICO is to write to the celebrities, law firms, banks and other companies to ask them what they knew about the activities of the investigators they were using.

Mr Graham said investigators will also have to examine more than 30 files generated by Operation Millipede, the Soca probe which resulted in the jailing of four rogue investigators last year.

The existence of the list emerged during an investigation by the committee. Soca, dubbed  ‘Britain’s FBI’, refused to publish it on the grounds it could breach privacy laws, and damage commercial interests.

But critics claim nothing was being done about a scandal akin to newspaper phone hacking.

Soca said it always intended to pass the list to the ICO once the Met investigation was over.

@highlight

Christopher Graham has demanded MPs withhold list while criminal investigation into potential breaches of data protection laws takes place

@highlight

Home Affairs select committee told Soca to publish or they would

@highlight

Deadline has passed without Soca taking any action