By 
Hayley O'keeffe

PUBLISHED:

07:49 EST, 14 November 2013


| 

UPDATED:

10:45 EST, 14 November 2013

Aeroplane passengers will soon be able to make calls, send emails and surf the internet during take-off and landing after a relaxation of safety rules.

The changes have been in place in the US since November 1, but the European Aviation Safety Authority announced that it is to follow suit this week.

Devices were allowed on some European aircraft in the past, but only at certain stages of the flight amid concerns over safety.

But in December the rules will change, 
after data showed that signals generated by the equipment do not affect 
how aircrafts function.

European planes, including the Airbus A380 will soon offer passengers the opportunity to use mobile phones and other gadgets during take-off and landing

Airlines who want to offer the service for the first time will now have to install technology onto the planes to enable devices to be used.

Some companies may choose to charge passengers if they want to use their mobile phones, laptops or other gadgets while on board.

Iilias Maragakis, policy officer at the European Aviation Safety Agency, said: 'What is important is that we give European airlines the ability to use new technology.

European airlines may have to install new technology in order to take advantage of the rule change

'Why not just address reality, it was good to be cautious at the beginning but data shows that if these devices are switched off the difference is negligible.'

In an announcement this week the agency said that it will publish guidance on the new changes by the end of this month.

Patrick Ky, executive director of the safety watchdog, said: 'This is a major step in the process of expanding the freedom to use personal electronic devices on-board aircraft without compromise in safety.'

According to the announcement, any bulky electronic devices such as laptops will still have to be stowed away during take-off and landing, and passenger will have to set their equipment to flight mode while on board.

@highlight

Safety rules to be relaxed for all European airlines from December

@highlight

Data shows that there is no real aviation safety risk from devices

@highlight

Airlines may have to install new technology to take advantage