Newly released statistics has shown which EU countries benefited most from illegal activities being included in the GDP.

Italy saw its 2010 GDP jump by one per cent, the biggest boost to any economy in the European Union, when including 'estimated illegal activities'.

Italy's increase thanks to drugs and prostitution was five times the average 0.2 per cent for the OECD as a whole.

Boost: Italy's 2010 GDP increased by a full one per cent when including 'estimated illegal activities' such as sales of drugs and prostitution -  five times the average 0.2 per cent for the OECD as a whole

In contrast, the inclusion of 'Research & Development' in GDP saw a four per cent boost for Sweden and Finland, but only a 1.3 per cent increase in Italy - a marginally bigger impact that prostitution.

Spain is hot on Italy's heels with a 0.9 per cent jump when including money generated by drug trafficking, prostitution, smuggling and illegal gambling.

Last year, the calculation of GDP was changed to include Class A drugs trade and the ‘provision of prostitution services’.

A revision to the 2010 GDP carried out by Brussels-based thinktank Bruegel shows that the two southern European nations were the ones to benefit the most from the inclusion of illegal activities. 

Last year, Spain's National Statistics Institute reported that money generated by drug trafficking, prostitution, smuggling and illegal gambling contributed some 9billion euros (£7billion) to the national economy last year 

Contrast: The inclusion of 'Research & Development' in GDP saw a four per cent boost for Sweden and Finland, but only a 1.3 per cent increase in Italy - a marginally bigger impact that prostitution

The figures are being included in GDP calculations on the recommendation of the European Union, which is trying to harmonize estimates across member states and get a full picture of economic activity, whether legal or not. 

The darker corners of the economy are now being measured - alongside traditional sectors such as farming and financial services - as part of an overhaul in the way economic activity is calculated.

The GDP covers every sector - from manufacturing and construction to agriculture, public services and tourism.

It now also covers the import, production and sale of illegal drugs and the ‘provision of prostitution services’.

The data classes growing drugs or importing them as ‘production’, buying them for home use as ‘expenditure’ and selling them as ‘income’.

It covers crack cocaine, powder cocaine, heroin, cannabis, ecstasy and amphetamines. 

@highlight

Italy's GDP up by one per cent when including 'estimated illegal activities'

@highlight

Spain followed with a 0.9 per cent boost thanks to prostitution and drugs

@highlight

The average for the European Union as a whole was 0.2 per cent