A fizzy drinks tax could save thousands of children from diabetes, a study has claimed (file photo)

Thousands of children would be saved from diabetes, cancer and heart disease later in life if a 20p tax is added to the cost of sugary drinks, researchers have claimed.

Health experts and Boris Johnson’s food adviser in London are pushing the idea under moves by the mayor and local authorities to devolve some taxation powers to the capital.

Academics from the University of Liverpool calculated the effects of introducing a tax equivalent to 20p per litre in London with the aim of reducing consumption of the high-calorie drinks over 20 years.

They calculated the levy would prevent 1,100 cases of cancer in the capital, reduce the number of people who develop diabetes by 6,300 and cut 4,300 from the total of those who suffer from coronary heart disease or strokes.

The work also suggests the health service in London would save around £39million over 20 years.

Based on these numbers, tens of thousands of disease cases nationwide could be prevented if the 20p per litre tax was adopted across the entire country.

The figures were released by the Children’s Food Campaign, which proposes that any revenue generated by the tax would pay for programmes to improve children’s health.

Malcolm Clark, Campaign co-ordinator of the CFC, said: ‘A duty on sugary drinks of 20 pence per litre would be the most practical and effective way of tackling a significant source of unnecessary calories and sugar in children and young people’s diets.

‘Mexico, France and Hungary have introduced a sugary drinks duty, and their citizens are reaping the benefits.

'Our politicians can no longer hide behind the idea that it wouldn’t be popular, or is an untried policy.

‘We urge London’s mayor and council leaders to include a sugary drinks duty in their review of how London might manage devolved taxation powers, and to make the case to Westminster for the introduction of such a duty nationally.' 

More than 60 organisations – including the Academy of Medical Royal Colleges, the British Dietetic Association, the Faculty of Public Health, CitizensUK, Netmums and Unison – have already backed the campaign.

Rosie Boycott, who was appointed by Mr Johnson to run the London Food Board, said: ‘We need a tax on sugary drinks.

Unhealthy: The proposed measure is the latest in a long line to curb deteriorating public health (file photo)

‘Sweetened fizzy drinks offer nothing to a city already suffering high levels of obesity-related diseases and dental decay,’ she said.

‘It would be good for our health and the environment if we drank less of them. In many areas, London has already been leading the charge in the battle to eat well.

'But we also need national action to ensure firms contribute to the overall health bill and encourage consumers to swap to healthier products.'

Soft drinks are the largest single source of sugar for children aged four to ten and teenagers. A tax of 20p a litre would add around 7p to the price of a can of Coca-Cola or Pepsi.

The idea is also supported by the internationally renowned surgeon Lord Darzi, of Imperial College London. 

Gavin Partington, the director general of the British Soft Drinks Association, said: ‘This is a poorly thought out political proposal which will hit the poorest hardest while doing nothing to curb obesity, the causes of which are far more complex than this simplistic approach implies.

‘Evidence from France shows that while sales of soft drinks fell after a tax was introduced in 2012, they have increased since, with sales up 6 per cent in the first four months of this year.

‘Policy should be based on evidence, not a tendentious report based on a flawed model.’

@highlight

Tax proposed by Children's Food Campaign would be 20p per litre

@highlight

That would add another 7p to every can of lemonade, Coke or Pepsi

@highlight

Research suggested it could save 6,000 from diabetes in London alone