All-seeing eye: Scientists have developed a prototype contact lens that could one day provide the wearer with the news, texts and social networking

Imagine catching up with your texts, social networking and perhaps the news  without having to log on to a computer or even glance at  a smartphone.

Messages and images would simply appear in front of your eyes, generated by a computerised contact lens.

Of course, you may not always want to be bothered by such messages if you are doing anything so quaint as – for instance – reading a book or going out walking and enjoying the scenery.

But until now the concept of info-vision – the ability to stream information across a person’s field of vision – had belonged to the realms of science fiction, featuring in films such as the Terminator series or TV shows such as Torchwood.

However, scientists have developed a prototype lens that could one day provide the wearer with all kinds of hands-free information.

It could also be used to display directions and TV programmes.

The lenses, which would be inserted and removed like normal contacts, could also be handy if you are indeed enjoying the great outdoors, allowing you to zoom in on distant views.

While the amount of information that could appear in front of our faces is tantalising, the researchers insist all the components are tiny and the normal field of vision will not be obstructed.

One day, perhaps? How the new information contact lens could work

The super-lenses are the brainchild of Professor Babak Parviz, a contact lens-wearing engineer who specialises in making parts on the nanoscale, thousands of times thinner than a human hair.

Pugh's take on the development

So far, he has created a lens which is implanted with tiny components, including a single LED light, an antenna that picks up power and information through a wireless connection, and an electronic circuit.

The lens was placed into a rabbit’s eye without causing any problems to its health and the light came on.

Professor Parviz, of the University of Washington in Seattle, said: ‘We have got a rudimentary display with one dot. If you had several dots, you could maybe create arrows, to give people directions.’

The professor envisions that one day we will be able to stream all the information we need directly on to the contact lens.

He is also investigating the idea of incorporating sensors that will pick up blood sugar levels and other potentially important medical information.

He told the Mail: ‘The surface of the eye is covered in live cells  and the body has to keep them alive, so they are in direct contact with the bloodstream.’

A bionic eye that could restore the sight to the blind is to be tested on Britons.

Small-scale trials on the Continent have already produced ‘quite astonishing’ results.

The tiny implantable microchip allowed men and women who thought they would never be able to see again to read a clock and identify everyday objects.

Let there be light: A microchip packed with 1,500 sensors is implanted in the back of the eye. This then stimulates nerves in the retina which pass signals down the optic nerve to the brain to create an image

Now, the wafer-thin device is to be implanted in Britons for the first time, with the first operations due within weeks.

Up to 12 men and women will be treated, with the surgery taking place in Oxford and London.

If these, and similar operations in Europe, prove the device from German firm Retina Implant to be safe and effective it could be on the market by 2013.

Most of the Britons treated will be middle-age and all will have retinitis pigmentosa, a hereditary disease that destroys the light-sensitive retina at the back of the eye.

A microchip packed with 1,500 light sensors designed to replace those lost to disease is implanted in the back of the eye.

The sensors convert light to electrical signals. These stimulate nerves in the retina which pass signals down the optic nerve to the brain to turn into an image.

Robert MacLaren, the surgeon who will lead the Oxford arm of the trial, cautioned that the surgery is still experimental and the device does not work in all cases.

@highlight

Prototype could create hands-free information

@highlight

Was placed into a rabbit’s eye without causing any health problems

@highlight

Inventor also looking to incorporate sensors to pick up important medical data

@highlight

Meanwhile, Britons to try out bionic eye which could end blindness