Scientists have pinpointed exactly why rechargeable batteries, such as those used in smartphones (pictured) degrade so quickly

Many of us have owned a smartphone that only has charge for a few hours, or a laptop that is no longer portable thanks to an almost ‘dead’ battery.

But such frustration could become a thing of the past because scientists have pinpointed exactly why rechargeable batteries degrade so quickly, forcing consumers to replace them, or upgrade their devices.

Experts say that laptops and smartphones could have much longer-lasting lithium ion batteries in the future and electric cars could even have batteries that last for more than 30 years with a full charge.

In two separate studies published in Nature Communications, researchers at the U.S. Department of Energy have revealed why batteries lose the ability to hold their charge over time.

Despite the battery being around in its basic form for around 200 years, until now, scientists have failed to understand why they lose their full charge over time and as a consequence, have not been able to do much to resolve the problem.

But this has changed in the last decade thanks to cutting-edge technology such as new types of electron microscopes and synchrotron X-ray techniques, Smithsonian magazine reported

The physicists studied the charge and discharge process of lithium ion batteries, which are used in many devices and pointed the finger at microscopic vulnerabilities in the structure of the batteries and the accumulation of tiny crystals.

The physicists discovered that 
microscopic vulnerabilities steer lithium ions through the battery 
haphazardly, eroding it in an irregular manner and reducing its 
efficiency.

Experts say that laptops, smartphones could have much longer-lasting lithium-ion batteries in the future and electric cars (pictured) could even have cells that last for over 30 years with a full charge

They also noticed that deposits of nano-scale crystals that are generated by chemical reactions cause the flow of ions to become more irregular each time a battery is recharged.

Using batteries at higher voltages exacerbated such irregularities and reduced the life of the battery too.

It is hoped that the findings will lead to the development of longer-lasting, smaller and more powerful batteries that could keep phones and laptops working for much longer at their full charge.

Some experts believe that the answer lies in protecting the surface of the battery or the cathode, with an incredibly thin film.

Huolin Xin, a materials scientist at the Brookhaven National Laboratory in New York, who co-authored both studies, believes that the price of batteries for electric cars will fall radically.

As scientists understand more about battery efficiency, they could create electric car batteries that last for over three decades, he said.

The physicists discovered that microscopic vulnerabilities steer lithium ions through the battery haphazardly, eroding it in an irregular manner and reducing its efficiency. The lithium ion battery of an electric car is pictured

Scientists have at last created pure lithium batteries, which in time could last four times longer than those currently powering smartphones and other gadgets.

The ‘Holy Grail’ discovery, announced this week, could revolutionise technology from electric cars to consumer devices like MP3 players, which all demand power storage.

Currently, owners of gadgets using the lithium ion batteries face the constant frustration of having to frequently recharge devices to make sure they do not run out of battery after a matter of hours. This is because while small, the batteries are power-hungry.

But after years of research, engineers at Stanford University, California, believe they have worked out how to keep them the same size, while boosting their longevity.

To do this, they have made the battery's anode out of lithium too. Scientists have been working for years to produce an anode of pure lithium, because it would be cheap, small and be a huge boost to battery efficiency.

The engineers managed to create a lithium anode by inventing a film made from carbon nanospheres to protect the anode and stop it from cracking when it expands.

The nanospheres create a surface resembling a honeycomb to make a flexible, uniform and non-reactive film that protects the unstable lithium.

‘Of all the materials that one might use in an anode, lithium has the greatest potential. Some might call it the Holy Grail,’ said Professor Yi Cui of the university.

‘It is very lightweight and it has the highest energy density. You get more power per volume and weight, leading to lighter, smaller batteries with more power.’

‘In practical terms, if we can improve the capacity of batteries to, say, four times today's, that would be exciting.'

@highlight

Scientists at the U.S. Department of Energy found microscopic vulnerabilities in the structure of batteries are to blame for degradation

@highlight

The accumulation of tiny crystals also contributes to the problem

@highlight

Physicists studied the charge and discharge process of lithium ion batteries, which are found in many consumer devices such as phones and laptops

@highlight

By understanding why lithium ion batteries lose their full charge over time, longer lasting versions could be developed

@highlight

This could lead to electric car batteries enduring for over 30 years