The European Commission has revealed that Ireland could be granting Apple illegal rebates worth billions of dollars which may have to be repaid.

If the EU's initial findings are confirmed over the coming months, Apple could face a massive repayment bill because it funnels the bulk of its international sales through subsidiaries in Ireland, where it benefits from low, negotiated tax deals.

In a letter to the Irish government published on Tuesday, the European Commission, which is carrying out an investigation into Apple's overseas tax practices, said the treatment granted to Apple 'constitutes state aid' and therefore raises 'doubts about the compatibility' with EU law.

Scroll down for video 

Merrion Street: The European Commission has written a letter to the Irish government stating that tax arrangements between the Republic and Apple may not be compatible with EU law

EU rules forbid governments from helping companies to avoid undermining free market competition. The EU first announced the probe in June, also targeting coffee store chain Starbucks and others as part of a crackdown on multinationals exploiting tax loopholes.

The EU Commission is now requesting further documents from Ireland before making a legally binding decision on whether the rebate granted to Apple is illegal and must be recouped, wholly or partially.

The EU probe focuses on exaggerated transfer pricing, where one part of a company charges another part an inflated price for goods or services to shift profits to low-tax locations.

If Apple had to repay some taxes, the money would come as a windfall to Irish state coffers. However, fearful of losing its reputation as a business-friendly country with low corporate taxes, the Irish government is adamant that no EU rules have been breached.

The Commission, however, said in the letter that the tax deals struck with Apple in 1991 and in 2007 show 'several inconsistencies' and may not comply with international taxation standards. 

The Brussels-based executive body also was critical of the fact that Apple's applicable tax rate appears to have been the result of 'a negotiation rather than a pricing methodology' which a 'prudent, independent' tax authority should not have accepted.

Irish presence: Apple has a large distribution centre on an industrial estate on the outskirts of Cork

Apple's tax practices have also attracted scrutiny in the United States, where a Senate Committee last year published a scathing report on the Cupertino-based firm's tax schemes. 

The report held up Apple as an example of legal tax avoidance made possible by the complicated U.S. tax code, estimating the firm avoided at least $3.5 billion (£2.1 million) in U.S. federal taxes in 2011 and $9 billion in 2012 by using its tax strategy.

Apple - one the world's most valuable and profitable firms - sat on some $164 billion in cash and cash equivalents, with $138 billion stashed away in foreign subsidiaries, according to its latest quarterly report in June. 

The company estimated its effective U.S. tax rate is 26.1 percent, as opposed to the statutory U.S. rate of 35 percent, primarily because of undistributed foreign earnings.

A 'substantial portion' of those foreign earnings was generated by subsidiaries organised in Ireland, Apple said in the regulatory filing, adding that 'such earnings are intended to be indefinitely reinvested outside the U.S'.

@highlight

European Commission probe criticises Ireland over tax deals with Apple

@highlight

Cupertino-based tech giant may be landed with massive repayment bill

@highlight

Irish government told that the deals may not be compatible with EU law