By
Daily Mail Reporter

The Government must crack down on untaxed foreign cars on British roads, the RAC has said.

Around 60,000 non-UK vehicles are registered with the Driver and Vehicle Licensing Agency (DVLA) every year but an estimated 15,000 are not registered, the RAC said.

It means that around £3 million in vehicle excise duty (VED) is not being collected each year, the RAC added.

The Government must crack down on untaxed foreign cars on British roads, the RAC has said

The RAC said that under current regulations visiting non-UK cars must be registered with the DVLA once they have been in the UK for six months when they must pay a £55 first registration fee, ensure they have paid VED, obtain an MOT if the vehicle is over three years old and in some instances pay VAT.

Around 60,000 non-UK vehicles are registered with the Driver and Vehicle Licensing Agency (DVLA) every year but an estimated 15,000 are not registered, the RAC said

The RAC added: 'However, despite the fact the UK Border Force gathers details of every non-UK vehicle entering and leaving the country this information is not currently used by the DVLA for licensing purposes, which means the Government is missing out on valuable tax revenue.

'And, as the DVLA has no idea whether non-UK-registered vehicles have stayed in the country longer than six months, many over three years may well not have a valid MOT and therefore will be contravening insurance rules, thereby compromising the safety of all road users.

'The lack 
of a record also means that EU-registered and other foreign vehicles are
 more likely to evade fines generated by the UK's army of speed cameras -
 a further source of revenue that could be ploughed back into the 
country's roads.'

RAC
 head of external affairs Pete Williams said: 'Given the prevalence of 
technology such as automatic number plate recognition, it is beyond 
belief that in the 21st century two important

Government
 agencies - namely the UK Border Force and DVLA - are not already 
sharing information in a system that allows us to keep track of the 
comings and goings of non-UK vehicles.

'We
 understand that DVLA, the UK Border Force and the police are looking at
 how data can be used to identify foreign-registered vehicles that have 
been in the UK for longer than six months, so we urge the Government to 
make finding an effective solution a high priority.'ends

@highlight

Around 60,000 non-UK vehicles are registered with the Driver and Vehicle Licensing Agency (DVLA) every year

@highlight

But an estimated 15,000 are not registered, the RAC said