In two years Chancellor George Osborne will be taking £1billion a year in tax from lottery tickets, it has been forecast

The biggest winner from the imminent revamp of the National Lottery will be the Treasury, independent analysts said yesterday.

They forecast that two years from now, Chancellor George Osborne will be taking £1billion a year in tax from lottery tickets – almost double the State’s share of the takings before the onset of the economic downturn.

The estimate means the Treasury is due to double its money following the doubling of the price of a Lotto ticket to £2 this autumn.

Analysts GBGC said the record take for the Government reflects the efficiency of Camelot’s stewardship of the lottery and the affordability of Lotto and Euromillions tickets and scratch cards.

But critics say ministers are increasing a stealth tax on those who have a flutter in the belief that they are helping good causes.

The new estimates come in advance of the first increase in the price of tickets for the main Lotto game since it was launched nearly 20 years ago.

The relaunch is designed to bring regular £5million weekend jackpots, but a family accustomed to a £5 weekly gamble will find themselves paying £10 for the same chance of winning.

Duty paid on National Lottery tickets runs at 12 per cent, and from the game’s beginnings in 1994 until 2007 the amount paid to the Treasury each year ran at between £500million and £600million.

But the Government’s take has been rising steeply in line with tickets since the onset of the downturn, the figures show. It topped £800million last year and will hit £1billion in two years’ time, they indicated.

The estimate means the Treasury is due to double its money following the doubling of the price of a Lotto ticket to £2 this autumn

For every £1 spent on the lottery, 50p is paid to winners, 28p goes to good causes, 5p to retailers, 5p to the operator – and 12p to the Treasury.

The report from GBGC, Global Betting and Gaming Consultants, said: ‘The last few years have each seen record-breaking amounts of duty generated by the National Lottery’s performance. The forthcoming ticket and prize increases will spur further sales increases and, therefore, increase the amount the Government receives in duty.’

But economist Ruth Lea of the Arbuthnot Banking Group said: ‘The lottery was always sold on the basis that …players were first and foremost supporting good causes.

‘People might be unpleasantly surprised at how much they are paying to HM Government.’

@highlight

Treasury to double its money when the price of a Lotto ticket doubles to £2

@highlight

Critics say it's a stealth tax on those who believe they're helping charity

@highlight

This year sees first Lotto price increase in 20 year history