By
Jonathan O'Callaghan

The frustration of losing your mobile phone could soon be a thing of the past thanks to new technology that could print it on a T-shirt.

Scientists have designed the world's first 'spaser' - a nanoscale laser - made out of graphene and carbon.

They claim the spaser is so small it will be used to print tiny microchips that can be attached to T-shirts or other items of clothing, and used to power mobile phones.

Scientists have designed the world's first 'spaser' - a nanoscale laser - made out of graphene and carbon. Artist's impression pictured. They claim the spaser is so small it will be used to print nanoscale microchips which can then be attached to clothing and other flexible surfaces

The electrical current in the technology could even be used to target and kill cancer cells within the human body.

'Other spasers are made of gold or silver nanoparticles and semiconductor quantum dots,' said lead researcher Chanaka Rupasinghe, from Monash University Department of Electrical and Computer Systems Engineering in Melbourne, Australia.

A spaser (surface plasmon amplication by stimulated emission of radiation) is effectively a nanoscale laser, or a nanonlaser.

It has been touted as the future of optical computers and technologies.

It could enable â€˜nanophotonicâ€™ circuitry, extremely small circuits far tinier than anything available today.

This could usher in many technological advances including hyperlenses, which could lead to microscopes ten times more powerful than anything we have today.

'Our device would be comprised of a graphene resonator and a carbon nanotube gain element.'

'The use of carbon means our spaser would be more robust and flexible, would operate at high temperatures, and be eco-friendly.

'Because of these properties, there is the possibility that in the future an extremely thin mobile phone could be printed on clothing.'

At present spasers are used to make microprocessors, memories and screens smaller, and more portable.

However the new spaser, made using graphene and carbon nanotubes, would be over a hundred times stronger than steel and is a better conductor than copper.

It can also withstand extremely high temperatures.

Researchers found that graphene and carbon nanotubes can transfer energy to each other through light, and as a result could be used to create a high-tech substitute for microchips.

The research claims that as mobile phone technology becomes smaller and more efficient, it could be embedded into our clothes, along with these nanoscale microchips and other circuitry. Stock image pictured

'Graphene and carbon nanotubes can be used in applications where you need strong, lightweight, conducting, and thermally stable materials due to their outstanding mechanical, electrical and optical properties.

'They have been tested as nanoscale antennas, electric conductors and waveguides,' continued Rupasinghe.

Researchers also hope the new spaser could be used in cancer research as a new way of destroying cancer cells, as the electric field generated by the spaser can destroy them without harming healthy ones.

Rupasinghe said: 'Scientists have already found ways to guide nanoparticles close to cancer cells.

'We can move graphene and carbon nanotubes following those techniques and use the high concentrate fields generated through the spasing phenomena to destroy individual cancer cells without harming the healthy cells in the body.'

@highlight

World's first carbon-only nanoscale laser has been designed in Australia

@highlight

The research was carried out by a team at Monash University

@highlight

It builds tiny microchips that can be used in small, flexible devices

@highlight

This nanolaser is so small it could usher in technological advances

@highlight

For example, experts said it could lead to phones being printed onto fabric

@highlight

The chips could also be used to target cancer cells in the human body