Hurricane Simon has rapidly strengthened in Pacific waters hundreds of miles off the tip of Mexico's Baja California Peninsula.

The U.S. National Hurricane Center in Miami says Simon's maximum sustained winds reached at 110 mph (175 kph) on Saturday. 

Forecasters say Simon is expected to become a major hurricane in coming hours and then begin to weaken Sunday.

Strengthening: The U.S. National Hurricane Center in Miami says Simon's maximum sustained winds reached at 110 mph (175 kph) on Saturday. It is currently 310 miles off the southern tip of Mexico's Baja peninsula

The center says the hurricane is centered about 310 miles (500 kilometers) southwest of the southern tip of the Baja peninsula and is moving west-northwest at 13 mph (20 kph). 

There are no coastal watches or warnings in effect.

Simon is expected to produce two to four inches or more of rainfall in southwestern Mexico and swells generated by the hurricane could cause life-threatening surf and rip current conditions. 

Accoridng to AccuWeather it is set to remain offshore, but rain will still batter parts of Baja California Sur, Sinaloa and western Sonora. 

It will also create rough surf making it hazardous for beach-goers and operators of small craft along the northwestern Mexico coast.

Meteorologists for the site say the downpours could continue into next week, but thunderstorms will gradually fade away. 

Some parts of the coast in Mexico and southern California could face power outages and tree damages as a result. 

A satellite image by the NOAA shows the hurricane growing off the west coast of Mexico on Friday. Meteorologists say it has now become a major hurricane 

 

@highlight

Storm is located hundreds of miles off the Baja California Peninsula

@highlight

Is expected to produce two to four inches of rain in south west Mexico 

@highlight

Will produce life-threatening conditions for surfers and beach-goers 

@highlight

Some of the moisture is predicted to reach southern parts of California 