By
Jonathan O'Callaghan

A devastating 'impact winter', brought on by an asteroid strike 66 million years ago, is being blamed for wiping out the dinosaurs.

Researchers have discovered the first physical evidence that global temperatures suddenly plummeted following the impact off Mexico's Yucatan Peninsula.

Its effects would have been identical to those seen in the aftermath of a large-scale nuclear war, including the chilling effect of dust blotting out of the sun.

Research suggests a devastating 'impact winter' wiped out the dinosaurs after a six-mile-wide (10km) asteroid slammed into the Earth 66 million years ago. The study is the first to provide physical evidence for the sudden plunge in global temperatures that followed the impact off Mexico's Yucatan Peninsula. Illustration pictured

Computer 
simulations suggest a hellish environment in the first hours following the 
impact, marked by earthquakes, tsunamis and global wildfires sparked by 
an intense heat pulse.

Next, dust and sulphur droplets would have collected in the atmosphere and blocked out the sun's rays.

The effect may have been made worse by heat-absorbing soot from burning organic matter, said the researchers.

The
 'dark phase' would have temporarily suppressed the photosynthesis of 
green plants and algae, causing a 'global collapse of terrestrial and 
marine food webs'.

According
 to the models, the amount of sunlight reaching the Earth's surface 
might have been reduced to around 20 per cent of its normal level after the 
impact.

According to the research, the 'Chicxulub' impact is likely to have brought about this 'nuclear winter' by lowering global sea surface temperatures by as much as 7°C (45°F) at a conservative estimate.

For creatures evolved to live in a lush, warm, green world, the result would have been catastrophic.

The 'winter' is thought to have lasted no more than two to three decades, but that was long enough to wipe out the dinosaurs, flying and swimming reptiles, and many other forms of life.

Only the most adaptable survived, leading to the reign of the birds and mammals that continues to this day.

The evidence comes from the Brazos River region of Texas, where sedimentary rocks the same age as the asteroid impact contain layers of broken shells.

They are thought to have been left there by a tsunami triggered when the massive space rock plunged into the ocean.

Unusually high concentrations of iridium produced as the asteroid vapourised were also found in the sediments.

An idea of post-impact sea surface temperatures was obtained by analysing fatty molecules from marine organisms preserved in these rocks.

According to the study, the 'Chicxulub' impact is likely to have lowered global sea surface temperatures by as much as 7°C (45°F) at a conservative estimate. For creatures evolved to live in a lush, warm, green world, the result would have been catastrophic

These had a different signature before and after the event, also known as the Cretaceous-Paleogene (K-Pg) boundary impact.

They
 indicated a significant temperature drop compared with the period just 
before the asteroid struck, with some samples suggesting a fall of up to
 7°C (45°F).

Scientists recently reconstructed one of 
the biggest asteroid impacts ever to hit Earth - and claim it was six 
times as big as the blast than wiped out the dinosaurs.

A huge asteroid is believed to have hit Earth 3.26 billion years 
ago, creating unique geological features found in a South African region
 known as the Barberton greenstone belt.

Researcher said the impact would have boiled oceans, burned the sky, and cause the planet to shake for 30 minutes.

The
 huge impactor - between 23 and 36 miles (37 and 58km) wide - 
collided with the planet at 12 miles (20km) per second.

The
 jolt, bigger than a 10.8 magnitude earthquake, propelled seismic waves 
hundreds of kilometers through the Earth, breaking rocks and setting off
 other large earthquakes.

Tsunamis
 thousands of metres deep - far bigger than recent tsunamis generated by
 earthquakes - swept across the oceans that covered most of the Earth at
 that time.

The
 scientists, led by Dr Johan Vellekoop, from Utrecht University in the 
Netherlands, wrote in the journal Proceedings Of The National Academy Of
 Sciences: 'The global impact winter, characterised by darkness and a 
dramatic cooling of ocean surface waters, perturbed a relatively stable,
 warm, latest Cretaceous climate and likely represented a major stress 
factor for life on Earth.'

Computer simulations suggest a hellish environment in the first hours after the impact marked by earthquakes, tsunamis and global wildfires sparked by an intense heat pulse.

Next, dust and sulphur droplets would have collected in the atmosphere and blocked out the sun's rays.

The effect may have been made worse by heat-absorbing soot from burning organic matter, said the researchers.

The 'dark phase' would have temporarily suppressed the photosynthesis of green plants and algae, causing a 'global collapse of terrestrial and marine food webs'.

According to the models, the amount of sunlight reaching the Earth's surface might have been reduced to around 20% of its normal level after the impact.

The contrast between still-warm oceans and cold air would have fuelled large storms and hurricanes, whipping up more dust and increasing the time it spent in the atmosphere.

Ocean life might also have been affected by the acidification of seawater caused by a fall-out of sulphurous particles raining down from the sky.

The researchers concluded: 'The K-Pg boundary impact presents a unique event in Earth history because it caused global change at an unparalleled rate. This detailed portrayal of the environmental consequences of the K-Pg impact and aftermath aids in our understanding of truly rapid climate change.'

@highlight

Study suggests a 'nuclear winter' followed the dinosaur extinction event

@highlight

Researchers from Utrecht University claim an asteroid impact altered Earth

@highlight

The effects would have been similar to the aftermath of a nuclear war

@highlight

The amount of sunlight could have dropped to 20% of its current level

@highlight

This would have lasted decades and wiped out any life that survived the hit