By
Mark Prigg

Scientists have reconstructed one of the biggest asteroid impacts ever to hit Earth - and say it was six times as big as the blast than wiped out the dinosaurs.

The 36 mile wide asteroid is believed to have hit Earth 3.26 billion years ago, creating unique geological features found in a South African region known as the Barberton greenstone belt.

Researcher say the impact would have boiled oceans, burned the sky, and cause the planet to shake for 30 minutes.

The massive asteroid was almost as wide as Rhode Island and about three to five times larger than the rock thought to have wiped out the dinosaurs.

The huge impactor – between 37 and 58 kilometers (23 to 36 miles) wide – collided with the planet at 20 kilometers per second (12 miles per second).

The jolt, bigger than a 10.8 magnitude earthquake, propelled seismic waves hundreds of kilometers through the Earth, breaking rocks and setting off other large earthquakes.

Tsunamis thousands of meters deep – far bigger than recent tsunamis generated by earthquakes — swept across the oceans that covered most of the Earth at that time.

The collision punched a crater into the planet’s crust that’s nearly 500 kilometers (about 300 miles) across: greater than the distance from Washington, D.C. to New York City, and up to two and a half times larger in diameter than the hole formed by the dinosaur-killing asteroid.

Seismic waves bigger than any recorded earthquakes shake the planet for about half an hour at any one location – about six times longer than the huge earthquake that struck Japan three years ago.

The impact also sets off tsunamis many times deeper than the one that followed the Japanese quake.

Although scientists had previously hypothesized enormous ancient impacts, much greater than the one that may have eliminated the dinosaurs 65 million years ago, now a new study reveals the power and scale of a cataclysmic event some 3.26 billion years ago which is thought to have created geological features found in a South African region known as the Barberton greenstone belt. 

The research has been accepted for publication in Geochemistry, Geophysics, Geosystems, a journal of the American Geophysical Union.

The collision punches a crater into the planet¿s crust that¿s nearly 500 kilometers (about 300 miles) across: greater than the distance from Washington, D.C. to New York City, and up to two and a half times larger in diameter than the hole formed by the dinosaur-killing asteroid.

The sky would have become red hot, the atmosphere would have been filled with dust and the tops of oceans would have boiled, the researchers said.

The impact sent vaporized rock into the atmosphere, which encircled the globe and condensed into liquid droplets before solidifying and falling to the surface, according to the researchers.

Tsunamis thousands of meters deep – far bigger than recent tsunamis generated by earthquakes — swept across the oceans that covered most of the Earth at that time.

The huge impactor – between 37 and 58 kilometers (23 to 36 miles) wide – collided with the planet at 20 kilometers per second (12 miles per second).

The jolt, bigger than a 10.8 magnitude earthquake, propelled seismic waves hundreds of kilometers through the Earth, breaking rocks and setting off other large earthquakes.

Tsunamis thousands of meters deep – far bigger than recent tsunamis generated by earthquakes — swept across the oceans that covered most of the Earth at that time.

'We knew it was big, but we didn’t know how big,' Donald Lowe, a geologist at Stanford University and a co-author of the study, said of the asteroid.

Lowe, who discovered telltale rock formations in the Barberton greenstone a decade ago, thought their structure smacked of an asteroid impact.

The new research models for the first time how big the asteroid was and the effect it had on the planet, including the possible initiation of a more modern plate tectonic system that is seen in the region, according to Lowe.

The study marks the first time scientists have mapped in this way an impact that occurred more than 3 billion years ago, Lowe added, and is likely one of the first times anyone has modeled any impact that occurred during this period of the Earth’s evolution.

The impact would have been catastrophic to the surface environment.

The smaller, dino-killing asteroid crash is estimated to have released more than a billion times more energy than the bombs that destroyed Hiroshima and Nagasaki.

The more ancient hit now coming to light would have released much more energy, experts said.

Although scientists had previously hypothesized enormous ancient impacts, much greater than the one that may have eliminated the dinosaurs 65 million years ago, researchers have now modelled the power and scale of the cataclysmic event  for the first time

The crator covers an areas 500km wide

The impact may have been one of dozens of huge asteroids that scientists think hit the Earth during the tail end of the Late Heavy Bombardment period, a major period of impacts that occurred early in the Earth’s history – around 3 billion to 4 billion years ago.

The study’s co-authors think the asteroid hit the Earth thousands of kilometers away from the Barberton Greenstone Belt, although they can’t pinpoint the exact location.

'We can’t go to the impact sites. In order to better understand how big it was and its effect we need studies like this,' said Lowe.

The study’s findings have important implications for understanding the early Earth and how the planet formed.

The impact may have disrupted the Earth’s crust and the tectonic regime that characterized the early planet, leading to the start of a more modern plate tectonic system, according to the paper’s co-authors.

The pummeling the planet endured was 'much larger than any ordinary earthquake,' said Norman Sleep, a physicist at Stanford University and co-author of the study.

He used physics, models, and knowledge about the formations in the Barberton greenstone belt, other earthquakes and other asteroid impact sites on the Earth and the moon to calculate the strength and duration of the shaking that the asteroid produced.

Using this information, Sleep recreated how waves traveled from the impact site to the Barberton greenstone belt and caused the geological formations.

The geological evidence found in the Barberton that the paper investigates indicates that the asteroid was “far larger than anything in the last billion years,' said Jay Melosh, a professor at Purdue University in West Lafayette, Indiana, who was not involved in the research.

The Barberton greenstone belt is an area 100 kilometers (62 miles) long and 60 kilometers (37 miles) wide that sits east of Johannesburg near the border with Swaziland. It contains some of the oldest rocks on the planet.

The model provides evidence for the rock formations and crustal fractures that scientists have discovered in the Barberton greenstone belt, said Frank Kyte, a geologist at UCLA who was not involved in the study.

'This is providing significant support for the idea that the impact may have been responsible for this major shift in tectonics,' he said.

@highlight

36 mile wide asteroid is believed to have hit Earth 3.26 billion years ago

@highlight

Collision punched a crater into the planet’s crust 300 miles across

@highlight

Atmosphere filled with dust and the tops of oceans boiled

@highlight

 Back to Mail Online home

@highlight

 Back to the page you came from