A new way of measuring precise distances to galaxies tens of millions of light years away has been developed - using a distant galaxy dubbed the Eye of Sauron.

Researchers accurately measured the distance to the galaxy, formally known as NGC 4151, by comparing the physical size of the dust ring around its black hole with the perceived sized seen from Earth.

And the galaxy - with a distance now known to be 62 million light-years - can be used as a 'cosmic marker' in the universe to work out the distance to other celestial objects.

Scroll down for video 

Scientists have worked out the distance to NGC 4151 (dubbed Eye of Sauron), 62million-light-years, and it can now be used as a distance marker in the universe. Powerful X-rays generated by a super-massive black hole produced the bright blue 'pupil' of the eye, while the red halo around the pupil is made up of hydrogen atoms

One of the major problems in astronomy is measuring very large distances in the universe.

The current, most common methods measure relative distances by using markers known as 'standard candles' - which are stars with a known luminosity whose distance can be measured.

But now research from the University of Southampton and Niels Bohr Institute in Denmark has demonstrated that precise distances can be measured using supermassive black holes.

By combining the light from the two 10-meter Keck telescopes on Mauna Kea on Hawaii using a method called interferometry, the scientists could achieve an effective resolution equivalent to a telescope with a perfect 85-metre diameter mirror.

This provides very high resolution - a hundred times better resolution than the Hubble Space Telescope - and allows them to measure the angle the dust ring of the Eye of Sauron made in the sky.

By now combining data about the observed size of the dust ring on the sky with the known physical size of 30 light days, the distance from the Earth can be calculated by using simple geometry.

'We calculated the distance to be 62 million light-years,' said Dr Darach Watson from the Niels Bohr Institute, who was involved in the research.

'The previous calculations based on redshift [a change in the wavelength of the light due to the velocity of the object away from us] were between 13 million and 95 million light-years, so we have gone from a great deal of uncertainty to now being able to determine the precise distance.

'This is very significant for astronomical calculations of cosmic scale distances.' 

Dr Sebastian Hoenig, from the University of Southampton, created the method which is similar to what land surveyors use on Earth.

It works by measuring the physical and angular, or 'apparent', size of a standard ruler in the galaxy, to calibrate the distance from this information.

The research, which is published in the journal Nature, was used to identify the accurate distance of the 'nearby' NGC 4151 galaxy, which wasn't previously known.

The galaxy NGC 4151, which is dubbed the Eye of Sauron by astronomers for its similarity to the film's depiction of the eye of the character in The Lord Of The Rings, is important for accurately measuring black hole masses.

Indeed, as in the famous saga, a ring plays a crucial role in this new measurement.

All big galaxies in the universe host a supermassive black hole in their centre and, in about a tenth of all galaxies, these supermassive black holes are growing by swallowing huge amounts of gas and dust from their surrounding environments.

In this process, the material heats up and becomes very bright - becoming the most energetic sources of emission in the universe known as active galactic nuclei (AGN).

The hot dust forms a ring around the supermassive black hole and emits infrared radiation, which the researchers used as the ruler.

However, the apparent size of this ring is so small that the observations were carried out using infrared interferometry.

This involved combining the twin 33ft (10 metres) telescopes of the WM Keck Observatory in Hawaii  to achieve the resolution power of a 280ft (85 metres) telescope.

The galaxy NGC 4151 is dubbed the Eye of Sauron by astronomers for its similarity to the film's depiction of the eye of the character in The Lord Of The Rings (shown), and it is important for accurately measuring black hole masses. Indeed, as in the famous saga, a ring plays a crucial role in this new measurement

The measurement was made using the two 33ft (10 metres) Keck telescopes (shown) on Mauna Kea on Hawaii via a method called interferometry. This involved combining the two telescopes to get a resolution power equivalent to a 280ft (85 metres) telescope

To measure the physical size of the dusty ring, the researchers measured the time delay between the emission of light from very close to the black hole and the infrared emission.

This delay is the distance the light has to travel (at the speed-of-light) from close to the black hole out to the hot dust.

By combining this physical size of the dust ring with the apparent size measured with the data from the Keck interferometer, the researchers were able to determine a distance to the galaxy 

Recently reported distances ranged from 13 million to 95 million light-years, but using this new method the researchers now know the galaxy is 62 milion light-years from Earth.

When the gas falls in towards the black hole, it is heated up and emits ultraviolet radiation, which in turn heats up the surrounding dust cloud. Using telescopes on Earth, scientists measured the time difference between the light from the black hole and the light from the dust cloud, 30 days, to work out its distance

Dr Hoenig said: 'One of the key findings is that the distance determined in this new fashion is quite precise - with only about 10 per cent uncertainty.

'In fact, if the current result for NGC 4151 holds for other objects, it can potentially beat any other current methods to reach the same precision to determine distances for remote galaxies directly based on simple geometrical principles.

'Moreover, it can be readily used on many more sources than the current most precise method.'

'Such distances are key in pinning down the cosmological parameters that characterise our universe or for accurately measuring black hole masses.

'Indeed, NGC 4151 is a crucial anchor to calibrate various techniques to estimate black hole masses. Our new distance implies that these masses may have been systematically underestimated by 40 per cent.'

Dr Hoenig, together with colleagues in Denmark and Japan, is currently setting up a new programme to extend their work to establish precise distances to a dozen galaxies in this new way and use them to constrain cosmological parameters to within a few per cent.

In combination with other measurements, this will provide a better understanding of the history of expansion of our universe. 

@highlight

Scientist devised a new method to measure distances in the universe

@highlight

He worked out the distance to NGC 4151 - dubbed the 'Eye of Sauron'

@highlight

This spiral galaxy has a supermassive black hole at its centre 

@highlight

By comparing its actual size to its 'observed size' the galaxy was found to be 62 million light-years away

@highlight

NGC 4151 can now be used as a so-called cosmic distance marker

@highlight

And more than a dozen galaxies will be measured with the new method

@highlight

This could provide more information on the history of the universe

@highlight

Measuring distances in the universe is difficult and usually relies on 'standard candles' - stars whose distances are already known 