By
Associated  Press Reporter

PUBLISHED:
  
  
      08:42 EST, 24 December 2013
    
  
 | 
  UPDATED:
  
  
      14:50 EST, 24 December 2013

Astronauts have wrapped up urgent space station repairs during a rare Christmas Eve spacewalk, braving a 'mini blizzard' of noxious ammonia as they popped in a new pump.

It was the second spacewalk in four days for U.S. astronauts Rick Mastracchio and Michael Hopkins, and only the second Christmas Eve spacewalk in NASA history.

NASA ordered up the spacewalks to revive a critical cooling loop at the International Space Station.

Scroll down for video

No turkey for Christmas: Astronauts Rick Mastracchio (top) and Michael Hopkins spend their Christmas Eve repairing an external cooling line on the International Space Station

One small step for man...: Astronauts Mike Hopkins (on the robotic arm, lower right) and Rick Mastracchio (front) take a rare spacewalk outside the International Space Station (ISS)

All nonessential equipment had to be turned off when the line conked out on December 11, and many science experiments halted.

With today's success, the cooling system should be restored and all equipment back up and running by this weekend, according to NASA.

Mastracchio and Hopkins removed the faulty ammonia pump during Saturday's outing. On Christmas Eve, they installed the fresh pump.

Standing on the end of the station's main robotic arm, Hopkins clutched the 780-pound, refrigerator-size pump with both hands as he headed toward its installation spot, and then slid it in.

An astronaut working inside, Japan's Koichi Wakata, gingerly steered the arm and its precious load.

'Mike Hopkins taking a special sleigh ride on this Christmas Eve,' Mission Control commentator Rob Navias said as the space station soared over the Pacific.

It was slow going because of a balky ammonia fluid line that sent frozen flakes of the extremely toxic substance straight at the men - 'a mini blizzard,' as Mission Control called it.

The spacewalkers reported being surrounded by big chunks of the stuff that bounced off equipment and, in all probability, their suits.

The ammonia needed to dissipate from their suits before the pair returned inside, to avoid further contamination.

Flying high: 'It's like Christmas morning opening up a little present here,' astronaut Rick Mastracchio (top) said as he checked his toolkit

Zero gravity: Astronaut Mike Hopkins lies against the robotic arm during a spacewalk outside the International Space Station

'Wow,' Hopkins sighed after the fourth and final fluid line was hooked to the new pump.

The electrical hookups went more smoothly, and six hours into the spacewalk, Hopkins finally called down, 'Houston, you've got yourself a new pump module'.

Christmas references filled the radio waves, as the action unfolded 260 miles above the planet.

'It's like Christmas morning opening up a little present here,' Mastracchio said as he checked his toolkit.

Later, as he worked to remove the spare pump from its storage shelf, he commented: 'Now it really feels like I'm unwrapping a present.'

Mission Control in Houston was in a festive mood, despite the gravity of the situation. Tabletop Christmas trees, Santa dolls and red Santa caps decorated the desks.

NASA's only previous Christmas Eve spacewalk occurred in 1999 during a Hubble Space Telescope repair mission.

But NASA's most memorable Christmas Eve was back on December 24, 1968.

Apollo 8 astronauts read from Genesis, the first book of the Bible, as they orbited the moon on mankind's first lunar flight.

Lost in space: The Christmas Eve venture was the second spacewalk in four days for U.S. astronauts Rick Mastracchio and Michael Hopkins

A bad valve in the ammonia pump caused the latest breakdown.

Another team of spacewalking astronauts installed that pump just three years ago, and engineers are perplexed as to why it didn't last longer. NASA hopes to salvage it in the years ahead.

The 2010 replacement required three spacewalks because of the difficulty in removing pressurized ammonia fluid lines. But this time, the astronauts managed to squeeze everything into two after NASA reduced the pressure and simplified the task.

Mission Control planned to wait until Tuesday evening before fully activating the new pump, but initial testing showed everything working well.

The two-line cooling system uses ammonia to dispel heat generated by on-board equipment; only one loop was disabled by the breakdown.

Busy: NASA astronaut Michael Hopkins work to repair an external cooling line on the International Space Station on a spacewalk 260 miles above Earth on Saturday

The second spacewalk was supposed to 
take place on Monday, but it was delayed a day to give Mastracchio time 
to switch to another suit.

He
 inadvertently hit a water switch in the air lock at the end of 
Saturday's excursion, and a bit of water encroached on a cooling device 
in the backpack of his suit, making it unusable.

Otherwise, the suits remained dry during both spacewalks.

Last
 July, an astronaut almost drowned when water from his suit's cooling 
system flooded his helmet. Makeshift snorkels and absorbent pads were 
added to the suits as a precaution.

A Moscow-led spacewalk, meanwhile, is set for Friday.

Two Russian crew members will install new cameras and fresh experiments outside.

@highlight

NASA astronauts Rick Mastracchio and Michael Hopkins ventured out of the International Space Station to repair a cooling system on December 24

@highlight

It was the second Christmas Eve spacewalk in NASA history, the first was in 1999

@highlight

NASA says all equipment should be up and running by the weekend