The government and London Legacy Development Corporation (LLDC) agreed to allow West Ham to bank all of the revenues from executive boxes and corporate hospitality under the terms of the 99-year lease they were awarded to move into Olympic Stadium - at a cost of millions of pounds a year to the taxpayer.

It has been confirmed that the government agreed to demands by the Hammers to retain 100 per cent of the corporate cash generated from 16 ‘super boxes’ and a wide range of executive packages.

The key element of the deal was revealed by the European Commission (EC) to The Charlton Athletic Supporters' Trust. The Trust is also trying to force LLDC to reveal the exact details of the rental contract between the LLDC and West Ham, amid concerns the Hammers move may impact negatively on local clubs such as Charlton and Millwall.

An artists impression shows what the Olypic Stadium could look like in West Ham's colours

(From left to right) West Ham chairman David Sullivan, London Mayor Boris Johnson, Hammers chief executive Karren Brady, Newham Mayor Robin Wales and West Ham chairman David Gold in front of the Olympic Stadium in 2013

The Olympic Stadium will contain 3,400 premium priced seats compared to Upton Park, which has less than 2,000 VIP seats. The Olympic Stadium will also have double the number of VIP lounges of Upton Park, to enable the Hammers a substantial uplift on the £18million a year in revenues the club currently generates from match days.

The EC has also confirmed that LLDC has agreed to reduce the estimated £2m a year rent West Ham will pay to use the 54,000-seat stadium if they are relegated to the Championship and that The Hammers won’t be required to pay £15m towards the stadium until they have completed the sale of Upton Park to London developer Galliard Group for an undisclosed amount.

Artist's impression of what the stadium could look like from the inside after West Ham move there in 2016

West Ham will start playing in the Olympic Stadium from the start of the 2016-17 season

West Ham and LLDC have agreed to share the revenues from match day tickets and catering, as well as any revenues generated from a potentially multi-million pound stadium naming rights deal yet to be announced.

The Hammers were awarded the 99-year lease by the LLDC to become anchor tenants of the Olympic site from August 2016.

 

@highlight

West Ham will move to the Olympic Stadium for  start of the 2016 season

@highlight

Club will bank all the revenue generated by corporate and executive seats

@highlight

But will share other match day ticket and catering revenue with LLDC 