By
Daily Mail Reporter

PUBLISHED:
  
  
      01:30 EST, 30 December 2013
    
  
 | 
  UPDATED:
  
  
      12:28 EST, 30 December 2013

A new study has found that over 60 percent of website visitors aren't people at all, but bots.

Web security company Incapsula has found that the bots make up much more of any given site's traffic than they did just last year.

Able to do all sorts of tasks for the people who create them, internet bots can bring with them data-stealing malware, viruses and even turn your computer into a spam-making machine.

Incapsula analyzed nearly 1.5 billion page views from its clients' over 20,000 websites over three months.

Bots: Internet bots make up 61.5 percent of website traffic, according to a new study

They found that 61.5 percent of those visits were generated by bots.

Incapsula registered 1.45 billion bot visits in traffic from nearly every world country.

Internet bots are created and employed for different uses.

They can be used to artifically gin up traffic to a site, thereby increasing its apparent value for advertisers.

Nefarious? According to web security firm Incapsula, potentially malicious bots account for 26 percent of non-human traffic

They may also be used as a means of hacking into data stored on the site such as users' credit card number or to turn a website into a malware spreading machine.

Bots can also refer to search engine crawlers that trawl the web for info in order to better serve their users.

According to Incapsula, around 31 percent of bots are the good search engine kind.

Meanwhile, malicious bots made up a little less of the bot traffic at 26 percent.

Bot traffic is nothing new and has been worried over for years.

However, the study also found that bot traffic is up 21 percent from 2012.

Are you at risk? The malicious bots can be broken down into four types, each of which are designed to carry out nasty deeds like steal credit card data or to create spam

@highlight

A study found that 61.5% of traffic on 20,000 different sites was non-human

@highlight

Human traffic made up only 38.5% of traffic, according to web security company Incapsula

@highlight

Called bots, the non-human web visitors are up a whopping 21 percent 2012