By
Sarah Griffiths

Listening to local radio can cause robins to lose their way.

Biologists have proved that the electromagnetic ‘noise’ from AM radio transmitters interferes with the Earth’s magnetic field, which migratory birds use to navigate.

The problem is thought to affect birds in urban areas more as there is less interference in the countryside.

Lost in music: Biologists have proved that the electromagnetic 'noise' from AM radio transmitters interferes with the Earth's magnetic field, which migratory birds such as robins (pictured) use to navigate

The study led by Professor Henrik Mouritsen of the University of Oldenburg, Germany, has proved for the first time that the magnetic compass of robins fails entirely when the birds are exposed to AM radio waveband electromagnetic interference - even if the signals are just a thousandth of the limit value defined by the World Health Organisation (WHO) as 'harmless'.

The findings, published in the journal Nature, are based on seven years of research by the scientists, in cooperation with Professor Peter Hore of Oxford University.

‘In our experiments we were able to document a clear and reproducible effect of human-made electromagnetic fields on a vertebrate,’ Professor Mouritsen said.

‘This interference does not stem from power lines or mobile phone networks’ but is generated by electronic devices like AM radio transmitters.

‘The effects of these weak electromagnetic fields are remarkable: they disrupt the functioning of an entire sensory system in a healthy higher vertebrate.’

Expert navigators: It has been known that migratory birds navigate the planet using the Earth¿s magnetic field to find their way for around 50 years. Biologists have proven this in numerous experiments in which they tested the birds' navigation abilities in so-called orientation cages

It has been known for 50 years that migratory birds navigate the planet using the Earth’s magnetic field. Biologists have proved this in numerous experiments in which they tested the birds' navigation abilities in so-called orientation cages.

‘So we were surprised when robins kept in wooden huts on the Oldenburg University campus were unable to use their magnetic compass,’ Professor Mouritsen said.

Dr Nils-Lasse Schneider, an electrophysiologist proposed covering the wooden huts, along with the orientation cages they contained, with sheets of aluminium to see if this made a difference.

It did not affect the Earth's magnetic field, which is vital for the birds to navigate, but it greatly reduced the electromagnetic interference – also known as electrosmog – inside the huts. The scientists found that the birds' orientation problems disappeared.

‘Our measurements of the interferences indicated that we had accidentally discovered a biological system that is sensitive to anthropogenic electromagnetic noise generated by humans in the frequency range up to five megahertz,' Professor Mouritsen explained.

Scrambled compass: The electromagnetic broadband interference is present in all urban environments, presenting a navigational challenge to migratory birds (pictured). The problem lessened in rural areas so the issue is localised

He was surprised that the intensity of the interference was far below the limits defined by the International Commission on Non-Ionizing Radiation Protection and the WHO.

The team performed a large number of experiments to explore the effect that they observed.

‘Over the course of seven years we carried out numerous experiments and collected reliable evidence in order to be absolutely certain that the effect actually exists,’ Professor Mouritsen said.

Students conducted the same experiments without knowledge of previous results and proved that as soon as electromagnetic interference was deliberately created inside the aluminium-clad and earthed wooden huts, the birds' magnetic orientation ability was immediately lost again.

The scientists were able to show that the disruptive effects were generated by electromagnetic fields that cover a much broader frequency range at a much lower intensity than previous studies had suggested.

And this electromagnetic broadband interference is present in all urban environments, presenting a navigational challenge to migratory birds. The problem lessened in rural areas so the issue is localised.

‘However these findings should make us think – both about the survival of migratory birds as well as about the potential effects for human beings, which have yet to be investigated,’ Professor Mouritsen said.

@highlight

Scientists from the University of Oldenburg, Germany, said electromagnetic noise from AM radio transmitters affects migratory birds

@highlight

They proved that the magnetic compass of robins fails entirely when the birds are exposed to AM radio waveband electromagnetic interference

@highlight

Robins in urban areas are worst affected as the 'noise' is loudest