By
David Mccormack

A storm chaser is lucky to be alive after he was struck by lightning while filming an approaching front on Tuesday.

Scott Sheppard was chasing storms in western South Dakota near Fairburn, about 30 miles south of Rapid City, when the incident happened.

He had parked his vehicle on the side of Highway 79 and was shooting footage from inside his car when he got hit.

Scott Sheppard was chasing storms in western South Dakota near Fairburn, about 30 miles south of Rapid City, when he was struck by lightning while filming an approaching storm on Tuesday

Sheppard had parked his vehicle on the side of Highway 79 in South Dakota and was shooting footage from inside his car when he got hit by lightning

The video initially shows a scene of eerie calm - there¿s even a rainbow in the sky - just before the lightning strike

The video initially shows a scene of eerie calm - there’s even a rainbow in the sky - just before the lightning strike.

The bolt of lightning struck Sheppard's arm and continued down to the ground - blowing a hole in the road.

Sheppard's camera is suddenly pointing directly up at the sky and a cloud of smoke can be seen from the crater left in the ground.

Fortunately for Sheppard, he wasn’t too badly hurt and escaped with just a sore arm.

The camera is suddenly pointing directly up at the sky and a cloud of smoke can be seen from a crater left in the ground

Fortunately for Sheppard, he wasn't too badly hurt and was able to photograph the damage left behind by the strike

According to the CDC, 100 people are killed by lightning every year in the U.S.; however 90 percent of victims, like Sheppard, survive

He was able to photograph the damage left behind by the strike including a number of marks on the road.

Unfortunately his car didn’t fare so well and had to be towed away.

According to the Centers for Disease Control, 100 people are killed by lightning every year in the U.S. However 90 percent of victims - like Sheppard - survive.

Video: Storm chaser hit by lightning

@highlight

Scott Sheppard was chasing storms in western South Dakota when he got hit as he was shooting video from inside his car

@highlight

Sheppard's footage initially shows a scene of eerie calm - there's even a rainbow in the sky - just before the lightning strikes

@highlight

A bolt of lightning strikes Sheppard's arm and continues down and blows a hole in the road

@highlight

The video footage captures a cloud of smoke generated by the crater