She’s known for her love of fast cars as host of BBC's Formula One coverage, but even Suzi Perry was impressed when called in to start up the four mighty engines of Britain’s largest cruise ship, P&O Cruises’ Britannia, for the first time.

When working to full capacity, Britannia’s four engines will generate 62.4 Megawatts or 84,000 horsepower - equivalent to the power generated by 168 'supercars', or 1,000 normal family cars. 

'[It is] a little bit more horsepower than I'm used to... 84,000, it's incredible!' Perry said after turning the engines over. 'When I first came into the dock I couldn't believe how big it is.'

The 141,000 ton ship will cruise at a speed of 22 knots when it hits the water in March next year.

The boat is being built at the Fincantieri’s Monfalcone shipyard near Trieste in Italy.

 Britannia will launch in March 2015, before her maiden season which will see the ship sail from Southampton to the Mediterranean, the Norwegian Fjords, the Canary Islands and the Baltic Sea.

The ship, which will also offer a range of short breaks and a round Britain cruise, will then transfer to the Caribbean for the winter season, sailing a range of 15 night fly/cruise itineraries from Barbados. 

It's so big: BBC Formula One host Perry marvelled at the size and power of the engines

Start me up! Suzi Perry switches on the engines of the UK's biggest cruise ship, Britannia, for the first time

Guided tour: Captain Paul Brown gives the F1 presenter a guided tour of the engine room of the ship

Perry was treated to a tour of the ship and its engine room with Captain Paul Brown, and the video of her visit gives an idea of the size and capacity of this enormous ship.

P&O Cruises is launching a national campaign to discover what or who people across the country believe embodies the spirit of modern Britain.

The most popular suggestions received via twitter and Facebook will be incorporated into two pieces of artwork which will be installed on  Britannia.

@highlight

Suzi Perry started engines of P&O's Britannia, Britain’s largest cruise ship

@highlight

Britannia’s four engines are powerful as 168 supercars or 1,000 normal cars

@highlight

The 141,000 ton ship will hits the water in March 2015